### ISSUE TITLE
better support for private var

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva#100]
If on namespace ns1 I have the following vars
```
(def foo :foo)
(def ^:private bar :bar)
```
trying to evaluate (with `ctrl+shift+v SPC`) them in the namespace ns2 return the following
```
ns1/foo  => :foo
#'ns1/bar => ns1/bar        <- instead of the expected :bar
```

Another problem with private vars is with the `Go to definition`. It can't find the var when prefixed by `#'`, similar to the issue reported on https://github.com/BetterThanTomorrow/calva/issues/98

**Comment by PEZ** [comment]
Hello and thanks for reporting!

Good finds. I'll investigate what the fix should be for the go to definiton.

Wondering about this:
```clojure
#'ns1/bar => ns1/bar        <- instead of the expected :bar
```
It seems the evaluation also misses the `#`. But if it didn't I would expect it to evaluate to `#'ns1/ba`. What happens when you evaluate it in the terminal repl? (Not using the Calva commands for it. because that will also miss the `#`).

**Comment by claynon** [comment]
Sorry, I messed up a bit.
The eval of `#'ns1/bar` is correct because bar is a var not a fn. `#'` is the syntax to access a private fn, not a var.
The syntax for accessing a private var of another namespace is `@#'` (since `#'` returns the var and the `@` derefs it)
But the problem is the same
```
@#'ns1/bar => ns1/bar
```

Looking at the color change when I eval `@#'ns1/bar` it seems that the problem is what you said (ignoring what is before the `'`)

----
when I define a private fn `baz` in ns1 and try to eval it in another namespace using `#'ns1/baz` I get the correct result :tada:
But the problem with the go to definition is the same (probably cause by the ignoring things before `'` too)

----
Thank you very much for the quick feedback and fix. I hope I manage to free some time to help with some code here too

**Comment by bpringe** [comment]
This seems to work now. Closing, but reopen if I missed something.
