### ISSUE TITLE
Calva setting to use only static parts

### ISSUE THREAD

**Issue by ericdallo** [BetterThanTomorrow/calva#1005]
It was an idea discussed with @PEZ [here](https://clojurians.slack.com/archives/CPABC1H61/p1612181210149200), where may have users that like Calva features like `clojure-lsp` integration but don't like the REPL or prefer another tool as the REPL.
Calva would reach those users if it could have a setting where it'd disable the REPL feature/keybindings etc (Probably in the future, extract it to other dep/extension?)

Just an idea though, I don't think it should be a priority too ;)

**Comment by PEZ** [comment]
Thanks. Makes sense to me. It shouldn't be all that much work to at least make the REPL take a bit less room in the UI when this option is active.

**Comment by PEZ** [comment]
Implemented!
