### ISSUE TITLE
Built-in tap current form.

### ISSUE THREAD

**Issue by clyfe** [BetterThanTomorrow/calva#1008]
This ticket is for designing/approving a built-in tap current form `calva.tapCurrentForm`.
`Alt+Shift+Enter` seems to be free, I propose it as keybinding.

Should we have tap top level form?
Related: https://github.com/seancorfield/vscode-clover-setup/blob/develop/keybindings.json

**Comment by PEZ** [comment]
I agree. And probably we should have top level as well.

But let's ponder it all a bit...

Those `args` in the keybindings you link to intrigue me. If we create a `tap` command that takes arguments, and we make the same variables available to those arguments as we do with our current [custom commands](https://calva.io/custom-commands/). Then we can bind keyboard shortcuts that tap anything we have defined variables for (and also code using the variables). We could then provide a few default shortcuts for obvious things like `$current-form` and `$top-level-form`. And the users can go crazy with it as well.

In fact we can take it a step further, I think... We can create a command that evaluates whatever `args` provided. And then provide default shortcuts with `args` like `(tap> $current_form)`.

What'ya'think, @clyfe?

CC: @sauvala

**Comment by clyfe** [comment]
Clover embeds sci, and correlates those args strings with functions in this little script here: https://github.com/seancorfield/vscode-clover-setup/blob/develop/config.cljs

On topic: yes I like the plan with the [args](https://code.visualstudio.com/docs/getstarted/keybindings#_command-arguments).
