### ISSUE TITLE
Calva Jack-in process exited

### ISSUE THREAD

**Issue by pratik97** [BetterThanTomorrow/calva#1013]
I am on my macbook in VSCode and when I try to jack-in using Start REPL and connect option it fails with this error:
```
lein update-in :dependencies conj '[nrepl,"0.8.3"]' -- update-in :plugins conj '[cider/cider-nrepl,"0.25.8"]' -- update-in '[:repl-options,:nrepl-middleware]' conj '["cider.nrepl/cider-middleware"]' -- repl :headless
/bin/sh: lein: command not found
Jack-in process exited. Status: 127
```
I have already installed leiningen and it's in my PATH variable and I can access the lein command from anywhere. I also checked the option of "Connect to a REPL running in your project" and that works fine, but I just have to start a REPL myself and enter port there.

**Comment by PEZ** [comment]
Hi! It is probably that VS Code is started with an environment that doesn't have `lein` in the path.

Try with starting VS Code from a terminal.

**Comment by pratik97** [comment]
Hi, tried that and it worked! Happy to close this issue. ~~Just that if we can make this more explicit in the docs(https://calva.io/connect/) it would be great!~~. Eh, I don't think it is that common of an issue :)

**Comment by PEZ** [comment]
It's actually already there, but not easy to find anyway: https://calva.io/connect/#environment-variables-are-not-readable-from-repl

I'll see if I can word it better.

**Comment by bpringe** [comment]
I would probably make it a separate troubleshooting header. The solution is the same and maybe the problem is really the same, but the users may come across it differently (env vars not readable from repl is one way, lein not found is another).

**Comment by PEZ** [comment]
Like this? https://calva.io/connect/#troubleshooting

**Comment by bpringe** [comment]
Looks good to me. What is this / how is it run?

> You might need to first run the Shell Command: Install code command in PATH

**Comment by PEZ** [comment]
It's a VS Code command, you run it from the command palette.

**Comment by bpringe** [comment]
Weird, I don't see it:

![image](https://user-images.githubusercontent.com/12722744/107096120-dd595b00-67be-11eb-9866-20855d503f0f.png)
