### ISSUE TITLE
Demo gifs 404 in README on VisualStudio Marketplace

### ISSUE THREAD

**Issue by jonoflayham** [BetterThanTomorrow/calva#1018]
The excellent animated demo GIFs in the README aren't being rendered on Calva's [VisualStudio Marketplace page](https://marketplace.visualstudio.com/items?itemName=betterthantomorrow.calva), because there's still a reference to the `master` branch lurking somewhere.

**Comment by PEZ** [comment]
Oh, how strange. Investigating it now. Thanks for reporting!

**Comment by PEZ** [comment]
Seems there is a an option on `vsce` for this: https://github.com/microsoft/vscode-vsce/issues/514

**Comment by jonoflayham** [comment]
Ah, cool - makes sense.  btw I noticed the URL for the Calva logo is absolute, and points to the `dev` branch.

**Comment by PEZ** [comment]
Now works. Thanks again for the heads up, @jonoflayham !

**Comment by jonoflayham** [comment]
Pleasure, @PEZ!  I'm looking forward to using it, and thanks for the fantastic work.
