### ISSUE TITLE
Add eval-defun-to-comment functionality 

### ISSUE THREAD

**Issue by ghost** [BetterThanTomorrow/calva#102]
Cider in Emacs has an eval-defun-to-comment function (C-c M-; if you want to explore) that will allow you to evaluate an expression and leave the result as a comment either to the right of the expression or below it as space permits. I find this great as I learn as it allows me to look at old code I wrote and immedietely see an example of how it works. 

I believe I found the source code for this function here if that helps: https://github.com/clojure-emacs/cider/blob/b85848b1b840d6e1ca60817b2cf34788e688057e/cider-eval.el#L707

I was thinking of something like C-M-;  to mirror cider a bit. I personally am trying to use the keybindings that would make it something like M-; because how easy is that! Not sure if that has any conflicts though and haven't found the equivalent of the ole handy Emacs C-h k functionality in vs code yet to check.

**Comment by chasote** [comment]
Actually I guess to stay consistent with Calva's keybindings it would be C-M-v ; which I would change per WebWitch's keybindings to M-v ;

**Comment by PEZ** [comment]
We'll get here, @chasote . There are just a couple of other things in flux right now, so I don't want to start this before we've stabilized things.

**Comment by PEZ** [comment]
This has been added in the most basic form. Please try it out and please feel welcome to file new requests on this feature's improvement.
