### ISSUE TITLE
Text selection - intended behaviour?

### ISSUE THREAD

**Issue by sauvala** [BetterThanTomorrow/calva#1022]
Hi!

Noticed this behaviour when selecting text. Is it intended that I can extend the selection from "both ends" but the selection cannot grow past expressions/strings? Haven't seen this kind of behaviour before in other text editors. I'm using macos and I'm selecting text with option+shift+arrowkey.

![calva-text-selection](https://user-images.githubusercontent.com/4200280/107289457-b96f7100-6a6d-11eb-93c4-df184551c7c2.gif)

**Comment by bpringe** [comment]
It won't keep expanding after that point? That's odd if so. For me it keeps expanding. This is using the "Expand selection" command via `shift+alt+rightArrow` (linux).

![expand-selection](https://user-images.githubusercontent.com/12722744/107292356-8b167500-6a1e-11eb-8364-e4608a8e0e4f.gif)

**Comment by PEZ** [comment]
On Mac `option+shift+left/right` are bound to *select sexpr backward/forward*. They won't select outside the current list as their movement ”buddies” wouldn't move outside either. To keep selecting forward you will need to *select forward up*. To expand the selection to the next level (the whole list, then the contents of the outer list, and so on) use `ctrl+w`.

I think there is an issue somewhere that asks for *select backward* to undo forward selections (and vice versa) which would be more consistent with how ”regular” selection expansion works.

**Comment by sauvala** [comment]
Thanks for explaining this. After the initial shock this makes sense to have text selection to work like it should in LISPs. 👍
