### ISSUE TITLE
Translate clojure-lsp integration to cljs

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1025]
This is something I want to play around with to see what it's like to use cljs, not just for core functionality but also integration. The lsp related code is pretty sectioned off, not too large, and is my current area of work, so I think it's a good candidate.

**Comment by bpringe** [comment]
This may just be my unfamiliarity with this area of shadow-cljs, but I haven't yet figured out how to use the typescript modules from cljs, like `state` and `utilities`, which I think is pretty important we're to use cljs more extensively and incrementally (no big rewrites).

https://github.com/thheller/shadow-cljs/issues/841

**Comment by PEZ** [comment]
It might be that there is some minimum big rewrite we need to do. Both the modules you mention, `utilities` and `state`, are pretty horrible sinks for all kinds of functions...

I think we need to start with figuring out the dependency graph as it is today, and what it needs to look like to do some incremental porting TS->CLJS of the kind you are aiming for here, @bpringe .

Speculation: As the central functionality of the `state` module is provided by `Immutable.js` it might be somewhat in reach to move it down to the CLJS library and use an atom or something there instead.

**Comment by bpringe** [comment]
>As the central functionality of the state module is provided by Immutable.js it might be somewhat in reach to move it down to the CLJS library and use an atom or something there instead.

Exactly what I've been thinking! I agree about possibly rewriting some things and rearranging some deps. I do want to continue to try a bit more without doing that though. Thomas provided some great info here that might allow us to avoid a large-ish rewrite: https://github.com/thheller/shadow-cljs/issues/841#issuecomment-778083341

But yeah, it may be necessary to rewrite some things. I do love the idea of using an atom for state :smile:.

**Comment by PEZ** [comment]
I made some experiments using `citrus` for state, back when we were planning on rewriting Calva in cljs completely. Might not be a good idea, but there is something with the subscription/dispatch model that lure me in. =) https://github.com/PEZ/calva-legacy/tree/citrus2/src/main

**Comment by bpringe** [comment]
One other thing to try is to make the TS compiler use `./out` as it's base directory. I forgot the setting but I saw this recently. So import paths will be searched from that point. Then the TS import path can be the same as the path shadow wants in require statements, looking in the classpath (if `out` is on the classpath).

**Comment by bpringe** [comment]
Released in 2.0.174. Must have forgotten to link this issue in a commit message.
