### ISSUE TITLE
re-frame project with shadow-cljs + deps.edn: Can't jack-in

### ISSUE THREAD

**Issue by n2o** [BetterThanTomorrow/calva#1032]
Hey there,

thanks for this great project. I really like it and want to use it a lot more, but there is currently a problem when I try to jack-into my project.

Setup: Clojure backend + ClojureScript frontend. shadow-cljs is used for the frontend. Backend fires the API.

Then, I want to jack into my project:

`Calva: Start a Project REPL and Jack In` > `deps.edn + shadow-cljs` > selecting an alias to launch with `dev-local` > selecting a shadow-cljs build `:app` > Error

The following log appears in the `output.calva-repl`:

```
; Jacking in...
; nREPL Connection was closed
; Starting Jack-in Terminal: clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.8.3"},cider/cider-nrepl {:mvn/version,"0.25.8"}}}' -A:dev-local -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
; Hooking up nREPL sessions...
; Connected session: clj
; TIPS: 
;   - You can edit the contents here. Use it as a REPL if you like.
;   - `alt+enter` evaluates the current top level form.
;   - `ctrl+enter` evaluates the current form.
;   - `alt+up` and `alt+down` traverse up and down the REPL command history
;      when the cursor is after the last contents at the prompt
;   - Clojure lines in stack traces are peekable and clickable.
clj꞉user꞉> 
; Creating cljs repl session...
; Connecting cljs repl: deps.edn + shadow-cljs...
;   The Calva Connection Log might have more connection progress information.
; Execution error (ClassNotFoundException) at java.net.URLClassLoader/findClass (URLClassLoader.java:435).
shadow.cljs.devtools.api
; Error while connecting cljs REPL: TypeError: Cannot read property 'search' of undefined
; Jack-in done.
clj꞉user꞉> 
```

If I jack-in using the option `shadow-cljs` (without the "deps.edn" part), shadow-cljs starts as expected and everything is fine. But I need the additional alias `dev-local` to start my API, because there are additional dependencies, which are needed for the API. And I also need the REPL for my Clojure-Backend for development.

In Cursive, I start two separate REPLs and switch between the REPLs. But I want to switch from Cursive to Calva, but this is just one crucial part for my current project, which I need to fix :D

My shadow-cljs.edn looks like this:

```
{:deps true
 :nrepl {:port 8777}
 :builds {:app {:target :browser
                :modules [...]
                :output-dir "resources/public/js/compiled"
                :asset-path "/js/compiled"
                :dev {:compiler-options {:closure-defines {re-frame.trace.trace-enabled? true}}}
                :release [...]
                :devtools {:http-root "resources/public"
                           :http-port 8700
                           :preloads [devtools.preload day8.re-frame-10x.preload]}}}}
```

And my deps.edn provides an Alias allowing to use dev-local:

```
{:paths ["src/main" "src/test"]
 :aliases {:dev-local
           {:extra-deps {com.datomic/dev-local {:local/root "local_jars/dev-local/dev-local.jar"}}}}}
```

Any ideas on this?  I have no idea where to find more information, and I am currently surprised by the output on the console pointing to `shadow.cljs.devtools.api`. 

Everything works in this project as expected. I am using the following versions:

* Clojure 1.10.2
* shadow-cljs 2.11.15
* Calva 2.0.172
* VSCodium Version: 1.53.2
  * Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
  * Date: 2021-02-12T00:30:20.237Z (2 days ago)
  * Electron: 11.2.1
  * Chrome: 87.0.4280.141
  * Node.js: 12.18.3
  * V8: 8.7.220.31-electron.0
  * OS: Darwin x64 20.3.0
* macOS Big Sur 11.2.1

**Comment by PEZ** [comment]
Hello. I'm sorry this is causing you troubles. I think this `deps.edn + shadow-cljs` jack-in option might be a bit broken actually. It's late here now, I'll have a look tomorrow and see if I can make sense of it.

Meanwhile. Since you start two REPLs in Cursive. Calva doesn't support that directly, but you can open the same project in two different Workspaces and start a REPL in each of them. See https://calva.io/workspace-layouts/. Not sure it helps you, but anyway, throwing it out here.

**Comment by n2o** [comment]
Thanks for the quick reply, using two workspaces is okay in the beginning :)

You can always contact me to get more information about full stack clojure/script projects. Loving this project, hope it supports fullstack apps with shadow-cljs in the future :)

**Comment by PEZ** [comment]
You are welcome, and thank you for the support you express!

We should definitely try to fix this.

For the record: Fullstack dev wiith shadow-cljs frontend currently works for some setups. I know `lein-shadow` works, see https://calva.io/luminus/ about that. I've also had reports that the Fulcro workflow is nice. Not sure what else was involved there (wether it was deps.edn or some other setup), I should try to figure out. Maybe the answer to the OP lurks there...

**Comment by PEZ** [comment]
Don't know if you are member of the `#calva` channel over at the Clojurian's Slack, @n2o . In any case, there was a recent question about deps.edn + shadow (with Fulcro involved, but I don't think that should matter). This config was posted there and the dev who had the problem seemed super happy about it:

```clojure
:aliases
 { :ui
  {:extra-deps {thheller/shadow-cljs {:mvn/version "2.11.15"}}}
  :watch
  {:main-opts ["-m" "shadow.cljs.devtools.cli"
               "watch" ":frontend"]}
```

Does this help you?

**Comment by n2o** [comment]
Indeed, it helps in a minimal project I just built (not in my real project, but there seems to be a different problem). I published the code here: https://github.com/DisqTecCom/full-stack-clojure-sample

The solution you are describing works as expected: Jack-in > Use 'deps.edn' > check required aliases, including the `watch` alias to enable shadow-cljs > it works 🚀

Thanks for your help, I'll figure out in the next days what the problem in my project is.

**Comment by n2o** [comment]
Finally, I got my project to work with Calva even with the proposed `deps.edn + shadow-cljs` configuration. There were two different problems. 

First, I needed to add `com.google.guava/guava {:mvn/version "30.1-jre"}` to my deps.edn file, because shadow-cljs and datomic are using different versions of guava and the combination crashes (see [shadow-cljs channel in slack](https://clojurians-log.clojureverse.org/shadow-cljs/2018-06-10))

Second, we are using Datomic dev-local, which is currently installed via deps.edns' `local/root` method. This results in the fact, that Calvas REPL does not find the artifact and therefore fails to start my Clojure-Namespace. 

So there seems to be a problem with the Classpath with in `deps.edn + shadow-cljs`. I fixed it by using Cognitect's `install` file, which installs the artifacts into my local .m2 directory, I suppose. Maybe the last part is worth of further investigation, or what do you think @PEZ?

**Comment by muhajirdev** [comment]
is this issue fixed yet? sorry I am new to clojure & calva

**Comment by bpringe** [comment]
Hey @muhajirdev. Are you having a similar issue as the above, and did the above info not help you get it to work?

Pinging @PEZ about your question, @n2o.

**Comment by bpringe** [comment]
@muhajirdev I see now that you and @pez followed up elsewhere.
