### ISSUE TITLE
Comment to see "hello-paredit.clj" should be "hello_paredit.clj" based on named file

### ISSUE THREAD

**Issue by rbeesley** [BetterThanTomorrow/calva#1037]
https://github.com/BetterThanTomorrow/calva/blob/276339cc5a3c63f17330bfdbe968e5041348c165/bundled/hello_repl.clj#L48

Looks like the files are named using snake_casing, and the comment is using kebab-casing. Just need to conform to one or the other. Changing from kebab to snake is probably easier as there is less to change only in the comment.

**Comment by PEZ** [comment]
This is fixed, I think. And the guides have moved. 😄  https://github.com/BetterThanTomorrow/dram
