### ISSUE TITLE
Calva commands should also list the default keyboard shortcuts where appropriate

### ISSUE THREAD

**Issue by rbeesley** [BetterThanTomorrow/calva#1038]
https://github.com/BetterThanTomorrow/calva/blob/276339cc5a3c63f17330bfdbe968e5041348c165/bundled/hello_paredit.clj#L33

Someone seeing this for the first time is not going to likely understand that this is Ctrl+Shift+P, calva paredit: expand selection. It is still valuable to inform the user what the command is, but I suggest also including Shift+Alt+RightArrow to encourage learning the key strokes, muscle memory, and what these commands will do.

See also:
https://github.com/BetterThanTomorrow/calva/blob/276339cc5a3c63f17330bfdbe968e5041348c165/bundled/hello_paredit.clj#L42
https://github.com/BetterThanTomorrow/calva/blob/276339cc5a3c63f17330bfdbe968e5041348c165/bundled/hello_paredit.clj#L44-L45
https://github.com/BetterThanTomorrow/calva/blob/276339cc5a3c63f17330bfdbe968e5041348c165/bundled/hello_paredit.clj#L51
https://github.com/BetterThanTomorrow/calva/blob/276339cc5a3c63f17330bfdbe968e5041348c165/bundled/hello_paredit.clj#L53
https://github.com/BetterThanTomorrow/calva/blob/276339cc5a3c63f17330bfdbe968e5041348c165/bundled/hello_paredit.clj#L67
https://github.com/BetterThanTomorrow/calva/blob/276339cc5a3c63f17330bfdbe968e5041348c165/bundled/hello_paredit.clj#L73

This is mentioned here:
https://github.com/BetterThanTomorrow/calva/blob/276339cc5a3c63f17330bfdbe968e5041348c165/bundled/hello_paredit.clj#L80-L81

But it would be valuable to someone which no prior knowledge to see the way the keyboard shortcuts are intelligently chosen to relate similar commands and to inform them of this before they reach the end of this document. It might also be better to suggest they look at Keyboard Shortcuts (Ctrl+K, Ctrl+S) and look at anything prefixed Calva*, but because the commands are listed in alphabetical order in the Keyboard Shortcut list, the relationship between commands might not be immediately obvious.

**Comment by PEZ** [comment]
Ah, I now realize you provided feedback in several issues. I did wonder where I had seen it! 😄 Anyway, now these guides have their own repository: https://github.com/BetterThanTomorrow/dram
