### ISSUE TITLE
New Gettng started Guides: Suggestions and typos

### ISSUE THREAD

**Issue by rbeesley** [BetterThanTomorrow/calva#1039]
https://github.com/BetterThanTomorrow/calva/blob/276339cc5a3c63f17330bfdbe968e5041348c165/bundled/hello_paredit.clj#L8

I think it was meant:
```
 ;; ”forms”, aka S-expressions (sexprs). 
```

Alternatively and more formally:
```
 ;; ”forms”, a.k.a. S-expressions (sexprs). 
```

**Comment by PEZ** [comment]
These guides have now moved to https://github.com/BetterThanTomorrow/dram
