### ISSUE TITLE
Compiler error message doesn't line wrap

### ISSUE THREAD

**Issue by slipset** [BetterThanTomorrow/calva#104]
Even when I've set Code to wrap lines, the error message from the compiler doesn't wrap:
<img width="715" alt="screenshot 2019-01-26 at 21 11 51" src="https://user-images.githubusercontent.com/5894926/51792300-6c364480-21af-11e9-9b9d-42408ff80ac2.png">

**Comment by PEZ** [comment]
These messages can't be wrapped unfortunately. But, maybe we can be smarter about what we display.

**Comment by mikeball** [comment]
This has been bothering me as well when using inline repl and I've taken to going full screen with a ton of whitespace to right so some of it is readable. Until vscode gives us better way to handle inline results, I don't know what we could do other than perhaps parse out the specific error message, then print the entire error to the repl window?

Another similar issue is #79.

**Comment by mikeball** [comment]
This continues to be an issue for me. As a temporary workaround could we calculate how many characters can be displayed inline, and if the length of the result is too long, the results are printed to output or repl window and a note that the result can be found there?

**Comment by glenjamin** [comment]
if the `::after` element was giving a max-width and an text-overflow, perhaps that would work?

**Comment by cfehse** [comment]
@slipset 

This issue should be "fixed" with the added hover. I close this issue for now.
