### ISSUE TITLE
Cljfmt `split-keypairs-over-multiple-lines?` config not being considered

### ISSUE THREAD

**Issue by leoiacovini** [BetterThanTomorrow/calva#1054]
Hello!

I am trying to configure my project formatting, however even adding the configuration `split-keypairs-over-multiple-lines? false` to my `.cljfmt.edn` file (that is getting the indentation rules correctly, so calva is picking it up correctly), is not taking effect, the the `ctrl+alt+l` formatter is still splitting maps keypairs into multiple lines. Running the standalone `cljfmt` tool does not apply this change, so I believe this must be something related to Calva not picking it up and passing forward correctly maybe.

Thanks

**Comment by bpringe** [comment]
Hello. Pinging @PEZ here, since he's more familiar with this area.

**Comment by PEZ** [comment]
The command for aligning map key pairs should align map key pairs, right? If you format using `tab`(and have the ”global” option for aligning key pairs disabled) it should honor the `:split-keypairs-over-multiple-lines?` setting.

So with this config, copied from (https://calva.io/formatting/#configuration):

```clojure
{:remove-surrounding-whitespace? true
 :remove-trailing-whitespace? true
 :remove-consecutive-blank-lines? false
 :insert-missing-whitespace? true
 :align-associative? false}
```

Formattng something like:

```clojure
{:foo [1 2] :gazonk #{1 2}
               :baz 3}
```

<kbd>tab</kbd>

```clojure
{:foo [1 2] :gazonk #{1 2}
 :baz 3}
```

Aligning map items:

<kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>l</kbd>

```clojure
{:foo    [1 2]
 :gazonk #{1 2}
 :baz    3}
```

This is expected behaviour.

**Comment by leoiacovini** [comment]
I think that splitting key-value pairs into lines and aligning the values are different things, maybe it should be clearly explained in the documentation?. I find it a bit confusing to have 3 different commands to ident my code, the regular VSCode Ident, The `ctl+shit+l`, and the `tab` one 😵 . Usually, I want to keep my code formatted consistently according to my `cljfmt` config, which one of those commands should I prefer to use for this use case?

**Comment by PEZ** [comment]
Regular VS Code indent is not very useful when you use Calva. Instead rely on the indent you get as you type, which will indent using the same rules as you define in `-cljfmt.edn`.

If you want to tidy up the code with the formatter rules, then use `tab`.  It will format the current enclosing form. If you want map key/value **pairs** aligned, either specify that as the default for the formatter (I don't recommend this) or use the _Format and **Align**_ command to do it on demand.

**Comment by leoiacovini** [comment]
I just checked it now, and with (on my cljfmt config):
```clojure
{:split-keypairs-over-multiple-lines? false
 :align-associative?                  true}
```
and
```clojure
{:thing/keys [a b c] :as something}
```
Using `tab` still splits and becomes:
```clojure

{:thing/keys [a b c]
 :as         something}
```

**Comment by alexandergunnarson** [comment]
I'm seeing the same behavior as @leoiacovini, whether using `tab`, `ctrl+alt+L`, or paste. By contrast, when I use just a minimal example, where `example.clj` has the contents `{:a 1 :b 2}`:

```
clj \
  -Sdeps '{:deps {cljfmt {:mvn/version "0.7.0"}}}' \
  -e "(require '[cljfmt.main])" \
  -e "(cljfmt.main/fix [\"example.clj\"]
        {:align-associative?                  true
         :split-keypairs-over-multiple-lines? false})"
```

it says the file is all good. Then, as expected, when I change to `:split-keypairs-over-multiple-lines? true`, it splits the keypairs.

**Comment by PEZ** [comment]
@alexandergunnarson, vanilla cljfmt does not support `:align-associative?`, right? So in essence you are testing.

```
clj \
  -Sdeps '{:deps {cljfmt {:mvn/version "0.7.0"}}}' \
  -e "(require '[cljfmt.main])" \
  -e "(cljfmt.main/fix [\"example.clj\"]
        {:split-keypairs-over-multiple-lines? false/true})"
```

> whether using `tab`, `ctrl+alt+L`, or paste

Sounds like you run with `: align-associative? true`. Remove it, or set it to `false` and only `ctrl+alt+l` should have this behaviour.

**Comment by PEZ** [comment]
@leoiacovini , yes, with `:align-associative true` in your setting, you will always get the key pairs split across lines. As I wrote above, I do not recommend having that setting enabled. Not only because it always splits key pairs across lines, but also because it sometimes does pretty weird things.

**Comment by alexandergunnarson** [comment]
Got it, okay thanks @PEZ !

**Comment by bhurlow** [comment]
I'm running into this issue as well. I work on a team that uses a standard `cljfmt` config across different editors and our config defines `:split-keypairs-over-multiple-lines?` but does _not_ define (or want) `:align-associative?`.

 If I set `:split-keypairs-over-multiple-lines?` in my VSCode fmt config, formatting:

```clj
(def format-test
  {:short-key 1231 :very-much-longer-key 123123})
```

should produce 

```clj
(def format-test
  {:short-key 1231
   :very-much-longer-key 123123})
 ```

but instead it makes no change. 

Is there a reason that Calva doesn't allow that option combination?

**Comment by PEZ** [comment]
I think the reason is that Calva is using a fork of cljfmt from before there was any `:split-keypairs-over-multiple-lines?` option. I haven't checked the code yet, but there is no such option mentioned at https://calva.io/formatting/#configuration so it seems like a reasonable guess.

**Comment by bpringe** [comment]
@bhurlow We plan to start using vanilla cljfmt rather than Calva's fork. That is mentioned in https://github.com/BetterThanTomorrow/calva/issues/1179.

**Comment by bhurlow** [comment]
awesome thanks @bpringe that makes sense to me
