### ISSUE TITLE
Feature request: support for CIDER's "Evaluate up to cursor"

### ISSUE THREAD

**Issue by igufi** [BetterThanTomorrow/calva#1057]
During a discussion on debugging in the calva channel at Clojurians Slack, it was noted that CIDER supports a feature where a user can "evaluate up to cursor". Could this functionality be exposed in Calva, too?

**Comment by bpringe** [comment]
Just adding more context from Slack. With a form like below, it should be possible to evaluate up to the cursor:

```clojure
(as-> 15 $
    (range 1 $ 3)|
    (interpose ":" $)) 
```

**Comment by PEZ** [comment]
This now released (might take a few minutes to process in the marketplace). Teaser:

![image](https://user-images.githubusercontent.com/30010/110395554-a224a300-806e-11eb-9476-215618f7a211.png)
