### ISSUE TITLE
Cannot find definition for derefed val

### ISSUE THREAD

**Issue by il-tmfv** [BetterThanTomorrow/calva#106]
"Go to Definition" leads to this when var is derefed with `@`:
<img src="https://user-images.githubusercontent.com/15895189/51829386-7d419b80-22fe-11e9-844a-843d409be6f6.png" width="50%">

I guess it thinks that `@` is a part of var name.
If I add a space after `@` then it works fine.

UPD: this is a cljs project.

**Comment by PEZ** [comment]
Thanks for reporting! It looks like the word-regexp lacks `@` as a delimeter.

**Comment by il-tmfv** [comment]
I think it can be closed. Thanks for fixing it 👍
