### ISSUE TITLE
Remove the display diagnostics setting in favor of managing diagnostics entirely via clojure-lsp config

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1067]
https://clojure-lsp.github.io/clojure-lsp/settings/#diagnostics-linter

Currently we just intercept diagnostics in the lsp middleware, but perhaps a better method is to modify the lsp config. I'm not sure though if this is wise. To disable diagnostics for all projects, we'd need to modify the users `~/.lsp/config.edn`, and then modify it again if we want to enable them.

Would modifying the user's global lsp config pose any issues? I guess another thing to consider is would the change be immediately noticeable. With the current implementation using middleware, the change is immediate. We could always keep the current method for the immediate effect, plus modify the config if that actually prevents some work being done on the server.

@ericdallo Does turning linting off in the lsp config cause less work by the server? I guess it at least makes it not send the diagnostics notification, but does it calculate them for other things anyway?

**Comment by ericdallo** [comment]
You don't need to change user config, you can pass those same configs via initializationOptions :)

**Comment by ericdallo** [comment]
the server will still calculate since we use for other features, but we will not publish them, avoiding unnecessary json to client, eventually improving performance

**Comment by bpringe** [comment]
Got it, thanks! Since this wouldn't take effect until next startup though, I think it makes sense to do this along with the existing middleware usage we have. Btw, am I understanding correctly that the initializationOption setting is `:linters` (plural)? If so, it may need to be corrected here: https://clojure-lsp.github.io/clojure-lsp/settings/#all-settings

**Comment by ericdallo** [comment]
Yes, I'll fix the docs, thanks!

**Comment by bpringe** [comment]
Removing this setting after discussing in Slack.
