### ISSUE TITLE
Call hierarchy does not work

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1069]
The command `Calls: Show Call Hierarchy` does not seem to work. Clojure-lsp has support for callHierarchy/incoming and it should work. When I run the command, I see that textDocument/codeLens and codeLens/resolve requests are made, but that's it.

**Comment by bpringe** [comment]
We should check if the protocol method existed in the current version of the protocol our client uses.

**Comment by bpringe** [comment]
From @EricDallo:

> yes, definitely that was added on latest protocol version, 3.16

**Comment by ericdallo** [comment]
Ref: https://microsoft.github.io/language-server-protocol/specification#whatIsNew

**Comment by bpringe** [comment]
We've updated the client library. We need to check if this works.

**Comment by bpringe** [comment]
I verified the call hierarchy feature is working.
