### ISSUE TITLE
Jack-in error: Clojure command not found

### ISSUE THREAD

**Issue by wevre** [BetterThanTomorrow/calva#1073]
Issue Type: <b>Bug</b>

Sometimes when I launch VS Code from Mac OS Finder, the environment seems to get messed up. When I try to jack-in, I get an error like this:

    clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.8.3"},cider/cider-nrepl {:mvn/version,"0.25.8"}}}'  -m repl.cmdline --middleware "[cider.nrepl/cider-middleware]"
    /bin/sh: clojure: command not found
    Jack-in process exited. Status: 127

But within the same project, if I open an additional terminal and execute the command that is the first line of that error, nrepl will start okay and I can then use Calva's command to connect to an in-project repl.

It's confusing why two terminals, both within the VS Code project, but one says it can't find the `clojure` command, and the other launches it no problem.

The workflow I'm using to launch Code from the finder is a little Automator script I created that executes this command:

    open -n -b "com.microsoft.VSCode" --args "$*"

This is maybe the culprit? Although, if that is the case, why does manually launching the repl still work? Also, this problem doesn't happen _every_ time I launch VS Code from the finder. And when it does happen, then usually if I completely quit out of VS Code and then relaunch (from the Finder) jack-in will work okay.

Extension version: 2.0.179
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T11:57:12.728Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (4.52GB free)|
|Process Argv|/Users/wevrem/Documents/programming/clojure/code-camp/tic-tac-toe-web --crash-reporter-id 4cf86013-bc94-4a39-b16e-ced1644b8579|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythontb:30265425
vscoresta800cf:30276762
vspre833:30267464
vsdfh931:30275552
vshan820:30276952

```

</details>

**Comment by bpringe** [comment]
Hi. I'm not sure of all the details with that method of launching, but there's a known issue (even with other editors I believe) that the environment when launching VS Code via certain means does not match the environment you might have in a terminal where a REPL would start fine.

Try launching VS Code from a terminal where `clojure` is seen as a command, using the `code` command. Let us know if that helps.

**Comment by bpringe** [comment]
This is touched on a bit here: https://calva.io/connect/#command-not-found-errors. If you think it should be more clear, let us know.

**Comment by bpringe** [comment]
I really should read the slack channel before commenting on issues :smile:. I just read the conversation and I see the above was discussed.

**Comment by wevre** [comment]
Brandon, thanks for your quick response. If you read the slack channel then you know that Peter (PEZ) asked me to try opening an issue from VS Code so that some of the system info was captured.

Given that we know there are issues around opening VS Code from the Finder, vs. opening it from a Terminal, the easy solution here is for me to get on board with what everyone else already knew and already does, which is open my project from a terminal, which I will start doing immediately. 

The only mystery that remains is why, with a Calva project where we are getting the 'command not found' 127 error when attempting jack-in, we can still open an additional terminal (still within the VS Code project) and successfully start the REPL with the normal jack-in command. It is odd that those two terminals don't seem have the same environment. But I don't need that mystery to be solved in order to continue successfully using Calva, so it's up to you guys if this is something you want to investigate, or just drop it.

Also, the documentation on [command-not-found](https://calva.io/connect/#command-not-found-errors) is quite clear. There is one small typo you might want to fix:

    If you get command not found error when Calva tries 
    to start your project, and you know you have the 
    command installed. It probably is because...
                    ^^^ [this should probably be a comma?]

**Comment by bpringe** [comment]
Thanks for the clear description of the issue and for pointing out the typo in the docs! I'll fix that now.
