### ISSUE TITLE
Weird highlight of literal data structures as first argument to `cond->`

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1076]
Here's a mystery. If I have a literal data structure as the thing I thread through a `cond->` form, and place the cursor in some symbol inside the structure form the whole structure form highlights. It looks like so:

<img width="149" alt="image" src="https://user-images.githubusercontent.com/30010/111903299-eab26800-8a41-11eb-8bf7-682ff5c125c1.png">

Pasting the example as text here as well.

```clojure
(cond-> [:foo
         100
         3301
         5000])
```

It happens for `cond->>` as well, but not with any other thread macro, as far as I can see.

**Comment by ericdallo** [comment]
This should be fixed on clojure-lsp [2021.03.18-19.23.41](https://github.com/clojure-lsp/clojure-lsp/releases/tag/2021.03.18-19.23.41)

**Comment by PEZ** [comment]
This was fixed in 2.0.184
