### ISSUE TITLE
Auto deletion of closing paren on deletion of opening paren in shorthand function syntax causes newline to be removed

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1079]
![auto_removal_newline](https://user-images.githubusercontent.com/12722744/112347646-45d39d00-8c84-11eb-8781-358719883d3a.gif)

Not sure if this is related to #1024.

**Comment by PEZ** [comment]
As always, text repro's appreciated. 😄 

```clojure
{::foo #(|)
 ::bar :foo}
```

<kbd>backspace</kbd>

**Expected:***

```clojure
{::foo |
  ::bar :foo}
```

**Actual:***

```clojure
{::foo #|::bar :foo}
```

And no, not related to that feature request. Which I would also love to implement, btw.

**Comment by PEZ** [comment]
This also affects <kbd>delete</kbd>.
