### ISSUE TITLE
Load files when running all tests

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva#108]
`Run all tests` only run tests from files loaded

I'm currently running (refresh-all) on the repl to load the test files before running the tests, but it would be nice if that was done automatically and loaded only test files (refresh-all load all files)

**Comment by PEZ** [comment]
Latest Calva addresses this. Please give it a spin and close this issue if you think it is fixed.

**Comment by claynon** [comment]
Yes, it works!
This actually help me find a bug in my tests when running all tests multiple times :)
