### ISSUE TITLE
"The Clojure Language Client server crashed 5 times in the last 3 minutes. The server will not be restarted."

### ISSUE THREAD

**Issue by fabricioc8** [BetterThanTomorrow/calva#1080]
I'm getting this warning when I open vsc, and the message "Initializing clojure language features via clojure-lsp" keeps spinning on the bar.
  
This happens after I woke up and found the pc restarting with a warning that the bios had been corrupted ... I have windows 7 64bits and the day before I had been installing versions of jdk and jre for 32bits because leiningen "could not find the .../programfiles86/java/jre/bin/server/jvm.dll " file, (which I had to copy manually because with the normal installation it was not created either). 

  The output panel shows:
"An error has occurred while processing the shared archive file.
Unable to unmap shared space.
[Info  - 11:50:58] Connection to server got closed. Server will restart.
An error has occurred while processing the shared archive file.
Unable to unmap shared space.
[Info  - 11:50:58] Connection to server got closed. Server will restart.
An error has occurred while processing the shared archive file.
Unable to unmap shared space.
[Info  - 11:50:58] Connection to server got closed. Server will restart.
An error has occurred while processing the shared archive file.
Unable to unmap shared space.
[Info  - 11:50:58] Connection to server got closed. Server will restart.
An error has occurred while processing the shared archive file.
Unable to unmap shared space.
[Error - 11:50:58] Connection to server got closed. Server will not be restarted."

I tried reinstalling but nothing changed

Any suggestion? Thanks a lot!!

**Comment by bpringe** [comment]
Hello. Thanks for the report. Those logs are from the Clojure Language Client output? If not, which output channel are they from?

**Comment by bpringe** [comment]
Could you also post the output of your latest `~/tmp/clojure-lsp*` file?

**Comment by PEZ** [comment]
I think this could be that VS Code is started w/o the necessary PATHs in its environment. Seems to happen on often on Mac  when VS Code is started from the GUI. See if starting VS Code from a terminal prompt makes a difference (the `code` command, I think `open -a` might be the same as opening via the GUI).

**Comment by PEZ** [comment]
Ah, and now read the issue properly. Never mind me. 😄

**Comment by fabricioc8** [comment]
I uninstalled and reinstalled everything related to jdk and it worked again, but now I have another problem which is that I cannot start the REPL.

With projects with deps.edn the terminal returns the following:

 java -jar ".calva\deps.clj.jar" -Sdeps "{:deps {nrepl/nrepl {:mvn/version,""0.8.3""},cider/cider-nrepl {:mvn/version,""0.25.8""}}}"  -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
Error while parsing option "--config-data {:deps {nrepl/nrepl {:mvn/version,0.8.3},cider/cider-nrepl {:mvn/version,0.25.8}}}": java.lang.NumberFormatException: Invalid number: 0.8.3
Jack-in process exited. Status: 1 

And with leiningen projects this other:

cmd.exe /d /c lein update-in :dependencies conj [nrepl,"0.8.3"] -- update-in :plugins conj [cider/cider-nrepl,"0.25.8"] -- update-in [:repl-options,:nrepl-middleware] conj '["cider.nrepl/cider-middleware"]' -- repl :headless
java.lang.NumberFormatException: Invalid number: 0.8.3
 at clojure.lang.LispReader.readNumber (LispReader.java:352)
    clojure.lang.LispReader.read (LispReader.java:278)
    clojure.lang.LispReader.readDelimitedList (LispReader.java:1398)
    clojure.lang.LispReader$VectorReader.invoke (LispReader.java:1347)
    clojure.lang.LispReader.read (LispReader.java:285)
    clojure.lang.LispReader.read (LispReader.java:216)
    clojure.lang.LispReader.read (LispReader.java:205)
    clojure.lang.RT.readString (RT.java:1874)
    clojure.lang.RT.readString (RT.java:1869)
    clojure.core$read_string.invokeStatic (core.clj:3815)
    clojure.core$read_string.invoke (core.clj:3805)
    clojure.core$mapv$fn__8430.invoke (core.clj:6912)
    clojure.core.protocols$fn__8144.invokeStatic (protocols.clj:168)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__8099$G__8094__8108.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__8131.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__8073$G__8068__8086.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6828)
    clojure.core$mapv.invokeStatic (core.clj:6903)
    clojure.core$mapv.invoke (core.clj:6903)
    leiningen.update_in$parse_args.invokeStatic (update_in.clj:13)
    leiningen.update_in$parse_args.invoke (update_in.clj:9)
    leiningen.update_in$update_in.invokeStatic (update_in.clj:36)
    leiningen.update_in$update_in.doInvoke (update_in.clj:24)
    clojure.lang.RestFn.applyTo (RestFn.java:146)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$partial_task$fn__7356.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:343)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__7445.invoke (main.clj:453)
    leiningen.core.main$_main.invokeStatic (main.clj:442)
    leiningen.core.main$_main.doInvoke (main.clj:439)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.main$main_opt.invokeStatic (main.clj:491)
    clojure.main$main_opt.invoke (main.clj:487)
    clojure.main$main.invokeStatic (main.clj:598)
    clojure.main$main.doInvoke (main.clj:561)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:37)
Jack-in process exited. Status: 1

**Comment by PEZ** [comment]
That's bad... I really don't understand why quoting on windows should be so hard to get right, or rather why it works so differently for different users.

Can you test what happens if you put those commands into `.bat` files, @fabricioc8 and run those?  Maybe Calva could do that on windows...

**Comment by fabricioc8** [comment]
mm i'm not sure if i did it right, but i pasted `java -jar ".calva\deps.clj.jar" -Sdeps "{:deps {nrepl/nrepl {:mvn/version,""0.8.3""},cider/cider-nrepl {:mvn/version,""0.25.8""}}}"  -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"` inside a cmd.bat file and i put it on the project root where the deps.edn file is. Then i ran it and i got this:

`C:\Users\Usuario\Desktop\clojure\Tutorial clj cli\hello-worl
d>java -jar ".calva\deps.clj.jar" -Sdeps "{:deps {nrepl/nrep
l {:mvn/version,""0.8.3""},cider/cider-nrepl {:mvn/version,"
"0.25.8""}}}"  -m nrepl.cmdline --middleware "[cider.nrepl/c
ider-middleware]"
Error while parsing option "--config-data {:deps {nrepl/nrep
l {:mvn/version,0.8.3},cider/cider-nrepl {:mvn/version,0.25.
8}}}": java.lang.NumberFormatException: Invalid number: 0.8.
3`

And the same for a leiningen proyect:
cmd.bat -> `cmd.exe /d /c lein update-in :dependencies conj [nrepl,"0.8.3"] -- update-in :plugins conj [cider/cider-nrepl,"0.25.8"] -- update-in [:repl-options,:nrepl-middleware] conj '["cider.nrepl/cider-middleware"]' -- repl :headless`

And i got this:
 
C:\Users\Usuario\Desktop\clojure\reag5>cmd.exe /d /c lein up
date-in :dependencies conj [nrepl,"0.8.3"] -- update-in :plu
gins conj [cider/cider-nrepl,"0.25.8"] -- update-in [:repl-o
ptions,:nrepl-middleware] conj '["cider.nrepl/cider-middlewa
re"]' -- repl :headless
java.lang.NumberFormatException: Invalid number: 0.8.3
 at clojure.lang.LispReader.readNumber (LispReader.java:352)
    clojure.lang.LispReader.read (LispReader.java:278)
    clojure.lang.LispReader.readDelimitedList (LispReader.java:1398)
    clojure.lang.LispReader$VectorReader.invoke (LispReader.java:1347)
    clojure.lang.LispReader.read (LispReader.java:285)
    clojure.lang.LispReader.read (LispReader.java:216)
    clojure.lang.LispReader.read (LispReader.java:205)
    clojure.lang.RT.readString (RT.java:1874)
    clojure.lang.RT.readString (RT.java:1869)
    clojure.core$read_string.invokeStatic (core.clj:3815)
    clojure.core$read_string.invoke (core.clj:3805)
    clojure.core$mapv$fn__8430.invoke (core.clj:6912)
    clojure.core.protocols$fn__8144.invokeStatic (protocols.clj:168)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__8099$G__8094__8108.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__8131.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__8073$G__8068__8086.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6828)
    clojure.core$mapv.invokeStatic (core.clj:6903)
    clojure.core$mapv.invoke (core.clj:6903)
    leiningen.update_in$parse_args.invokeStatic (update_in.clj:13)
    leiningen.update_in$parse_args.invoke (update_in.clj:9)
    leiningen.update_in$update_in.invokeStatic (update_in.clj:36)
    leiningen.update_in$update_in.doInvoke (update_in.clj:24)
    clojure.lang.RestFn.applyTo (RestFn.java:146)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$partial_task$fn__7356.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:343)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__7445.invoke (main.clj:453)
    leiningen.core.main$_main.invokeStatic (main.clj:442)
    leiningen.core.main$_main.doInvoke (main.clj:439)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.main$main_opt.invokeStatic (main.clj:491)
    clojure.main$main_opt.invoke (main.clj:487)
    clojure.main$main.invokeStatic (main.clj:598)
    clojure.main$main.doInvoke (main.clj:561)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:37)

**Comment by PEZ** [comment]
Thanks for testing that. I'll have to make some tests as well and will get back to you with more things to test. Meanwhile, can you file an issue using vscode's issues reporter (Help menu)? If it allows you to just copy the system info, you can just paste it as a comment here, but otherwise a separate issue works as well.

**Comment by bpringe** [comment]
Closing this since #1106 was created and the original issue is no longer occurring. A different username created that issue, so either a weird coincidence or that was you @fabricioc8. :smile:
