### ISSUE TITLE
Make clojure-lsp version configurable by the user

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1088]
I know this could potentially cause us trouble, but deploying it hardcoded in the app can also cause us trouble. 😄 

Besides, we do this with the jack-in dependencies.

**Comment by bpringe** [comment]
Sounds good to me! Something like this has been on my radar, but I've waited to implement. What you did looks good. I had also implemented, at one time, a setting for the clojure-lsp path, so someone could download a version manually and set the path, but I abandoned that as I felt it was something additional to the change I was making, and wasn't sure it was what we wanted. I think lsp-mode allows this. But using a version setting seems to be about the same and easier.
