### ISSUE TITLE
Run all tests only target namespaces that end with `test`

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva#109]
I have tests that don't end with `test` and those are not run. It would be nice to have look into the files and run all tests defined with `deftest` or have a way to configure a path for tests

**Comment by PEZ** [comment]
This might have been fixed with the lastest Calva (1.3.63). Please check and let me know if it works for you.

**Comment by claynon** [comment]
It works, thanks :)

**Comment by PEZ** [comment]
Awesome!
