### ISSUE TITLE
1.3.61 breaks vim (vscodevim) extension

### ISSUE THREAD

**Issue by il-tmfv** [BetterThanTomorrow/calva#110]
v1.3.61 breaks vim (vscodevim) extension. I cannot switch back to normal mode only in clojure script files. Ruby, for example is fine.

Steps: to reproduce:
1. open some cljs file
2. switch to insert mode with `i`
3. try to switch back to normal mode with `esc`
4. nothing happens

In 1.3.60 (installed via "install another version") everything works fine.

**Comment by mseddon** [comment]
Thanks for the report!

We recently bound escape to clear the inline evaluation results.

https://github.com/BetterThanTomorrow/calva/blob/master/package.json#L265

We will look at changing the defaults so it does not conflict. As an interim workaround you can re-bind that key to something else, and that should bring vscodevim back for now. Let me know if that doesn't work for you.

**Comment by PEZ** [comment]
Escape is the natural way to dismiss those inline evaluations, but, boy, does it interfere with vi modes! I think we can detect it though, and use another default for when vscodevim is present.

**Comment by il-tmfv** [comment]
Thanks! Changed vim's keybinding for switching to normal mode and it works again.

**Comment by mseddon** [comment]
You can change calva's binding instead if you prefer!

**Comment by il-tmfv** [comment]
Yep, but they propose to bind it to `jj`. Lets see how it will feel 🙂

**Comment by PEZ** [comment]
Can we close this? Seems there are at least two work-arounds and probably keeping track of possibly conflicting extensions is a bit of a burden.

**Comment by il-tmfv** [comment]
Sure!
