### ISSUE TITLE
Falsely reporting unused var

### ISSUE THREAD

**Issue by vindkaldr** [BetterThanTomorrow/calva#1102]
In the following example, the `arbitrary-fn?` is reported as an unused public var.

```clojure
(ns namespace
  (:require [datascript.core :as d]))

(defn arbitrary-fn?
  [n]
  (< n 10))

(d/q '[:find ?e
       :where [?e :number ?v]
       [(namespace/arbitrary-fn? ?v)]]
     [[1 :number 5]
      [2 :number 15]])
```

For Datalog queries, I need to provide an escaped collection. I suspect this is the root case of the issue. For example, uncommenting the other line that references `f` solves the issue. (Edited. The wrong line was initially commented.)

```clojure
(defn f [])

;; [f]
'[f]
```

I'm not sure to how much extent is Calva involved in making this decision or if it's completly in `clojure-lsp`'s hands.

Thank you in advance!

**Comment by PEZ** [comment]
Hello. See if you get the same result using `clj-kondo` from the command line.

**Comment by vindkaldr** [comment]
Thank you for the quick reply!

`clj-kondo` does not seem to do anything with unused public vars.

```
echo '(defn f [])' | clj-kondo --lint -      
linting took 6ms, errors: 0, warnings: 0

echo '(defn f []) [f]' | clj-kondo --lint -
linting took 7ms, errors: 0, warnings: 0

echo "(defn f []) '[f]" | clj-kondo --lint -
linting took 15ms, errors: 0, warnings: 0
```
Although for unused private vars, the mentioned  issue applies.
```
echo '(defn- f [])' | clj-kondo --lint -     
<stdin>:1:8: warning: Unused private var user/f
linting took 10ms, errors: 0, warnings: 1

echo '(defn- f []) [f]' | clj-kondo --lint -
linting took 7ms, errors: 0, warnings: 0

echo "(defn- f []) '[f]" | clj-kondo --lint -
<stdin>:1:8: warning: Unused private var user/f
linting took 11ms, errors: 0, warnings: 1
```

**Comment by vindkaldr** [comment]
I just found this on the `clojure-lsp` site: https://clojure-lsp.github.io/clojure-lsp/features/#diagnostics-linter
This is aligned with what's on the dialog on hovering the function: `Unused public var '...' clojure-lsp(unused-public-var)`

**Comment by PEZ** [comment]
I think unused public vars is linter provided by `clojure-lsp`, come to think about it.

I wonder if the issue you see could be related to this: https://github.com/clj-kondo/clj-kondo/issues/1246 ...

There is a Calva setting for clojure-lsp version. Can you see if the issue remains with version: `2021.04.03-18.43.55 `?

**Comment by vindkaldr** [comment]
The issue remains even with the suggested version.
I found this already closed issue, that is suspiciously similar: https://github.com/clojure-lsp/clojure-lsp/issues/203

**Comment by vindkaldr** [comment]
About https://github.com/clj-kondo/clj-kondo/issues/1246, based on the [wrote test](https://github.com/clj-kondo/clj-kondo/commit/a14a06c8fa257c1d876c509517b2ac24ffd20f50#diff-0012db6d5784c239c681035c9ec52a124338a1a8f41af9c6123362b94470e852) it seems to be about a different issue. For completeness sake, I copied the code and config into my project and it didn't give any error.

**Comment by PEZ** [comment]
Don't forget to remove your custom clojure-lsp setting. 😄

**Comment by vindkaldr** [comment]
I already reset it. But thank you for the heads-up! :slightly_smiling_face:

**Comment by vindkaldr** [comment]
Thank you for your help! I'm closing the issue as it was based on an unfounded expectation.

I started discussing the issue here but arrived at a conclusion here: https://github.com/clojure-lsp/clojure-lsp/issues/394
