### ISSUE TITLE
Add some output options

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1104]
This is related to issue #767

At work we have some custom writers that makes some output to come in transit form. This throws the parsing of the output window out of whack and we stop being able to submit from the prompt. I'm not sure how hard the actual parsing issue would be to fix here, but in any case it is a symptom. Arbitrary output doesn't mix all that well with a Clojure parser.

However, of course it is convenient to have the output in a syntax highlighted file with full structural editing. I am leaning towards making it configurable where to output things. We should be able to at least syntax highlight output in the jack-in terminal for instance. (We would could also open such a ”terminal” for the connect scenario.) VS Code is a bit stupid about how you can arrange different panes, but I often run with the terminal visible so this could work.

I know we have floated other output options before, but can't recall them right now. Let's brain storm it a bit.

**Comment by bpringe** [comment]
In #942 we talked about adding an option to send all stdout to Calva says or some other output channel like that. This doesn't apply to results though, but we could have settings for both. I guess one situation to keep in mind is people evaluating things in the output window, when they have configured output to go to another place. Ignore the settings and print to the output window in this case to avoid confusion? Not sure yet.

**Comment by PEZ** [comment]
I think it was #942 that I was remembering. I think it makes sense to keep results in the output window, and only add options for sending side effect output elsewhere. Results is always valid EDN because homoiconicity. We should fix the transit issue in our parser instead.
