### ISSUE TITLE
Add custom refactors using snippets

### ISSUE THREAD

**Issue by maxrothman** [BetterThanTomorrow/calva#1108]
The custom REPL commands feature in Calva is great! In fact it's so great, that I've recently found myself wanting a similar system for creating custom refactor commands. For example, here's a simple one that would wrap the current form in a `let`:

```json
{
  "name": "Wrap in let",
  "snippet": "(let [$1] $current-form)"
}
```
For other languages VSCode's snippet feature works fine, but having a structure-aware version for Clojure would be amazing.  I went looking for a way to extend the variables available in standard VSCode snippets, but I didn't find much.

**Comment by PEZ** [comment]
Sound great! What's in `$1` there?

**Comment by maxrothman** [comment]
Oh, sorry for the lack of explanation. [That's something from VSCode's snippet syntax](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_tabstops), it tells the snippet where to put your cursor upon snippet expansion.

**Comment by bpringe** [comment]
@maxrothman Have you tried the command `Calva Refactor: Introduce let`?  This is a clojure-lsp feature. It sounds the same as what you describe, but maybe I'm misunderstanding.

**Comment by maxrothman** [comment]
@bpringe the two are a little different:
```clojure
;; | is the cursor
(foo |(bar baz))
;; Introduce Let
(foo |(let [something (bar baz)] something))

(foo |(bar baz))
;; Wrap in let
(foo (let [|] (bar baz)))
```

Something else that occurred to me: another way of approaching this feature request would be, instead of re-implementing some part of VSCode's snippet system, to get a PR accepted to VSCode allowing extensions to inject custom variables for snippets. [They've got a bunch available already](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables), making the list extensible seems like a thing that should be possible...

Alternatively, there might be a hacky workaround where Calva selects the next form for you and then snippet authors can use `TM_SELECTED_TEXT`. Just spitballing!

**Comment by bpringe** [comment]
Ah I see. Interesting. I'd imagine getting a VSCode PR accepted would take much longer than implementing it in Calva or clojure-lsp.

@ericdallo, does this look like something clojure-lsp could/should do?

**Comment by ericdallo** [comment]
Yes, that'd be possible and should/could be implemented on clojure-lsp, I'm just not sure if the LSP protocol support that kind of notation to place the editor cursor somewhere.

**Comment by ericdallo** [comment]
I can't find anything about snippet besides on completionItems: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#snippet_syntax

So, AFAICS, if we would implement that, we would need to make changes on both server and client (Calva, lsp-mode etc) to fully support that, using a custom request/response

**Comment by bpringe** [comment]
Hmm I see. Not sure if that's the best path then.

**Comment by ericdallo** [comment]
Hey @bpringe, talking with @yyoncho, he gave a suggestion about using the completion which already has support for snippets + a custom server config, example:

1. User register in Calva the snippet:
```json
{
  "name": "Wrap in let",
  "snippet": "(let [$1] $current-form)"
}
```
2. When starting clojure-lsp, Calva send that as a `initializationOptions`:
```clojure
"initializationOptions": {
   "additionalSnippets":[
     {"name": "Wrap in let", "snippet": "(let [$1] $current-form)"}
   ]
   ...
}
```
3. clojure-lsp register that snippet and make it available via completion following the LSP spec for that.
4. User can action the snippet at any time via completion and use it.

WDYT?

**Comment by PEZ** [comment]
> WDYT?

That sounds pretty damn awesome if it works.

Seems like Calva needs to do something more to actually replace the `$current-form` variable?

**Comment by maxrothman** [comment]
Would users have to restart the language server whenever they add new
snippets?

**Comment by ericdallo** [comment]
> Would users have to restart the language server whenever they add new
snippets?

For now, yes, we can think in improve that using workspaceConfiguration from LSP spec that allow changing things without server restart later.

> Seems like Calva needs to do something more to actually replace the $current-form variable?

I don't know how Calva act as a LSP client, but since we will follow LSP spec, there's a chance we don't need to change anything on clients related to manually handling snippets as LSP clients like already support that

**Comment by bpringe** [comment]
> > Seems like Calva needs to do something more to actually replace the $current-form variable?

> I don't know how Calva act as a LSP client, but since we will follow LSP spec, there's a chance we don't need to change anything on clients related to manually handling snippets as LSP clients like already support that

I don't really understand... where and at what point would `$current-form` be replaced by the current form? It seems to me that Calva would have to replace that at some point after the completion is selected. Also how would this completion look? Maybe my brain is not very sharp after work today. :smile:

**Comment by ericdallo** [comment]
It's all on the [LSP spec about completion](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion), clojure-lsp can get the `$current-form` from the completionContext sent when user trigger completion

**Comment by bpringe** [comment]
Oh, awesome!

**Comment by ericdallo** [comment]
@bpringe @maxrothman I created this issue to track on clojure-lsp: https://github.com/clojure-lsp/clojure-lsp/issues/403

**Comment by bpringe** [comment]
The clojure-lsp feature for this is out now (just noting here), `snippetSupport` needs to be set to true in the client initializationOptions (by Calva), from what I understand.

**Comment by ericdallo** [comment]
@bringe is not a `initializationOptions` options, but a client capability, not sure how vscode handles those configs: https://microsoft.github.io/language-server-protocol/specification#textDocument_completion

**Comment by bpringe** [comment]
Ah, I see. Thanks.

**Comment by maxrothman** [comment]
I happened to be reminded of this issue, did the Calva side of this ever land? Is this issue now stale?

**Comment by Cyrik** [comment]
What I'm not fully understanding here: why does Calva need to be involved in this process? At this point, you can just add the snippet in the clojure-lsp config, right? Not sure if doing it through a Calva setting adds any benefits.

**Comment by bpringe** [comment]
> At this point, you can just add the snippet in the clojure-lsp config, right? Not sure if doing it through a Calva setting adds any benefits.

Yes, this should just work now from what I can tell. I haven't tried it, though. The clojure-lsp docs for it are here: https://clojure-lsp.io/settings/#snippets.

I verified that Calva / the client lib is sending `true` for `snippetSupport` during initialization. I'm going to optimistically close this, but if @maxrothman you or anyone else has issues with this, please report back here.

**Comment by maxrothman** [comment]
I gave this a shot, but I couldn't get custom snippets to work. I successfully toggled some other settings so I know my config file is getting picked up. The problem should be reproducible with just the [example in the docs](https://clojure-lsp.io/settings/#snippets).

**Comment by bpringe** [comment]
Thanks @maxrothman. I created a new issue to track it.
