### ISSUE TITLE
printing with new line prevent tests of running

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva#111]
When I load and run the following test it works
```clojure
(deftest a-test
  (is (= 1 1))))
```
`1 tests finished, all passing 👍, ns: 1, vars: 1`

But when I change I add a `print` call it stops running the tests
```clojure
(deftest a-test
  (is (= 1 (do (println :foo) 1)))))
```
`No tests found. 😱, ns: 0, vars: 0`

This problem happens with `prn` and `println` but works fine with `print` (however the printed value doesn't go the `Output`, or any other place that I found).

`prn` and `println` not only prevents the actual test from running but all other tests (when the problematic test is loaded)

**Comment by mseddon** [comment]
:D classic! Thanks for the report.

**Comment by bpringe** [comment]
This appears to be working in the latest Calva, as far as my testing went. Some things around evaluation may be working differently now and may have fixed this. I'll close, but reopen if I made a mistake.
