### ISSUE TITLE
REPL evaluation hangs if an error is raised during debug session

### ISSUE THREAD

**Issue by athos** [BetterThanTomorrow/calva#1118]
Hi, thank you for all the hard work to make this extension amazing!

Recently, I found a weird REPL behavior during a debug session.

Repro:
1. Instrument a function for debug execution
2. Evaluate the invocation to that function
3. Step over to the form where the error occurs
4. After that, no further evaluation will take place

![calva-screencast](https://user-images.githubusercontent.com/27441/114297913-7756c000-9aee-11eb-86ab-a7c98b5a9296.gif)

**Comment by PEZ** [comment]
Thanks for reporting!
