### ISSUE TITLE
Inline evaluation results can show up in the wrong editor

### ISSUE THREAD

**Issue by eerohele** [BetterThanTomorrow/calva#1120]
Easier to show than tell (look at what happens on line 31 of `hello_clojure.clj`):

![Screen Recording 2021-04-15 at 15 41 17](https://user-images.githubusercontent.com/31859/114870816-45e93780-9e01-11eb-89db-f283ba24dc19.gif)

If I evaluate the `(do)` form, then switch to a different editor, the inline evaluation result shows up in the new editor instead of next to the form I evaluated. I'd expect it to show up next to the form I evaluated regardless of which editor is active.

**Comment by PEZ** [comment]
Thanks for reporting! I have a vague memory of someone telling me this befor..., Good to have an issue about it.
