### ISSUE TITLE
Jack-in and connect broken with re-frame template (upstream issue)

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1121]
In #314 some comments are added about breakage with the re-frame template. This comment has a video showing it: https://github.com/BetterThanTomorrow/calva/issues/314#issuecomment-820910091

Two things wrong there: There are two `shadow-cljs` options and one of them is pointing at a broken connect setting.

Anyway, this needs to be fixed upstream. I'm on it.

**Comment by muhajirdev** [comment]
Hi @PEZ 
Thanks for opening this new issue.

Is there a quick fix I can try on my side, or we'll need to wait new release?

**Comment by muhajirdev** [comment]
actually yeah, one of the options is correct and the other one broken.

**Comment by PEZ** [comment]
Yes, the re-frame template was updated recently and it broke Calva. I have sent them a PR now.

Thanks for bringing this to my attention, @muhajirdev !

**Comment by muhajirdev** [comment]
no problem!

Thanks for the awesome tool man @PEZ !

**Comment by PEZ** [comment]
This should now be fixed. Please verify and let me know how you fare, @muhajirdev . I'll reopen if the problem still remains.
