### ISSUE TITLE
Paredit: delete # character before opening delimiter

### ISSUE THREAD

**Issue by yuhan0** [BetterThanTomorrow/calva#1122]
Calva treats `#(` and `#{` as single units and refuses to delete the `#` character alone.
This can be annoying when eg. refactoring a `#(..)` into a `(fn ..)` or when deleting the `#_` ignore macro one character at a time.

```clj
#_ (ignore me) ;;  delete the _
# (ignore me)  ;; oops, can't delete the #  

#:same{:thing :here} ;; try removing the namespace tag
```

@PEZ  suggested `Alt-backspace` as a temporary workaround which ignores paredit and forces deletion.

**Comment by PEZ** [comment]
So translating this to Paredit tests, one way to solve this would be to make these tests pass (without breaking any existing tests, naturally).

```typescript
            it('Deletes open paren prefix characters', () => {
                // https://github.com/BetterThanTomorrow/calva/issues/1122
                const a = docFromTextNotation('#|(foo)');
                const b = docFromTextNotation('|(foo)');
                paredit.backspace(a);
                expect(textAndSelection(a)).toEqual(textAndSelection(b));
            });
            it('Deletes open map curly prefix/ns characters', () => {
                const a = docFromTextNotation('#:same|{:thing :here}');
                const b = docFromTextNotation('#:sam|{:thing :here}');
                paredit.backspace(a);
                expect(textAndSelection(a)).toEqual(textAndSelection(b));
            });
            it('Deletes open set hash characters', () => {
                // https://github.com/BetterThanTomorrow/calva/issues/1122
                const a = docFromTextNotation('#|{:thing :here}');
                const b = docFromTextNotation('|{:thing :here}');
                paredit.backspace(a);
                expect(textAndSelection(a)).toEqual(textAndSelection(b));
            });
            it('Moves cursor past entire open paren, including prefix characters', () => {
                const a = docFromTextNotation('#(|foo)');
                const b = docFromTextNotation('|#(foo)');
                paredit.backspace(a);
                expect(textAndSelection(a)).toEqual(textAndSelection(b));
            });
```

Note that of these, the _ Deletes open map curly prefix/ns characters_ already passes.

My rationale behind this particular solution is that if you place the cursor somewhere ”in” a multi-character `open` token it is OK for backspace to delete things. While if the cursor is inside the list and you hit backspace twice, you get protection against accidentally removing the prefix, if the first backspace takes outside the whole `open` token.

**Comment by yuhan0** [comment]
Hmm, then I guess the same thing should happen with any other prefix character, like 
```clj
'(quotes) 
~@(splicing unquotes) 
~'#?@(:clj [un-syntax-quoted splicing reader conditional])  ; 💥 
```
I didn't notice this before but all these prefixes currently behave the same as `#` and you can't delete them individually.
In the last case your proposal would jump over 6 characters when hitting backspace from within a nonempty form? 

And should it distinguish the sequence `#_` such that you can delete it like such:
```clj
#_(|foo)
#_|(foo) 
#|(foo) 
|(foo) 
```

**Comment by PEZ** [comment]
Please see if you think this behaves like you want it to, @yuhan0 : https://12910-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.189-1122-paredit-backspace-in-open-token-d4b4134d.vsix

**Comment by PEZ** [comment]
Yes, Calva lumps together all sorts of opening ”prefix” characters. So the VSIX should now behave consistently in the new way. 😄 And the ignore marker is not considered an opening prefix so also that should work as you suggest there.

**Comment by yuhan0** [comment]
Yup, it handles all those cases exactly how I'd expect them too 👍 
Thanks for the quick fix!

**Comment by PEZ** [comment]
Thanks for being super quick in testing and responding here. It helps tons!
