### ISSUE TITLE
Allow jackInEnv per replConnectSequences 

### ISSUE THREAD

**Issue by rjerue** [BetterThanTomorrow/calva#1124]
Hello,

Thanks for all the work you all do on Calva, it's a great tool to make Clojure more accessible to the masses!

Currently in Calva, if one wished to send an `env` var to their project. There is `calva.jackInEnv` which lets one specify a JSON Object with environment variables for *all* connect sequences. I'd like to propose an option that lets one set these per object in `calva.replConnectSequences`. I imagine a `jackInEnv` could be provided in there and the json objects could be merged in the style of `{...global, ...customConnectJackIn}` where the more specific entries override the global ones.

The use case that I have is that I have different REPL connect sequences for development vs. running unit tests (different lein profiles are used). Additionally. I have different env variables that need to be used. Typically, I go into the vscode `settings.json` and change them prior to deciding what connect sequence I will be running. I'd be nice to just set the specific overrides that I need for unit tests inside of it's REPL custom connect sequence.

**Comment by PEZ** [comment]
This issue makes perfect sense to me.

>  I imagine a jackInEnv could be provided in there and the json objects could be merged in the style of {...global, ...customConnectJackIn} where the more specific entries override the global ones.

I totally agree!

**Comment by bpringe** [comment]
Closing this since #1142 was merged and released.
