### ISSUE TITLE
CLJS Repl Promises won't resolve

### ISSUE THREAD

**Issue by cljs944** [BetterThanTomorrow/calva#1128]
Hello, I am trying to use the node-repl, and everything works fine except for promises. The repl shows that a promise has been executed, but I never see the resolved output of the promise, I only see `#object[Promise [object Promise]]` in the REPL. Any ideas on what I'm doing wrong here?

**Comment by PEZ** [comment]
Maybe the output ends up in the process where the REPL is started? If it is started using Calva Jack-in, you would then see it in the Jack-in terminal pane.

**Comment by bpringe** [comment]
@cljs944 Are you using a `.then` call to get the result of the promise?

**Comment by PEZ** [comment]
I get output in the output window when I try this:

```clojure
(def prom (new js/Promise
               (fn [resolve, _reject]
                 (js/setTimeout
                  (fn [_]
                    (resolve 42))
                  5000))))

(comment
  (.then prom #(js/console.log %))
```

@cljs944:  on Slack, you said:

> also I am using the standard jack-in sequence, and then choosing node-repl  when prompted for a repl

Which I don't quite understand. If you use the `deps.edn + ClojureScript built-in for node` you should not get any more prompts. The only jack-in prompt looks like so:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/30010/115424129-b1b31200-a1fe-11eb-9743-5d206972d3a5.png">

**Comment by bpringe** [comment]
Closing this since it appears to not be an issue with Calva. Please reopen if you feel there is a problem with Calva.
