### ISSUE TITLE
calva.evaluateTopLevelFormAsComment results in vim Visual mode

### ISSUE THREAD

**Issue by kjoshi** [BetterThanTomorrow/calva#1131]
When using Calva with VSpaceCode, doing "_evaluate top-level form as comment_" (, e ; in VSpaceCode) leaves me in Vim Visual mode after the comment has been pasted.
Is there a setting I can update so that _evaluate top-level form as comment_ leaves me back in Normal mode?

Some dicussion from #calva on Slack:
> practicalli_john:
> Seems like the selection used by Calva keeps the form selected in VSpaceCode, e.g in visual select mode.
In that case a manual press of the Esc key is required it seems, unless there is a way to send an unselect at the end of the call to that function.
> ...
> It seems strange, because the previous two functions will leave the expression selected.
However, calva.evaluateSelection and calva.evaluateCurrentTopLevelForm do not leave the expression selected.

>pez:
>Indeed:
```
    vscode.workspace.applyEdit(wsEdit).then((_v) => {
        editor.selection = selection;
    });
```
> I wonder why I thought that was a good idea…

I don't know much about VSCode extensions, but I'm happy to try and help out or test possible solutions.

**Comment by PEZ** [comment]
Here is a VSIX with a fix for this. Please test. ❤️ 

https://12985-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.190-1131-eval-to-comment-decoration-f5fdb6f7.vsix

**Comment by practicalli-johnny** [comment]
Installing the VSIX file mentioned above resolved the issue on my system (Ubuntu Linux, VS Code 1.55.2)

Installation was via the command
```
code --install-extension calva-2.0.190-1131-eval-to-comment-decoration-f5fdb6f7.vsix
```
Thank you.

**Comment by kjoshi** [comment]
Installing the VSIX file has fixed the issue for me as well.
Thanks @PEZ!
