### ISSUE TITLE
Jack-in to metabase Leinigen project fails

### ISSUE THREAD

**Issue by AL4AL** [BetterThanTomorrow/calva#1149]
This is the error I encounter:
![image](https://user-images.githubusercontent.com/22044358/115993320-81e18100-a5e7-11eb-9a3d-dddbbf771f09.png)

This happens after running this command `Start a Project REPL and Connect` and by selecting any of it's options 
Here is specifications:
![image](https://user-images.githubusercontent.com/22044358/115993414-e997cc00-a5e7-11eb-8047-52f7a4f7e9b2.png)
But this command from terminal works:
`lein update-in :dependencies conj '[nrepl,"0.8.3"]' -- update-in :plugins conj '[cider/cider-nrepl,"0.26.0"]' -- update-in '[:repl-options,:nrepl-middleware]' conj '["cider.nrepl/cider-middleware"]' -- with-profile +repl repl :headless`

**Comment by bpringe** [comment]
Can you provide a project and repro steps? It could just be like "create a project with `lein new <something>...`, open the project directory in vs code, run jack-in, select option x, <etc...>" . It would be great if we can repro this ourselves. I've not yet run across this though.

**Comment by PEZ** [comment]
It's Metabase, https://github.com/metabase/metabase

I updated the title of this issue.

I've seen this problem before. It's the `#=` evaluation dispatch, They use it twice in `project.clj`.  This makes the `tools.reader/read` croak when we parse the forms in the file. We will need to find another way to read the information out of  `project.clj`.  Maybe we can somehow reach into clj-kondo/edamame inside clojure-lsp and have it do this reading for us...

Usage of `#=` is fairly uncommon, and rightly so.  It's undocumented, and I'm pretty sure I've seen Alex Miller discourage the use of it.

**Comment by PEZ** [comment]
Closing this and tracking the underlying problem in #1158
