### ISSUE TITLE
Shadowing of Clojure vars doesn't work in the REPL, even with `:refer-clojure :exclude`

### ISSUE THREAD

**Issue by alexandergunnarson** [BetterThanTomorrow/calva#1153]
As a minimal example, I have the following file:
```clojure
(ns my.namespace
  (:refer-clojure :exclude [find]))

(defn find [] "here it is")
```

When I evaluate a file within a non-Calva REPL with `load-file`, evaluating `(find)` at the REPL returns the expected `"here it is"`. However, at a Calva REPL (both with direct evaluation and with an explicit `load-file`), when I evaluate `#'find`, the var `#'clojure.core/find` is returned, and when I evaluate `#'my.namespace/find`, I get a `SyntaxError` saying `Unable to resolve var: my.namespace/find in this context`.

Seems like Calva's REPL is injecting `clojure.core` functions somewhere and preventing this sort of shadowing from taking place.

This problem seems not to happen when I just don't touch the REPL and just use key combos to load files.

**Comment by PEZ** [comment]
Hello,

I can't reproduce this. I started a standalone Calva REPL, created a new file, `my_ns.clj`, put something similar in, and then loaded the file. I got this when evaluating the things:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/30010/116188172-37671e00-a727-11eb-8145-8bc83a0e638c.png">

Or, maybe I am misunderstanding the problem?

**Comment by alexandergunnarson** [comment]
Sorry for the confusion above — I was trying to retrace my steps on an error I had seen a few times in different contexts and the bug report got muddled. Here's a reproducible path to the error on my end:

1) Put the following in an (unsaved/temporary) file/buffer in VSCode:
```
(ns my.namespace
  (:refer-clojure :exclude [find]))

(defn find [] "here it is")

(find)
```

2) Evaluate each of the forms in sequence using the appropriate key combo. Observe that this is fine, just as you say.
3) Evaluate at the REPL `(ns other.namespace)`.
4) Evaluate at the REPL `my.namespace/find`. Observe that it has "disappeared" — `Unable to resolve var: my.namespace/find in this context.`

You can also try various other things — e.g. evaluating `(find)` again in that temporary file after step 4) and observing that it's still disappeared.

There are other ways to reproduce this — initially I used some combination of `load-file` and related key combos to get to a similar place — but we can get started with this one path.

**Comment by PEZ** [comment]
OK. Yes. Unsaved files are not really supported like that. The instructions for starting a Calva session tries to avoid the culprit:

> You should start with loading the file you are working with. Do this with **Load Current File and Dependencies**, `ctrl+alt+c enter`.

https://calva.io/try-first/

Before that is done, all bets are off. However after that is done, I think that your example works even for new unsaved files.

I'm not sure why this is so, but something happens in `nrepl/load-file` that needs to happen before things start to work. Today I saw [this](https://clojureverse.org/t/clojurescript-repl-with-cider/7596/8) on ClojureVerse, regarding Emacs/CIDER, which uses the same tooling for these things (Calva is distilled from Cider):

> I have one really useful pointer which I only discovered recently: sometimes, especially when you have a large source file, you need to cider-load-buffer (C-c C-k) before doing a cider-eval-last-sexp (C-c C-e). In fact, as a rule of thumb I do that whenever I open a script containing any code I want to evaluate in the REPL, especially a large one, otherwise it can tend to hand. This also evaluates all symbols in the script and makes them available in the REPL.

**Comment by alexandergunnarson** [comment]
Ah, interesting. Thanks for the tip! So that invalidates the path to error-reproduction I outlined in my most recent comment. However, the way I came across this bug was specifically when using the load-file key combo (`ctrl+alt+c enter` as you say — I've mapped it to something else). I feel like this is somewhat of a heisenbug so I'll try to pin it down with a minimal example.

Okay, so I tried the following:

1) Define the following namespaces in saved files at the source paths appropriate to their namespace names:
```clojure
(ns namespace.temp0
  (:refer-clojure :exclude [find]))

(defn find [] "here it is")
```
```clojure 
(ns namespace.temp1
  (:require 
    [namespace.temp0 :as temp0]))

temp0/find
(temp0/find)
#'temp0/find
```
2) Use the Calva load-file command on `namespace.temp0` and then `namespace.temp1`. There is here a suspicious warning that shouldn't happen which seems to be related to this bug:
```clojure
; Evaluating file: temp0.clj
; WARNING: find already refers to: #'clojure.core/find in namespace: namespace.temp0, being replaced by: #'namespace.temp0/find
#'namespace.temp0/find
```
This means that something in Calva, or nREPL, or whatever tool in some way down the line, is not respecting `(:refer-clojure :exclude [find])`.
3) Try to repro the bug by evaluating in the file via key commands each of the elements of the `temp1` namespace one after the other. On my end everything actually did work, which was both surprising and frustrating to me trying to reproduce this.

In the setup where this is (admittedly, intermittently) failing, it's more like:
```clojure
(ns name.space0
  (:refer-clojure :exclude [find])
  ;; Lots of `require`s here
)

;; Lots of code over here

(defmacro find [...]
  ...)
```
```clojure
(ns name.space0-test
  (:require 
    [clojure.test :as test]
    [name.space0  :as space0]))

;; Lots of code over here

(deftest find-test
  ;; Lots of code in here
  (testing "this"
    (testing "other"
      (testing "thing"
        (is (= (space0/find ...) ...)))))
)
```

First I evaluate `name.space0` with the Calva load file command, then same for `name.space0`, and then observe in the REPL a `SyntaxError` saying `Unable to resolve var: space0/find in this context`. (However after repeated evaluations of these namespaces, sometimes this error goes away, and sometimes it comes back. I'm still trying to pin it down.) That said, in my mind, the particularities of where `space0/find` appears (e.g. that it's a macro being used in a `testing` block) shouldn't matter, so that's why I'm trying to just boil it down to a minimal example.

The `WARNING: find already refers to: #'clojure.core/find` is the only clue I can see currently, possibly caused by https://github.com/BetterThanTomorrow/calva/blob/b1695db6572e984536071d5f0142894afd9aac1f/src/namespace.ts#L77 . (This will create a namespace that doesn't respect `(:refer-clojure :exclude [...])` initially.) My conjecture is that this function is somehow being run again in certain edge cases and the shadowing vars (`(defmacro find ...)`) are being themselves shadowed by their `clojure.core` counterparts (`clojure.core/find`).

**Comment by alexandergunnarson** [comment]
Meanwhile I'll keep you posted if I come across a reproducible case when using only the Calva load file command.

**Comment by bpringe** [comment]
This is a great analysis. Thanks. That's an interesting theory about that `client.eval` line.

**Comment by alexandergunnarson** [comment]
No problem — thanks :)

**Comment by alexandergunnarson** [comment]
This bug unfortunately has brought my use of the Calva REPL to a screeching halt for the moment, since it introduces subtle bugs when it shadows the vars without telling me (I'm still using Calva's paredit and formatter, at least, so that's nice!) I'm just using plain old nREPL within the built-in VSCode terminal, which is working just fine, if clunkily:

```shell
clj -Sdeps '{:deps {nrepl {:mvn/version "0.8.3"}}}' -m nrepl.cmdline --connect --host localhost --port 7888
```

I'm pressed for time right now and can't provide a minimal example quite yet, but the bug really is happening in a variety of namespaces and contexts in my workflow. Happy to jump on a screenshare to demo it — I'd be willing to pay you guys a little for your time (at the rate a cash-poor startup can pay haha, so like $15/hour — enough for lunch or a few coffees) if you can fix it @bpringe @PEZ 😄

**Comment by bpringe** [comment]
So the issue doesn't seem to happen if you're not using cider-nrepl? But you're connecting to the repl you start with just nrepl? If @PEZ can't get to it first, I can join you on a screenshare some time this weekend at the latest. I can't guarantee a quick fix though. I'm not even sure what's really happening yet. :smile:

**Comment by alexandergunnarson** [comment]
I'm not sure about `cider-nrepl` (is that what Calva uses?), but to be clear, here's what's happening:

**Approach 1 (works)**

1. Go to external terminal (I use Alacritty, but it's probably not important). Run the appropriate command to launch a REPL. 
2. Start an nREPL server via:
```clojure
(require 'clojure.tools.nrepl.server)
(defonce server (clojure.tools.nrepl.server/start-server :bind "localhost" :port 7888))
```
3. Go to VSCode's built-in terminal. Start an nREPL client via the following command:
```shell
clj -Sdeps '{:deps {nrepl {:mvn/version "0.8.3"}}}' -m nrepl.cmdline --connect --host localhost --port 7888
```
4. At this point let's say we have two namespaces, `ns0` and `ns1`. `ns0` shadows a `clojure.core` var, via `(defn find ...)`. `ns1` `require`s `ns0` and refers to `ns0/find` in the body of the namespace.
5. Evaluate `(load-file <path-to-ns1>)` in the REPL.
6. Observe that the loading works correctly.

**Approach 2 (fails)**

1. Same as Approach 1, step 1.
2. Same as Approach 1, step 2.
3. Start a Calva nREPL client session with the appropriate key combo. Specify 7888 as the port.
4. Same as Approach 1, step 4.
5. Use the appropriate key combo to evaluate the file corresponding to `ns1` in the running Calva nREPL.
6. Observe that the loading sporadically fails: sometimes Calva will say `Unable to resolve var: ns0/find in this context`. (There are other related problems, like sometimes `ns0/find` will be bound to `clojure.core/find` without any warning until you figure this fact out later by accident.)

Without a repeatable example for how to encounter Approach 2, step 6, I understand it's hard to proceed. So a screenshare would be perfect and would probably save you time sifting through my verbosity here 😄

**Comment by alexandergunnarson** [comment]
@bpringe @PEZ I'll make myself available any day except Sunday, and any time except 11pm-7am Pacific Time. Let me know what works!

**Comment by PEZ** [comment]
I will need to handle this off-line for now. Too many things on my plate right now. But you two should of course go ahead and I'll try to keep some kind of service level up from my off-line position.

I tested your setup with the two example files, @alexandergunnarson. I also get the warning when loading `temp0`. (And also couldn't reproduce the actual error that way.)

It would be good to know if this is upstream or something Calva is doing wrong. Easiest way to test that is to do the same thing using Emacs/CIDER.

**Comment by bpringe** [comment]
@alexandergunnarson, I messaged you on the Clojurians Slack yesterday to try to schedule a call time for today, but maybe you haven't checked that Slack in a while. I have some other things to do today so maybe another time would be good. I know you said not Sunday, so some time during the week, 5:30pm PDT or later would be good for me.

However, if you have uses Emacs/Cider before and can test this there easily as Peter was saying that would be great. Also, we should explore your hunch too with Calva evaluating the `ns` form without the `:refer-clojure` right before user evaluations. We could make Calva instead grab the entire `ns` form and evaluate that before user evaluations, and see if that helps.

**Comment by alexandergunnarson** [comment]
Understood @PEZ. I'll have to get Emacs/CIDER set up — never used it (just mainly have used Sublime, Atom, and now VSCode). I'll check out what that says.

@bpringe I messaged you back just now — sorry about that. Slack never emailed me for whatever reason. Signed into Clojurians on my computer now so we should be good. Let's coordinate about times / Zoom links there! (Short story: tomorrow afternoon opened up for me if it works for you.) I'll try to get Emacs/CIDER set up and see if I can reproduce the issue there.

**Comment by alexandergunnarson** [comment]
So, evaluating `name.space0-test` (as seen above), then `name.space0`, then `name.space0-test` again (all with Calva key commands) yields a compilation error in Calva, but doing the same in Emacs/CIDER (using CIDER key commands) is just fine. Preliminarily, the problem seems to be isolated to Calva as opposed to affecting CIDER, which lines up with what I was seeing when running nREPL in VSCode's built-in terminal (which is also fine). I also upgraded to `[nrepl/nrepl "0.8.3"]` since Emacs complained about the `[org.clojure/tools.nrepl "0.2.13"]` I had, but that didn't appear to help Calva.

Will try to pin down a reproducible case.

**Comment by PEZ** [comment]
Awesome. Thanks for checking that with CIDER.

I think we do some `in-ns` evaluations that CIDER does not do, and now suspect that as being the source of the problem. And applying @bpringe 's plan about figuring out the right order of doing things, I hope we can keep doing the `in-ns` things.

Hope to see you in the #calva channel at Clojurians Slack, @alexandergunnarson ! Faster turnaround on the communication that way.

**Comment by bpringe** [comment]
Had a great zoom chat with @alexandergunnarson. Although we don't have a consistent reproduction still, here are some notes:

* Running `(ns <namespace>)` for a namespace that was previously loaded will re-refer clojure.core and override any symbols that were the overridden by the user with `:refer-clojure`. I'm not sure if this ever happens since Calva only runs that if the namespace hasn't been created yet (maybe worth verifying), but even still, it probably should be the whole namespace form that's run here (or at least that's something to try): https://github.com/BetterThanTomorrow/calva/blob/b1695db6572e984536071d5f0142894afd9aac1f/src/namespace.ts#L77
* It might be worth investigating our load-file command implementation. In our call at least, when Alex called `load-file` directly in the repl, the warning did not occur. We did see, however, that calling Calva's load-file command sometimes gives the warning.

@alexandergunnarson, if I forgot something or you have something else to add, please add it.

**Comment by alexandergunnarson** [comment]
Good summary @bpringe! Thanks again for the call — it was fun 😊

**Comment by bpringe** [comment]
Same to you!

**Comment by alexandergunnarson** [comment]
FWIW this also happens with a "headless" Calva REPL, meaning when there's an nREPL connection managed by Calva, but the Calva REPL window/file is not present. Steps to reproduce:

1. Launch Calva REPL client using normal commands to connect to running nREPL server
2. Close Calva REPL window/file (the nREPL client connection will continue to run in the background)
3. Evaluate the files as detailed above
4. Observe the `:refer-clojure` warning and then evaluation error

Maybe it was obvious that this would be the case, but then again maybe it's nice to explicitly take away the variable of the REPL window/file.

**Comment by PEZ** [comment]
I haven't read up fully on this so bare with me if this is a stupid question.

Are we doing the mistake mentioned here? https://clojure.org/guides/repl/navigating_namespaces#_how_things_can_go_wrong

**Comment by alexandergunnarson** [comment]
Heh no worries! No, that is distinct from what's happening here. Wish it were that simple 😄

**Comment by bpringe** [comment]
@alexandergunnarson Have you still been having this issue and/or been working around it?

I've tried to figure out an approach to this. If I jack-in, then evaluate a file with this code:

```clojure
(ns issue1153
  (:refer-clojure :exclude [find]))

(defn find [] "here it is")
```

Each time the loading the file succeeds without a warning, and `find` refers to `issue1153/find`.

However, I can reproduce the warning _sometimes_ with a combo of actions, some of which I'm not sure are relevant, but I'll list them for the sake of reproduction:

1. Jack-in
2. In the file with the `:refer-clojure :exclude [find]` and the `defn find ...`, eval the var `find` with `ctrl+enter` (eval current form) - see that it refers to `clojure.core/find`
3. Run the load-file command, and see the warning

The above events happen most of the time, though sometimes at step 2, evaluating `find` gives a syntax error (unable to resolve symbol `find`) instead of showing it referring to `clojure.core/find`, and of course in that instance, subsequently running load-file does not produce the warning.

I think what the above and other happenings described in this thread show is that there is at least one, but maybe multiple nondeterministic outcomes of functionality that's run in between issuing the jack-in command, and seeing or not seeing the warning. By functionality I mean whatever Calva is doing during jack-in, after jack-in, on evaluation, possibly on editor switching/focusing, etc.

I even saw sometimes stacktrace code lens appear in the repl window while I was trying to reproduce the warning, when there was no other indication that an error occurred (and the stacktrace code lens repeated several times, which is a bug that I think has been reported elsewhere). When I look at the stacktrace it just looked like some kind of clj/tooling error.

## Summary

Even though we can't consistently reproduce the issue, I think it's evident that there is likely some issue in our load-file implementation and/or our evaluation implementation. It would probably be worth visiting both and seeing if anything could be changed or simplified for the better. This needs to be done carefully, of course.

**Comment by alexandergunnarson** [comment]
Hey Brandon — sorry for the huge delay. Super busy on our end so haven't paid attention to tooling for a while.

To your question, I've been working around the issue by just copying the absolute file path in VSCode and using `load-file` manually in an nREPL in the VSCode command line sidebar. Not ideal, but it's reasonably quick and it does the job. I find my main slowdown was lack of autoformatting, so now that that's taken care of, I'm not as picky about the other tooling around it.

**Comment by bpringe** [comment]
@alexandergunnarson This new feature might help in diagnosing the problem: https://calva.io/nrepl_and_cider-nrepl/#viewing-the-communication-between-calva-and-nrepl. There may be some evidence of something odd happening that could cause the problem in the nREPL messages.

**Comment by alexandergunnarson** [comment]
Sorry, message got buried in my inbox for a time. Thanks for the update! I'll look into it at some point.

**Comment by alexandergunnarson** [comment]
Interestingly, I haven't been seeing this problem crop up when going back to Calva in the last few days (after using `load-file` manually for months since we last talked). I'll let you know if I hit this bug again. Looking good so far! 🤞

**Comment by bpringe** [comment]
Thanks for letting us know! 🤞
