### ISSUE TITLE
[REPL Window] Autocompleting with tab leaves initial user input

### ISSUE THREAD

**Issue by il-tmfv** [BetterThanTomorrow/calva#116]
Let say you switched to some `ns`. This `ns` has `fn` `to-param`.
Steps to reproduce:
- start typing `to-`
- select `to-param` in suggestions
- press `tab`
Expected result: you see `=> to-param`
Actual result: you see `=> to-to-param`

BTW, If you start to type in `()` then everything is fine.

**Comment by mseddon** [comment]
Should be fixed in https://github.com/BetterThanTomorrow/calva/commit/5fc1f7d44f8ae19b74be06441f45a861501cc8aa

**Comment by il-tmfv** [comment]
I cannot reproduce it in SNAPSHOT-1 🎉
