### ISSUE TITLE
Add gutter icons for indicating test pass/fail

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1163]
Cursive has gutter icons like this: https://cursive-ide.com/userguide/testing.html

I'm not a fan of the red lines for failures, which Cursive and Calva both do (though I think Calva does a bit more sparingly). The underlines remind me of linting warnings. Maybe a red background like Mocha Test Explorer adds would be good, in addition to the gutter icon.

**Comment by PEZ** [comment]
Much prefer if this is addressed with an integration with Test Explorer.

Like you suggest here: #953 😄

**Comment by bpringe** [comment]
I consider this a small thing that's separate from integrating with Test Explorer, but if you really want to bundle it with that, then that's fine.

**Comment by bpringe** [comment]
I realize now that the gutter icons are part of the Test Explorer UI: https://github.com/hbenl/vscode-test-explorer#configuration. Sorry if I misunderstood!

**Comment by PEZ** [comment]
Well, we can add gutter decorations without Test Explorer. As a small thing, like you said.

I don't think you misunderstood anything, until right there at the end. 😄

**Comment by bpringe** [comment]
This should have been closed in the past.
