### ISSUE TITLE
Debugger decorations are not working properly

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1165]
Debugger decorations were working fine before from what I know, after I spent some time on fixes and enhancements in the past. I noticed while working on another debugger feature that they are functioning oddly now. The only thing I know off hand that changed is the version of clojure-lsp, but since the code uses lsp to get references, and I doubt there's a mistake with lsp, I'll have to revisit the code :disappointed:.

Hopefully I can find a more resilient solution.

Repro:

```clojure
(ns hello)

(defn thing [x]
  (println x))

(comment
  (thing "foo"))
```

1. Instrument `thing`
2. Add a newline before the call to `thing` in the `comment` form, notice the decoration there disappears.
3. Add letters to the call to `thing` or  remove letters, i.e. `things` or `thin` and notice weird behavior with the decoration showing up when or where it shouldn't, or not showing up when it should

Seems likely to be a problem with the timing of the update/render.

**Comment by bpringe** [comment]
An idea came to me so I'll put it here, though I haven't investigated it yet. The issue could be because of a timing issue with when clojure-lsp updates its database of where references are located, and when we send a request to get the locations. We may be able to fix this by waiting a short time after a document update to send the request for reference locations.

It may also help to clear decorations right after a doc update, then render them again when we get the new locations. This way there won't be moments when (or they'll be hopefully too short to notice) the decorations are off between document update and re-render of decorations. I think a flicker off/on of the decorations is better than a moment of a buggy-looking rendering.

We may just need to increase the debounce time here: https://github.com/BetterThanTomorrow/calva/blob/35f1490fe0a8e43b3c19ecab37a83edf2a1973d3/src/debugger/decorations.ts#L99

**Comment by PEZ** [comment]
By chance I found the issue. It is `nsPath()` on the repl session that returns blank. So we don't get any document uri:

https://github.com/BetterThanTomorrow/calva/blob/dev/src/debugger/decorations.ts#L48

Changing to get the Uri from `editor.document.uri` works though. But seems there might have been a reason why this was not used to begin with. Do you recall, @bpringe?

**Comment by bpringe** [comment]
I don't recall right now if there was a reason to use `nsPath()`, but I'm glad it seems to be fixed now!
