### ISSUE TITLE
Feature request: Jump back and forth between Clojure source and its test

### ISSUE THREAD

**Issue by rudolfvesely** [BetterThanTomorrow/calva#1168]
Dear Calva developers,

[As discussed on Clojureverse](https://clojureverse.org/t/we-created-and-maintain-calva-ask-us-anything/7131/18?u=rudolfvesely), I'd like to kindly ask to add the following feature:

* A command called "Clojure source/test jump" with or without specified key binding.
* When executed for example from a file `src/a/b/c.clj` Calva will open a file `test/a/b/c_test.clj` and then when executed again Calva will focus to the the source file `src/a/b/c.clj`.
* If the test file is missing, Calva will ask to create it with the following content:
``` clojure
(ns a.b.c-test
  (:require [clojure.test :refer :all]
            [a.b.c :as t]))
```
* If the source file is missing, Calva will ask to create it with the following content:
``` clojure
(ns a.b.c)
```
* Files are created with all parent directories in case they're missing

There is already a similar extension for Elixir called [Elixir Test](https://marketplace.visualstudio.com/items?itemName=samuel-pordeus.elixir-test) that has exactly this functionality so you may consider to take a look at its code (MIT licensed) to see how it's implemented.

Thank you.

Kind regards,

Rudolf Vesely

**Comment by PEZ** [comment]
Thanks! There is some prior art in Calva as well, in the way the `ctrl+alt+c o` shortcut jumps between the output window and the source file of the current namespace.

**Comment by rudolfvesely** [comment]
Output window jump is great. Thank you PEZ!

For those looking for the command name:

``` json
{
    "key": "ctrl+alt+c o",
    "command": "calva.showOutputWindow",
    "when": "calva:connected && calva:connected && calva:keybindingsEnabled && !calva:outputWindowActive"
},
{
    "key": "ctrl+alt+c o",
    "command": "calva.showFileForOutputWindowNS",
    "when": "calva:connected && calva:connected && calva:keybindingsEnabled && calva:outputWindowActive"
},
```

**Comment by pratik97** [comment]
@PEZ @bpringe I'd like to work on this feature if it's not yet assigned. I looked at [this](https://github.com/samuelpordeus/vscode-elixir-test/blob/7925920d73cf5646a6400cf667568bf9fa769ab1/src/commands/jumpToTest.js#L4) module of Elixir test repo that @rudolfvesely mentioned and I can implement similar thing for Calva unless you guys have some other ideas.

**Comment by PEZ** [comment]
@pratik97 please do! And please holler or way in the calva channel over at the Clojurians slack.

**Comment by bpringe** [comment]
Just moving this info from Slack: if we make the way this feature calculates/finds test namespaces account for more possibilities than just the test namespace being the same plus `-test`, maybe we should also consider changing the implementation of the command for running namespace tests, which I think only checks for the `-test` variety of test namespace: https://github.com/BetterThanTomorrow/calva/blob/210e8161568f97f02da59f91a3a99af332ec433b/src/testRunner.ts#L123

@seancorfield mentioned that there are different conventions used for test namespace and file organization:

> and most test runners have options so you can tell them the directory structure and namespace pattern to use, so I think this really should expose those settings from the get-go

We should probably either add settings like this, or implement this in such a way that it accounts for a majority of cases.

**Comment by bpringe** [comment]
Maybe this goes without saying, but I think we should keep this implementation as simple as possible so as to reduce future maintenance work/requests on it. If that means just implementing it for one convention, without settings, and documenting that it's just a convenience feature _if you use x convention_, I think that would be fine.

Also, thank you @pratik97 for working on this!

**Comment by PEZ** [comment]
I agree about starting simple, with few settings.

**Comment by seancorfield** [comment]
The cases to consider:

* Where are tests? 
  * Many simple projects have just a `src` and a `test` folder so you can fairly safely go from `/path/to/src/foo/bar.clj` to `/path/to/test/foo/bar_test.clj` and back again.
  * However, a number of projects -- such as Contrib libraries and almost any projects that have Clojure + Java -- tend to have `src/main` and `src/test` -- or `src/main/<lang>` and `src/test/<lang>` -- so I would suggest that if you're in `src/test/foo/bar_test.clj` you'd want to look for `src/main/foo/bar.clj` and vice versa (test cases to bear in mind: `src/main/foo/bar.cljs` and `test/main/foo/bar_test.cljs`; `src/main/cljs/foo/bar.cljs` and `test/main/cljs/foo/bar_test.cljs`; both cases have `foo.bar` and `foo.bar-test` for their namespaces).
  * There are other patterns -- typically in repos that have `.clj`, `.cljs`, and `.cljc` -- but those mostly seem to be `src/cljs/foo/bar.cljs` and `test/cljs/foo/bar_test.cljs` so a swapping of `src` for `test` and addition of `_test` or removal of it are going to catch most cases. Caveat: again, with repos that have `src/<lang>/foo/bar.clj*`, the `<lang>` portion is _not_ part of the namespace, but you should be able to follow the lead of whatever file you are in and not worry about the actual path (beyond making source and test match).
* File extensions:
  * I think you'll get most cases by just keeping the same file extension between source and test files, and if you offer to create a new file, offer the same file extension as the "original", whichever direction you're going in.

I think you could do all of that without adding any options -- even though you'd need to support the "simple" style and "Maven" style paths (`src/main` & `src/test`).

This would be a reasonable test case: https://github.com/clojure/tools.cli -- it follows the Maven structure and uses `.cljc` files. 

Not sure if you'd want to support this as a test case: https://github.com/clojure/data.xml -- the test files have `test_` at the _beginning_ of the file name (and `test-` in the namespace).

Of course, I would love to see this support additional test filename patterns (such as `_expectations.clj*` and `-expectations` in the namespace) but that's definitely a minority of users -- so for the first version of it, just supporting `_test`/`-test` should be fine.

LMK if you have any Qs about that.

**Comment by pratik97** [comment]
makes sense, @seancorfield thanks for your inputs! I will work on adding extra look-up path and the file extensions.
