### ISSUE TITLE
Add information about `jackInEnv` to the documention

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1170]
Now we have both a ”global” jackInEnv and, thanks to @rjerue , also in the Jack-in sequences. On [calva.io](https://calva.io), only the sequence setting is documented.  We should find out a good place to host info about the ”global” one as well.

And  for that one we should document the interpolation behaviour of things like `${env:FOO}`.

**Comment by rjerue** [comment]
https://calva.io/connect-sequences/ it looks live on this page?

**Comment by PEZ** [comment]
You're right. It's actually the global one that lacks proper documentation.

And the info about that existing environment variables can be interpolated use lacking as well.

**Comment by bpringe** [comment]
I see info about that here: https://calva.io/connect/#customizing-jack-in. Was that added since this issue was created?

**Comment by PEZ** [comment]
Maybe this is already covered then?

**Comment by PEZ** [comment]
No, the global `calva.jackInEnv` isn't documented.

**Comment by PEZ** [comment]
Hmmm, now I see it again. I don't know why I can't find it when I look for it. Maybe we need some links at places where I look. 😄
