### ISSUE TITLE
Slurp-forward may cause syntax error by adding unmatched paren instead of slurping

### ISSUE THREAD

**Issue by pbwolf** [BetterThanTomorrow/calva#1171]
Starting with this

```
(def foo
  (str
   )
  42)
```
Point within the str form, e.g., after the r
Slurp forward

```
(def foo
  (str)
  42))
```

The str did not embrace the following form, but instead lost some whitespace; and an unmatched close-paren, which Calva highlights in red, got added at the end of the following form.

Whitespace inside the end of the str form seems to be the key to the matter.  If there is none, then slurp-forward works as expected by bringing the 42 into the str form.

Observed in Calva 2.0.195

**Comment by PEZ** [comment]
Thanks! I could reproduce this in a unit test.

How would we ideally want the form to look like after slurping? Using a `|` to mark the cursor here:

**Before**:

```clojure
(def foo
  (str|
   )
  42)
```

**After A** (this is probably easiest to achieve):

```clojure
(def foo
  (str|

  42))
```

**After B**:

```clojure
(def foo
  (str|
  42))
```

**After C**:

```clojure
(def foo
  (str| 42))
```

C has the advantage that if you want to keep `42` on the next line you can just press `enter`. OTOH, from A, B is just a `ctrl+j` away. (And C just another `ctrl+j` away.

I'll first see what seems simplest.

**Comment by PEZ** [comment]
As I guessed, option A was easiest so I implemented that. Please see the PR #1172 for some more details and request for help testing this.

**Comment by pbwolf** [comment]
Works great!
