### ISSUE TITLE
Use vanilla cljfmt for regular formatting

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1179]
Formatting of code with namespaced keywords does not work (or does not work well?) currently. @PEZ suggested updating our fork of cljfmt would fix the issue.

**Comment by PEZ** [comment]
I did some work on it a month ago or so, actually: https://github.com/BetterThanTomorrow/cljfmt/tree/pez/align-pairs

Things have moved a lot under our feet here, much thanks to @lread. I could almost get it to work, but the align code misbehaves like crazy. I'm thinking that maybe we should solve the aligniment som other way and use vanilla `cljfmt` for the regular formatting...

**Comment by PEZ** [comment]
I of course mean that it is super duper great that things have moved, in case that wasn't all that clear. 😄

**Comment by bpringe** [comment]
> I'm thinking that maybe we should solve the aligniment som other way and use vanilla cljfmt for the regular formatting...

This seems to be a good idea to me.
