### ISSUE TITLE
[REPL Window] Bug: Copy and paste to/from REPL not working in vscode on windows

### ISSUE THREAD

**Issue by tomdl89** [BetterThanTomorrow/calva#118]
Ctrl-C and Ctrl-V are not copying/pasting to/from the new REPL window for me. Even running the `calva.copyLastResults` command doesn't work.

vscode details:
```
Version: 1.30.2 (system setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
```

**Comment by mseddon** [comment]
Should be fixed in https://github.com/BetterThanTomorrow/calva/commit/5fc1f7d44f8ae19b74be06441f45a861501cc8aa

**Comment by tomdl89** [comment]
Looks to be fixed. Very fast work! Thanks
