### ISSUE TITLE
Support custom clojure-lsp path

### ISSUE THREAD

**Issue by ericdallo** [BetterThanTomorrow/calva#1181]
I'm a NixOS user and most programs don't work unless you install it via the nix way, for example [clojure-lsp](https://clojure-lsp.github.io/clojure-lsp/installation/#nix), so the way Calva install clojure-lsp ATM doesn't work for Nix users.
Maybe Calva could have an option to specify the clojure-lsp path similar to how lsp-mode does [here](https://emacs-lsp.github.io/lsp-mode/page/lsp-clojure/#lsp-clojure-custom-server-command)

**Comment by ericdallo** [comment]
c/c @bpringe

**Comment by bpringe** [comment]
Sounds great. I think I actually started to add this when doing other changes, but I decided to hold off on it and see if it would be needed/requested later, and here it is. :smile:
