### ISSUE TITLE
Calva Jack in fails

### ISSUE THREAD

**Issue by SockworkOrange** [BetterThanTomorrow/calva#1182]
When I run "Calva: Start a Project REPL and Connect (aka Jack-In)" it fails with:
command "...." resulted in an error(running the contributed command calva.jackin failed).

I can't find any additional indicative message.

vscode version: 1.56.2
calva version: latest
leiningen version: 2.9.1 
clojure version:  1.10.3
java version: 11
operating system: kubuntu 20.04 (I have the exact same OS in a different computer - there it works perfectly).

![image](https://user-images.githubusercontent.com/26390445/118408949-aa154a80-b690-11eb-81bc-abc7e62d554d.png)

**Comment by bpringe** [comment]
Hello! Thanks for the report and info. Let's troubleshoot.

1. Does the terminal where the repl is being started show any error messages? Another place where you may be able to find some useful information is the developer console. `Help -> Toggle Developer Tools -> Console tab`.
2. Please describe the choices you make during jack-in (project type, etc.)
3. Does this happen in a fresh, new, minimal project? (such as one created with `lein new app ...`)

**Comment by SockworkOrange** [comment]
1. No errors in the terminal. In the console you can see these errors:
`workbench.desktop.main.js:2237 [[object Object]]Cannot read property 'setDecorations' of undefined
workbench.desktop.main.js:2237 TypeError: Cannot read property 'setDecorations' of undefined
	at /home/kubuntu/.vscod…/out/extension.js:2
	at Array.forEach (<anonymous>)
	at W (/home/kubuntu/.vscod…/out/extension.js:2)
	at Timeout.M [as _onTimeout] (/home/kubuntu/.vscod…/out/extension.js:2)
	at listOnTimeout (internal/timers.js:554)
	at processTimers (internal/timers.js:497)
workbench.desktop.main.js:735 Command 'Calva: Start a Project REPL and Connect (aka Jack-In)' resulted in an error (Running the contributed command: 'calva.jackIn' failed.)`

2. Don't fully understand the question here. It happens on every jack in on that computer - regardless of the choice, and it doesn't happen in the 2nd computer - regardless any choice.
3. Yes, I tested it with a new project and an existing project - behaves the same.

**Comment by bpringe** [comment]
Hmm, it's hard to figure out what's going wrong with being able to repro it myself. On the machine where it doesn't work, if you [run Calva in dev mode](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva) and set a breakpoint in the jack-in command and step through it, you should get an idea of where it's going wrong.

The jackin process starts here: https://github.com/BetterThanTomorrow/calva/blob/a1afb5799bc8f1e4063badb8964f462b1da7dfcc/src/nrepl/jack-in.ts#

**Comment by SockworkOrange** [comment]
will test it this weekend and will update here

**Comment by SockworkOrange** [comment]
can't re-produce since I formatted my computer (unrelated reason) and the issue isn't reproduced there.
if it will occur again, will re-open
