### ISSUE TITLE
Calva start clojure-lsp client failed

### ISSUE THREAD

**Issue by stardiviner** [BetterThanTomorrow/calva#1183]
![Screen Shot 2021-05-22 at 11 22 46 AM](https://user-images.githubusercontent.com/378699/119213219-1dcfb100-baf0-11eb-8282-bf2aab559825.png)

Here is the error.

I'm using M1 macOS under latest version of macOS system and latest version of Calva.

**Comment by stardiviner** [comment]
I tried to install `clojure-lsp` from homebrew. But still got this error.

**Comment by PEZ** [comment]
I've had this error too, once. It started working after a reload of the VSCode window.

(Calva bundles its own clojure-lsp client.)

**Comment by bpringe** [comment]
@stardiviner Did reloading the VSCode window help? If not, please paste the contents of the developer console here, after reloading VSCode and receiving the error. `Help -> Toggle Developer Tools` -> `Console tab`

**Comment by stardiviner** [comment]
@PEZ I already tried restart vscode and reload window too. not working. Thanks.
@PEZ Not working.

Here is the output log (which also contains other error and warnings, I can't separate them, sorry for too much long log).

https://gist.github.com/stardiviner/992387b6b1ceda72d7d9e2040c0a138d

**Comment by bpringe** [comment]
It looks like you may have some issue with your network, or somehow requests are being redirected to `127.0.0.1:1081`.

I see in your logs `ECONNREFUSED 127.0.0.1:1081` multiple times in your logs, and they're not just related to Calva.

Here are some Calva-related errors:

I'm not sure if the below one is related to the issue at hand, but wondering if @PEZ knows why this might happen.

```
workbench.desktop.main.js:62 [Extension Host] Failed activating Paredit: command 'paredit.forwardSexp' already exists
```

Here we can see the download of the clojure-lsp client failed because of that connect error:

```
workbench.desktop.main.js:62 [Extension Host] Error downloading clojure-lsp. Error: connect ECONNREFUSED 127.0.0.1:1081
```

It tries to start the backup, but maybe it doesn't exist or is corrupt:

```
workbench.desktop.main.js:62 [Extension Host] Starting clojure-lsp at /Users/stardiviner/.vscode/extensions/betterthantomorrow.calva-2.0.197/clojure-lsp_backup
workbench.desktop.main.js:735 Couldn't start client Clojure Language Client

workbench.desktop.main.js:627   ERR spawn /Users/stardiviner/.vscode/extensions/betterthantomorrow.calva-2.0.197/clojure-lsp_backup ENOENT: Error: spawn /Users/stardiviner/.vscode/extensions/betterthantomorrow.calva-2.0.197/clojure-lsp_backup ENOENT
```

@PEZ Any clues here? Looks like some kind of networking issue on their machine.

**Comment by stardiviner** [comment]
I understand why this problem. I have a proxy software running. I will do some testing and report result later. Thanks @bpringe  for your investigating.

**Comment by stardiviner** [comment]
I checked my macOS network preference, found it has `http://127.0.0.1:8070/proxy.pac`. But this PAC proxy port is not same with vscode log error `1081`.

![Screen Shot 2021-05-28 at 10 19 40 AM](https://user-images.githubusercontent.com/378699/119920078-46e3bc00-bf9e-11eb-99e6-70f1783fb15a.png)

Then I checked the proxy app's config. Not found 1081 port proxy settings. I'm using port `1086` instead.

![Screen Shot 2021-05-28 at 10 19 57 AM](https://user-images.githubusercontent.com/378699/119920082-4814e900-bf9e-11eb-8256-f299ed615691.png)

After I quit the proxy app. I restart vscode, check the "Clojure Language Client" log panel. Here is the output:

```
May 28, 2021 10:24:56 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFO: Unsupported notification method: $/setTraceNotification
```

Seems the problem is solved.

**Comment by bpringe** [comment]
Well... glad it's working now. :smile: I'll close this now. Reopen if it starts happening again and you can't fix it.

**Comment by stardiviner** [comment]
I finally found the `1081` port location. It's in proxy app's PAC file definition.
```js
var V2Ray = "SOCKS5 127.0.0.1:1081; SOCKS 127.0.0.1:1081; DIRECT;";
```
Hope this will be helpful for other user which have same problem.

**Comment by stardiviner** [comment]
@bpringe Thanks for your help, really glad. 😄

**Comment by bpringe** [comment]
No problem! Thanks for reporting your issue details. It may help others, as you said.

**Comment by PEZ** [comment]
You are a star, @bpringe !
