### ISSUE TITLE
Syntax errors on `output.calva-repl`

### ISSUE THREAD

**Issue by meinside** [BetterThanTomorrow/calva#1184]
Hi,

I haven't used calva for sometime, and found out today that the repl tab emits syntax errors on its own outputs.

I think there might be some problems with my outdated settings of calva or vscode, but I cannot figure out what is wrong.

Is there anything I should check out?

<img width="1680" alt="Screenshot 2021-05-25 AM 11 21 58" src="https://user-images.githubusercontent.com/185988/119431083-e873cf00-bd4c-11eb-9723-a5aaec8513af.png">

**Comment by PEZ** [comment]
Hello,

I think that might come from some other extension. See if the dev console (which you can open from the Help menu) provides some hint.

**Comment by meinside** [comment]
Thank you for your suggestion.
Unfortunately, I don't see relevant logs from the developer console.
I'll try turning on and off other extensions.

**Comment by meinside** [comment]
Disabling [this extension](https://marketplace.visualstudio.com/items?itemName=martinklepsch.clojure-joker-linter) fixed my issue.
Thank you :-)
