### ISSUE TITLE
Add nrepl message logging

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1198]
This has been discussed before, and I believe Cider has this. It could help us debug some issues, such as #1153, but probably several others.

I think an output channel would be good for this. What do you think @PEZ?

**Comment by bpringe** [comment]
This is the feature in Cider: https://docs.cider.mx/cider/1.1/troubleshooting.html#debugging-the-communication-with-nrepl

**Comment by ieugen** [comment]
I would also like to see this. Working on a nrepl ssh transport and debugging the messages sent between client and server would come in handy.
