### ISSUE TITLE
[REPL Window] REPL becomes semi-disconnected when dismissing the class connection  popup

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#120]
In a Clojure only project I get a Figwheel connection prompt a while after connecting the CLJ REPL. if I dismiss this prompt I get a message about Figwheel connect having failed and then can't do stuff like evaluating forms inline in the editor.

However. if I press enter on that prompt, without selecting the sole Figwheel option I get no error messages and things continue to work. It took me a while to even test that. :smile:

I think Calva should be able to figure out that there is no Figwheel in the project and refrain from prompting about it. But as a minimum we could have a Ux where the prompt also has a "No thanks” option, and that does not continue to try connect figwheel if it is dismissed with ESC.

**Comment by cfehse** [comment]
@PEZ 

This is fixed, isn't it? I have newer seen the prompt. I close this issue for now.
