### ISSUE TITLE
Using Remote-Containers w/ `clojure:lein` container, extension doesn't work.

### ISSUE THREAD

**Issue by bdruth** [BetterThanTomorrow/calva#1202]
Hope this is the right place to report this, apologies if not.

I'm trying to get this extension working under `Remote-Containers`, i.e. when VS code is running while connected to a Docker container. The container is just a vanilla `clojure:lein` image. The `Clojure Language Client` output reports 

```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[Info  - 3:01:59 PM] Connection to server got closed. Server will restart.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[Info  - 3:02:00 PM] Connection to server got closed. Server will restart.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[Info  - 3:02:00 PM] Connection to server got closed. Server will restart.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[Info  - 3:02:00 PM] Connection to server got closed. Server will restart.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
[Error - 3:02:00 PM] Connection to server got closed. Server will not be restarted.
```

And the taskbar just has _Initializing Clojure language features via clojure-lsp_ spinning ... what additional information can I provide?

**Comment by bpringe** [comment]
Hi. Thanks for reporting. Do other features of Calva work, besides clojure-lsp features?

I haven't used VS Code in that way before, but I'll take a guess at what's going on here. Calva downloads the clojure-lsp native binary that corresponds to the OS it detects. I'm guessing your host OS is not the same as the container OS. I think maybe ​Calva is downloading the native binary for the container OS and then trying to start it on the host OS. Clojure-lsp runs as a separate process outside of VS Code, presumable on the host OS in this situation.

I'm not sure if this would work, but you may be able to set the path to a clojure-lsp binary (for your host OS, that you download from the clojure-lsp repo's releases) on your host OS for Calva to use. See how to do that here: https://calva.io/clojure-lsp/#using-a-custom-clojure-lsp-native-binary.

Let me know if this seems like the issue, and if the solution above works for you.

**Comment by bpringe** [comment]
Closing this, but we can reopen it if needed.
