### ISSUE TITLE
Custom repl commands show error if run from non-clojure file

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1203]
When running a custom repl command from a non-clojure file VS Code shows an error that the command resulted in an error. We should more gracefully handle this situation, maybe by informing the user that the commands can only be run from clojure files.

![image](https://user-images.githubusercontent.com/12722744/122099749-35d0e280-cdc7-11eb-8836-e11701352ac2.png)

**Comment by PEZ** [comment]
Maybe not enable the command in non-clojure files? And also not enable any of the shortcuts in that case.

That would make it difficult to provoke this situation and we wouldn't need to handle it more gracefully. 😄

**Comment by bpringe** [comment]
That's arguably another way of handling it gracefully. :smile:

**Comment by leifericf** [comment]
I see that this is already fixed and merged in [this commit](https://github.com/BetterThanTomorrow/calva/pull/1221/commits/5555fbfd97e0eca90d22323b272d58f4750bbf6f).

It checks the language identifier to enable the command (`editorLangId == clojure`).

But is _"Run Custom REPL Command"_ supposed to work for ClojureScript? Currently, the command does not show up for ClojureScript files, but I'm unsure whether it should show up.

As far as I can tell from [the documentation](https://code.visualstudio.com/docs/languages/identifiers), Visual Studio Code does not have a Language Identifier for ClojureScript.

**Comment by leifericf** [comment]
Ah! Upon further inspection, I found [this](https://github.com/BetterThanTomorrow/calva/blob/020ab0ae51a400bd84150f9699794c5e8d81fc74/package.json#L83-L105) in `calva/package.json`:

```
    "languages": [
      {
        "id": "clojure",
        "aliases": [
          "Clojure",
          "clojure"
        ],
        "extensions": [
          ".clj",
          ".cljs",
          ".cljc",
          ".cljd",
          ".cljx",
          ".clojure",
          ".edn",
          ".joke",
          ".boot",
          ".bb",
          ".calva-repl"
        ],
        "configuration": "./language-configuration.json"
      }
    ]
```

Which includes the ClojureScript extension: `.cljs`

I suppose this implies that Calva does not need to distinguish between Clojure and ClojureScript?

**Comment by PEZ** [comment]
> is "Run Custom REPL Command" supposed to work for ClojureScript?

Yes. You can configure custom commands to use the Clojure or ClojureScript REPL, or leave it at ”whatever is the current REPL”.  Do you have a REPL connected when you test that?

> I suppose this implies that Calva does not need to distinguish between Clojure and ClojureScript?

Calva actually distinguishes between Clojure and ClojureScript, even if VS Code only cares about ”clojure”.

**Comment by bpringe** [comment]
Seems this should have been closed after the merge. Please continue the conversation here if necessary, though.
