### ISSUE TITLE
Emacs keybindings extensio is ignored in the repl window

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva#121]
As far as I could notice all the keybindings from the extension are being ignored on the repl window.
I'm using this extension https://github.com/SebastianZaha/vscode-emacs-friendly

**Comment by melito00** [comment]
I tried new repl window does not released. it works fine for me.

**Comment by claynon** [comment]
I just tested it and all keybindings tried worked!
thanks!
