### ISSUE TITLE
The debugger never lets me step

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1210]
Issue Type: <b>Bug</b>

When I instrument a function for debugging and then eveluate a call to that function, the debugger starts. But it doesn't break into the code as it used to. There is nothing displayed in *Variables* and the debug control strip doesn't activate the step buttons.

<img width="399" alt="image" src="https://user-images.githubusercontent.com/30010/123173591-20228380-d47f-11eb-8201-f3dc68dbca96.png">

Extension version: 2.0.200
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id 2ae7a090-f6a7-4ed2-9d2d-8d3fb632392c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30319632
vscorehov:30309549
vscod805cf:30301675
vscextlang:30322306

```

</details>

**Comment by bpringe** [comment]
Can you provide a code example for reproducing? It may be something related to the code you were trying to debug. Stepping has worked as recently as 2.0.199 I believe, and 2.0.200 only includes a clojure-lsp update. :thinking:

**Comment by PEZ** [comment]
I noticed it because a friend was trying out the Getting Started REPL and got confused. Then I tried it myself and noticed this.  So, any code, really. Though I notice slightly different behaviour with different pieces of code. In the Getting Started REPL example it is as though the function is never entered. While with this code, I get `tail` decorated with its value, but still no stepper and no value in the side view:

```clojure
(ns pez.lab.reverse
  (:refer-clojure :exclude [reverse]))

;; We are Only allowed to use the
;; * first
;; * cons
;; * rest
;; * concat
;; * count

(defn reverse' [head tail]
  (if (empty? tail)
    head
    (reverse' (cons (first tail) head) (rest tail))))

(defn reverse [lst]
  (reverse' '() lst))

(comment
  (reverse (str 512345)))
```

I suspect a change in VS Code.

**Comment by mchughs** [comment]
+1
I've been working through the `hello_repl.clj` example and I wasn't sure if I was doing something wrong. To reproduce I would say use a clean installation of VScode and Calva on OSX and follow the instructions on line 154 as written.

**Comment by bpringe** [comment]
Thanks for the info and instructions to reproduce. I'll look into this soon.

**Comment by cgrabenstein** [comment]
I experienced the same behaviour, although it's just happening for a couple of days now. I am pretty sure that it was working before.

It appears that the current frame is not being selected in the callstack. After I select the topmost frame, the controls re-enable for me, the variables show up and I can get one step further. But after each step the frames are de-selected again. For the next step I'll have to re-select the current frame.

VSCode version 1.57.1
Calva version 2.0.201

**Comment by djaquay** [comment]
I'm seeing a similar issue, except I don't see anything in the callstack to select, so it kinda just hangs.  Callstack window says "paused on breakpoint" but nothing in either callstack window or breakpoint window to interact with.

VSCode 1.57.1
Calva 2.0.202

(And let me say thanks for the PLEASE NOTE in hello_repl.clj; I'm new to both Clojure and Calva, and this would have been more frustrating without that note :).

**Comment by bpringe** [comment]
I just reproduced this and then updated Calva to 2.0.203 and I cannot reproduce it again. Can someone else report if the debugger works fine for them in 2.0.203?

I'm using VSCode Insiders 1.58.0. To clarify, I reproduced the issue with this VSCode Insiders version, then updated Calva to 2.0.203 and could not reproduce it.

**Comment by bpringe** [comment]
Nevermind, again I can reproduce it... :disappointed:

**Comment by bpringe** [comment]
Could someone here also try debugging with version 2.0.198 and tell me if it always works correctly for you? It does for me in my testing just now, which tells the issue lies in code changes since then (probably related to the call stack change in .199).

FYI, to install an older version you can click the cog on the Calva extension in the extensions side pane and click to install another version.

**Comment by bpringe** [comment]
Ok, I've got a consistent way to reproduce the issue with the latest Calva version, and I cannot reproduce it with 2.0.198, so I think there's just a regression in the code, which is better than an issue with VSCode, I suppose.

Steps to reproduce:
1. Reload the VSCode window
2. Start a _new repl_
3. Connect to the repl
4. Load the file used for testing
5. Instrument a function, then call it or call a function that calls it

The above steps cause the issue for me, but then if I hit disconnect on the debugger, and call the same function again, the debugger starts fine and I can step as expected. After this I cannot reproduce the issue again unless I reload the VSCode window and start a new repl again.

Edit: I can reproduce just by jacking-in, then the first time I try to run the instrumented function the issue occurs. If I hit disconnect on the debugger and try again, it works fine, as mentioned above. Then, without reloading the window, I can jack-in again and repeat the steps mentioned to reproduce the issue again.

**Comment by bpringe** [comment]
To be more sure the problem is the result of a change in Calva, I checked out commit 34ff4c37 (from before the call stack change) and ran that version of the code and I cannot reproduce the issue.

When I tried to change code in debugger/calva-debug.ts from the current dev branch back to how it was (or close to it) in a version that doesn't have the issue, I still experienced the issue. So, this might take some time to figure out what changed that's causing this.

**Comment by bpringe** [comment]
I've narrowed the problem down a bit further. If I use the same version of the calva-debug.ts file from commit 34ff4c3 in the dev branch, I cannot reproduce the issue, and if I reset the file back to its current state in the dev branch, I can reproduce the issue again.

So, the problem must lie in what's changed in that file.

**Comment by PEZ** [comment]
Great finds! And good news the bug is created by us! 😄

**Comment by bpringe** [comment]
Calva version 2.0.205 contains a rollback of code that seemed to cause the issue. The good news is I've isolated it to the `stackTraceRequest` function in calva-debug.ts. I tried changing just that function back to an earlier version, before the call stack improvement, and I couldn't reproduce the issue.
