### ISSUE TITLE
Use new custom LSP method for server info command and print info in "Calva says" output channel

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1211]
The clojure-lsp command used currently by Calva is being deprecated in favor of a new custom command that will return the server info and include additional information.

We should make the implementation for Calva's clojure-lsp server info command use the new custom command instead of the now deprecated one.

Reference: https://github.com/clojure-lsp/clojure-lsp/issues/450#issuecomment-867150118

**Comment by bpringe** [comment]
I noticed the server info is now too large to fit in a VSCode information message, so we should use the `clojure/serverInfo/raw` command and print it where it can be fully read.

![image](https://user-images.githubusercontent.com/12722744/125208295-65e49780-e246-11eb-9ad9-ab220e2e5632.png)

**Comment by bpringe** [comment]
@PEZ, regarding the above, where should we show this information to the user now? Some ideas:

1. Just copy it to their clipboard and display a message like "Clojure-lsp server info copied to clipboard"
2. Print it to the output window, even though the REPL may not be connected and the window may not be open (we would open it in this case, of course)
3. Print it to the Calva says output channel and show the channel

**Comment by ericdallo** [comment]
I like the third option :)
