### ISSUE TITLE
Jump between source/test does not work properly with multiple workspace folders

### ISSUE THREAD

**Issue by seancorfield** [BetterThanTomorrow/calva#1219]
Monorepo structure:
```
<root>
  clojure
    bases
      src
        ws
          preview-web
            main.clj
      test
        ws
          preview-web
            main_test.clj
```
Open `main.clj` and toggle to test: it wants to create `main_test.clj` but the path is actually correct and if you select Create, it opens `main_test.clj` correctly.

Once in `main_test.clj`, try to toggle: again, it wants to create `main.clj` but the path is correct and selecting Create causes it to open the existing source file.

**Comment by PEZ** [comment]
Thanks!

**Comment by bpringe** [comment]
CC @pratik97

**Comment by pratik97** [comment]
Seems to be working fine for me @seancorfield, is it on Windows OS? does it happen with all the projects or only this one?

https://user-images.githubusercontent.com/15200937/123907101-00192580-d993-11eb-949c-5ee0029bcf97.mov

**Comment by seancorfield** [comment]
macOS. And this is the only project I work with day-in, day-out because it's the monorepo at work. Your project is not set up the same way at all!

**Comment by pratik97** [comment]
ah, I haven't worked with monorepos... I thought it's just multiple projects under one directory, is there any open source monorepo project that I can pick for reproducing this?

**Comment by bpringe** [comment]
Not sure if @seancorfield can provide a better project for reproducing, but you could see if it happens with the polylith tool project, as it's built using the polylith (monorepo) architecture: https://github.com/polyfy/polylith

**Comment by seancorfield** [comment]
I tried to repro in a smaller project but haven't been able to nail it down yet. Will post more here as and when I figure it out.

**Comment by pratik97** [comment]
I tried creating a minimal polylith project as documented in https://github.com/polyfy/polylith project but couldn't repro it

**Comment by seancorfield** [comment]
FWIW, with the latest Calva, I'm still seeing the warning that it wants to create the file (in both directions) but it *does* switch to the correct (existing) file. And the path in the popup that it says it wants to create **exists** and is the correct path -- so I've no idea why the popup appears because the path is correct and the file exists...

**Comment by pratik97** [comment]
Can't reproduce it in my non-polylith project, but the current logic is, to create a path for the src or test file and then search it in all the workspace folders(by regex/glob pattern), if found just switch to it, else ask to create it. For example, a if we run command on a src file named, `<project root>/src/domain/foo.clj` it will try to find `<project root>/test/domain/foo_test.clj` in all the folders in the workspace. Does your project fits in with that?

**Comment by seancorfield** [comment]
As noted early in the thread, the pattern for us is something like `<root>/clojure/components/<name>/src/ws/<name>/impl.clj` and the corresponding test file is `<root>/clojure/components/<name>/test/ws/<name>/impl_test.clj`

But my point is that the confirmation popup *has the correct filesystem path in it* to an *existing* file -- so whatever test it is doing on the file's existence is "off" somehow.

Here are some screenshots showing the sequence of events:

[Three screenshots](https://www.dropbox.com/s/n049v4x1oe9cd0v/Screen%20Shot%202021-08-19%20at%2010.13.36%20AM.png?dl=0)

**Comment by pratik97** [comment]
hmm, this is tricky, if we are finding the correct path, and the correct file name, all we are doing is to call VSCode API's `findFiles` function with the file to open as an inclusion regex,  and if one or more file matches that pattern it will return those files. In our case, only one file should match, and if that matches it shouldn't ask to create a new one. Relevant code snippet,

```
  const fileToOpen = vscode.workspace.asRelativePath(filePath); // <root>/clojure/components/<name>/test/ws/<name>/impl_test.clj

  vscode.workspace.findFiles(fileToOpen, '**/.calva/**').then((files) => {
     // files is an array of all the files that matches regex given as a first argument to findFiles 
      if (!files.length) {
          askToCreateANewFile(path.join(projectRootPath, sourcePath), newFilename);
      } else {
          const file = files[0].fsPath;
          openFile(file);
      }
  });
```
@PEZ do you know if there are any gotchas around these VSCode APIs? especially for windows(though I think it mostly have to do with polylith structure)?
@seancorfield would be great if you can repro this in a small project.

**Comment by seancorfield** [comment]
It feels a bit like the ship has sailed on this. It's not a feature I care about, to be honest, and no one seems to be able to repro the issues we had so I'm closing it.

**Comment by maxrothman** [comment]
This appears to be caused by multi-root workspaces. Repro steps:

- open a clojure project in vscode
- run “Workspaces: Add folder to project” with any folder outside the project that contains at least one file
- Open a clojure file that has a matching test file in the expected directory
- Run “Calva: toggle between implementation and test”

Expected behavior; the test file is opened

Actual behavior: Calva asks “Create <path to file>?” If you click “Create”, it switches to the existing file. If you click “Cancel”, nothing happens (as expected)

**Comment by PEZ** [comment]
Please give this VSIX a spin. Should fix the issue and hopefully not create new issus. :smile:

https://output.circle-artifacts.com/output/job/903bbf25-eef4-47e1-981d-810de7876133/artifacts/0/tmp/artifacts/calva-2.0.265-1219-file-switch-workspace-folders-7ea23173.vsix

**Comment by maxrothman** [comment]
It works!
