### ISSUE TITLE
Auto complete of private symbols

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva#122]
if I have a private fn called `foo` in a namespace called `bar`
auto complete of `#'foo/bar` does not work

If I write `#'foo/bar` once in a file and try to write it again in the same file it will try to autocomplete to  `'foo/bar` (without the `#`)

**Comment by PEZ** [comment]
Thanks. We will have to check what determines what vscode gives us to complete.

The second thing there... I see the behaviour too, but the end result is correct, right? (Even if it is a bit confusing what shows in the pop-up.)

**Comment by claynon** [comment]
I think it should autocomplete to `#'foo/bar`. Or am I missing something on the semantics of `#`?

**Comment by PEZ** [comment]
I don't think you are missing something. What I mean is that if I type `#'foo/bar`, then `#'fo`, I get a popup suggesting `'foo/bar`. If I accept that suggestion, I end up with having typed `#'foo/bar`. Is that not what happens for you?

**Comment by claynon** [comment]
Now I understood. Yes, it works in that way.
however it's not working in all cases. when I try to write `fo` or `'fo` this triggers the auto complete popup because of the fuzzy finder
If I hit enter in the popup I get `'foo`

**Comment by cfehse** [comment]
@claynon 

This should be fixed in version 2.0.57. I am closing the issue for now.
