### ISSUE TITLE
Evaluate and send (only) printed/returned results to a text buffer (feature request)

### ISSUE THREAD

**Issue by lspector** [BetterThanTomorrow/calva#123]
Desired functionality: Evaluate selected text and have all printed/returned results appear, without a copy of the selected text or anything else, in a plain text buffer in which results can be viewed (even if they're big), copied, etc. It would be nice if it could also be applied to the whole buffer, but if that requires a select-all first then that's not a big deal. Conceivably also apply to the "current expression," although most important to apply to selection and/or full buffer.

Many commands in Calva currently come close, but either put the results inline (not good for big values, and can't easily be copied, etc.) or includes the evaluated text and/or other additions.

The output could appear in a REPL, or some other Terminal, or somewhere else.

**Comment by PEZ** [comment]
Thanks for this request! We'll figure a bit on it and see in which way this need could be supported. It can easily get to be an explosion of commands.

> Conceivably also apply to the "current expression," although most important to apply to selection and/or full buffer.

Two thoughts on this:

1. Evaluating the selection and the ”current” expression is the same command today, so would work the same for this evaluate-to-somewhere thing.
1. Evaluating the full buffer would only visibly result in getting the evaluation of the last top level form, right?

**Comment by lspector** [comment]
Awesome!

On thought 2: Evaluating the full buffer should send any explicit print output (e.g. from `println`) to the output place, but as for return values, I think I've seen it done both ways, either printing all return values (which often means function symbols returned from `defn`) or just the value of the last expression. Either could be okay, but I guess (not super confident) just printing the last is better.

**Comment by orestis** [comment]
I'm missing this from emacs/CIDER: The ability to get the evaluated results to a new buffer that I can format, fold, copy, save etc. I think the *printed* stuff is craziness though :D -- there's `(with-out-str ...)` for that.

**Comment by PEZ** [comment]
Yes, it is due time for this to happen. I don't think it is very complicated even. Especially if we let people handle printed stuff themselves.

**Comment by bpringe** [comment]
I believe this has been accomplished with the new output/repl window :tada:. Please reopen if I'm wrong.
