### ISSUE TITLE
[LSP] Support semantic tokens feature 

### ISSUE THREAD

**Issue by ericdallo** [BetterThanTomorrow/calva#1231]
I'd like to suggest adding support for LSP semantic tokens :)

### What is it?
[LSP semantic tokens](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens) is a feature introduced on latest spec release 3.16 and clojure-lsp is one of the few servers that support it. It was called semantic highlighting in the past and basically needs the server to return tokens, saying which they are, like functions, enums, namespace, variable, keyword, etc and the client color it on the document following user theme, giving to the user a better and improved highlighting on their code :)

### Do I need it for Clojure?

[Here](https://emacs-lsp.github.io/lsp-mode/tutorials/clojure-guide/#semantic-tokens-experimental) is a comparation of it on emacs with cider(REPL) connected:
![image](https://user-images.githubusercontent.com/7820865/125142648-a0d3b780-e0ee-11eb-9355-54fcb869693c.png)
Remember that this would make highlight works without the need of a REPL ;)

This is a screenshot of Calva without semantic tokens as of now with default theme:
![image](https://user-images.githubusercontent.com/7820865/125143414-ff019a00-e0f0-11eb-87ac-0e09ed50c1c5.png)

This is a screenshot of Calva without semantic tokens as of now with monokai theme:
![image](https://user-images.githubusercontent.com/7820865/125142352-e5128800-e0ed-11eb-8c42-fc88906be44a.png)

Emacs(lsp-mode) with semantic tokens enabled:
![image](https://user-images.githubusercontent.com/7820865/125142406-07a4a100-e0ee-11eb-9e43-d5b38025f9c3.png)

You can see how tokens like `@db/db`, `string/upper-case`, and especially for Clojure, __macros__, are highlighted with a specific color, also some themes don't handle well clojure keywords and things like that, which with LSP probably would fix it 

### What Calva needs to do?

On server side, this feature is enabled by default already (`:semantic-tokens?`) as it exists for months already and it works great IMO. 
On client side, it needs to send during initialization that it supports the semantic tokens. The good news are, AFAICS there is no need for Calva to configure anything as the `vscode-languageclient` already handles that, but I could not make it work for calva for some reason and I suspect that is related to the version of that lib, maybe upgrading to `7.0.0` just like Dart-Code, which supports semantic-tokens as well, [did](https://github.com/Dart-Code/Dart-Code/commit/a11cba2dd6ca38d086a01619296f79f1fd1847b8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R2260)?

I think this would be a nice addition for Clojure users, LMK what you think :)
c/c @PEZ @bpringe

**Comment by bpringe** [comment]
Yeah, I think we would need to upgrade the language client library. The version we use now is using 3.15.3 of the protocol.

As far as using this feature, I'll defer to @PEZ to see what he thinks.

It's great that you added that feature to the server!

**Comment by PEZ** [comment]
I think it is great! We can let the users have a setting for it, with enabled as default, imo. Can it be toggled on/off while the server is running?

**Comment by ericdallo** [comment]
@PEZ, ATM no, but I think it could be done as LSP has a specific method for things like that, didConfiguratiinChanged I think

**Comment by ericdallo** [comment]
@PEZ It's possible via https://microsoft.github.io/language-server-protocol/specification#client_registerCapability.
This is not blocker for Calva though.
I'll try to implement on clojure-lsp soon
