### ISSUE TITLE
[REPL Window] Feature request: Alt+Enter executes

### ISSUE THREAD

**Issue by tomdl89** [BetterThanTomorrow/calva#124]
Currently, the only way to execute what's typed at the new REPL window is by pressing enter when at the end. I would like a way to execute wherever the cursor is. Alt+enter seems most consistent with the other Alt commands (like navigating history).

**Comment by mseddon** [comment]
Totally agree, that is a great suggestion. Consider it accepted 😀

**Comment by PEZ** [comment]
I think like this: If alt+up/down alters the up/down keys from moving within the current form to moving between forms, then it makes sense that alt+enter alters the behavior of enter from adding a new line to the current form to entering the form itself. It is then added to the history and reachable with alt+up/down. cmd+enter would make the same sense if cmd+up/down was the way to access the history stack.

**Comment by Gnurdle** [comment]
add to that the ability to kill the entire input line and start over easily.  if you ever get a single ')' on the input line, good luck getting rid of it.

**Comment by Gnurdle** [comment]
and another, either the proposed <alt+enter> or <end> should overrule any completions suggestions that are pending w/o having to hit <esc> first.

**Comment by bpringe** [comment]
I think this can be closed since the original issue is now implemented? alt+enter evaluates the form no matter where the cursor is. @PEZ

**Comment by Gnurdle** [comment]
@bpringe @pez I feel like most of this is in place, +1 to close it

**Comment by PEZ** [comment]
Thanks for helping me with tidying the issues list, friends!

To your ”single `)`” issue, @Gnurdle: there is `alt+backspace`, and `alt+delete`.
