### ISSUE TITLE
Starting nRepl + shadow cljs REPL session fails if shadow-cljs dep is under alias which user selected but not checked

### ISSUE THREAD

**Issue by MaximGB** [BetterThanTomorrow/calva#1240]
Hello, this is more a usability issue I guess. 

### Environment:
VSCode Version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:30:16.440Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 4.15.0-147-generic
Calva: 2.0.205

### Summary
It is not clear that you have to use checkboxes to select an alias instead of just clicking on the alias name in the menu ;) And it would be much more convenient if clicking on the alias name worked in case one needs to select just a single alias. 

### The issue description
I have following `deps.edn` file in a full stack project:

```
{:deps {org.clojure/clojure               {:mvn/version "1.10.3"   :scope "provided"}
        integrant/integrant               {:mvn/version "0.8.0"}
        ring/ring-core                    {:mvn/version "1.9.4"}
        ring/ring-devel                   {:mvn/version "1.9.4"}
        ring/ring-defaults                {:mvn/version "0.3.3"}
        ring/ring-anti-forgery            {:mvn/version "1.3.0"}
        compojure/compojure               {:mvn/version "1.6.2"}
        http-kit/http-kit                 {:mvn/version "2.5.3"}
        maximgb/maximgb.integrant.helpers {:git/url "https://github.com/MaximGB/maximgb.integrant.helpers"
                                           :sha "70fa988deb162be1a6123b6bb3bdbc2a35d5ab14"}}
 :paths ["src/clj"]

 :aliases
 {:shadow-cljs
  {:extra-paths ["src/cljs/main"
                 "src/cljs/dev"
                 "src/cljs/test"]
   :extra-deps {thheller/shadow-cljs {:mvn/version "2.15.2"}}
   :main-opts ["-m" "shadow.cljs.devtools.cli" "watch" :app]}}}

```
When I run **Start project REPl and Connect** Calva command it asks for project type where I select **nRepl + shadow.cljs** and an alias afterwards. But each time I clicked on the alias name the process failed with `ClassNotFoundException` failing to find `shadow.cljs.devtools.api` namespace. I'd spent couple of hours reading the docs and trying different approaches with no results until I realized that I can actually select several aliases in the alias selection dropdown, and I have to use checkboxes in front of alias names to do so. So after I set the checkmark against my only alias in the menu the Jack-In process succeeded.

**Comment by MaximGB** [comment]
I might raise a PR with the fix if this issue will be considered as worth fixing

**Comment by PEZ** [comment]
Hello. I'm not sure there is a fix for this issue. It's VS Code's Ux. Or am I missing something?

**Comment by MaximGB** [comment]
Hi, @PEZ frankly speaking I don't know, I've never written any VSCode extensions, but I might investigate if you consider it is needed to be fixed

**Comment by MaximGB** [comment]
@PEZ Please, mark the issue as invalid. You were right the dropdown menu behavior is controlled by VSCode. As well as after I'd started investigating for possibilities to fix the issue I've understood that I actually haven't used the mouse to select an alias. Have I used it I wouldn't be able to miss the checkbox. Every time the dropdown menu item is clicked on, the checkbox is toggled. So actually I've used keyboard (`down arrow`) to select the alias item and then hit `Enter`. Such sequence of actions doesn't check the alias checkbox and Jack-In sequence proceed without alias. One has to use `Space` to hit the alias checkbox after he has navigated to the item using `down arrow` and only then hit `Enter`
