### ISSUE TITLE
Word boundaries spanning `-` by default

### ISSUE THREAD

**Issue by otwieracz** [BetterThanTomorrow/calva#1246]
With `Calva` plugin enabled, word boundaries are not correctly respected with `Vim` plugin.
I.e. hitting `w` on `(|foo-bar car)` should move cursor before `-`, that is `(foo|-bar car)`.
With `Calva` enabled, it jumps to whitespace: `(foo-bar| car)`.

See attached video:
https://drive.google.com/file/d/1htBJ8tj2HMko2PDGZCsCs8X5FTrOMYeN/view?usp=sharing

**Comment by PEZ** [comment]
Calva defines Clojure word boundaries. There is probably nothing we can do about this. It's similar with how double-clicking `foo` in `(foo-bar car)` will select `foo-bar`.

**Comment by alpox** [comment]
This can for now be fixed by adding the `-` to the `editor.wordSeparators` setting. As calva defines the `editor.wordSeparators` for `clojure` specifically one has to override that setting for that language as following:

 ```
 "[clojure]": {
    "editor.wordSeparators": "\t ()\"':,;~@#$%^&{}[]`-",
  }
  ```

**Comment by PEZ** [comment]
I've tried this now. Indeed, adding `-` to word separators changes the behaviour of double-click as well. So this is rather a matter of taste than anything else. We should mention this here: https://calva.io/customizing/

**Comment by otwieracz** [comment]
Yes, it's unfortunate and I agree both solutions have their own disadvantages. Best thing that can be done here is to document it.

**Comment by PEZ** [comment]
Documentation updated. Thanks for highlighting the issue!
