### ISSUE TITLE
go to defintion and intellisense doesn't work with "special" characters

### ISSUE THREAD

**Issue by diacone** [BetterThanTomorrow/calva#125]
VS Code version:
```
Version: 1.31.0
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-06T08:51:24.856Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.20.6-200.fc29.x86_64
```

Calva Version: 1.3.0

Using ClojureScript, connected to cljs REPL 
* minus in Var name (-)
* slash (e.g. for calling from other namespaces) (/)
* dot (.)

![screenshot_20190212_121538](https://user-images.githubusercontent.com/6052247/52632448-e52ce000-2ec1-11e9-81a9-eaffd8f3f223.png)
![screenshot_20190212_122528](https://user-images.githubusercontent.com/6052247/52632456-ea8a2a80-2ec1-11e9-9bea-644abb1b4ccf.png)
![screenshot_20190212_122852](https://user-images.githubusercontent.com/6052247/52632460-ed851b00-2ec1-11e9-8e7a-917e1bb70657.png)

**Comment by PEZ** [comment]
Hmmm, are you sure about the Calva version? It seems very old.

**Comment by diacone** [comment]
You're right. I took it from changelog :)
```
Name: Calva: Clojure & Clojurescript Interactive Programming
Id: cospaia.clojure4vscode
Description: Integrated REPL, linting, inline eval and more for VSCode. Powered by Cider & nRepl.
Version: 1.3.63
Publisher: Better Than Tomorrow
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=cospaia.clojure4vscode
```

**Comment by PEZ** [comment]
OMG. I should remove that changelog until I have a way to keep it updated...

I can't reproduce this error. Does goto definition fork for `f1`, but not for `f-1`, you mean?

**Comment by diacone** [comment]
Yes @PEZ, that's right. If you look at the screenshot, you can see that actually only part of the name is "hovered" and it's looking for wrong symbol.

**Comment by PEZ** [comment]
It is very strange. Have you evaluated the `f-1` form when that happens? (That wouldn't explain why only `1` is highlighted in, but anyway.)

What other extensions do you have active?

**Comment by diacone** [comment]
Ok, mystery solved. I've disabled Calva Clojure Formatter because it interfered with Parinfer. When I enable it seems to be working.

Thanks for pointing me the right direction.

**Comment by PEZ** [comment]
Ah, but you can instead disable ”Format as you type”. (Even though I rather recommend you keep it on and try to be content with Calva Format's ”Infer parens” command.
