### ISSUE TITLE
Suspicion: when Calva's REPL window has a lot of text, it is slowing down clojure-lsp

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1250]
As VS Code is sending all Clojure files to clojure-lsp, and the REPL/output window is a Clojure file, it is analysed and could potentially be causing performance problems affecting the whole project.

**Comment by PEZ** [comment]
Speaking with @ericdallo about this it seems we can't cut off clojure-lsp analysis of this file without also loosing the clojure-lsp services in the file. So a worst case solution (given that this really is a problem) is to make clojure-lsp ignore the file and drop the clojure-lsp support there.

**Comment by bpringe** [comment]
To stop clojure-lsp from analyzing the repl file, these are some possible options off the top of my head, without looking further into it right now:

0. We may be able to modify the initialize request
0. We probably can use middleware to not send the file in certain individual protocol requests

**Comment by ericdallo** [comment]
One thing I can think to fix the issue is that for the REPL buffer, we just care about the code that was not sent to repl yet, right? the code user is writing right now, not the one that was already evaluated, if we could make calva send only that code, it'd certainly fix the issue.

![image](https://user-images.githubusercontent.com/7820865/128379070-5d6404c6-d9b7-41ff-a230-afb172099b46.png)

**Comment by ericdallo** [comment]
I temporary fix for users right now is cleaning the repl as well...

**Comment by brdloush** [comment]
a simple way to reproduce:

1. open a `lein new whatever` project in calva
2. cider jack in
3. evaluate and wait until this finishes
```clj
(->> (range 100000)
     (run! #(println "line " %)))
```
4. watch clojure-lsp eat 100-300 %CPU for many minutes

EDIT: adding step 5

5. evaluate any expression in REPL window. `(+ 1 1)` should be enough. You may also want to make sure that code completion got triggered.

**Comment by ericdallo** [comment]
> watch clojure-lsp eat 100-300 %CPU for many minutes

Odd, I could not repro that slowness or high CPU 🤔 

Even so, a huge clojure buffer will certainly affect the performance (only for that buffer, other buffers should work normally as expected).

[My suggestion](https://github.com/BetterThanTomorrow/calva/issues/1250#issuecomment-893559746) would still work for this case

**Comment by ericdallo** [comment]
> Odd, I could not repro that slowness or high CPU 🤔 

I can repro the issue if I try to edit the repl and complete something

I even got a OOM exception, and we can see rewrite-clj is having issues as it needs to parse a huge text:
```
2021-08-05T15:47:30.033Z gregnix-nubank ERROR [clojure-lsp.server:?] - 
                              clojure.core/seq     core.clj:  139
                                           ...                   
                    clojure.core/repeatedly/fn     core.clj: 5138
               rewrite-clj.parser/parse-all/fn  parser.cljc:   25
                      rewrite-clj.parser/parse  parser.cljc:   20
            rewrite-clj.parser.core/parse-next    core.cljc:   46
             rewrite-clj.reader/read-with-meta  reader.cljc:  147
                                           ...                   
                    rewrite-clj.parser.core/fn    core.cljc:   74
          rewrite-clj.parser.token/parse-token   token.cljc:   45
                rewrite-clj.reader/string->edn  reader.cljc:  109
          clojure.tools.reader.edn/read-string      edn.clj:  437
          clojure.tools.reader.edn/read-string      edn.clj:  440
                 clojure.tools.reader.edn/read      edn.clj:  392
                 clojure.tools.reader.edn/read      edn.clj:  407
          clojure.tools.reader.edn/read-symbol      edn.clj:  260
clojure.tools.reader.impl.commons/parse-symbol  commons.clj:  117
                                           ...                   
java.lang.OutOfMemoryError: Java heap space

```

**Comment by brdloush** [comment]
Oh, you're correct, I also evaluated some expression in the REPL window, just after all that output got appended to the REPL window.

So I'm adding step 5:

```
5. evaluate any expression in REPL window. `(+ 1 1)` should be enough. You may also want to make sure that code completion got triggered.
```

**Comment by ericdallo** [comment]
This should fix the issue: https://github.com/BetterThanTomorrow/calva/pull/1479
