### ISSUE TITLE
Setting for disabling clojure-lsp to reduce RAM consumption.

### ISSUE THREAD

**Issue by lkyhfx** [BetterThanTomorrow/calva#1262]
I have noticed that when setting up a Clojure project then jacking in the REPL it will consume a lot of RAM (2 processes of java, 1 process of `clojure-lsp`). The total of RAM consumed by vscode + Calva even exceed IntelliJ + cursive sometime. Sometimes we just need a lightweight editor that connect to the REPL. So it will be helpful that we can disable the `clojure-lsp` to save some RAM.

**Comment by bpringe** [comment]
In https://github.com/BetterThanTomorrow/calva/issues/917 we discussed this and opted to not allow disabling clojure-lsp. However, some time has passed, and I wonder what @PEZ thinks about this with the current state of Calva and how we use clojure-lsp and plan to use it going forward.

**Comment by PEZ** [comment]
I'm starting to lean towards that we should add this option.

Maybe something like a setting named `autoStartClojureLsp`, defaulting to `true`. In combination with commands for starting and stopping the server at will.
