### ISSUE TITLE
Formatter gets tripped by :/

### ISSUE THREAD

**Issue by kstehn** [BetterThanTomorrow/calva#1267]
When using a the keyword `:/`

The formatter doesn't work anymore more to format the current form.
Example:
```clojure
[:/
 [:a "iuna"]
 [:b "urina"]]
```
When i create a new line it gets correctly formatted.
The formatting in the other vectors also work.

**Comment by PEZ** [comment]
Thanks! Do you get any error messages? Also would be good if we tried this using cljfmt directly. (The indent when you hit return is done by Calva w/o cljfmt so that is why they might have different bugs.)

**Comment by kstehn** [comment]
No only that it didn't work.
When i use `lein cljfmt fix ...` it works correctly and fixes the formatting.

**Comment by PEZ** [comment]
It might be due to that we are using an ancient fork of cljfmt...

**Comment by bpringe** [comment]
This is related to #1179. What I mean is, I think we've decided it's a good idea to switch to using upstream cljfmt for formatting, rather than our fork. We probably should provide some other solution to to the alignment feature, though, as mentioned in that issue.
