### ISSUE TITLE
Calva not detecting tests when trying to run a single tests.

### ISSUE THREAD

**Issue by jmayaalv** [BetterThanTomorrow/calva#1269]
Calva is unable to detect test when trying to run a single tests. Test is found if all the tests in the namespace are executed.   

I could reproduce it on windows and can say that works on cider, so probably not something related to `cider-nrepl` the output when running a single tests is always:

``` clojure
; Evaluating file: reports_test.clj
#'edge.test.reports-test/sb-switches-report-test
; Running test: _…
; No tests found. :scream:, ns: 0, vars: 0
``` 

The same behavior can be seen if `deftest` is aliased or refered, so doesn't seem to be related to https://github.com/BetterThanTomorrow/calva/issues/1086

**Comment by bpringe** [comment]
Thanks for the report!

**Comment by bpringe** [comment]
I cannot reproduce this on MacOS. I suspect it may be an issue only on Windows. Do you see any errors in the developer console after reproducing the issue? `Help -> Toggle Developer Tools -> Console tab`

@PEZ Maybe you could try this on your Windows machine?

@jmayaalv If you'd like to debug and fix this, Calva has a [pretty easy contribution process](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva).

**Comment by jmayaalv** [comment]
Thank you for looking at this @bpringe. I am not really a VS code user myself and the ecosystem is very foreign for me, i use Cider and on macOS as well. I reported this on behalf of a new team mate totally new to the Clojure ecosystem.

We check the  the console but there doesn't seem to be anything relevant there, screenshot below:

![image (21)](https://user-images.githubusercontent.com/758737/132198740-105e6bd0-dd56-4f08-89b9-1dd141864410.png)

**Comment by bpringe** [comment]
Thanks, it seems a good next step would be for someone to run Calva in the extension development host on Windows and set breakpoints to see where things are going wrong. CC @PEZ

**Comment by marcomorain** [comment]
Can you try to reproduce this again with the latest Calva please? We added better error reporting, and I would expect to see a better error message in the REPL window now.

**Comment by jmayaalv** [comment]
Hello @marcomorain, 
indeed, now with the latest version we still get "no test found" and an error in a test fixture. But at at least now the error is visible. Once we removed the fixture the tests can be executed without problem. 

Thanks a lot for the help !

**Comment by marcomorain** [comment]
Awesome!
