### ISSUE TITLE
Clojure Spec's `fdef` macro not given special formatting like `defn`

### ISSUE THREAD

**Issue by kyleerhabor** [BetterThanTomorrow/calva#1271]
Hi! I'm using Clojure's `clojure.spec.alpha/fdef` macro to define the specs on a function. It works, but the editor positions the arguments like a regular function call as opposed to the special formatting that comes with `defn`. While I can reformat it myself, this makes me wonder if `defn` just gets special treatment built-in and if I can mimic the formatting. Thanks.

**Comment by bpringe** [comment]
Pinging @PEZ since he's more familiar with Calva's formatting.

**Comment by PEZ** [comment]
@KyleErhabor Hello! I think the solution is to use a config file for the formatter, see https://calva.io/formatting/#configuration
And add an indent spec to it where you give `fdef` the same spec as `defn` has.

You can find cljfmt's default indents in `clojure.clj` here:
https://github.com/weavejester/cljfmt/tree/master/cljfmt/resources/cljfmt/indents

Please let us know if this works or not.

**Comment by kyleerhabor** [comment]
Thanks Pez, I was able to get it working.
