### ISSUE TITLE
[New REPL Window] REPL window freezes when the evaluation takes a long time

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#128]
When evaluating something that takes ”a sufficiently long time” to evaluate, the REPL window freezes. Evaluating the same thing inline works. 

** REPRO **

Below is a naïve implementation of [Eratosthenes Sieve](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes). When evaluating the top-level form in that `comment` form in the REPL window (`ctrl+alt+v alt+space`) for `n = 1000000` on my machine the REPL window never returns with the answer and becomes totally unresponsive.

```clojure
(defn not-divisible-by [n d]
  (when-not (integer? (/ n d))
    n))

(defn sieve [n]
  (loop [found-primes [2]
         candidates (range 3 (inc n))]
    (let [highest-found-prime (last found-primes)
          remaining (->> candidates
                         (map #(not-divisible-by % highest-found-prime))
                         (remove nil?))]
      (if (= remaining candidates)
        (concat found-primes candidates)
        (recur (conj found-primes (first remaining)) (rest remaining))))))

(comment
  (sieve 1000000))
```

Again, evaluating the same form inline (`ctrl+alt+v space`), eventually, the results will be delivered.

Also, closing the REPL window and reopening it again works as a fix for getting the window back in operation.

**Comment by PEZ** [comment]
Update: It doesn't seem to be about how long time the evaluation takes. If I wrap my run of this test in `(time)`, like so:

```clojure
eratosthenes=> (time (str "mine: " (count (sieve-refined 1000000)) " primes"))
"Elapsed time: 7845.699169 msecs"
"mine: 78498 primes"
```

I do get the prompt back (even running  this for primes up to 1,000,000).

So now I am guessing it is that the REPL Window chokes on the size of the results.

**Comment by cfehse** [comment]
> So now I am guessing it is that the REPL Window chokes on the size of the results.

This is exactly what happens. The whole output is processed through the `Scanner.processLine()` method which takes a awful long time.
