### ISSUE TITLE
Document clj-kondo config

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1282]
As I just uttered ”we should document this” in the `#calva` channel on Clojurians slack, @bpringe will immediately create an issue for it. This time maybe I beat him to it! 😄 

Anyway, calva.io should probably make it easier to figure out that clj-kondo configs goes in `.clj-kondo/config.edn` and maybe even give a few reasonably common examples.

**Comment by mathieuroblin** [comment]
Hi @PEZ, I came across this issue when I was looking into how to ignore some repositories that are on the classpath (ie. `target/`) and it took me more time that I care to admit between the kondo configuration itself and the fact that ignoring files is actually at the lsp level.

I'd like to try to make this part of the documentation better, I glanced at https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva#editing-documentation for how to do so. besides your comment and mine, do you think of anything else, especially on the examples, that I could look into?

**Comment by PEZ** [comment]
Awesome, @mathieuroblin! Have you found the slack conversation that I am referring to? Thinking you might find some material there. In any case, I can't think of anything in particular right now.

**Comment by mathieuroblin** [comment]
No I have not, any tips on how I can find it back?

**Comment by PEZ** [comment]
I don't know if these links work.

Here's the one i was referring to in the issue start: https://clojurians.slack.com/archives/CBE668G4R/p1630166986030200

And here's one a bit more recent: https://clojurians.slack.com/archives/CBE668G4R/p1645345689650639?thread_ts=1642676377.084000&cid=CBE668G4R

They don't contain a lot of detail, though. But maybe some context around what kind of questions users have.

**Comment by mathieuroblin** [comment]
@PEZ Thanks, I will have a look.

Something to note, (I won't be touching any of it because I don't work with python so I don't feel confident taking this up). Following the README to start mkdocs locally doesn't work.

> AttributeError: module 'jinja2' has no attribute 'contextfilter'

The root cause of the issue is this: https://github.com/mkdocs/mkdocs/issues/2799, to unstuck myself locally I just bumped mkdocs from `1.2.3` to the latest version: `1.3.0`. It seems to do the trick so far.

**Comment by PEZ** [comment]
Thanks for the headsup! I've now bumped the versions of both mkdocs and mkdocs materials. + removed the requirement to edit mkdocs.yml plugins settings.

**Comment by PEZ** [comment]
I guess we forgot to submit a closing commit in #1636 😄

**Comment by mathieuroblin** [comment]
Oops😬
