### ISSUE TITLE
paredit.killSexpForward should copy deleted code to clipboard

### ISSUE THREAD

**Issue by xfthhxk** [BetterThanTomorrow/calva#1283]
Firstly, thanks so much for Calva!  I'm coming from a Spacemacs/emacs background where killing an s-expression copies the s-expression to the clipboard which makes moving code around much easier.  I'd like to see `paredit.killSexpForward` and `paredit.killSexpBackward` copy the deleted text to the clipboard.

**Comment by PEZ** [comment]
Hello, thanks for the feature request! It has been discussed before in #559, and then concluded that there is another extension that lets you chain the `paredit.Select*` commands and **Cut to Clipboard**, which achieves this effect.

As is also discussed there is that this is pretty uncommon behaviour for VS Code. It would come as a surprise that deleting something also overwrites what was previously on your clipboard.

Using that other extension is a bit unconvenient and adds setup, granted, and also a bit hard to discover. So I'm leaning towards that we should build it in to Calva Paredit, as [your PR](https://github.com/BetterThanTomorrow/calva/pull/1284) has started to do. If so we should:

1. Place it behind a setting (maybe `calva.paredit.killAlsoCutsToClipboard` that is default off.
2. Make it consistent over all *Kill* commands.
3. Document it. Probaby here: https://calva.io/paredit/#editing

**Comment by xfthhxk** [comment]
Thanks for the input @PEZ . Will incorporate your feedback and update the PR.

**Comment by xfthhxk** [comment]
@PEZ PR #1284 has been updated per your suggestions. Please have a look. Thanks!
