### ISSUE TITLE
There should be an opposite to "Start project"

### ISSUE THREAD

**Issue by pekeler** [BetterThanTomorrow/calva#1286]
Would be nice if "Start your project with a REPL and connect" had a mirror-command to stop the project again.

**Comment by PEZ** [comment]
Thanks!

For everyones info: This would be a pretty big win for Calva, and should be pretty easy to implement, while still making it necessary to visit quite a few places in the codebase. So if you have had plans to try contributing to Calva, this is a very good issue to tackle.
