### ISSUE TITLE
Document how to use clojure-lsp via Calva with an M1 Mac

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1289]
This is a note to myself for later, if it's still even necessary. @EricDallo is working on a fix, but currently the clojure-lsp binary for MacOS doesn't work with the M1 chip.

The workaround is to use the `clojure-lsp` binary from the releases, which uses a jar.

**Comment by ericdallo** [comment]
While trying to reproduce/making aarch64 CI work, I got the same issue on GithubActions and opened a issue here: https://github.com/DeLaGuardo/setup-graalvm/issues/19

**Comment by bpringe** [comment]
After updating my OS (it was a new machine), the clojure-lsp binary for MacOS now works. :tada:
