### ISSUE TITLE
Running the contributed command:'calva.lintFile' failed.

### ISSUE THREAD

**Issue by feelextra** [BetterThanTomorrow/calva#129]
I have `joker` installed:

```sh
$ joker -v 
v0.10.1
$ which joker
/home/felix/bin/joker
```
in the JSON settings:
```
"calva.jokerPath": "joker"
```

When I try command `Calva: Lint current file` with this config nothing happens and no error messages unlike expected behavior of linting (e.g. `(printBADln "Hello world")` isn't highlighted).

Tried configuring:
```
"calva.jokerPath": "/home/felix/bin/joker"
```
When I try command `Calva: Lint current file` with this config I get error:
```
Running the contributed command:'calva.lintFile' failed.
```

Currently I am able to get linting working instead using another extension [Clojure Linter (Joker) by Martin Klepsch](https://github.com/martinklepsch/vscode-joker-clojure-linter) for anyone wondering for working alternative.

**Comment by PEZ** [comment]
Thanks! I can reproduce this. Seems the `calva.jokerPath` setting fails when specifying a full path.

Also, maybe the default Joker settings that Calva uses are not the best, because the linting does not complain for the example you give. I'll take a look at that.

Meanwhile, to confirm that joker is indeed invoked at all when linting through Calva you can try using the default setting, just `joker`, and create a `let` binding that you do not use, or `require` something that you do not use.

**Comment by feelextra** [comment]
Thanks for the reply!
> Thanks! I can reproduce this. Seems the `calva.jokerPath` setting fails when specifying a full path.
At least now I know I'm not alone with this misbehavior, thanks for reproducing.
> Also, maybe the default Joker settings that Calva uses are not the best, because the linting does not complain for the example you give. I'll take a look at that.
> Meanwhile, to confirm that joker is indeed invoked at all when linting through Calva you can try using the default setting, just `joker`, and create a `let` binding that you do not use, or `require` something that you do not use.
So I tried the suggestion, added a `require` to my `ns` like this:
```clj
(ns myapp.core
  (:require (clojure.contrib math seq-utils)))
```
But didn't get any linting on the names `math`, `seq-utils` nor any error.

**Comment by andresrgz** [comment]
Currently, `calva.jokerPath` must contain a path to a _directory_ where it's assumed a `joker` binary can be found in there.

Try using the following config:
```
"calva.jokerPath": "/home/felix/bin"
```

I added this configuration parameter and now realize this may be counter-intuitive. 😅  @PEZ perhaps you would like this configuration to be used for specifying a full path to the binary instead?

**Comment by feelextra** [comment]
> Currently, `calva.jokerPath` must contain a path to a _directory_ where it's assumed a `joker` binary can be found in there.
> 
> Try using the following config:
> 
> ```
> "calva.jokerPath": "/home/felix/bin"
> ```

This works! :tada: 

> I added this configuration parameter and now realize this may be counter-intuitive. sweat_smile @PEZ perhaps you would like this configuration to be used for specifying a full path to the binary instead?

**I think this boils down to two issues basically**:
1. Apparently it won't use the binary on the `joker` path as returned by `which joker`
2. The naming of the config option for specifying our own custom joker binary path is ambiguous

The first is obviously the most important as users want it to "just work" whereas power users might have custom setups which they'd like to integrate with their own custom path.

The second I think the reason is that I was having this issue could be attributed to ambiguity of the `jokerPath` option name, perhaps these options are more intuitive:
-  `calva.jokerBinaryPath` / `calva.jokerDirectoryPath`
- `calva.joker.binaryPath` / `calva.joker.directoryPath`

**Comment by feelextra** [comment]
I'm not sure if something changed in my setup that now solves this (I don't think I'm using a different version of the extension than the one I had before).

Basically I no longer have to provide the `calva.jokerPath` config anymore, since the global `joker` (with `which joker`) is just being used directly.

I no longer have to use the separate linter extension, at least for now, so this could be closed.

If this issue resurfaces, open up this issue again.
