### ISSUE TITLE
[New feature SUGGESTION]t: Highlight symbol occurences in Editor

### ISSUE THREAD

**Issue by feelextra** [BetterThanTomorrow/calva#130]
Calva when connected to nREPL:
![workspace 4_045](https://user-images.githubusercontent.com/43674238/53110074-e786de00-3542-11e9-9264-9a67a949389b.png)
Cursive:
![workspace 4_047](https://user-images.githubusercontent.com/43674238/53110095-ec4b9200-3542-11e9-8566-199dc142bb44.png)

**Comment by feelextra** [comment]
Actually on closer inspection, it seems to be working!

However with my chosen theme it is very hard to see, so I had to switch theme:
![workspace 4_049](https://user-images.githubusercontent.com/43674238/53110924-c0311080-3544-11e9-804c-f75861345420.png)

I think this feature should be documented as I couldn't find it in the README
Also the Right-hand vertical bar has the occurrences highlighted as well which is just perfect.

**Comment by PEZ** [comment]
It is really hard to see with that theme, but now I see it. 😄 

(It is a built-in vscode feature. That is why it is not mentioned in the Calva README.)
