### ISSUE TITLE
Can't use $current-form more than once in a custom repl command snippet

### ISSUE THREAD

**Issue by colinkahn** [BetterThanTomorrow/calva#1301]
There is an issue if you use `$current-form` twice in a snippet, like so:

```
   "calva.customREPLCommandSnippets": [
     {
         "name": "foo",
         "snippet": "(vector $current-form (quote $current-form))"
     }
     ]
```

This will output for the expression `(do {:foo :bar})`:

```
 (vector (do {:foo :bar}) (quote $current-form))
 [{:foo :bar} $current-form]
```

**Comment by PEZ** [comment]
Thanks for reporting!

**Comment by PEZ** [comment]
Not sure why this isn't auto-closed, but anyway, @colinkahn, this should be fixed in latest release, 2.0.212.

**Comment by colinkahn** [comment]
Thanks!

**Comment by bpringe** [comment]
> Not sure why this isn't auto-closed

Just FYI, it may be because your commit used "fixing" instead of something like "fixes." I'm not sure if "fixing" is one of the words that triggers the closing.
