### ISSUE TITLE
Javadocs are not opening with Calva

### ISSUE THREAD

**Issue by pratik97** [BetterThanTomorrow/calva#1304]
I have JDK11 installed and `JAVA_HOME` path is also set in my system. I have the following import in one of my namespaces.

```
(:import [java.time Instant LocalDate LocalDateTime LocalTime ZonedDateTime ZoneId]
          [java.time.format DateTimeFormatter DateTimeParseException]
           java.time.temporal.ChronoUnit)
```
When I open my project, connect to a REPL and click on the `DateTimeFormatter` for example, it goes to a `DateTimeFormatter.java` file implementation and shows the docs. But if I click on any other symbol second time, it starts to give me this error: 
```
Unable to open 'DateTimeParseException.java': Invalid filename.
```
and now, for any of the java symbol it stops showing docs with the same Unable to open <File> error. 
I can reproduce it consistently by closing and re-opening my project.

<img width="419" alt="Screenshot 2021-09-28 at 10 23 37 PM" src="https://user-images.githubusercontent.com/15200937/135139406-dd812631-9007-498b-9dd3-da7d93a079f1.png">

**Comment by bpringe** [comment]
I've not really tried to navigate to Java files before like that, so I'm unfamiliar with if this has ever worked in Calva, or if the issue is with Calva or upstream.

**Comment by pratik97** [comment]
@bpringe we had a [conversation](https://clojurians.slack.com/archives/CBE668G4R/p1632718946361200) on Slack about this, @PEZ thinks it's supported whenever REPL is connected.

**Comment by PEZ** [comment]
This totally works when I try it. Have you loaded the file, @pratik97?

**Comment by PEZ** [comment]
Slightly off topic: While Calva supports this decently, there is a lot of work still to do to get on par with what CIDER users enjoy: https://youtu.be/aYA4AAjLfT0?t=1120

**Comment by pratik97** [comment]
Yes I am loading the file, in fact, I just start the repl before clicking on java symbols. Do you have red hat java extension installed? I think that's responsible for navigation

**Comment by pratik97** [comment]
@PEZ also wanted to know if in your VSCode left panel(explorer), do you have a `JAVA Projects` section? For me, when it initially works I have a java file opened from that section.

**Comment by PEZ** [comment]
> I just start the repl before clicking on java symbols

So, just to be certain. Do you follow this process?

1. Start and connect the REPL
2. Load the Clojure file using the command: **Calva: Load Current File and Dependencies**
3. Examine Java symbols

I don't see you mention step two there.

>  in your VSCode left panel(explorer), do you have a _JAVA Projects_ section?

Never heard of such a thing. 😄 Is it something from the Java Extension, maybe? I don't use that.

**Comment by pratik97** [comment]
Yes, I am doing the same steps. Although, I thought if we just start the REPL we don't have to load a file if we didn't changed it, but loading it and examining the Java symbols is also not working. I mean, it works only for the short time, for the first symbol and then it breaks. I can try to repro this in smaller project.

**Comment by PEZ** [comment]
> Although, I thought if we just start the REPL we don't have to load a file if we didn't changed it

Starting the REPL does not load anything. Calva needs the initial load to start functioning properly.

**Comment by bpringe** [comment]
I tried to navigate to a Java source file in the past and could not, and I was informed that the Java sources aren't installed with the JDK on some OSs/distributions. 

See the conversation starting with [this comment](https://github.com/clojure-emacs/orchard/issues/103#issuecomment-764842012). @bbatsov informed me in [this comment](https://github.com/clojure-emacs/orchard/issues/103#issuecomment-764936527) of what I just mentioned.

> On Linux the sources are a separate package (at least on Debian-like distros), I'm not sure how it is on other OS-es. You should have a file named src.zip somewhere. For me it's in /usr/lib/jvm/openjdk-14/src.zip.

So, it does look like in some cases there are manual steps involved with installing the Java source. I don't think I ended up getting it working, but I didn't really have a need to. If anyone does this manual source install and gets the navigation to Java source working, please document your steps here. It would be appreciated, and maybe we could add instructions in the docs for this.

**Comment by bbatsov** [comment]
It should certainly work if the sources are installed and on the classpath. Same with the sources for any Java package really. Today we also have a small Lein plugin to help with the sources https://github.com/clojure-emacs/enrich-classpath //cc @vemv

**Comment by vemv** [comment]
Worth noting, currently the library / plugin (a tools.deps story is around the corner) fetches sources for _third-party deps_, not for JDK sources themselves.

I have however already at hand the code for adding that feature, have tested it out very recently, etc.

Expect a new release very soon!

**Comment by pratik97** [comment]
Tried it after uninstalling the Java extension(by RedHat), and it started working for me. 
I re-installed the extension and it's still working for me. I don't have much idea on what was causing it before, but I will observe this for couple of days before closing the issue.

**Comment by pratik97** [comment]
Closing this issue, I can't reproduce this with my current setup, it was mostly some race condition with other java extension.
