### ISSUE TITLE
Create PR template for submitting docs-only changes/additions

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1326]
I saw @PEZ mention this in https://github.com/BetterThanTomorrow/calva/pull/1322, so here's the issue so we don't forget. 😄

**Comment by PEZ** [comment]
I actually did this already. Just that it is really awkward to use it. You are supposed to edit the PR url... Maybe we can add some instruction about that to the default template...

**Comment by bpringe** [comment]
Oh, I missed that. That does seem awkward. It would be nice if the user were presented with the templates when creating a PR, as they are when creating an issue when multiple issue templates exist.
