### ISSUE TITLE
Connection Timeout when connecting to running nREPL

### ISSUE THREAD

**Issue by sseekamp0** [BetterThanTomorrow/calva#134]
Hi!
I'm having connection timeout issues when connecting to nRepl. I'm assuming it's because I'm behind a firewall, and unable to connect to external websites to download dependencies. Is there anyway around that?

**Comment by PEZ** [comment]
Hello!
No dependencies should start downloading when connecting. So, you can start the repl fine? Can you describe the steps you take from starting the repl to connecting and the error message you get?

**Comment by sseekamp0** [comment]
I have a repl that I'm attempting to connect to, through typing in the port number. However, when I attempt to connect I eventually get a message after a timeout occurs.

Connecting to nREPL at localhost:59136
org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at reply:reply:jar:0.3.7

Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at reply:reply:jar:0.3.7
 at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies (DefaultDependencyCollector.java:300)
    org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:350)

I'm behind a firewall, so I'm thinking it's related to that?

**Comment by PEZ** [comment]
It does look like it starts to collect dependencies... It is also strange that you need to type in the port number. Calva should pick that up from the `.nrepl-port` file in the root of the workspace.

**Comment by cfehse** [comment]
@sseekamp0 

We made quite a lot of improvements regarding the connection process in version 2.0.49. Perhaps you can give it a try. I will close the issue for now but if the problem persists feel free to reopen it. 

Thanks.
