### ISSUE TITLE
Prevent warning during deps.edn jack-in

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1355]
The warning: `WARNING: Implicit use of clojure.main with options is deprecated, use -M`

It seems we can remove this just by adding `-M` to the jack-in command. I tested with this command:

```sh
clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.8.3"},cider/cider-nrepl {:mvn/version,"0.26.0"}}}' -M -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
```

**Comment by bpringe** [comment]
Further discussion is here: https://github.com/BetterThanTomorrow/calva/issues/826.

@PEZ Should we close this as a duplicate?

**Comment by PEZ** [comment]
This one is more visible. Let's close'em together with the fix. =)
