### ISSUE TITLE
Formatting form with comma whitespace inserts 0 and places the cursor wrong

### ISSUE THREAD

**Issue by pinkfrog9** [BetterThanTomorrow/calva#1370]
```
(
<Cursor>
,)
```
type the Tab key, gives
```
<Cursor>
(0)
```

Note the comma in ,) is intentionally left there.

**Comment by PEZ** [comment]
Thanks!

I've seen similar things, but never such a minimal repro.

**Comment by PEZ** [comment]
FYI. If you are using the comma to try keep the closing paren in place, that won't work anyway. The formatter removes surrounding whitespace. It's probably why we have that bug, actually, coming to think of it.

**Comment by pinkfrog9** [comment]
Yes, the comma is intentionally put there. I learned this trick from Sean Corfield's talk on repl development: https://www.youtube.com/watch?v=gIoadGfm5T8&t=957s

**Comment by PEZ** [comment]
Still, it won't work in Calva. And since a while no such tricks are needed in `(comment ...)` blocks.
