### ISSUE TITLE
Version v2.0.224 causes problems on some machines (possibly Windows related)

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1379]
* UPDATE, Nov 11: The latest 226 VSIX build seems to have fixed the problems. It's the one linked in this issue. Please keep testing it. I don't want to release another breaking release too soon. 😄 
* UPDATE 2, Nov 11: I've received report that the problem show up in 226 still, just in a different ”place”. **Paredit delete to end of list** was an example.
 
Symptoms. Editing files in CRLF mode, entering brackets instead inputs other characters. 

If you just need to work and do not have time for helping with fixing, use v2.0.225 which reverts the changes.

If you have a kind heart and want to help me bring Parinfer to Calva, know that there is a 226 dev build that can we can use for investigating this together. please read on:

Why it happens I don't know, but it has to do with a new method for auto-closing brackets, which was enabled by default in 224 and made impossible to code for the users where it didn’t work.

I can't reproduce on Mac, nor on Windows, so I really need help. If you can reproduce the problem and want to [run Calva in debug mode](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva) to help pinpoint, that would be so awesome. ❤️ 

## How to test with dev 226

* Download and install [v2.0.226 VSIX](https://15952-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.226-dev-ec9f3fcb.vsix)
* Read the [WIP docs](https://github.com/BetterThanTomorrow/calva/blob/dev/docs/site/parinfer.md) (Github doesn’t render it very well, but anyway)

This is what I currently want tested:

* Used with its defaults (Parinfer and Format Forward off) it should work without troubles.
* Used with Parinfer and Format Forward on, it should deliver the experimental features (mostly trouble free)
* Used with the new auto-closing it will keep causing problems in CRLF files, under some unknown circumstances. 226 can therefore be used to help figure out a way for me to reproduce the problem. (Which I can’t yet.)

### General, as-things-were, testing

To test that it doesn’t cause problems ”as is” run it without changing any Calva settings.

### Parinfer fans

To test the experimental features, use these settings:

```json
  "calva.fmt.formatForward": true,
  "calva.fmt.inferParensAsYouType": true,
  "[clojure]": {
      "editor.autoClosingBrackets": "never",
  }
```

### Bug hunters

To try provoke the problem, edit files in CRLF mode and have these setting:

```
  "calva.paredit.strictPreventUnmatchedClosingBracket": true,
  "calva.paredit.strictAutoClosingBrackets": true,
  "calva.fmt.formatForward": false,
  "calva.fmt.inferParensAsYouType": false,
  "[clojure]": {
      "editor.autoClosingBrackets": "never",
  }
```

Thanks in advance! ❤️ 🙏

**Comment by kstehn** [comment]
For a colleague of mine the newest version (2.0.225) just fixed this

**Comment by PEZ** [comment]
@kstehn, was it also only for entering new opening parens? It would be great to know what other extensions your colleagues has, and also version of Windows and such.

**Comment by kstehn** [comment]
Yes only for opening `{,(,[`
There aren't many extensions, mainly calva.
And Windows its 10.

If i use the version it works for me.
But two things are diffrent 
1. i use Windows 11
2. i use completly diffrent keyboard layout (Neo2) => if i use the normal layout it still works 🤨

**Comment by PEZ** [comment]
It has to do with CRLF line endings. So if you don't edit files in that mode, you won't see the problem, @kstehn.

Even so, I can't reproduce it on my Windows 10 machine.

**Comment by PEZ** [comment]
I've updated the issue description, @kstehn (and anyone 😄).
