### ISSUE TITLE
Calva did not download clojure-lsp, might need to use VS Code's HTTP Proxy settings

### ISSUE THREAD

**Issue by pbwolf** [BetterThanTomorrow/calva#1380]
Calva (in VS Code in Linux) did not invoke clojure-lsp, but after I installed my own clojure-lsp Calva invoked it without trouble.  Notably, I needed curl to use an HTTP proxy to get clojure-lsp.  Perhaps Calva could do likewise.  I notice that VS Code has HTTP proxy settings.

**Comment by bpringe** [comment]
Hi, thanks for reporting. Can you describe in more detail what happened when the download failed and/or clojure-lsp failed to start?

I'm not sure I've heard of this issue before, so I wonder what in particular about your machine requires the download to happen via proxy.

**Comment by pbwolf** [comment]
Oops, Calva downloaded clojure-lsp OK after I put the proxy literally into VS Code's settings. (The VS Code settings page says to leave the proxy blank to inherit from environment variables, but something evidently did not go as expected on that score.... at any rate, presumably not a problem for Calva to solve.)

**Comment by bpringe** [comment]
I'm glad you resolved the issue! I believe in some cases environment variables may not be seen by VS Code unless it's started from a terminal where the environment variables are readable, via the `code` command.

**Comment by bpringe** [comment]
See here for more on what I said above (though this may not have been your issue): https://calva.io/connect/#environment-variables-are-not-readable-from-repl.
