### ISSUE TITLE
Test runner not finding tests with + in middle of the name

### ISSUE THREAD

**Issue by rjerue** [BetterThanTomorrow/calva#1383]
Given the following file:

```clojure
(ns app.fun-test
  (:require [clojure.test :refer [deftest is]]))

(deftest name-with+in-it
  (is true))

(deftest name-with-plus-end+
  (is true))

(deftest name-with-plus-in-it
  (is true))

(deftest +name-with-plus-start
  (is true))
```

this is the output

```
; Evaluating file: fun_test.clj
#'app.fun-test/name-with-plus-in-it
; Running test: name-with+in-it…
; No tests found. 😱, ns: 0, vars: 0
clj꞉app.fun-test꞉> 
; Evaluating file: fun_test.clj
#'app.fun-test/name-with-plus-in-it
; Running test: name-with-plus-end+…
; 1 tests finished, all passing 👍, ns: 1, vars: 1
clj꞉app.fun-test꞉> 
; Evaluating file: fun_test.clj
#'app.fun-test/name-with-plus-in-it
; Running test: name-with-plus-in-it…
; 1 tests finished, all passing 👍, ns: 1, vars: 1
clj꞉app.fun-test꞉> 
; Evaluating file: fun_test.clj
#'app.fun-test/+name-with-plus-start
; Running test: +name-with-plus-start…
```

Note, the last one hangs with the following error in the console:

```
Exception in thread "nREPL-session-f877bb99-3510-4125-81e9-6647caa1a1dd" 
java.util.regex.PatternSyntaxException: Dangling meta character '+' near index 0
+name-with-plus-end
```

The last error `+`  regex escaping fun a coworker had while searching for the test lead me to believe that there's a regex escaping issue somewhere with the `+` character.

Expected behavior is that these tests would be detected with the _Run Current Test_ command.

**Comment by bpringe** [comment]
Thanks for reporting! We should see if this might be an issue with nrepl/cider-nrepl. Calva pretty much just uses cider-nrepl to run the tests - see here: https://github.com/BetterThanTomorrow/calva/blob/published/src/testRunner.ts.

Do you have the same / similar issues when running the command to run all tests and the command to run all tests for the namespace?

**Comment by bpringe** [comment]
@bbatsov Have you seen something like this before?

**Comment by rjerue** [comment]
Using the same file as above, if I use the run all tests or run all tests in current namespace, things seem to work fine. It's only the individual "run current test" where things break.

**Comment by bbatsov** [comment]
@bpringe I haven't seen this problem, but it's likely on cider-nrepl's side. Feel free to file a ticket there, so we don't forget to look into this. I guess it should be an easy fix.

**Comment by bpringe** [comment]
It seems we can/should fix this issue in Calva. Details are here: https://github.com/clojure-emacs/cider-nrepl/issues/730#issuecomment-978703607.

> If you pass a + it should be escaped (presumably client-side: we shouldn't second-guess what a client meant).

**Comment by marcomorain** [comment]
I might take a look at this this week.

**Comment by marcomorain** [comment]
I've opened a PR that addresses this.
