### ISSUE TITLE
thousands of json files get created with seemingly no purpose. 

### ISSUE THREAD

**Issue by inakirosa** [BetterThanTomorrow/calva#1385]
self explanatory. I downloaded the app and immediately thousands of files got into my changelog. I like the app so far but will be unusable if it's destroying my git history by adding thousands of files

**Comment by bpringe** [comment]
Hi! I've not heard of Calva causing something like this before. Are you sure it's coming from Calva? What are the names of the json files like, and what are the contents?

**Comment by bpringe** [comment]
Besides proving the info asked for above, I suggest you disable Calva and see if the issue still occurs. You can also try using [bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to find which extension might be causing the problem.

**Comment by TuggyNE** [comment]
Just add `.calva`, `.clj-kondo`, and `.lsp` to your `.gitignore`. All the files Calva and its dependencies ever add are in those three folders.

Well, except for the REPL files; you can also ignore `.lein-repl-history` and `.nrepl-port` in the project root.

**Comment by bpringe** [comment]
You might not want to ignore everything in `.clj-kondo`, such as if you want to persist the config file. You may just want to ignore `.clj-kondo/.cache`. The same goes for `.lsp`. You may want to just ignore `.lsp/.cache`.

**Comment by bpringe** [comment]
I'm going to close this, but please let us know if you're still having issues @inakirosa.
