### ISSUE TITLE
Connecting to an out-of-process nREPL server and a merged Figwheel-main build

### ISSUE THREAD

**Issue by danieroux** [BetterThanTomorrow/calva#1386]
As discussed with @PEZ on Slack:

- We start nREPL out-of-process and then connect to it
- We start figwheel-main with merged builds

The README.md in this repo explains the ideal workflow: https://github.com/danieroux/calva-clojurescript-usage

The less magic, the better ;-)

**Comment by danieroux** [comment]
We structure builds this way:

- `common.cljs.edn` is the base setup, for `cljs.main`, annotated with some Figwheel options that does not come into play for `cljs.main`.
- `min.cljs.edn` adds minification
- `some-domain.com.cljs.edn` is a production deploy to that domain, with all its flags twiddled and variables set for prod.

This allows us to do this for a production deploy, as a merged build: 

```
clojure -M --main cljs.main --compile-opts common.cljs.edn --compile-opts min.cljs.edn --compile-opts some-domain.com.cljs.edn --compile
```

Only vanilla `cljs.main`, no Figwheel required. Stable, clean, clear.

So for development we merge `common.cljs.edn` and `local.cljs.edn`. And `local.cljs.edn` has preloads, and development toggles on. That's how we start Figwheel in dev then, by merging those two:

```Clojure
(defn start-cljs-repl []
  (let [read-build (figwheel.main.api/read-build "common" "local")
        build-id   (:id read-build)]
    (try
      (figwheel.main.api/start {:mode :serve} read-build)
      (figwheel.main.api/cljs-repl build-id)
      (catch RuntimeException _e
        (println "The build is already running, connection to the REPL only")
        (figwheel.main.api/cljs-repl build-id)))))
```

**Comment by PEZ** [comment]
Thanks. It is strange that the built-in Figwheel Main sequence doesn't work for connecting to `local` in that repro-repo. I don't really understand what goes wrong.

Anyway, I pushed a PR to that reoro, containing a [custom repl connect sequence](https://calva.io/connect-sequences/), that simply calls your `(start-cljs-repl)` there. It looks like so:

```json
  "calva.replConnectSequences": [
    {
      "name": "My local build",
      "projectType": "deps.edn",
      "cljsType": {
        "dependsOn": "Figwheel Main",
        "connectCode": "(start-cljs-repl)",
        "isConnectedRegExp": "To quit, type: :cljs/quit",
        "buildsRequired": false,
      }
    }
  ]
```

Not sure the last two settings there are required. You can experiment with removing them and see if it works anyway.
