### ISSUE TITLE
How do I get this off of my system

### ISSUE THREAD

**Issue by elijahrdorman** [BetterThanTomorrow/calva#1388]
I use vim (M1 mac).

I installed calva and cannot get <esc> to remap back to vim.

I completely removed these directories and uninstalled vscode

```
rm -fr ~/Library/Preferences/com.microsoft.VSCode.helper.plist 
rm -fr ~/Library/Preferences/com.microsoft.VSCode.plist 
rm -fr ~/Library/Caches/com.microsoft.VSCode
rm -fr ~/Library/Caches/com.microsoft.VSCode.ShipIt/
rm -fr ~/Library/Application\ Support/Code/
rm -fr ~/Library/Saved\ Application\ State/com.microsoft.VSCode.savedState/
rm -rf ~/.vscode*
```

Still no luck.

Is there something else Calva is doing somewhere?

**Comment by PEZ** [comment]
> I installed calva and cannot get to remap back to vim.

What does ”cannot get to remap back to vim” mean?

**Comment by bpringe** [comment]
@elijahrdorman Did installing Calva cause some issue for you, and did you uninstall the Calva extension from VS Code?

**Comment by PEZ** [comment]
Closing this, because inactivity.
