### ISSUE TITLE
Avoid linting source files

### ISSUE THREAD

**Issue by andresrgz** [BetterThanTomorrow/calva#139]
When a source file is opened, for example `core.clj` when going to the definition of `println`, the extension tries to lint this file but fails because of the path that is being sent.

![image](https://user-images.githubusercontent.com/11339972/53701590-4f032000-3dc4-11e9-9751-189512375f75.png)

Because of this error, perhaps linting should be disabled for source files.

**Comment by cfehse** [comment]
This should be fixed in version 2.0.49.
