### ISSUE TITLE
Running failing tests in Calva don't produce line numbers or stack trace

### ISSUE THREAD

**Issue by dharmaturtle** [BetterThanTomorrow/calva#1393]
Minimal code:

```clojure
(ns my-tests
  (:require
   [clojure.test :refer :all]))

(defn may-throw
  [x]
  (< x 0))

(deftest missing-stack+line-numbers
  (is (may-throw nil)))

#_(clojure.test/run-all-tests)
```

`Calva: Run Tests for Current Namespace` does not print a stack trace or helpful line number. An example output:

```clojure
clj꞉user꞉> 
; Evaluating file: my_tests.clj
#'my-tests/missing-stack+line-numbers
; Running tests for my-tests...
; ERROR in my-tests/missing-stack+line-numbers (line 10):
; error: java.lang.NullPointerException (Numbers.java)
; expected:
(may-throw nil)
; 1 tests finished, problems found. 😭 errors: 1, failures: 0, ns: 1, vars: 1
```

Line 10 is `(is (may-throw nil)`, which is where the test is invoked, but not where the error is thrown. Notably evaluating `(may-throw nil)` by itself or evaluating `(clojure.test/run-all-tests)` yield correct line numbers. E.g.:

```clojure
clj꞉my-tests꞉> 
; Execution error (NullPointerException) at my-tests/may-throw (my_tests.clj:7).
; null
```

[Minimal repo](https://github.com/dharmaturtle/calva-minimal-2).

[Video of the issue](https://youtu.be/f976_NXuFjg).

I'm pretty new to Clojure so there could be something obvious I'm missing!

**Comment by bpringe** [comment]
Thank for the detailed report! This would take some looking into. Calva uses cider-nrepl to run tests, and it could be that cider-nrepl is not returning the desired info, or that Calva is not including it in the output.

If you'd like to take some time to look into it more, [hacking on Calva](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva) is easy! The test runner code is located [here](https://github.com/BetterThanTomorrow/calva/blob/published/src/testRunner.ts).

**Comment by dharmaturtle** [comment]
Ah, looks like it was an cider-nrepl problem. [They merged a fix ~week ago.](https://github.com/clojure-emacs/cider-nrepl/pull/729)

**Comment by bpringe** [comment]
Ah, thanks for the info!
