### ISSUE TITLE
"extract to new function" doesn't respect clj-kondo/ignore comments

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva#1399]
Especially after the introduction of clojure-lsp I added a few `:clj-kondo/ignore` comments before some sexp in my code.
However, when I try to extract a part of this code to a new function the clj-kondo comment stays before the extracted function, which usually is not what I would expect.
 
eg:
```
#_{:clj-kondo/ignore [:clojure-lsp/unused-public-var]}
(defn foo []
  (do 1))
```
after the refactor command becomes:
```
#_{:clj-kondo/ignore [:clojure-lsp/unused-public-var]}
(defn bar []
  (do 1))

(defn foo []
  (bar))
```

In the case of `:clojure-lsp/unused-public-var` it's very clear that the behaviour is not ideal. I imagine that in most cases it would be better if the `ignore` stuck with `foo`. However, for other types of warnings and errors it might be hard to judge which would be the best result. WDYT?

Would a change like that require too many changes in the way refactor is done?

**Comment by bpringe** [comment]
Calva calls clojure-lsp for this functionality. @ericdallo What are your thoughts on this?

**Comment by ericdallo** [comment]
Yeah, that's something to be fixed on clojure-lsp, please open an issue there with the minimal repro

**Comment by bpringe** [comment]
@claynon Please open an issue on clojure-lsp's repo, and I'll go ahead and close this one.

**Comment by ericdallo** [comment]
Good news @claynon I made a quick fix and it's working on clojure-lsp master, it should be available on next release, couple of days :)

**Comment by claynon** [comment]
That‘s Great! Thanks folks 😄
