### ISSUE TITLE
Error while peeking definition of a namespace

### ISSUE THREAD

**Issue by andresrgz** [BetterThanTomorrow/calva#140]
This is a minor error which is only visible in the developer console. If you peek the definition of a namespace, the following error is thrown:

![image](https://user-images.githubusercontent.com/11339972/53701951-b4a4db80-3dc7-11e9-8de4-2e72bfaa0f71.png)

This doesn't stop this feature from working because the preview of the namespace's definition is still shown correctly.

**Comment by cfehse** [comment]
This is fixed in version 2.0.49.
