### ISSUE TITLE
Ability to change the library/function used by nrepl for printing, to gain pretty printing and coloured output

### ISSUE THREAD

**Issue by alzadude** [BetterThanTomorrow/calva#141]
Hi there,

I noticed that as of `nrepl` 0.6 / `cider` 0.21, it's possible to override how printing is done with nrepl, for example to use other printers like `clojure.pprint/pprint`, fipp, puget and zprint, instead of the default `clojure.core/pr`:

- https://nrepl.org/nrepl/0.6.0/design/middleware.html#_pretty_printing
- https://github.com/clojure-emacs/cider/blob/master/doc/pretty_printing.md

What would be needed to use this new feature with Calva? It would be great to get pretty printing, with coloured output at the repl.

FWIW, I'm using `nrepl` 0.6 started via `clj` / `deps.edn`, and I configure Calva to use `reply` as a nrepl client to launch the Clojure and ClojureScript repls. As in, I'm not using Leiningen.

Thanks!

**Comment by PEZ** [comment]
Hello,

As for pretty printing with colored output. That is solved w/o this new abilities by the new REPL window. Have you tried that?

I'm not sure how to leverage this printer override, yet. What other use cases do you see, besides syntax highlighted printing?

**Comment by alzadude** [comment]
Hi @PEZ!

> Hello,
> As for pretty printing with colored output. That is solved w/o this new abilities by the new REPL window. Have you tried that?

I must be missing a trick.. I didn't know about any new REPL window, I just checked the README and I couldn't see anything about that.. How do I use that? 🙂

> I'm not sure how to leverage this printer override, yet. What other use cases do you see, besides syntax highlighted printing?

Well I was thinking it might be useful to allow the user to specify which printer library/function to use, since they might have reasons to use one in particular, e.g. `clojure.pprint/pprint`, fipp, puget or zprint.

Although I don't know the details, I was assuming it would be useful to gain this functionality through `cider-nrepl` and the new print middleware in `nrepl` (since Calva already uses `cider-nrepl`), to benefit from the improvements made in that common library. I don't really know enough to comment, but it just seemed like a good idea!

Also, while I'm here I was wondering how to get the same feature(s) in a ClojureScript REPL in addition to a Clojure REPL, for example a ClojureScript REPL launched using `piggieback` (this I how I launch my ClojureScript REPL in Calva).

Thanks!

**Comment by PEZ** [comment]
> I must be missing a trick.. I didn't know about any new REPL window, I just checked the README and I couldn't see anything about that.. How do I use that? 🙂

Yeah, it is not released yet so the README has no mention. But I have posted dev builds including the feature here and there. Including it here as well now:

[clojure4vscode-1.3.65-SNAPSHOT.zip](https://github.com/BetterThanTomorrow/calva/files/2948831/clojure4vscode-1.3.65-SNAPSHOT.zip)

Rename it from `.zip` to `.vsix` and install it in VS Code. I am looking forward to your feedback! Check the current issues list for how I have been reporting issues on it.

**Comment by cfehse** [comment]
This is fixed in version 2.0.49.
