### ISSUE TITLE
The version of cljfmt used by calva can't handle shebang

### ISSUE THREAD

**Issue by Cnly** [BetterThanTomorrow/calva#1414]
It [seems](https://github.com/pez/cljfmt) calva is using cljfmt 0.6.3, but this version can't handle shebang lines.

When given a file

```clj
#! /usr/bin/env bb

(println "Hello!"    )
```

the "Format Document" function in VSCode will do nothing, and manually invoking cljfmt gives

```
Failed to format file: test.clj
clojure.lang.ExceptionInfo: Invalid symbol: /usr/bin/env.
1 file(s) could not be parsed for formatting
```

cljfmt 0.8.0 doesn't have this problem.

**Comment by PEZ** [comment]
Thanks!

Let's also add to this that the Clojure Reader treats `#!` the same as `;`. Calva doesn't treat it like that consistently also in other regards.

**Comment by bpringe** [comment]
Linked this related issue, since it seems that using the latest cljfmt will help: https://github.com/BetterThanTomorrow/calva/issues/1179
