### ISSUE TITLE
Pretty printer not working

### ISSUE THREAD

**Issue by Cyrik** [BetterThanTomorrow/calva#1415]
I'm on version 2.0.227 of calva. When I'm in my project the following repl interaction doesn't seem to use full pretty printing. If 
I turn off pretty printing i get the same result, just not sorted by key.

```clojure
(require '[zprint.core :as zp])
(def example {:this :is :a :test :it :is :only :a :test :foo :bar :baz :but :better :if :it :does :not :fit :on :one :line})
example
;; => {:a :test, :bar :baz, :but :better, :does :not, :fit :on, :if :it, :it :is, :one :line, :only :a, :test :foo, :this :is}
(zp/zprint example)
;; => {:a :test
 :bar :baz
 :but :better
 :does :not
 :fit :on
 :if :it
 :it :is
 :one :line
 :only :a
 :test :foo
 :this :is}
(require 'clojure.pprint)
(pprint/pprint example)
;; => {:but :better,
 :one :line,
 :only :a,
 :if :it,
 :fit :on,
 :this :is,
 :does :not,
 :bar :baz,
 :it :is,
 :test :foo,
 :a :test}
````
relevant settings.json:
```
    "calva.prettyPrintingOptions": {

        "enabled": true,
        "width": 120,
        "maxLength": 100,
        "printEngine": "zprint"
    },
```

**Comment by bpringe** [comment]
I can reproduce this. @PEZ Any idea what's going on here?

Also just FYI, the docs say about zprint:

> Will need to be configured before Jack-in if you want Calva's help to inject its dependencies

However, Calva doesn't seem to add zprint to the repl. I had to add it to my project dependencies in order for pretty printing to work.

**Comment by bpringe** [comment]
@Cyrik Does this seem to be an issue with all the print engines?

**Comment by Cyrik** [comment]
> However, Calva doesn't seem to add zprint to the repl. 

it does add it for me, just in a very old version, something like 0.4, and it adds it as zprint, not zprint/zprint so you get a warning. but I've had zprint in my classpath anyway, so I don't mind.

> Does this seem to be an issue with all the print engines?

I only tried pprint/calva/zprint. calva and zprint give the same output, at least for the few I tried. pprint is "worse" and doesn't even sort the map.

**Comment by bpringe** [comment]
> "width": 120,

It seems the width of the output doesn't exceed your set width of `120`, which is why you don't see the map pretty printed when you evaluate `example` with pprint enabled. Try lowering the "width" setting or adding more content to `example`.

If I convert `example` to a string and count it, I get `120` but that includes the commas that are added in the conversion.

```clojure
  (-> example
      str
      count)
  ;; => 120
```

With the below settings, the map is pretty printed and sorted when I evaluate `example`:

```json
    "calva.prettyPrintingOptions": {
        "enabled": true,
        "width": 100,
        "maxLength": 50,
        "printEngine": "zprint"
    }
```

**Comment by PEZ** [comment]
I think it sounds like the pretty printing is working, even if not to the expectations of @Cyrik .

The different engines will behave differently with the same settings. The semantics vary, and also the engines just care about different things.

The difference between `zprint` and `calva` is that `zprint` will happen on the server side, before nREPL hands over the results to Calva, while `calva` (which is also using zprint) will be that nREPL does no pretty printing, and it instead happens on the client side. It's mentioned here: https://calva.io/pprint/ (The server side options are actually links in that table, so you can look up how they will behave.) Server/client gets important for some scenarios e.g. when data readers are involved. Server side pretty printing a datomic db value can really blow up. While on the client side it will just be the tagged reference.

**Comment by Cyrik** [comment]
yes, you are right, it's working if I have longer output. It's a little unfortunate that the example was too short.
