### ISSUE TITLE
Cant connect to repl, hanging forever.

### ISSUE THREAD

**Issue by anyayunli** [BetterThanTomorrow/calva#142]
<img width="259" alt="screen shot 2019-03-07 at 2 09 26 pm" src="https://user-images.githubusercontent.com/5514769/53992827-a6660080-40e2-11e9-8f98-dac3abac5231.png">

<img width="599" alt="screen shot 2019-03-07 at 2 06 22 pm" src="https://user-images.githubusercontent.com/5514769/53992704-5be48400-40e2-11e9-9b45-ce36e7d11591.png">
<img width="1662" alt="screen shot 2019-03-07 at 2 07 00 pm" src="https://user-images.githubusercontent.com/5514769/53992723-6acb3680-40e2-11e9-83eb-c06e2f2d85e9.png">

calva connect is hanging forever and cant connects, let me know if you need other info.

**Comment by synthomat** [comment]
Just out of curiosity, can you open any terminal (iTerm, Terminal.app, etc.) windows after this happens? I noticed that I cannot, they hang at the login process. Not sure if that problem is related somehow but I noticed that both problems appear at the same time.

**Comment by PEZ** [comment]
There is another issue about freezing terminals. I'm in the run and can't
look it up right now. But I have posted a dev build of Calva there, which
hopefully dodges the terminal issue. It's a quite early build of the new
REPL window, but quite useful. I use that build daily. Give it a try and
let me know how it fares, please!

**Comment by synthomat** [comment]
The other terminal related ticket is #83

**Comment by PEZ** [comment]
Closing this now. Calva 2 should have fixed the issue. Reopen if it that doesn't check out.

**Comment by anyayunli** [comment]
FYI, tried the Calva2, it's not hanging, however, i still cant connect.

![Screen Shot 2019-06-05 at 11 13 47 AM](https://user-images.githubusercontent.com/5514769/58979501-0ec88a80-8783-11e9-9cf8-6720d4092e3f.png)
![Screen Shot 2019-06-05 at 11 13 59 AM](https://user-images.githubusercontent.com/5514769/58979502-0f612100-8783-11e9-8399-22384846d955.png)

**Comment by PEZ** [comment]
Can you try with letting Calva start the repl for you?

**Comment by anyayunli** [comment]
@PEZ yes, Calva start the repo works well. But it will be nice it could connect to running repl

**Comment by PEZ** [comment]
Good to know. If you start your project with the command line that Calva uses in the *Calva Jack-in* task, can you connect then?
