### ISSUE TITLE
dialog with two definitions for one function on Go To Definition (F12)

### ISSUE THREAD

**Issue by blueskyonmars** [BetterThanTomorrow/calva#1426]
I have a simple file with two functions, one which calls the other.  When I stand a function call `(doubleme)` and hit F12, I see a popup to disambiguate which function it should go to.  There's only one actual function in the code though.

Project is attached, code looks like this:
```
(ns mytest.core)

(defn- doubleme [])

(defn foo
  "I don't do a whole lot."
  [x]
  (doubleme)
  (println x "Hello, World!"))

```

I noticed three phases, just after I open the project with VS Code+Calva: 
1) immediately after, nothing happens when I hit F12 except a message saying "No definition found for doubleme", 
2) after 20 seconds or so when I hit F12 it goes directly to the function without a popup, and then 
3) eventually a popup gets in the way when I hit F12.  Phase 3 seems to be after I see the message "Connected to nREPL."   The whole process takes maybe 2 minutes on my old OS X Big Sur system.

I first saw this in a different project, and we discussed on the calva slack channel.

[mytest.zip](https://github.com/BetterThanTomorrow/calva/files/7672517/mytest.zip)
[clojure-language-client-output.log](https://github.com/BetterThanTomorrow/calva/files/7672521/clojure-language-client-output.log)
![dialog-screenshot](https://user-images.githubusercontent.com/16437998/145129606-0c629f2d-e150-49c8-80fb-7e62b1eb74af.png)

**Comment by bpringe** [comment]
> Phase 3 seems to be after I see the message "Connected to nREPL."

So you are connecting Calva to an nrepl server or jacking in? Calva doesn't connect to nrepl automatically (in any case that I know of), so I just want to make sure I understand correctly.

**Comment by PEZ** [comment]
The message `Connected to nREPL.` does not come from Calva.

I'm guessing you are using some other nREPL extension (maybe the *Clojure* extension?). Then maybe both clojure-lsp and that other extension finds the function and that's why you get two options.

**Comment by blueskyonmars** [comment]
OMG, you're right!  I had tried the Clojure extension before I found Calva and forgot it was still enabled.  Sorry!

**Comment by PEZ** [comment]
Don't be sorry. It is quite common and you are reminding us that we should maybe detect this situation and issue a warning about it, as we do with some other potential extension conflicts.

**Comment by PEZ** [comment]
This issue is an excellent example of providing context, btw. It made it possible to spot a probable cause quickly.

**Comment by PEZ** [comment]
@bpringe 

>  Calva doesn't connect to nrepl automatically (in any case that I know of), so I just want to make sure I understand correctly.

I just tried with the Clojure extension installed. It actually just starts a REPL and connects automatically. 😄
