### ISSUE TITLE
Inform about conflict with the Clojure extension

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1427]
It is not uncommon for VS Code clojurians to try some different extension, among them Calva. It is probably extra common to try the [Clojure](https://marketplace.visualstudio.com/items?itemName=avli.clojure) extension early. However as #1426 shows, it overlaps with a lot of what Calva provides, and it is not clear to users that they might be using the nREPL services from there, rather than from Calva. Which creates confusion in a lot of ways.

We should consider to issue a warning when we see that the Clojure extension is active while Calva's nREPL services are enabled.

There is also Clover, but the overlap is much smaller and I think it is often a much more deliberate decision to use its REPL instead of Calva's.

**Comment by bpringe** [comment]
I think the intention was for this to be closed. Reopen if I'm mistaken.

**Comment by PEZ** [comment]
We haven't released the fix yet, have we?

**Comment by bpringe** [comment]
My mistake
