### ISSUE TITLE
Build test tree for test explorer with data from clojure-lsp

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1438]
See here for more info: https://github.com/clojure-lsp/clojure-lsp/issues/653#issuecomment-991930377.

CC @marcomorain

**Comment by erickisos** [comment]
So as I'm understanding, we have everything to show that tree in VSCode now?

**Comment by bpringe** [comment]
Yes, there's work being on this by @marcomorain in https://github.com/BetterThanTomorrow/calva/pull/1398.

**Comment by bpringe** [comment]
This was not closed when it should have been, it seems.
