### ISSUE TITLE
[New REPL Window] Loading files silently fails on compilation errors

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#145]
When loading/evaluating current file, if there is an error somewhere in the file that prevents it from compiling fully, things will just fail and the user sees no error messages from the compiler.

This is not particularly a problem with the new REPL window, btw, but it is in this build that the problem resides. I would like the load file error to be displayed in the REPL window, with stack trace and all.

A ”workaround” is to start evaluating suspected forms until you find which one is the problem.

**Comment by cfehse** [comment]
@PEZ 

I think this is fixed, isn't it? I close this error for now.
