### ISSUE TITLE
Jump to definition fails after the destination file has been closed

### ISSUE THREAD

**Issue by pinkfrog9** [BetterThanTomorrow/calva#1458]
How to reproduce this issue:
For example,

1. Clone the repo: https://github.com/dharrigan/startrek
2. Place cursor on the line https://github.com/dharrigan/startrek/blob/master/src/startrek/api/general/swagger.clj/#L11
3. Jump to definition for `create-swagger-handler`
4. **CLOSE** the source file containing `create-swagger-handler`
5. Go back to step 2, and perform jump to definition. It complains no definition found.

**Comment by pinkfrog9** [comment]
cc @ericdallo

**Comment by ericdallo** [comment]
I confirmed the issue happens only with Calva indeed, @bpringe I think we should prioritize this fix somehow, I already faced and saw people facing it multiple times.
I think it's related with calva custom code for opening jars

**Comment by bpringe** [comment]
This is happening without a connected repl, correct?

**Comment by younger-1** [comment]
> This is happening without a connected repl, correct?

To me, yes

**Comment by bpringe** [comment]
https://github.com/BetterThanTomorrow/calva/issues/1494 is a duplicate of this one, but let's close this one and track the issue there, since that issue has some troubleshooting info already.
