### ISSUE TITLE
[Feature Request] Show eval in repl option

### ISSUE THREAD

**Issue by Cyrik** [BetterThanTomorrow/calva#1465]
Currently `eval` commands like "Evaluate current form" send the form to the repl silently and then print the result. Custom repl commands show the forms in the repl first and then print the result.

These should behave the same way and an option should be provided to toggle the behavior.

The initial idea of equal behavior came from @PEZ but I'm happy to work on this since I'm playing with the command code anyway.
Any feedback on the design would be appreciated.

**Comment by PEZ** [comment]
We can consider to model this similar to how we treat pretty print toggling. It's a setting, but has special support in that it can be toggled via the status bar and via a keyboard shortcut.

**Comment by Cyrik** [comment]
I like the hotkey, but at least for me, the status bar is already filling up. I'm not sure this is important enough to have a place on it. But I guess it's fine if it's just an icon instead of text.
