### ISSUE TITLE
Autoload test tree after clojure-lsp end the init process

### ISSUE THREAD

**Issue by erickisos** [BetterThanTomorrow/calva#1467]
Hey folks, I saw the new tes tree implementation, thanks to @marcomorain and everyone else involved. However we were asking if it makes sense to enable this kind of feature automatically, I mean, after clojure-lsp ends all of his process, maybe sending a message to VSCode/Calva or just requesting the data, like a crawler(?)

Idk if this makes sense and what could be the best approach, however it would be great to know your opinion.

Also, FYI @ericdallo (in case you want to keep track of this, maybe some changes could be done in clojure-lsp)

Pls if you think something is wrong with this issue, let me know!

**Comment by ericdallo** [comment]
I'd like to know how it works the vscode test tree, I thought the test tree was related to a single file, does vscode allow showing more than one file in the same test tree?

**Comment by erickisos** [comment]
Yes!

If you have opened multiple files, or if your project has multiple test files it is showed directly in the same tree.

**Comment by ericdallo** [comment]
I see, so what we could do is after clojure-lsp startup, clojure-lsp could send test-tree for each file that detects test analysis, this way calva work OOTB, WDYT @bpringe ?

**Comment by marcomorain** [comment]
The VSCode Test Explorer sits next to the File Explorer and is designed to show data for the whole workspace, not just the current file. The user can enable a filter to ask VSCode to only show items related to the current file in the Explorer. That filtering is done by VSCode automatically. So Calva is free to fill the Explorer with data about all tests.

**Comment by ericdallo** [comment]
Alright, that makes sense, Could you create an issue on clojure-lsp side about this?

**Comment by erickisos** [comment]
I can create that if you want, also, I think I can help with the clojure-lsp side if you find that helpful.

**Comment by erickisos** [comment]
@ericdallo do you know if we can close this issue? Or do we need to wait to check if everything is ok with the clojure-lsp update?

**Comment by ericdallo** [comment]
Calva usually closes the issue if nothing should be changed on its side, but personally, I'd like to double check using calva to confirm the issue was indeed solved.

**Comment by erickisos** [comment]
Amazing, I will check then to be sure that everything is working

**Comment by erickisos** [comment]
This was solved on clojure-lsp side
