### ISSUE TITLE
OSX 12.1 VS Code 1.63.2 terminal set to zsh -> jack-in -> lein: command not found

### ISSUE THREAD

**Issue by e-b** [BetterThanTomorrow/calva#1472]
jacking in, the terminal shows:
```
lein update-in :dependencies conj '[nrepl,"0.9.0"]' -- update-in :plugins conj '[cider/cider-nrepl,"0.27.4"]' -- update-in '[:repl-options,:nrepl-middleware]' conj '["cider.nrepl/cider-middleware"]' -- repl :headless
/bin/sh: lein: command not found
Jack-in process exited. Status: 127
```
However PATH to lein is set and it is executable in zsh directly.
What am I missing?

**Comment by PEZ** [comment]
It could be that the vscode instance does not inherit the path fully. Is it set correctly in a VS Code internal terminal?

If not, a workaround is to start VS Code with the `code` command from a terminal where the path is correct.

**Comment by e-b** [comment]
Yes, starting vs code from the terminal / directory did the trick. Thanks!
