### ISSUE TITLE
Continue to support `-Aalias` for jack-in

### ISSUE THREAD

**Issue by stefan-toubia** [BetterThanTomorrow/calva#1474]
#1417 that changed the jack-in command to use `-Malias` instead of `-Aalias`. This broke jack-in for our company because we're using a forked older version of the Clojure CLI. From what I gather reading over #826, Clojure CLI 1.10.1.697 was only released a little over a year ago, can we reconsider making this configurable?

**Comment by PEZ** [comment]
Yes, we probably should.

**Comment by stefan-toubia** [comment]
This seems like a pretty minor change, I'd be happy to open a PR if we can specify how the configuration option should be implemented. It can be as simple as a boolean, like `calva.jackIn.useDeprecatedAliasFlag`

```json
"calva.jackIn.useDeprecatedAliasFlag": {
    "type": "boolean",
    "default": false,
    "description": "Use the -A flag instead of -M for Clojure CLI versions < 1.10.1.697"
},
```

**Comment by PEZ** [comment]
I like your suggestion. Very clear. We can use `markdownDescription` to make the tooltip easier to parse with the eye.

**Comment by stefan-toubia** [comment]
Hmm, the fixes syntax from the PR didn't close this issue as expected.

**Comment by bpringe** [comment]
@stefan-toubia I think the fixes syntax must be in a commit message for the PR. The auto closing doesn't seem to work if the fixes syntax is just in the PR description.

**Comment by PEZ** [comment]
Which is strange. However. You and I can link the issues on the PR manually, @bpringe. Maybe we just need a way to not forget doing it. 😄

**Comment by bpringe** [comment]
Can PR creators link the issue themselves? If so, and if that does cause the issues to be closed, we can add a checklist item to the PR template about that, or maybe even replace the existing item about adding the fixes syntax in a commit message in favor of the linking.
