### ISSUE TITLE
"Calva says" scrolling

### ISSUE THREAD

**Issue by lspector** [BetterThanTomorrow/calva#148]
Output from "Calva: Evaluate..." commands go to the "Calva says" output area, but after the first screen-full, manual scrolling is required after each new evaluation, to see the results. 

Ideally, I think this should behave like most Terminal windows: by default, auto-scroll to show the last-printed line, but if the user has scrolled back manually then don't auto-scroll until the user again scrolls to the bottom.

**Comment by PEZ** [comment]
Hello. This is vscode built-in behavior that is not under Calva's control. I haven't quite figured out how the scroll-lock is activated, but it happens to me too quite often. Fortunately, you can toggle it off manually. There's a small button for that to the right of the output channel selector:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/30010/55384601-6e0fe180-552b-11e9-9261-2d7c7e27100d.png">

**Comment by lspector** [comment]
Fabulous! No problem that it's not under Calva's control. I just had no idea this switch was there. Thanks!
