### ISSUE TITLE
Using this makes an insane amount of jsons

### ISSUE THREAD

**Issue by inakirosa** [BetterThanTomorrow/calva#1488]
Downloaded this extension, works nicely but it destroys my git history:

![image](https://user-images.githubusercontent.com/86803841/150199575-d8359081-68f2-4300-8679-1abd16d7762e.png)

![image](https://user-images.githubusercontent.com/86803841/150199676-73743f2e-4d64-412b-ab24-8d542efb1a6b.png)

Any help getting this to stop nuking my git history with json files would be greatly appreciated

**Comment by kstehn** [comment]
well you could add this to your .gitignore
`.clj-kondo`
`.calva`
`.lsp`

At least this is what i always do

**Comment by PEZ** [comment]
You probably want to go a bit more precise.

```
.calva/output-window/
.clj-kondo/.cache
.lsp/.cache
```

All these directories may contain config files that you do want to version control.

**Comment by inakirosa** [comment]
man do I feel dumb, thanks!
