### ISSUE TITLE
Show arglists along with documentation in autocomplete popups

### ISSUE THREAD

**Issue by lspector** [BetterThanTomorrow/calva#149]
Control-space shows autocompletions with doc strings, which is fabulous, but the arglists should really be included too. Doc strings refer to the args, but without seeing the arglists themselves one doesn't know what order they come in, etc.

**Comment by PEZ** [comment]
Yeah, that should really be fixed.

**Comment by lspector** [comment]
I see that this is handled correctly in the new REPL window :), but it would be nice for ot to also work in the editor window.

**Comment by cfehse** [comment]
This is fixed in version 2.0.48.
