### ISSUE TITLE
Exception thrown when registering "resolve-macro-as" command

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1495]
It seems we may be registering it twice. See this comment for this error: https://github.com/BetterThanTomorrow/calva/issues/1482#issuecomment-1019459933.

**Comment by bpringe** [comment]
@ericdallo It seems that clojure-lsp now registers or causes the client to register the `resolve-macro-as` command, and also handles presenting the user with choices about how to resolve the macro, which Calva previously did itself. This now causes an exception to be thrown when Calva tries to register `resolve-macro-as` itself, and it also causes the current code to present the options to the user as Calva does it, then clojure-lsp presents options to the user (since that command now causes that).

It seems we probably can stop registering `resolve-macro-as` _and_ stop presenting the options to the user, and instead defer all of this to clojure-lsp. Is that correct?

**Comment by bpringe** [comment]
You can see the changes in the linked PR. @ericdallo Let me know what you think.

**Comment by ericdallo** [comment]
@bpringe correct, I think I found a issue with that recently and ended up changing to handle via code action / clojure-lsp side, sorry for not warning about that, calva should handle that as other refactor commands normally.
