### ISSUE TITLE
Output window gets stuck constantly appending to queue

### ISSUE THREAD

**Issue by stefan-toubia** [BetterThanTomorrow/calva#1509]
I've identified a long running issue where the output window gets into a bad state and no longer updates with new output. What I found is that the current logic which uses an `isUpdating` flag encounters some edge condition that causes `isUpdating` to never get cleared, causing the queue to grow indefinitely and require a vscode restart.

**Comment by PEZ** [comment]
I think I encountered that the other day. It was too strange for me to make any sense of that single time.

**Comment by bpringe** [comment]
@stefan-toubia Can you reproduce this consistently? If so, can you provide a repro case? I haven't experienced this, that I know of, but a repro case would help with testing the PR.

**Comment by stefan-toubia** [comment]
@bpringe I have not been able to reproduce this consistently, though it's at least a daily occurrence for me. The only reason I was able to identify the cause was by launching calva with the debugger turned on and getting lucky with break points.

I haven't seen a specific pattern. Sometimes it gets into a bad state nearly immediately after starting vscode, before ever starting a repl. Most of the time though it's after a few hours of working with a repl and then trying to restart the repl with jack-in.

**Comment by bpringe** [comment]
Seems this wasn't linked properly to be closed when the changes were merged to `published`.
