### ISSUE TITLE
[2.0] More Explicit Control of Jacked-in repl

### ISSUE THREAD

**Issue by Gnurdle** [BetterThanTomorrow/calva#151]
When Jackin-in fails (aka a post-merge compile surprise), need explicit control of retrying the jack-in.

Similarly would like to have explicit control of killing and/ or restarting a jacked in repl.

In cider we did this by tracking down and killing buffers, which isn't quite straightforward.

**Comment by PEZ** [comment]
If you think that managing this using VS Code's task manager is explicit enough you can close this issue. :smile:

**Comment by Gnurdle** [comment]
this, and having a jack-in kill old processes is sufficient
