### ISSUE TITLE
LSP loading is unreliable with multiple VS Code windows

### ISSUE THREAD

**Issue by TuggyNE** [BetterThanTomorrow/calva#1513]
I habitually maintain as many as half a dozen VS Code windows with different Clojure projects (several of which usually have REPLs running). As of 2.0.237, restarting VS Code (after restarting macOS, or just manually) consistently fails to load the LSP in several of those windows, requiring manually closing, then reopening each window that didn't load correctly. Opening windows one at a time does not show this problem.

I think I've seen similar race conditions before, but not so severe.

**Comment by bpringe** [comment]
Thanks for reporting. So, you're saying that when restarting VS Code, those several windows you had open are reopened at once, and clojure-lsp fails to start for several of those projects (windows)?

If you use a version before 2.0.237, does this issue occur?

CC @ericdallo

**Comment by TuggyNE** [comment]
It's happened occasionally after VS Code updates in the past, but only transiently: a single extra restart would always fix the problem. In this case, I downgraded to 2.0.235, which was successful (with only a reload necessary) but at some point VS Code re-updated the extension. Somehow or other that (or the unrelated homebrew and npm maintenance) appears to have cleared out the problem, with seven windows loading simultaneously and no LSP errors in any of them on two successive restarts. I'll keep you updated if this recurs. ([This reminds me of the three most terrifying words.](http://thecodelesscode.com/case/225))

**Comment by bpringe** [comment]
Interesting site ^. I hadn't seen it before.

**Comment by bpringe** [comment]
>  with seven windows loading simultaneously and no LSP errors in any of them on two successive restarts.

Just curious, how are you loading windows simultaneously? I'm also unsure of what you mean by restarts in the above context.

**Comment by TuggyNE** [comment]
I have VS Code set to remember previous windows when it starts up (`window.restoreWindows = "all"`), so Cmd-Q, then launching it again once all windows close is one way to do it; restarting after VS Code updates is another, as well as launching after restarting the OS. I expect the race condition would never show up any other way.
