### ISSUE TITLE
TypeError when "Run Tests for Current Namespace" in non "-test" namespace 

### ISSUE THREAD

**Issue by arcesino** [BetterThanTomorrow/calva#1516]
I got error:
```
TypeError: Cannot read property 'test' of undefined
```
when trying to **"Run Tests for Current Namespace"** in a non `-test` namespaces. [This command's official docs](https://calva.io/test-runner/#test-commands) state that:

> Runs the tests for the current namespace. If not a -test namespace, tests for the current namespace plus its corresponding <current-namespace>-test namespace will be run.

so it seems that non `-test` namespaces are indeed supported so I would expect the command worked instead of giving an error, especially if individual tests can be run using command **"Run Current Test"**.

For instance, in the attached image you can see 2 test files `core-test.clj` & `test-core.clj` and the output in REPL for each file  when first each test is run individually using **"Run Current Test"** and then all tests in namespace are run using **"Run Tests for Current Namespace"**. As you can see, everything works fine for `core-test` namespace but we got the error in this issue when running "Run Tests for Current Namespace" in namespace `test-core`.

I understand that the convention is to write tests inside `-test` namespaces but based on the official docs and the fact that the tests in the namespace can be successfully run by evaluating `(clojure.test/run-tests 'example.test-core)` in the REPL,  I do believe this is an issue.

![Screen Shot 2022-02-03 at 13 37 50](https://user-images.githubusercontent.com/847819/152419272-a3ada9ca-a443-4817-8607-9463b8ab7d87.png)

**Comment by aturok** [comment]
Also faced this today.
That worked smoothly before, apparently got broken between v2.0.226 (works) and  v2.0.227 (doesn't). 
Unfortunately my understanding of the inner workings of calva is not good enough to pinpoint the problem.

**Comment by bpringe** [comment]
I can reproduce this. @marcomorain An exception seems to be thrown here: https://github.com/BetterThanTomorrow/calva/blob/05bf0428f2a4e11e93d7e85bdea6910766a05626/src/testRunner.ts#L104. Would you mind looking into this?

**Comment by bpringe** [comment]
These changes related to the test runner were included in 2.0.227: https://github.com/BetterThanTomorrow/calva/pull/1405. I'm not sure if something in that PR is causing this but it seems to be the only change in that version directly related to the test runner.

**Comment by bpringe** [comment]
I sort of see what's happening. When the command to run tests for a namespace is executed, if the current namespace does not end in `-test` it seems another namespace is set to have tests run for it that is the current namespace with `-test` appended to it.

In the below case, I ran the command in the `test-core` namespace. So then Calva tries to run tests for `test-core` and `test-core-test`. The latter namespace does not exist, but tests are attempted to be run for it and reported. During the reporting is where the error occurs, at this line: https://github.com/BetterThanTomorrow/calva/blob/05bf0428f2a4e11e93d7e85bdea6910766a05626/src/nrepl/cider.ts#L116

You can see in the below screenshots that one of the `results` is an nrepl response with a `namespace-not-found` status, which I think leads to one of the `summaries` in `totalSummary` being undefined.

![image](https://user-images.githubusercontent.com/12722744/152631123-166347f5-b7e3-403e-af54-eefc317cbc7b.png)

![image](https://user-images.githubusercontent.com/12722744/152631177-4885c1e7-e8c6-484f-887f-a1f2ff801170.png)
