### ISSUE TITLE
[2.0] Font size if visibly bigger in the [new REPL window]

### ISSUE THREAD

**Issue by dabrazhe** [BetterThanTomorrow/calva#152]
See the image below. If you decrease font it also affects the code editor window, making it too small.

![image](https://user-images.githubusercontent.com/24795958/55683740-8759c900-5943-11e9-8189-1fb4d4389da4.png)

**Comment by PEZ** [comment]
Yes, there is currently a bug in vscode that prevents us from using the same font size as the editors. But I saw that the bug is being fixed, so hopefully, we can get rid of this problem soon.

**Comment by ncharchut** [comment]
Has this been resolved?

**Comment by PEZ** [comment]
No. This is a tricky one.

**Comment by ITSecMedia** [comment]
Any updates on this nasty bug?

**Comment by PEZ** [comment]
Actually, I spoke to some VS Code dev guys the other day, and they said they have provided what is needed to fix this. I haven't had the time to look at it yet, though. But there's hope!

**Comment by PEZ** [comment]
Turns out there isn't a nice way to do this: https://github.com/microsoft/vscode/issues/86722

But I've sort of hacked my way around it now. Next release!

**Comment by liftM** [comment]
On 2.0.68, I'm seeing some strange UI behaviour where my REPL is now in what looks like the default sans-serif font rather than my monospace editor font. Any idea how I can start debugging this?

**Comment by PEZ** [comment]
Indeed. I found where I had messed up and have fixed that in 2.0.69.
