### ISSUE TITLE
clojure lsp can not start

### ISSUE THREAD

**Issue by paomian** [BetterThanTomorrow/calva#1521]
got this error
```
Launching server using command /Users/paomian/.vscode/extensions/betterthantomorrow.calva-2.0.240/clojure-lsp failed.
```

in path `/Users/paomian/.vscode/extensions/betterthantomorrow.calva-2.0.240/` i not found `clojure-lsp` file.
reinstall calva is not working.

calva version: v2.0.240

java version:
```
java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

vscode version:
```
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:20:17.224Z (3 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

**Comment by bpringe** [comment]
When Calva starts, the status bar will show that clojure-lsp is downloading, and then that it's initializing. When you reload the VS Code window, does the status bar indicator get stuck during the clojure-lsp download or initialization phase?

**Comment by paomian** [comment]
I don't know why.It is work today. Yesterday it is no download action before start clojure-lsp.but today i found clojure-lsp file in extensions path.

**Comment by bpringe** [comment]
If you happen to have trouble again in the future, please let us know.
