### ISSUE TITLE
TS + ESLint upgrades

### ISSUE THREAD

**Issue by corasaurus-hex** [BetterThanTomorrow/calva#1525]
I'd like to upgrade typescript + eslint to be the latest and update the configuration for the latest. While initially I'd try to get it set up such that changes to existing code aren't required (or are minimal), I'd later like to introduce new eslint rules that improve the types across the app to prevent unexpected behaviors and add code clarity.

Sound good?

**Comment by corasaurus-hex** [comment]
Just for reference, the current typescript version in the package.json was released two years ago. The changes between 3.7 and 4.5 (the current) are huuuuuuuuuge. The typescript site helpfully [lists the major differences](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) in an easy to read way.

**Comment by PEZ** [comment]
I'll be happy to follow your advice here, @corasaurus-hex . This used to be a all JavaScript and we haven't really fully transitioned into TypeScript.

I'd like to hear what @bpringe says about it. And as I've noted how TS-y @marcomorain's contributions are, it would be good to get input from him as well. 

Anyway, we're not on this ancient TS version on purpose. 🤠

**Comment by corasaurus-hex** [comment]
I'd love to hear their thoughts on it! I usually like to go with [airbnb's](https://github.com/iamturns/eslint-config-airbnb-typescript) eslint config with some minor tweaks.

**Comment by PEZ** [comment]
Related to #1524. I'd like to enforce curly brackets always, even on one-liners. Iiuc, this is something for ESLint, rather than for Prettier, so putting it here. I'd like it to work with auto-formatting and format-on-save and such, though, like the Prettier extension does. Is that possible with ESLint?

**Comment by corasaurus-hex** [comment]
Do you mean like this? https://eslint.org/docs/rules/curly

ESLint and Prettier can work well with each other they just need to be aware of each other via a plugin https://github.com/prettier/eslint-config-prettier

There's also this rule https://eslint.org/docs/rules/arrow-body-style -- there are quite a few to meet most of what you want done stylistically.

**Comment by corasaurus-hex** [comment]
Also, expanding on what you said about ESLint vs Prettier, you're mostly right. ESLint can fix some rule violations (using `eslint --fix`) like Prettier does formatting but generally you want to use Prettier to format instead and make sure their rules are aligned.

**Comment by PEZ** [comment]
> Do you mean like this? https://eslint.org/docs/rules/curly

Yes! Especially with  the `"all"` option mentioned there.

**Comment by corasaurus-hex** [comment]
That's absolutely something we can do! I'll try to do it this weekend. I'd love to keep the next PR to a minimum size however fixing issues that violate the Coding Style in the wiki will probably involve a fair bit of changes.

**Comment by corasaurus-hex** [comment]
They're mostly not functional changes, though. Things like using const vs let where the compiler is positive the variable is never assigned again, or avoiding variable shadowing, that sort of stuff that is harmless to fix.

**Comment by PEZ** [comment]
Ah, good that you mention const vs let. I'd love it if we could enforce that.

I'm mainly curious about what we can achieve. Totally agree that it is good to keep PRs focused!

**Comment by bpringe** [comment]
Sorry I'm late to this discussion, but I'm loving where all this is going! I like using the Airbnb config as a base as well.

**Comment by corasaurus-hex** [comment]
I'm going to turn on all the recommended typescript rules and after that I'll bring in airbnb. Feels more incremental that way.
