### ISSUE TITLE
Map key/value pair aligning is not working on format

### ISSUE THREAD

**Issue by furkan3ayraktar** [BetterThanTomorrow/calva#1535]
Calva was able to align map key/value pairs when formatting the current file until the version 2.0.241. After that version, it stopped working. I can still align them by pressing `ctrl+alt+l` within each map, however, it is not working when the file is formatted by Calva.

`.cljfmt.edn`👇
```clojure
{:remove-surrounding-whitespace?  true
 :remove-trailing-whitespace?     true
 :remove-consecutive-blank-lines? false
 :insert-missing-whitespace?      true
 :align-associative?              true}
```

and the VSCode settings 👇
```json
{
  "editor.formatOnSave": true,
  "files.insertFinalNewline": true,
  "files.autoSave": "off",
  "files.eol": "\n",

  "calva.showDocstringInParameterHelp": true,
  "calva.paredit.defaultKeyMap": "strict",
  "calva.paredit.strictPreventUnmatchedClosingBracket": true,
  "calva.referencesCodeLens.enabled": false,
  "calva.fmt.configPath": ".cljfmt.edn",
  "calva.keybindingsEnabled": true,
  "calva.prettyPrintingOptions": {
    "enabled": false,
    "width": 120,
    "maxLength": 50,
    "printEngine": "pprint"
  },
}

**Comment by PEZ** [comment]
Please help testing this VSIX, containing a fix for this bug: https://18064-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.244-formatter-config-from-lsp-90442af0.vsix

**Comment by furkan3ayraktar** [comment]
Hi @PEZ, I've tested it with 2.0.244 and now it fixes the map alignment with `tab` but still it does not fix the alignments automatically when I save the file.

**Comment by PEZ** [comment]
Ah, thanks. I'll look at it.

**Comment by PEZ** [comment]
This VSIX should fix the file-on-save, @furkan3ayraktar https://18227-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.245-1556-format-on-save-74268175.vsix
