### ISSUE TITLE
Show def values in tooltip

### ISSUE THREAD

**Issue by Cyrik** [BetterThanTomorrow/calva#1538]
```clojure
(def a {:foo "bar"})
(def b (assoc a :newProp 2))
```

When writing code like that, it would be nice to hover over b and see the value it currently has. This will only work if connected to a repl and if that var is actually eval'd already, but better that's true a lot of the time.

I'd build this on top of #1471 just to also dogfood that feature.

What do you think @PEZ @bpringe?

**Comment by bpringe** [comment]
I think this would be awesome. So looking at https://github.com/BetterThanTomorrow/calva/pull/1492 I'm guessing we'd just use eval in a custom hover snippet, and we could also call pprint if we wanted?

Could there be any issue with really large values? Would we truncate them?

**Comment by bpringe** [comment]
So looking at #1492 I'm guessing we'd just use `eval` in a custom hover snippet, and we could also call `pprint` if we wanted?

**Comment by Cyrik** [comment]
Yeah you're exactly right, should be a tiny bit of code for a nice feature. Not using custom snippets would probably be more performant, but I think it's a good idea to use our own features. 

Big data would be a problem, yes. I'll have a look at how the repl display does truncating + we should probably use the configured pprint engine for consistency.

**Comment by PEZ** [comment]
We already show values in hover when evaluating, without caring about the size of the data.

**Comment by PEZ** [comment]
Maybe we should have a separate pretty printing setting for hovers? That way users are in better control of how much data is ever thrown into the hover.

**Comment by Cyrik** [comment]
I think we might want to do that at some point, but I think it makes sense to keep finding use-cases with the current bare-bones approach, so we know which options are needed and how they overlap. I feel like one of the problems with the evaluate.ts namespace is overlapping options.
But you gave me the idea to at least add a max length to each hover string so that we don't blow up vscode if there's a bug in one of the hovers. I think it should be pretty large since it's meant to prevent crashes, not be a setting. I'll play around with some values. What do you think @PEZ @bpringe?

**Comment by PEZ** [comment]
I was thinking thinking that we do have a use-case already with evaluation results. I once removed them completely because I was worried they impact performance for some users. Having a way to control it would help me sleep better.

Sure, it can start without it being a setting. Like we do in the lexical scanner: https://github.com/BetterThanTomorrow/calva/blob/dev/src/extension-test/unit/cursor-doc/paredit-test.ts#L7

Though different machines have different limitations so that speaks a bit for making it configurable.

**Comment by Cyrik** [comment]
@PEZ I just tried it. We don't actually need to set a limit since vscode already does it. It has a hard limit of about 100k chars per hover, which should save us from explosions. I'm not sure if this can be configured, but if it can it makes more sense for the user to use that setting.

**Comment by Cyrik** [comment]
Closed by #1582

**Comment by PEZ** [comment]
VS Code knows nothing about Clojure, so to me it makes sense that this is first handled by pretty printing settings.
