### ISSUE TITLE
"Resolve macro as..." code action produces unreadable text in pop up

### ISSUE THREAD

**Issue by hgranthorner** [BetterThanTomorrow/calva#1539]
When using the code action "Resolve macro <macro name> as...", the text on the buttons in the pop up in the bottom right hand side of the screen is cut off, making them basically unreadable. Luckily this can be worked around via mouseover tool tips (although they're a bit finicky), but making this pop up more readable would be a nice usability improvement.

Screenshot taken when calling the code action on `clojure.test.check.properties/for-all`.

Link to slack thread: 
https://clojurians.slack.com/archives/CBE668G4R/p1645027436974109

Screenshot:
![image](https://user-images.githubusercontent.com/37941012/154307389-79626dc5-f060-4eca-82d4-cc7842185a0c.png)

**Comment by PEZ** [comment]
@ericdallo is this something we can solve in Calva without any change in clojure-lsp, you think?

**Comment by ericdallo** [comment]
Yes, calva can handle `window/showDocumentRequest` differently, showing a different vscode popup instead of the default vscode-languageclient uses.

**Comment by PEZ** [comment]
It's a bit unclear to me how showDocumentRequest is related to this. It looks like in the default languageclient this is about showing documents rather than showing messages:

https://github.com/microsoft/vscode-languageserver-node/blob/f72faa0975cb2aaa85ce84da819944f84e1aac52/client/src/common/client.ts#L3422

**Comment by PEZ** [comment]
Maybe you mean showMessageRequest? https://github.com/microsoft/vscode-languageserver-node/blob/f72faa0975cb2aaa85ce84da819944f84e1aac52/client/src/common/client.ts#L3401

I think this is what clojure-lsp uses:

https://github.com/clojure-lsp/clojure-lsp/blob/1754cdfa6da3f72477ea09868f9d9ae159db0bda/lib/src/clojure_lsp/feature/resolve_macro.clj#L73

It seems reasonable that Calva shows a message on such a request, like the default client does, right?

**Comment by ericdallo** [comment]
Yes, sorry, I meant `showMessageRequest`

**Comment by ericdallo** [comment]
IMO, the default one that vscode uses has a bad UX for multiple options

**Comment by PEZ** [comment]
Agreed. I am more thinking that from the semantics of showMessage it seems like the right choice. Seems like the server should be able to show a menu. Not that I find such an option from a quick scan.

**Comment by ericdallo** [comment]
How can server show a menu? this should be done on client side right?
Changing Calva to show the menu just like REPL jack in sounds the best fix

**Comment by ericdallo** [comment]
This is how emacs show the menu:
![](https://clojure-lsp.io/images/features/resolve-macro-as.gif)

**Comment by PEZ** [comment]
Something like `window/showMenuRequest` springs to mind. 😄

**Comment by ericdallo** [comment]
I see your point, the method name sounds odd, yeah, agreed

**Comment by PEZ** [comment]
I checked with people in the know and there is simply no such command.

**Comment by PEZ** [comment]
So... that was a bit more work than I had anticipated. But now we have this VSIX you can test:

https://18213-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.245-massage-quick-picks-d3172aba.vsix 

Looks like so:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/30010/155331467-a0ad4fdd-a3c3-4e42-b530-12808d129040.png">

Followed by:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/30010/155331620-59fcae20-4a8c-4f03-9b41-5bfe94ca98b0.png">
