### ISSUE TITLE
[2.0] repl UI should be draggable to or creatable in another window

### ISSUE THREAD

**Issue by Gnurdle** [BetterThanTomorrow/calva#154]
If I create a new window, I want to either put the repl window in it, or be able to create a new one in it

**Comment by Gnurdle** [comment]
Actually, I'm pretty sure I can make a use case for more than one repl at a time, if nothing else, one clj one cljs working in tandem.

Another possible reason to want this might be different kinds of nrepl clients playing nice together.  Think "namespace browser", that knows how to drill into namespaces, and then atoms, and then data-structures.

**Comment by PEZ** [comment]
I am not sure what you mean with moving the repl window to a new window. Do you mean as with the vscode command *New Window*? I don't think it is even possible for us to support moving the repl window there then. But you can always do *Calva Connect* and create a new REPL window in that window. See also: https://github.com/Microsoft/vscode/issues/68831 (and please upvote if you like it.)

As for supporting making several repls. I agree that would be a great feature. I'd like a separate issue for it, even. :smile:

**Comment by PEZ** [comment]
Is this issue still relevant? (I'm in cleaning mode.)

**Comment by Gnurdle** [comment]
Closing because this likely isn't feasible to do in VS-code, and connect achieves same result
