### ISSUE TITLE
Print stacktrace link in REPL gets duplicated

### ISSUE THREAD

**Issue by jacobemcken** [BetterThanTomorrow/calva#1542]
How to reproduce:

1. Create empty Clojure project `lein new calvabug`
2. Open VS Code and start REPL: *Calva: Start a Project REPL and Connect*
3. Trigger any exception e.g. with `(/ 4 0)`
4. Close the REPL buffer by clicking the little x or pressing <kbd>Ctrl+w</kbd>
5. Start REPL again: *Calva: Start a Project REPL and Connect*
6. Trigger exception again

Expected behavior:
Show *"Print stacktrace"* a single time.

What actually happens:
The *"Print stacktrace"* is shown as many times as the REPL was (re-)started.

![multiple print stacktrace](https://user-images.githubusercontent.com/1869708/154793169-a82a9f5f-2331-4a7b-8216-db8666672c2a.png)

**Comment by PEZ** [comment]
I have been wondering about this. I vaguely remember someone speculating that it was about REPL restarts. Should be easy to fix if this is what it is about.
