### ISSUE TITLE
Gold Syntax highlighting not showing on code. 

### ISSUE THREAD

**Issue by LeonRomo** [BetterThanTomorrow/calva#1546]
Gold syntax highlighting not showing in code, especially in functions. 

See the screenshot below.

- ![Screenshot from 2022-02-16 08-50-13](https://user-images.githubusercontent.com/48680199/154798826-8ab7ac8d-a37e-4956-879a-53965ab8279e.png)

**Comment by PEZ** [comment]
Hello.

This is probably something missing with your project configuration. Try using `clj-kondo` from the command line and see if you get the warnings you expect there.

Also, the error report is very unclear to me. I have no clue what you expect to happen. Please provide this information.

**Comment by bpringe** [comment]
@PEZ I think they are actually referring to syntax highlighting. Notice in the image, functions are not colored yellow. Any idea what could be going on?

@LeonRomo What theme are you using? Maybe the theme you're using just doesn't color functions yellow. You can change your theme using the VS Code command palette. I use "Dark+ (default dark)" and it colors functions yellow.

**Comment by PEZ** [comment]
Ah, yes, highlighting.

**Comment by LeonRomo** [comment]
@bpringe @PEZ  the colour theme change to "Dark+ (default dark)" did the trick. The gold highlights are seen. Thanks.

**Comment by PEZ** [comment]
Thanks for updating about the solution, @LeonRomo!
