### ISSUE TITLE
Make alt+enter evaluate top level form also within line-comments

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1549]
Using `alt+enter` when the cursors is in a line comment currently performs comment continuation. This is by my design, but at least for me, a bad design. ...

**Comment by PEZ** [comment]
Is it a Github bug that this issue is not closed by the merged PR linking it? WDYT, @bpringe ?

**Comment by bpringe** [comment]
I'm not sure... the note in the linked issues section says:

> Successfully merging this pull request _may_ close these issues.

Emphasis by me. I'd have to look more into it to know if that's a bug.

**Comment by PEZ** [comment]
I'm thinking ”may” is because the issue might be already closed. Anyway, I posted about this on their community forum: https://github.community/t/issues-which-a-linked-pr-is-supposed-to-close-does-not-close/230879
