### ISSUE TITLE
Metadata is not passed on form evaluation

### ISSUE THREAD

**Issue by daslu** [BetterThanTomorrow/calva#1551]
Just noticed a little gap between CIDER and Calva.
If we have the following code:
```clj
^:abcd [1]
```
(that is, a vector with a number in it, with some metadata before it), and we put the cursor after this piece of code,
then `cider-eval-last-sexp` would pass the code `^:abcd [1]` to nREPL,
while `Calva: Evaluate Current Form` would pass only `[1]`.

**Comment by PEZ** [comment]
Thanks. I agree with CIDER about this. We treat reader tags as part of the form they tag, and this is very similar.

What do we say about ignores? They are reader tags, but treated a bit differently (not part of the form they ignore out) by Calva, to make it convenient to evaluate an ignored form. What does CIDER do here?

**Comment by PEZ** [comment]
Here's a VSIX fixing most of this issue: https://18486-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.247-1551-current-form-metadata-58199575.vsix

Please put it to some tests. See #1566 about what to expect.
