### ISSUE TITLE
Warning when loading a file produces an error: n.filter is not a function

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1567]
To reproduce, while connected to a repl, put a symbol at the top level of the file that's not defined (like `a`, assuming that is not defined) and load the file. See the warning:

![image](https://user-images.githubusercontent.com/12722744/156256895-12493014-9339-443d-b986-934dc606a2ed.png)

**Comment by PEZ** [comment]
Boo!
