### ISSUE TITLE
Typo in https://calva.io/get-started-with-clojure/ 

### ISSUE THREAD

**Issue by oscaretu** [BetterThanTomorrow/calva#1570]
In https://calva.io/get-started-with-clojure/  you can find a typo (ClojureScipt => ClojureScript):

The basics of the [ClojureScipt](https://clojurescript.org/) language (we won't be using ClojureScript, but it is same language 😀)

![imagen](https://user-images.githubusercontent.com/2979926/156511653-0b4c61bf-8b66-463a-bf5a-08b2ac1b98e3.png)

**Comment by PEZ** [comment]
Thanks for reporting!
