### ISSUE TITLE
user.clj not loaded on jack-in if in extra-path defined in alias

### ISSUE THREAD

**Issue by willmruzek** [BetterThanTomorrow/calva#1574]
I have a very simple `deps.edn` project and a `dev/user.clj` file with a `:dev` profile including `dev` into the classpath.

However, when I start a REPL via "Calva: Start a Project REPL and Connect (aka Jack-In)", `dev/user.clj` fails to load automatically.

But when I run the command used to launch it and connect a REPL manually, it does.

```
clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.9.0"},cider/cider-nrepl {:mvn/version,"0.27.4"}}}' -M:dev -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"]"
```

Is there any way to get `dev/user.clj` to load automatically with Jack-In?

Thanks for this extension and your help!

## Files

**deps.edn**
```
{:paths ["src" "resources"]
 :deps {org.clojure/clojure {:mvn/version "1.10.3"}
        ring/ring           {:mvn/version "1.8.0"}
        ring/ring-defaults   {:mvn/version "0.3.2"}
        compojure/compojure {:mvn/version "1.6.2"}}

 :aliases
 {:run-server {:main-opts ["-m" "myusername.mynewapp.core"]}
  :dev {:extra-paths ["dev"]}}}
```

**dev/user.clj**
```
(ns user)

(println "Message from user namespace")

(defn say-hello []
  (println "Hello"))
```

**Comment by PEZ** [comment]
Hi!

Iiuc, you can use a [custom connect sequence](https://calva.io/connect-sequences/) for this and configure `afterCLJReplJackInCode `to load the file.

**Comment by bpringe** [comment]
@PEZ Any idea why the file would not be loaded with jack-in, but using the same jack-in command manually and connecting to that repl causes the file to be loaded?

**Comment by PEZ** [comment]
I somehow missed that detail. No idea why it would load automatically in that scenario. That is very strange.

**Comment by willmruzek** [comment]
From what I understand, it's the default to load user.clj if it's in the classpath, but for some reason that's not the case with Calva's Jack-In.

**Comment by PEZ** [comment]
I really don't undertand why it behaves differently with jack-in. Seems like there must be a bug in Calva. Should be investigated.

**Comment by willmruzek** [comment]
Just further info, it does work if I put user.clj in my src folder. But I think it should be loaded anywhere on the classpath.

**Comment by bpringe** [comment]
@mruzekw Just to be sure, when you jack-in, you are making sure the dev alias is checked in the menu that pops open, right?

**Comment by bpringe** [comment]
@mruzekw When I jack-in and select the dev alias, the `user.clj` is loaded. I see this in my terminal:

```sh
clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.9.0"},cider/cider-nrepl {:mvn/version,"0.27.4"}}}' -M:dev -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
Message from user namespace
nREPL server started on port 50398 on host localhost - nrepl://localhost:50398
```

**Comment by PEZ** [comment]
> Just further info, it does work if I put user.clj in my src folder. But I think it should be loaded anywhere on the classpath.

I agree. Thing is Calva doesn't really do anything with loading files. All I could think of was if we somehow interrupt something that tools-deps is doing when it starts the project. But if it loads with `user.clj` in the `src` folder, I don't think the interrupt is happening either. I'm totally clueless.

Oh, now see that @bpringe has it working also with the alias. Hmmm. what on earth could be going on here?

**Comment by willmruzek** [comment]
> @mruzekw Just to be sure, when you jack-in, you are making sure the dev alias is checked in the menu that pops open, right?

Yes. I am checking the `:dev` alias box.

> @mruzekw When I jack-in and select the dev alias, the user.clj is loaded.

Interesting. I forgot to mention that I'm using VSCode's Remote-Container plugin to run a Clojure dev env in a container. After tinkering around, I found that Calva was looking for the clojure-lsp binary in the container. I installed clojure-lsp manually, told Calva where it is, and it connects. 

Jacking-in on the host machine (with nix-shell), `dev/user.clj` is loaded with `:dev`.

So I guess it could very well have something to do with developing in a container? Does that help diagnose what might be the issue?

**Comment by PEZ** [comment]
When you run the command to connect, do you do it from a VS Code terminal or a terminal outside VS Code. I'm thinking it could be something lacking with the environment that VS Code runs in.

**Comment by willmruzek** [comment]
I do it through the regular VSCode command prompt that shows at the top. Cmd + Shift + P on Mac.

**Comment by PEZ** [comment]
Sorry, I was a bit undlear. I meant this:

> But when I run the command used to launch it and connect a REPL manually, it does.
> 
>    clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.9.0"},cider/cider-nrepl {:mvn/version,"0.27.4"}}}' -M:dev -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"]"

**Comment by willmruzek** [comment]
No worries.

I ran it in a terminal within VSCode (with a nix environment applied, trying to keep my machine clear of global deps).

**Comment by PEZ** [comment]
How did you apply the nix environment?

**Comment by willmruzek** [comment]
shell.nix + using the Nix Environment Selector (arrterian.nix-env-selector) + Command: Nix-Env: Select environment

```
{ pkgs ? import (fetchTarball "http://nixos.org/channels/nixos-21.11/nixexprs.tar.xz") {} }:

pkgs.mkShell {
  buildInputs = [
    pkgs.clojure
  ];
}
```

Though, this set up works. 👍

**Comment by PEZ** [comment]
So maybe it is this that is not happening in the Jack-in process. I'm not sure, but it might be that we only have access to the environment that VS Code had when it started.

**Comment by willmruzek** [comment]
I can't really explain it, but I've gotten this to work. `dev/user.clj` loads consistently on Jack-In. We can probably close this now.

The working setup matches what I put [here](https://github.com/PEZ/pirate-lang/issues/2#issuecomment-1068090433).

**Comment by PEZ** [comment]
Thanks!
