### ISSUE TITLE
Metadata affects the Current Form being recognized

### ISSUE THREAD

**Issue by daslu** [BetterThanTomorrow/calva#1577]
Tested with the current version (`v2.0.250`), we get the following behaviour.
```clj
(+ 1 2)

^:abcd/efgh
[:hello]
```

If we put the cursor between the two forms, Calva: `Evaluate Current Form` would evaluate the second form.
If we remove the metadata, it would evaluate the first form.

**Comment by PEZ** [comment]
Fixed in this build: https://18821-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.251-1577-current-form-metadata-5-2ee67986.vsix
