### ISSUE TITLE
Calva ignores auto closing settings.

### ISSUE THREAD

**Issue by Tillaert** [BetterThanTomorrow/calva#1583]
With the settings:

```
{
    "editor.autoClosingBrackets": "never",
    "editor.autoClosingDelete": "never",
    "editor.autoClosingOvertype": "never",
    "editor.autoClosingQuotes": "never" 
 }
 ```
 
 Calva still inserts autoclosing brackets, etc.

**Comment by bpringe** [comment]
Are you setting those at the top level of your settings? Calva sets a couple of those settings to `"always"`, specifically for the `clojure` langauge,  which I think would override those top-level settings. See here: https://calva.io/customizing/#clojure-defaults.

@PEZ Is there another way to stop Calva from auto-closing brackets, etc. (not that I'd recommend that), besides changing those settings for the `clojure` language? I see this in the docs:

> Some of these are needed for Calva to function correctly, which should not be tampered with unless you really know what you are doing, and some of them are convenient defaults.

**Comment by PEZ** [comment]
I think that is the only way to change it.

Closing this, since I think you have your answer there, @Tillaert? If not, please re-open.

**Comment by Tillaert** [comment]
@PEZ Well, yes and no. My problem is that I am a touch typist who learned to type on a mechanical typewriter. This makes it hard for me to work with tools which add things I didn't type (ie. adding closing symbols). As far as I can see, there is no accesibility option in Calva to disable paredit?

**Comment by PEZ** [comment]
@Tillaert It is not Paredit adding the closing paren. It is VS Code. Disable it in settings. See https://calva.io/customizing/#clojure-defaults
