### ISSUE TITLE
Add commands and UI for controlling the clojure-lsp process

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1592]
It takes a reload of the VS Code window to restart clojure-lsp after having changed version of formatting config or whatever. This can be quite expensive, killing the REPL for instance.

The solution probably is to let the user start and stop clojure-lsp at will. Then we can also add the option to run without clojure-lsp for projects where it consume to much resources.

There is also sometimes troubles with the clojure-lsp download going wrong and then causing problems. So a command for forcefully re-download would be nice as well.

**Comment by riotrah** [comment]
Is this not complete? @PEZ

**Comment by PEZ** [comment]
It is. Could be closed.
