### ISSUE TITLE
Calva downloads the wrong clojure-lsp when running in devcontainer

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1598]
On my M1 Mac when VS Code is running in a [devcontainer](https://code.visualstudio.com/docs/remote/create-dev-container), downloading clojure-lsp, downloads `clojure-lsp-native-linux-amd64.zip`. Which then can't be started.

I am not completely sure how it is supposed to work, or which version should be downloaded. But anyway, this doesn't work.

I notice this when working on https://github.com/PEZ/pirate-lang/issues/2

**Comment by bpringe** [comment]
I haven't tried dev containers, so I'm not sure how it's supposed to work. It seems that currently Calva is trying to start clojure-lsp on the host machine, instead of inside the container. We need to find out where clojure-lsp _should_ be run in this case, first.

**Comment by PEZ** [comment]
I'm pretty sure it should run in the container. Everything should run there. What makes you think it runs it in the host?

**Comment by PEZ** [comment]
I'm pretty sure it should run in the container. Everything should run there. What makes you think it runs it in the host?

**Comment by bpringe** [comment]
Oh, it's early here, I guess there's no indication it's being run on the host 😄 . For some reason I guess I thought that it was implied that the reason it wasn't working is that it's for linux, but trying to be run on macos.

**Comment by bpringe** [comment]
But yes, I think it should be run in the container, without having looked into dev containers. That seems the logical place for it to run. Is there any startup error?

**Comment by PEZ** [comment]
That would explain it the issue. But `process.platform`  returns `linux`, which is why that binary is downloaded. So why would the lsp client be executed on the host...

**Comment by bpringe** [comment]
Yeah, I'm not sure if that's what's happening or not at this point.

**Comment by PEZ** [comment]
This is what I see in *Clojure Langyage Client* output:

```
[Trace - 3:55:25 PM] Sending request 'initialize - (0)'.
[Error - 3:55:25 PM] Connection to server is erroring. Shutting down server.
[Trace - 3:55:25 PM] Sending request 'shutdown - (1)'.
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

**Comment by PEZ** [comment]
In the dev console of the containerized VS Code:

```
[Extension Host] Starting clojure-lsp at /home/vscode/.vscode-server/extensions/betterthantomorrow.calva-2.0.254/clojure-lsp
log.ts:313   ERR [Extension Host] Error: Unexpected SIGPIPE
	at process.<anonymous> (/vscode/vscode-server/bin/linux-arm64/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/out/bootstrap.js:1:370)
	at process.emit (events.js:315:20)
```

**Comment by Cyrik** [comment]
It seems that just starting clojure-lsp already explodes. Have you tried to ssh into the container and run lsp manually, just to see if it even works?
oh and setting `:log-path` to somewhere you can find in .lsp/config.edn might also produce something interesting

**Comment by PEZ** [comment]
```sh
root ➜ .../vscode/.vscode-server/extensions/betterthantomorrow.calva-2.0.254 $ ./clojure-lsp --version
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```

These are the clojure-lsp files there:

```
-rwxr-xr-x 1 vscode vscode 28397944 Mar 16 15:19 clojure-lsp
-rwxr-xr-x 1 vscode vscode 28397944 Mar 16 15:02 clojure-lsp_backup
-rw-r--r-- 1 vscode vscode 25659578 Mar 16 15:19 clojure-lsp-native-linux-amd64.zip
-rw-r--r-- 1 vscode vscode       19 Mar 16 15:19 clojure-lsp-version
```

I think the problem might be linux on an M1:

```sh
root ➜ .../vscode/.vscode-server/extensions/betterthantomorrow.calva-2.0.254 $ uname -s
Linux
root ➜ .../vscode/.vscode-server/extensions/betterthantomorrow.calva-2.0.254 $ uname -m
aarch64
```

**Comment by PEZ** [comment]
Right now I feel like a complete vscode noob. After having exprimented with devcontainers, now when I open a new blank VS Code window the status bar is purple, and when I run the Getting Started REPL, clojure-lsp fails to start.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/30010/158652862-342591ac-561b-46c9-a389-60ebdc7cf99a.png">

 It starts fine when opening up a folder with Clojure stuff in it (and then the statusbar is it's regular blue color).

**Comment by PEZ** [comment]
To convince myself that we shouldn't be downloading the mac version I did that in the devcontainer and this happens when I try to run it:

```sh
$ ./clojure-lsp --version
bash: ./clojure-lsp: cannot execute binary file: Exec format error
```

**Comment by Cyrik** [comment]
I wanted to say that you probably have the wrong version, but I'm not a Graal VM expert. Have you tried starting the jvm? https://mkyong.com/java/bash-usr-bin-java-cannot-execute-binary-file-exec-format-error/

**Comment by willmruzek** [comment]
clojure-lsp should run in the container. I have a running setup [here](https://github.com/PEZ/pirate-lang/issues/2#issuecomment-1068090433).

Note you will need both `.devcontainer/devcontainer.json` and `.devcontainer/Dockerfile` for it to work.

This is also on my M1 Mac, but the Dockerfile does download the correct clojure-lsp for arm64.

The key is this setting:

```
{
	"settings": {
                 // ...
		"calva.clojureLspPath": "/usr/local/bin/clojure-lsp",
	},
}

**Comment by mathieuroblin** [comment]
I think I am encountering the same issue on a different setup, maybe it can help troubleshoot. This is very similar to https://github.com/BetterThanTomorrow/calva/issues/1598#issuecomment-1069367672

On my side I am not using a .devcontainer but a direct ssh connection (using ms-vscode-remote.remote-ssh). I am also on a M1 Mac but I am running ubuntu via multipass. Then I let vscode connect and install the vscode-server on the ubuntu instance.

I am getting the following error in the Output:
```
[Error - 3:43:13 PM] Connection to server is erroring. Shutting down server.
[Trace - 3:43:13 PM] Sending request 'shutdown - (1)'.
/home/ubuntu/.vscode-server/extensions/betterthantomorrow.calva-2.0.254/clojure-lsp: 1: cannot create �D�@@8@=N�=N�P�P��Q�td�:_�UPX!h	
<�<����� �ELF>@�k)�o��@/�4�&8
rhk�Oh�fc�o�/[2!�n6)�n}jW��o�.�֖�u�ho�@Զ�
dx��o�&n���ֹvg'xlO0roȶ<���@rr!7�@�Ʉ��D����P�tdP�4Olp��oQN���R/V�9�T��zk�21o���/lib64: Directory nonexistent
/home/ubuntu/.vscode-server/extensions/betterthantomorrow.calva-2.0.254/clojure-lsp: 1: ELF: not found
/home/ubuntu/.vscode-server/extensions/betterthantomorrow.calva-2.0.254/clojure-lsp: 1: Syntax error: word unexpected (expecting ")")
```

I went to check the binary under the path `~/.vscode-server/extensions/betterthantomorrow.calva-2.0.254`
```sh
-rw-rw-r-- 1 ubuntu ubuntu    66472 Mar 16 22:16 CHANGELOG.md
-rw-r--r-- 1 ubuntu ubuntu     1162 Mar 16 22:16 LICENSE.txt
-rw-rw-r-- 1 ubuntu ubuntu    14542 Mar 16 22:16 README.md
drwxrwxr-x 6 ubuntu ubuntu     4096 Mar 16 22:16 assets
drwxrwxr-x 2 ubuntu ubuntu     4096 Mar 16 22:16 bundled
-rwxr-xr-x 1 ubuntu ubuntu 28397944 Mar 16 22:16 clojure-lsp
-rw-rw-r-- 1 ubuntu ubuntu 25659578 Mar 16 22:16 clojure-lsp-native-linux-amd64.zip
-rw-rw-r-- 1 ubuntu ubuntu       19 Mar 16 22:16 clojure-lsp-version
-rw-r--r-- 1 ubuntu ubuntu    10282 Mar 16 22:16 clojure.tmLanguage.json
-rw-r--r-- 1 ubuntu ubuntu  4679415 Mar 16 22:16 deps.clj.jar
-rw-r--r-- 1 ubuntu ubuntu      401 Mar 16 22:16 language-configuration.json
drwxrwxr-x 3 ubuntu ubuntu     4096 Mar 16 22:16 out
-rw-r--r-- 1 ubuntu ubuntu    91461 Mar 17 15:36 package.json
```

I am not very familiar with virtualisation and M1 so take the following with a pinch of salt.
The zip does mention a linux amd64 binary `clojure-lsp-native-linux-amd64.zip` but when trying to start it manually I am getting:
```shell
bash: ./clojure-lsp: cannot execute binary file: Exec format error
```

Running:
```sh
uname -m # => aarch64
```

I would assume in my case (and I think docker also default to arm images if not specified otherwise), only a aarch64 binary would work?

**Comment by PEZ** [comment]
@mruzekw I'll try with downloading that one manually and see what happens. I saw the the trick with the settings in your config, but i can't use it because that will not keep clojure-lsp updated.

**Comment by PEZ** [comment]
@mathieuroblin, thanks for the input!

> I would assume in my case (and I think docker also default to arm images if not specified otherwise), only a aarch64 binary would work?

I am starting to think that yes, that is what we would need both of us. We'll see. @ericdallo is also thinking a bit around this issue now.

**Comment by PEZ** [comment]
Worst case will be that we can detect the situation and fall back on using the jar. That should always work, I think.

**Comment by mathieuroblin** [comment]
@PEZ Multipass only supports the same architecture as the host so no way to have amd64 for this setup.

That said I went and installed the clojure-lsp directly using their script at https://clojure-lsp.io/installation/#script and setting my vscode config to `"calva.clojureLspPath": "/usr/local/bin/clojure-lsp"` and all is working perfectly fine. I'm not sure how calva and the lsp sync up their version so maybe their will be an issue later on, but at least it confirms that the lsp can work fine on aarch64.

Looking at the installation scripts it seems that running the script directly on MacOS with a M1 chip would download the amd64 version and have it run with Rosetta.

```sh
case "$(uname -m)" in
    aarch64) arch=aarch64;;
    *)       arch=amd64;;
esac
```

as running the following on MacOS directly gives:
```sh
uname -m # => arm64
```

**Comment by PEZ** [comment]
@mathieuroblin Thanks! I have been looking at that script and read that wrong.

It is also a bit confusing that inside a VS Code terminal, on my M1:

```sh
$ uname -m
x86_64
```

(Without any containerisation going on.)

**Comment by mathieuroblin** [comment]
@PEZ I don't know what's the status of VSCode with M1 so I am purely speculating...

I got my mac a weekish ago, would it make sense that because I installed VSCode recently I have a native M1 version, and you installed yours a while ago which would in fact be an amd64 version running through Rosetta? The `uname` you see through vscode's terminal would actually be the result of Rosetta's emulation?

**Comment by PEZ** [comment]
@mathieuroblin It's very possible. I have transferred my complete MacOS installation from my old c86_64 machine... I'll try to install a fresh VS Code insiders and see what I get there. Thanks!

**Comment by PEZ** [comment]
There are tons of cases and combinations here... I am starting to wonder if we should just default to using the jar version all the time.

**Comment by ericdallo** [comment]
> There are tons of cases and combinations here... I am starting to wonder if we should just default to using the jar version all the time.

The jar is way slower than graalvm compiled, IMO that should be avoided

**Comment by ericdallo** [comment]
Feel free to improve clojure-lsp install script if you find anything to improve there.

**Comment by mathieuroblin** [comment]
@PEZ Is there any way for you to directly leverage the install script from clojure-lsp? It seems it's quite configurable regarding versions/checksum etc...

Regardless It seems to me the only case they are handling is aarch64 (arm64 linux) and all the rest default to the amd64 version.

**Comment by PEZ** [comment]
I'll have a look if we can use the install script, or be inspired by it at least. 

Re the jar, Is it slower when it is running or just slower to start? The latter could be a prize I am willing to pay to know that we are compatible as long as Java works.

**Comment by PEZ** [comment]
Another way to deal with it is to remove this functionality with downloading latest clojure-lsp for the user, and let them install things themselves and configure the path. I'm reluctant because it would mean a lot of users running w/o clojure-lsp, but it is a trade-off of course. I wonder how common it is with clojure-lsp not starting for Calva users...

**Comment by ericdallo** [comment]
We would need to rely on the java installed by user which doesn't seem better than using the binary, both startup/memory/CPU management are improved by graalvm

**Comment by ericdallo** [comment]
Also, IMO the clojure-lsp installation works for most people, disabling would not be a good decision IMO, if we have ways to set the path and not install automatically, sounds enough to me.
We can still use clojure-lsp installation script or improve things somewhere though

**Comment by PEZ** [comment]
w/o a proper Java there will be no Clojure coding anyway. It is a rare support topic for Calva use that someone has troubles with Java. And in the devcontainer we can control which Java is installed. 

But it does sound like using the  jar should be the last resort, since it impacts all those performance aspects.

Remote and container use is a very big use case with VS Code.

**Comment by ericdallo** [comment]
> But it does sound like using the jar should be the last resort, since it impacts all those performance aspects.
 Remote and container use is a very big use case with VS Code.

Agree

**Comment by PEZ** [comment]
This seems to have started working now. Not sure what has changed. I now see that Calva downloads clojure-lsp-native-static-linux-amd64.zip, which sort of rings a bell, but I can't recall what it is about.

**Comment by bpringe** [comment]
This may have been fixed by https://github.com/BetterThanTomorrow/calva/pull/1693 or https://github.com/BetterThanTomorrow/calva/pull/1758, just FYI.

**Comment by bpringe** [comment]
@PEZ Actually you may want to verify it still works since https://github.com/BetterThanTomorrow/calva/pull/1758 was merged. I don't know if you tried before or after that, but that PR brought back the downloading of the non-static linux. But it only downloads that one if the architecture is arm64 (so it may be fine).
