### ISSUE TITLE
clojure-lsp does not start in the Getting Started REPL

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1601]
Clojure-lsp fails to start when firing up a standalone REPL in a folder-less VS Code window.

~I am pretty sure this is a regression cause by~

* #1592

**Comment by PEZ** [comment]
I no longer think this is a regression. It is probably rather that the clojure-lsp status indicator exposes the error. And then the status-indicator does not get updated because we don't handle the error that happens:

When running the serverInfo command on the client there happens an internal error in the lsp server:

```
'java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessa…173)
\tat clojure_lsp.feature.format$resolve_user_cljfmt_config.invokeStatic(format.clj:21)
\tat clojure_lsp.feature.format$resolve_user_cljfmt_config.invoke(format.clj:19)
\tat clojure_lsp.handlers$server_info$fn__35173.invoke(handlers.clj:186)
\tat clojure_lsp.handlers$server_info.invokeStatic(handlers.clj:185)
\tat clojure_lsp.handlers$server_info.invoke(handlers.clj:177)
\tat clojure.lang.Var.invoke(Var.java:380)
\tat clojure_lsp.server.ClojureLSPServer.serverInfoRaw(server.clj:404)
\t... 15 more'
```

Testing v2.0.253 of Calva, clojure-lsp is indeed working some. But running the serverInfo command (the user command) results in an ”Internal error” message box.

@ericdallo: Do you have some idea about what I could do to try diagnose this further? It only happens when there is no folder opened in VS Code, so might be something with clojure-lsp running into troubles finding the project root.

**Comment by ericdallo** [comment]
Yeah, it's probably related with wrong project-root, we should probably do a safe check of the project-root and fail the initialize instead of waiting for things to crash on clojure-lsp side, even so, clojure-lsp won't probably work if project-root is incorrect, could you get the full log from server? More info on how to [here](https://clojure-lsp.io/troubleshooting/#server-log)

**Comment by ericdallo** [comment]
@PEZ I think @Cyrik helped me find the issue, it's related with cljfmt-raw setting inclusion on the server logs info, we expect that `project-root` is valid, if not we crash, I'll change to not crash, so that command doesn't blow up at least

**Comment by PEZ** [comment]
Ah, so the problem is pretty new then. That explains why we haven't seen it until now. I thought that was a bit strange.

**Comment by ericdallo** [comment]
So clojure-lsp starts on getting started right? but without a project-root most features probably doesn't work

**Comment by PEZ** [comment]
Correct. It starts, but not much is working.

**Comment by PEZ** [comment]
Seems we can trick VS Code into sending a valid root-uri to clojure-lsp at start up by using something like this in `LanguageClientOptions`:

```
    workspaceFolder: {
      uri: vscode.Uri.file('/tmp/'),
      name: 'foo',
      index: 0,
    },
```

Since we know where the **Getting Started REPL** files are stored we can use that path and get clojure-lsp to start with the right root path.

Also, @ericdallo suggests we include a minimal `deps.edn` to make clojure-lsp as helpful as possible.
