### ISSUE TITLE
Connect fails when there is no project file (`deps.edn`, etc)

### ISSUE THREAD

**Issue by brettrowberry** [BetterThanTomorrow/calva#1613]
I have a custom project type in `.vscode/settings.json`:

```json
{
    "calva.replConnectSequences": [
        {
            "name": "Monorepo REPL",
            "projectType": "generic",
            "nReplPortFile": [".nrepl-port"],
            "afterCLJReplJackInCode": "(start)",
            "cljsType": "none"
        }
    ]
}
```

In 2.0.256, I can connect a REPL client.

In 2.0.257, I 
1. Start my REPL server
2. Run `Calva: Connect to a running REPL Server`
3. I'm greeted with the new `Project root` picker
4. I bypass with <kbd>Esc</kbd>
5. I'm greeted with `Please select a project type`
6. I choose `Monorepo REPL`
7. A popup appears with message `Failed initializing project root directory:`

I think this was introduced by #1254.

**Comment by PEZ** [comment]
Hello. Thanks for reporting!

We should probably complain at 4 instead of pretending things will work. You need to pick a project root. The same one as was auto-picked before #1609 is now pre-selected in the project root menu, so you should be able to connect by pressing `enter` instead of `esc`.

**Comment by brettrowberry** [comment]
I don't know which project root was auto-picked before #1609, but all the project roots surfaced now look to be locations containing a `deps.edn` and none is pre-selected.
The project root I want is some Bazel thing. Now both <kbd>enter</kbd> and <kbd>esc</kbd> seem to be no-ops.

**Comment by PEZ** [comment]
I checked the Calva code now, and `esc` and `enter` do the same thing. I'm sorry for the misinformation. (Still think we probably should complain on `esc` rather than auto-selecting something.)

Can you describe the project and what file you have open when you run the connect command? What is a **Bezel thing**? Judging from the connect sequence you have, it looks like the workspace root should be the project root. Do you have a deps.edn there?

**Comment by brettrowberry** [comment]
Making a minimal repro is beyond my current understanding of what we've built using https://bazel.build. However, adding a `deps.edn` containing `{}` at the root of my repo worked.

**Comment by PEZ** [comment]
Thanks for the update, @brettrowberry!

I'll reopen the issue because we should probably do something about it. At least document it...

**Comment by CFiggers** [comment]
Possibly related:

With 256, I can connect to a Babasha nREPL using the `Calva: Start a Project REPL` command in a completely empty directory.

Repro:
```Bash
$ mkdir calva-testing
$ cd calva-testing
$ code .
```

Within VS Code:

1. Run `Calva: Start a Project REPL (aka Jack-In)`
=> Get "Please select a project type" pop-up:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/55862180/159949053-418c4ebd-287c-47c0-968f-c1346b12f329.png">

2. Select Babashka
=> Successful Jack-in 

---

With 257, following the exact same steps does not present the "Please select a project type" pop-up.


Repro:
```Bash
$ mkdir calva-testing
$ cd calva-testing
$ code .
```

Within VS Code:

1. Run `Calva: Start a Project REPL (a.k.a Jack-in)`
=> Nothing

<img width="423" alt="image" src="https://user-images.githubusercontent.com/55862180/159950131-5a10cf55-47c8-46b4-8e02-5dffb02ad0af.png">

---

After adding a deps.edn containing `{}` at project root, I get the "Please select a project type" pop-up with Babashka, nbb, and deps.edn options:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/55862180/159950711-1fe034a8-19df-43f0-90a5-acc081f0c66c.png">

But a bb.edn containing `{}` at project root does not have the same effect.

**Comment by PEZ** [comment]
And the winner for best repro description is @CFiggers ! Thanks 🙏 ❤️ (Close call, 😄 )

A first an easy fix is to include `bb.edn` as a project root ”marker”. Something I was already planning to do, so extra thanks for confirming that.

We need to do more to fix the problem in general... I need to ponder about exactly what though. 😄
