### ISSUE TITLE
Keywords not highlighting

### ISSUE THREAD

**Issue by deadeyejoe** [BetterThanTomorrow/calva#1614]
Keywords recently stopped highlighting for me, I think that this happened at the same time as a vscode update, but it was a week or two ago and I can't remember the exact timings. As can be seen in the screenshot the other syntax highlighting works fine, but the keywords should be an orangey colour.

I've made sure I'm running the latest (linux) version of vscode and the extension, and I've tried changing themes and all of them seem to have the same problem. Keywords in other languages (e.g. ruby) highlight fine.

Apologies if this is not a calva problem, but I'm stumped on how to proceed. Any advice on how I can narrow down the source of the problem?

![image](https://user-images.githubusercontent.com/10846066/159735809-7a58cc2a-a3b4-4aca-940e-c1748267a867.png)

**Comment by PEZ** [comment]
We changed how Clojure keywords are tokenized in the grammar. Your theme probably doesn't have a highlight defined for the scopes we are now using. If you are very fond of the theme you can help it with a setting:

```json
    "editor.tokenColorCustomizations": {
        "[Default Dark+]": {
            "textMateRules": [
                {
                    "scope": [
                        "constant.keyword.clojure"
                    ],
                    "settings": {
                        "foreground": "#6fbfff"
                    }
                }
            ]
        }
    },
```

Instead of `Default Dark+` you should use your theme's name/key. And choose a color you like, of course.

**Comment by deadeyejoe** [comment]
Did the trick! thanks!
