### ISSUE TITLE
error reported during jack-in

### ISSUE THREAD

**Issue by vamem9z-Moses** [BetterThanTomorrow/calva#1615]
On Windows 11 WSL on ARM - Surface Pro X - SQ1 16GB

When trying to start a repl in my project I see the following in the Calva Jack-in Window

your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
Jack-in process exited. Status: 1

I'm not sure what other information you need. Please let me know and I will provide it.

**Comment by PEZ** [comment]
Hi there! Do you see the command that Calva tries to execute in the jack-in terminal?

**Comment by vamem9z-Moses** [comment]
Sure. Here is the jack-in command

; Starting Jack-in Terminal: npx shadow-cljs -d cider/cider-nrepl:0.27.4 -A:dev:test:clj:cljs:cljs-dev:cljs-test watch app

**Comment by PEZ** [comment]
Thanks. That comes from the Output/REPL Window, right? I am assuming that the error messages involving `xargs` and such was in the jack-in terminal. Did the command ever print there? The jack-in command line for starting doesn't even contain quotes. So maybe something goes wrong before we even get there...

Can you try executing that command in a terminal and then connect Calva instead of using Jack-in?

**Comment by vamem9z-Moses** [comment]
It works when I run the command in a terminal and then connect Calva. 

Here is what printed in the terminal during Jack-in.

npx shadow-cljs -d cider/cider-nrepl:0.27.4 -A:dev:test:clj:cljs:cljs-dev:cljs-test watch app
shadow-cljs - config: /home/mmiles/Software/dcentwork-app/shadow-cljs.edn
shadow-cljs - starting via "clojure"
your 131072x1 screen size is bogus. expect trouble
your 131072x1 screen size is bogus. expect trouble
xargs: unmatched double quote; by default quotes are special to xargs unless you use the -0 option
Jack-in process exited. Status: 1

**Comment by PEZ** [comment]
Very strange. Seems to be something happening in the `clojure` script. I don't think shadow ever does any `xargs` stuff. Maybe @puredanger knows what we should investigate now... Which version are you using?

**Comment by puredanger** [comment]
`clojure` also does not use xargs, but I don't see you using `clojure` above - that says `npx shadow-cljs` (not sure what it does).

**Comment by PEZ** [comment]
@puredanger shadow-cljs is spawning `clojure`

```
shadow-cljs - starting via "clojure"
```

I'm not sure, from the output, if it ever gets to actually spawn it, of course.

**Comment by PEZ** [comment]
@vamem9z-Moses when you used the command manually, did you do it in a VS Code integrated terminal or something external to VS Code?

**Comment by PEZ** [comment]
The whole thing sound a lot like this one:

* #1162

 But it couldn't be, using WSL, right? (1162 ultimately was a java spawning bug in Oracle's executables, that they fixed.)

**Comment by vamem9z-Moses** [comment]
@PEZ Yes, when I run the command manually, I run it in the integrated VS Code terminal.  And yes, this is in WSL. [Microsoft's JAVA port for Windows on ARM](https://github.com/microsoft/openjdk-aarch64/releases) is also installed on the base OS.

The project I'm working on depends on [shadow-cljs](https://github.com/thheller/shadow-cljs) and node e.g. the npx command. I think this is something specific to WSL and Windows on ARM. I have an x86 laptop with the same project and I don't have any issue jacking in. 

I can't tell if this is a calva issue or a shadow-cljs issue. Since it works outside of calva in both platforms, I thought it might be a calva issue.

**Comment by PEZ** [comment]
The fact that it works when you run the jack-in command line in a VS Code terminal, but not when using jack-in suggests that it is a Calva issue. Not sure what we can do about it, but it's good to have this issue letting us know the problem exists.

Your best workaround here is the command **Copy Jack-in command line to clipboard** together with **Connect to a running REPL**, I think.
