### ISSUE TITLE
Rainbow parentheses sometimes not activating

### ISSUE THREAD

**Issue by danielytics** [BetterThanTomorrow/calva#1616]
Hi, I was away from Clojure for a few weeks and when I came back, today, I noticed that my syntax highlighting had changed. I saw from #1614 that some of this was caused by change sin how Calva handles keywords, so I was able to resolve that.

However, rainbow parentheses aren't working for me at all. It doesn't appear to matter what theme I choose and I tried changing settings (eg toggling on and off and specifying my own list of colours) but to no avail. I don't get rainbow parentheses for any clojure files, regardless of what I try.

Might be related to #1597 as commented out forms (with `#_` or `(comment ...)`) do not get styled either.

**Comment by PEZ** [comment]
I'm thinking maybe the highlight (sub) extension does not activate. Can you see if you have some message in the dev console (Help menu -> **Toggle Developer Tools**)?.

**Comment by danielytics** [comment]
Hmm, strange, today rainbow parentheses are working! There is nothing in the console.

The only thing I did was restart VSCode (but not my laptop). I did that yesterday too but it didn't help then, odd. `#_` now changes highlighting too (`comment` does not, but I don't remember if it is supposed to?)

I will close this issue, but if it reoccurs, I will check the dev console and reopen it.

**Comment by PEZ** [comment]
Let's keep this open for now. It's more visible and if someone sees it they might be reminded that it has happened to them and then they can provide some clues.

As for `( comment ...) ` it should be _italicized_. It is configurable though, maybe you didn't like the defaults and changed it? https://calva.io/customizing/#calva-highlight

**Comment by danielytics** [comment]
Ah, it does actually italicize, so its working as expected after all! I think everything is working for me then. I suspect it had something to do with version updates (Calva and/or VSCode) but I'm not really sure why I couldn't get it resolved yesterday.

**Comment by PEZ** [comment]
> I'm not really sure why I couldn't get it resolved yesterday.

I suspect we have a bug that we need to find and fix. 😄
