### ISSUE TITLE
Add default Clojure associations for file extensions `.bb` and `.cljd`

### ISSUE THREAD

**Issue by baibhavbista** [BetterThanTomorrow/calva#1617]
Does not support some extensions (.bb, .cljd) by default. 

.bb is for [Babashka](https://github.com/babashka/babashka) files
.cljd is for [ClojureDart](https://github.com/Tensegritics/ClojureDart) files (currently under private beta, will be released pretty soon)

Workaround is to change the language association manually via the setting `File: Association`, or at-will with the command `Change Language Mode`.

Discussed here: https://clojurians.slack.com/archives/CBE668G4R/p1648009121586269

**Comment by PEZ** [comment]
Thanks for this issue! Maybe @borkdude knows of some more extension we could add as default?

**Comment by borkdude** [comment]
Other than .bb from my side there are no special extensions. Thanks!

**Comment by Cyrik** [comment]
This is now also added to lsp, so I'm closing the ticket

**Comment by PEZ** [comment]
I should learn the resolving commit message syntax better. 😄
