### ISSUE TITLE
bizzare behavior  calva.setREPLNamespace

### ISSUE THREAD

**Issue by Gnurdle** [BetterThanTomorrow/calva#162]
This was a 2.0.0-SNAPSHOT 

The keybinding

{
  "key": "meta+n",
  "command": "calva.setREPLNamespace"
}

paste the following snippet into a buffer with a jacked-in repl (I think connect creates the same issue).

running calva.setREPLNamespace fails (results in namespace 'user' being selected), and a lot of CPU being chewed up by the vs-code executable.  This one isn't so bad, but it shows the problem.  The one I started with was grinding for 15+ seconds on modern ryzen desktop.

Now, remove the blank line @32, and try it again.  It works perfectly.

Weird.

;;=====================================================================;;
;;     ____                         _  _                               ;;
;;    / ___| _ __   _   _  _ __  __| || |  ___                         ;;
;;   | |  _ | '_ \ | | | || '__|/ _` || | / _ \                        ;;
;;   | |_| || | | || |_| || |  | (_| || ||  __/                        ;;
;;    \____||_| |_| \__,_||_|   \__,_||_| \___|                        ;;
;;     ____                           _  _    _                        ;;
;;    / ___| ___   _ __   ___  _   _ | || |_ (_) _ __    __ _          ;;
;;   | |    / _ \ | '_ \ / __|| | | || || __|| || '_ \  / _` |         ;;
;;   | |___| (_) || | | |\__ \| |_| || || |_ | || | | || (_| | _       ;;
;;    \____|\___/ |_| |_||___/ \__,_||_| \__||_||_| |_| \__, |( )      ;;
;;    _      _      ____                                |___/ |/       ;;
;;   | |    | |    / ___|                                              ;;
;;   | |    | |   | |                                                  ;;
;;   | |___ | |___| |___  _                                            ;;
;;   |_____||_____|\____|(_)                                           ;;
;;                                                                     ;;
;;=====================================================================;;
;;
;; Purpose
;; -------
;; blah blah blah blah blah blah blah blah blah blah blah blah blah blah
;; blah blah blah blah blah blah blah blah blah blah blah blah blah blah
;; blah blah blah blah blah blah blah blah blah blah blah blah blah blah
;; blah blah blah blah blah blah blah blah blah blah blah blah blah blah
;; blah blah blah blah blah blah blah blah blah blah blah blah blah blah
;; blah blah blah blah blah blah blah blah blah blah blah blah blah blah
;; blah blah blah blah blah blah blah blah blah blah blah blah blah blah
;; blah blah blah blah blah blah blah blah blah blah blah blah blah blah
;; blah blah blah blah blah blah blah blah blah blah blah blah blah blah

;; =======================================================================
;;
(ns ace2.legacy.bink
  (:gen-class)
  (:require [clojure.java.io :as io])
  (:import (java.io RandomAccessFile)))

(defn foo [] (println "whee"))

**Comment by PEZ** [comment]
Thanks. This should now be resolved in the latest preview of Calva 2.

**Comment by Gnurdle** [comment]
This has been resolved for quite a while now.
