### ISSUE TITLE
Indenting not working correctly in vectors starting with fn-like symbols

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1622]
If I have the below code and press enter with my cursor where noted with `|` in the first example, it then ends up where noted in the second.

Starting:

```clj
(let [context {:a 1
               :b [{:c 2}]}|])
```

When I press enter:

```clj
(let [context {:a 1
               :b [{:c 2}]}
       |])
```

What I expect after pressing enter:

```clj
(let [context {:a 1
               :b [{:c 2}]}
      |])
```

**Comment by PEZ** [comment]
Oh, wow, this is weird:

```clojure
(let [context|])
```
<kbd>enter</kbd>
```clojure
(let [context
       |])
```

But:

```clojure
(let [contexs|])
```
<kbd>enter</kbd>
```clojure
(let [contexs
      |])
```

**Comment by PEZ** [comment]
So, I think I know what is going on now. `context` has default indents `[[:inner 0]]`

If we test that theory with some more default indentations:

```clojure
;; `[[:inner 0]]`
[fn|]

;; `[[:block 0]]`
[do|]

;; `[[:block 1]]`
[let|]
```

<kbd>enter</kbd> in all the forms

```clojure
;; `[[:inner 0]]`
[fn
  |]

;; `[[:block 0]]`
[do
  |]

;; `[[:block 1]]`
[let
 |]
```

So, the bug then is that our indenter doesn't check for the type of list it indents. Amazing.
