### ISSUE TITLE
Use clojure-lsp to show decompiled Java classes

### ISSUE THREAD

**Issue by Cyrik** [BetterThanTomorrow/calva#1637]
Clojure-lsp just added a way to get decompiled versions of Java classes. We should start returning those if the regular "go to def" returns nothing. 
https://github.com/clojure-lsp/clojure-lsp/issues/762

**Comment by ericdallo** [comment]
@Cyrik I made some changes after my last comment, and it should work OOTB for all editors :) It may worth test on Calva

**Comment by PEZ** [comment]
:tada: https://twitter.com/pappapez/status/1508359384849657862

**Comment by ericdallo** [comment]
I think we can safely close this issue so :)

**Comment by Cyrik** [comment]
Great work, thank you!
