### ISSUE TITLE
CLJS breakpoint error

### ISSUE THREAD

**Issue by rongcuid** [BetterThanTomorrow/calva#1642]
I was trying to insert a `#break` in a CLJS project, and I get this error:

```
Attempting to call unbound fn: #'cider.nrepl.middleware.debug/breakpoint-reader
```

I am using shadow-cljs. Just try this:

```
(comment
  #break 1 ;; <- evaluate this)
```

**Comment by bpringe** [comment]
Hi! Unfortunately, the debugger only works on Clojure, not ClojureScript. From the docs (and for more info):

> The debugger currently does not support ClojureScript. Calva's debugger utilizes cider-nrepl for debugging. See [this Cider issue](https://github.com/clojure-emacs/cider/issues/1416) for more information.

https://calva.io/debugger/

**Comment by bpringe** [comment]
I'm going to close this, but if you have any issues using the debugger on Clojure code, please file another issue.
