### ISSUE TITLE
In example actual does not match expected.

### ISSUE THREAD

**Issue by phreed** [BetterThanTomorrow/calva#1645]
In [Evaluation](../blob/published/docs/site/evaluation.md#evaluate-to-cursor) the expected result is `(12 21)` but the actual result is `(13 21)`. 
Here is the corrected form.
```clojure
  (->> [1 1 2 3 5 8 13 21]
       (partition 2)
       (zipmap [:a :b :c :d])
       :d| ; => (13 21)
       (apply -)
       (Math/abs))
```

**Comment by PEZ** [comment]
Thanks! Can we hope for a PR? 😄 See [Editing Documentation](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva#editing-documentation) in [How to Hack on Calva](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva)

**Comment by phreed** [comment]
I made PR #1646

**Comment by PEZ** [comment]
❤️ Closing since you fixed it!
