### ISSUE TITLE
Jump to code definition feature failed while repl is on

### ISSUE THREAD

**Issue by Hzqi** [BetterThanTomorrow/calva#1649]
I use this plugin version 2.0.225, when i turn repl on, i hold command (macos) and click the code, it will jump to the definition, it works fine.

I update the plugin to version 2.0.260, the feature seems failed, when the repl is on, jump to definition failed, when I turn it off, it works ok again.

So I don't know whether this feature is cancel or bug when using repl.

System: MacOS 12.0.1
clojure: 1.10.3
nrepl: 0.9.0
cider-nrepl: 0.27.4
cider/piggieback: 0.5.3
clojure-lsp version configured: latest (configured by calva)

**Comment by PEZ** [comment]
Thanks for the report!

What kind of project are you working with?

**Comment by Hzqi** [comment]
> Thanks for the report!
> 
> What kind of project are you working with?

clojure project with deps tools, but my project nrepl dependency version is 0.6.0

**Comment by bclark-videra** [comment]
I'm seeing this as well with a leiningen clj project. Jack-in and Connect to running REPL seem to show the same behavior: connected to REPL, jump to definition doesn't work.

**Comment by Cyrik** [comment]
#1596 is hopefully going to fix this by having better merging/priority for "go to def" when having a repl and LSP running

**Comment by Hzqi** [comment]
Looks it is fixed on the newset version (2.0.269)

if no other problem, @Cyrik @PEZ ,this can be closed 😁
