### ISSUE TITLE
Combined command for `backward/forwardSexp` and `backward/forwardUpSexp` - `backward/forwardSexpOrUp`

### ISSUE THREAD

**Issue by JJ-Atkinson** [BetterThanTomorrow/calva#1657]
As per some [discussion on slack](https://clojurians.slack.com/archives/CBE668G4R/p1648707972296699), I'd like to request a new paredit command that will go up if at the end of an sexp. 

Current `forwardSexp` behavior: (`|` is cursor, each line is an invocation of fwdSexp)
 ```clojure
(def x (|inc 1))
(def x (inc |1))
(def x (inc 1|))
(def x (inc 1|)) ;; stopped moving
```

To more closely match some paredit behavior from Cursive that I use, it'd be nice to have this modified behavior:

 ```clojure
(def x (|inc 1))
(def x (inc |1))
(def x (inc 1|))
(def x (inc 1)|) ;; Escaped the sexp
(def x (inc 1))| ;; Escaped the sexp
```

**Comment by corasaurus-hex** [comment]
I agree this would be great! We could go even further, though, like in this issue: https://github.com/BetterThanTomorrow/calva/issues/1487

**Comment by corasaurus-hex** [comment]
Specifically the movements here for curly braces and brackets https://github.com/luxbock/evil-cleverparens#movement

**Comment by corasaurus-hex** [comment]
ohh this is just similar but not identical to my feature request. ignore me!

**Comment by JJ-Atkinson** [comment]
@corasaurus-hex Peter actually pointed me at your issue - I've not considered that feature before. Unfortunately I have very little idea on how to implement that, so I'm working on the one I understand :P
