### ISSUE TITLE
Feature request: Evaluate file result shown in VSCode notification

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#166]
My current workflow usually involves editing files and saving with eval-on-save turned on. So I can change some code, save, and try to call the changed code (function) in the repl. If an error occurs on evaluation, I have to switch my terminal window to the output window ("Calva says") to see the error. 

It would be nice if on save (or really, on any evaluation of a file), a notification popped up showing the result of the evaluation. so that I would know immediately if there is an error. This is similar to how some setups involving building/bundling javascript files on save results in a notification that the build was successful.

Perhaps I'm using an inefficient workflow. I'm open to suggestions if you think so.

**Comment by PEZ** [comment]
Hello. I agree it can be quite a bit of things silently failing. I think it demands some thought through, general solution. But for the specific case, we could bring the ”Calva says” pane open on evaluation errors, would that help? Or would it break your flow having to switch back to the terminal?

**Comment by bpringe** [comment]
Actually, bringing the "Calva says" pane open on evaluation errors I think would be a good solution, as I wouldn't want to me in the terminal trying to run something I just saved if there were errors.

**Comment by bpringe** [comment]
Closing since this seems to already happen (the Calva says window opens upon evaluation).
