### ISSUE TITLE
Calva and Vim Keybindings

### ISSUE THREAD

**Issue by gkhasel1** [BetterThanTomorrow/calva#167]
Hey, loving Calva so far really appreciate the hardwork.

I'm using Vim keybindings with VSCode (https://github.com/VSCodeVim/Vim) and noticed that when I'm working on my clojure projects with Calva the behavior of ESC to enter Vim command mode stops working. Working well with other extensions obviously isn't the sole responsibility of Calva, but I was hoping you could point me in the right direction to debugging this behaviour.

Is calva setting some action on ESC or overriding some VSCode settings related to ESC? Is there a way for me to view what action Calva is trying to take when i hit ESC? Is this an issue that has been brought to your attention before? Open to any suggestions on how to sort out this situation. 

Thanks!

Vim version 1.4.0
Calva 1.3.66
Calva Clojure Formatter 0.0.38
Calva Paredit 0.1.22

**Comment by gkhasel1** [comment]
hmm may have found the issue:

```
{
  "command": "calva.clearInlineResults",
  "key": "escape",
  "when": "editorLangId == clojure && editorTextFocus && !editorReadOnly && !suggestWidgetVisible && !hasOtherSuggestions"
}
```

gonna try remapping this and report back.

**Comment by gkhasel1** [comment]
I suspect that this might be an issue with other extensions as well using <Esc> to clear out some displayed result in debug mode and a repl mode (like Calva). As a result I decided to remap vim's insert mode keybinding to go into command mode by adding the following to my user settings:

```
"vim.insertModeKeyBindings": [
        {
            "before": ["j", "k"],
            "after": ["<esc>"]
        }
   ]
```

Hope this helps someone else with this issue!

**Comment by PEZ** [comment]
Thanks! It would be extra awesome if you added this to the wiki. (Maybe with some more explanation on why your settings helps.)

**Comment by gkhasel1** [comment]
Cool added it to the Customize Calva page. Feel free to edit the formatting as you see fit, thanks again @PEZ!

**Comment by PEZ** [comment]
Thanks! I copied some of that to a page if its own. To make it easier to discover.
