### ISSUE TITLE
Jack-in doesn't handle a shadow-cljs config without builds

### ISSUE THREAD

**Issue by lilactown** [BetterThanTomorrow/calva#1683]
shadow-cljs comes built in with a few default REPL builds, the `browser-repl` and `node-repl`.

Right now, if I have no `:builds` key in my `shadow-cljs.edn`, Calva's jack in command fails when I select shadow-cljs as the type of REPL with the error

```
Command 'Calva: Start a Project REPL and Connect (aka Jack-In)' resulted in an error (Cannot convert undefined or null to object)
```

Once I add an empty hashmap `:builds {}` to my config, I continue to the next step (select the build) and type in `browser-repl`, which fails with the following error

```
Command 'Calva: Start a Project REPL and Connect (aka Jack-In)' resulted in an error (No shadow-cljs build selected)
```

It would be great to support jacking in with the shadow-cljs browser REPL and node REPL just like with plain CLJS.

**Comment by riotrah** [comment]
I get what I believe is your desired functionality when I run my work web/ui project that uses shadow. When picking the build, I see 3 of our defined builds (eg app, test, etc), plus the default node and browser options. What do you see? Could you share a screenshot?

**Comment by lilactown** [comment]
if you have a shadow-cljs project with builds defined in `shadow-cljs.edn`, jacking in works seamlessly. However, if I start a new project with a shadow-cljs.edn config like:

```clojure
{:source-paths ["src"]
 :dependencies [[lilactown/helix "0.1.5"]
                [binaryage/devtools "1.0.6"]]}
```

and I want to start a browser REPL, I can't do that by running the typical jack in command.

What I would like to be able to do is have an option to pick a "shadow-cljs browser REPL" and "shadow-cljs Node.js REPL" similar to the options for "deps.edn + ClojureScript Browser REPL."

**Comment by lilactown** [comment]
To be clear, what I mean by browser REPL is documented here https://shadow-cljs.github.io/docs/UsersGuide.html#browser-repl

it's basically a way to quickly spin up a browser environment with a REPL connected without configuring a build.

**Comment by lilactown** [comment]
A temporary solution I found is that if I run shadow-cljs from a terminal `npx shadow-cljs server` and then use calva's "Connect to a running REPL" command, it gives me an option to select shadow-cljs a connection and start a browser REPL once connected.

**Comment by riotrah** [comment]
Interesting, so in the absence of _any_ defined builds, not even the defaults are available.

Jacking is overall still the way to go! In the meantime of a deeper understanding or resolution of this, does passing some kind of trivial or no-op-ish build provide the defaults?

**Comment by PEZ** [comment]
@rayat: I challenge that jack-in is the way to go. It totally depends on circumstances. There are too many project setups possible for jack-in to cover them all, even if we manage to expand this piece by piece with the user feedback coming in. But when jack-in works, it is great, with you there.

@lilactown: This issue points at an unnecessary requirement in the jack-in process. It is probably predating the addition of the `browser-repl` and `node-repl` ”builds” support. Alternatively something recently added when we have added more checks all over the codebase. Regardless, I think it can be pretty easily fixed. Thanks for the heads-up!

**Comment by PEZ** [comment]
Latest Calva, v2.0.268, fixes this. I basically applied your workaround, @lilactown. This works because jack-in is really ”just” a command line and a managed process which, when the Clojure REPL is started, hands over to regular Calva connect functionality. See [The Jack-in Academy](https://calva.io/jack-in-guide/) for more on this.

**Comment by lilactown** [comment]
yeah - it is helpful to have this as a built in option, since to run the correct `npx shadow-cljs server ...` command I had to convince Calva to construct the shell command for me - so I would load all the right cider deps - and then modify it before running it. Thank you for adding this as a built in option!
