### ISSUE TITLE
Jack-in to Clojure REPL using shadow-cljs

### ISSUE THREAD

**Issue by lilactown** [BetterThanTomorrow/calva#1684]
I often work within shadow-cljs projects that have two or more builds. With Emacs, I prefer to first start a Clojure REPL where I can then start the builds I want to run, then drop into the appropriate CLJS REPL by running `(shadow/repl :build-id)` and returning to the Clojure REPL by typing `:cljs/quit`.

It would be great to be able to do this with Calve as well, i.e.

1. Start by jacking in to a Clojure REPL started via shadow-cljs
2. Drop into different builds' REPLs (either via simple REPL commands or some Calva functionality)

**Comment by PEZ** [comment]
Calva has a command **Select CLJS Build Connection** that let's you switch between shadow-cljs builds. Is that what you need? There's a build indicator in the status bar that also is a button tied to this command.

**Comment by lilactown** [comment]
Perhaps that would cover the important 80% of what I want. I'm just used to being able to run e.g. `cider-jack-in-clj` in my CLJS projects that then let me futz around in a Clojure REPL before dropping into the ClojureScript REPL.

**Comment by PEZ** [comment]
It works a bit differently in Calva. It will automatically use the Clojure REPL for `.clj` files, and the ClojureScript REPL for `.cljs` files. For `.cljc` files, Calva lets you toggle which REPL to use. And also, the REPL/output file is treated as `.cljc`, so you can futz around there in your REPL of choice.

**Comment by PEZ** [comment]
You _can_ do `:cljs/quit` in the ClojureScript REPL, and promote it back when your done. But during the while it is a Clojure REPL, Calva won't know this, causing the UI to reflect a different situation than what you have, so I usually do not do stuff like that.

There is also the option to use a [Custom REPL Connect Sequence](https://calva.io/connect-sequences/) and skip promoting to a ClojureScript REPL there. Doing that later, manually. Sounds like that would mimic the workflow you are used to. But again, Calva would assume the REPL to be a ClojureScript one, so the UI wouldn't reflect things correctly. I don't recommend.

**Comment by lilactown** [comment]
I see. Sounds like I can do all the same stuff I used to, just with a slightly different workflow. Closing this!
