### ISSUE TITLE
Environment Variables in nRepl

### ISSUE THREAD

**Issue by gkhasel1** [BetterThanTomorrow/calva#169]
Hello! 

Was hoping to get some guidance about how to integrate my Environment Variable workflow with the nrepl integration.

Generally, for all projects, I use direnv (https://direnv.net/) to populate the environment when I enter a new working directory with a `.envrc` file. I do this for clojure too and its a great workflow! As a result, I start a repl inside my terminal where the appropriate environment variables have been exported by direnv and I'm ready to jack-in with tools such as Cider.

I've noticed that when I use Calva to evaluate sexp's in my VSCode files environment variables aren't properly exported for use in my code. My current workflow looks like:

* Calva: Connect (connect to the repl i started in my terminal where direnv is running)
* Calva: Evaluate current file
* Calva: Evaluate selection of current form

When i connect i see `lein repl :connect localhost:51347` which is the correct repl!
I am using `environ.core` for environment variable integration with my clojure code, a fairly simple and standard library for env management.

Any ideas on how to debug? Any thoughts on other workflows that would better integrate with my environment variables?

Thank you!

**Comment by PEZ** [comment]
Hello! How are you starting VS Code?

**Comment by gkhasel1** [comment]
usually i start it from the command line using `code` but im seeing the same effect when opening the native osx app by clicking it in the finder.

**Comment by gkhasel1** [comment]
derp it was special characters in the env var that broke things.

**Comment by PEZ** [comment]
Happy you solved it!

Just as an information point, the next major release of Calva will allow you to pass environment variables to the process that starts the REPL. (It has a CIDER inspired jack-in feature.)
