### ISSUE TITLE
Pressing "enter" in the REPL window while editor suggestions are active evaluates whatever's typed without applying the suggestion

### ISSUE THREAD

**Issue by maxrothman** [BetterThanTomorrow/calva#1696]
Replication:
- Connect to a REPL
- Start typing something into the REPL window that will trigger editor suggestions
- Highlight one of the suggestions
- Press "enter"

Expected behavior: the suggestion is applied

Actual behavior: whatever you typed is evaluated in the REPL

**Comment by bpringe** [comment]
@maxrothman Is this something you mentioned you wanted to create a PR for? I seem to remember some discussion about it on Slack but I don't know if you said that. The solution seems to be a when context adjustment on a shortcut.

**Comment by maxrothman** [comment]
@bpringe thanks for following up! I don't remember if I had planned to make a PR or not, but nonetheless I have done so now! https://github.com/BetterThanTomorrow/calva/pull/1720

**Comment by bpringe** [comment]
@maxrothman Awesome! Thanks!
