### ISSUE TITLE
Enable users to bind keyboard shortcuts to clojure-lsp drag commands

### ISSUE THREAD

**Issue by mainej** [BetterThanTomorrow/calva#1697]
The clojure-lsp version of the drag commands offer some improvements over the built-in drag commands. See #1695 for a detailed explanation of how the clojure-lsp commands work.

This is a request to allow users to bind keyboard shortcuts to the clojure-lsp drag commands.

I'll contribute a PR, but this is my first contribution to Calva, so I may need some guidance. Thanks in advance!

**Comment by PEZ** [comment]
Thanks, @mainej ! I'm eager to help you, even if I don't know if I am the best person to know how this could be done. I have added some commands that request things from clojure-lsp. Then I needed to first provide something in clojure-lsp. Good thing you already know how to hack that. 😄  Please join the `#calva` channel at the [Clojurians slack](http://clojurians.net). It is the easiest and quickest way to reach us.
