### ISSUE TITLE
[2.0] Annoying horizontal scroll in REPL Window

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#171]
The automatic scrolling horizontally often scrolls things at the beginning of the lines out of view, seemingly unnecessary.

It should probably only scroll automatically in order to make the input cursor visible.

**Comment by PEZ** [comment]
This one also needs your attention, @mseddon . I'm thinking that we probably should present the input caret below the prompt, because that one often gets quite long in real projects, and the REPL window often needs to be quite narrow.

**Comment by cfehse** [comment]
@PEZ 

This seems to be fixed as well for me. I close this issue for now.
