### ISSUE TITLE
`:refer-clojure :exclude` doesn't work as expected

### ISSUE THREAD

**Issue by zeitstein** [BetterThanTomorrow/calva#1718]
I have the following file
```clojure
(ns server.transit
  (:refer-clojure :exclude [read]))

(defn read [])
```
When I evaluate it with Calva ("Load Current File and Dependencies"), I get:
```
WARNING: read already refers to: #'clojure.core/read in namespace: server.transit, being replaced by: #'server.transit/read
```

This does not happen when loading the file directly from Clojure CLI or shadow-cljs. From [Clojurians](https://clojurians.slack.com/archives/C053AK3F9/p1652086685621209).

**Comment by bpringe** [comment]
Just adding this context from the linked Slack convo for later (from Peter):

> Loading a file causes a switching of the ns, and there Calva injects (clojure.core/refer-clojure), which seems to interfere with the file loading.

**Comment by bpringe** [comment]
I just realized this may be related to https://github.com/BetterThanTomorrow/calva/issues/1153.
