### ISSUE TITLE
"Toggle between implementation and test" doesn't work in multi-root workspaces

### ISSUE THREAD

**Issue by maxrothman** [BetterThanTomorrow/calva#1725]
Steps to reproduce:
- Open a multi-root workspace
- Create a clojure file (at path `<path-to-file>`) in one of the workspaces (at path `<workspace1>`)
- Run "toggle between implementation and test"

Expected behavior:
Calva asks if I want to create `<workspace1>/test/<path-to-file>`

Actual behavior:
Calva asks if I want to create `<workspace2>/<workspace1>/test/<path-to-file>`

**Comment by PEZ** [comment]
Thanks! I can reproduce it.
