### ISSUE TITLE
Add a command to restart clojure-lsp

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1727]
We have commands to start and stop clojure-lsp. Now it's time to combine the functionality for another command. 😃

**Comment by PEZ** [comment]
Not saying we should not add this, but copying my comment from Slack here about using [Joyride](https://github.com/BetterThanTomorrow/joyride#readme) for this.

This keyboard shortcut does it.

```json
    {
        "key": "cmd+f4",
        "command": "joyride.runCode",
        "args": "(require '[promesa.core :as p]) (p/do (vscode/commands.executeCommand \"calva.clojureLsp.stop\") (vscode/commands.executeCommand \"calva.clojureLsp.start\"))"
    },
```

I would probably define a function for it in some `my-commands` namespace during [Joyride activate](https://github.com/BetterThanTomorrow/joyride/blob/master/doc/api.md#scripting-life-cycle) and call that function instead. This will keep the shortcut simpler. And such a namespace is a natural place to start writing code like this and get it right using the REPL. I will add an example recipe for this to Joyride, I think.
