### ISSUE TITLE
Failure to work with programs installed via asdf-vm

### ISSUE THREAD

**Issue by wbehrens-on-gh** [BetterThanTomorrow/calva#1728]
I'm using asdf-vm to manage the versions of the languages in my project, I have clojure, node, and java installed globally using asdf yet opening a clojure project still gives me.
![image](https://user-images.githubusercontent.com/35979547/168451626-b0453654-f5ba-4824-9c68-492f6dce38fc.png)

all the commands listed there work when I run them in a terminal

**Comment by corasaurus-hex** [comment]
I use asdf, too, and everything works as long as I run `code .` from within the project directory to start the vscode instance. This makes the vscode instance inherit the environment of the shell that started it.

**Comment by wbehrens-on-gh** [comment]
> I use asdf, too, and everything works as long as I run `code .` from within the project directory to start the vscode instance. This makes the vscode instance inherit the environment of the shell that started it.

good to know, is there a setting though that can tell a workspace to inherit from the current directory?

**Comment by corasaurus-hex** [comment]
I don't know if a way, offhand. Your shell initializes asdf in the shell's environment variables and so you need to get vscode to load a shell and grab its environment... or just start a vscode instance from the shell and it uses the environment it starts in.

**Comment by corasaurus-hex** [comment]
Maybe you could do something with direnv? I'm really not sure. I'm going to close this issue for now but if you do find a way to do what you want that doesn't include the discussed solution then feel free to re-open it.
