### ISSUE TITLE
Partial name navigation

### ISSUE THREAD

**Issue by kostafey** [BetterThanTomorrow/calva#1736]
I would like to have an option to navigate by parts of the Clojure names.
E.g. if I have a cursor in the beginning of 
`|my-function-name`
I need to navigate cursor to the end of the first word position: 
`my|-function-name`.

How can I achieve this? No one of these functions `cursorWordLeft`, `cursorWordPartRight`, `paredit.forwardSexp` can do that.

**Comment by PEZ** [comment]
I see three options, each with their own trade-offs:

- Use `corsorWordAccessibilityRight`. It doesn't do the exact right thing.
- Redefine `editor.wordSeparators` in the `[clojure]` scope. It will make double-click and other word-operations work differently as well.
- Use [Joyride](https://github.com/BetterThanTomorrow/joyride). It will take some work (it's fun!).

**Comment by kostafey** [comment]
@PEZ, thank you! Calva and Joyride are awesome!

Redefining `editor.wordSeparators` is exactly what I'm looking for to reproduce my Emacs habits.

`settings.json`:
```json
"[clojure]": {
        "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"
}
```
`keybindings.json`:
```json
    {
        "key": "ctrl+right",
        "command": "cursorWordRight",
        "when": "calva:cursorAfterComment && editorLangId == 'clojure' || calva:keybindingsEnabled && config.calva.paredit.hijackVSCodeDefaults && editorTextFocus && !calva:cursorInComment && editorLangId == 'clojure' && paredit:keyMap =~ /original|strict/"
    }, 
    {
        "key": "ctrl+alt+right",
        "command": "paredit.forwardSexp",
        "when": "calva:keybindingsEnabled && editorTextFocus && editorLangId == 'clojure' && paredit:keyMap =~ /original|strict/"
    },
    {
        "key": "ctrl+left",
        "command": "cursorWordLeft",
        "when": "calva:cursorAfterComment && editorLangId == 'clojure' || calva:keybindingsEnabled && config.calva.paredit.hijackVSCodeDefaults && editorTextFocus && !calva:cursorInComment && editorLangId == 'clojure' && paredit:keyMap =~ /original|strict/"
    },
    {
        "key": "ctrl+alt+left",
        "command": "paredit.backwardSexp",
        "when": "calva:keybindingsEnabled && editorTextFocus && editorLangId == 'clojure' && paredit:keyMap =~ /original|strict/"
    },
```
