### ISSUE TITLE
Align behavior of backspace in paredit with other editors (Cursive, Emacs)

### ISSUE THREAD

**Issue by isaksky** [BetterThanTomorrow/calva#1741]
When your code+cursor is like this:

```
(defn nil-if-blank [s]
  (if (str/blank? s) 
    |
    nil s))
```

and you press backspace, your code and cursor should look like this afterwards:

```
(defn nil-if-blank [s]
  (if (str/blank? s) |
    nil s))
```

Currently, you get this:

```
(defn nil-if-blank [s]
  (if (str/blank? s) 
   |
    nil s))
```

That isn't helpful in paredit mode, because one would never want to start writing anything at an incorrect indentation level. Changing the behavior of Calva to do this would make it match Cursive and Emacs, and wouldn't harm anyone's ability to write correct code.

As for what the Calva code would need to do, I think it is this:

1. If: on your cursors line, everything to the left of the cursor is whitespace
2. And your cursor is not inside a string literal
3. Then backspace does this: 
    - Deletes all whitespace to the left of the cursor
    - Deletes a newline, going to the end of the previous line
    - Trims all trailing whitespace
    - Inserts one space if that line is not blank

[Slack discussion](https://clojurians.slack.com/archives/CBE668G4R/p1653581016040119)

**Comment by PEZ** [comment]
Thanks for this issue! 🙏 

> ```clojure
> (defn nil-if-blank [s]
>  (if (str/blank? s) |
>    nil s))
> ```

I think that space will be up to the formatter settings, because Paredit commands in Calva end with a formatting of the current enclosing form. With the default settings it will become:

```clojure
(defn nil-if-blank [s]
  (if (str/blank? s)|
    nil s))
```

Also I wonder about this case:


```clojure
(defn nil-if-blank [s]
  (if (str/blank? s) 
    |; comment
    nil s))
```

I can imagine the user intending to move the comment to the left rather than up to the previous line. I think it's better that the user uses regular VS Code commands for deleting to the start of the line in that case.

Yet another case is if there is a selection:

```clojure
(defn nil-if-blank [s]
  (if (str/blank? s) 
   |>| |>|
    nil s))
```

Then I think that selection should be deleted, rather than the deleting up to the end of the previous line.

**Comment by isaksky** [comment]
> I think that space will be up to the formatter settings, because Paredit commands in Calva end with a formatting of the current enclosing form. With the default settings it will become

Ah I see. That is not ideal, because the idea is that you should be ready to type the next form. But is formatting the current enclosed form required or desirable? Cursive (and I think Emacs) only does that when structural changes happens, e.g., if you slurp/barf/enclose/etc. Here is an example of the enclosing form not getting reformatted despite backspace being hit:

![idea64_q44S2zVGTp](https://user-images.githubusercontent.com/607986/170574223-f553fa53-4162-4c52-9415-bbdfd60eae64.gif)


> I can imagine the user intending to move the comment to the left rather than up to the previous line. I think it's better that the user uses regular VS Code commands for deleting to the start of the line in that case.

That is true, I see that matches Cursive also. But they have an exception if the comment is already at the right indentation level. Do you agree with that exception?

>Yet another case is if there is a selection:

Yea, good point.
