### ISSUE TITLE
Support use a nightly clojure-lsp

### ISSUE THREAD

**Issue by ericdallo** [BetterThanTomorrow/calva#1746]
It'd be really nice if we could tell calva to use the latest nightly build of clojure-lsp, maybe on the same existing setting CLOJURE_LSP_VERSION, when the value is NIGHTLY or something.

The nightly builds area available on github builds, but you can use the link just like [here](https://clojurians.slack.com/archives/C032YH7P0R2/p1653750495501089)

Thread: https://clojurians.slack.com/archives/C032YH7P0R2/p1653750050858089?thread_ts=1653749719.246089&cid=C032YH7P0R2

**Comment by PEZ** [comment]
My first attempt trying to implement this failed, when starting. https://github.com/BetterThanTomorrow/calva/pull/1750

The binary inside the zip file is not executable. If I `chmod +x` on it, it starts. I'd rather not have to do this, because Windows and generally just would rather be treating this almost exactly as the other builds. Can you make it so that the binary is executable inside the zip, @ericdallo ?

**Comment by ericdallo** [comment]
I'd love to @PEZ, but it's a GitHub actions issues, the binary loses its permissions when uploading it, there is a open issue with lots of people complaining I can't easily find it right now.
Although, the release binaries have the same issue I think?

**Comment by PEZ** [comment]
Strangely enough it works with the release builds.

**Comment by ericdallo** [comment]
I think the issue is on the Github Action that upload to the action summary (nightly) not the one that upload to releases

**Comment by PEZ** [comment]
The server-info for the latest nightly build reports:

```
"server-version": "2022.05.23-13.18.11",
```

That's a bit confusing. I was wondering if I am really using the right build. But it also reports:

```
  "clj-kondo-version": "2022.05.29",
```

So I guess it is OK.

**Comment by ericdallo** [comment]
Yeah, ATM the nightly build reports the same as the latest release, it'd be nice to show that is a nightly indeed, feel free to create a issue on clojure-lsp for that

**Comment by PEZ** [comment]
There was an issue already. 😄 

* https://github.com/clojure-lsp/clojure-lsp/issues/889
