### ISSUE TITLE
Auto-Indentation for `deftype` is slightly off

### ISSUE THREAD

**Issue by bowbahdoe** [BetterThanTomorrow/calva#1751]
![deftype indent](https://user-images.githubusercontent.com/5004262/171010751-a197a3f9-7286-49db-a8d3-5bb0d5675bce.gif)

Pressing tab to format, I would expect the opening `[` and the `(` of the methods to stay in the same column

**Comment by PEZ** [comment]
Hi there!

It's a bit unclear what you expect should happen. Can you show with some text (not images) what you expect and what you get instead?

I tested with `cljfmt` and a file I named `deftype.clj`:

```clojure
(deftype
 Name
 [fields]
  Protocol)
```

```
 % clojure -Sdeps '{:deps {cljfmt {:mvn/version "0.8.0"}}}' -m cljfmt.main check deftype.clj
WARNING: Implicit use of clojure.main with options is deprecated, use -M
All source files formatted correctly
```

So at least we know that the format you get after pressing `tab` is what cljfmt does by default. Depending on how you would want it formatted, you might need to customize the indentation.

I do see one weird behaviour when I try this. It's that the indentation after pressing enter on after `(deftype` is two spaces in. Is that the error you are reporting?

**Comment by bowbahdoe** [comment]
If I have this

```clojure
(deftype
  BoxImpl
  [^:unsynchronized-mutable val]
  Box
  (box-set [this v]
    (set! (. this -val) v))
  (box-get
    [_]
    val))
```

And I press tab, I expect nothing to happen.

Instead it turns into this

```clojure
(deftype
 BoxImpl
 [^:unsynchronized-mutable val]
  Box
  (box-set [this v]
    (set! (. this -val) v))
  (box-get
    [_]
    val))
```

which messes with parinfer in other editors (multi-dev codebase problems, etc)

<img width="265" alt="image" src="https://user-images.githubusercontent.com/5004262/171035304-8a8e72c7-eb7b-449a-9f05-33768a0db32c.png">

Alternatively it would make sense for two spaces to be replaced by one space consistently 

```clojure
(deftype
 BoxImpl
 [^:unsynchronized-mutable val]
 Box
 (box-set [this v]
   (set! (. this -val) v))
 (box-get
   [_]
```

**Comment by PEZ** [comment]
Closing this, because there is an upstream issue we have little control over. I don't know I managed to get across that this change request should go on cljfmt. And that you can change things for yourself by configuring indents as you want/need them to work.
