### ISSUE TITLE
Allow show evaluation output somewhere else instead of the repl window

### ISSUE THREAD

**Issue by ghost** [BetterThanTomorrow/calva#1767]
In improving my workflow, I am thinking about ditching the interactive repl pane and use it only when very necessary.  

However, one thing annoying when hidding the repl is that, say if I do a calva evaulate current file and if something bad happens, e.g., thrown exception, I can only go to the repl to see what’s going on.

I think if it would be better to also show the output somewhere inside the bottom part of vscode (see figure). Possible? Or any better approach?

Slack thread: https://clojurians.slack.com/archives/CBE668G4R/p1654870103815189

**Comment by bpringe** [comment]
I think we could narrow the scope of this to be about errors. Here are some ideas:

a. Show errors somewhere else, including the stack trace
b. Alert the user that there was an error somewhere else, but instruct them to view the error details in the output window, OR open the output window automatically when there is an error.

We could use the Calva says output window for showing errors or for informing the user that there is an error, but the user would either need to have _this_ pane open or we'd have to open it automatically (same problem as with the output window, sort of).

With the above in mind, maybe it's best to indicate a load-file error in the status bar, or with an error popup. The error pop up gives us the ability to explain more in a more convenient way than the status bar, and is more obvious to the user (they might not notice the status bar indicator), plus we can add a button to it to open the output window.

I think @PEZ likes to avoid pop up messages, and I think that's a good idea for something that happens often, but I think if we're just talking about load-file in particular (after all, we can already tell if errors occur when evaluating individual forms in the file), then a pop up message would actually work nicely for this.

**Comment by PEZ** [comment]
I'm leaning towards an error pop-up giving some context and with a button taking you to the output window for more info/stack trace. For all the reasons you mention, @bpringe.
