### ISSUE TITLE
Paredit strict backspace in the leftmost symbol/keyword/thing inserts a space instead

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1771]
Briefly, the problem is that when you press backspace in this form:

(if• :|foo)

It inserts a space between `:` and `f`, instead of just deleting the `:`. This is because the `onlyWhitespaceLeftOfCursor` that was being used to guard the new backspace on whitespace behavior function didn't verify that you were not deeply inside the current token (as opposed to just touching the left edge).

**Comment by PEZ** [comment]
This is being addressed by @isaksky , here:

* #1768

**Comment by kees-** [comment]
Hi, I'll open another issue if preferred but I'm finding this behavior elsewhere, when trying to use `)` to skip past a **nested** matched closing paren in strict mode.

Skipping over a single matched closing paren with `)` works fine.
![single](https://user-images.githubusercontent.com/6820950/175649307-b77930b4-bca0-48d0-82fd-98e8925e175b.gif)

Spaces are added when pressing `)` to skip a paren that is nested. Doing so with the top-level paren removes all the spaces in some instances.
![nested](https://user-images.githubusercontent.com/6820950/175651363-65ada6d8-16c2-4f43-bb3c-b1f9c3a97615.gif)

Same goes for all collection syntaxes `()` `[]` `{}` `#{}`

**Comment by bpringe** [comment]
@kees- Thanks for reporting this. Please create a new issue.

**Comment by kees-** [comment]
Sure thing. #1787
