### ISSUE TITLE
Backspacing an open paren in paredit strict mode leaves the closing paren, causing unbalanced code

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1776]
I don't know if this is intended or not, but I'm pretty sure Calva used to remove the closing paren when the opening one was deleted.

**Comment by PEZ** [comment]
I can't reproduce this. Can you provide a repro, @bpringe?

**Comment by bpringe** [comment]
It's not happening for me now... I'll see if this comes up again later.

On a sort of unrelated note - I have a question: Is the closing paren suppose to not be removed when backspace is pressed with the cursor to the right of it, to prevent unbalancing, or was a change made to make backspace delete the closing paren for some reason? For me, the closing paren is deleted, whereas it used to be skipped over when in paredit strict mode.

https://user-images.githubusercontent.com/12722744/175837304-c3f9e0c9-ee2b-41de-8742-01f949be2194.mov

**Comment by PEZ** [comment]
Very strange. I can't reproduce that either. We haven't intentionally changed this behaviour. We seem to have a regression here, even if it seems a bit elusive...

**Comment by bpringe** [comment]
I think my `calva.paredit.defaultKeyMap` setting was set to `"original"` 😑. I'll close this. 😄
