### ISSUE TITLE
Getting Started page doesn't tell you how to actually get started

### ISSUE THREAD

**Issue by puredanger** [BetterThanTomorrow/calva#1778]
Everything on https://calva.io drives you towards https://calva.io/getting-started/ ("Let's start a REPL!", "Start here", etc).

The Getting Started page does not mention or link anywhere (afaict) how to download or install VS Code or Calva, which is confusing to me. The video is primary above the fold and called "Get Started with Clojure in VS Code in 20 seconds" but assumes you've already done those steps.

**Comment by PEZ** [comment]
Thanks for looking at this and giving feedback! I'll take a look at these and see what can be done in short term as well as what should be really be done to make it comfortable and enjoyable to take these first steps.

I have intended to do a new Get Started with Clojure video sometime soon. Hesitating if I should use the browse based setup or desktop VS Code, but am leaning towards using both in some way, and will not skip the ”Installing Calva” step then.

I'm also thinking I want two videos:

* Get Started with Clojure
* Get Started with Calva

And figure out some good way to help users find the right entry point for them.

Any thoughts on this?

A related issue is how to not end up at dead end left to your own figuring out how to create a simple project, like the users are today...

* #1779
