### ISSUE TITLE
[2.0] Calva crashes on a second Jack-in

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#178]
When restarting the Jack-in process, Calva crashes.

Repro:
* Jack-in
* Wait until the task output says it has started an nREPL server
* Jack-in
* Wait a little while
* BOOM!

**Comment by xanatos1992** [comment]
On windows i found out that even when i close the repl and the terminal from the jack-in
i have a running jvm aka zombie process that gets not closed

i guess that could be a problem related to this

**Comment by PEZ** [comment]
That's very bad news. It does not happen for me on Mac. Hopefully there is something with the Task config that can fix it for Windows.

However, this crash was due to something else and is now fixed in the `dev` branch. Can you file the zombie thing as a separate issue, please?
