### ISSUE TITLE
[2.0] Pretty printing is broken

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#179]
This might be the case for the currently released Calva as well. In any case. We need to get pretty printing back and working. Also taking #141 into consideration.

**Comment by bbatsov** [comment]
That should be trivial with nREPL 0.6+. All you need it to pass some of the printer functions bundled with cider-nrepl for the requests that originate from the REPL (I assume you don't want the pretty printing for inline evaluations). Not sure if you're using result streaming already, but you should definitely do this as well - it ensure much faster feedback for the users for big results.

**Comment by bbatsov** [comment]
Everything you need to know is here https://nrepl.org/nrepl/0.6.0/design/middleware.html#_pretty_printing

**Comment by PEZ** [comment]
Thanks for the push, @bbatsov. It was indeed quite trivial. I started out with regular `clojure.pprint` until I've figured out how to deal with the other printers and the dependencies for them.

Also, right now, no pretty printing in the repl window yet. I need to ponder about the UI for that some...

**Comment by bbatsov** [comment]
> Thanks for the push, @bbatsov. It was indeed quite trivial. I started out with regular clojure.pprint until I've figured out how to deal with the other printers and the dependencies for them.

You don't really need to worry about the deps, as they are part of `cider-nrepl` anyways. Things here work out of the box. I'd just add some configuration option for Calva users to pick one of them. Generally `fipp` seems like a pretty reasonable default (it's the default in CIDER).

> Also, right now, no pretty printing in the repl window yet. I need to ponder about the UI for that some...

Why do you need a special UI for that? In the REPL you just dump the pretty-printed result and you're in business. In CIDER it's just a toggle - enable/disabled for REPL (on by default).

**Comment by PEZ** [comment]
I didn't get anything other than `clojure.pprint` to work without also adding dependencies. Maybe I did something wrong. I'll experiment a bit more with it.

Also I am a bit unsure about the value added by making this configurable. If `fipp` is good, and I don't have to add deps for it, then I just might go for that. Thoughts on that?

Regarding UI. I didn't say ”special”, did I? :smile: Rather what you are describing with CIDER. Wether it should be a toggle or separate commands.

**Comment by bbatsov** [comment]
> I didn't get anything other than clojure.pprint to work without also adding dependencies. Maybe I did something wrong. I'll experiment a bit more with it.

That's really weird. As you can see `cider-nrepl` actually depends on all the popular pprint libraries that exist. 

> Also I am a bit unsure about the value added by making this configurable. If fipp is good, and I don't have to add deps for it, then I just might go for that. Thoughts on that?

As I said - it's a safe choice and I doubt that anyone's going to complain about it. CIDER has just historically made everything configurable. :-)

> Regarding UI. I didn't say ”special”, did I? 😄 Rather what you are describing with CIDER. Wether it should be a toggle or separate commands.

I think that even if just enabled it unconditionally no one is going to complain about it. In a REPL pprinting definitely is a sound default behaviour. It has been the default in CIDER for a while and no one ever suggested turning it off by default.

**Comment by PEZ** [comment]
> I think that even if just enabled it unconditionally no one is going to complain about it.

I have a user that would complain loudly, actually. But making it the default sounds very reasonable.

**Comment by PEZ** [comment]
> > I didn't get anything other than clojure.pprint to work without also adding dependencies. Maybe I did something wrong. I'll experiment a bit more with it.

> That's really weird. As you can see cider-nrepl actually depends on all the popular pprint libraries that exist.

So, I lied. I had only tested `zprint`, which gives me the error: `(FileNotFoundException) at clojure.lang.RT/load (RT.java:466).
Could not locate zprint/core__init.class, zprint/core.clj or zprint/core.cljc on classpath.` Unless I include `zprint` as a dependency.

With `fipp` everything is dandy. 😃

**Comment by bbatsov** [comment]
Roger that! Now I remembered that we added zprint only in the unreleased cider-nrepl 0.22. Sorry about the mixup!

**Comment by bbatsov** [comment]
Yeah, I just remembered we've added zprint only in cider-nrepl 0.22. My bad!
