### ISSUE TITLE
Command not found error shown when clojure-lsp server info command is run

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1790]
While clojure-lsp is running, when I run the command to get the server info, I get an error:

![image](https://user-images.githubusercontent.com/12722744/176483126-3832974a-4580-4445-94c2-a007a8365a2c.png)

**Comment by PEZ** [comment]
I can't reproduce this. I've seen similar issues many times when some part of Calva has failed to initialize, so maybe that could be what happens here.

**Comment by bpringe** [comment]
That's odd that you can't reproduce it, because the command name in package.json isn't being registered in the code. (Well, it is now on dev via the linked PR).
