### ISSUE TITLE
Support user-extended cljs repl types

### ISSUE THREAD

**Issue by SevereOverfl0w** [BetterThanTomorrow/calva#180]
Edge uses figwheel/figwheel-main via an API, so doesn't work directly with the built-in configuration for those repl types.

CIDER allows changing the set via appending to `cider-cljs-repl-types` which takes a string which is the code to execute for that REPL.
In Edge, that is `"(do (require 'dev-extras) ((resolve 'dev-extras/cljs-repl)))"`

If VSCode/Calva supports a "project-local configuration" it would be useful if this repl could be added via that mechanism.
If not, I'm sure the Edge documentation can include instructions for Calva users.

**Comment by PEZ** [comment]
Is this solved now, you'd say, @SevereOverfl0w ?

**Comment by SevereOverfl0w** [comment]
Yeah!
