### ISSUE TITLE
How to remove Margin (line number column) from Calva REPL window

### ISSUE THREAD

**Issue by skylize** [BetterThanTomorrow/calva#1802]
Documenting this VS Code UI tweak in case someone else finds it useful:

1. Install the [Customize UI extension](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui) (and ensure it works correctly).
2. Add the following styles to your `settings.json` file to remove line numbers only for repl, and save.
3. Restart or reload the window for effect. (You should get a notification with a `Reload` button after saving. Otherwise `Reload Window` from the Command Palette.)

```js
{
...
    "customizeUI.stylesheet": {
        // Hide margin (aka number column) only in Calva Repl windows.
        "[data-uri*=\"output.calva-repl\"] .margin":
            "display: none",
        // Set `left` to move Calva repl text near left edge.
        // Set `width` accordingly to realign scrollbar back to the right edge.
        "[data-uri*=\"output.calva-repl\"] .monaco-scrollable-element":
            "left: 8px !important; width: calc(100% - 8px) !important",
    }
...
}
```

---
Notes: 
* If you have `editor.wordWrap` set to `off` or `wordWrapColumn`, this is extremely effective at taking back wasted screen real estate. 👍🏻 

* Unfortunately it is less impressive if `editor.wordWrap` is set to `on` or `bounded`. VS Code prints each line as a separate div, without first consulting the DOM to check how much space is available. No matter how much space we create, we get the exact same number of characters per line.

    This is still mildly useful because line numbers are meaningless noise in this context. In such case, you probably want 47px instead of 8px (`"left: 47px !important; width: calc(100% - 47px) !important"`), which more-or-less centers the area of visible text within the Editor.

**Comment by skylize** [comment]
😸

**Comment by PEZ** [comment]
Thanks for sharing this recipe! Another way to hide the line numbers in the Output Window is to use [Joyride](https://github.com/BetterThanTomorrow/joyride) and a snippet like this:

```clojure
(set! (.-cursorStyle vscode/window.activeTextEditor.options) 2)
```

What's lacking here is how to target the right window. The [`workspace_activate.cljs` example](https://github.com/BetterThanTomorrow/joyride/blob/master/examples/.joyride/scripts/workspace_activate.cljs) has the setup for doing things when documents are opened, where I think this could be done.

**Comment by skylize** [comment]
@PEZ I had no idea of the existence of Joyride. That looks pretty awesome!

Looks like your idea (assuming we can get it applied only to the correct editor) should improve on my recipe for the case of `on` or `bounded` Word Wrap, by freeing up 3? characters of space that VS Code can actually write into. 

Unfortunately doesn't seem like there is a similar per-editor option for the glyph margin. So we still have an oversized gap on the left side that needs to be styled away in all cases.

**Comment by holyjak** [comment]
PEZ Shared another snippet that might help:

```clj
; (require '["vscode" :as vscode]) ; might be necessary ???
(set! (.-lineNumbers vscode/window.activeTextEditor.options) 0)
```

**Comment by PEZ** [comment]
Thanks for updating here, @holyjak . I think it might be that snippet I intended to include [above](#issuecomment-1186137114). 😄

**Comment by holyjak** [comment]
I have tried to do this with Joyride but there are some timing issues preventing me from succeeding. Namely when the `output.calva-repl` text document is opened, the corresponding text editor is not yet in the `window.visibleTextEditors` (at least sometimes). From inside the main in my user_activate.cljs script:

```clj
(vscode/workspace.onDidOpenTextDocument
    (fn [doc]
      (when (str/ends-with? (.-fileName doc) "/.calva/output-window/output.calva-repl")
        (let [repl-editor
              (->> vscode/window.visibleTextEditors
               ;(filter #(-> % .-document .-fileName (str/ends-with? "/.calva/output-window/output.calva-repl")))
                   (filter #(= (-> % .-document .-fileName) (.-fileName doc)))
                   first)
              names (map #(-> % .-document .-fileName) vscode/window.visibleTextEditors)]
          (.appendLine (joyride/output-channel) (pr-str "on-opened-doc-hide-repl-linenums editor = " repl-editor names))
         ; this above prints repl-editor as nil, names as (".../user_activate.cljs" "extension-output-betterthantomorrow.joyride-#1-Joyride")
          (set! (.-lineNumbers (.-options repl-editor)) 0)))))
```
