### ISSUE TITLE
Wrong 'when condition' for command 'paredit.togglemode'

### ISSUE THREAD

**Issue by acorello** [BetterThanTomorrow/calva#1804]
I tried to remap the command 'Calva Paredit: Toggle Paredit Mode' and found my keybinding was not working. Entering VSCode 'Keyboard Shortcut Troubleshooting' mode revealed the 'when condition' of the command was not succeding.

The default configuration is the folloing. 

```json
{
  "key": "ctrl+alt+p ctrl+alt+m",
  "command": "paredit.togglemode",
  "when": "editorLangId == 'clojure' && editorLangId == 'clojure calva:keybindingsEnabled' && paredit:keyMap =~ /original|strict/"
}
```

I guess it should instead be:

```json
{
  "key": "ctrl+alt+p ctrl+alt+m",
  "command": "paredit.togglemode",
  "when": "editorLangId == 'clojure' && calva:keybindingsEnabled && paredit:keyMap =~ /original|strict/"
}
```

**Comment by PEZ** [comment]
Thanks! Care to crate a PR with that fix? I think it might explain some strange behaviour I have experienced...

**Comment by acorello** [comment]
@PEZ sure! I'll have a look. Sorry for the late replay, I didn't notice your comment.
