### ISSUE TITLE
function highlight missing signature info

### ISSUE THREAD

**Issue by claudiu-apetrei** [BetterThanTomorrow/calva#181]
https://github.com/BetterThanTomorrow/calva/blob/master/assets/howto/features.gif
In the features gif from the readme the highlight contains signature information, but in the current calva version it only shows the function docstring (ex: hover over `map` or `defn`)

**Comment by rexwangcc** [comment]
I was able to view the signature info by holding the `command ⌘` button, in case it helps.

**Comment by bpringe** [comment]
@PEZ This is working for me in latest (2.0.55). Can this be closed?
