### ISSUE TITLE
Missing support for core.logic

### ISSUE THREAD

**Issue by dokutan** [BetterThanTomorrow/calva#1816]
When using [core.logic](https://github.com/clojure/core.logic) expressions, calva:
- fails to correctly indent the code
- fails to correctly highlight symbols (``q`` and ``a`` in the example)
- marks newly introduced symbols as unresolved (``q`` and ``a`` in the example)

For example:
```
(run* [q]
      (fresh [a]
             (== a q)))
```

The fix would be to treat ``fresh``, ``run*`` and similar similarly to ``fn``.

**Comment by bpringe** [comment]
I think you can fix all or at least 2 of those points (maybe only except for the indenting) in your clj-kondo configuration, by telling it to lint `fresh`, and `run*` as `fn`. I'm not certain that will fix it but it's worth a try. Calva uses clojure-lsp for some functionality, which uses clj-kondo to analyze the code.

**Comment by dokutan** [comment]
> I think you can fix all or at least 2 of those points (maybe only except for the indenting) in your clj-kondo configuration

Thanks, that fixed the errors and syntax highlighting, the indentation is still wrong.
In case someone else has this problem, i created ``.clj-kondo/logic/logic/config.edn`` containing
```
{:lint-as
 {clojure.core.logic/run clojure.core/fn
  clojure.core.logic/run* clojure.core/fn
  clojure.core.logic/fresh clojure.core/fn}}
```

Edit: i fixed the indentation as described in the [documentation](https://calva.io/formatting/#configuration), ``.cljfmt.edn`` contains:
```
{:indents {run [[:inner 0]]
           run* [[:inner 0]]
           fresh [[:inner 0]]}}
```
and the ``calva.fmt.configPath`` setting in VS Code is set to ``.cljfmt.edn``.
