### ISSUE TITLE
Two references to the same class in the same namespace can refer to two different instances of the class

### ISSUE THREAD

**Issue by dchelimsky** [BetterThanTomorrow/calva#1821]
I ran into an issue in which tests run were passing the first time I ran them and then consistently failing any subsequent test runs in the same process. I narrowed this down to some surprising behavior when reevaluating a namespace with a class declaration (`defrecord`) and references to the class: two different references to the class point at different instances of the class. This only happens when using VSCode+Calva+leiningen.

Deps and tools

- VSCode 1.70.0
- Calva v2.0.291
- nrepl/nrepl 0.9.0
- cider/cider-nrepl 0.28.5
- leiningen 2.9.8
- Java 11.0.11

Minimal repro here: https://github.com/dchelimsky/calva-leiningen-test-oddity

**Comment by Cyrik** [comment]
Even two classes with the same class file can be different, according to the jvm, if they are loaded by a different class loader. I have no idea how leinigen works, but I'd bet it's related to this oddity.

**Comment by dchelimsky** [comment]
Thanks @Cyrik. I think you're right that it's likely a classloader issue. The weird thing is that using Leiningen with IntelliJ or emacs doesn't produce this same behavior.

**Comment by bpringe** [comment]
Thanks for the detailed repro, @dchelimsky. I think this is caused by Calva loading the file before running the tests. If I comment out this line, I consistently get the same id's for the record each time: https://github.com/BetterThanTomorrow/calva/blob/c546793a10eda223982cd8a030fe2d341393adf5/src/testRunner.ts#L298

@PEZ Is loadFile just run as a convenience to the user to remove the need to save the file for changes to be included in the test run? I'm wondering if it's a good idea to remove the call to loadFile.

In case anyone is wondering about the comment above that referenced line, I did try passing `document` to loadFile but the same issue was observed.

**Comment by bpringe** [comment]
Also, for the record, I had to add clojure to the deps in project.clj in order for the jack-in terminal command to not throw an error about clojure.main not being found. @dchelimsky, do you have clojure in your lein user profile as a dep? It's not really related to the issue, I'm just wondering, and wanted to state what I had to do here in case someone else tries to run the repo and hits that issue.

**Comment by dchelimsky** [comment]
@bpringe thanks for pointing that out. You're correct that the clojure dep was coming from my lein profiles. I [added it to the repro repo](https://github.com/dchelimsky/calva-leiningen-test-oddity/blob/7d0bb3a34fcade7b2aaad327d32ea24289ea32d6/project.clj#L2) and, for good measure, eliminated all deps and plugins in my lein profiles file and the behavior persisted.

**Comment by dchelimsky** [comment]
> I think this is caused by Calva loading the file before running the tests.

It reloads the file when using tools.deps (deps.edn), also, in which case the IDs change from test run to test run, but they are consistent within each run.

**Comment by bpringe** [comment]
Thanks. At least if we remove the loading of the file before running tests there will be consistent behavior between build tools (I suspect). Is this causing you any issues with how your tests are set up? I'm wondering if there's really a problem to solve here, or at least one that is worth solving and losing the small benefit of changes being picked up on test runs without needing to save the file.

**Comment by dchelimsky** [comment]
I'm accustomed to eval'ing forms as I change them, and reloading namespaces when I want to. My preference is to have the control, but that's just me.

**Comment by bpringe** [comment]
I think we should probably stop loading the file before running tests then, as doing so seems it could cause more confusion than not.

**Comment by PEZ** [comment]
I'm totally on @dchelimsky's page here. I want to be in control of loading and reloading namespaces. Calva shouldn't be doing that magically.

**Comment by dchelimsky** [comment]
Thank you!

**Comment by bpringe** [comment]
No problem!
