### ISSUE TITLE
Clojure Notebooks

### ISSUE THREAD

**Issue by Cyrik** [BetterThanTomorrow/calva#1824]
My initial idea is to have a “open this clojure file as a notebook” context menu and have every top-level expression be a code cell and every comment markdown cell. Mostly the same stuff clerk is already doing. The advantage of having this inside Calva would be interaction with all the other Calva stuff and Calva itself would gain a rich inline eval output space.

So my vision is less of a data science notebook that you pass around to other people, although that’s still possible, and more of a deeper integration of eval stuff. Basically mini portal inline windows or similar. If I could just do that in the normal text view, I’d keep it there, but we’re not allowed to have full html in there.

**Comment by PEZ** [comment]
I also find the big win here to be how we can make the evaluation/result support better.

**Comment by bpringe** [comment]
I don't think there's a commit in the linked PR using the closes syntax, so we may need to close this manually once it's released. I do see the closes syntax in the PR but that has seemed to not work on its own before.

**Comment by Cyrik** [comment]
I put the "Closes" syntax into the squash commit. Let's see if that works 😄
