### ISSUE TITLE
`calva.fmt.formatAsYouType` setting seems redundant

### ISSUE THREAD

**Issue by zakkor** [BetterThanTomorrow/calva#1827]
This setting achieves the same thing as the following built-in VSCode setting:
```
 "[clojure]": {
    "editor.formatOnType": false,
  },
```

I think the fix here could be to remove the `calva.fmt.formatAsYouType` setting, if there is really no difference between the two.

**Comment by PEZ** [comment]
This setting is bound to cause confusion. I can't recall why it is there. Let's remove it. Let us know if you want to do it, @zakkor.
