### ISSUE TITLE
Calva starts automatically even in non-Clojure(script) workspaces

### ISSUE THREAD

**Issue by danielkarch** [BetterThanTomorrow/calva#1830]
Hi, I noticed that Calva starts up automatically whenever I open VSCode (`v1.7.0.1`), even when I open it in an empty directory. 

I would expect that Calva only starts up when there are files in the workspace that are somehow related to Clojure development (`.clj`, `.cljs`, `.edn`, ...).

This affects Calva `v2.0.291` and only happens when Joyride is also installed (`v0.0.15` here), both were installed via the standard VS Code extension dialog.

**Comment by PEZ** [comment]
Thanks! Can you check your Joyride `user_activate.cljs` script and see if you are activating Calva there?

**Comment by danielkarch** [comment]
This indeed seems to be the case
```
(defn- my-main []                                                                                               [5/80]
  (println "Hello World, from my-main in user_activate.cljs script")                                                  
  (clear-disposables!) ;; Any disposables add with `push-disposable!`                                                 
                       ;; will be cleared now. You can push them anew.                                                
                                                                                                                      
  ;;; MARK require VS Code extensions                                                                                 
  ;; In an activation.cljs script it can't be guaranteed that a
  ;; particular extension is active, so we can't safely `(:require ..)`
  ;; in the `ns` form. Here's what you can do instead, using Calva
  ;; as the example. To try it for real, copy the example scripts from:
  ;; https://github.com/BetterThanTomorrow/joyride/tree/master/examples 
  ;; Then un-ignore the forms in the promise handler and run
  ;;   *Joyride; Run User Script* -> activate.cljs
  ;; (Or reload the VS Code window.)
  (-> (vscode/extensions.getExtension "betterthantomorrow.calva")
      ;; Force the Calva extension to activate 
      (.activate)
...
```
Note that I did not change/edit anything, I just installed Joyride via VSCode.

**Comment by PEZ** [comment]
Then I think you had the bad luck of installing Joyride at a moment where it didn't have that activation default disabled. The script looks like so now: https://github.com/BetterThanTomorrow/joyride/blob/master/assets/getting-started-content/user/user_activate.cljs

**Comment by danielkarch** [comment]
Thanks!
This is `master` though, if I reinstall the latest published version I will not see any difference, will I?

**Comment by PEZ** [comment]
Joyride will not overwrite an existing user script. Replace the script or edit it is the best way.

**Comment by PEZ** [comment]
Fixed with https://github.com/BetterThanTomorrow/joyride/pull/86
