### ISSUE TITLE
Feature Request: color customization for inline result

### ISSUE THREAD

**Issue by maksimr** [BetterThanTomorrow/calva#1831]
It would be nice to have the possibility to customize color for inline result like it does gitlens for inline blame

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/616193/185307813-c3e9ec7f-9c72-49a5-b1e6-8e350803c4ea.png">

**Comment by PEZ** [comment]
Hi! Thanks for this suggestion. And for #1832 implementing it.

I'm often a bit weary of surfacing settings/configuration areas, but this one makes a lot of sense to me, so I am going to allow it. (We also have some existing styling configuration that would benefit from this approach, but that's for later.)
