### ISSUE TITLE
git: staged file gets evaluated instead of uncommitted file

### ISSUE THREAD

**Issue by ccidral** [BetterThanTomorrow/calva#1833]
I started experiencing this issue a couple of days ago. Apparently it's related to vscode's git extension. This is the procedure to reproduce the problem.

1. Run nREPL on some Clojure project that has a git repo.
2. Open the project in vscode.
3. Connect to nREPL.
4. Open any file that has uncommitted changes **and** is staged.
5. Run the "Calva: Load/evaluate current file" command.
6. Verify somehow that the uncommitted version of the file was evaluated.
7. Close the file.
8. Go to Source Control.
9. Click on the file to see the **staged** diffs.
10. In the top right corner there's an Open File button, click on it.
11. Run the "Calva: Load/evaluate current file" command.

What happens is the committed version of the file gets loaded/evaluated instead of the uncommitted version. When I reload vscode, connect and evaluate the file, the uncommitted version gets evaluated correctly.

**Comment by PEZ** [comment]
Thanks for such a wonderfully crafted reproduction. I could immediately reproduce this. I suspect it is a Calva bug and that it could get much nastier than the symptoms exposed here.
