### ISSUE TITLE
Bind any keys to custom custom repl commands

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1853]
We can provide a way to run [custom repl commands](https://calva.io/custom-commands/) bound to any shortcut if we let the user specify the command snippet definition as `args` to the shortcut binding.

It would allow a keybinding like this:

```json
    {
        "key": "ctrl+alt+u alt+enter",
        "command": "calva.runCustomREPLCommand",
        "args": {
            "ns": "user",
            "snippet": "$current-form"
        }
    },
```

This would evaluate the current form in the `user` namespace.

To achieve this today you need to first define a custom repl command snippet in settings, giving it some key, then bind the shortcut providing the key:

settings.json:

```json
    "calva.customREPLCommandSnippets": [
        {
            "name": "Eval Current Form in user NS",
            "key": "eval-current-form-in-user-ns",
            "ns": "user",
            "snippet": "$current-form"
        },
```

keybindings.json:

```json
    {
        "key": "ctrl+alt+u alt+enter",
        "command": "calva.runCustomREPLCommand",
        "args": "eval-current-form-in-user-ns"
    }
```

Another difference between the two implementations would be that with a direct shortcut binding, you  will not get the snippet added to the custom repl commands menu. But you can always define it the second way, if you like.

**Comment by skylize** [comment]
Just a note: I think (assuming other shortcuts set to default) the keyboard shortcut used in this example would better align with `$top-level-form` instead of `$current-form`.

**Comment by PEZ** [comment]
I guess you mean the `alt+enter` part of the chord? Makes sense.
