### ISSUE TITLE
Inline prompt evaluation not visible in Light themes

### ISSUE THREAD

**Issue by marcraminv** [BetterThanTomorrow/calva#1855]
Context: Trying the __Fire Up the Getting REPL__

Possible issue: If users prefer Light themes, the inline prompt will not be visible for them

![Kapture 2022-09-06 at 09 32 43](https://user-images.githubusercontent.com/13021787/188574788-36c35af9-bffc-4d55-84ac-43ef2fd2f803.gif)

**Comment by PEZ** [comment]
Thanks! We are using alpha 0 for the color on light themes 🤦 

Fix on its way!
