### ISSUE TITLE
Files from outside "current project" adds to the problem count

### ISSUE THREAD

**Issue by jacobemcken** [BetterThanTomorrow/calva#1864]
I find the following behavior in Calva (lsp?) a bit annoying:
1. Open your favorite project with fairly few "Problems"
2. Open a file from outside your project to inspect some code
3. See the "problem" count skyrocket :sweat_smile:
4. Close the file outside your project again

Expected behavior:
The "problem" count goes back down, when the file is closed.

Actual behavior:
The problems from the "external" file lingers and now drown my "real" problems.

Workaround:
Restart VS Code.

Also worth noting:
`Clear Document Diagnostics` doesn't seem to work on "outside files". I reopen the problematic outside file in the hope that I can "clear diagnostics" and then quickly close it again before the problems are picked up.

**Comment by PEZ** [comment]
Thanks for reporting!

Pinging @ericdallo. It might be something we need to tell clojure-lsp when that file closes.

As for workarounds. A slightly less dramatic (depending on your usage of VS Code) way is to only reload the current window. One way to do so is to use the command **Developer: Reload Window**. You can even make the REPL survive this by starting it yourself and use Calva Connect instead of Jack-in. VS Code terminals survive window reloads. (Sadly this doesn't go for the Jack-in terminal yet.)

> `Clear Document Diagnostics` doesn't seem to work on "outside files".

TIL. I didn't know about this command. Have been needing it! Anyway, this indicates that it might be a VS Code problem. We'll see.

**Comment by ericdallo** [comment]
I think it makes sense to count the errors while the file is opened but I agree that after receiving a `didClose` on server we should check if it's inside the project and update the diagnostics if not, please open a ticket on clojure-lsp

**Comment by ericdallo** [comment]
Fixed on clojure-lsp master, please test the nightly build

**Comment by jacobemcken** [comment]
I might not understand something, but using a "nightly" does not seem to have fixed the problem.

<img alt="lsp nightly configuration" height="250" width="428" src="https://user-images.githubusercontent.com/1869708/190844704-85173ee2-d373-4f88-9ba7-147208ad6a67.png" />


1. I open my project from the folder `~/Private/Projects/my-project/` in VS Code/Calva with an initial "Problem count" of 2.
2. I open a file outside my project folder `~/Private/Projects/mongo-driver-3/src/mongo_driver_3/operator.clj` (cloned from [Mongo Driver 3][])
4. "Problem count" rise to 363.
5. Upon closing the file, the "Problem count" fall to 176

<img alt="error count before" height="169" width="428" src="https://user-images.githubusercontent.com/1869708/190844720-6fe576ca-ba37-4b9a-8e40-5b3475d03f26.png" />
<img alt="error count after" height="169" width="428" src="https://user-images.githubusercontent.com/1869708/190844723-bb27d139-a006-4e89-821a-615d6db1862a.png" />

Expectation: The "Problem count" would fall to 2 which it was initially.


[Mongo Driver 3]:https://github.com/gnarroway/mongo-driver-3

**Comment by ericdallo** [comment]
@PEZ is that related to Calva not downloading nightly properly?

**Comment by bpringe** [comment]
@ericdallo It might be related. @jacobemcken A new version of Calva was released since your last comment that fixed an issue with the nightly build download. I would try it again and see if the problem persists.

**Comment by jacobemcken** [comment]
Tried again this morning using Calva version [2.0.304] - 2022-09-20.

Same problem (as in: the problem count goes somewhat down, but only around half... see screenshots about for example)

**Comment by jacobemcken** [comment]
@ericdallo do you want me to create an issue over at https://github.com/clojure-lsp/clojure-lsp ?

or is the bug somewhere else?... the nightly did reduce the number of warnings (see above screenshots).

**Comment by ericdallo** [comment]
@jacobemcken is there any repro I can try? The fix I made should fix cases like that

**Comment by jacobemcken** [comment]
Thanks for your patience @ericdallo 
**The bug is fixed.**

The reason why only some linting warnings would disappear once I closed the external file, was because I also had the [clj-kondo VS Code extension installed][1]. I don't know how many months I've been running double linting checks  :scream:

Now that I've uninstalled that clj-kondo, I can verify that `nightly` fixes the issue for me.
:pray: 

[1]: https://marketplace.visualstudio.com/items?itemName=borkdude.clj-kondo

**Comment by ericdallo** [comment]
Good, I think that 's more common that you think.
Maybe we should present some warning when both are installed c/c @PEZ

**Comment by bpringe** [comment]
It appears I thought it was a good idea to remove that warning in the past 😅: https://github.com/BetterThanTomorrow/calva/issues/1091. Sorry @jacobemcken! I think we should add that back...
