### ISSUE TITLE
Download of clojure-lsp nightly build fails on Apple M1/M2

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1869]
The nightly builds are not where Calva is looking for them currently.

**Comment by bpringe** [comment]
Was that PR only about Apple Silicon? It seems it was a general issue, judging by the change in the PR.

**Comment by PEZ** [comment]
The old link still works for the other platforms. The new link has artifacts for all platforms. So, you are right, a general change, but only really makes a difference for Apple Silicon.
