### ISSUE TITLE
[2.0] Doesn't connect to nREPL

### ISSUE THREAD

**Issue by danlucraft** [BetterThanTomorrow/calva#188]
I've been testing out Calva 2 alpha but not been able to make it work in my Clojure project. (As discussed in #calva-dev yesterday.)

This is VSCode 1.34.0, Clojure 1.10, and Calva 2.0.0-SNAPSHOT, installed from VSIX and with a restart of VSCode after installation.

I've reproduced the issue with a minimal test project (this is the example from the official _deps_ docs):

*/deps.edn*
```clojure
{
 :deps {
   clj-time {:mvn/version "0.14.2"}
 }
 :aliases {
    :cider-clj {:extra-deps {cider/cider-nrepl {:mvn/version "0.21.1"}}
                :main-opts ["-m" "nrepl.cmdline" "--middleware" "[cider.nrepl/cider-middleware]"]}}
 }
```

*/src/hello.clj*
```clojure
(ns hello
  (:require [clj-time.core :as t]
            [clj-time.format :as f]))

(defn time-str
  "Returns a string representation of a datetime in the local time zone."
  [dt]
  (f/unparse
    (f/with-zone (f/formatter "hh:mm aa") (t/default-time-zone))
    dt))

(defn -main []
  (println "Hello world, the time is" (time-str (t/now))))
```

The command I'm running to start the REPL is: `$ clj -A:cider-clj`

Issues:

 - Calva prompts for which type of CLJS repl to start. I don't want CLJS so I press escape here, which brings up the normal "localhost:port" textbook, which has spotted the correct port as usual.
 - Calva opens a blank window titled "CLJ REPL" in an editor split
 - It doesn't connect to the REPL.

**Comment by PEZ** [comment]
Thanks! This is very helpful for my fixing of the issue.

Just checking, it works if you use the **jack-in** command, right?

**Comment by danlucraft** [comment]
@PEZ hey, glad to help. I wasn't able to find any docs on how jack-in works (I'm not even really sure what it is...) so haven't tried that. If you can show me some instructions I can have a go.

**Comment by PEZ** [comment]
Yeah, sorry, Cider lingo. There is a command named something like **Start a REPL and connect (a.k.a. Jack-in**. Keyboard shortcut is: `ctrl+alt+c ctrl+alt+j`. So, the idea with that command is that for many projects Calva should be able to start the REPL for you.

**Comment by danlucraft** [comment]
Ah, I see! Ok, so that get's a bit further, in that it opens a REPL tab in which I can type clojure and it executes.

However, I then have the same issues as in the other issue I filed, in that clojure.core and clojure.repl are not available, and go-to-definition doesn't work, until you evaluate the `ns` declaration.

![Screenshot 2019-05-23 at 17 16 21](https://user-images.githubusercontent.com/6118/58269013-7d1e4d80-7d7e-11e9-9d45-24f00fa5ce1e.png)

**Comment by danlucraft** [comment]
Can I ask, if you run this locally with the same project setup, does it work for you?

**Comment by PEZ** [comment]
You are supposed to evaluate/load the file to get it to work. You'll get used to it. =) 

Can you get connect to work with the latest build? (Without jack-in.)

**Comment by danlucraft** [comment]
> You are supposed to evaluate/load the file to get it to work. You'll get used to it. =)

Ah, ok.

> Can you get connect to work with the latest build? (Without jack-in.)

Just checked, it works! It still asks about CLJS but now has a None option that works.

So the only thing remaining for this issue I think is that the REPL (the pretty one on the right) still doesn't import the clojure.repl namespace automatically, neither using Jack-in or connecting manually.

**Comment by PEZ** [comment]
Yes. I'd appreciate a separate issue about that, and then we can close this one.

**Comment by danlucraft** [comment]
@PEZ Will do, thanks for getting it fixed / helping me get it working 😊
