### ISSUE TITLE
Calva should route parsing exceptions into VS Code's linter reporting system

### ISSUE THREAD

**Issue by skylize** [BetterThanTomorrow/calva#1888]

**Comment by PEZ** [comment]
The suggested fix (for the missing problem description) is nice, but given we have the API to do it, there will also be cheaper solutions. I suggest phrasing the issue more as a problem statement than a solution suggestion. And, provide some more context around the issue in the description, where possible solutions also fit well.

**Comment by skylize** [comment]
Incomplete Issue submitted by mistake. Consider this a dup of #1889.
