### ISSUE TITLE
[1.3.66] Various namespace loading issues

### ISSUE THREAD

**Issue by danlucraft** [BetterThanTomorrow/calva#189]
I've had some trouble using Calva as it doesn't seem to load the right namespaces. It's possible to get work done by loading namespaces, but it's very awkward. (As discussed in #calva-dev yesterday.)

This is VSCode 1.34.0, Clojure 1.10, and Calva 1.3.66, with a restart of VSCode after installation.

I've reproduced the issue with a minimal test project (this is the example from the official _deps_ docs):

*/deps.edn*
```clojure
{
 :deps {
   clj-time {:mvn/version "0.14.2"}
 }
 :aliases {
    :cider-clj {:extra-deps {cider/cider-nrepl {:mvn/version "0.21.1"}}
                :main-opts ["-m" "nrepl.cmdline" "--middleware" "[cider.nrepl/cider-middleware]"]}}
 }
```

*/src/hello.clj*
```clojure
(ns hello
  (:require [clj-time.core :as t]
            [clj-time.format :as f]))

(defn time-str
  "Returns a string representation of a datetime in the local time zone."
  [dt]
  (f/unparse
    (f/with-zone (f/formatter "hh:mm aa") (t/default-time-zone))
    dt))

(defn -main []
  (println "Hello world, the time is" (time-str (t/now))))
```

*/test.clj*
```clojure
; empty file
```

The command I'm running to start the REPL is: `$ clj -A:cider-clj`

Issues:

If the file you are in contains a `ns` declaration at the top, then:

 - clojure.core and clojure.repl are not loaded
 - "Go to definition" doesn't work

If the file you're in _doesn't_ have an `ns` declaration, then both these things seem to work.

If you evaluate the `ns` form in your file, then clojure.core is loaded but clojure.repl is not, and you can do go to definition then. (Is it intentional that you have to evaluate the file to get go-to-definition support?)

As this is a bit weird I recorded a video to demo it: https://cl.ly/ae4d46b4d3de

**Comment by PEZ** [comment]
Hello,

The reason it works in the empty file is that it gets evaluated in the `user` namespace, which is magic in Clojure. Other files need to first be evaluated/loaded before things start to work. There is a command for that.

As for the `doc` commands, I'd like a separate issue for that, because it might be something that can be fixed if we just ponder it some. Though, I'd say that doc on hover sort of covers most of the bases.

**Comment by PEZ** [comment]
Closing this now, since the remaining issue is separated out.
