### ISSUE TITLE
trying to jack-in to a legacy figwheel project, a mysterious question dialogue opens up at the top the editor window and won't go away

### ISSUE THREAD

**Issue by jamiepratt** [BetterThanTomorrow/calva#1892]
I'm trying to jack-in to a legacy figwheel project. The clojurescript has compiled but before the cljs REPL will open I get this question and I can't figure out what it wants me to enter, nothing seems to work.
<img width="593" alt="Screenshot 2022-10-11 at 09 55 14" src="https://user-images.githubusercontent.com/558780/195122478-f1a9ad0f-c53b-4e80-b0fd-0f4376517824.png">

**Comment by PEZ** [comment]
This was caused by the `dev` dependency on Figwheel Sidecar 0.5.16. If you use 0.5.18, it will start to work, @jamiepratt. See https://github.com/jsa-aerial/hanami/pull/20 for a working project.clj config.

**Comment by jamiepratt** [comment]
I can confirm legacy figwheel compilation of hanami in Calva is working for me now.
