### ISSUE TITLE
`extension.ts` can be refactored for less boilerplate registering commands

### ISSUE THREAD

**Issue by skylize** [BetterThanTomorrow/calva#1897]
The main-entry file `src/extension.ts` has numerous duplicate calls to `context.subscriptions.push` and duplicate or nearly duplicate calls to `vscode.someScopeOrSubAPI.registerAThing`. What Calva actually provides here is buried inside the boilerplate wrappings of these individual registry calls.

I propose improving this, by gathering related functions together into a small number of collections, keyed on the feature provided (blended with whatever data is needed to determine how to dispatch). Then iterate over the collections to apply registry and disposable storage for each feature.

*-This could also potentially extend to other files with similar behavior, such as* `src/calva-fmt/src/extension.ts`*. Even if so, that is beyond the scope of this issue.*

**Comment by skylize** [comment]
At [L552-556](https://github.com/BetterThanTomorrow/calva/blob/3dac2051bb140b76ba1310c56930a90ce1e7df61/src/extension.ts#L552-L556) of `extension.ts`, we register an `onDidOpenTextDocument` handler. The callback is an inline function that does nothing except call `onDidOpen` at [L65-L69](https://github.com/BetterThanTomorrow/calva/blob/3dac2051bb140b76ba1310c56930a90ce1e7df61/src/extension.ts#L65-L69). And all `onDidOpen` does is an `if` statement that returns an implied `undefined` in all cases, so basically a no-op.

I am assuming there must have been something meaningful here in the past. Or is there some side-benefit to just have anything at all registered as a listener?

Am I safe to just delete this, instead of moving it around, as a part of this issue?

**Comment by PEZ** [comment]
> Am I safe to just delete this, instead of moving it around, as a part of this issue?

Place a TODO comment there and note that it seems to be a noop, linking to ^ that ^ comment. I don't know why it looks like that, but there will be a lot of testing needed if we change it. Since we haven't documented the strange state of that code...

**Comment by skylize** [comment]
`onDidOpen` used to read as follows
```clojure
function onDidOpen(document){
  if (document.languageId !== 'clojure') {
    return;
  }

  EvaluateMiddleWare.evaluateFile(document);
  LintMiddleWare.lintDocument(document);
  TestRunnerMiddleWare.runNamespaceTests(document);
}
```

`evaluateFiddleware` was removed in 8e79d97a
`runNamespaceTests` was commented out in 6203a12a
`lintDocument` was wrapped in with an extra if in `
```

**Comment by skylize** [comment]
`onDidOpen` used to serve as gated entry-point for several functions.

```typescript
function onDidOpen(document){
  if (document.languageId !== 'clojure') {
    return;
  }

  EvaluateMiddleWare.evaluateFile(document);
  LintMiddleWare.lintDocument(document);
  TestRunnerMiddleWare.runNamespaceTests(document);
}
```

* `evaluateMiddleware` was removed in 8e79d97a (Apr 14, 2018)
* `runNamespaceTests` was commented out a few days later in 6203a12a (Apr 17, 2018)
* `runNamespaceTests` was fully removed the next day, while adding an extra gate around `lintDocument`cef54148 (Apr 18, 2018), along with fully removing `runNamespaceTests` 
    ```typescript
     function onDidOpen(document) {
     if (document.languageId !== 'clojure') {
         return;
     }

      if (state.config().lint) {
        LintMiddleWare.lintDocument(document);
      }
    };
    ```
* lintDocument was finally removed in 448c6a74 (Oct 24, 2019), making `onDidOpen` a no-op.

**Comment by PEZ** [comment]
Thanks for the investigation about how that onDidOpen turned into a noop. I now say it's cool to clean it away. 😄
