### ISSUE TITLE
Evaluating an entire file doesn't pretty-print the result of the evaluation

### ISSUE THREAD

**Issue by zakkor** [BetterThanTomorrow/calva#1905]
![image](https://user-images.githubusercontent.com/6191421/196926106-8efadbe6-709a-4831-9035-b9937b46c827.png)

In the picture:

1. An object being evaluated via <kbd>Option+Enter</kbd>
2. The same object being evaluated due to it being the last form in the file, and the entire file being evaluated (either via the explicit  `Calva: Load/Evaluate Current File` command, or via <kbd>Cmd+S</kbd> when "eval on save" is enabled - same result)

**Comment by PEZ** [comment]
Thanks!

We should be pretty printing both (when pretty printing is enabled), I think
