### ISSUE TITLE
Use requirements.txt in CI for publishing docs

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1913]
> Note that we don't use the requirements file in CI. There we just manually `pip install` the things. We probably should use the requirements file, because confusing.

_Originally posted by @PEZ in https://github.com/BetterThanTomorrow/calva/issues/1909#issuecomment-1288555979_

**Comment by PEZ** [comment]
I messed up the fixes syntax, I think. =) 

Anyway, this works now. We might get some merging troubles next time we release, since I needed to get this to published to test it.
