### ISSUE TITLE
Drag sexps in value part of doseq sometimes jumps 2 sexps instead of 1

### ISSUE THREAD

**Issue by maxrothman** [BetterThanTomorrow/calva#1914]
(`|` is the cursor)

```
(doseq [x] [1 2 3 4 |5])
;; Drag sexp backwards

;; Expected behavior
(doseq [x] [1 2 3 |5 4])

;; Actual behavior
(doseq [x] [1 2 |5 3 4])
```

Dragging forward and backwards also acts oddly for other elements in the value list.

https://user-images.githubusercontent.com/2607086/197859676-3b23588d-f9ed-4c28-9bdc-ed9ef9489cdd.mov

**Comment by PEZ** [comment]
Thanks! Not sure, but I think that the drag code is treating it as a binding vector.
