### ISSUE TITLE
Calva: Open REPL snippets User config.edn couldn't create the file if parent folders doesn't exist

### ISSUE THREAD

**Issue by jeff66ruan** [BetterThanTomorrow/calva#1916]
Ran the command but the user config.edn couldn't be created as the calva folder doesn't exists in my environment. This is not expected behavior according to the document. The reason is the fs.promises.writeFile couldn't create the file if the parent folder doesn't exist.

I can send a pull request if it needs to be fixed.

**Comment by PEZ** [comment]
Thanks! Yes, PR welcome!
