### ISSUE TITLE
Can't do formatting code from Calva: Fire up the Getting Started REPL on hello_repl.clj

### ISSUE THREAD

**Issue by genegois** [BetterThanTomorrow/calva#1918]
When in `==Editing Code==` chapter and then press `tab` key, nothing happened, but the alternative solution to this are already addressed in [https://clojurians.slack.com/archives/CBE668G4R/p1666820065090229](url)
Thank you

**Comment by PEZ** [comment]
Thanks for reporting this! Formatting indeed works in regular folders. The Getting Starte REPL is folder-less so a bit special and something we have done recently must have broken formatting there...

**Comment by svdo** [comment]
~For me this works correctly when choosing a new temp dir for the REPL location, and it fails when choosing to use the existing one.~ Scratch that, same behaviour in both cases.

I get:

```
'Unable to move/copy '/Users/<redacted>/Library/Application Support/Code/User/globalStorage/betterthantomorrow.calva/drams/deps.edn' because target '/var/folders/m7/ykdfcv0x2xb1p75hztn5d9s40000gt/T/betterthantomorrow.calva/zkc74j/deps.edn' already exists at destination.'
```

Tracking this further, I get to `openStoredDoc()` in `repl-start.ts`, where it says:

```ts
try {
    await vscode.workspace.fs.copy(sourceUri, destUri, {
      overwrite: false,
    });
  } catch (e) {
    console.log(e);
  }
```

It says here not to overwrite, which indeed causes the `console.log`. @PEZ Is this intended behaviour?

**Comment by PEZ** [comment]
Thanks, @svdo! I haven't checked the code, but from your comment it sounds like a bug that we would try to create the file when the user has choosen to use existing files.

**Comment by svdo** [comment]
Hmm that doesn't feel quite right, I think it maybe something else. I'll look into it soon @PEZ.
