### ISSUE TITLE
Minimist security vulnerability

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1919]
https://github.com/BetterThanTomorrow/calva/security/dependabot/14

> Dependabot hasn't attempted to update minimatch as it's no longer vulnerable.

I don't know if this is really true ^, since the mentioned version is still in the top level package-lock and the atom-language-clojure package-lock.

**Comment by PEZ** [comment]
It's interesting:

``` sh
~/Projects/calva(dev|✔) % npm audit
found 0 vulnerabilities
```

``` sh
~/Projects/calva/src/calva-fmt(dev|✔) % npm audit
found 0 vulnerabilities
```

**Comment by bpringe** [comment]
I'm going to dismiss that alert, then.
