### ISSUE TITLE
Calva Paredit: Kill/Delete Right deletes also the space before the form

### ISSUE THREAD

**Issue by karimarttila** [BetterThanTomorrow/calva#1922]
If I have the following row and | marks the cursor:

```clojure
(count |[:a :b])
```

... and then I give command `Calva Paredit: Kill/Delete Right` ... I get:

```clojure
(count|)
```

and not:

```clojure
(count |)
```

(i.e. I'd like to have the space preserved) ... and therefore if I "paste" the form back I get:

```clojure
(count[:a :b])
```

and not:

```clojure
(count [:a :b])
```

We had some discussion about this in the Clojurians slack:
https://clojurians.slack.com/archives/CBE668G4R/p1666803713170629

I copy-paste here some information regarding that discussion that might help the person working with this ticket:

If I understood correctly the discussion with `pez` and `skylize` the `:remove-surrounding-whitespace?` rule in cljfmt causes this behaviour. 
`skylize` said: "A config to disable that rule would make this go away, but would also break the many cases where applying this rule is desirable."
`pez` said: "Calva already distinguishes between format-on-demand and format-as-you-type, relaxing the formatting for the latter case. It could be that this strategy should be expanded on, or some similar approach should be taken for Paredit-induced formatting (which counts as format-as-you-type)."

**Comment by PEZ** [comment]
Thanks! 🙏 

I'll create a test build with an idea of mine, which we can take for a spin.

> A config to disable [the `:remove-surrounding-whitespace?`] rule would make this go away, but would also break the many cases where applying this rule is desirable.

For the record, this config is entirely up to the user to apply. See: https://calva.io/formatting/#configuration
