### ISSUE TITLE
Calva Paredit: Kill/Delete Right does not trim spaces

### ISSUE THREAD

**Issue by karimarttila** [BetterThanTomorrow/calva#1923]
Calva formatting does not trim spaces when applying Paredit: Kill/Delete Right in certain situations:

If I'm editing Clojure code and at some point, I have done some modifications and I have a form like this: (| marks cursor):

```
(map inc (map inc
              |(range 3)))
```

If I then backspace I get this:

```
(map inc (map inc (range 3)))
```

... which is what I want.

But. If the cursor is here:

```
(map inc (map inc |
              (range 3)))
```

... and I either delete or I Calva Paredit: Kill/Delete Right I get this:

```
(map inc (map inc               (range 3)))
```

... which is definitely not what I want (i.e. the extra spaces from the next line).

**Comment by skylize** [comment]
Current behavior allows for internal manual alignment.

```clojure
(let [foo                :bar
      a-really-long-name :baz])
```
Kill right brings the form onto the same line _before_ formatting is done, so it looks like manual alignment and doesn't get collapsed.

**Comment by PEZ** [comment]
The inspiration for Calva's **Paredit Kill Right** is **Emacs paredit-kill**, which also keeps the indentation spacing. I just tested that. Doesn't mean we should keep the behaviour, just that we might surprise Emacs people if we change it.

**Comment by PEZ** [comment]
Can you give an example of the behaviour you are referring to @skylize? I don't quite follow.

**Comment by PEZ** [comment]
Here's a VSIX behaving like I think you are suggesting, @karimarttila: https://output.circle-artifacts.com/output/job/79b752b2-97e0-430f-8f8f-e4d85812e57b/artifacts/0/tmp/artifacts/calva-2.0.314-1923-kill-right-squashing-leading-whitespace-09468992.vsix

I think I agree. Will run with this a bit and see how it feels.
