### ISSUE TITLE
Newline missing in some prints to Output/REPL window

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1927]
The ones I've found so far:

* When printing Clojuredocs examples to the Output window
* Test runner results are a bit garbled

Please comment on this issue if you find anything else.

**Comment by bpringe** [comment]
I've noticed that warnings like this are being printed with an added `;` on a line of its own after each. I don't think that was the case before.

```clojure
; WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.test.check.generators, being replaced by: #'clojure.test.check.generators/abs
; 
```

**Comment by bpringe** [comment]
I just noticed if I eval `*e` or `*1`, for example, in the REPL window, it prints the result starting on the same line as the input.

![image](https://user-images.githubusercontent.com/12722744/199122302-d35c62bb-11ef-4ef7-a573-71eceb01cbbd.png)

**Comment by PEZ** [comment]
It's not just *e, etcetera, actually. Anything evaluated from the prompt get this treatment.
