### ISSUE TITLE
Warnings printed with an added `;` on a line of its own

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1930]
I've noticed that warnings like this are being printed with an added `;` on a line of its own after each. I don't think that was the case before.

```clojure
; WARNING: abs already refers to: #'clojure.core/abs in namespace: clojure.test.check.generators, being replaced by: #'clojure.test.check.generators/abs
; 
```

_Originally posted by @bpringe in https://github.com/BetterThanTomorrow/calva/issues/1927#issuecomment-1297417908_

**Comment by PEZ** [comment]
I did a quick check and can't immediatelly see where this happens. And I don't know of a good way to reproduce.

**Comment by bpringe** [comment]
I can reproduce by loading a file with the following code:

```clojure
(ns test)

(defn abs [x] x)
```

Output:

```clojure
; Evaluating file: test.clj
; WARNING: abs already refers to: #'clojure.core/abs in namespace: test, being replaced by: #'test/abs
; 
#'test/abs
```

**Comment by bpringe** [comment]
You'd need at least Clojure 1.11 for the specific case above, as that's when `abs` was added to `clojure.core`.

**Comment by bpringe** [comment]
It's happening here: https://github.com/BetterThanTomorrow/calva/blob/79557eb8cf15dda255aa6e7581036fb4882fbabb/src/evaluate.ts#L437

The warning has a newline at the end:

![image](https://user-images.githubusercontent.com/12722744/199392245-46037154-0f46-457e-a44d-5bb2b2caa722.png)

which `asLineComment` replaces with `\n; ` here: https://github.com/BetterThanTomorrow/calva/blob/79557eb8cf15dda255aa6e7581036fb4882fbabb/src/evaluate.ts#L265

I can work on a fix soonish if you want, but there are a few references to `asLineComment` and you're more familiar with this printing code, so if you have time maybe you can look at it before me.

**Comment by PEZ** [comment]
I can repro it now. Thanks!

Fix on its way. Possibly creating new problems, but we'll see about that, I guess. 😄
