### ISSUE TITLE
Extra newlines are printed in output from function called from test

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1937]
Repro - If you run the below function by itself the output is printed as expected (no extra newlines), but if you use one of Calva's test commands to run the test that calls the function, the output is printed with extra newlines.

```clojure
(defn print-stuff []
  (prn "one")
  (prn "two")
  (prn "three"))

(deftest print-stuff-test
  (is (nil? (print-stuff))))
```

Result of using a test command to run the test:

```clojure
"one"

"two"

"three"

; 1 tests finished, all passing 👍, ns: 1, vars: 1
```

**Comment by PEZ** [comment]
Thanks! PR pushed!
