### ISSUE TITLE
Make Calva a bit more VIM friendly

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1947]
User of the VIM extension often run into troubles with some incompatibilities with Calva. Specifically these two issues are reported:

* The cursor jumps to the beginning of the line when entering new lines
* The `escape` key is bound to dismiss inline results

Users get rid of the issue with the cursor positioning by configuring Calva to not use the ”New indent engine”. I have been thinking this is a matter of the old engine being slower and thus being later than the VIM extension to the party. But today I realized that another difference is that the old indent engine actively sets the cursor position after re-indenting. So maybe we can do the same with the new indenter and solve this issue...

The `escape` key problem could be made much less impactful if we only bind it when we are actually showing inline results.

**Comment by tom-adsfund** [comment]
This is really useful, thanks!
