### ISSUE TITLE
The indenter fails matching cljfmt rules on qualified symbols

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1956]
Using the new (default) indent engine, and default cljfmt rules. With text like this (cursor represented by `|`):

```clojure
(foo/defbars body|
  [:body {}])
```

Typing <kbd>enter</kbd>, results in:

```clojure
(foo/defbars body
             |
  [:body {}])
```

Hitting <kbd>tab</kbd>, we get:

```clojure
(foo/defbars body
  |
  [:body {}])
```

Which is the correct indent position, given the default cljfmt rules. So that is what the new indent engine also should do.

The problem here is that the new indent engine matches the regex (`#"^def(?!ault)(?!late)(?!er)"`) against the whole symbol, while cljfmt matches it against the symbol with the namespace part stripped.

I'm not sure what should happen if the regex includes namespace. We should investigate this a bit.

**Comment by PEZ** [comment]
Here are some more test cases.

```clojure
; Should indent like `(let ...`
(clojure.core/let [x :x]
  |
  x)

; Should indent `[[:inner 0]]`
; Assuming we have the custom indent rule:
; `{:indents {inner-0-form [[:inner 0]]}}`
(foo/inner-0-form :a
  |
  :foo)

```

**Comment by wevre** [comment]
I don't know what the _default_ rule is for deftype, but I expected the bodies of methods within deftype to be indented by 2 spaces, instead they are indenting all the way over to the second term, similar to what @PEZ notes in the initial comment. Could be related?

    (deftype MyType [arg1 arg2]
      IMyProto
      (method1 [this] |(print "hello world")))

Typing `enter` results in

    (deftype MyType [arg1 arg2]
      IMyProto
      (method1 [this]
               |(print "hello world")))

It sort of flashes for a moment in the right spot, then scoots over. Hitting `tab` does not put it in the right spot. But I did find out something interesting while experimenting. If I hit `enter` and create a blank line

    (deftype MyType [arg1 arg2]
      IMyProto
      (method1 [this]
               
               |(print "hello")))

and then hit `backspace`, it goes to the correct spot.

    (deftype MyType [arg1 arg2]
      IMyProto
      (method1 [this]
        |(print "hello")))

Which is great! But if I hit `tab` again it will go over to the wrong spot.

**Comment by PEZ** [comment]
Thanks @wevre! That is somewhat related, I would say. It's a bit trickier to deal with though. Because the cause here is that Calva only formats the enclosing form, so `deftype` is never considered. `backspace` causes the parent form to be formatted, which is why your trick works. Similar if you format the `deftype` form. Please post as a separate issue, so that we can track it even if we don't fix it in this first go.
