### ISSUE TITLE
Getting Started REPLs download config from dram `dev` branch

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1977]
For downloading the content to the Getting Started REPLs, Calva uses the `dev` branch of https://github.com/BetterThanTomorrow/dram when Calva is run in debug mode. And from `published` when run in production. This is so that we should be able to update the drams with confidence.

However, we always download the dram.edn config file from the dev branch. Which just had me break the Getting Started REPL, by pushing a test config to drams `dev`...

**Comment by SillyCoon** [comment]
I'll take it, seems easy to fix

**Comment by bpringe** [comment]
I think there was no commit with a message containing the closes/fixes syntax in the PR commits. Closing now.

@SillyCoon FYI, for some reason just using the closes/fixes syntax in the PR description doesn't cause auto-closing of related issues. The syntax has to be used in a commit message in the PR.
