### ISSUE TITLE
Inconsistent formatting of defprotocol with docstring on separate line from method declaration.

### ISSUE THREAD

**Issue by skylize** [BetterThanTomorrow/calva#1978]
* While typing, the docstring aligns with the parameters.

* If the cursor is anywhere within the method form, then calva-fmt.formatCurrentForm follows the same rule, and aligns the docsctring to the params.

* This only applies or gets updated for the single form containing the cursor. Move the cursor inside a different method's form, and run calva-fmt.formatCurrentForm to also format that form as described above, but again not affecting alignment of any other methods.

* Move the cursor to where it is outside of any method expression and run calva-fmt.formatCurrentForm and a different rule takes over. All the docstrings align to the second character of the respective method name.

* Same with other format-triggering events (such as paredit.dragSexpForward). So long as the cursor is _not_ within a form that defines a method, all the docstrings align to a +2 character indentation.

```clojure
; | for cursor

(defprotocol Foo
  (method [_] |"docstring"))

; <Enter>
(defprotocol Foo
  (method [_]
         |"docstring"))

; <calva-fmt.formatCurrentForm>
(defprotocol Foo
  (method [_]
         |"docstring"))

; <move cursor>
(defprotocol Foo
 |(method [_]
          "docstring"))

; <calva-fmt.formatCurrentForm>
(defprotocol Foo
 |(method [_]
    "docstring"))

; <move cursor>
(defprotocol Foo
  (|method [_]
     "docstring"))

; <calva-fmt.formatCurrentForm>
(defprotocol Foo
  (|method [_]
           "docstring"))
```

**Comment by SillyCoon** [comment]
@PEZ  I think this issue related to #1957,  the indenter case seems to be already fixed, I'll take a look on the formatter case

**Comment by skylize** [comment]
I agree this sounds like probably an alternate manifestation of the same issue (though cannot say for sure until one or the other is fixed 😄).

**Comment by PEZ** [comment]
@SillyCoon, I think the formatter case might be solved by adding `defprotocol` to the format-depth map you introduced in your latest PR.

**Comment by SillyCoon** [comment]
> 

Yeah, it looks like this. I will create a PR with `defprotocol` and will move this map to the config

**Comment by SillyCoon** [comment]
Hello @PEZ! I think this ticket also was not closed automatically 😢

**Comment by skylize** [comment]
Thanks @SillyCoon
