### ISSUE TITLE
[2.0] REPL doesn't load clojure.repl automatically

### ISSUE THREAD

**Issue by danlucraft** [BetterThanTomorrow/calva#198]
When using 2.0 alpha, either with Jack-in or connecting manually, the repl doesn't import `clojure.repl` symbols into the namespace.

You can do this manually with `(use 'clojure.repl)` but for best first time use it should do this automatically (at least in the pretty open tab repl – it may not make sense to load it into whatever space is being used for evaluating forms from the editor).

**Comment by bbatsov** [comment]
Actually what Clojure's default REPL does is `(clojure.core/apply clojure.core/require clojure.main/repl-requires)`. After inspecting its code I've also added this in CIDER for whatever the initial REPL ns is. CIDER also has one command to quickly run this code in your current REPL ns (useful when you're switching between namespaces).

**Comment by PEZ** [comment]
Thanks, @bbatsov!

I just pushed `2.0.7`, fixing an ugly jack-in bug, but also including the command: **Require REPL utilities, like (doc) etecetera, into current namespace**, `ctrl+alt+c ctrl+u`.

I had to do something slightly different for `cljs` repls: `(use '[cljs.repl :only [apropos dir doc find-doc print-doc pst source]])`.

If this checks out for you, @danlucraft, please close this issue.

**Comment by danlucraft** [comment]
Nice!

Thanks @PEZ !
