### ISSUE TITLE
CI: Webpack build throws with an error: [webpack-cli] Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1985]
The CI `build` step crashes like so:

https://app.circleci.com/pipelines/github/BetterThanTomorrow/calva/5846/workflows/ced2b29e-da91-4410-ae5a-e4276b7d8845/jobs/27100

```
[webpack-cli] Error: error:0308010C:digital envelope routines::unsupported
```

_Originally posted by @bpringe in https://github.com/BetterThanTomorrow/calva/issues/1983#issuecomment-1331198611_

I find this issue, which seems to have cause a ruckus in the Webpack community:

* https://github.com/webpack/webpack/issues/14532

It is many, many pages of comments. Seems like the conclusion is to upgrade to Webpack 5. Which sucks a bit for us, because that is what we are using! But anyway, now I am not as scared by this error. I'm sure we'll at least find a workaround with some sensible amount of work.

**Comment by PEZ** [comment]
I've [reproduced the error](https://app.circleci.com/pipelines/github/BetterThanTomorrow/calva/5846/workflows/ced2b29e-da91-4410-ae5a-e4276b7d8845) in a separate branch. Let's see if I can figure out a way to fix it.

**Comment by PEZ** [comment]
Bumping the webpack dependency made it start to work: https://app.circleci.com/pipelines/github/BetterThanTomorrow/calva/5848/workflows/a177ebb5-a61b-444c-88dd-845b9a1e44b0

But I think the actual error is hidden now that we have a different build artifact. Reading the original error message more carefully, I see that the message comes from `webpack-cli`, where we actually still are on a version 4, while there is a version 5.0.0 available. I will try with bumping that as well.

**Comment by PEZ** [comment]
Using webpack-cli 5.0.0 also gives us a green build. I think that even if this is not the real fix, I am a bit too blind about the underlying cause to figure out what the real fix is and that we should make do with this hiding of the symptoms for now. (And it actually might be the real fix, it was pretty clear in that Webpack issue that using Webpack 5 is the fix.)

**Comment by bpringe** [comment]
Why did it suddenly just break anyway? Was there a breaking change in a minor or patch update?

**Comment by PEZ** [comment]
I don't know, tbh. I think some cache was either invalidated or stale.
