### ISSUE TITLE
Update Calva docs to no longer mention removed clojure-lsp setting

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1988]
@skylize Mentioned in a Slack convo that part of the Calva docs are outdated.

> :use-source-paths-from-classpath was removed this June. https://github.com/clojure-lsp/clojure-lsp/blob/ee8ad07be39e9ecd6ced8ad53e4623f605896941/CHANGELOG.md#20220622-140950

The doc page that mentions that setting is here: https://calva.io/linting/#exclude-entire-folders-from-the-linter

**Comment by PEZ** [comment]
I opted to remove the examples all together. It's an unnecessary burden to keep our docs in sync from also documenting the other projects. And, it can create confusion for the user, especially when we miss to keep something in sync.
