### ISSUE TITLE
[2.0] Calva won't let to re-jack-in upon manual termination of the Task-Calva Jack-In

### ISSUE THREAD

**Issue by dabrazhe** [BetterThanTomorrow/calva#199]
Occasionally, Calva won't allow Jack-in again if you terminate the task (Ctrl-C in the terminal pane). 
Closing / opening the VSC window helps : )

Seen on a Mac, 
Leiningen 2.9.1 on Java 10.0.2 Java HotSpot(TM) 64-Bit Server VM

**Comment by cfehse** [comment]
This should be fixed in version 2.0.49.
