### ISSUE TITLE
Clojure notebooks don't seem to work on MS-Windows

### ISSUE THREAD

**Issue by ikappaki** [BetterThanTomorrow/calva#1994]
Hi,

it appears that Clojure notebooks with MS-Windows CRLF line endings are broken, with sexp forms spilling over to the next code block:

![image](https://user-images.githubusercontent.com/34983288/206389255-5299bf64-e8db-4951-95f7-800fd81b8e5e.png)

How to reproduce.
1. Create a `dos.clj` file with CRLF endings in any project using the following code
``` clojure
(spit "dos.clj" "(ns dos\r\n  (:require [clojure.string :as str]))\r\n\r\n(str/split \"1 2\" #\" \")")
```
2. In VS Code Explorer right click on `doc.lj` and select `Open with...` -> `Clojure Notebook`.
3. You should get the above break in the first form whose last closing parenthesis spills over to the scond code cell.

PR to follow

**Comment by PEZ** [comment]
Thanks for reporting! ❤️ 🙏  Looking forward to that PR!

**Comment by PEZ** [comment]
We forgot to close this with the commits.
