### ISSUE TITLE
Calva development: `npm run prettier-format` fails on MS-Windows

### ISSUE THREAD

**Issue by ikappaki** [BetterThanTomorrow/calva#1996]
Hi,

prettier compalins it can't match any files when invoked on MS-Windows

```
npm run prettier-format

> calva@2.0.322 prettier-format
> npx prettier --write './**/*.{ts,js,json}'

[error] No files matching the pattern were found: "'./**/*.{ts,js,json}'".
```

to reproduce
1. Clone Calva
2. Run `npm install`
3. Execute `npm run prettier-format`, it fails with the above message.

`prettier-check` and their watch variants fail for the same reason.

PR to follow.

**Comment by PEZ** [comment]
This is now fixed, right?

**Comment by ikappaki** [comment]
> This is now fixed, right?

It is yes, thanks
