### ISSUE TITLE
Calva keeps telling me "Could not resolve symbol" however the symbol is resolved during evaluation

### ISSUE THREAD

**Issue by namig-tahmazli** [BetterThanTomorrow/calva#2000]
Hello. 

I came across this issue today.
I created a custom macro as such.

```Clojure
(defmacro if-and-let
  ([bindings then]
   `(if-and-let ~bindings ~then nil))

  ([bindings then else & more]
   (let [form (first bindings)
         tst (second bindings)]
     (if (and form tst)
       `(let [name# ~tst]
          (if name#
            (let [~form name#]
              (if-and-let ~(into [] (nnext bindings))
                          ~then
                          ~else))
            ~else))
       then))))
```

evaluating the following code works fine and it returns "39Nam"

```Clojure
(if-and-let [val (+ 1 2)
                    some (some #(and (pos-int? %) %) [-1 -2 9]) 
                    name (:name {:name "Nam"})]
                   (str val some name )
                   (str "I" "do" "not" "know"))
```

However, Calva keeps showing a red line under some of the properties (usually the second parameter in the vector) saying that
"Unresolved symbol:"

Thank you for your help in advance.

**Comment by PEZ** [comment]
Hi!

This is due to that clj-kondo not knowing that those are bindings. You'll need to tell it that this should be linted as some macro it does now about. Looks like `let` would work here.

See this page about Calva linting: https://calva.io/linting/

It has links to relevant pages in the clj-kondo docs.

**Comment by namig-tahmazli** [comment]
@PEZ Thank you very much for the tip. Indeed adding my macros as let in the lint-as worked.
```Clojure
{:lint-as
{app/if-and-let clojure.core/let}}
```
