### ISSUE TITLE
afterCLJReplJackInCode fails if no editor buffer open

### ISSUE THREAD

**Issue by bbqbaron** [BetterThanTomorrow/calva#2025]
When eval'ing `afterCLJReplJackInCode`, Calva seems to crash if there isn't an active text editor. Assuming I understand the problem correctly, I'd rather it evaluate and just not print the output anywhere, rather than failing to evaluate.

Minimal workspace settings:

```json
{
    "calva.replConnectSequences": [
        {
            "name": "Test broken jack-in",
            "projectType": "generic",
            "afterCLJReplJackInCode": "(prn \"hi\")",
            "cljsType": "none",
        },
    ]
}
```

**Repro**

There may be variations on this, but one possible flow:

* start a headless repl in an otherwise-empty deps project
* open a couple VSCode tabs. No files open, just tabs! Select the first tab.
* connect to a running repl in project
* observe an error like this in the extension logs:

```
2023-01-20 10:28:08.166 [error] Error: Expected active text editor!
```

Note that if you _do_ open a text buffer in the active tab before connecting, jack-in works and you get `"hi"` in the REPL output.

I'm new to Calva's codebase, but I assume it's `getActiveTextEditor` blowing up when trying to eval the code?

**Comment by bbqbaron** [comment]
I'd be happy to PR a change that basically just skips any statements that would have used the active editor. I'm just not sure if I'll break other flows/use cases by doing so.

**Comment by PEZ** [comment]
Thanks for reporting!

I can reproduce this. Here's an example project with instructions for a minimal repro:

* https://github.com/BetterThanTomorrow/calva/tree/dev/test-data/projects/repl-connected-code

A PR is welcome. It does not sound right to ”just skip any statements ...”. It still could be right, it depends on which statements. 😄

**Comment by PEZ** [comment]
I added a PR fixing this essentially the way you suggested, @bbqbaron.

**Comment by bbqbaron** [comment]
> I added a PR fixing this essentially the way you suggested, @bbqbaron.

Amazing! Thanks for the quick reply.
