### ISSUE TITLE
Indenter and formatter not in agreement about some forms

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#2032]
With a form like (cursor at `|`):

```clojure
(and x |y)
```

Pressing <kbd>enter</kbd> gives

```clojure
(and x 
     |y)
```

Which I think is expected (can't recall right now). However, if I then press <kbd>tab</kbd>, I get:

```clojure
(and x
  |y)
```

So it seems like the indenter and the formatter read the config differently.

Possibly related:

> That said, I am experiencing weird indentation issues quite often lately. Which could be regressions from the fixing of this issue. I'll try figure out a repro. It happens to me in my work project and code I can't share as is.

_Originally posted by @PEZ in https://github.com/BetterThanTomorrow/calva/issues/1957#issuecomment-1398981754_

**Comment by PEZ** [comment]
Maybe a unit test that checks that the indenter and the formatter does the same thing is called for here.

**Comment by SillyCoon** [comment]
I'll try to identify the config for both indenter and formatter, probably the sorting fix from the `deftype` issue was not applied everywhere

**Comment by SillyCoon** [comment]
Hi @PEZ! I can't reproduce it this way and `Format current form` also. But it reproduces in a slightly different manner:

With a form like (cursor at |):
```clojure
(and x |y)
```
Pressing `enter` gives
```clojure
(and x 
     |y)
```
I then press `enter` again

```clojure
(and x 
     
    |y)
```
And then `backspace`
```clojure
(and x 
  |y)
```

I guess it happens because `backspaceOnWhitespaceEdit` doesn't pass `config` to `getIndent` function, but I'm not sure about your case, could you please re-check it. Thanks!

**Comment by PEZ** [comment]
Ah, you are right, my repro is bad. So the error I see, happens in my work project, where we have `#"\S+" [[:inner 0]]` in our `cljfmt.edn` config. This config reproduces it:

```clojure
{:indents {#"\S+" [[:inner 0]]
           ,,,}
 :test-form
 (and a b)}
```

It used to make both the indenter and the formatter indent like: 

```clojure
(and x 
  y)
```

But since recently it makes the indenter format it as if the regex catch-all wasn't there.

Your find with backspace is interesting. I tried it with v2.0.322 and it was the same there. Please file as a separate issue.

**Comment by SillyCoon** [comment]
@PEZ  and this one also 🙏
