### ISSUE TITLE
Sort `deps.edn` project aliases in picker for Jack-In

### ISSUE THREAD

**Issue by ferdinand-beyer** [BetterThanTomorrow/calva#2035]
The quick picker to select the alias(es) to use for Jack-In of `deps.edn` projects is unsorted. For projects with a lot of aliases, this makes it hard to find the ones you want to use.

Sorting them helps with this.

(I will submit a PR for this in a few minutes)

**Comment by PEZ** [comment]
Thanks for reporting. 🙏  Looking forward to the PR!

**Comment by ferdinand-beyer** [comment]
Extremely simple fix :)

**Comment by ferdinand-beyer** [comment]
Note sure why this was not auto-closed with #2036...?
