### ISSUE TITLE
Formatting issues on `backspace`

### ISSUE THREAD

**Issue by SillyCoon** [BetterThanTomorrow/calva#2038]
With a form like (cursor at |):
```clojure
(and x |y)
```
Pressing `enter` gives
```clojure
(and x 
     |y)
```
I then press `enter` again

```clojure
(and x 
     
    |y)
```
And then `backspace`
```clojure
(and x 
  |y)
```

I guess it happens because `backspaceOnWhitespaceEdit` doesn't pass `config` to `getIndent` function.

_Originally posted by @SillyCoon in https://github.com/BetterThanTomorrow/calva/issues/2032#issuecomment-1404797546_

**Comment by bpringe** [comment]
This was fixed by the linked PR, but wasn't auto-closed since there wasn't a commit message with the closes/fixes syntax in it.
