### ISSUE TITLE
Missing required argument for "-M ALIASES"

### ISSUE THREAD

**Issue by roxanadangerm** [BetterThanTomorrow/calva#2039]
Hello,
I am just starting with Clojure and Calva and I am testing them with a very simple example.

The structure of my project is:
- time
    - deps.edn
    - src
         - time.clj

The content of the files deps.edn and time.clj is as described in the section "Writing a program" at https://clojure.org/guides/deps_and_cli.

I then execute the command: Calva: Start a project and connect, selected my directory and type deps.edn.

The output in the terminal shows an error and I do not get connected to the REPL. 

Terminal output:
clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"1.0.0"},cider/cider-nrepl {:mvn/version,"0.28.5"}}}' -M -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
Missing required argument for "-M ALIASES"
Jack-in process exited. Status: 1

What am I missing here?

Thank you very much in advance.

**Comment by PEZ** [comment]
Thanks for reporting! I think this is to do with using an old `clojure` executable. Calva has a setting for this.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/30010/215101948-45b87b5e-2fdb-4a48-bfd0-37523775d51d.png">

I think we should keep this issue open. Calva has a check for if `clojure` is installed, and we can make it check version too, and at least say something about the setting if it is too old for the regular jack-in command line.

**Comment by roxanadangerm** [comment]
Fantastic!! Thank you very much!

**Comment by PEZ** [comment]
Did you upgrade your `clojure` CLI tools, @roxanadangerm? I'm asking because we are about to release a new version of Calva, where we replace the settings mentioned above with a version check and automatic fallback to the deprecated flag. If you run into problems with Calva v2.0.331, please holler our way! I'm pretty confident it will work just fine, but anyway.
