### ISSUE TITLE
Can't use `add require` feature after updating to 2.0.327 version

### ISSUE THREAD

**Issue by evandroferreiras** [BetterThanTomorrow/calva#2040]
After updating the version to `[2.0.327] - 2023-01-26` this feature stopped working. I receive an error: `command 'add-require-suggestion' not found`
![image](https://user-images.githubusercontent.com/3903012/215194751-b3bd4081-4c73-4d0c-a229-0b5eed445336.png)

Ps 1: I've already validated that the feature returned to work when I rolled back to the previous version. 
Ps 2: I tested with an old LSP version and with the current (`2023.01.26-11.08.16`), doesn't seem to be related.

**Comment by PEZ** [comment]
Thanks for reporting! I can reproduce this. Will roll back the changes now.

**Comment by PEZ** [comment]
We have rolled back the changes now, @evandroferreiras . Please update Calva to 2.0.328 and it will be working as before. Thanks again for reporting!

* We're tracking the regression in #2041
