### ISSUE TITLE
Establish REPL connection without being prompted for the kind of project every time

### ISSUE THREAD

**Issue by jqmtor** [BetterThanTomorrow/calva#2049]
On every jack in, Calva prompts the user for the kind of project being used (`deps.edn`, `joyride`, etc.).
The suggestion is to introduce a mechanism that allows this to be configured once, potentially via a project-level setting. 

If this feature were to support selecting custom REPL sequences as the kind of project, it would allow users to jack in without being prompted at all. For that, they would have to use this setting in combination with the `menuSelections` attribute from the custom REPL sequence.

**Comment by SillyCoon** [comment]
Hi! I can pick it up, sounds useful
