### ISSUE TITLE
Clojure-lsp does not automatically start when using VSCode on Windows in Calva version 2.0.329

### ISSUE THREAD

**Issue by LouDnl** [BetterThanTomorrow/calva#2054]
Starting with the release of [v2.0.239](https://github.com/BetterThanTomorrow/calva/releases/tag/v2.0.329) clojure-lsp will no longer start automatically when using VSCode on Windows. Rollback to version v2.0.238 fixes this issue and clojure-lsp starts automatically again.
It is however possible to start clojure-lsp by hand in v2.0.239 by clicking on `clojure-lsp` in the bottom statusbar and selecting the correct Clojure project from the drop-down menu that appears.
This issue has been discussed on Slack in the [v2.0.239 release thread](https://clojurians.slack.com/archives/CBE668G4R/p1675253617226879).

My guess is that the fix from #2041 stops it from identifying the correct project path.

project-root-uri from server info in v2.0.238:
`"project-root-uri": "file:///d:/thier/Documents/GoogleDrive-Thorax/Dev/aorta-develop"`

In v2.0.239 the uri is the same after manually selecting the project.

clojure-lsp popup in v2.0.239:
![image](https://user-images.githubusercontent.com/8543038/216078101-7b09cdd1-7066-4a34-ab90-f184425097e3.png)

clojure-lsp popup in v2.0.239 (with extra folders removed from .code-workspace file):
![image](https://user-images.githubusercontent.com/8543038/216078047-a7d29fcb-e22a-480d-9fb3-955bc477d294.png)

VSCode explorer view:
![image](https://user-images.githubusercontent.com/8543038/216077998-0392e1bf-9fcd-40db-831c-b92f65e6c766.png)

_Changing the "." path to the full path makes no difference_
VSCode .code-workspace file:
```json
{
	"folders":
	[
		{
			"path": "."
		},
		{
			"path": "..\\_docs-code"
		},
		{
			"path": "..\\bootstrap\\bootstrap-4.1.3"
		}
	]
}
```

**Comment by PEZ** [comment]
Thanks for reporting! Are you perhaps using a VS Code Workspace proper, with folders?

**Comment by LouDnl** [comment]
> Thanks for reporting! Are you perhaps using a VS Code Workspace proper, with folders?

Yes, it is a trusted workspace, see screenshot:
![image](https://user-images.githubusercontent.com/8543038/216083414-17ffb239-a2bb-437e-96d2-28c5d7e000ab.png)

**Comment by kstehn** [comment]
I have some other infos maybe this will help to pinpoint this problem too.

So my workspace layout is like this 

- Project A
- Project B
- Random Other folder
- Project C
- ...

I added all Folders to workspace.

When i want to start the lsp i get for each project two choices. For example with Project A

1. project a
2. path to project a (but has wrong structure /d:\rest-of-path )

I choose the first option and see this error on lsp start:
![image](https://user-images.githubusercontent.com/5702321/216269098-02bb2bc4-8282-43b7-9c8e-5a8091fde6c3.png)

So far so okayisch, it somehow works and in the project i can jump between the references.

When i want to start the second lsp i see this error:
![image](https://user-images.githubusercontent.com/5702321/216269583-9d1eaaa0-35a8-433e-8c63-e1333cf8a530.png)

Here you can see the completly wrong path where the \ got escaped which is the second option from lsp start.

Also what is interesting on my second try (restart debug calva) even the first start didn't work.


When i use a diffrent workspace layout like so:

- root folder
   - Project A
   - Project B
   - ....

With this i get only the Activate Extension info when i try anything from calva (starting lsp, navigating through code with ctrl + left arrow). In the debug window from calva there is no info.
