### ISSUE TITLE
Multiple LSP processes automatically running, broken LSP features in multi-root workspaces

### ISSUE THREAD

**Issue by stefan-toubia** [BetterThanTomorrow/calva#2065]
The recent change how the LSP server is run has lead to some issues in my multi-root workspace

[Slack thread](https://clojurians.slack.com/archives/CBE668G4R/p1675468715446929)

[Here's a minimum repro.](https://github.com/stefan-toubia/clj-repro/tree/monorepo)
This branch defines a small "monorepo" workspace with multiple projects. There's also a vscode workspace file that lists some of the projects in this repo as standalone workspace roots.

The new setting `calva.enableClojureLspOnStart` has a couple issues:

`when-workspace-opened-use-workspace-root` (default): This causes multiple LSP processes to start, one per Clojure project workspace folder.
`when-file-opened-use-furthest-project`: This does have the desirable behavior of only starting a single LSP process in the repo root, but many LSP features do not work for projects configured as their own workspace root folders (`project-a` and `project-b` in the repro). Per the status bar indicator, no LSP server is identified as running and Calva will prompt you to start LSP.

Based on comments in the slack thread, it does seem like some of the current behavior is unintentional, though it's not clear to me exactly what the intended behavior of `when-workspace-opened-use-workspace-root` was supposed to be with regard to multiple workspace roots.

**Comment by bpringe** [comment]
Thanks for the detailed report. @julienvincent, can you take a look at this?

**Comment by PEZ** [comment]
> it's not clear to me exactly what the intended behavior of `when-workspace-opened-use-workspace-root` was supposed to be with regard to multiple workspace roots.

It was meant to behave just as it did before the update with this setting being set to `true`. (Which was the default, as `when-workspace-opened-use-workspace-root` is default now, so without any configuration from the user it was intended to also behave as before the updates.)

**Comment by PEZ** [comment]
Now, as before, in a project with many workspace folders, the workspace root  is considered to be the root of the first (topmost in the UI) workspace folder.

This is also what VS Code does if we would use the now deprecated `vscode.workspace.rootPath`, from `@types/vscode/index.d.ts`:

```typescript
    export namespace workspace {
        ...
        /**
         * The uri of the first entry of {@linkcode workspace.workspaceFolders workspaceFolders}
         * as `string`. `undefined` if there is no first entry.
         *
         * Refer to https://code.visualstudio.com/docs/editor/workspaces for more information
         * on workspaces.
         *
         * @deprecated Use {@linkcode workspace.workspaceFolders workspaceFolders} instead.
         */
        export const rootPath: string | undefined;
```

**Comment by kpipk** [comment]
v2.0.330.  I have a workspace with 5 project folders.  The top-most is a clojure exclusive project.  However, when starting VS code, lsp does not start.  If I click on the lsp icon at the bottom toolbar, it asks which sub-directory to choose from.  The selection is too granular.  I will attach a screenshot if I can that shows what I mean

![image](https://user-images.githubusercontent.com/123606622/217310207-7b94fe3e-3a22-41e0-bf4c-748c1a83a4f7.png)

**Comment by julienvincent** [comment]
This kind of project structure (entire mono-repo opened + sub-projects independently opened) was not even considered when changing this functionality, so this is definitely an oversight of the PR.

The fix here is more of a behaviour change than a bug fix, and it’s not immediately obvious what the behaviour then should be.

It might even indicate a third behaviour - “use-first-project-root” (or similar) as an option to always just start an lsp server, but start it in the first project root (which was essentially what Calva did before this change). And then make this the default?

Or maybe there is a better general behaviour we can implement that accounts for this workflow and others too.

**Comment by PEZ** [comment]
> It might even indicate a third behaviour - “use-first-project-root” (or similar) as an option to always just start an lsp server, but start it in the first project root (which was essentially what Calva did before this change). And then make this the default?

I think ”first project root” is what people think ”workspace root” means. At least that's how I think about it. I suggest making the `when-workspace-opened-use-workspace-root` behave like this, restoring how old Calva did it.

I don't think auto-starting multiple LSP servers makes sense, as each one use a lot of memory. If enough users want that behaviour we can consider adding an option for it.

What could make sense is to autostart clojure-lsp in the first `WorkspaceFolder` which has a Clojure project. But we can wait with that option as well. There is always the `never` option and then starting the desired server manually.

**Comment by julienvincent** [comment]
> I think ”first project root” is what people think ”workspace root” means.

I don't think we should make this assumption. I would guess that many people who use multi-project workflows in vscode think in terms of multiple roots. For example I, to add a datapoint, think in terms of multiple roots.

> I don't think auto-starting multiple LSP servers makes sense, as each one use a lot of memory. If enough users want that behaviour we can consider adding an option for it.
> 
> What could make sense is to autostart clojure-lsp in the first `WorkspaceFolder` which has a Clojure project. But we can wait with that option as well. There is always the `never` option and then starting the desired server manually.

It does make sense to auto-start the lsp server for multiple projects if they are independent. If we only auto-started the lsp-server for the first root opened then any other projects opened would not work without manually starting the lsp-server in those projects. I don't think this would be the expected behaviour.

I'd rather we didn't favour only one particular group of people/workflow here, I think we can come up with a solution that works for multiple different workflows without much compromise.

---

My proposal would be to keep the auto-start behaviour we have already but make it a bit smarter:

The issue reported here is due to the user opening multiple projects which are descendent's of other already opened project roots. We can use this as a heuristic for deciding whether or not to start an lsp-server;

If a project is opened which is a descendent of another project in the workspace with a running lsp-server then we do not auto-start anything. If an independent project is opened then we do start the lsp-server.

For example if this is the currently opened projects in a vscode workspace:

```
root-1/
 deps.edn
 projects/
  a/
   deps.edn
  b/
   deps.edn
---
b/
 deps.edn
---
root-2/
 deps.edn
```

Then:

- We start an lsp server in `root-1/`
- We _do not_ start an lsp server in `b/` because it is a descendent of `root-1`
- We start an lsp server in `root-2` because it is independent.

This should resolve the issue reported here, I think, while still allowing Calva to work with multiple project roots.

**Comment by PEZ** [comment]
> I think we can come up with a solution that works for multiple different workflows without much compromise.

As long as the compromise does not change things for people unaware of the multi-lsp changes, this might be fine. Since Calva has previously behaved the way I described, people's projects and expectations are adapted to that. The default startup behaviour should not change with this change-set if it can be avoided.

Your proposal makes sense, as long as starting multiple lsp server is an opt-in thing. And in any case I think it is stuff for later improvements. Making things smarter is tricky and opens up corner cases. That's OK, but I much rather have it as a separate thing. Right now we are fighting fires, and I'd like us to get out of that mode.

**Comment by stefan-toubia** [comment]
I might be out of the loop here, I was curious why it's desirable to run one LSP process per independent process in the first place? As far as I know you wouldn't do this for any LSP for another language.

For what it's worth, I also do not think of a single root when working in a "multi-root" workspace. I wasn't aware that vscode previously had such a concept, though I'm guessing this is why it has been deprecated.

**Comment by julienvincent** [comment]
> That's OK, but I much rather have it as a separate thing. Right now we are fighting fires, and I'd like us to get out of that mode.

I understand where you are coming from. I am just a bit concerned about the wip-lash of changing the behaviour back and forth, and of re-introducing a behaviour (as a default) that feels a bit like a step backwards.

It's hard to get a feel for how many people are affected by the current issues. If the impact isn't too wide-spread I would prefer we first try to improve on the current implementation, and focus on getting it as close to (or exactly like) the old behaviour while still (by default) supporting multiple projects.

If we are worried about wide-spread impact then I guess we can re-introduce the old behaviour as a stop-gap. I just feel we are very close to getting this right.

> I might be out of the loop here, I was curious why it's desirable to run one LSP process per independent process in the first place? As far as I know you wouldn't do this for any LSP for another language.

@stefan-toubia Some lsp-servers (like the TS one for example) allows for running a single server per vscode window. The clojure-lsp server however only supports a single project per process.

When the clojure-lsp boots it discovers information about the directory it was booted into (like deps.edn) and uses that to analyse the project. If you wanted to have a clojure-lsp server analyse a different independent project then you need a separate process to do so.

At least this is my current understanding. @ericdallo please correct me if I am wrong about this.

**Comment by julienvincent** [comment]
> I just feel we are very close to getting this right.

@PEZ If we implement my proposal above as well as the fallback of starting the lsp server in a tmp directory when no valid project is found (as we discussed on slack) I think the behaviour for existing users should be identical (unforeseen edge-cases notwithstanding).

---

To add to this, I don't think the work needed to implement this change would be too involved. It should be relatively easy to introduce this change on top of what we have.

**Comment by PEZ** [comment]
> I was curious why it's desirable to run one LSP process per independent process in the first place?

Julien already explained why, but there is still a point in challenging this. It is much to prefer to configure your workspace such that only one clojure-lsp server is needed. Like placing an umbrella deps.edn (or bb.edn) at the root (the single root that you don't acknowledge 😄) and use `:local/root` to all the projects. clojure-lsp eats a lot or memory.

> @PEZ If we implement my proposal above as well as the fallback of starting the lsp server in a tmp directory when no valid project is found (as we discussed on slack) I think the behaviour for existing users should be identical (unforeseen edge-cases notwithstanding).

I still don't like the idea of potentially 10 or 20 or more clojure-lsp servers firing up for a user who hasn't opted in for that. But if we can make it opt-in I think it sounds like a nice option.

**Comment by stefan-toubia** [comment]
> The clojure-lsp server however only supports a single project per process

I suppose the only reason my monorepo setup works is because we pin external dependency versions across the repo and have resolved various dependency conflicts with overrides. This allows us to merge multiple `deps.edn` into a single umbrella file.

Calva could in theory take multiple `deps.edn` or similar config files, union together the classpaths and source paths and pass that to Clojure LSP instead of requiring a combined config file. Though I'm not sure what kind of issues that might introduce. For example, a dependency version conflicts among multiple independent projects could cause go-to-definition to take you to the wrong version of said definition.

That is to say, I see where you're coming from. True support for multiple independent projects from a single LSP process would require intentional support from Clojure LSP, if it's even possible. I'm guessing other LSP implementations have had to deal with similar issues. Even then, I agree that running multiple LSP processes should not be enabled by default.

**Comment by ericdallo** [comment]
> @stefan-toubia Some lsp-servers (like the TS one for example) allows for running a single server per vscode window. The clojure-lsp server however only supports a single project per process.

> When the clojure-lsp boots it discovers information about the directory it was booted into (like deps.edn) and uses that to analyse the project. If you wanted to have a clojure-lsp server analyse a different independent project then you need a separate process to do so.

> At least this is my current understanding. @ericdallo please correct me if I am wrong about this.

Correct
