### ISSUE TITLE
Clojure-lsp doesn't load if the workspace's deps.edn is invalid

### ISSUE THREAD

**Issue by PavlosMelissinos** [BetterThanTomorrow/calva#2067]
### Description
On Calva v2.0.331, if I start Calva in a workspace with an invalid deps.edn (e.g. odd number of keys in a dep map), clojure-lsp fails to load but never recovers and I have to fix deps.edn and then restart VS Code to get the linter working. However, when deps.edn is correct it seems to load as expected.

### Steps to reproduce

1. Create a deps.edn in an empty directory
2. Open it with an editor and add `{:deps {org.clojure/clojure {:mvn/version}}}` in it.
3. Start VS Code

### Expected behaviour

clojure-lsp should be active and a squiggly red line should appear under `:mvn/version`

### Actual behaviour

![image](https://user-images.githubusercontent.com/388545/217347774-f618a475-a5cd-4eb2-b6ac-50d611936b33.png)

This is what I see when I click on the button

![image](https://user-images.githubusercontent.com/388545/217348223-1608e3f7-57d9-4a87-be8a-6c059a747296.png)

If I click on "foo", I can stop/restart clojure-lsp but neither fixes the issue.

### How to mitigate

The only way to recover the expected behaviour to add a value after :mvn/version (e.g. `"1.11.1"`) and restart VS Code.

**Comment by PEZ** [comment]
Thanks for reporting!

FYI. To recover, you don't need to do a full VS Code restart. It's enough to reload the window. (Still kills the REPL and such, but any other REPLs and whatever running in other VS Code windows are not affected.)


@julienvincent, this is not a regression from the clojure-lsp server management update. But you are of course welcome to have a look anyway. 😄

@ericdallo, I think this could be a upstreams from Calva. When I tried with version 2.0.328 (= 326), where we still show clojure-lsp's statusbar item,  I noticed that it never stopped spinning.

**Comment by ericdallo** [comment]
if classpath scan fails, it's presented a message from server to client, I think that used to work before calva workspace changes

**Comment by PEZ** [comment]
That message still works.

**Comment by julienvincent** [comment]
> FYI. To recover, you don't need to do a full VS Code restart. It's enough to reload the window. (Still kills the REPL and such, but any other REPLs and whatever running in other VS Code windows are not affected.)

To recover I think you can also stop and then start the server again via the management menu.

I don't think we would want to keep retrying to start the lsp server. Maybe what we want to do is check if project files have changed and then attempt to start the lsp server again in those cases?

**Comment by PavlosMelissinos** [comment]
> To recover I think you can also stop and then start the server again via the management menu.

@julienvincent If you mean click on the clojure-lsp button, stop the server and then start it again, this doesn't seem to work, even after fixing deps.edn.

**Comment by PEZ** [comment]
It would be enough if the start process was interrupted and that it would work to start it manually once the project file is fixed. An indicator that this is upstream, is that the **Retry** button in the clojure-lsp message doesn't work.

<img width="455" alt="image" src="https://user-images.githubusercontent.com/30010/217545628-962274d1-a3a8-48b7-a014-b37f746d7d32.png">

**Comment by ericdallo** [comment]
The retry button bug is indeed a clojure-lsp bug, issue welcome

**Comment by ericdallo** [comment]
I do think we should keep showing the message if classpath scan fail, otherwise clojure-lsp will barely work affecting multiple features

**Comment by ericdallo** [comment]
Opened a clojure-lsp issue about the retry not working: https://github.com/clojure-lsp/clojure-lsp/issues/1500

**Comment by PEZ** [comment]
`clojure` accepts an empty `deps.edn` these days. I think this fixes the vast majority of cases for this issue.
