### ISSUE TITLE
interrupting the repl

### ISSUE THREAD

**Issue by seebs** [BetterThanTomorrow/calva#2068]
If you are a newbie to clojure, it's easy to accidentally write something that becomes an infinite loop. If you try to evaluate it in the repl... Now what? Some REPLs apparently allow ^C to interrupt an evaluation, without killing the entire REPL process and losing its context. I can't tell whether Calva does, but if it does, I couldn't find out how by looking in the documentation.

It feels to me like "how do I stop this" should be prominent in the documentation, we've been having problems with runaway processes since _Fantasia_. :)

**Comment by PEZ** [comment]
Thanks for pointing this out, @seebs! You are very welcome to have a look at the documentation and REPL Ux, and file PRs addressing this.

Some things to consider for you (or anyone taking it on):

* There indeed is a way to interrupt runaway evaluations. The VS Code command: **Calva: Interrupt Running Evaluations**. It's default bindings are <kbd>ctrl+alt+c ctrl+alt+d</kbd> (so you can hold <kbd>ctrl+alt/option</kbd> while pressing <kbd>c</kbd>, then <kbd>d</kbd>).
* <kbd>ctrl+c</kbd> isn't really free, as it is used for **Copy** on Windows and Linux. Also, as a user you might think it kills the REPL. (Which it does if you use Jack-in and press <kbd>ctrl+c</kbd> in the Jack-in terminal.)
* Information about how to interrupt evaluations could be added to the REPL greetings.
* The REPL statusbar item brings up a menu. This menu could be a place to discover this command.

Cheers!

**Comment by seebs** [comment]
Thanks! I did in fact look in the docs for "interrupt" a bit, but apparently I did not look in them enough.

**Comment by PEZ** [comment]
I don't think it is mentioned in the docs. You should have searched the command palette instead. 😄

**Comment by seebs** [comment]
Huh. I do "calva: inte" in the command palette and don't get any matches. Calva claims to be version v2.0.331, if that matters.

**Comment by PEZ** [comment]
I'm guessing you haven't connected a REPL. Otherwise we might have a bug.

**Comment by seebs** [comment]
! Right you are. I suspect I broke it, sent a SIGINT to the process because someone said ^C had worked in something else so I thought "oh, maybe it traps sigint", then searched the palette for "interrupt", didn't find it, restarted the repl...

**Comment by bpringe** [comment]
@PEZ Might the interrupt command be a good thing to include in the Getting Started REPL? It could include some code that when evaluated, doesn't terminate, and then instruct the user to run the interrupt command.

**Comment by PEZ** [comment]
@bpringe Indeed!
