### ISSUE TITLE
[2.0] Support for "venantius/ultra" lein plugin

### ISSUE THREAD

**Issue by tamizhvendan** [BetterThanTomorrow/calva#207]
Thanks, @PEZ for revamping calva and it looks fantastic!

With this new version, I am unable to use the ["venantius/ultra" lein plugin](https://github.com/venantius/ultra).

**profiles.clj**

```clj
{:repl {:plugins [[venantius/ultra "0.5.4"]]}}
```

**terminal output**
```bash
> Executing task: /usr/local/bin/lein update-in :dependencies conj "[nrepl \"0.6.0\"]" -- update-in :plugins conj "[cider/cider-nrepl \"0.21.1\"]" -- update-in "[:repl-options :nrepl-middleware]" conj "[\"cider.nrepl/cider-middleware\"]" -- with-profile test repl :headless <

[WARNING] No nREPL middleware descriptor in metadata of #'clojure.tools.nrepl.middleware.render-values/render-values, see nrepl.middleware/set-descriptor!
nREPL server started on port 63347 on host 127.0.0.1 - nrepl://127.0.0.1:63347
```

After nREPL server started, VSCode is prompting to enter the port to connect to the nREPL server. Entering the port number doesn't connect the server.

Here is the terminal output that I am getting.
```
--
Start the REPL with the command *Start Project REPL and connect (aka Jack-in)*.
Default keybinding for Jack-in: ctrl+alt+c ctrl+alt+j
Jacking in...
Hooking up nREPL sessions...
```

If I remove that plugin from the profiles, everything is working as expected.

**Comment by bpringe** [comment]
@tamizhvendan I'm not sure if it's possible to use cider middleware (as Calva does) alongside Ultr. See this in its readme: https://github.com/venantius/ultra#using-cider-alongside-ultra

I may be wrong though. CC @PEZ

**Comment by PEZ** [comment]
It does seem, from that link, that Calva will be quite incompatible with Ultra. However, it also seems like we need some way to specify profiles to exclude with jack-in.

**Comment by svdo** [comment]
I just came across this issue. I'm not sure what the original poster's use case was, but for me what I would really want to have is the way ultra prints test output, specifically not only the expected and actual, _but also the diff_. Would that be easier somehow, possibly with another lib that maybe Ultra also uses for this purpose or something? Maybe https://github.com/lambdaisland/deep-diff2, the library that is used by Kaocha.

**Comment by bpringe** [comment]
Without looking more into it atm, I think it would be possible. Maybe even fairly easy to add to the test runner. Please submit a feature request if you'd like. Although, maybe making ultra work with Calva could be simpler, I'm not sure.

**Comment by PEZ** [comment]
I'll be closing this because it is tricky to take action on as it stands. I've heard other people wishing for better test results diffing. If there isn't an issue for that already, please feel invited to file one.

**Comment by bpringe** [comment]
Here's an issue for that: https://github.com/BetterThanTomorrow/calva/issues/1007
