### ISSUE TITLE
completion lag with latest clojure-lsp

### ISSUE THREAD

**Issue by zxx457** [BetterThanTomorrow/calva#2070]
I tried both windows and linux platform , the results are the same

[clojure-lsp 2023.01.26-11.08.16](https://github.com/clojure-lsp/clojure-lsp/releases/tag/2023.01.26-11.08.16), When using this newest version, the completion just slow , very lag. 

But when I switch to a older version it's work fine. And I also tried clojure-lsp nightly version, it works fine too.

openjdk 17.0.6 2023-01-17

**Comment by PEZ** [comment]
Hi! Thanks for reporting. Is this issue known to the clojure-lsp team?

**Comment by julienvincent** [comment]
This was an upstream issue in clojure-lsp and was resolved in https://github.com/clojure-lsp/clojure-lsp/issues/1487 - it hasn't yet been released yet though. @PEZ this one can probably be closed.
