### ISSUE TITLE
Can't delete prior word in clojure project using mac os

### ISSUE THREAD

**Issue by milhamh95** [BetterThanTomorrow/calva#2079]
I have an issue where I couldn't delete the prior word using `alt + delete` shortcut in clojure project using mac os.

In mac os we can delete prior word using `alt + delete` shortcut. I'm able to delete prior word with `alt + delete `shortcut using vscode and another programming language (javascript, go)

Is there any configurations that I need to change?

![CleanShot 2023-02-11 at 08 49 56](https://user-images.githubusercontent.com/25811761/218233827-4d09cb1d-e93b-4e1c-a8f7-ed6ef2c2ebbd.gif)

**Comment by milhamh95** [comment]
found the shortcut `select backward up sexp`

**Comment by PEZ** [comment]
Hi! The closest structural command is **Kill Sexp Backwards** `ctrl+alt+backspace`. You can find all Paredit commands and their default bindings here: https://calva.io/paredit/

I seldom need to delete words in the non-structural sense, but the command is still there in VS Code, and you can bind it to some keys.

Those words in your image are not forms/sexpressions, btw. Clojure uses double quotes for strings. So the commands for moving/selecting/deleting sexps won't work in that particular example.

Calva has a command for introducing you to Calva and Clojure. **Fire up the Getting Started REL**. Please give it a spin!
