### ISSUE TITLE
[2.0] Jack-in sometimes does not find nrepl port file

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#208]
Only sometimes (seems to be random) the nrepl port file is not found when I run the jack-in task. I get the following:

```
Jacking in...
No nrepl port file found. (Calva does not start the nrepl for you, yet.) You might need to adjust "calva.projectRootDirectory" in Workspace Settings.
```

But then I see the `.nrepl-port` file and I add the port from the file into the connect prompt at the top of the window and it connects and opens the new REPL window. Perhaps there could be a timing issue / race condition happening? I think it works correctly most of the time, but maybe sometimes the file is not quite ready when it tries to read it.

**Comment by cfehse** [comment]
@bpringe  @PEZ 

This issue should be fixed with version 2.0.48.  There was an exception in the watch process for the port file under some circumstances. This should be fixed.

**Comment by bpringe** [comment]
Awesome. Thanks for all your work @cfehse!

**Comment by PEZ** [comment]
I second that! So many improvements all over the product.
