### ISSUE TITLE
Monorepo setup working on `v2.0.333`, broken on `v2.0.334`

### ISSUE THREAD

**Issue by simonacca** [BetterThanTomorrow/calva#2088]
Hi there,
first off thanks to all that contributed to the recent monorepo setup troubleshooting!

Unfortunately I have some issues with our monorepo setup in `v2.0.334` which were also there in `v2.0.332` but used to be solved by `v2.0.333`.

I've set up a repo that reproduces the issue [here](https://github.com/simonacca/calva-monorepo-repro) please see the readme over there for details of the issue.

Before spending time to look into the specifics of the issue, is this kind of setup something that should be supported by Calva as-is? Or is some other config step (like a top-level `deps.edn`?) required?

Thanks in advance!
Simon

<details><summary>Issue details and repro steps also here</summary>

# How the repo is structured

```
repo-root
├── libs
│   ├── lib1
│   │   ├── deps.edn
│   │   └── src
│   │       └── mycorp
│   │           └── lib1
│   │               └── core.clj
│   └── lib2
│       ├── deps.edn
│       └── src
│           └── mycorp
│               └── lib2
│                   └── core.clj
├── project1
│   ├── deps.edn
│   ├── project1.code-workspace
│   └── src
│       └── mycorp
│           └── project1
│               └── core.clj
├── project2
│   ├── deps.edn
│   ├── project2.code-workspace
│   └── src
│       └── mycorp
│           └── project2
│               └── core.clj
└── README.md
```

The repo has a top level *"libs"* folder containing units of reusable code. Each lib
has its own `deps.edn`.

The repo also has top level *"projects"* folders (in this case just `project` but you can imagine multiple ones)
which represent units of deployment (i.e. an "application" that one might want to actually compile,package and deploy on its own).

To provide a more ergonomic view on an otherwise unwieldy repo, 
each project folder has a vscode workspace file with many values in the `folders` entry,
listing the project folder itself and all libraries relevant to the current project.
See `project1/project1.code-workspace` for example.

# Expected behavior

As of calva `2.0.333`, if we either:
- manually start the LSP server in the repo root
- add `"calva.enableClojureLspOnStart": "when-file-opened-use-furthest-project"` to a workspace (like the one listed above)

The whole repo is "covered" by the LSP, meaning that one can for example:

- open `project1/src/mycorp/project1/core.clj`
- move the cursor to `mycorp.lib2.core`
- get all usual LSP functionality on all symbols in this namespace
- hit "jump to definition" in vscode
- get to `libs/lib2/src/mycorp/lib2/core.clj`
- get all usual LSP functionality on all symbols in this namespace
- get to `libs/lib1/src/mycorp/lib1/core.clj`
- get all usual LSP functionality on all symbols in this namespace

# Observed behavior

As of calva `2.0.334`, if we either:
- manually start the LSP server in the repo root
- add `"calva.enableClojureLspOnStart": "when-file-opened-use-furthest-project"`

No LSP server functionality is available in any of the namespaces.

Switching back to `2.0.333` restores functionality.

</details>

**Comment by PEZ** [comment]
Hi! Thanks for reporting! I'm short of time right now so can't analyze your excellent description. Will do that later. For now, suffice to say that the behaviour of 333 is supposed to be the coming behaviour of Calva, minus the bugs it created for Windows users. 334 is identical with 332 and only temporary there until we have sorted the issues with 333 out.

Your project description and expectations and such will be super helpful for us. If you can create a public repro with that setup, and a README with the info you have provided here, that would be super great. Even better if you add it as PR on Calva, we have a directory `test-data/projects` for things like this where this would fit great. If you do this, treat it as a documentation contribution, the PR template should guide you to what that means.

**Comment by simonacca** [comment]
Sounds good, thanks for the quick reply! Will add the repro to `test-data/projects` :+1:
