### ISSUE TITLE
[2.0.3] Can't connect on Windows

### ISSUE THREAD

**Issue by johnjelinek** [BetterThanTomorrow/calva#209]
I've tried the latest calva on Windows 10 where I try to connect locally and then via a remote tunnel. Both work in legacy calva, both don't in latest calva.

**Comment by qassim** [comment]
I'm seeing a similar issue on macOS with the new Calva - can't connect to my local `lein repl` instance. Going back to the legacy extension works fine.

**Comment by PEZ** [comment]
Can you give some more info for reproduction of this? Things like what kind of project it is. How you start the repl and what you do to connect.

Also, have you tried if Jack-in works?

I have started a wiki page for collecting connection problem troubleshooting and workarounds: https://github.com/BetterThanTomorrow/calva/wiki/Troubleshooting-connection-problems Not that it can help you with these probelms right now, but just reminding us to update that page if we do manage to figure this out.

**Comment by johnjelinek** [comment]
Actually, this is the experience I get in all OSes atm (mac, win, linux)
![no-jack-in](https://user-images.githubusercontent.com/873610/59153850-f5953780-8a29-11e9-9211-46a8053724a1.gif)

**Comment by johnjelinek** [comment]
it never connects with the latest extension, but continues to work fine in the legacy one.

**Comment by johnjelinek** [comment]
and I can't Jack-In because of https://github.com/BetterThanTomorrow/calva/issues/214

**Comment by johnjelinek** [comment]
I can jack-in now, I can also connect to an existing repl environment, but this is still dependent on me making a workspace where `deps.edn` lives in the root.

**Comment by PEZ** [comment]
Thanks for the update. I have now moved the trouble-shooting info on the wiki here: https://github.com/BetterThanTomorrow/calva/wiki/About-Calva-Jack-in

And included this about the workspace root and project root being the same.

Does that information help you connect, @qassim ? If not, please open a new issue and provide your reproduction steps.
