### ISSUE TITLE
Tab to reindent should pull the start of a top level expression to the left margin

### ISSUE THREAD

**Issue by lspector** [BetterThanTomorrow/calva#2096]
Using tab to reindent a definition doesn't pull the start of a top level expression to the left margin, which it should.

What I mean is that if I have for example a defn at the top level of my file, but the first line has for some reason been indented, then (assuming the definition is complete, with balanced brackets) tab will make the indention consistent with the top line, but not first pull that top line all the way to the left.

While this probably doesn't happen much in the workflow of experienced coders, in my experience as a teacher of beginners I see it happening regularly. For these newcomers, tab-to-reindent is particularly important, so it'd be great if it was more reliable. One situation in which this occurs is when copying code from within a rich comment and pasting it outside of the rich comment. Cutting/pasting/editing strategies of some beginners cause it to happen also in other situations, sometimes with more extreme indentation. (I am not sure what the histories are in all cases, but I see the badly indented results, which tab does not fix.)

Newcomers bring all sorts of unexpected typing/cutting/pasting habits with them, and it'd be great if tab would fix the indentation no matter what, ideally both in the kind of case described here (complete definitions, but with the first line incorrectly indented) and when definitions are not yet complete or have other bracket matching issues (see issues [1420](https://github.com/BetterThanTomorrow/calva/issues/1420) and [1709](https://github.com/BetterThanTomorrow/calva/issues/1709)).

**Comment by PEZ** [comment]
Thanks!

A good command to learn in Calva is **Expand Selection**. On Mac it is default bound to `ctrl+w`. Without an existing selection it will first select the ”current” form. Then it's sibling forms, then the parent form.

Given this code, and cursor at `|`:

```clojure
(comment
  |(defn get-samples [sound]
    (let [audio-file (java.io.File. sound)
          audio-stream (AudioSystem/getAudioInputStream audio-file)
          audio-format (.getFormat audio-stream)
          buffer (audio-stream-to-buffer audio-stream)]
      (buffer-to-samples buffer audio-format)))
  
  (println "Hello")
  :rcf)
```

<kbd>Expand Selection</kbd> will select the definition of `get-samples`. 

With this (cursor at `|` beside `.getFormat`):

```clojure
  (defn get-samples [sound]
    (let [audio-file (java.io.File. sound)
          audio-stream (AudioSystem/getAudioInputStream audio-file)
          audio-format (.getFormat| audio-stream)
          buffer (audio-stream-to-buffer audio-stream)]
      (buffer-to-samples buffer audio-format)))
  
  (println "Hello")
  :rcf)
```

<kbd>Expand Selection</kbd> nine times will also select the `get-samples` definition.

Telling you this because *Expand Selection* is an easy way to select complete forms, and without extra whitespace. Which can then be copied and pasted with less issues.

**Comment by lspector** [comment]
Thanks @PEZ. This is a good thing to know. That said, the motivation here is to let students use their existing editing skills, and not have to learn new ways to type or even select things. That's why it will be so helpful for tab-to-reindent to work correctly in more situations.

Incidentally, I mentioned this issue to a colleague at another institution after I posted it, and he said he saw this issue 10 or 15 times in his most recent class. We are both teaching undergraduate courses that use Clojure, which most of the students have never seen before, but the courses are not primarily about Clojure or software development (they're about AI). These students will have taken a few CS courses but not necessarily have the same skills or motivations as people setting out to become Clojure developers.

**Comment by PEZ** [comment]
I'm not arguing with the request in the issue here, @lspector. 😄 Just sharing some knowledge that can help you and your students have a better time with Calva copy/paste.

**Comment by lspector** [comment]
@PEZ: Understood and I am really grateful for this along with everything else you are doing!
