### ISSUE TITLE
Document Calva's automatic downloading of new versions of deps.clj

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#2097]
Sometimes when developing, a new version of the deps.clj.jar file will be downloaded and added to the Calva repo, and the deps-cljs-version file will be updated.

These files should be committed and a changelog entry added for the update.

We should note this in the wiki.

@PEZ Should this process be a more manual one that we run ourselves sometimes to update deps.clj so contributors don't have to worry about this while working on some other changes, or do you think it's fine how it is?

I was surprised when this happened to me, and even if we add it to the wiki, contributors who have already read it in the past before we updated it might still be surprised, and probably not all new contributors are going to read all of that part of the wiki.

Not making this happen automatically might reduce some confusion and questions directed at us over time.

**Comment by PEZ** [comment]
It's an effect of that we dynamically update deps.clj for end users. Which I think we should continue to do.

**Comment by bpringe** [comment]
I think if we wanted we could keep the end-user download feature but also not make some need-to-commit artifact be sometimes downloaded while developing Calva. However, maybe it's not worth doing that / not very important.

**Comment by PEZ** [comment]
As long as we both want to bundle deps.clj and do OTA update, it's not super obvious how to avoid this. I like to update the changelog with the bundle updates, to help with finding sources of any error. I guess we could let CI handle it, but it is more work than documenting the current behaviour. =)

**Comment by PEZ** [comment]
I documented this on the wiki now.
