### ISSUE TITLE
[FR] [REPL Windows] Allow using of ⌥+← / ⌥+→ to jump one word at a time in REPL window

### ISSUE THREAD

**Issue by AlexVPopov** [BetterThanTomorrow/calva#210]
In the REPL window, after a command has been sent, it can be brought back again by pressing ⌥+↑. However, currently it is not possible to use ⌥+← or → to jump the cursor one word at a time, which makes editing commands a bit harder. It would be good, if it's possible to use the standard shortcut to jump between words.

**Comment by vorou** [comment]
Looks like they're binded to something else, ⌥+← removes characters to the left and removes the brackets.

But I couldn't find any mappings for it in VS Code settings, so I guess it's a REPL shortcut.

**Comment by PEZ** [comment]
Is that really `alt+left`? Sounds strange that it would remove characters. (Not at a computer so I can try it.)

**Comment by PEZ** [comment]
OMG. Now I tested it. You're right @vorou! I also notice that `alt+right` sometimes adds characters.

**Comment by PEZ** [comment]
So, I found what was going on `alt+left/right` were bound to **splice and kill backward/forward**. I now moved them to `ctrl+alt+backspace/delete`.

To somewhat honour @AlexVPopov's suggestion I assigned **move backward/forward sexp** to `alt+left/right`. Maybe I should have made it `ctrl+alt+left/right` as it is in the editors, but figured we can do that later, when we have fixed the **move by a word** thing.

**Comment by bpringe** [comment]
I want to post this here as it might provide some updates on recent related changes, and clarity: https://calva.readthedocs.io/en/latest/paredit.html

What is meant here by moving a "word?" In my mind this is accomplished by the forward and backward sexp commands.
