### ISSUE TITLE
Calva crashes when editing new file without namespace

### ISSUE THREAD

**Issue by roskenet** [BetterThanTomorrow/calva#211]
Editing a file without a namespace leads to a freezing calva repl.

Reproduceable:
1. Open a leininigen project folder and a Calva REPL
2. Add a new file
3. Start to edit it by typing:
(d

Now the REPL is dead.
Workaround for me is to copy and paste (ns mynamespace) into the new file first.

Version: 1.35.0
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:13:26.790Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-16-generic

Perhaps somehow related to #189 ?

**Comment by PEZ** [comment]
Thanks for catching and reporting this! I was stubbornly going down the first list found in the file and if there were no `ns` form there, I got stuck at the closing paren. I've just released `2.0.5` which fixes this in my testing. If it works for you too, please close this issue.

**Comment by roskenet** [comment]
Thanks a lot! Seems to be fixed!
