### ISSUE TITLE
Clojure Language Client: couldn't create connection to server. Internal Error.

### ISSUE THREAD

**Issue by h806131** [BetterThanTomorrow/calva#2112]
> lein -v
Leiningen 2.10.0 on Java 17.0.5 Java HotSpot(TM) 64-Bit Server VM

I have downloaded the clojure-lsp.exe.
I'm a novice at clojure and thank you for your help.
![O(TEY)O$6X)%0%749Z_UA_A](https://user-images.githubusercontent.com/125721284/225269028-2df9ae13-f132-464e-8d4d-7c40763df841.png)

**Comment by PEZ** [comment]
Hi! Have you set `"calva.clojureLspPath"` to point at the clojure-lsp.exe you have downloaded? See here for some more on this: https://calva.io/clojure-lsp/#using-a-custom-clojure-lsp

**Comment by h806131** [comment]
> 

I have set it.
C:\Users\h806131\.vscode\extensions\betterthantomorrow.calva-2.0.337\clojure-lsp.exe

**Comment by h806131** [comment]
> Hi! Have you set `"calva.clojureLspPath"` to point at the clojure-lsp.exe you have downloaded? See here for some more on this: https://calva.io/clojure-lsp/#using-a-custom-clojure-lsp

I have set it.
C:\Users\h806131.vscode\extensions\betterthantomorrow.calva-2.0.337\clojure-lsp.exe

**Comment by h806131** [comment]
> Hi! Have you set `"calva.clojureLspPath"` to point at the clojure-lsp.exe you have downloaded? See here for some more on this: https://calva.io/clojure-lsp/#using-a-custom-clojure-lsp

I have set it.
C:\Users\h806131\.vscode\extensions\betterthantomorrow.calva-2.0.337\clojure-lsp.exe

**Comment by PEZ** [comment]
That's where Calva downloads the default client. I am assuming the reason you are downloading your own executable is that the Calva download doesn't work? If so, place the executable somewhere else and point Calva to the new location. Otherwise I think maybe Calva will overwrite it with it's failed download.

**Comment by h806131** [comment]
> 

Oh, I downloaded clojure-lsp.exe and then moved it to the default path. It couldn't start and then I set the `"calva.clojureLspPath"`. But it still couldn't start…

> 

Oh, I downloaded clojure-lsp.exe and then moved it to the default path. It couldn't start and then I set the `"calva.clojureLspPath"`. But it still couldn't start… Should I move it to other path and reset the `"calva.clojureLspPath"`?

**Comment by h806131** [comment]
> That's where Calva downloads the default client. I am assuming the reason you are downloading your own executable is that the Calva download doesn't work? If so, place the executable somewhere else and point Calva to the new location. Otherwise I think maybe Calva will overwrite it with it's failed download.

Oh, I downloaded clojure-lsp.exe and then moved it to the default path. It couldn't start and then I set the "calva.clojureLspPath". But it still couldn't start… Should I move it to other path and reset the "calva.clojureLspPath"?

**Comment by PEZ** [comment]
> Should I move it to other path and reset the "calva.clojureLspPath"?

Yes. I think that might be the issue.

**Comment by h806131** [comment]
> > Should I move it to other path and reset the "calva.clojureLspPath"?
> 
> Yes. I think that might be the issue.

![BAE99}3{H0GDQO UJ{`{LHH](https://user-images.githubusercontent.com/125721284/225322880-a994c16a-d635-4078-ab71-2e867b0df124.png)
I have moved clojure-lsp to the path that the image displays. It still doesn't work.🤕

**Comment by h806131** [comment]
> > Should I move it to other path and reset the "calva.clojureLspPath"?
> 
> Yes. I think that might be the issue.

It's the version of my clojure-lsp.
![I0N$R4`}19(Q@A0KI%Z$~~F](https://user-images.githubusercontent.com/125721284/225325121-0901b862-e6b1-4b7e-811d-e1f60e89c13e.png)

**Comment by PEZ** [comment]
In VS Code, from the Help menu, you can open the development tools/console. Maybe you can see there any error messages that might give us a clue.

Is your Leiningen project working otherwise? Thinking that it could be something with that, tripping clojure-lsp up.

**Comment by h806131** [comment]
> In VS Code, from the Help menu, you can open the development tools/console. Maybe you can see there any error messages that might give us a clue.
> 
> Is your Leiningen project working otherwise? Thinking that it could be something with that, tripping clojure-lsp up.

My leiningen project can work.
![)NSH5F`D`JP78O01QJ1$6P2](https://user-images.githubusercontent.com/125721284/225334489-9c33142c-c180-46e8-b37f-0af040ec585e.png)

**Comment by h806131** [comment]
> In VS Code, from the Help menu, you can open the development tools/console. Maybe you can see there any error messages that might give us a clue.
> 
> Is your Leiningen project working otherwise? Thinking that it could be something with that, tripping clojure-lsp up.

![DTYS6DJ3H9D00$ VUKTE(OD](https://user-images.githubusercontent.com/125721284/225334683-356eca3b-369d-4ab0-b267-63a77ebfa045.png)
![GM 8Y42B168$U%J5AF`Z57Y](https://user-images.githubusercontent.com/125721284/225334744-caf6f4c1-dfa9-4154-9a26-2f79529befb5.png)

**Comment by PEZ** [comment]
> > In VS Code, from the Help menu, you can open the development tools/console. Maybe you can see there any error messages that might give us a clue.
> > Is your Leiningen project working otherwise? Thinking that it could be something with that, tripping clojure-lsp up.
> 
> My leiningen project can work. ![)NSH5FDJP78O01QJ1$6P2](https://user-images.githubusercontent.com/125721284/225334489-9c33142c-c180-46e8-b37f-0af040ec585e.png)

Looks strange that you change directory to `src/hello` before you do `lein run`. Where is your project.clj located, and which folder do you open in VS Code?

**Comment by h806131** [comment]
> > > In VS Code, from the Help menu, you can open the development tools/console. Maybe you can see there any error messages that might give us a clue.
> > > Is your Leiningen project working otherwise? Thinking that it could be something with that, tripping clojure-lsp up.
> > 
> > 
> > My leiningen project can work. ![)NSH5FDJP78O01QJ1$6P2](https://user-images.githubusercontent.com/125721284/225334489-9c33142c-c180-46e8-b37f-0af040ec585e.png)
> 
> Looks strange that you change directory to `src/hello` before you do `lein run`. Where is your project.clj located, and which folder do you open in VS Code?

Oh, changing directory is really unnecessary. I open the folder `D:\VScode\Clojure\hello` in VS Code and my `project.clj` located here.

**Comment by bpringe** [comment]
Do you have this issue in other projects? Can you provide a link to a minimal project where you can reproduce the issue?

**Comment by PEZ** [comment]
It seems to be a minimal project. Named **hello** and all. 😄 Would be really great with a public repository.

**Comment by h806131** [comment]
> It seems to be a minimal project. Named **hello** and all. 😄 Would be really great with a public repository.

Because I am a mere beginner. 😄I used `lein new app hello` to create a new project and opened the folder in VS Code. Then this error occurred.

**Comment by bpringe** [comment]
@PEZ Maybe you can try to reproduce this in a Windows VM?

**Comment by h806131** [comment]
> It seems to be a minimal project. Named **hello** and all. 😄 Would be really great with a public repository.

Oh, I found the reason. I set Java path in PATH environment variable wrongly. Now the lsp works.
