### ISSUE TITLE
Jack-in fails with version 2.0.337

### ISSUE THREAD

**Issue by cmaussan** [BetterThanTomorrow/calva#2113]
Jack-in is not working anymore, Calva can't connect to nREPL server whereas it is correctly launched.

```
; This is the Calva evaluation results output window.
; TIPS: The keyboard shortcut `ctrl+alt+o o` shows and focuses this window
;   when connected to a REPL session.
; Please see https://calva.io/output/ for more info.
; Happy coding! ♥️

; Jacking in...
; Connecting using "deps.edn" project type.
; You can make Calva auto-select this.
;   - See https://calva.io/connect-sequences/
; 
; Starting Jack-in Terminal: clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"1.0.0"},cider/cider-nrepl {:mvn/version,"0.28.5"}}}' -M:dev -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
; Using host:port localhost:44071 ...
; Hooking up nREPL sessions ...
; Failed connecting.
; Jack-in done.
clj꞉undefined꞉>  ; Use `alt+enter` to evaluate
```
Downgrading to 2.0.336 fixes the issue.

**Comment by cmaussan** [comment]
ctrl+c in pseudo terminal does not really kill the repl either. A `ps` launched in another terminal shows the repl still up.

**Comment by PEZ** [comment]
Thanks for reporting!

Some questions:

* If you use the command **Calva: Copy Jack-in Command Line to Clipboard** and use that to start the repl and then connect Calva, does that work?
* Can you reproduce this in a minimal project?
* What OS are you using?


> ctrl+c in pseudo terminal does not really kill the repl either. A `ps` launched in another terminal shows the repl still up.

Extra interesting, it was one of the things I thought I improved with this version. I just tried in a project here:

1. After jack-in:
    ```
    % lsof -d cwd | grep 'java.*'"$PWD"                                   
    java      64431  pez  cwd    DIR   1,17      928 111060084 /Users/pez/Projects/poly-real-world
    % 
    ```
2. <kbd>ctrl+c</kbd> in the jack-in terminal:
    ```
    % lsof -d cwd | grep 'java.*'"$PWD"                                   
    %
    ```

It might be that the two errors are related, of course.

**Comment by cmaussan** [comment]
- I launched the repl by hand in a terminal and tried to connect to it with "connect to a running repl in your project" or "connect to a running repl, not in your project". Both did not work.
- It was failing in all my clojure projects
- Ubuntu 22.10

1. After jack-in
```
$ lsof -d cwd | grep 'java.*'"$PWD"
java      15651         cmaussan  cwd       DIR  253,1     4096 12072379 /home/cmaussan/code/foo
```

2. After `ctrl+c` in jack-in terminal
```
$ lsof -d cwd | grep 'java.*'"$PWD"
java      15651         cmaussan  cwd       DIR  253,1     4096 12072379 /home/cmaussan/code/foo
```

Hope that helps you.

**Comment by PEZ** [comment]
Thanks! Does **connect to a running repl in your project** work in v2.0.336?

**Comment by PEZ** [comment]
And, does ctrl+c work in 336? Thinking it could be this issue:

* https://github.com/BetterThanTomorrow/calva/issues/1544

(Which does not have a solution yet.)

**Comment by cmaussan** [comment]
> Thanks! Does **connect to a running repl in your project** work in v2.0.336?

Yes!

> And, does ctrl+c work in 336? Thinking it could be this issue:

It works! (that's why I noticed it in 337)

**Comment by PEZ** [comment]
> ctrl+c in pseudo terminal does not really kill the repl either. A `ps` launched in another terminal shows the repl still up.

Hi again! The connection issue should be fixed in 338. Can you check if this one still is left to fix?

**Comment by cmaussan** [comment]
Hello!
Yes, the connection issue is fixed. But `ctrl+c` in the terminal still does not kill the repl.

**Comment by PEZ** [comment]
Thanks. We track it here now:
* https://github.com/BetterThanTomorrow/calva/issues/2116
