### ISSUE TITLE
Legacy indent engine: indent on return is broken

### ISSUE THREAD

**Issue by sirmspencer** [BetterThanTomorrow/calva#2114]
I suspect its related to this https://github.com/BetterThanTomorrow/calva/pull/2110

I think instead of only the top level indent aligning all the way the left margin, and form is.  Also if I am at the head of the parens, tab no longer auto formats like it used to (and still does for the tail of the parens)

Note, I use cljfmt and not the new indent engine.

**Comment by bpringe** [comment]
Thanks for reporting! CC @PEZ

**Comment by PEZ** [comment]
I want to chime in with the thanks for reporting! I'm not sure I understand the details of this, but it does sound like something that could be an effect of the #2110 fix. @sirmspencer, can you share an example? In text. Something like:

With this code (cursor at `|`):

```clojure
(foo bar|)
```

<kbd>return</kbd>

Expected:
```clojure
(foo bar
  |)
```

Actual:
```
actual result
```

**Comment by sirmspencer** [comment]
```
(defn example []
  (if true |(inc 1) (inc 2)))
```
`return`

Expected
```
(defn example []
  (if true
    (inc 1)
    (inc 2)))
```

Actual
```
(defn example []
  (if true 
(inc 1) (inc 2)))
```

**Comment by PEZ** [comment]
Thanks! I can reproduce.

**Comment by PEZ** [comment]
@sirmspencer, Can you confirm that this VSIX fixes the issue?

* https://output.circle-artifacts.com/output/job/94fa2c17-3e92-4c92-b716-4c72f3846cc1/artifacts/0/tmp/artifacts/calva-2.0.339-2114-toplevel-indent-bug-a7408a29.vsix

To install it, you download it, and ensure that it still has a `.vsix` extension. Then from the Extension pane in VS Code, in the top meatballs menu, select **Install from VSIX...**.

**Comment by sirmspencer** [comment]
That worked!  Do you know if the extension will still update after that install?
