### ISSUE TITLE
Stopping Jacked-in REPL process doesn't kill Unix Java process

### ISSUE THREAD

**Issue by k3nj1g** [BetterThanTomorrow/calva#2116]
Enviroment:
```
VSCode: latest
WSL2: Ubuntu 18.04
Calva: v2.0.338
```

Checked on a minimal project:
Run Jack-in process via `deps.end` project-type.
`ps -a`  shows java process.
Then `ctrl + c` in Calva terminal followed with `ps -a` and java process is still there.

**Comment by PEZ** [comment]
I can't reprodice this neither on my Mac nor on my Fedora machine. My repro attempt:

1. Jack-in
1. ```
    $ lsof -d cwd | grep 'java.*'"$PWD"
    java      359036             pez  cwd       DIR   0,40      108 1203447 /home/pez/Projects/calva/test-data/projects/pirate-lang
    $
    ```
1. <kbd>ctrl+c</kbd> in the jack-in terminal
1. ```
    $ lsof -d cwd | grep 'java.*'"$PWD"
    $
    ```

Wondering if it could be specific to Ubuntu.
