### ISSUE TITLE
REPL automatically switches back to `user` namespace

### ISSUE THREAD

**Issue by svdo** [BetterThanTomorrow/calva#212]
Hi,

First thanks PEZ for Calva! I'm new to Clojure and chose to use VSCode and Calva and was very happy. Now with v2 I'm even happier, very well done.

I have a strange "phenomenon": I'd like to use the setting "Sync REPL namespace to current file" but it causes strange behaviour. I have a Leiningen project (created with `lein new app`, nothing special about it). I then use jack-in to start a REPL. I have the source code and the REPL side-by-side. Now when I'm in the source code, I see the REPL namespace switch to that of the source code file, as expected. So far so good. Now when I click in the REPL window to try some things directly from the REPL, immediately on clicking in the REPL window its namespace changes back to `user`. Click source file, changes to my namespace, click REPL, changes back to `user`.

I'm assuming this is a bug, but if I'm doing something wrong please don't worry about hurting my feelings ;)

**Comment by svdo** [comment]
I made a video of the behaviour and noticed that the behaviour I'm describing is not 100% consistent. The video visualises the mouse clicks so that you can better see what I mean. I'll drop the video in Slack #calvadev if you don't mind, not sure where to put it otherwise (I don't want to create an account on any of the video-sharing web sites).

**Comment by PEZ** [comment]
Thanks! I think I know what's going on. It's not you!

**Comment by PEZ** [comment]
Thanks for reporting this! Version `2.0.5`, just released, should fix this. Please close this issue if that checks out for you.

**Comment by svdo** [comment]
Wow, that's fast, I'll check in a moment!

**Comment by svdo** [comment]
Superb, it works. 👏
