### ISSUE TITLE
Notebook nrepl integration flag

### ISSUE THREAD

**Issue by Cyrik** [BetterThanTomorrow/calva#2133]
Calva notebooks currently send a normal `eval` message to nrepl when running a cell.
Setting a special flag would make it possible for integrations like Portal to have special handling for them in the middleware.
Set the `'nrepl.middleware.eval/env': { 'calva-notebook': true, notebook: true }` for all notebook evals.

**Comment by bpringe** [comment]
Closing this manually now since the issue wasn't mentioned in a commit for the PR.
