### ISSUE TITLE
Cannot find project

### ISSUE THREAD

**Issue by johnjelinek** [BetterThanTomorrow/calva#214]
> Cannot find project, no project.clj, deps.edn or shadow-cljs.edn. (Boot projects are not supported by Jack-in yet. You'll need to start those manually, then connect Calva.

```
tree .
.
├── deps.edn
└── src
    └── kashoo
        └── core.clj

2 directories, 2 files
```

I have the `deps.edn` file in my editor up as the active file at the time I run `Start a project REPL and Jack-In`

**Comment by johnjelinek** [comment]
I'm using the macOS `10.13.6` for this test.

**Comment by johnjelinek** [comment]
oic -- it expects this to not be executed from a subdirectory. I created a new workspace where the subdirectory is root and then started the repl/jack-in from that workspace and it connected. This was a helpful hint: https://github.com/BetterThanTomorrow/calva/blob/f82eaeb2b7ceb4c9dd8dea3177fb213cd48a61b3/calva/nrepl/jack-in.ts#L30

**Comment by PEZ** [comment]
Yes, this has been supported before, actually, but the implementation caused other problems, so I simplified it until I, or someone, has the time to do it properly.
