### ISSUE TITLE
Calva intercepts ctrl+alt, leaving me unable to create multiple cursors on Windows

### ISSUE THREAD

**Issue by HuntressRubyRose** [BetterThanTomorrow/calva#2166]
On windows, I'm no longer able to use the vscode shortcut to create multiple cursors using keyboard shortcuts within the editor.

**Comment by PEZ** [comment]
I'm not familiar with how `ctrl+alt` is related to creating multiple cursors. Can you elaborate a bit?

Though, it is just default keyboard shortcuts. You can change them to whatever you rather have. Either for the multiple cursors thing, or for whatever Calva command is conflicting.

**Comment by HuntressRubyRose** [comment]
My mistake, I missed paredit.backwardDownSexp and paredit.selectForwardDownSexp on my first pass of the settings

**Comment by PEZ** [comment]
The Shortcut editor is pretty good at finding commands by shortcut. Dunno if you tried that, but anyway.
