### ISSUE TITLE
[2.0] Colored output via ANSI does not work in new REPL window

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#217]
I have enabled ANSI colored output on windows with cmd. However, when I start the new Calva REPL window using cmd as the default shell, and I log an exception using timbre, I see the escape codes in the output.

![ANSI_colors](https://user-images.githubusercontent.com/12722744/59229746-dd93f400-8ba0-11e9-9bee-09d87550dc41.png)

I believe something would have to be changed through Calva to make this work. If I start a repl with `lein repl` in cmd and log in the terminal, the colors show correctly.

![ANSI_colors_2](https://user-images.githubusercontent.com/12722744/59229868-4aa78980-8ba1-11e9-84ac-be101563ff1e.png)

**Comment by PEZ** [comment]
Yes, the repl window does not understand ANSI codes at all. I don't really know how to fix that. Maybe @mseddon has an idea?

**Comment by PEZ** [comment]
Right, so I have figured it out. Can you try v`2.0.11`, @bpringe , and let me know if that fixes this for you. If it does, please close the issue.

**Comment by bpringe** [comment]
That works! Great job 👍
