### ISSUE TITLE
Unknown error message keeps popping up.

### ISSUE THREAD

**Issue by sirmspencer** [BetterThanTomorrow/calva#2173]
Whenever I am in an edn file, I get this error message.  I am using cljfmt with clojure-lsp.

![image](https://user-images.githubusercontent.com/33734037/234683083-41cf2ad3-4160-4a85-8f90-bfd2217831df.png)
 And the output 
![image](https://user-images.githubusercontent.com/33734037/234683183-0df11cb6-6b32-4e9e-ab6b-b7200497afe6.png)

**Comment by PEZ** [comment]
Related to #2165

**Comment by bpringe** [comment]
Also related issue and comment in the clojure-lsp issue: https://github.com/clojure-lsp/clojure-lsp/issues/1557#issuecomment-1523689817

You _might_ be able to get rid of those popups for now by using clojure-lsp version `2023.02.27-13.12.12` (set the `calva.clojureLspVersion` setting to that version).

**Comment by PEZ** [comment]
I believe this is fixed now, upstream?
