### ISSUE TITLE
Unable to run Clojure script

### ISSUE THREAD

**Issue by AGoh2019** [BetterThanTomorrow/calva#2174]
Type: <b>Bug</b>

Installed Leiningen REPL, Calva and all associated tools on VS Code.  Cannot run Hello World Clojure file.  Ask me to consider the command: **Calva: Fire up the Getting Started REPL** Calva version used: v2.0.353

Extension version: 2.0.353
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (8.08GB free)|
|Process Argv|--crash-reporter-id 878a6b85-9049-465e-849e-1cc9b3b95d57|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by PEZ** [comment]
Hi! I'm sorry you are having problems. It is unclear to me what is going wrong. Can you describe step by step what you do and what happens?

**Comment by AGoh2019** [comment]
Hi,
I start up VS Code, and I believe its after I open the Clojure file, that Calva is loaded as shown in the output window. When I start run without debugging the clojure file. I get two error messages -
a.  Variable ${workspace Root} can not be resolved. Please open a folderb.  Java language server being unable to start (a long lingering problem that is not fixed).
I hope this helps.

--- Andrew Goh
 

    On Thursday, 27 April 2023 at 12:46:41 pm SGT, Peter Strömberg ***@***.***> wrote:  
 
 


Hi! I'm sorry you are having problems. It is unclear to me what is going wrong. Can you describe step by step what you do and what happens?

**Comment by PEZ** [comment]
Hi again. I had missed that you commented, sorry for the delay.

> When I start run

What does this mean? From the error messages it seems like maybe you are trying to run the Clojure file via the *Run and Debug* panel. This is generally not the way to do it with Calva. And generally, a Java Language Server, is not involved.

What's your goal with this? Do you have a Clojure program that you want to run and debug, or are you trying to learn Clojure, or something else? It'll be easier for us to help you if we know what you aim at doing.

**Comment by AGoh2019** [comment]
Hi, I was just experimenting with Clojure.  I tried out simple examples using Leiningen and it runs. Would suggest that the Calva package be a all-in-one installation without the need for additional plugins on VS Code.
--- Andrew Goh
 

    On Wednesday, 10 May 2023 at 06:53:58 pm SGT, Peter Strömberg ***@***.***> wrote:  
 
 


Hi again. I had missed that you commented, sorry for the delay.


When I start run


What does this mean? From the error messages it seems like maybe you are trying to run the Clojure file via the Run and Debug panel. This is generally not the way to do it with Calva. And generally, a Java Language Server, is not involved.

What's your goal with this? Do you have a Clojure program that you want to run and debug, or are you trying to learn Clojure, or something else? It'll be easier for us to help you if we know what you aim at doing.

**Comment by PEZ** [comment]
> Would suggest that the Calva package be a all-in-one installation without the need for additional plugins on VS Code.

That's what Calva is. You don't need any other extensions. Did you find this page? https://calva.io/connect/

**Comment by PEZ** [comment]
@AGoh2019 it is still unclear to me where the bug is. I'm thinking it might be lack of documentation/guidance that tricks you into doing things that are not meant to work. If you have some time, I'd love to know in more detail what you tried to do and where things went wrong.
