### ISSUE TITLE
Custom Connect Sequences Menu Selections not working

### ISSUE THREAD

**Issue by rugbbyli** [BetterThanTomorrow/calva#2189]
With the document
> - menuSelections: a dictionary with pre-filled-in selections for the Jack-in and Connect prompts, making Calva not prompt for that particular selection:
>   - cljAliases: At Jack-in to a deps.edn project, use these aliases to launch the repl.

I expected it could auto select aliases when jack-in, while it's not. So I read the source code, and find this line to read aliases from menuSelections config:
https://github.com/BetterThanTomorrow/calva/blob/3de7693b0a5aebcf965c54fa7c110e0c1cba3e86/src/nrepl/project-types.ts#L588-L589
and this line show a menu to choose aliases found from deps.edn, simply override the variable (so make the config useless):
https://github.com/BetterThanTomorrow/calva/blob/3de7693b0a5aebcf965c54fa7c110e0c1cba3e86/src/nrepl/project-types.ts#L619-L624
Is this by design or not?

**Comment by PEZ** [comment]
Hi! We don't hit line 619 if there is config for cljAliases, because that's in the `else` from line 588. Unless I misunderstand what you are asking... We really should factor that code more tidy.

Do you still get that prompt even though you've configured `cljAliases`?

**Comment by rugbbyli** [comment]
Sorry for that mistake. You were right, I didn’t carefully look at the scope of the parentheses above. After restarting vscode, the problem was resolved, possibly due to some configuration synchronization issues.
