### ISSUE TITLE
Bug: Existing code is replaced when new file is saved

### ISSUE THREAD

**Issue by mrkam2** [BetterThanTomorrow/calva#2196]
Steps to reproduce:
- Create a new file using Cmd-N, don't save it.
- Type in some clojure code.
- Save it into your project's `src` folder.
- RESULT: The whole code is replaced with a namespace declaration, i. e. `(ns ...)`.

**Comment by PEZ** [comment]
I think this might be the same things as is observed in:

* #1900 

We tracked it down to an issue in VS Code, that was reported here:

* https://github.com/microsoft/vscode-languageserver-node/issues/1105

@bpringe Do you know if the fix has been released yet? And if we need to do anything to source in the fix, if so.

**Comment by mrkam2** [comment]
> I think this might be the same things as is observed in:
> 
> * [Saving an untitled file, naming it with a `.clj(s)` extension, wipes its content #1900](https://github.com/BetterThanTomorrow/calva/issues/1900)

Yes, that's the same issue.

**Comment by PEZ** [comment]
I'm closing this as a duplicate, then.

**Comment by bpringe** [comment]
> Do you know if the fix has been released yet? And if we need to do anything to source in the fix, if so.

It looks like it was fixed in 8.1.0 judging by what I see in the issue. I think we just need to update the language client dep.
