### ISSUE TITLE
2.0.359 broke custom REPL connect sequences

### ISSUE THREAD

**Issue by seancorfield** [BetterThanTomorrow/calva#2197]
From Slack:

Somewhere in a recent Calva update (prior to 2.0.360), my REPL connect sequences at work have broken:

```
  "calva.replConnectSequences": [
    {
      "name": "World Singles Backend (Jack-In)",
      "projectType": "deps.edn",
      "cljsType": "none",
      "autoSelectForJackIn": true,
      "projectRootPath": ["/var/www/worldsingles"],
      "menuSelections": {
        "cljAliases": ["build", "dev", "+default", "test", "vscode-calva-jack-in"]
      }
    },
    {
      "name": "World Singles Backend (Connect)",
      "projectType": "deps.edn",
      "cljsType": "none",
      "autoSelectForConnect": true,
      "projectRootPath": ["/var/www/worldsingles"]
    }
  ],
```

I'm guessing I missed some change based on the enhancements recently added? When I jack-in now, I get prompted for project type (and it only offers Babashka, nbb, and Joyride -- even though this is a JVM `deps.edn` project).

Confirmed working on 2.0.358. Broken on 2.0.359 and 2.0.360.

**Comment by seancorfield** [comment]
This is the breaking change:

```
  const projectRootPath: vscode.Uri = defaultSequence
    ? vscode.Uri.joinPath(
        vscode.workspace.workspaceFolders[0].uri,
        ...(defaultSequence?.projectRootPath ? defaultSequence.projectRootPath : [])
```

In the previous code, `projectRootPath` could be absolute but in this new code, it is always appended to the workspace folder path.

**Comment by PEZ** [comment]
This will be a bit tricky. The previous didn't work in Windows:

* https://github.com/BetterThanTomorrow/calva/issues/2190

When I fixed it I had forgotten why we did it that other way, though, so we are in a better place now at least, for finding the right solution.

**Comment by seancorfield** [comment]
#821 and #825 (the latter in particular) seem to be the root cause of the broken-on-Windows behavior.

I think `path.resolve()` is the key to handling an absolute `projectRootPath` tho'...?

**Comment by PEZ** [comment]
> I think `path.resolve()` is the key to handling an absolute `projectRootPath` tho'...?

Maybe. But it created a weird path that was half windows, half unix style and then the Output window creation croaked on that.

**Comment by PEZ** [comment]
This build should fix the issue:

* https://output.circle-artifacts.com/output/job/b583d97b-8c71-4f37-bdf6-4e9347e8df41/artifacts/0/tmp/artifacts/calva-2.0.361-2197-connect-sequence-abs-root-38b1d277.vsix

I've tested it on Windows with the [ClojureCLR starter project](https://github.com/PEZ/clojure-clr-starter), and it still works, so at least we're at a new place, hopefully the right one.

**Comment by seancorfield** [comment]
The change looks good in git. I'm installing the .vsix now...
