### ISSUE TITLE
Use of `calva.tellAboutNewChordingKey`

### ISSUE THREAD

**Issue by jefffriesen** [BetterThanTomorrow/calva#220]
There have been a few issues about the keybinding keys already (for example: https://github.com/BetterThanTomorrow/calva/issues/213). For me, `control-option-c` requires me to look down at the keyboard and completely reposition my hands to complete it. It's faster to search the dropdown menu. 

So I was re-binding keys through VSCode's UI (tedious but straightforward), I saw `calva.tellAboutNewChordingKey`. So I tried it and got this message:

```
the "Calva Key" has changed. It is now cntrl-alt-c
```

At first I thought it just undid all of the keybindings I just changed. But from testing, they stayed the same. But then I was wondering if it could make the "Calva key" anything I wanted. That would be nicer than rebinding everything. 

Is that possible?

Here's where I see it in the code: https://github.com/BetterThanTomorrow/calva/blob/987b12d40350318f300a45ab8361c204d6a19392/calva/extension.ts#L137

Thanks

**Comment by PEZ** [comment]
Hi there!

That command is just bound to `ctrl+alt+v` (which was the ”Calva key” previously). So nothing magic about it. :smile:

I don't think it is possible to make the start of the chords configurable. That would be very, very good, I agree.

Please consider sharing your keybindings json and linking it here: https://github.com/BetterThanTomorrow/calva/wiki/Customising-Calva#key-bindings

**Comment by jefffriesen** [comment]
@PEZ 

Thanks for your response. Makes sense.  I used WebWitch's keybinding of option-v instead of control-option-v, so my keybinding file isn't significantly different.  I'm closing this issue.
