### ISSUE TITLE
Cannot start a cljs REPL since version 2.0.355

### ISSUE THREAD

**Issue by furkan3ayraktar** [BetterThanTomorrow/calva#2200]
The newer versions of Calva are reporting the following when I Jack-in:
```
Error while connecting cljs REPL: class clojure.lang.Compiler$CompilerException
```
As a result, I cannot use the cljs REPL.
I rolled back my Calva version one by one and discovered that the REPL works as expected on version 2.0.355.
Here are the related parts of the settings.json:
```json
{...

  "calva.autoOpenJackInTerminal": true,
  "calva.autoConnectRepl": true,
  "calva.replConnectSequences": [
    {
      "projectType": "shadow-cljs",
      "name": "Start ShadowCLJS REPL",
      "autoSelectForJackIn": true,
      "projectRootPath": [
        "."
      ],
      "cljsType": "shadow-cljs",
      "menuSelections": {
        "cljsLaunchBuilds": [
          "frontend",
          "devcards",
          "test"
        ],
        "cljsDefaultBuild": "frontend"
      }
    },
    {
      "projectType": "deps.edn",
      "name": "Connect ShadowCLJS REPL",
      "autoSelectForConnect": true,
      "projectRootPath": [
        "."
      ],
      "cljsType": "shadow-cljs",
      "menuSelections": {
        "cljsDefaultBuild": "frontend"
      }
    }
  ],

...}
```

Shadow CLJS version: `2.20.12`

**Comment by PEZ** [comment]
Thanks. I can reproduce this. It seems to be related to a combination involving the connect sequences. If I set `autoSelectForJackIn` to `false` and choose `shadow-cljs` as project type, the connection works.

**Comment by PEZ** [comment]
Found it. We don't keywordize the builds with the new check for cljs runtimes. Your config starts to work if I prepend the builds with `:`, @furkan3ayraktar. Fix coming, but now you know how to dodge this bug.

**Comment by furkan3ayraktar** [comment]
Great to hear you were able to find! Thank you and tack!
