### ISSUE TITLE
Stop Run All in Clojure Notebooks from evaluating `comment` forms

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#2210]
[On Slack, @seancorfield noted](https://clojurians.slack.com/archives/C0185BFLLSE/p1685553266275099) that it is dangerous to do **Run All** in a Clojure Notebook, because it also evaluates Rich Comments Forms.

* Somewhat related discussion: https://github.com/BetterThanTomorrow/calva/discussions/1825

**Comment by seancorfield** [comment]
It needs to also skip RCFs in the "Execute Above Cells" and "Execute Cell and Below" commands.
