### ISSUE TITLE
`customJackInCommandLine` does not receive `JACK-IN-*` environment variables

### ISSUE THREAD

**Issue by Cortys** [BetterThanTomorrow/calva#2215]
I'm trying to write a custom jack-in script. The documentation states [the following](https://calva.io/connect-sequences/#custom-command-line-substitutionsplaceholdersenvironment-variables):
> All these placeholders will also be provided to your script via environment variables with the same names

For a project of type `deps.edn` I would therefore expect to have access to various environment variables named `JACK-IN-*`.
Though, for some reason this does not appear to work (tested on Ubuntu with zsh login shell). Minimal example:
```json
{
	"calva.replConnectSequences": [{
		"name": "test",
		"projectType": "deps.edn",
		"customJackInCommandLine": "env"
	}]
}
```

In the list of printed environment variables there are no `JACK-IN-*` variables.

While I have not checked whether this is the root cause here, environment variables containing dashes are, in any case, pretty uncommon and [not well supported by most shells](https://unix.stackexchange.com/questions/23659/can-shell-variable-name-include-a-hyphen-or-dash).

Maybe it would make sense to provide the `JACK-IN-*` vars as `JACK_IN_*` instead?

**Comment by PEZ** [comment]
> Maybe it would make sense to provide the `JACK-IN-*` vars as `JACK_IN_*` instead?

You are right, that makes sense.

Which shell are you using? I get this with `zsh`:

```
⚡️ Starting the REPL ⚡️ using the below command line:
pushd /Users/pez/Projects/calva/test-data/projects/shadow-w-backend ; env | grep JACK-IN-  ; popd
JACK-IN-CLJS-LAUNCH-BUILDS=:app
JACK-IN-CIDER-NREPL-VERSION=0.28.5
JACK-IN-NREPL-PORT-FILE=.shadow-cljs/nrepl.port
JACK-IN-PROJECT-ROOT-PATH=/Users/pez/Projects/calva/test-data/projects/shadow-w-backend
Jack-in process exited. Status: 0
```

**Comment by Cortys** [comment]
Interesting. I'm also using zsh (version 5.8) but inside WSL (Kernel `5.15.90.1-microsoft-standard-WSL2`). Since I don't have a "real" linux installation at hand right now I can't check but maybe this is the reason?

**Comment by PEZ** [comment]
Could be. Can you set environment variables using `calva.jackInEnv`?

**Comment by Cortys** [comment]
Yes, `calva.jackInEnv` works. I've also just tried a custom jack-in command on Windows and did not observe the issue (all vars are set correctly). So it could indeed be WSL specific.

**Comment by Cortys** [comment]
I just tried the following:
```json
"calva.jackInEnv": {
	"JACKA": "foo",
	"JACK-B": "bar"
}
```
The first variable is correctly set, the second one not, so it seems the issue is indeed caused by the dashes in the var name.

**Comment by PEZ** [comment]
Thanks! Let's use proper variable names.

**Comment by PEZ** [comment]
Can you test this VSIX and see that it fixes the issue? [tmp/artifacts/calva-2.0.368-2215-jack-in-env-underscores-8d84ad52.vsix](https://output.circle-artifacts.com/output/job/36fc0471-1436-4262-afd5-da9282aaf33b/artifacts/0/tmp/artifacts/calva-2.0.368-2215-jack-in-env-underscores-8d84ad52.vsix)

You can install it from the meatballs menu at the top of the extension pane.

<img width="697" alt="image" src="https://github.com/BetterThanTomorrow/calva/assets/30010/3688449f-29af-4bf1-80f3-991d4ae84fdf">

Also, sometimes it downloads with a `.zip` extension. If that happens, just rename it to `.vsix`.

**Comment by Cortys** [comment]
Nice. 👍 Yes, works as expected:
```
pushd /home/clemens/test; env | grep JACK  ; popd
JACK_IN_CLJ_MIDDLEWARE=cider.nrepl/cider-middleware
JACK_IN_CIDER_NREPL_VERSION=0.28.5
JACK_IN_CLI_ALIASES=:foo,:bar
JACK_IN_NREPL_VERSION=1.0.0
JACK_IN_NREPL_PORT_FILE=.nrepl-port
JACK_IN_PROJECT_ROOT_PATH=/home/clemens/test
Jack-in process exited. Status: 0
```
Thanks a lot for fixing this so quickly (and also for this awesome extension in general)!

**Comment by PEZ** [comment]
Thanks!

**Comment by PEZ** [comment]
Now released. Please keep your fingers crossed together with me that I didn't break too many users with this change. 🤞

**Comment by Cortys** [comment]
Awesome, thanks! 🤞 Will do
