### ISSUE TITLE
Calva extension always shows in status bar

### ISSUE THREAD

**Issue by Gr1N** [BetterThanTomorrow/calva#222]
Hi and thank you for the great extension.

But after update to the new version of Calva I always see nREPL and Paredit buttons in the status bar even if I use another language, e.g. Python. Are there any options to fix that?

[![image.png](https://i.postimg.cc/wMcM2Lzw/image.png)](https://postimg.cc/T51TYypb)

Thanks!

**Comment by PEZ** [comment]
It's a change I made to make Calva work w/o people first having to open a Clojure file, something lots of people didn't figure out.

But I think I can do it a bit smarter. Leaving this issue open to remind myself to look at it. Thanks for reporting!

**Comment by PEZ** [comment]
OK. So I have published a new version of Calva, `2.0.12`, that doesn't activate until you either open a Clojure file or tell it to start a REPL for you (or connect to a running REPL). It won't deactivate the extension once it has been activated, but I hope this is an improvement for you, @Gr1N?

**Comment by Gr1N** [comment]
Works as I expect! Thank you for the quick response and fix!
