### ISSUE TITLE
Jack-in error when selecting multiple shadow-cljs builds

### ISSUE THREAD

**Issue by svdo** [BetterThanTomorrow/calva#2220]
I have a mono repo with both front-end and backend. I use "deps.edn + shadow-cljs" as project type. In shadow-cljs, I have defined two builds (client and test) which I want to start watching both. When I select both in the Calva dialog that shows up during jack-in, I get this error in the Calva output:

```
; Creating cljs repl session...
; Connecting cljs repl: deps.edn + shadow-cljs...
;   The Calva Connection Log might have more connection progress information.
; Starting cljs repl for: deps.edn + shadow-cljs...
; shadow-cljs - HTTP server available at http://localhost:8889
; Execution error (AssertionError) at shadow.cljs.devtools.api/watch* (api.clj:173).
Assert failed: (map? opts)
```

The reason is that `shadow.cljs.devtools.api/watch` does not support passing more than one build.

PR coming up.

**Comment by PEZ** [comment]
Oh, wow. This could be the answer to a mystery with how the **deps.edn + shadow-cljs** connect sequence fails in ways I haven't been able to explain.
