### ISSUE TITLE
When pasting something with trailing space, it gets removed

### ISSUE THREAD

**Issue by mrkam2** [BetterThanTomorrow/calva#2229]
Steps to reproduce: copy `x ` (with a trailing space) and paste it in the cursor position denoted by `|` in the following function call: `(my-fn |y)` expecting to get `(my-fn x y)` but instead getting `(my-fn xy)`. Discussion in [slack](https://clojurians.slack.com/archives/CBE668G4R/p1687376528919539).

**Comment by PEZ** [comment]
Thanks! I can reproduce. And I can undo the trimming. Quite strange...

**Comment by PEZ** [comment]
So, the reason this happens is that VS Code will call Calvas range formatter with the range of the pasted text, and then Calva will format this. (All given that formatOnPaste is enabled, which is default with Calva). If the format config `:remove-surrounding-whitespace?` is set to `true` (again, the default), `b ` will be formatted to `b`.

What we can do is to check if the range is a list of some type, and if it isn't we can expand the range to the enclosing list. It will make formatOnPaste sometimes format a bit more than it used to, but this is how the `tab` format command works, so shouldn't be too surprising, and probably better than producing broken code, like with the example in the OP.
