### ISSUE TITLE
Calva breaks existing keybindings

### ISSUE THREAD

**Issue by markokocic** [BetterThanTomorrow/calva#223]
When Calva is installed, some standard VSCode keybinding don't work anymore. They are overriden by the Paredit keybinding.

For example, if I'm inside a Java project, editing Java file, Ctrl+Arrow keys doesn't work anymore, since it seems like it's bound to Paredit command which has no effect on Java file.

The only way to get the Ctrl+Arrows keybindings back is to actually disable Calva plugin.

**Comment by markokocic** [comment]
Just to note that I noticed this after the upgrade to the new Calva. I don't remember such issue with legacy Calva plugin.

**Comment by markokocic** [comment]
It may be that #222 is the root cause of the issue, since Paredit is always enabled?

**Comment by PEZ** [comment]
Yes, that makes sense. (That Paredit maybe always is enabled.) I'll have a look at it.

**Comment by PEZ** [comment]
Latest Calva, `2.0.12` tries to improve this some. Can you try it and see if you think it is better now, @markokocic ?

**Comment by markokocic** [comment]
@PEZ the problem is still there after the update.

In non-clojure projects keybindings are not overwritten now, so that part is fixed.

However, inside Clojure projects, the Paredit bindings are activated for all file types, not only for clj and cljs files.
For example in html and sql files Paredit keybindings are still activated.

The real fix would be to restrict Paredit keybindings only to Clojure file types.

**Comment by PEZ** [comment]
Yeah, that is why my question was if the sitiuation is better now. :smile:

I'll try to do the real fix soon, but there are things I need to solve for that to work. (It is todo with that I currently can't reliable see if a REPL window is active and Paredit needs to be active there.)

The REAL real fix, however, would be to make Paredit work in all file types. But that is quite hard to do.

**Comment by markokocic** [comment]
> The REAL real fix, however, would be to make Paredit work in all file types. But that is quite hard to do.

Why would that be the case? I don't what value would paredit bring to non-lisp files. Restricting Paredit to only Clojure/Lisp files would be enough.

**Comment by PEZ** [comment]
Oh, but there are Paredit implementations that works on all filetypes, and it is sweet!

(And, I can't restrict to only Clojure files yet, for the reasons mentioned above.)

**Comment by PEZ** [comment]
Hello again,

The latest release, `2.0.16` tries to improve on this issue. Can you give it a spin and let me know if you think it is better now, or maybe even good enough?

**Comment by markokocic** [comment]
Nope, just tried `2.0.20` and it's the same as before. Keybindings don't work in any file type inside Clojure projects.

**Comment by PEZ** [comment]
I think we might have finally gotten the API we need for fixing this: https://code.visualstudio.com/updates/v1_37#_support-for-or-in-when-clauses

**Comment by cfehse** [comment]
This should be fixed with version 2.0.49. I am closing this issue for now.
