### ISSUE TITLE
deps.edn + shadow-cljs jack-in fails, when connect sequence builds are not keywords

### ISSUE THREAD

**Issue by zilti** [BetterThanTomorrow/calva#2242]
There is something weird going on with jacking in to a project, depending on if it's done by manually selecting the menu options, or by having them as a configuration in settings.json.

Here's the approach that works:

* Start the jack-in dialog;
* Select `deps.edn + shadow-cljs`;
* Choose the aliases - in my case `:dev/deps` and `:dev/env`;
* Choose the launch builds - in my case `:app` and `:portfolio`;
* Choose the default build - in my case `:app`.

Now, to my understanding, this translates to the following replConnectSequence for settings.json:

```json
{
  "name": "redsky Server + Client",
  "projectType": "deps.edn",
  "cljsType": "shadow-cljs",
  "menuSelections": {
    "cljAliases": [
      "dev/deps",
      "dev/env"
    ],
    "cljsLaunchBuilds": [
      "app",
      "portfolio"
    ],
    "cljsDefaultBuild": "app"
  }
}
```

The approach in that case should be to open the jack-in dialog, and select "redsky Server + Client". This does manage to start the clj portion of it apparently, but then fails.

The command it runs is:

```
clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"1.0.0"},cider/cider-nrepl {:mvn/version,"0.28.5"}}}' -M:dev/deps:dev/env -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware shadow.cljs.devtools.server.nrepl/middleware]"
```

It gives the following output in the REPL:

```
; Jacking in...
; Connecting using "redsky Server + Client" project type.
; You can make Calva auto-select this.
;   - See https://calva.io/connect-sequences/
; 
; Starting Jack-in Terminal: pushd /home/zilti/projects/fossil/redsky ; clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"1.0.0"},cider/cider-nrepl {:mvn/version,"0.28.5"}}}' -M:dev/deps:dev/env -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware shadow.cljs.devtools.server.nrepl/middleware]" ; popd
; Using host:port localhost:33727 ...
; Hooking up nREPL sessions ...
; Connected session: clj
; TIPS:
;   - You can edit the contents here. Use it as a REPL if you like.
;   - `alt+enter` evaluates the current top level form.
;   - `ctrl+enter` evaluates the current form.
;   - `alt+up` and `alt+down` traverse up and down the REPL command history
;      when the cursor is after the last contents at the prompt
;   - Clojure lines in stack traces are peekable and clickable.
; Evaluating code from settings: 'calva.autoEvaluateCode.onConnect.clj'
nil
clj꞉user꞉> 
clj꞉user꞉> 
; Creating cljs repl session...
; Connecting cljs repl: redsky Server + Client...
;   The Calva Connection Log might have more connection progress information.
; Starting cljs repl for: redsky Server + Client...
; Execution error (ExceptionInfo) at shadow.cljs.devtools.config/get-build! (config.clj:167).
no build with id: app
; Cljs builds started
; Execution error (ExceptionInfo) at shadow.cljs.devtools.server.nrepl-impl/repl-init (nrepl_impl.clj:30).
watch for build not running
; Error while connecting cljs REPL: TypeError: Cannot read properties of undefined (reading 'search')
; Jack-in done.
clj꞉user꞉> 
```

**Comment by PEZ** [comment]
I can reproduce this. Thanks for providing the info about it working without a defined custom sequence, but not with the sequence. Very strange, but probably a clue about where the bug lives...

**Comment by PEZ** [comment]
The reason this happened is that we assumed the build names where entered as Clojure keywords. It's a bit undocumented that they need to be, but instead of updating the docs, I now keywordize the build names. In my testing this dev build works with your config file:

* https://output.circle-artifacts.com/output/job/4ad2128a-2c29-4418-b4c8-a9f58355ef8e/artifacts/0/tmp/artifacts/calva-2.0.378-2242-deps-shadow-custom-sequence-f896c78d.vsix

It would be great if you could confirm. 🙏

**Comment by zilti** [comment]
I can confirm that it works both with keywords (`":app"`) and non-keywords (`"app"`), thank you! :)
