### ISSUE TITLE
Default value for calva.fmt.configPath?

### ISSUE THREAD

**Issue by jakepearson** [BetterThanTomorrow/calva#2243]
My team uses a custom `.cljfmt.edn` config file in our repos. People need to set `calva.fmt.configPath` on each repo or at their user level to have calva apply the formatting config. Would be be possible to have calva detect if a config file exists (https://github.com/weavejester/cljfmt#configuration) if `calva.fmt.configPath` is not set?

![image](https://github.com/BetterThanTomorrow/calva/assets/325306/b3a551df-1c91-457a-8e5f-4918eec05259)

Happy to work on a PR if people like the idea.

**Comment by PEZ** [comment]
I like the idea. Looking forward to that PR!

**Comment by jakepearson** [comment]
Here is a PR that appears to work. https://github.com/BetterThanTomorrow/calva/pull/2246 Please let me know if you think I made the change in the right place (and any other comments). Thanks!!
