### ISSUE TITLE
Calva not recognizing namespace for forms after in-ns

### ISSUE THREAD

**Issue by craig-latacora** [BetterThanTomorrow/calva#2245]
When evaluating a form, Calva is not recognizing the namespace the form should be evaluated in, if `in-ns` was used to set the namespace.

In foo.clj
```clojure
(ns foo)
(def bar 1)
```

in boog.clj
```clojure
(in-ns 'foo)
(+ bar 2)
```

This is a common pattern for interactive clojure development and not supporting this makes Calva very difficult to use in those scenarios where a "lab" or "user" namespace is provided to users

**Comment by craig-latacora** [comment]
It looks like https://github.com/BetterThanTomorrow/calva/blob/published/src/namespace.ts -- getNameSpace

will need to be updated to take a file position, and then work backwards to find the ns or in-ns form.

**Comment by PEZ** [comment]
Hi! Thanks for the feature request. I have been thinking about this now and then. But I have hesitated in changing anything, because it is not clear to me what the user wants that to happen. The `in-ns`  form could be somewhere in the file temporarily and evaluating something further down you might not want the `in-ns` to be considered.

To me it makes sense that Calva treats the first `ns` form as determining the namespace of the file. Today we fall back on `user`, when not finding any `ns` form. We could fall back on searching backwards for the `in-ns` forms. Though then we want to make sure we don't go strictly by the top level, since we might be in a `comment` form and the `in-ns` could be there. I think we need to come up with a few examples and decide which is the “correct” namespace for each... It would also be interesting to know what CIDER does. CC: @bbatsov 

---

What you can do while we figure out how we want this to behave is to select what you want to evaluate and include the `in-ns` form, so for the example both forms:

```clojure
(in-ns 'foo)
(+ bar 2)
```

And then evaluate the selection (`ctrl+enter`). At least I think that should work...

**Comment by bbatsov** [comment]
@PEZ We look for the ns closest to the form to infer what ns to use. Basically we start from the current line and look for `in-ns` or `ns` and we take whatever ns we find first. I don't see another way to always get the "right" ns, but it's also an overkill 99% of the time.

**Comment by PEZ** [comment]
Thanks, @bbatsov. That seems to be in line with what is asked for in this issue.

**Comment by craig-latacora** [comment]
I believe what @bbatsov suggested would properly reflect the semantics of in-ns in the file.  There need not be a ns statement in a file.  This is also how Slime handles `in-package`.  Slime also looks for a slime-buffer-package variable, which users can set thru various means.  This is quite handy for files that are loaded and evaluated in a specific namespace.

Some "real world" use cases of this are things like rule systems, where we read files at runtime that define rules, or similiar "code as config" situations.

I am not familiar with VSCode enough to grok what their "buffer var" or "file var" equivalent is, so that may not be possible.  When hacking CL, we would use emacs file local vars to define the package in these "code as config" use cases.


If I were to sketch it out:

1. If there is a editor level file variable defining a ns, use that.
2. Starting from the form to be evaluated, look backwards for a non-commented ns or in-ns form until you find one, and use that.
3. Default to user

Hmm, my pre ☕ github issue comments may not be the clearest 8^)

**Comment by craig-latacora** [comment]
Slime code reference: https://github.com/slime/slime/blob/master/slime.el#L1989

**Comment by PEZ** [comment]
I think this still begs for a definition of “backwards”. And given that the “it's also an overkill 99% of the time” is an understatement, I wonder if we could be fine with evaluating the selection in cases where picking the first ns or in-ns form we find would pick something else.

**Comment by PEZ** [comment]
> am not familiar with VSCode enough to grok what their "buffer var" or "file var" equivalent is

I'm not familiar with Emacs enough to know whet the equivalents would be either. 😄

**Comment by craig-latacora** [comment]
For the definition of going backwards to find the most recent ns/in-ns form:

Assume:
  - only in-ns and ns forms at the top level matter...
  - formRange = a Range for the selection or form we are evaluating.
  - tlFormRanges = result of LispTokenCursor.rangesForTopLevelForms
  - nsFormRanges = tlFormRanges that start with `ns` or `in-ns`

It would be the nsFormRange with the greatest start value whose end value is < formRange.start.

Most of the time nsFormRanges will be a an array with a single [int, int] tuple.

**Comment by craig-latacora** [comment]
I agree that the "easiest" solution of using the first `in-ns` or `ns` form would handle the  vast majority of use cases and would be a relatively trivial transform to existing code.  It would solve my immediate use case.

However, the nsFormRanges approach described above would be more "correct" than the current code in terms of handling `comment` forms and actual semantics of in-ns/ns.  Multiple in-ns and ns forms in a file is valid clojure.

The clojure-lsp also handles these cases, and may even be a better way to get the "namespace" a form should be evaluated in?  I'm not familiar enough with it's API to say.

```
(ns com.latacora.ghbroker.foo)
(def foo 1)
foo ;; cider and clojure-lsp recognize it as defined and return correct value
(ns com.latacora.ghbroker.bar)
(def bar 2)
foo ;; cider and clojure-lsp recognize it as undefined
baz. ;; cider and clojure-lsp recognize it as undefined
bar ;; cider and clojure-lsp recognize it and return correct value
(ns com.latacora.ghbroker.baz)
(def baz 3)
baz  ;;cider and clojure-lsp recognize this and return correct value


(in-ns 'com.latacora.ghbroker.foo)
foo. ;; cider and clojure-lsp recognize this and return expected value
```

**Comment by PEZ** [comment]
It needs to work also when clojure-lsp is not active. And I think we want to be as close as possible to the perceived REPL truth, anyway, regardless what the linter thinks.

> Assume:
> 
> * only in-ns and ns forms at the top level matter...

That's what I don't want to assume. It could be code like:

```clojure
(ns bar)
(comment
  (in-ns 'foo)
  (baz 42)|
  )
```

```clojure
(ns bar)
(defn- f
  []
  {:rcf (comment
          (in-ns 'foo)
          (baz 42)|)}
  ...)
```

```clojure
(ns bar)
(in-ns 'foo)
(defn- f
  []
  {:rcf (comment
          (baz 42)|)}
  ...)
```


```clojure
(ns bar)
(comment
  (in-ns 'foo)
  (defn- f
    []
    {:rcf (comment
            (baz 42) |)}
    ...)
  )
```

Seem to me like “backwards” should be defined as ”backwards through the current top level, then up to the next top level, and so on until we're at the start of the file.

**Comment by craig-latacora** [comment]
Agreed, I think preserving the behavior in those comments and nested forms is preferable.

**Comment by PEZ** [comment]
As it happens I have written some basic tests for the get-ns code in another branch. I'll get that merged and then we can fix this in-ns thing.

**Comment by PEZ** [comment]
Those tests are now merged on `dev`. Do you want to have a go at implementing the in-ns behaviour, @craig-latacora? I'll do it if you don't have the time right now, but I don't want to steal the fun from you. 😄

**Comment by craig-latacora** [comment]
I appreciate the offer, and i even DLed calva and tried to get up to speed on the dev loop.  I don't have the time this week.

**Comment by PEZ** [comment]
That's cool. There's no shortage of things that needs fixing in Calva, anyway, there will be things there for you when you find the time. 😄

**Comment by PEZ** [comment]
Please have a look at the PR, @craig-latacora:

* #2247

With these type of structure navigation, I'm always worried there will be cases where we go into some infinite loop or blow the recursion stack...

To take it for a spin you can build Calva from that PR or use this VSIX: [calva-2.0.377-2245-in-ns-f5cecbd8.vsix](https://output.circle-artifacts.com/output/job/357f9f11-f5d7-4174-81a8-eb87732067e3/artifacts/0/tmp/artifacts/calva-2.0.377-2245-in-ns-f5cecbd8.vsix)
