### ISSUE TITLE
Rich comments broken by 2.0.377

### ISSUE THREAD

**Issue by TuggyNE** [BetterThanTomorrow/calva#2249]
Looks like the fix to #2245 broke rich comments in source files. 2.0.376 does not have this problem.

```clojure
(ns example (:require [cyrus-config.core :as cfg]))
; ... various def* forms ...
(comment
  (cfg/reload-with-over-ride! {}))
```
Evaluating the form inside the `comment` switches to `user` ns and naturally fails to find the `cfg` alias. Evaluating other forms outside comments will switch back to the correct ns. (I didn't check if this also occurs with e.g. `#_` syntax.)

**Comment by pwhittin** [comment]
I just crashed into the same problem :(

**Comment by PEZ** [comment]
I'm sorry about this! Am about to work with a fix now. Shouldn't take too long.

As a workaround you can put an `ns` or `in-ns` form first in the rich comment.

**Comment by PEZ** [comment]
I found the issue. I threw in the towel too early when not finding a namespace at a top level context... Pretty straightforward fix: https://github.com/BetterThanTomorrow/calva/pull/2250/files

v2.0.378 building now. Will update here when it is released. (And this issue will auto-close just moments before the release is available.)

**Comment by PEZ** [comment]
And, v2.0.378 is now released. I'm super sorry for the inconvenience. Rich comments are dear to me!
