### ISSUE TITLE
`+` in `.cljfmt.edn` `:indents` breaks auto indenting

### ISSUE THREAD

**Issue by zeitstein** [BetterThanTomorrow/calva#2263]
To reproduce, let your `.cljfmt.edn` be
```clojure
{:indents {+ [[:block 0]]}}
```

Now, pressing enter or backspace no longer produces correct indentation. More in attached video.

https://github.com/BetterThanTomorrow/calva/assets/8146007/57fe9870-1905-496d-8478-f30c16eb5756

In my project I have a bunch of these rules, but `+` seems to be the only one causing the issue.

**Comment by PEZ** [comment]
Thanks for reporting! An interesting one. 😄

**Comment by PEZ** [comment]
I can't reproduce this. Can you still, @zeitstein?

**Comment by zeitstein** [comment]
Yup. Latest Calva.

https://github.com/BetterThanTomorrow/calva/assets/8146007/1dc82123-bd84-438c-9f2a-9adcab14977c

**Comment by PEZ** [comment]
Thanks! I can reproduce it now.

**Comment by PEZ** [comment]
Calva `v2.0.403` should fix this. Please give it a spin!

**Comment by zeitstein** [comment]
Fixed. Thank you!
