### ISSUE TITLE
"Error loading complete.core" launching REPL with lein using a profile

### ISSUE THREAD

**Issue by pbwolf** [BetterThanTomorrow/calva#227]
"Error loading complete.core" launching REPL with lein using a profile in Calva 2.0.14.

Upon Ctrl+Alt+C, Ctrl+Alt+J to jack in to a lein project, Calva confirms to use Leiningen, prompts for profiles (only one is offered in this case, :dev, and I choose it), and then displays an error message in the Terminal:  

`Error loading complete.core: Could not locate complete/core__init.class, complete/core.clj or complete/core.cljc on classpath.`

The TERMINAL tab displays the following command:

`Executing task: /home/foo/bin/lein update-in :dependencies conj "[nrepl \"0.6.0\"]" -- update-in :plugins conj "[cider/cider-nrepl \"0.21.1\"]" -- update-in "[:repl-options :nrepl-middleware]" conj "[\"cider.nrepl/cider-middleware\"]" -- with-profile dev repl :headless`

According to https://github.com/technomancy/leiningen/issues/1329, 'The problem here is that you're removing the "base" profile.... If you want to add in your own "repl" profile, try lein with-profiles +repl repl instead.'

The same command Calva used, but with +dev in place of dev, works without error when I try it in a Linux bash shell.

**Comment by PEZ** [comment]
Thanks. I have been thinking that error message was something we had to live with. But there is hope!

I need to know a bit more about how to specify this, so I filed a request for better documentation here: [#2598](https://github.com/technomancy/leiningen/issues/2598)

**Comment by PEZ** [comment]
Hello again. `2.0.16` should behave better, prepending the profiles with `+`. And that error message is gone. Can you test and see if it checks out for you, @pbwolf ?

**Comment by pbwolf** [comment]
Works great!
