### ISSUE TITLE
Failing to download clojure-lsp server on Windows

### ISSUE THREAD

**Issue by JordanSkousen** [BetterThanTomorrow/calva#2287]
I recently updated to the latest VSCode and now the clojure-lsp server won't start. This is the error the Calva extension is throwing:
```
Failed to download clojure-lsp server. Error: Error downloading clojure-lsp, version: 2023.08.06-00.28.06, from https://github.com/clojure-lsp/clojure-lsp/releases/download/2023.08.06-00.28.06/clojure-lsp-native-windows-amd64.zip
```

These are the console logs in VSCode Developer Tools:
```
[Extension Host] Downloading clojure-lsp from https://github.com/clojure-lsp/clojure-lsp/releases/download/2023.08.06-00.28.06/clojure-lsp-native-windows-amd64.zip
[Extension Host] Clojure-lsp artifact downloaded to c:\Users\Jordan\.vscode\extensions\betterthantomorrow.calva-2.0.385\clojure-lsp-native-windows-amd64.zip
[Extension Host] Unzipping file
[Extension Host] Error downloading clojure-lsp, version: 2023.08.06-00.28.06, from https://github.com/clojure-lsp/clojure-lsp/releases/download/2023.08.06-00.28.06/clojure-lsp-native-windows-amd64.zip Error: ENOENT: no such file or directory, chmod 'c:\Users\Jordan\.vscode\extensions\betterthantomorrow.calva-2.0.385\clojure-lsp'
workbench.desktop.main.js:sourcemap:762 Failed to download clojure-lsp server. Error: Error downloading clojure-lsp, version: 2023.08.06-00.28.06, from https://github.com/clojure-lsp/clojure-lsp/releases/download/2023.08.06-00.28.06/clojure-lsp-native-windows-amd64.zip
```

VSCode About dialog info:
```
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

I have the latest Calva installed (`v2.0.385`). I also tried disabling all other extensions and only enabling Calva, and it still won't download.

**Comment by JordanSkousen** [comment]
I think I've narrowed down the problem. In [src/lsp/client/dowloader.ts](https://github.com/BetterThanTomorrow/calva/blob/published/src/lsp/client/downloader.ts#L39C47-L39C47):
<img width="942" alt="Screenshot 2023-08-15 162829" src="https://github.com/BetterThanTomorrow/calva/assets/35109863/ded230e1-024d-4052-97f9-c0b2c81b7749">

My system reports my `arch` as "`x64`" rather than "`win32`". Instead, my `platform` is "`win32`". This means it thinks the executable is named `clojure-lsp` instead of `clojure-lsp.exe`. I'm thinking the fix here would be to change `arch` on line 39 to `platform`. I even made the change myself and clojure-lsp now downloads successfully.

I would make a PR, but I don't trust that I know enough about what's going on 😛

**Comment by PEZ** [comment]
Hi! Strange that this just started to happen. So the downloaded file in the zip is `clojure-lsp.exe`?

I think it seems like you know what's going on. 😄 I don't have a good Windows machine so it is clunky for me to fix this. Please consider filing a PR. 🙏 

As a workaround for now to get it working you can move that exe file somewhere on your disk and set `calva.clojureLspPath` to point to it.
