### ISSUE TITLE
Evaluating a non-list top level form from inside a form evaluates the wrong form when in a rich comment

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#2290]
Repro:

```clojure
(comment
  {:hello "w|orld"})
```

With the cursor at `|` within the form above, run the command the evaluate the top level form, and see that `"world"` is returned. I expect `{:hello "world"}` to be returned.

If you move that map outside the comment form and perform the same steps, the whole map is returned instead of just the string, as is expected.

**Comment by PEZ** [comment]
I updated the title to reflect that this seems to be specific to when the top level form evaluated is not a function call. This is correctly handled:

```clojure
(comment
  (str "w|orld") => "world"
  :rcf) 
```

**Comment by PEZ** [comment]
I updated the title again, because it is not only from inside strings it goes wrong. It's from inside a form that's is inside a “non-list”, when in a rich comment:

```clojure
(comment
  {:hello "w|orld"} => "world"
  {:hello ['w|orld]} => [world]
  :rcf)
```

I added some unit tests that expose this:

* https://github.com/BetterThanTomorrow/calva/commit/399b758accd0361b4543b325fc0bc89fe1d551db

**Comment by bpringe** [comment]
> I updated the title to reflect that this seems to be specific to when the top level form evaluated is not a function call. This is correctly handled:

Assuming you ran the command to evaluate the top level form in that code you showed, from where you showed the cursor to be, that example doesn't show for sure that the evaluation is correctly handled. Evaluating both `(str "world")` and `"world"` will both result in `"world"`, and I don't know from the example which was evaluated.

Anyway, good investigation and nice work on the fix.
