### ISSUE TITLE
when editing a line comment, hitting <enter> should extend the comment so that s-expression structure is not broken

### ISSUE THREAD

**Issue by dustingetz** [BetterThanTomorrow/calva#2296]
See video.

Expected behavior: `;` is inserted such that the comment block is gracefully continued.
Actual behavior: literal `\n` is inserted, breaking program structure which has various consequences, e.g. incorrect auto-formatter, cursor unexpectedly jumps from L35 to L29

https://github.com/BetterThanTomorrow/calva/assets/124158/861ee3ec-ff44-473d-900e-a3a9d34056c4

**Comment by PEZ** [comment]
Yeah, this is not super good. We have decided against automatic comment continuation until we figure out how that should work without getting in the way when you don't want it. There is a command for continuing comments. Something like **Calva: Continue line comment**. You could bind that to a shortcut (even to `enter` but that will take some careful consideration around what to include in the `when` clause).

**Comment by PEZ** [comment]
@dustingetz Latest Calva now tries to avoid formatting the code when a line comment is split. Should make things less jarring.

As for your suggested behaviour. You can try adding a keybinding like so:

<img width="832" alt="image" src="https://github.com/BetterThanTomorrow/calva/assets/30010/802f42a8-38c9-4ded-a3a6-15b6e7fb8622">

``` json
    {
        "key": "cmd+enter",
        "command": "calva.continueComment",
        "when": "editorLangId == clojure"
    }
```

I.e. Do the comment continuation at will, but not by default. (We used to have it enabled by default, but I realized that I most often do not want that.)
