### ISSUE TITLE
re-natal intellisense

### ISSUE THREAD

**Issue by oguimbal** [BetterThanTomorrow/calva#230]
Disclaimer: I'm pretty new to clojure. So i'm a bit in the dark here.

I've setup a [re-natal](https://github.com/drapanjanas/re-natal) project, and successfuly connected calva to it.

i.e. :
```
lein repl
user => (start-figwheel "android")
```
(then `react-native start` and `react-native run-android` in another shell)

And finally, I could connect calva
![image](https://user-images.githubusercontent.com/8973947/59662540-72a07980-91ad-11e9-9021-de05527fea93.png)

And run repl commands in the context of my android emulator:

![image](https://user-images.githubusercontent.com/8973947/59662894-26096e00-91ae-11e9-8cad-41ced92f4a7f.png)

Which makes me think that everything is _almost_ OK.... but I dont have any intellisense support:

![image](https://user-images.githubusercontent.com/8973947/59662799-f0648500-91ad-11e9-8b7e-79febe140d64.png)

Am I missing something ? How can I troubleshoot that ?

Thanks

**Comment by PEZ** [comment]
It is probably a mismatch/lack of dependencies. Try letting Calva start the
repl for you (a.k.a Jack-in).

**Comment by oguimbal** [comment]
Thanks, you were right, I finally got it working this way (for the record):

1) Jack-in
2) `user =>  (start-figwheel "android")`
3)  `react-native run-android`   ( `react-native start` if not already started)
4) Once figwhell as started (you can see this on the jacked-in repl), run the "connect to a running REPL server" to connect to figwheel.  **This was what I missed and made me try with a standalone repl in the first place**

=> Hot reload on android OK, Intellisense OK.

**Comment by PEZ** [comment]
Thanks for sharing how you solved it. Question: didn't it work choosing `Leiningen+Figwheel` at Jack-in?

**Comment by oguimbal** [comment]
Nope, it did not.

**Comment by PEZ** [comment]
Calva should figure that out...

It could be something with that it is assumed that it is a browser app when Figwheel is involved.

Can you share the re-natal project or tell me how you created it?

**Comment by oguimbal** [comment]
Sure, here is only the [project.clj](https://pastebin.com/R0nPPbmE) , or if you're interested in it, 
[the whole repo](https://github.com/BetterThanTomorrow/calva/files/3303649/dot.git.zip)

... which is an almost brand new project, created using `re-natal init XXXX` (if i remember well, I just added a couple of npm libs, and toyded a bit with it... no other significant modification)

May be worth mentioning: When Jacking in Lein + Figwheel, a browser page is started on http://0.0.0.0:3449 which never loads (and no CLJS repl tab is opened)

![image](https://user-images.githubusercontent.com/8973947/59724136-1ed37600-9229-11e9-8308-4657d8f3a5ab.png)

**Comment by oguimbal** [comment]
Oh, wait ! I'm terribly sorry, Jackin lein+figwheel seems to actually work: It just takes ~1-2min to pop the cljs repl.
(i'm not usually patient when nothing seems to be loading, never waited that long)

... but how does it choses between ios & android build configs ?

**Comment by PEZ** [comment]
Calva stupishly assumes it is a web project when Fighweel is involved. I'll have a look at this and see if I can better support re-natal projects. Thanks for all this info!
