### ISSUE TITLE
stdout from sub threads is not printed in the terminal 

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#2300]
When spawning off a thread and printing to stdout from the thread, the output is printed from the repl/Clojure process and not picked up by Calva's nREPL client. It can create a bit of confusion, like with this [missionary](https://github.com/leonoel/missionary) code where only `Hello` is printed in the REPL/Output window and the other two strings are printed in the jack-in pseudo terminal:

```clojure
  (def slowmo-hello-world
    (m/sp (println "Hello")
          (m/? nap)
          (println "World")
          (m/? nap)
          (println "!")))

  (let [begin (System/currentTimeMillis)]
    (m/? slowmo-hello-world)
    (println "Took: " (- (System/currentTimeMillis) begin) " ms"))
Hello
nil
clj:hello.example:=>
```

And in the jack-in terminal this is printed:
```
World
!
```

**Comment by PEZ** [comment]
Following up this issue:

* https://github.com/nrepl/nrepl/issues/119 

I tried evaluating:

```clojure
  (do
    (import 'org.apache.commons.io.output.WriterOutputStream)
    (import 'java.io.PrintStream)
    (System/setOut (PrintStream. (WriterOutputStream. *out*) true))
    (alter-var-root #'*out* (fn [_] *out*)))
```

And that fixes the issue. I'm now running with these settings, which also fix the issue, to see if I can notice any reason why Calva shouldn't be doing this by default:

```json
  "calva.autoEvaluateCode": {
    "onConnect": {
      "clj": "(when-let [requires (resolve 'clojure.main/repl-requires)] (clojure.core/apply clojure.core/require @requires))\n(do (import 'org.apache.commons.io.output.WriterOutputStream) (import 'java.io.PrintStream) (System/setOut (PrintStream. (WriterOutputStream. *out*) true)) (alter-var-root #'*out* (fn [_] *out*)))",
      "cljs": "(try (require '[cljs.repl :refer [apropos dir doc find-doc print-doc pst source]]) (catch :default e (js/console.warn \"Failed to require cljs.repl utilities:\" (.-message e))))"
    },
    "onFileLoaded": {
      "clj": null,
      "cljs": null
    }
  }

```

**Comment by PEZ** [comment]
So one side effect of this setting is that some output that people might be used to happening in the terminal where the repl is started, now is routed to the output window. E.g. server side logging and shadow-cljs test runner output.

The “out-of-band” (dunno if that's the correct term) output messages are all coming in with the same message id, maybe the message id used for the `autoEvaluateCode`. I don't see a way we can separate out these messages from those coming from child threads to some particular evaluation

**Comment by dustingetz** [comment]
More test cases for consideration:
```clojure
(comment "println from second thread with future"
  (do (println "hello") (future (println "world")))
  ; hello
  ; world
  ; #<Future@403ac18d: nil>
  )

(comment "println from second thread with java Thread constructor"
  (do (println "hello")
    (doto (java.lang.Thread. #(println "world")) (.start)))
  ; hello
  ; #object[java.lang.Thread 0x1952f3ce "Thread[Thread-43,5,main]"] 
  )

(comment
  "bypass Clojure *out* binding"
  (.println System/out "Hello stdout.")
  ; nil


(clojure.tools.logging/info "asd")
(shadow.jvm-log/info ::foo "hi") logs to java stdout by default, bypassing *out*
[2023-08-29 10:35:34.138 - INFO] :missionary-docs.missionary-examples/foo - "hi"
```

**Comment by PEZ** [comment]
The current PR build is here: https://output.circle-artifacts.com/output/job/c39cb214-96f5-4b91-9857-44921b945139/artifacts/0/tmp/artifacts/calva-2.0.388-2300-subscribe-stdout-47382319.vsix

I'm not sure I like it. With shadow-cljs the REPL Output window gets crowded with non-repl output, which can look like:

```clojure
cljs꞉cljs.user꞉> 
; [:calva-lib] Build completed. (268 files, 2 compiled, 0 warnings, 0.28s)
cljs꞉cljs.user꞉> 
========= Running Tests =======================

Testing calva.fmt.editor-test

Testing calva.fmt.formatter-test

Testing calva.fmt.util-test

Testing calva.html2hiccup-test

Testing calva.js-utils-test

Testing calva.js2cljs.converter-test

Testing calva.parse-test

Testing calva.pprint.printer-test

Testing calva.state-test

Testing pez-rewrite-clj.node-test

Testing pez-rewrite-clj.paredit-test

Testing pez-rewrite-clj.zip-test

Testing pez-rewrite-clj.zip.editz-test

Testing pez-rewrite-clj.zip.findz-test

Testing pez-rewrite-clj.zip.seqz-test

Ran 117 tests containing 302 assertions.
0 failures, 0 errors.
===============================================
; [:test] Build completed. (233 files, 3 compiled, 0 warnings, 2.68s)
cljs꞉cljs.user꞉> 
```

It's the same with CIDER, but it's hardly comforting that CIDER users have a bad time too. 😄 

However, the only alternative which does not involve a lot of work is to leave this as opt-in, and the way that surprises someone working with multithreaded code is not good either. We're between a rock and a hard place. I think I will go for defaulting to redirecting the server output to the repl output (like it is in the dev build posted above). Calva is named from CIDER after all. They know what they're doing.

**Comment by PEZ** [comment]
At least with the solution used here we can distinguish between messages that “belong” to a user evaluation and messages coming out-of-band, and thus we have the option to create other behaviour than throwing it all into the repl output. I like options. 😄

**Comment by dustingetz** [comment]
Calva v2.0.388

I'm seeing the stdout redirect happening late in the game. I don't know if anything can be done about it. It's just surprising to beginners so I wanted to document it for future reference.

Any stdout prior to `; Using host:port localhost:49505 ...` goes to the jack-in terminal. The corresponding point in the jack-in terminal is `nREPL server started on port 49505 on host localhost - nrepl://localhost:49505`

The offender here is namespaces that log on require, thus logging on app initialization but before the entrypoint is invoked. Datomic appears to be one such namespace.

I think my app can be changed to not load any app namespaces at all until after `-m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"` runs, which IIUC means no :require in user.clj . This is imo a best practice anyway for faster REPL startup (in my user.clj I do stuff like `(def shadow-start! (delay @(requiring-resolve 'shadow.cljs.devtools.server/start!)))`.

**Comment by dustingetz** [comment]
~~I also at least once saw Datomic logs going to *both* the jack-in terminal and output.calva-repl, which shocked me and is hard to reproduce. How can that happen?~~
i believe this race condition was on me (my user.clj), sorry!

**Comment by PEZ** [comment]
I consistently see output go both to the terminal and to the output window. In the above output I pasted these messages are also printed in the terminal:

```clojure
; [:calva-lib] Build completed. (268 files, 2 compiled, 0 warnings, 0.28s)
; [:test] Build completed. (233 files, 3 compiled, 0 warnings, 2.68s)
```

It gets the `stderr` treatment by Calva (we prepend with `; `) so might be only for `stderr` it happens. And CIDER does the same thing (of course it does, but anyway).

**Comment by PEZ** [comment]
For anyone finding this issue and wondering what happened. Calva 2.0.388 changed the default behaviour and closed this issue. Read about how it works now and how to change the default here: https://calva.io/output/#repl-process-output-stdout-and-stderr
