### ISSUE TITLE
Clear output in `output.calva-repl`.

### ISSUE THREAD

**Issue by lkyhfx** [BetterThanTomorrow/calva#2304]
Read through the documentation and googled, can't find a way to clear the `output.calva-repl` file. Sometime infinite loop print 10k+ lines before interrupt the evaluation. The only way is to delete the file and must re jack-in.
Is there a way to clear the output easily? There is a command to clear the history of repl 'Clear REPL History', but it seems that it don't clear the output fil.

**Comment by PEZ** [comment]
Hello. There's no command for doing this. It's just a file though, and there is a command for showing and focusing the REPL/Output window:

<img width="597" alt="image" src="https://github.com/BetterThanTomorrow/calva/assets/30010/56a0165d-5e37-449b-b67c-ee9ec97ff09d">

A less disruptive way of cleaning the window, than you do now, is to use that command and then delete everything in there (select all, delete).

**Comment by lkyhfx** [comment]
Thanks!
