### ISSUE TITLE
Jack-in terminal unaware of Homebrew directories

### ISSUE THREAD

**Issue by brettrowberry** [BetterThanTomorrow/calva#2307]
My `settings.json` includes:

```json
{
    "calva.replConnectSequences": [
       {
            "name": "CLJ",
            "projectType": "custom",
            "nReplPortFile": [".nrepl-port"],
            "customJackInCommandLine": "./repl",
            "cljsType": "none",
            "autoSelectForJackIn": true,
            "projectRootPath": ["."]
       }]
}
```

After updating from macOS 13.5.0 to 13.5.1, performing a Jack-in using this sequence no longer works. My `repl` script fails because it no longer knows where to find a utility I installed via Homebrew, located at `/opt/homebrew/bin`.

As a workaround, I changed `customJackInCommandLine` to
            
```json
"export PATH=$PATH:/opt/homebrew/bin && ./repl",
```

I don't know if this is something Calva can or should do something about, I'm just noting that the behavior changed. Starting the `repl` script in a "normal" terminal and having Calva connect continues to work.

**Comment by bpringe** [comment]
If you start VS Code using the `code` command from a normal terminal, then try your original connect sequence, does it work?

**Comment by brettrowberry** [comment]
I observed this behavior on my machine and one other.

Today, I quit VS Code. Then, I launched VS Code using the methods below following by running my original jack-in sequence:

- from the dock 
- from a terminal like you requested
 
Everything is fine! Homebrew dirs are in PATH for the jack-in terminal. 🤷‍♂️ 

The possibility exists that Calva or VS Code updated in that time and I didn't pin my versions down to check.

**Comment by PEZ** [comment]
It's an issue with all IDEs and operating systems. Sometimes starting an app from the GUI does not give the application the expected environment. IDEs often integrate commanding tools and run into problems when this happens. I always start VS Code from the command line to avoid the issue.
