### ISSUE TITLE
Don't auto-add matching sigils inside double quotes

### ISSUE THREAD

**Issue by ingydotnet** [BetterThanTomorrow/calva#2312]
It's a bit annoying that when I'm editing text inside a double quoted string with Calva, when I type a `(`, `[` or `{` it auto-adds the `)`, `]` or `}`. It **doesn't** auto-add a second `"` when you type `"` like it would outside a double quoted string.
And the paredit commands like slurp don't work inside double quotes. So there's not even consistency.

I'd rather have no magics at all inside double quotes.

**Comment by PEZ** [comment]
It is VS Code auto-closing the brackets, not Calva. There's not much we can do about it without implementing our own auto-close-brackets. Which maybe we should do, but anyway.

**Comment by PEZ** [comment]
Closing this, because better be reported on VS Code first.
