### ISSUE TITLE
[Windows] The ClojureScript Quick Start REPL Experiences are broken

### ISSUE THREAD

**Issue by AlbertSnows** [BetterThanTomorrow/calva#2325]
Hello! This is the follow up issue to our investigation in the Clojure slack. I will also make a PR with a proposed fix to resolve this issue after. 

## Problem 
On Windows, running the "Quick Start ClojureScript" commands for either Node and Browser does not work.

## Expectation
When running a quick start command, Calva should boot up its own environment to immediately allow the user to start using some of Calva's neat features in a core `.cljs` file. 

## Outcome
When running the command, nothing happens. There's no feedback. Not in the output window, the terminals, or any popups. Some sort of behavior is happening in the background, and isn't being reflected to the user.

**Comment by AlbertSnows** [comment]
~~todo: move analysis to PR when made~~

**Comment by PEZ** [comment]
Hi! Thanks for the report and for having a look at it fixing this. I'll have a look at that PR right away!
