### ISSUE TITLE
Structure editor glitch - backspace is inhibited from removing `#`

### ISSUE THREAD

**Issue by dustingetz** [BetterThanTomorrow/calva#2327]
expected: backspace to delete #, actual: backspace passes over #

https://github.com/BetterThanTomorrow/calva/assets/124158/6cc5efa8-52e5-4c60-8da8-b8f95e5f85ca

**Comment by PEZ** [comment]
I'm having a look at this. Can minimize it down to:

```clojure
[#|[]]
```

(Cursor at `|`).

That case is clear cut, but when it looks like so:

```clojure
[#|()]

[#|{}]
```

Maybe it is better to not delete?
