### ISSUE TITLE
Could not install in Samsung Galaxy Tab s4 (Linux on Dex)

### ISSUE THREAD

**Issue by nitisinn** [BetterThanTomorrow/calva#233]
I could not install Calva extension to VS code provided by Linux on Dex (Ubuntu in Galaxy Tab S4).

**Comment by PEZ** [comment]
Do you get any errors you can share?

**Comment by nitisinn** [comment]
Hi Peter,

I attached the screenshot for the error message here.

Please note that I am very new to both Linux and Clojure.

Sorry for late reply.

Best regards,
Nitisinn,



Sent from Samsung tablet.


-------- Original message --------
