### ISSUE TITLE
Syntax Highlighting inconsistencies in VSCode theme extensions, when Calva installed

### ISSUE THREAD

**Issue by InSuperposition** [BetterThanTomorrow/calva#2333]
There seem to be inconsistencies between the Syntax highlighting when using Theme extensions (GitHub Dark, Cobalt2) with Calva.

The top row is the default VS Code Dark theme and the bottom row is cobalt2 
The left side is with Calva installed, right side is without Calva

<img width="2020" alt="Screenshot 2023-10-29 at 10 17 31 AM" src="https://github.com/BetterThanTomorrow/calva/assets/433871/21553233-ed33-4a68-90c2-bbcfabe15b97">

**Comment by PEZ** [comment]
Hi!

What you call inconsistencies, I call features. 😄 

The themes you use there are very complete and support semantic tokens. Calva provides that, through clojure-lsp. You can disable this in the clojure-lsp configuration.

**Comment by PEZ** [comment]
Please reopen the issue if you think it was wrong of me to close it, @InSuperposition.

**Comment by InSuperposition** [comment]
Thank you, however, I should have been more clear. When Calva is installed and used with a theme (specifically Cobalt2) some of the highlighting colors are redundant, with Calva installed (lower left image above) the keywords `ns` and `defn` match the colors of the namespace and function name. Without Calva installed (lower right), there is some distinction between the colors.

There seems to be a clash in color when using Calva and some themes together. Is it the theme that might be causing the issue? or is It clojure-lsp?
