### ISSUE TITLE
"Fire up the Clojurescript Quickstart Browser REPL" functionality fails when another application is using port 9000

### ISSUE THREAD

**Issue by radhakrishnan-chandarasikharan-kr** [BetterThanTomorrow/calva#2335]
## Issue
When launching the Quickstart Browser REPL, if another application is listening on port 9000 the operation fails with the following message in the output.calva-repl pane
```
clj꞉user꞉> 
; Creating cljs repl session...
; Connecting cljs repl: deps.edn + ClojureScript built-in for browser...
;   The Calva Connection Log might have more connection progress information.
; Execution error (BindException) at java.net.PlainSocketImpl/socketBind (PlainSocketImpl.java:-2).
Address already in use (Bind failed)
; Failed starting cljs repl
; Jack-in done.
clj꞉user꞉> 
```
## Replicate
To replicate (in Mac/Linux)
open bash terminal and run
```
nc -l 9000
```
This will cause nc to bind to port 9000 and listen for incoming connections

Now open command palatte and select "Fire up the Clojurescript Quickstart Browser REPL"

## Reason
In /clojure/browser/repl.cljs the port for repl is hardcoded as
```
(goog-define HOST "localhost")
(goog-define PORT 9000)
```
## Remedy
Provide an option to override the port via preferences

**Comment by bpringe** [comment]
Thanks for reporting this.

> Provide an option to override the port via preferences

@PEZ What are your thoughts on this? Do we have control over that? If not, maybe we should at least document this (if it isn't documented).

**Comment by PEZ** [comment]
Yeah, when @radhakrishnan-chandarasikharan-kr and I discussed the issue we thought it may not be as hard coded as it seems it is. But we can document it some so at least you find it mentioned on calva.io. And possibly we can also catch the error in Calva and provide a link to the documentation.

**Comment by PEZ** [comment]
After having had a look, the port used does seem to be hard coded. I'm closing this, as it is unclear what we can do about it. At least there's this issue that people running in to the problem can find.
