### ISSUE TITLE
I can't run calva extension in vsCode on Mac m2 pro

### ISSUE THREAD

**Issue by goodmanstarkov** [BetterThanTomorrow/calva#2347]
I have some error after run calva extension, please help me

```
[Error - 23:06:59] Server initialization failed.
  Message: Internal error
  Code: -32603 
[object Object]
[Error - 23:06:59] Clojure Language Client client: couldn't create connection to server.
  Message: Internal error
  Code: -32603 
[object Object]
```

**Comment by PEZ** [comment]
Hi! Sorry about the troubles. First thing. You can still use Calva, it is “only” clojure-lsp that is not starting. But let's try figure out how to get that starting, because clojure-lsp is great!

Have this worked before, or is it the first time you use Calva?

**Comment by goodmanstarkov** [comment]
I'm using calva for the first time, I tried downloading clojure-lsp via rosetta 2, I tried writing JAVA_HOME in a file.zhrc and nothing helped me

**Comment by PEZ** [comment]
Calva downloads its own clojure-lsp, maybe that got corrupted or something. Let's see if we can make it re-download it. 

In the status bar you have a **clojure-lsp** indicator/button. If you click it you should get a menu with the option to download clojure-lsp.
<img width="726" alt="image" src="https://github.com/BetterThanTomorrow/calva/assets/30010/076fcfb5-26b5-482e-a923-0fbc61911dcd">

**Comment by goodmanstarkov** [comment]
successfully downloaded, restarted VSCode , have the same error

**Comment by PEZ** [comment]
Hmmm, I'm not sure about the successful download. Calva can be saying that without it being true, I think. Let's see...

There's a command for opening the extensions folder: **Extensions: Open Extensions Folder**. If you use that and find the folder `betterthantomorrow.calva-2.0.396` there. Remove all files in the root of the folder that is named something that starts with **clojure-lsp<**, there.

Then use the download clojure-lsp command again, and then try to start the server (you can do that from the same menu as you download clojure-lsp, if you first select the project root.)

**Comment by goodmanstarkov** [comment]
I found all the files related to clojure-lsp there were 3 of them, I deleted, downloaded clojureLsp from VSCode, all 3 files appeared again, restarted VSCode and have the same error

**Comment by PEZ** [comment]
Thanks for enduring! Now that you have found the files. Can you try execute that `clojure-lsp` executable from a terminal and see of you get some error message we can make sense of?

**Comment by goodmanstarkov** [comment]
<img width="1233" alt="image" src="https://github.com/BetterThanTomorrow/calva/assets/32370508/2cc0e829-27cc-4172-9149-dc8c96a52b4f">
I ran Clojure-lsp, restart VsCode, same error exist

<img width="473" alt="image" src="https://github.com/BetterThanTomorrow/calva/assets/32370508/18493b5f-b337-4577-9a3a-a0b2920b3804">

**Comment by PEZ** [comment]
Yeah, didn't expect it to start working. Just want to see if we could see an error message that told us something. I don't on that try. But if you try to run it from the terminal, from the project you want to use it with.

**Comment by goodmanstarkov** [comment]
The problem is solved, Cyrillic letters were used in the path to the project, only Latin letters should be in the path

**Comment by jahson** [comment]
@PEZ Maybe you could provide me with more information: is this problem related to Calva or JSON-RPC? It looks like something could be implemented to either check path for non-ascii symbols, or even allow these symbols in path. This way there would be much less tickets like these.

**Comment by PEZ** [comment]
@jahson thanks. Good thinking! I don't think it is within our reach to fix the problem. Seems to be rooted upstream. But we could check the path and warn about funny characters in the path. PR welcome!

@goodmanstarkov Great that you found the issue! I should have thought of checking that.
