### ISSUE TITLE
Evaluation result randomly sliced in REPL and log

### ISSUE THREAD

**Issue by CheatEx** [BetterThanTomorrow/calva#236]
After editing/changing focus Calva starts to shorten outputs in various places. Can't catch the exact trigger. I've double checked with `js/console.log` the runtime data is fine.

![output_slice_1](https://user-images.githubusercontent.com/633649/60085519-25d71880-9742-11e9-8334-6984a440c177.png)
![output_slice_2](https://user-images.githubusercontent.com/633649/60085521-25d71880-9742-11e9-84f3-5741b9fa7bd8.png)
![output_slice_3](https://user-images.githubusercontent.com/633649/60085525-25d71880-9742-11e9-874d-af1d56bc3204.png)

**Comment by PEZ** [comment]
Thanks for the report.

It looks very broken with that incomplete map.

I've never seen that happen. What do you get if you use the comman **Copy last evaluation command** (or something like that).

**Comment by CheatEx** [comment]
With 'Copy last' I get the full string representation

**Comment by bpringe** [comment]
@CheatEx This is really odd, I've never experienced it. Is this something that still happens for you?

**Comment by CheatEx** [comment]
@bpringe I haven't seen this issue for a while, but currently I work with calva very rarely.

**Comment by bpringe** [comment]
Thanks.
>currently I work with calva very rarely

I hope we can change this for you in time if it's because of quality or missing features :smiley: . I'm going to close this for now since we haven't seen other reports and I haven't experienced it either.
