### ISSUE TITLE
Keybindings using meta keys `ctrl+alt` combination not working while following 'Fire uo the Getting Started REPL'

### ISSUE THREAD

**Issue by InSuperposition** [BetterThanTomorrow/calva#2362]
I am unable to complete the Calva tutorial due to an issue with `ctrl+option` plus any other keys not accepting input.
It may be related to this issue in VS Code.

https://github.com/microsoft/vscode/issues/199034

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.1.0

**Comment by PEZ** [comment]
Hi! Until they have fixed that I think all you really can do is to either use the commands from the command palette or re-bind them to shortcuts that do work.

**Comment by InSuperposition** [comment]
Thanks for the response. Closing the bug, it's been put in VS code team's backlog.

**Comment by PEZ** [comment]
Thanks for reporting. Hopefully next person running against this will find this issue.
