### ISSUE TITLE
[Feature Request] Paredit unwrap

### ISSUE THREAD

**Issue by sirmspencer** [BetterThanTomorrow/calva#2363]
To compliment wrap and rewrap, can we add a unwrap command?

Before
`[1 2]`

After
`1 2`

**Comment by athos** [comment]
Is `paredit.spliceSexp` what you want?

**Comment by PEZ** [comment]
Maybe we should add unwrap to the command name somehow?

**Comment by sirmspencer** [comment]
Yes, that appears to be the same thing.
