### ISSUE TITLE
Update to cljfmt v0.12

### ISSUE THREAD

**Issue by miridius** [BetterThanTomorrow/calva#2365]
Hi,

[cljfmt v0.12](https://github.com/weavejester/cljfmt/releases/tag/0.12.0) is a non-breaking change that adds a new configuration option to support two space list indents (https://github.com/weavejester/cljfmt/pull/324)

Would it be possible to update the calva dependencies so that we can use this new configuration option? Is it a simple matter of updating the deps.edn or is it more involved?

**Comment by PEZ** [comment]
Hi! It's mostly about bumping the dependency. Maybe we need to check if there should be some test added and wether we want the formatting docs to mention the settings. Do you want to do it, @miridius? If you don't have the time I can do it, but would be more fun with a new contributor. 😄

**Comment by miridius** [comment]
Ahh I'd love to but I'm really swamped leading up to the holidays sorry!

Regarding tests I'm not sure, do you have tests for any other formatting logic? There are tests for this functionality in cljfmt itself so I'd think that's enough.

Likewise with docs, the new configuration option is documented in the cljfmt readme so I don't think there's a need to mention it in the Calva docs unless it's something people commonly ask about

**Comment by PEZ** [comment]
Well, yes, we have tests for the formatting integration. Looking at them I think they don't need updating because of this and they keep passing also after the bump so we should be good.
