### ISSUE TITLE
[Feature Request] show argument list of fn

### ISSUE THREAD

**Issue by slipset** [BetterThanTomorrow/calva#238]
In Cider, when you type out a call to a function, eg 
```clojure
(core/reader? ) ; there is now a space after the `?`
```
Cider will show you the argument list of the function in the mini buffer, like so
![Screenshot 2019-06-28 at 10 19 15](https://user-images.githubusercontent.com/5894926/60328454-996d6580-998e-11e9-935a-d81ab0b0d743.png)

It would be very nice if Calva could do something along those lines.

**Comment by cfehse** [comment]
This is fixed in version 2.0.47.
