### ISSUE TITLE
Debug call stack view blank only top item

### ISSUE THREAD

**Issue by zhongwm** [BetterThanTomorrow/calva#2384]
Debug call stack view blank only top item

calva version 2024-01-11, 00:07:44
vscode version 1.84.0

**Comment by PEZ** [comment]
Hello: The debugger only implements handling the top element of the call stack. See:

* https://calva.io/debugger/#viewing-the-call-stack
* #1150

Please consider having a look att resurrecting the changes that implemented the full call stack.
