### ISSUE TITLE
Feature request: make it easy to pick the name for the new binding created after running one of the "extract-" code actions

### ISSUE THREAD

**Issue by maxrothman** [BetterThanTomorrow/calva#2388]
Currently when you run one of the code actions that creates a new binding (move to let, extract fn, etc.), it picks the name of the binding for you, and you have go to change both uses of it manually. Pylance, the Python language extension helpfully prompts for a name for the binding:

https://github.com/BetterThanTomorrow/calva/assets/2607086/756c968c-316b-488e-91d5-032100c77feb

Upon further investigation, it appears that the way this is accomplished is Pylance consists of _both_ a VSCode extension _and_  a LSP server. When an action that creates a new binding is sent to the LSP, the extension immediately follows the resolution of that action with a "rename symbol" action.

It would be nice if Calva were to do something similar to help devs rename bindings newly created by code actions, either by using Pylance's rename-symbol approach, or by highlighting all instances of the new symbol with multiple cursors. Personally I kind of like the multiple cursors approach because it doesn't put anything in front of the code, but either approach would be an improvement.

**Comment by PEZ** [comment]
Thanks for the request! It's neat, but is it worth its weight? Not saying it isn't, but it's a question we need to answer. What I do is to follow-up with a manual refactor-rename. Which is pretty convenient:  

https://github.com/BetterThanTomorrow/calva/assets/30010/99ce3b11-1f01-4942-a472-662e5ea149f3

**Comment by maxrothman** [comment]
I think one way to answer that question would be to look at tooling parity with other language ecosystems. Both Python and Javascript's extensions automatically trigger a rename. I suspect most others do too, though I don't have those extensions set up on my computer to be able to test them. If users expect this behavior, lacking it in Clojure tooling would be seen as a deficiency.

Another way to view it might be to think about cognitive overhead. If _every time_ a user does an extract action they'll _always_ want to trigger a rename, this seems like a prime "don't make me think" example. Remember also that not all users have "Rename symbol" bound to a keyboard shortcut, for those who don't, accessing rename requires going through the command palette. Now the sequence of actions for doing an extract is:
1. Cmd+. or click the lightbulb to see the actions list
2. Select "extract"
3. Navigate to the symbol (your cursor isn't left on top of it)
4. Cmd+Shift+P
5. Type "rename", hit enter
6. Type in the new symbol, hit enter

Auto-rename cuts that list in half.

**Comment by PEZ** [comment]
I don't think “users that do not have rename bound to a shortcut” makes a strong case. If someone disables the shortcut and then finds it painful to reach the feature, they have done this to themselves, and they have all the tools to fix it.

That said, it makes sense to trigger the rename. I remember being a bit surprised that it didn't happen the first times I used the quick-fixes. If it can be added somewhat cleanly, I would merge a PR providing it.

Also, maybe the [vscode-languageserver-node](https://github.com/microsoft/vscode-languageserver-node) team would consider a PR adding it to the `vscode-languageclient`, helping all users of the client in one go. Could be worth filing an issue and see what they say.
