### ISSUE TITLE
Feature request:  Make window stay open if code is executed from it.

### ISSUE THREAD

**Issue by sirmspencer** [BetterThanTomorrow/calva#2389]
When you are clicking through the file tree or file search, and select a file, the window in VSCode opens in a temp state (you can see the title is in italics).  This means it won't stay open if you click around.  If you then start making edits to the file, it converts to a fully open state (the title removes italics), and it stays open until closed manually. 

It would be great if executing code (ctrl+enter) would also mark the file to stay open.

**Comment by PEZ** [comment]
Thanks! This would be very nice, but I don't think the [VS Code Extension API](https://code.visualstudio.com/api/references/vscode-api) allows it. This is called **Editor Preview** in VS Code talk and all I can see is that you can check the Tab is it is in preview mode or not. But maybe there is a way, even though I don't see it. 😄

**Comment by sirmspencer** [comment]
I wonder if you can open the window that's in preview to get it out of preview.

**Comment by PEZ** [comment]
Cool! I just tried with **Joyride: Run Clojure Code**:

```
(-> vscode/window.activeTextEditor .-document (vscode/window.showTextDocument #js {:preview false}))
```

And it actually removed the preview status.

**Comment by sirmspencer** [comment]
I loooooveeee it! Thank you for getting that in.

**Comment by PEZ** [comment]
It's much better. Thanks for suggesting!
