### ISSUE TITLE
Provide option to not have Hiccup conversion convert class names to Hiccup dot shortcut class names

### ISSUE THREAD

**Issue by gerdint** [BetterThanTomorrow/calva#2390]
When using the popular [Tailwind CSS](https://tailwindcss.com/) it not uncommon to have class names like this in your HTML:
```
<a href="#" class="inline-block bg-[#5890FF] min-w ...">
  ...
</a>
```
When pasting this as Hiccup I get:
```
[:a.inline-block.bg-[#5890FF].min-w.... {:href "#"}
 "..."]
```
... which is not valid Clojure.

And so I propose an option to not bother massaging class names into the Hiccup shortcut-style, instead just leaving it as a normal class attribute like so:
```
[:a {:class "inline-block bg-[#5890FF] min-w ..." :href "#"}}
 "..."]
```

**Comment by PEZ** [comment]
Hi! Thanks for bringing this to our attention. I had no idea such classnames was a thing.

**Comment by gerdint** [comment]
Me neither. And Tailwind is a CSS processor of sorts, so those classnames
are actually expanded into regular CSS rules. But still the classnames are
in the source so need to be handled.

-Tobias


ons 7 feb. 2024 kl. 21:05 skrev Peter Strömberg ***@***.***>:

**Comment by PEZ** [comment]
Here's a build of Calva where invalid-keyword classes will be put into the props map. Valid classes will keep being tucked on the tag keyword.

* https://output.circle-artifacts.com/output/job/a55cfb82-eb52-4fd1-b74b-2138be1a15a2/artifacts/0/tmp/artifacts/calva-2.0.410-2390-hiccup-kw-or-prop-276ebbdc.vsix

Please download this and test if it works as you need. There's an option to **Install from VSIX...** in the meatballs menu at the top of the Extensions pane. You may need to change the file extension of the downloaded package from `.zip` to `.vsix`. (Sometimes it downloads as `.zip` for unknown reasons.)

The code around this is a bit messy, so I'm waiting with adding an option (creating even more cases) until I have a better idea about how to factor the code.

**Comment by gerdint** [comment]
@PEZ Hi sorry for not getting back as fast as you are fixing this. I downloaded your build and can confirm that it is indeed smarter about the classnames now and a great default mode I think. Kudos for fixing the case with class names with colons in them as well (which I didn't include above but are very common in Tailwind CSS class names).

Too bad if you do not find the code as elegant as you aspire to. I was just assuming you were leveraging some external library for this but apparently not! One idea I had was just to try to `read-string` the resulting "naive" hiccup keyword, and catch the exception and do the backup option it's not valid. But you know your code best...

The reason I proposed an option was that I noticed that there are already seem to exist [a couple of Hiccup-related options](https://calva.io/hiccup/#it-is-somewhat-configurable). FWIW I could still use an option that would just put _all_ classes under the `:class` key since when using Tailwind there is simply just so many of them making the dot syntax a bit noisy. But if you do find this is too much of a niche case there is always the work-around and resort to external converters. And the one thing that I appreciate most in VS Code coming from Emacs is actually the relative paucity of options, instead thinking hard about good default behaviour and UX experience for new as well as experienced users (whose needs are typically not all that different I think).

Thanks a bunch for Calva and your prompt action on this!

**Comment by PEZ** [comment]
Thanks for the feedback, @gerdint. I think an option like you suggest make perfect sense. You are welcome to open a new issue about it. And of course also welcome to help implement it, maybe you see how the code code get a bit less messy. As it is, adding this option would make it even harder to follow, I think. This is the relevant code, btw:

```clojure
(defn- valid-as-hiccup-kw? [s]
  (and s
       (not (re-matches #"^\d.*|.*[./:#@~`\[\]\(\){}].*" s))))

(defn- tag+id [tag id]
  (str tag (when (valid-as-hiccup-kw? id)
             (str "#" id))))

(defn- separate-classes [classes]
  (let [kw-classes (filter valid-as-hiccup-kw? classes)
        remaining-classes (remove valid-as-hiccup-kw? classes)]
    [kw-classes remaining-classes]))

(defn- build-tag-with-classes [tag-w-id kw-classes]
  (str tag-w-id
       (when (seq kw-classes)
         (str "." (some->> kw-classes (string/join "."))))))

(defn- element->hiccup [{:keys [tag attrs content] :as element} options]
  (if tag
    (let [normalized-attrs (normalize-attrs attrs options)
          {:keys [id class]} normalized-attrs
          lowercased-tag (string/lower-case tag)
          tag+id (tag+id lowercased-tag id)
          classes (when class
                    (string/split class #"\s+"))
          [kw-classes remaining-classes] (separate-classes classes)
          tag-w-id+classes (build-tag-with-classes tag+id kw-classes)
          remaining-attrs (cond-> normalized-attrs
                            :always (dissoc :class)
                            (seq remaining-classes) (assoc :class (vec remaining-classes))
                            (valid-as-hiccup-kw? id) (dissoc :id))]
      (into (cond-> [(keyword tag-w-id+classes)]
              (seq remaining-attrs) (conj remaining-attrs))
            (map #(element->hiccup % options)
                 (->> content
                      (map #(if (string? %) (string/trim %) %))
                      (remove string/blank?)))))
    (if (comment? element)
      (list 'comment (string/replace element #"^<!--\s*|\s*-->$" ""))
      element)))
```

I actually had the option working by throwing everything in the `remaining-classes` bin, in the presence of the option. But I will need to understand the code some months from now too... 😄

**Comment by gerdint** [comment]
@PEZ I will have a look at it!

**Comment by gerdint** [comment]
@PEZ I may have a few suggestions of making the code somewhat clearer (and though I admit that element->hiccup features perhaps the most let-bindings I have ever seen the code is not too shabby I think. Most clarity would probably be achieved by separating the two code paths but not sure it's worth it.

BUT, I have problems experimenting with the code since I cannot seem to get a Calva [shadow] CLJS repl running. This is my first attempt hacking Calva and though I have followed the [instructions](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva) the output.calva-repl window says this:
 
```
...
 Connecting ...
; Reading port file: file:///Users/tger/Projekt/calva/.shadow-cljs/nrepl.port ...
; Using host:port localhost:49493 ...
; Hooking up nREPL sessions ...
; Connected session: clj
; TIPS:
;   - You can edit the contents here. Use it as a REPL if you like.
;   - `alt+enter` evaluates the current top level form.
;   - `ctrl+enter` evaluates the current form.
;   - `alt+up` and `alt+down` traverse up and down the REPL command history
;      when the cursor is after the last contents at the prompt
;   - Clojure lines in stack traces are peekable and clickable.
; Evaluating code from settings: 'calva.autoEvaluateCode.onConnect.clj'
nil
clj꞉shadow.user꞉>  ; Use `alt+enter` to evaluate
clj꞉shadow.user꞉> 
; Creating cljs repl session...
; Connecting cljs repl: Calva...
;   The Calva Connection Log might have more connection progress information.
; Please start your ClojureScript app (load it in the browser, or whatever is appropriate) so that Calva can connect to its REPL...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Waiting for Shadow CLJS runtimes, start your CLJS app...
; Timed out waiting for Shadow CLJS runtimes, pretending we are connected.
; Connected session: cljs, repl: :calva-lib
; TIPS: You can choose which REPL to use (clj or cljs):
;    *Calva: Toggle REPL connection*
;    (There is a button in the status bar for this)
; Evaluating code from settings: 'calva.autoEvaluateCode.onConnect.cljs'
nil
; No available JS runtime.
; See https://shadow-cljs.github.io/docs/UsersGuide.html#repl-troubleshooting
```

Not exactly sure what 'The Calva Connection Log' refers to, but shadow-cljs starts alright in the "rigthtmost" terminal window:
```
 *  Executing task: npm run watch-cljs 


> calva@2.0.410 watch-cljs
> npx shadow-cljs -d cider/cider-nrepl:0.28.5 watch :calva-lib :test

shadow-cljs - config: /Users/tger/Projekt/calva/shadow-cljs.edn
shadow-cljs - starting via "clojure"
shadow-cljs - server version: 2.25.2 running at http://localhost:9630
shadow-cljs - nREPL server started on port 49493
shadow-cljs - watching build :calva-lib
shadow-cljs - watching build :test
[:calva-lib] Configuring build.
[:test] Configuring build.
[:calva-lib] Compiling ...
[:test] Compiling ...
========= Running Tests =======================
...
```
This is on the tip of the 'published' branch (9dc110b) since I assumed it would be the most stable. 
VS Code 1.86.1 on macOS Big Sur.

Any ideas? Since I am new to Calva I do not have a good understanding how all the pieces fit together and I am probably over-looking something obvious.

**Comment by PEZ** [comment]
`dev` is best for this. It's seldom more than one or two days behind `published`, and should be reasonably stable, or we have been sloppy with reviewing some PR.

I have had similar connection troubles with the REPL (very seldom). Don't know why. It should work starting the build and then reload the development extension host.

**Comment by gerdint** [comment]
OK so the shadow cljs runtime it is trying to connect to is running in the extension host? Is there any way of diagnosing why it may not start?

**Comment by PEZ** [comment]
Yes, it's trying to connect to the extension host. Or, rather to the shadow-cljs server running in there. I don't quite know how to diagnose, but you could check if the shadow-cljs dashboard (typically started on http://localhost:9630/) has any information. Looks like so when things work:

<img width="638" alt="image" src="https://github.com/BetterThanTomorrow/calva/assets/30010/00e32760-6ea4-4d1b-b9f1-6a7a4c6af571">

**Comment by gerdint** [comment]
Right, in my case the second runtime is not there (the calva-lib build).

1) Is the extension development host sharing the same shadow-cljs server as the other "building" host? If not and I fresh shadow-cljs process is started I probably need to increase some timeout since on my 10-year old machine anything but the tiniest Clojure classpaths typically takes several minutes to start (in Cursive I increased the REPL timeout to 5 minutes).
2) Do I perhaps need to do something in the extension development host (open a Clojure project etc) in order for the shadow runtime to start there?

**Comment by gerdint** [comment]
Ah, so when I open som Clojure project from the extension development host the 2nd Shadow runtime starts and I can connect with the Calva "project" REPL. This was not very clear from the [relevant section](https://github.com/BetterThanTomorrow/calva/wiki/Run-Calva-in-Development-Mode#the-dev-process) in the docs, but perhaps common sense?

**Comment by gerdint** [comment]
OK, I see now that when I start the extension dev host the 2nd time the last open project is re-opened, and so if it's a Clojure project the Shadow runtime would be started. Perhaps this is why this detail was missed and I should add a note on the wiki like?

_"The first time you start the Calva extensions development host you may need to open a folder containing a Clojure project."_

**Comment by PEZ** [comment]
For your context, it is about that Calva needs to activate. The reason it works opening a Clojure project, is that this activates Calva. There is a command for activating Calva too. I usually use the `"Launch w/ test folder"` configuration. We could make that the default. But for now it sounds like a great idea to update the wiki. Please do.

**Comment by PEZ** [comment]
I now made `"Launch w/ test folder"` the default. Not sure it's the most convenient, but we will see when we have used it a while.

**Comment by gerdint** [comment]
@PEZ OK so should be no need anything to the wiki instructions then?
