### ISSUE TITLE
No symbols visible in Clojure source file inside JAR

### ISSUE THREAD

**Issue by gerdint** [BetterThanTomorrow/calva#2391]
If I jump to a file belonging to a dependency of my project the outline view does not list any symbols:

![vscode-file___vscode-app_Applications_Visual%20Studio%20Code app_Contents_Resources_app_out_vs_code_electron-sandbox_workbench_workbench html](https://github.com/BetterThanTomorrow/calva/assets/14966/7f6d676d-60ed-4985-87db-ba21e67da636)

The opened file was file:/$HOME/.m2/repository/hiccup/hiccup/2.0.0-RC2/hiccup-2.0.0-RC2.jar!/hiccup/page.clj which indeed has symbols. The symbols do appear in the outline view if I copy the contents to a file and put it among my project sources.

**Comment by PEZ** [comment]
Thanks for reporting! I think I know where this goes wrong.
