### ISSUE TITLE
Integration with REBL

### ISSUE THREAD

**Issue by svdo** [BetterThanTomorrow/calva#240]
As promised on Slack, here's the feature request about REBL.

I'd like to be able to use [REBL](https://github.com/cognitect-labs/REBL-distro) in combination with Calva.

* With a bit of effort, it is already possible to manually start REBL from the Calva REPL, but this could definitely be a lot easier. When following the [Java 11 instructions](https://github.com/cognitect-labs/REBL-distro/wiki/Java-11-Usage), you need to *leave out* the `main-opts` and then in the REPL require `cognitect.rebl` and call `(cognitect.rebl/ui)`. Ideally, the setup would be in such a way that the instructions on the REBL web site can be followed as-is, and REBL can be started from Calva using a hotkey or something.
* And importantly, it should be _integrated_: as a minimum it should be possible to send the output of an evaluation to REBL, so that you can browse it there.

Thanks for awesome Calva!!

**Comment by sauvala** [comment]
I also ran into some challenges getting this to work. I wanted to have nREPL and REBL and sync data between them, meaning that when evaluating things with Calva it would send the expression (and returning value) to nREPL and to REBL. I discussed about this issue also in Slack, but I wanted to share the process and setup here.

I got this working by running `clj -A:nrepl:cider-clj:rebl -m nrepl.cmdline --middleware '[nrebl.middleware/wrap-nrebl cider.nrepl/cider-middleware]' -I` in terminal with the following aliases in my deps.edn:

```
  ;; nREPL
  :nrepl {:extra-deps {nrepl {:mvn/version "RELEASE"}}}

  ;; REBL
  :rebl {:extra-deps
         {org.clojure/clojure {:mvn/version "1.10.0"}
          org.clojure/core.async {:mvn/version "0.4.490"}
          com.cognitect/rebl {:local/root "/Users/janne/Dev/REBL/REBL-0.9.218.jar"}
          org.openjfx/javafx-fxml     {:mvn/version "11.0.1"}
          org.openjfx/javafx-controls {:mvn/version "11.0.1"}
          org.openjfx/javafx-graphics {:mvn/version "11.0.1"}
          org.openjfx/javafx-media    {:mvn/version "11.0.1"}
          org.openjfx/javafx-swing    {:mvn/version "11.0.1"}
          org.openjfx/javafx-base     {:mvn/version "11.0.1"}
          org.openjfx/javafx-web      {:mvn/version "11.0.1"}
          rickmoynihan/nrebl.middleware {:mvn/version "0.2.0"}}}

  ;; CIDER
  :cider-clj {:extra-deps {org.clojure/clojure {:mvn/version "1.9.0"}
                           cider/cider-nrepl {:mvn/version "0.21.1"}}
              :main-opts ["-m" "nrepl.cmdline" "--middleware" "[cider.nrepl/cider-middleware]"]}
```

Then from Calva I connected to the nREPL. Rest happened like @svdo described by requiring `cognitect.rebl` and launched REBL with `(cognitect.rebl/ui)` (and removing the `:main-opts`).

It would be great if this could be done by using the Jack-In to spin up the setup. I tried to do this by modifying deps.edn to make the nREPL alias to look like
```
:nrepl {:extra-deps
          {nrepl {:mvn/version "RELEASE"}}
          :main-opts ["-m" "nrepl.cmdline" "--middleware" "[nrebl.middleware/wrap-nrebl cider.nrepl/cider-middleware]" "-i"]}
```
 and selecting all three aliases for Jack-In. But when I ran `(cognitect.rebl/ui)` I got `FileNotFoundException Could not locate clojure/datafy__init.class or clojure/datafy.clj on classpath. clojure.lang.RT.load (RT.java:463)`.

**Comment by PEZ** [comment]
Thanks, both of you. I agree it would be great to have better support for REBL in Calva. Very nice with all this info on how to set it up and the problems you run in to.

**Comment by ozimos** [comment]
I got it working with these aliases in my $HOME/.clojure deps.edn:
```
;; REBL 12
:rebl-12
  {:extra-deps {org.clojure/core.async {:mvn/version "0.4.490"}
                ;; deps for file datafication (0.9.149 or later)
                org.clojure/data.csv {:mvn/version "0.1.4"}
                org.clojure/data.json {:mvn/version "0.2.3"}
                org.yaml/snakeyaml {:mvn/version "1.23"}
                com.cognitect/rebl
                ;; adjust to match your install location
                {:local/root "/Users/ozimos/REBL/latest/REBL.jar"}
                org.openjfx/javafx-fxml     {:mvn/version "12.0.1"}
                org.openjfx/javafx-controls {:mvn/version "12.0.1"}
                org.openjfx/javafx-graphics {:mvn/version "12.0.1"}
                org.openjfx/javafx-media    {:mvn/version "12.0.1"}
                org.openjfx/javafx-swing    {:mvn/version "12.0.1"}
                org.openjfx/javafx-base     {:mvn/version "12.0.1"}
                org.openjfx/javafx-web      {:mvn/version "12.0.1"}}}
;; nREBL
  :rebl-nrepl {:extra-deps {rickmoynihan/nrebl.middleware {:mvn/version "0.2.0"}}
               :main-opts ["-m" "nrepl.cmdline" "--middleware" "[nrebl.middleware/wrap-nrebl]" "-I"]}
```
I also added the following to my vscode settings.json
```
"calva.replConnectSequences": [
        {
            "name": "Rebl Connect",
            "projectType": "Clojure CLI",
            "afterCLJReplJackInCode": "(require 'cognitect.rebl) (cognitect.rebl/ui)",
            "menuSelections": {
                "cljAliases": [
                    "rebl-12",
                    "rebl-nrepl"
                ],
            }
        }
    ],
```

**Comment by PEZ** [comment]
^ This ^ would be fantastic to have on the wiki. Just sayn' :smile:

**Comment by PEZ** [comment]
Thanks to @ozimos , we now have a wiki page describing how to do this:

https://github.com/BetterThanTomorrow/calva/wiki/Using-with-REBL

🎉
