### ISSUE TITLE
"Eval on save" causes files to be opened incorrectly

### ISSUE THREAD

**Issue by svdo** [BetterThanTomorrow/calva#2402]
There seems to be a breaking change in the latest release, v2.0.412 in "eval on save" (maybe last release because of https://github.com/BetterThanTomorrow/calva/issues/2389?). I have both "auto save" set to "on focus change", and also Calva's "run on save" enabled. This combination now causes files to be opened incorrectly.

Examples:

1. I always work with at least three panes in VSCode: on the left I have the Calva repl out, in the middle I tend to have the unit tests, and on the right the production code. Recently there was a change that unsaved files all of a sudden automatically get opened at strange times. I have (unsaved) changes in my test file, I go to the right pane to edit the production code, and all of a sudden my test code is also opened on the right.
2. I have unsaved changes, I command-click a symbol to go to a definition, and boom I'm right back where I came from because the changes got saved, code eval'ed, and then the file displayed again. 

Can this be fixed? Thanks!!

**Comment by PEZ** [comment]
I'm sorry for the inconvenience!

This PR should fix it:

* https://github.com/BetterThanTomorrow/calva/pull/2403

Can you pick up the VSIX there and check, @svdo?
