### ISSUE TITLE
Support clojure-lsp Project Tree feature

### ISSUE THREAD

**Issue by ericdallo** [BetterThanTomorrow/calva#2406]
As presented and discussed [here](https://clojurians.slack.com/archives/CBE668G4R/p1705320412535089).

clojure-lsp added recently a new feature called [Project Tree](https://clojure-lsp.io/features/#project-tree) that is supported only by Emacs ATM.

PR coming

**Comment by PEZ** [comment]
Ah, forgot to check if you had closed this with a commit, @ericdallo 😄
