### ISSUE TITLE
Calva notebooks namespace eval issue

### ISSUE THREAD

**Issue by djblue** [BetterThanTomorrow/calva#2408]
Calva notebooks seem to be unable to evaluate code for the ns declared at the top of the file. For example, I get the following by simply evaluating the first two blocks in a notebook.

![image](https://github.com/BetterThanTomorrow/calva/assets/1986211/2661ae70-63ec-48ff-a4b3-8a9c50bd4811)

If I explicitly set the namespace, everything works as expected:

![image (1)](https://github.com/BetterThanTomorrow/calva/assets/1986211/8b42b15d-55aa-4670-9105-a679a211f51d)

**Comment by PEZ** [comment]
We'll close this once we release it.
