### ISSUE TITLE
No stacktrace from cljs startup error

### ISSUE THREAD

**Issue by SevereOverfl0w** [BetterThanTomorrow/calva#241]
When doing a ClojureScript jack-in and getting an error, no error output to indicate the cause is output, only `Error while connecting cljs REPL: Aborted`.

**Comment by SevereOverfl0w** [comment]
oh, I found it. I'm just being stupid. Sorry!

**Comment by PEZ** [comment]
Where did you find it?

**Comment by SevereOverfl0w** [comment]
So, I think that for Figwheel main calva has some special handling which I dismissed because I'd stupidly misconfigured my project. For that, the error message was a pop-up.

For the case where I intentionally added an exception for testing, it put it in a particular output. And it did tell me so.

I think I wasn't paying enough attention the first time round :)'

Sat Jun 29 12:23:32 GMT+01:00 2019 Peter Strömberg <notifications@github.com>:
