### ISSUE TITLE
Calva effects vim motion targets

### ISSUE THREAD

**Issue by tggreene** [BetterThanTomorrow/calva#2410]
I'm finding that the Calva extension modifies vim motion with respect to some symbols common in clojure, specifically ignoring `:"'({[`. For example when pressing `w` before the string ` :hello`, calva+vim will select `h` where vim alone would select `:`. Here's a demo of vim with calva and vim without calva (the keys used are `w+0` for each line):

with calva:
https://github.com/BetterThanTomorrow/calva/assets/1188382/f22c971d-b6b6-4c17-8165-ed8a35c78ad8

without:
https://github.com/BetterThanTomorrow/calva/assets/1188382/e0ea2591-4bf0-4cb5-ae04-443e74a2142b

Thanks!

**Comment by PEZ** [comment]
Hi! Thanks for reporting.

You will need to describe this to someone not familiar with the Vim Extension, though. (If you are using the Vim Extension? Maybe something else?= The gifs do not tell me anything, unfortunately.

Try explain it in terms of:
* I have this text, and the cursor here (we usually indicate the cursor with `|`)
* When I do this (use a command, or press some keys):
  * I expect ... (text showing expected cursor position)
  * Instead I ... (text showing actual cursor position)

I'm actuallyespecially curious about wether this happens only from the keyboard presses/shortcuts, or if it also affects the actual commands used (if there indeed are any such commands, I am completely unfamiliar with the Vim Extension).

Also I'd like to know if this happens only in Clojure code or also affects other code.

**Comment by tggreene** [comment]
Sure! I'm using the vscodevim Vim extension. I'll use the pipe to describe the normal mode cursor position of the character following the pipe so `|a` would mean the cursor is over a.

When I say "motion targets" I essentially mean the parts of text that can be navigated to when using various vim motion commands such as word `w` to navigate to the start of a word.

The main issue is as follows; I have the text `|  :abc` and when I use `w` I expect the cursor to be in the position `  |:abc` but instead have `  :|abc` (essentially skipping the `:` character, this is true for all characters in `:'"([{}])` and `).

In looking at it a bit more closely I've also found that spaces between words are also motion targets. I have the text `|abc def` if I use `w` I expect the cursor to be in position `abc |def` but instead have `abc| def`.

The above issues also effect compound vim commands that take a motion argument i.e. delete word `dw`.

The capitalised motion commands (essentially including all non-whitespace characters) `WB` are unaffected and work normally.

I can't find a way of invoking the motion commands from the command palette (and I'm not familiar enough with the vim extension myself to know how they're implemented).

This only happens with clojure and only with the calva extension enabled.

I'm entirely open to this being a issue local to my configuration/environment as no-one else seems to have raised this issue. I've run vscode with everything but vim and calva loaded to run through these issues.

**Comment by tggreene** [comment]
It almost looks like every non-alphanumeric character is being treated like whitespace and whitespace is being treated as a word target. If that makes any sense. It's really quite odd.

**Comment by PEZ** [comment]
Thanks! I wonder if it could be the `editor.wordSeparators` defaults that Calva contributes, that is messing things up for the Vim motion. If you open workspace settings JSON (there's a command for that) and start type `[clojure]`, you should get auto-completions help for inserting the defaults that Calva contributes. You should find the wordSeparators setting there. See if it has any effect on the Vim motion (it may have other effects too, but just to check).

**Comment by tggreene** [comment]
Ah, that's perfect. I think the addition of `\t ` to the word separator list was causing this (removing it fixes the problem). I've dropped back to the default provided by vscode for now. Will this have any knock on effect to Calva do you think?

**Comment by PEZ** [comment]
I think that whatever knock on effect on Calva it may have will be about what happens if you double click text, matched word highlighting and such. Please keep us posted about how you fare.

**Comment by tggreene** [comment]
This has completely solved the issue for me and haven't noticed any side effects of changing the `editor.wordSeparators` value.

Thanks very much for your time Peter!

**Comment by PEZ** [comment]
Closing this, but we should consider whether Calva really needs to contribute those defaults.
