### ISSUE TITLE
Add `.lpy` as a support clojure file extension

### ISSUE THREAD

**Issue by ikappaki** [BetterThanTomorrow/calva#2415]
Hi,

I would like to add [Basillisp ](https://github.com/basilisp-lang/basilisp)file extension, `.lpy`, to the list of supported Clojure Calva extensions.

Basilisp is a highly compatible Clojure dialect for Python. It has an nREPL server that Calva can automatically connect using the Generic connect via a `.nrepl` file.

I haven't thought about how to jack-in to it because it would require spawning Python but in a virtual environment.

PR to follow.

Thanks

**Comment by bpringe** [comment]
It seems this wasn't closed automatically.
