### ISSUE TITLE
Loading repl with profile declared in `~/.lein/profiles.clj`

### ISSUE THREAD

**Issue by enhan** [BetterThanTomorrow/calva#242]
I encounter an issue when I try to jack in a project.

Given the following setup:
- a set of corporate repositories associated with a profile in `~/.lein/profiles.clj`
- a project using dependencies published in the aforementioned repositories

When I try to jack in this project, I am not able to select my profile (I just select 'Leiningen" as project type and the task starts directly) resulting in loading failure.
The trace is:

```
:repositories detected in user-level profiles! [:myprofile] 
See https://github.com/technomancy/leiningen/wiki/Repeatability
Could not find artifact {MyArtifact} in central (https://repo1.maven.org/maven2/)
Could not find artifact {MyArtifact} in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
The terminal process terminated with exit code: 1
```

Is there anything I can do to fix this, or is it a bug ?

**Comment by bpringe** [comment]
@enhan Did you ever figure out what was going on here? If you still have this issue, can you provide more details?

**Comment by PEZ** [comment]
I think it has to do with that `{MyArtifact}` thing there. Closing this, and it can be reopened if it still suspected to be a Calva issue.
