### ISSUE TITLE
Allow to use an array of strings for `afterCLJReplJackInCode` in a connect sequence

### ISSUE THREAD

**Issue by dionysus98** [BetterThanTomorrow/calva#2423]
- The ```afterCLJReplJackInCode``` key in the ```replConnectSequences``` can only accept **string** as an value for now. 
- This creates an issue that when I enter code in the new line, for readability, the *formatter/linter* throws an EOString exception.
- Could it be done so, the value for that key can be a vector of strings, just like **vscode** snippets.

**Comment by PEZ** [comment]
Hi! Thanks for pointing this out. Generally I think most people call some function and keep longer code snippets from the JSON. But I still think your suggestion makes sense. Sounds good with allowing a vector there.
