### ISSUE TITLE
Shortcuts in Calva editor triggered even out of editor tab

### ISSUE THREAD

**Issue by CheatEx** [BetterThanTomorrow/calva#244]
When I have a Clojure editor open and use a shortcut elsewhere it is triggered in editor window. 

For example when I edit commit message in sidebar and use Ctrl+Del or Ctrl+Backspace (it's a default delete word forward/backward shortcut for PC keyboards) nothing happen in the commit message input, but in editor next/previous form gets deleted. Furthermore focus remains in the input and undo shortcut also works there.

This one especially bad because you may end up committing badly broken code.

It happens with search/find action inputs, but not in terminal and Calva's REPL.

**Comment by PEZ** [comment]
I can reproduce it.

No idea right now how to stop that madness. VSCode doesn't make it easy...

**Comment by PEZ** [comment]
I've managed to stop it from happening in the sidebar and in the panel. I still don't know how to prevent it in the editor search box and quick pick menu, though...

**Comment by CheatEx** [comment]
Thanks. It's much better now, having it in commit message box was disastrous.

**Comment by cfehse** [comment]
@CheatEx 

This should be fixed with the new keyboard shortcuts. I tested the cases you mentioned in the description and the default shortcuts worked as expected. I will close this issue for now but feel free to reopen it if further problems persist.

Thanks.
