### ISSUE TITLE
Calva Load File Command Results in RangeError on certain machine

### ISSUE THREAD

**Issue by zacharyc** [BetterThanTomorrow/calva#2443]
When running "Calva: Load/Evaluate File" command in version 2.0.423 and beyond, I run into a RangeError:

```
; Evaluating file: dev.clj
; Evaluation of file dev.clj failed: RangeError: Maximum call stack size exceeded
```

I have tested this on multiple computers, but it only happens on my one machine. When I go back to version 422, it works as expected.

**Comment by zacharyc** [comment]
Just for documentation purposes, @PEZ and I did a coding session and we think the issue is tied to bencode. Still needs more investigation.

**Comment by PEZ** [comment]
Fixed by https://github.com/kurtharriger/calva/commit/072670c6553a1196cd83dce707543b7bf0b09c00
