### ISSUE TITLE
Output pane ("Calva says") keeps popping up

### ISSUE THREAD

**Issue by filipesilva** [BetterThanTomorrow/calva#246]
I have a shadow-cljs project to which I have jacked in, and have calva configured to evaluate on file save. Everytime I save, the "Calva says" output window helpfully logs that the file has been evaluated.

If I close the output pane completely and save a file, it will re-open it and show the evaluating message. This is problematic because it means I need to always have the output pane open, losing some screen real estate. I could try to make it very small so the space I lose is reduced. But since the output pane and the terminal pane are in the same panel, when I want to use the terminal I would need to resize the panel again.

I think there must be a way to prevent this from happening because there are several tabs in the output pane that don't pop up on every message. For instance, the git pane has many messages but it did not pop up.

Thank for you work in this extension!

**Comment by PEZ** [comment]
Thanks. Yes there is a way to write to the output pane w/o popping it up. And I agree it should not pop up on auto-evaluation. (I don't use that myself, so haven't noticed this.)

**Comment by filipesilva** [comment]
That was super quick, thank you!
