### ISSUE TITLE
Add legacy opt-in for printing bare `stdout` to the REPL Window

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#2470]
When introducing the new output destination options we also changed how stdout is printed in the REPL Window if it remains configured as the destination for such output. The change made this output line comments in the REPL Window, to protect the structure of the Clojure document, and to make the window handle more output (as one line comment token can possibly replace many, many word tokens when the output is printed bare.

However, there have been confusion about this for some users. Sometimes it is mostly about it being unfamiliar, but there are also cases where the workflow of some users more or less demands bare output. There are of course options to print it to other destinations, where the output is bare, but nonetheless, in lack of an output destination that is similar enough to the REPL Window in functionality (Paredit, read/write, etc) I think an option to retain the legacy behaviour for now could be added. Opt in. We can remove it later when we have bridged the functionality gap some more.

**Comment by LouDnl** [comment]
Thanks for this! 👊🏻💪🏻
