### ISSUE TITLE
Debugger clashes with Emacs / Cider

### ISSUE THREAD

**Issue by yuhan0** [BetterThanTomorrow/calva#2496]
I've noticed that when both Calva and Cider are connected to the same nREPL server, attempting to eval a #dbg tagged form in Emacs causes Calva to take over control of the evaluation in the background and start a debugging session, which can be quite unexpected behaviour.

**Comment by PEZ** [comment]
Thanks. I've tested it a bit and couldn't reproduce, but I am not good with Emacs at all. I think the only way to tackle it for now would be to add something to the documentation, https://calva.io/debugger/ about this.
