### ISSUE TITLE
Sending a selection of forms to the REPL only sends the first form

### ISSUE THREAD

**Issue by alzadude** [BetterThanTomorrow/calva#250]
Steps:
Connect to running nrepl server
Open a clj/cljs file
Select two or more forms in the editor
Press Ctrl+Alt+C, Ctrl+Alt+E

Expected:
All selected forms are sent to the REPL

Actual:
Only the first form in the selection is sent

**Comment by PEZ** [comment]
Hello. I can't reproduce this. When I try it, all selected text is sent to the REPL window.

**Comment by cfehse** [comment]
I cannot reproduce this issue as well with version 2.0.49. The exact selection will be send to the REPL window.
