### ISSUE TITLE
unexpected cursor movement when using 'Strict Prevent Unmatched Closing Brackets'

### ISSUE THREAD

**Issue by CmdrDats** [BetterThanTomorrow/calva#2500]
With this text:

```
(a {|})
```

Type `}` and expect:
```
(a {}|)
```

Actual:
```
  |(a {})
```

With `Strict Prevent Unmatched Closing Brackets` unchecked, this behaves as expected.

**Comment by PEZ** [comment]
Thanks. This feature is really forced upon the VS Code API to help with, so it may be tricky to fix. But it could also be a simple mistake.

**Comment by PEZ** [comment]
I think the best path to take here is to retire the feature. VS Code has a better version built-in:

<img width="456" alt="image" src="https://github.com/BetterThanTomorrow/calva/assets/30010/662d3ea2-8b7f-4297-9950-f9a0c9401af9">

We could make it default to that, just as we default to auto-adding closing brackets.

**Comment by CmdrDats** [comment]
ah, nice - makes sense to just lean on vscode!

**Comment by PEZ** [comment]
I wonder if that setting was there when I added this feature. 😄

**Comment by riotrah** [comment]
While I'm personally overjoyed to have this fairly annoying behavior removed, I wonder if it will also remove a different useful behavior:

If I try to add extra closing brackets, Calva currently prevents me (if my computer is slow enough, I can see the bracket being added and then deleted clearly).

Is `strictPreventUnmatchedClosingBracket` also responsible for that behavior? I'd love to preserve it if possible.
