### ISSUE TITLE
Throws error when debugging atoms

### ISSUE THREAD

**Issue by javierrweiss** [BetterThanTomorrow/calva#2501]
The problem arises when debugging a function using an atom. In this particular case the atom is declared within a let binding.
In order to reproduce the issue:

0. Clone this [repo](https://github.com/javierrweiss/calva-debugger-issues):
1. Use "Instrument top level form for debugging" command.
2. Then either use the "Step over" or "Step out" commands.
3. Finally, in this particular reproduction case it will throw the error when evaluating the swap! function.

**Comment by PEZ** [comment]
I've tracked this down to an issue with `cider-nrepl`. Reported here:

* https://github.com/clojure-emacs/cider-nrepl/issues/865

**Comment by PEZ** [comment]
Nope, it is Calva that needs to handle this case. The expression `@!a` should be treated as `(deref !a)`. Behind the scenes there really is a list to navigate inside.

**Comment by PEZ** [comment]
cc: @jpmonettas just to keep you in the loop.

**Comment by javierrweiss** [comment]
Ok. This makes sense: that's why I also had issues when dereferencing a
Future, though I wasn't able to reproduce the issue.

**Comment by PEZ** [comment]
Here's a Calva build where this should be fixed. https://output.circle-artifacts.com/output/job/5713bad8-6680-4f9f-aba8-d1e585713fee/artifacts/0/tmp/artifacts/calva-2.0.437-2501-debug-atoms-0baa8fdb.vsix

Can you take it for a spin, @javierrweiss ?

**Comment by PEZ** [comment]
Here's how to install a VSIX package: https://github.com/BetterThanTomorrow/calva/wiki/Testing-VSIX-Packages#installing-a-vsix-package

**Comment by javierrweiss** [comment]
Hi Peter,

I tried some simple examples and it seems to work fine.

Best,

 JJ
