### ISSUE TITLE
Calva: Replace Current Form seems to stop working from v2.0.428 onwards

### ISSUE THREAD

**Issue by mmeroberts** [BetterThanTomorrow/calva#2512]
I use this function to reformat an edn file that represents a map and it should reformat it from one long line to a nice formatted doc.

It was working until 428, when it appears to no longer work.

`{:base {:key1 "long string" :key2 "another long string", :key3 "string with CAPITAL", :address "somemachine somewhere"}, :users {, :user {:api-key "randomstring", :password "randomvalue", :username "admin"}}}`

should end up like:

```
{:base {:address "somemachine somewhere"
        :key1 "long string"
        :key2 "another long string"
        :key3 "string with CAPITAL"}
 :users {:user
         {:api-key "randomstring" :password "randomvalue" :username "admin"}}}
```

**Comment by PEZ** [comment]
Thanks. Another symptom is that it re-indents. It's the breaking up in lines that's broken.
