### ISSUE TITLE
Test explorer creates a test case each time a keystroke is registered

### ISSUE THREAD

**Issue by hjbolide** [BetterThanTomorrow/calva#2530]
### Environment
VsCodium: v1.88.1
Calva: 2.0.446

### Issue
Test explorer creates a test case each time a keystroke is registered, ended up having a lot of test cases with cut up names. Not sure if it's related, the gutter icons are all over the place.
Reloading the namespace or whole repl doesn't help.

### Screenshots
![Screenshot 2024-04-22 at 9 31 27 PM](https://github.com/BetterThanTomorrow/calva/assets/416502/7e004b88-c07a-4a5c-938b-e14d6706b57b)

![Screenshot 2024-04-22 at 9 40 08 PM](https://github.com/BetterThanTomorrow/calva/assets/416502/a0c914c9-6a0f-4fb5-8a8a-3e4eecb278e1)

Has anyone run into this issue before and have a workaround?

Thanks.

**Comment by PEZ** [comment]
Oh, wow. That's really weird. And awful. Is there a way you can create a reproduction project? It needn't be a super minimal repro to begin with. We can try to shrink it together.

**Comment by hjbolide** [comment]
I'll work on it some time today and share the repo link here.

Thank you PEZ.

**Comment by hjbolide** [comment]
Hi PEZ:

Please find the minimal clojure project I have set up: https://github.com/hjbolide/minimal-clj.

What I noticed also during this is: test explorer only updates whenever things are added to the file, new paste, new typed in characters, deletion doesn't seem to update the test explorer at all.

Here's another couple of screenshots:

![Screenshot 2024-04-23 at 12 44 23 PM](https://github.com/BetterThanTomorrow/calva/assets/416502/dec42240-ba1e-4c33-a3d4-a5648561895e)
![Screenshot 2024-04-23 at 12 44 32 PM](https://github.com/BetterThanTomorrow/calva/assets/416502/59fe96ea-fc71-49ec-90a5-54c6b315b7a7)

Thank you for your time.

**Comment by PEZ** [comment]
Hi, thanks for the project. To make it a repro project, please add instructions to it of how to reproduce the problem. I'm not a test explorer user so it needs to be a bit detailed.

**Comment by hjbolide** [comment]
Oh I'm sorry, let me add the detailed steps:

### Steps to reproduce

* Turn on "Use Test Explorer" in Calva settings:
![Screenshot 2024-04-23 at 4 46 31 PM](https://github.com/BetterThanTomorrow/calva/assets/416502/62ff63ee-7043-4b86-bf60-75d9712b8879)

* Add the following block to settings.json:
```
"calva.replConnectSequences": [{
  "name": "repl",
  "projectType": "Leiningen",
  "menuSelections": {
    "leinAlias": null,
    "leinProfiles": []
  }
}],
```

* Checkout repo: https://github.com/hjbolide/minimal-clj

* Open project using VsCodium File -> Open Folder

* Start a project REPL (Jack-in), and select `repl` as project type

* Navigate to namespace `minclj.domain.auth-test`

* Switch view to Test Explorer:
![Screenshot 2024-04-23 at 5 10 52 PM](https://github.com/BetterThanTomorrow/calva/assets/416502/8d22be69-bfd3-4f57-a8ec-07564ff0618b)

* Make change to test case `test-platform-admin-truthy-value` by deleting a few characters

* Notice the Test Explorer tree having more and more test cases:
![Screenshot 2024-04-23 at 5 13 04 PM](https://github.com/BetterThanTomorrow/calva/assets/416502/e520c118-fe7d-43eb-b342-031fef446103)

**Comment by PEZ** [comment]
I can reproduce this easily with any project. It seems we do not implement clojure-lsp testTree as we should. @ericdallo where can I read about how to implement it properly? The problem here is that we get notifications for the new deftest symbol, but we don't get anything about the old one, so I am guessing we should listen on something more than just this: 

```ts
    client.client.onNotification('clojure/textDocument/testTree', (tree: defs.TestTreeParams) => {
      params.testTreeHandler(tree);
    });
```

**Comment by ericdallo** [comment]
@PEZ sorry, I think I missed this one.
Calva should clean the tree for the received URI and re-apply its data, so I think we are just missing the cleaning

**Comment by PEZ** [comment]
Thanks, @ericdallo. That makes sense.
