### ISSUE TITLE
Calva fails to set the focus on the output repl windown, when toggling using the ```@command:calva.showResultOutputDestination```.

### ISSUE THREAD

**Issue by dionysus98** [BetterThanTomorrow/calva#2547]
- I'm not sure if this is a bug or a feature.
- When I switch to the repl window using the keyboard shortcut ```ctrl+alt+o o```,  it does switch to the otuput file, but it doesn't set the cursor **focus** to that window.
- This is the vscode command: ```@command:calva.showResultOutputDestination```
- Calva version: 2.0.451

If this is a feature, I'm sorry about this report.

**Comment by PEZ** [comment]
Hi! Thanks for reporting.

It is on purpose. There is a separate command for opening the REPL Window, with the default keybinding of `ctrl+alt+o r`, which will also focuses the window. The rationale is that output is something you want to see, and the repl is something you want to interact with.

Nevertheless. You put the finger on a lack of documentation, and also a lack of flexibility. The latest version of Calva, v2.0.452, addresses the latter by making the command (and related commands) take an argument which lets you choose if they should focus the output view or not. And I also added some documentation around it:

* https://calva.io/output/#commands-for-showing-output-destinations

**Comment by dionysus98** [comment]
Thank you. That's really helpful.
