### ISSUE TITLE
Overly aggressive paredit in REPL window

### ISSUE THREAD

**Issue by lspector** [BetterThanTomorrow/calva#255]
If I type `[1 2 3]` in the REPL window and then decide that I want it to be `(shuffle [1 2 3])` then if I click at the beginning and type `(` then it adds `)` right after it automatically, which is the sort of thing I've come to expect both in Calva and in other environments... *but* unlike when this happens in other contexts there appears to be no way to delete the `)` no matter what I do.

I know that I'm an outlier in not personally liking any automatic typing of closing brackets ever, and also in not wanting to learn/use Paredit commands (I prefer ordinary typing), and I don't expect the behavior of Calva to change in response to my preferences! But the middle ground adopted in Calva editor windows -- adding closing brackets but letting me delete them -- works well enough for me, and presumably also for others.

So my request is that the REPL window acts like the editor windows in this respect.

**Comment by PEZ** [comment]
Thanks. It is a pity with the separate behaviours between the prompt and the editors. I'll see what I can do about it. Meanwhile, you might find that `alt+backspace` is your friend at times. It force-deletes stuff, bypassing paredit's demands for structure integrity.

**Comment by lspector** [comment]
Ahh, thanks -- `alt+backspace` is indeed now my friend. I hope I don't forget about it, and agree that consistent behaviors would be desirable in the long run.
