### ISSUE TITLE
Extend "Refresh Changed Namespaces" to accept optional parameters exposed by cider-nrepl

### ISSUE THREAD

**Issue by jlesquembre** [BetterThanTomorrow/calva#2556]
Calva exposes 2 commands, "Refresh Changed Namespaces" and "Refresh All Namespaces", which invoke `cider-nrepl`  [refresh](https://docs.cider.mx/cider-nrepl/nrepl-api/ops.html#refresh) and [refresh-all](https://docs.cider.mx/cider-nrepl/nrepl-api/ops.html#refresh-all). 

Those accept multiple optional parameters, in particular `:after` and `:before` are useful to perform certain operations after and/or before refreshing the namespaces. 

Currently, it isn't possible to customize those parameters from Calva. It would useful to allow users to provide their own `before` and `after` functions. 

A case for those is to invoke `malli.instrument/instrument!` or `donut.system.repl/start` after a refresh.

**Comment by PEZ** [comment]
Thanks for reporting! 🙏 

A way to do so is to execute two commands, first the refresh and then a repl evaluation. The `runCommands` command lets you do things like this. See https://blog.agical.se/en/posts/vs-code-runcommands-for-multi-commands-keyboard-shortcuts/ The repl evaluation command can be specified like so in a keybinding or in a `runCommands` keybinding:

```json
    "command": "calva.runCustomREPLCommand",
    "args": {
      "snippet": "some-clojure-code"
    }
```

The arguments for this command are specified here: https://calva.io/custom-commands/

Unfortunately, the **refresh** command in Calva is not returning the promise correctly so runCommands won't wait for it to finish before following up with the repl command. So you would have to do some thread sleeping, until we have fixed the issue with the promise.

**Comment by PEZ** [comment]
As it hard to tell how long time the refresh will take, sleeping may be a bit too inconvenient. For now it may be better with a separate keybinding for the repl command and you would issue it manually once you see that the refresh is done.

**Comment by jlesquembre** [comment]
@PEZ thanks for the suggestion. For now, I'm good with executing manually the repl command after the refresh. I tested it and it's working as expected :)

**Comment by PEZ** [comment]
To add to your options, there is a case for configuring repl commands like this in project settings (as described in https://calva.io/custom-commands/).

* All Calva users in the project can share the shortcut
* There's a keyboard shortcut bringing up a menu of configured repl commands, `ctrl+alt+space ctrl+alt+space`, making it less to memorize, depending on how often the command is used

You can still bind a regular keyboard shortcut, without duplicating the code snippet, using the `key` in the custom repl commands config, see: https://calva.io/custom-commands/#binding-keyboard-shortcuts

**Comment by PEZ** [comment]
Please have a look at https://calva.io/commands/, @jlesquembre, and let us know how you fare.

**Comment by jlesquembre** [comment]
:pray: thanks a lot @PEZ ! I just tried it and it is working perfectly!

I added this to my keybings:

```
{
        "key": "ctrl+alt+c c",
        "command": "calva.refresh",
        "args":{
            "after": "local-utils/reload-system"
        },
        "when": "calva:activated"
 }
```

`local-utils/reload-system` are my local dev utils, that reloads the system (and also refreshes Malli instrumentation) after a refresh :)

**Comment by PEZ** [comment]
Awesome! Then we have one using this `:after` option and one (as reported on Slack) who uses the `runCommands` way of doing it.
