### ISSUE TITLE
Write clj-kondo and lsp folders to clojure project workspaces **exclusively**

### ISSUE THREAD

**Issue by InSuperposition** [BetterThanTomorrow/calva#2568]
Each time a workspace or project is opened in VS code, Calva writes the cache folders to the root of the opened directory. This happens regardless of language used and is unnecessary for most projects.
Perhaps a check for `deps.edn` and/or lein's `project.clj` could help to determine the behavior.

**Comment by PEZ** [comment]
Calva should only activate in Clojure projects. Can you give an example of a project where this happens?

**Comment by InSuperposition** [comment]
Its happening in [my dotfile repo](https://github.com/InSuperposition/.file), which contains a git submodule at [`.config/clojure`](https://github.com/InSuperposition/clojure) and that repo contains a `deps.edn` file.

I tried adding the paths in various combinations to Calva's `Project Roots Search Exclude` setting but each time I restart the folders are added back.

**Comment by PEZ** [comment]
The **Project Root Search Exclude** setting doesn't control this. The activation is pretty hard coded in the VS Code Extension manifest for Calva. Not all that much we can do about it. Maybe what you can do is disable the Calva extension in your dotfiles repo.

**Comment by InSuperposition** [comment]
That worked, I was not aware of that feature for extensions. Not exactly what I was hoping for initially, but this will work nicely. I appreciate the feedback. Closing the issue.

**Comment by PEZ** [comment]
Another option is to configure the auto-start of clojure-lsp to not happen by default in your user settings and then configure it to auto-start only in selected workspaces.
