### ISSUE TITLE
Use of undeclared var in REPL window resets the namespace

### ISSUE THREAD

**Issue by CheatEx** [BetterThanTomorrow/calva#257]
Steps:
1. Switch any window to any namespace
2. Evaluate some unknown variable, `(fake)` for example
3. Got exception (see below)
4. Namespace becomes `cljs.user`

Expected: namespace doesn't change.

Example session

> do-stack.tasks-test=> (fake)
> core.clj: | 4739 | clojure.core/ex-info
> -- | -- | --
> core.clj: | 4739 | clojure.core/ex-info
> repl.cljc: | 577
> repl.cljc: | 498
> piggieback.clj: | 208 | cider.piggieback/eval-cljs
> piggieback.clj: | 207 | cider.piggieback/eval-cljs
> piggieback.clj: | 244 | cider.piggieback/do-eval/fn
> AFn.java: | 152 | clojure.lang.AFn/applyToHelper
> AFn.java: | 144 | clojure.lang.AFn/applyTo
> core.clj: | 657 | clojure.core/apply
> core.clj: | 1965 | clojure.core/with-bindings*
> core.clj: | 1965 | clojure.core/with-bindings*
> RestFn.java: | 425 | clojure.lang.RestFn/invoke
> piggieback.clj: | 221 | cider.piggieback/do-eval
> piggieback.clj: | 220 | cider.piggieback/do-eval
> piggieback.clj: | 267 | cider.piggieback/evaluate
> piggieback.clj: | 265 | cider.piggieback/evaluate
> Var.java: | 381 | clojure.lang.Var/invoke
> piggieback.clj: | 299 | cider.piggieback/wrap-cljs-repl/fn/fn/fn
> piggieback.clj: | 191 | cider.piggieback/enqueue/fn
> AFn.java: | 22 | clojure.lang.AFn/run
> session.clj: | 171 | nrepl.middleware.session/session-exec/main-loop/fn
> session.clj: | 170 | nrepl.middleware.session/session-exec/main-loop
> AFn.java: | 22 | clojure.lang.AFn/run
> Thread.java: | 834 | java.lang.Thread/run
> cljs.user=>

**Comment by cfehse** [comment]
@CheatEx  @PEZ 

I can reproduce this behavior. I will take a look at this.

**Comment by cfehse** [comment]
@CheatEx  This issue is fixed in version 2.0.49.
