### ISSUE TITLE
Getting Started REPL fails when there is no folder open

### ISSUE THREAD

**Issue by librejutsu** [BetterThanTomorrow/calva#2572]
Type: <b>Bug</b>

```
Command 'Calva: Fire up the Getting Started REPL' resulted in an error
Cannot read properties of undefined (reading 'map')
```

In order to reproduce just launch the `Calva: Fire up the Getting Started REPL` command in either OSS Code or regular VS Code. (Tried it in both).

**I also tried this on a completely fresh VS Code install on Ubuntu on another PC and got the same error, so it doesn't seem to be related to my system per se.**

Extension version: 2.0.456
VS Code version: Code - OSS 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-07T07:53:34.265Z)
OS version: Linux x64 6.9.3-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz (4 x 3799)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|15.56GB (9.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by PEZ** [comment]
Hi! Thanks for reporting! It could be that the latest changes to this makes assumptions that do not hold on Linux. I'll look at it pronto!

**Comment by PEZ** [comment]
It wasn't about Linux either. This fails when the command is run from a VS Code window that has no folder opened. Because we changed things so that we start the clojure-lsp server also for the Getting Started REPL.

**Comment by PEZ** [comment]
And... it wasn't even that. It was some files missing at the tutorial repository. Please try again, @librejutsu, and let me know if it works now.

**Comment by librejutsu** [comment]
It works now! Thanks a lot!
