### ISSUE TITLE
Send to REPL

### ISSUE THREAD

**Issue by karls** [BetterThanTomorrow/calva#259]
Hi,

Thanks for Calva!

I'm trialling VS Code and Calva coming from Emacs + Cider and it's looking really nice so far.

One thing I haven't been able to figure it is how to port a specific workflow that I have in Emacs. Namely, in Emacs I have a `ctrl+c r` bound to a.. I guess a macro, which basically finds the REPL, types `(reset)` in there, presses `<enter>` and switches back to the last buffer. The idea is that when working on a web service that I want to reload after having done some code changes, I can just press this key chord and it'll reload everything automatically.

The first thing to prefix this with is the fact that I'm totally new to VS Code and Calva, so what I' trying to do may have a really simple solution, but I just don't know enough about the ecosystem.

I tried various things in VS Code without much success. For instance, AFAICT, the "command" feature only takes one command, so they can't be chained "natively". I tried a macro extension, but that doesn't seem to work either. I see that Calva has various functions that seem to have the "right" name — there is `sendTextToREPLWindow` in `repl-window.ts` which looks like it might work. But AFAICT it's not exported, so I'm not sure how to make use of that. There are various evaluation functions in `evaluate.ts`, but I can't seem to work out how to use them when you just want to evaluate some pre-defined text in the REPL.

How should I approach this? Create a new extension and depend on Calva? Add this feature to Calva in a PR? Maybe there is a really simple solution using exising functionality that I'm just not seeing?

**Comment by PEZ** [comment]
Hello,

I think that functionality belongs in Calva. I would love me a PR with it. There is an old branch where I started with it actually. Let's see... https://github.com/BetterThanTomorrow/calva/tree/custom-commands-wip But it is really old so might be a bit of a puzzle to merge back. I can try see if I can merge master onto it.

The basic idea with that branch was to let the user define custom commands in `settings.json` and then use VS Code's quick pick UI for firing them. I remember I had some idea of numbering the commands and then it would be a bit like chording keyboard shortcuts... A problem I ran across is that the VS Code API does not let us pick up User and Workspace settings separately. I think the solution there is to simply have separate commands for accessing the user and workspace custom commands. If we name the commands and the settings well, it should be clear to the users how to configure and use it.

We can talk more about it on Slack, or some other chat/voice channel. It usually is quicker to sort things out that way.

**Comment by PEZ** [comment]
Hello again,

So that branch was a bit older than I remembered! 😄 

Anyway, I've merged it and retrofitted it onto the new REPL Window. Also managed to get a bit lost in the merging so created a new branch: https://github.com/BetterThanTomorrow/calva/tree/wip/custon-commands

Let's try to connect and chat some about this and we might have something great cookin'

**Comment by PEZ** [comment]
Closing this and letting it continue in #281.
