### ISSUE TITLE
Return values and stdout do not appear in the REPL window

### ISSUE THREAD

**Issue by gentius** [BetterThanTomorrow/calva#2607]
Type: <b>Bug</b>

With the below version of the extension, upon creating a mini Clojure Project I wasn't able to see return values or stdout messages in the REPL window (.calva/output-window/output.calva-repl) with the default settings.

I used the standard "Start your project with a REPL and connect (a.k.a. Jack-in)".

Otherwise, Errors do show up in the REPL window (prefixed with "; "), I can see return values as well as stdout in the Calva Output Terminal, and I can also see return values inline in the editor when evaluating a form.

Extension version: 2.0.467
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1345U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.35GB (11.57GB free)|
|Process Argv|--crash-reporter-id 59f142d2-f370-4b49-b9be-0939f847d5ee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-c:31111717
wkspc-ranged-t:31123313
ei213698:31121563

```

</details>

**Comment by PEZ** [comment]
Hello,

The mini project has local settings that uses the VS Code terminal for output. Is that what's going on? The mini project should inform about that there is custom settings. Looks like so when I run the command:

<img width="673" alt="image" src="https://github.com/user-attachments/assets/53cb95f0-d009-43b1-8523-be82159bd6e9">

**Comment by gentius** [comment]
Oh wow, I didn't pay attention to that at all, I just went straight into a (comment) to test out code.

FWIW, I'm attaching how that file looks like before I try modifying it:

![grafik](https://github.com/user-attachments/assets/c7c75e0d-df68-44f7-9ba0-ac636789dd04)

Which is why I guess the only thing I was seeing in the REPL window was stderror, as "otherOutput" isn't correct and defaulted to the global settings for that.

After changing the outputDestinations there to "repl-window" it works as expected. 

Thanks!


P.S. Isn't the mini.playground a very common way for users to try out the extension initially though? What's the motivation to have the settings be so different from the defaults in that project?

**Comment by PEZ** [comment]
Oh, very odd that the file looks like that. Something must have gone wrong downloading it. This is what it should look like: https://github.com/BetterThanTomorrow/dram/blob/published/drams/v2/mini/.vscode/settings.json

To your question about why we use non-defaults in the mini-project. It is partly what's beeing stated in that file:

> ```jsonc
>   //// They are included here as a suggestion for a nice repl
>   //// workflow setup.
> ```
 
The repl window is not suited to handle a lot of output. It is causing troubles for users and us maintainers. That's why I created the terminal output, which handles this great. We are probably going to change the defaults at some point.

**Comment by gentius** [comment]
OK I'm closing this. I guess the fact that I was getting some outputs in the REPL window and some in the terminal is what made it unintuitive for me, as that meant the need to have 3 'panes' open to see everything, leaving very little room for the editor.

Unfortunately vscode doesn't seem to have a way to slot the terminal only to the bottom-right, as an example. Switching to this config as in the mini project could be workable if it supported that, as at least you'd still have a place to enter forms in the REPL directly and not in the editor. (since this terminal doesn't handle input)

**Comment by PEZ** [comment]
> Unfortunately vscode doesn't seem to have a way to slot the terminal only to the bottom-right

You can drag the individual terminals around to the editor part of the window. Giving you an arrangement like this: 

<img width="1565" alt="image" src="https://github.com/user-attachments/assets/319c97ea-8a4d-44a7-8d6b-d82de2b6d18d">

A drawback is that VS Code forgets about this arrangement between sessions, so you'd start with doing it manually. But if you don't restart the repl often, it is quite doable. I don't use the repl prompt much at all, but I do often throw the Output terminal into the editors area.
