### ISSUE TITLE
[Windows] Jack-in for shadow-cljs fails to start on Windows with "Error: spawn EINVAL" on the latest VS Code version

### ISSUE THREAD

**Issue by uds** [BetterThanTomorrow/calva#2616]
It seems like "npx.cmd shadow-cljs... " fails,  apparently it has something to do with recent nodejs security patch.

I've found a description of the similar behavior here: https://github.com/nodejs/node/issues/52554.
It says that the node version starting from 20.12.2 does not accept ".cmd" extension in spawn calls anymore.

Changing version of node in with e.g. nvm does not helps as apparently extensions are run on the node version bundled with the VS Code, which in turn is coming from the Electron that VS Code is bundled with.

Checking my VS Code electron version says it's 30.4.0, which is bundled with node version 2.15.1. 
That node version already contains the fix preventing it from starting the "npx.cmd".

According to https://github.com/nodejs/node/issues/52554#issuecomment-2060026269, there is a simple fix: 
specifying {shell: true} option in spawn should resolve the issue.

**Comment by PEZ** [comment]
Thanks for the report and for the work with researching! I can't try it right now, because no Windows machine handy. Though I can see here that we probably use `{shell: false}` for shadow-cljs Jack-in on Windows:

https://github.com/BetterThanTomorrow/calva/blob/dev/src/nrepl/project-types.ts#L405

Iirc, we are sometimes overriding that config, so it needs some further studying. If you have some time for it you are most welcome to investigate. The wiki has instructions for how to get Calva running in development mode. Otherwise I will have a look tomorrow.

**Comment by kevindragon** [comment]
I'm experiencing the same problem on Windows as well. 
node version: 20.17.0
Calva version used: v2.0.468
clojure-lsp version used: 2024.08.05-18.16.00
clj-kondo version used: 2024.08.01

![1725760509220](https://github.com/user-attachments/assets/8a61f4fb-176e-41e0-876e-c67719cc1930)

Having logs would be very helpful in debugging this issue. Perhaps we could try enabling additional logging to gather more information?

**Comment by PEZ** [comment]
We actually used to log a bit more here. I think we have by mistake disabled some logging. And we could definitely look into having a more verbose mode for trouble shooting.

**Comment by PEZ** [comment]
Can you try this build and see if it works better?
* https://output.circle-artifacts.com/output/job/9800c637-7c2a-4068-a083-115cc89555eb/artifacts/0/tmp/artifacts/calva-2.0.469-2616-shadow-cljs-windows-shellout-fb8c7e15.vsix

**Comment by kevindragon** [comment]
> Can you try this build and see if it works better?
> 
> * https://output.circle-artifacts.com/output/job/9800c637-7c2a-4068-a083-115cc89555eb/artifacts/0/tmp/artifacts/calva-2.0.469-2616-shadow-cljs-windows-shellout-fb8c7e15.vsix

Cool! it's working !!!

![1725981389255](https://github.com/user-attachments/assets/ebf16f99-94d7-422f-bb86-cdd38ff67393)
