### ISSUE TITLE
Can't start REPL in lein projects with backtick on project.clj

### ISSUE THREAD

**Issue by ericdallo** [BetterThanTomorrow/calva#2633]
Calva tries to parse project.clj as edn instead of clj, so it doesn't recognize the ` (backtick).

![image](https://github.com/user-attachments/assets/f4a6358d-6b30-43d7-b048-744d6be95d62)

[Repo project](https://github.com/ericdallo/clojure-sample/tree/calva-issue-parse-project)

[Thread with more context](https://clojurians.slack.com/archives/CBE668G4R/p1727187202992099)

Connecting via a remote repl works as a workaround although it's not that convenient

**Comment by PEZ** [comment]
Thanks for reporting! It could be as easy as using `read-string` instead of `clojure.edn/read-string`, but it also could be not that easy. I'll have a look. Unless you want to have a go at it, @ericdallo?

**Comment by ericdallo** [comment]
I have not much time, but I can try and let you know today

**Comment by PEZ** [comment]
Cool. Let's see who gets at it first. We can sync it a bit, I guess. 😄

**Comment by PEZ** [comment]
We also should make the process more fault tolerant. So connection is at least possible even if the project file parsing croaked.

**Comment by ericdallo** [comment]
I won't be able to take it quickly 🫠

**Comment by PEZ** [comment]
I'll have a look at it now. Will shoot any questions to you on Slack if I need support.
