### ISSUE TITLE
Unable to install because, the depending extension 'betterthantomorrow.calva' compatible with current version '1.26.1' of VS Code is not found.

### ISSUE THREAD

**Issue by ahmedmrefaat** [BetterThanTomorrow/calva#264]
Installing Calva via the Extensions tab in VS Code on Mac OS fails with a vague error message and when attempting an install from the [Marketplace](https://marketplace.visualstudio.com/items?itemName=betterthantomorrow.calva), I get the following error in Code: 

`Unable to install because, the depending extension 'betterthantomorrow.calva' compatible with current version '1.26.1' of VS Code is not found.`

I am on Mac OS Mojave (10.14.5) and VS Code 1.26.1

**Comment by PEZ** [comment]
Hello! Sorry for late reply.

Minimum VS Code is 1.30.0.
