### ISSUE TITLE
Autocomplete and see doc issues

### ISSUE THREAD

**Issue by mrkaspa** [BetterThanTomorrow/calva#265]
When you connect to a running repl the editor does no autocomplete nor show the doc of the funcionts, and when you start calva jack in from the editor it works on the code but not on the tests. Is there an special configuration that must be done for this?

**Comment by PEZ** [comment]
Hello, the reason it works better when you jack in, compared to when you connect to a running repl is that jack in makes sure the nrepl and cider dependencies are injected. That's what jack in is for. :smile: If you need to use connect instead, study the command that jack-in uses and use the same dependencies in your project file.

About why hover and things do not work in your tests. I am not sure what it could be about, but maybe you haven't loaded the file with the tests (`ctrl+alt+c enter`)?

**Comment by cfehse** [comment]
@PEZ @mrkaspa 

The completion/hover should work in version 2.0.49 for code and tests if the file containing the tests is loaded. I will close this issue for now.
