### ISSUE TITLE
Command 'replace-refer-all-with-refer' not found

### ISSUE THREAD

**Issue by RobWood8426** [BetterThanTomorrow/calva#2667]
When trying to run a particular Quick Fix action in calva I get the error message:
"Command 'replace-refer-all-with-refer' not found"

![Screenshot 2024-11-21 at 11 04 51](https://github.com/user-attachments/assets/209d6221-be74-4aeb-872a-c8fc9927f5fe)
![Screenshot 2024-11-21 at 11 30 12](https://github.com/user-attachments/assets/cce33f8c-f7c6-4493-ac93-1dd67dea5ef6)

**Comment by PEZ** [comment]
Thanks for reporting! As discussed on Clojurians Slack, I think this is that we are not registering this clojure-lsp command. There may be others missing as well.

**Comment by RobWood8426** [comment]
Perfect, I will take a stab at getting just this command running first, and then once that is going will look at finding all available commands from lsp.

**Comment by PEZ** [comment]
Thanks! I keep forgetting to reference the issue in the merge commit.
