### ISSUE TITLE
Calva Legacy is about to be removed - comment here with issues against it

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#267]
The four different Calva extensions on the marketplace are causing confusion. Therefore we have reached the point where Calva Legacy, Calva Paredit and Calva Formatter are about to be removed.

I think everything that worked with Calva Legacy now works with new Calva. However, there could be issues I am unaware of. If something stops you from upgrading, please say so in the comments to this issue. If I deem something as a blocker for removing I will first try to address it before I go ahead removing the legacy extensions.

Cheers!

**Comment by sergeiudris** [comment]
Hi @PEZ 

First, thank you for calva, it's lifechanging 

**Issue:**

When using new calva with cljs (shadow or lein-figwheel),
calling (prn 3) prints only to browser console, not to REPL pane. 
Pane correctly prints function returns, but not (prn ..)

Legacy calva (with same projects):
(prn 3) prints to editor REPL, not browser console.
js/console prints to browser

Use case:
REPL is most useful to be able to make requests and print results in editor. 
Async calls return promise or channel, so REPL pane always prints '[Promise ..]'

I've been searching for similar issues for a couple of days now, but haven't found any.
I hope I'm not imagining things.. )

**Comment by PEZ** [comment]
Hello, @sergeiudris, thanks for the feedback!

Can you file this as an issue of its own? I have noticed it myself, but thought it was out of my control to fix it. But since the legacy REPL does the right thing, we can probably look in the Leiningen course for how it's done there. (Legacy Calva uses `lein repl :connect` for its REPL.)

I see how this is inconvenient, but I lean towards going ahead removing Legacy Calva from the marketplace even with this inconvenience. Having it as an issue will remind me to have it fixed.
