### ISSUE TITLE
new calva cljs : printing to REPL pane

### ISSUE THREAD

**Issue by seeris** [BetterThanTomorrow/calva#272]
When using new calva with cljs (shadow or lein-figwheel),
calling (prn 3) prints only to browser console, not to REPL pane. 
Pane correctly prints function returns, but not (prn ..)

Legacy calva (with same projects):
(prn 3) prints to editor REPL, not browser console.
js/console prints to browser

Use case:
REPL is most useful to be able to make requests and print results in editor. 
Async calls return promise or channel, so REPL pane always prints '[Promise ..]'

_Originally posted by @sergeiudris in https://github.com/BetterThanTomorrow/calva/issues/267#issuecomment-517985718_

Can you file this as an issue of its own? I have noticed it myself, but thought it was out of my control to fix it. But since the legacy REPL does the right thing, we can probably look in the Leiningen course for how it's done there. (Legacy Calva uses `lein repl :connect` for its REPL.)

I see how this is inconvenient, but I lean towards going ahead removing Legacy Calva from the marketplace even with this inconvenience. Having it as an issue will remind me to have it fixed.

_Originally posted by @PEZ in https://github.com/BetterThanTomorrow/calva/issues/267#issuecomment-517991711_

**Comment by cfehse** [comment]
@seeris 

This should be working with version 2.0.49. Perhaps you can give it a try to test. I am closing this issue for now.

**Comment by seeris** [comment]
Did try it promptly, but  `prn` `println` still seem to output to js console..
Used Calva 2.0.49 with shadow-cljs 2.8.52. Maybe I missed some step. 
When the next opportunity comes, will test it more carefully and comment here if anything.

**Comment by PEZ** [comment]
Do you `(enable-console-print!)` anywhere in your app?

**Comment by seeris** [comment]
Yes i did.. :man_facepalming: 
Commented out `(enable-console-print!)` but still `prn` seems to log to console..
![Screenshot from 2019-10-14 08-32-34](https://user-images.githubusercontent.com/19359748/66731025-c53d2a00-ee5d-11e9-90e0-e7d6ca20b317.png)
Will come back to it when I can properly focus on it. I'm clearly not paying attention atm.

**Comment by PEZ** [comment]
I think it might be that you have an old shadow-cljs.
