### ISSUE TITLE
Jack-In when mutliple projects are in the workspace

### ISSUE THREAD

**Issue by kstehn** [BetterThanTomorrow/calva#273]
When i have multiple projects in my workspace and want to jack-in, it always picks the first project folder it finds with the project.clj file.

With the config: Project Root Directory it also doesn't work. 

For example: 
Workspace: 
- foo
- bar

I want to jack-in in bar open one clojure-file in bar and try to jack-in.
Result: jack-in processs starts in foo

When i change the Project Root Directory to bar/ it also jacks-in to foo.

Also i think its not really helpfull when you always need to change the config when you want to jack-in another project.

I guess the solution should be somewhere in the connect, because with the connect it always finds the right directory.

**Comment by PEZ** [comment]
I think the logic in `getProjectDir()` is faulty. And also it might need to be adapted to more specifically support this. More like the way we find the nrepl-port file. Start from the active editor file and search for project files from there and upwards. Maybe we can even remove the settings for this if we do it right.

**Comment by kstehn** [comment]
Resolved with the merge #275
