### ISSUE TITLE
[Question] Starting cljs repl within clj repl

### ISSUE THREAD

**Issue by mkarp** [BetterThanTomorrow/calva#276]
Hey there!

Several members of my team love using VS Code and would like to use Calva as their nREPL client.

Our setup needs to support several nREPL clients (currently it works with Atom's ProtoREPL, vim.fireplace, CIDER and Cursive), but I can't figure out how to make it work with Calva.

The way we do it:

1. We have a custom main function that starts an nREPL server and Figwheel.
1. After a client connects to the Clojure REPL via nREPL, user can evaluate `(cljs-repl)` and connect to Figwheel ClojureScript repl.

Here's a minimal project with a similar setup against which you can test Calva https://github.com/mkarp/cljs-nrepl-exercise.

This setup has a very nice feature that has increased our productivity significantly. We added an nREPL middleware that reloads our app after some code has been evaluated via nREPL. In a bigger app that reduces hot code reload times from a few seconds (with Figwheel's file watched) to a fraction of a second.

Please let me know what you think and if there anything we can do differently to make it work with Calva.

We're really excited that Calva got supported via Clojurists Together!

**Comment by PEZ** [comment]
Hello!

Thanks for this question and the example! We need to work a bit more with Calva Jack-in to support the setup. But you might get away with using a `customCljsRepl` setting and use the *Calva Connect to a Running REPL* command.

The setting looks like so, and should go in the `.vscode/settings.json` in the root directory of the project.

I sent a PR to the example project with this addition: https://github.com/mkarp/cljs-nrepl-exercise/pull/1

As I say in that PR, I am not sure this makes it all work. But at least it moves our pieces. 😊 

Thanks for those encouraging words about the CT funding! Part of it will go to documentation, and I should probably document this `customCljsRepl` setting...

**Comment by mkarp** [comment]
Resolved in https://github.com/mkarp/cljs-nrepl-exercise/pull/1

Thanks again @PEZ!
