### ISSUE TITLE
Honor main arguments for clj and Leiningen aliases

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#277]
As is evident from #276 and its [example project](https://github.com/mkarp/cljs-nrepl-exercise) Calva still has troubles jacking in to some not-all-that-crazy projects.

I think that what is lacking is that Calva insists on it's predefined main arguments, disregarding any such arguments specified in the alias (in the `clj` case), and not even offering to start with aliases (in the Leiningen case).

- [ ] `clj` (`deps.edn`)
- [ ] Leiningen

**Comment by kstehn** [comment]
Just a side note here. 
For clj it is already possible to select a alias, just checked it myself. :)

**Comment by PEZ** [comment]
We should improve on referencing the issues when committing fixes. :smile:
