### ISSUE TITLE
REPL ns prompt does not change with (ns ..) form

### ISSUE THREAD

**Issue by joinr** [BetterThanTomorrow/calva#280]
First time trying out calva.  I downloaded VSCode, and installed the latest version from the MarketPlace.  I have lein version 2.9.1, running on openJDK 1.8.222, windows 10.

Going from [this snake game repo](https://github.com/joinr/clj-snake), calva connects and I get the REPL.  From the repl, I enter `(require 'snake.main))` and get okay.  Switching namespaces at the repl via `(ns snake.main)` doesn't appear to work in the REPL prompt (still at user=>), but in fact we do switch to the namespace.

![image](https://user-images.githubusercontent.com/4629681/62973363-8b0ec800-bddb-11e9-990a-2a97fdfd62cf.png)

**Comment by PEZ** [comment]
Thanks for reporting this. Looks very confused and should be fixed. Putting it up on our todo.

**Comment by PEZ** [comment]
Fixed with #340.
