### ISSUE TITLE
command 'calva.jackIn' not found

### ISSUE THREAD

**Issue by xavi** [BetterThanTomorrow/calva#287]
I had Calva working before, but today when pressing ctrl+alt+c ctrl+alt+j in a .clj file I get

command 'calva.jackIn' not found

I tried uninstalling and reinstalling Calva and restarting the computer, but it didn't help.
I use Visual Studio Code 1.37.1 .

**Comment by Vuizur** [comment]
I have the same problem on Windows 10. The extension seems not to activate at all, there is nothing where the "nrepl: etc." text is usually located. It worked previously, so it is possibly the new update.

**Comment by PEZ** [comment]
I have the same problem.

I don't have the faintest idea what went wrong with the publishing of the extension. But I am republishing it now and am pretty sure it should work. Will take a few minutes before it is processed. Then `2.0.33` will appear. Please let me know if it still is not working!

**Comment by PEZ** [comment]
It is live now. Works when I test it. Totally sorry about the mess. Those publishing tools have never failed me before.

**Comment by Vuizur** [comment]
It works now. 👍 Thanks for the support!

**Comment by PEZ** [comment]
Glad to hear!
