### ISSUE TITLE
Paredit Barf direction not indicated in Keyboard Shortcuts

### ISSUE THREAD

**Issue by admiralbumblebee** [BetterThanTomorrow/calva#290]
Currently there appears to be two bindings for Barf: ctrl-← and ctrl-shift-→ 

Both of them are listed as simply "Barf Sexp". 

ctrl-← is Forward Barf (pulling the nearest-to-the-right paren leftwards by one sexp)

ctrl-shift-→ Backwards Barf (pulling the nearest-to-the-left paren rightwards by one sexp)

They should be labelled as their Forwards/Backwards variants like Slurp is.

**Comment by PEZ** [comment]
Thanks. Will fix!

**Comment by PEZ** [comment]
Sorry, forgot about this. But now at least it is fixed on `dev`.
