### ISSUE TITLE
':main-opts ["-m" "nrepl.cmdline"]' breaks intellisense in :nrepl alias

### ISSUE THREAD

**Issue by sauvala** [BetterThanTomorrow/calva#293]
Intellisense and code navigation breaks when I try to start project REPL (Jack-In) by having `:main-opts ["-m" "nrepl.cmdline"]` and starting REPL using that alias. I cannot navigate through the code or see function descriptions by hovering over them.

Example alias:
```
:nrepl {:extra-deps {nrepl {:mvn/version "RELEASE"}}
            :main-opts ["-m" "nrepl.cmdline"]}
```

**Comment by PEZ** [comment]
Hello,

I think this is because Calva, when it sees that `:main-opts` are provided with the alias, does not provide its default main-opts. So then the cider-middleware is not injected. Try adding that with the alias. Like so:

```clojure
:nrepl {:extra-deps {nrepl {:mvn/version "RELEASE"}}
        :main-opts ["-m" "nrepl.cmdline" "--middleware" "[cider.nrepl/cider-middleware]"]}
```

**Comment by sauvala** [comment]
You were right, adding the middleware fixed intellisense and navigation! 🎉 Thanks @PEZ
