### ISSUE TITLE
is there an example repo to try Calva with Figwheel-Main?

### ISSUE THREAD

**Issue by seeris** [BetterThanTomorrow/calva#296]
could you please point me in the right direction: i've been successfully using calva with old figwheel, but cannot connect to figwheel-main.. (have no problems connecting to shadow-cljs ).

i've been failing for a while now. what i do: select 'Figwheel Main' and specify localhost:port (e.g. 9500).

anyway, the question: is there a demo repo (maybe https://github.com/PEZ/fresh-figwheel-main) that i can try with calva and figwheel-main ? what host:port should i type in ?

**Comment by seeris** [comment]
resolved, with the help of  PEZ:

> @seeris: I recommend using Jack in instead of connect.  So, open a file in your project, then run the command “Calva: Start a Project REPL and connect (aka Jack-in)“. 
Or click the nREPL button in the status bar and choose that command.

if anyone is still failing to connect:

1. clone https://github.com/PEZ/fresh-figwheel-main
2. open project in vscode
3. open fresh_figwheel_main/core.cljs file
4. click nREPL, select 'Start a REPL server...'
5. select fig build
6. select dev build (maybe twice)

the calva REPL pane will open

**Comment by PEZ** [comment]
Great that you got it working!

That `fresh-figwheel-main` project is created straight from the `figwheel-main-template`, FYI.

**Comment by baflo** [comment]
> 
> 
> resolved, with the help of PEZ:
> 
> > @seeris: I recommend using Jack in instead of connect.  So, open a file in your project, then run the command “Calva: Start a Project REPL and connect (aka Jack-in)“.
> > Or click the nREPL button in the status bar and choose that command.
> 
> if anyone is still failing to connect:
> 
>     1. clone https://github.com/PEZ/fresh-figwheel-main
> 
>     2. open project in vscode
> 
>     3. open fresh_figwheel_main/core.cljs file
> 
>     4. click nREPL, select 'Start a REPL server...'
> 
>     5. select fig build
> 
>     6. select dev build (maybe twice)
> 
> 
> the calva REPL pane will open
> 
> or if yo're using a docker container:
> use https://github.com/bhauman/figwheel-main-template with `+deps`
> 
> start with
> 
> ```shell
>  clojure \
>     -Sdeps '{:deps {nrepl {:mvn/version "0.6.0"} cider/cider-nrepl {:mvn/version "0.21.1"} cider/piggieback {:mvn/version "0.4.1"} figwheel-sidecar {:mvn/version "0.5.18"}}}' \
>     -A:fig -m nrepl.cmdline  --middleware "[cider.nrepl/cider-middleware cider.piggieback/wrap-cljs-repl]" --bind "0.0.0.0" --port 7888
> ```
> 
> expose ports
> `EXPOSE 7888 9500`
> 
> connect from calva ( ctrl+alt+c ctrl+alt+c)

If I understand this correctly, to use both `fig` and `dev` build in a vscode container, I should first call the command `clojure -Sdeps ... -A:fig:build -m nrepl.cmdline ...` and then connect in the project?

I tried to put this in another build config, but as I understood from the [`Clojure CLI doc`](https://clojure.org/reference/deps_and_cli#_usage), the `-Sdeps` option set the *exact* dependencies vector, while the build option `:extra-deps` augments the deps... moreover, I wasn't able to pass the options after `-m nrepl.cmdline`.

Do you have suggestions?

**Comment by seeris** [comment]
@baflo 

- as a sanity check created this repo https://github.com/seeris/tmp.figwheelmain-calva-docker
- all the details are in README
- please tag me if it does not or is unclear

**Comment by baflo** [comment]
*Awesome!* Thank you very much for the quick support! I adapter your suggestion for my setup, such that I just have an npm script: 

```json
    "nrepl:fig": "clojure -Sdeps '{:deps {nrepl {:mvn/version \"0.6.0\"} cider/cider-nrepl {:mvn/version \"0.21.1\"} cider/piggieback {:mvn/version \"0.4.1\"} figwheel-sidecar {:mvn/version \"0.5.18\"}}}' -A:fig -m nrepl.cmdline  --middleware \"[cider.nrepl/cider-middleware cider.piggieback/wrap-cljs-repl]\" --bind \"0.0.0.0\" --port 7888"
```

I start that script from within the container then `connect from calva ( ctrl+alt+c ctrl+alt+c)`, which just works as fine and I can still forward the ports to the host.

**Comment by baflo** [comment]
Just for completness, here's my example: https://github.com/baflo/cljs-examples
