### ISSUE TITLE
Calva selection commands do not trigger VISUAL mode of the VIM plugin

### ISSUE THREAD

**Issue by Tebro** [BetterThanTomorrow/calva#297]
If you use the "Calva Paredit: Expand selection", "Select current form" or similar commands while also using the VSCode VIM plugin, it will not trigger VISUAL mode as a user might expect.

**Comment by PEZ** [comment]
Thanks! This looks to be something for the VIM Extension to solve. https://github.com/VSCodeVim/Vim/issues/2224

I'll keep this issue open for now, so that VIM:ers using Calva can easier find out about this limitation.

**Comment by dijonkitchen** [comment]
If that's really the case, I guess this issue can really be closed since it'll still be searchable.

**Comment by bpringe** [comment]
Closing, in agreement with the above comment.
