### ISSUE TITLE
Should provide option to make repl tabs open in current pane

### ISSUE THREAD

**Issue by mattly** [BetterThanTomorrow/calva#300]
It's kind of annoying that Calva will create a split if I don't already have one, in order to display the repl pane. I prefer using narrow windows and splits get in the way of that. For my workflow with shadow-cljs, it's even more annoying, because it opens two panes.

Calva should at least provide an option to specify the repl tabs open in the current split instead of creating one, if not make that behavior default.

**Comment by PEZ** [comment]
Yes, this should be improved a bit. I'm not sure what the APIs allow, but at least an option to open in column two or in current pane should be possible.
