### ISSUE TITLE
Are Cider Repl commands supported in calva repl?

### ISSUE THREAD

**Issue by erkinun** [BetterThanTomorrow/calva#301]
I'm trying to try out calva for Clojure development. I couldn't figure out a way to use emacs keybindings and previous/next commands in the repl it provides. Pressing `enter` does not evaluate the input but adds an actual new line to it. Is there a way to customise it?

**Comment by PEZ** [comment]
Hi, happy that you are trying out Calva!

Generally, see this for getting keybindings more emacsy: https://github.com/BetterThanTomorrow/calva/wiki/Keybindings-for-Emacs-users

Some of those translate over to the REPL window as well, but not all. And the beaviour of pressing enter in the REPL window is not configurable yet. Use `alt+enter` to submit the current form, regardless of where the cursor is on the line.
