### ISSUE TITLE
REPL colours and logo get too much attention

### ISSUE THREAD

**Issue by kwladyka** [BetterThanTomorrow/calva#303]
![image](https://user-images.githubusercontent.com/3903726/64487180-573a8d00-d237-11e9-8606-e7901df54699.png)
While it can sounds stupid I stare on logos. This elements are very disrupting and get too much of my attention. Comparing to code colours it is much more interesting for my brain :)
![image](https://user-images.githubusercontent.com/3903726/64487192-8cdf7600-d237-11e9-9789-27c9578be71a.png)

Solution: hide it and start with clean REPL? This information could show instead in console when start REPL? Not sure if it is possible.

Edited:
The best if it can have the same syntax highlight like in code. I found myself even `user=>` is too light comparing to whole window and all code.

**Comment by emaphis** [comment]
I would guess that this is to show off the advanced graphical abilities of the new REPL.

**Comment by RomanTsopin** [comment]
Another proposal – it should be possible to clean intro with <cmd> + L
