### ISSUE TITLE
Calva leaves running java.exe processes on Windows when closing VS Studio

### ISSUE THREAD

**Issue by cfehse** [BetterThanTomorrow/calva#305]
When you open a clojure project and Jack-in a repl for lets say a leiningen project the extension starts 2 java.exe processes. If you close VS code one process is left running. 

The output windows states:
Jack-in done.
Use the VS Code task management UI to control the life cycle of the Jack-in task.

If I therefore terminate the running task using Terminal->Terminate Task... (which ends one of the 2 processes) and terminate VS code afterwards there is one leftover process as well.
This running process seems to be a running repl . If you start VS code again an choose "Connect to a running repl server" the connection is established an the repl window works as expected. In this state there is no running task to terminate and if you close VS code again the java.exe process is still running.  So for each time starting VS code jack-in a repl an terminating VS code one additional process is left running.

I just noticed this behavior because I tried to figure out how the extension and VS code works and therefore restarted VS code quite some times which leaves an unusual number of java processes in the task manager.

**Comment by PEZ** [comment]
Hello, thanks for pointing this out. It should be mentioned in the documentation. It is a VS Code + Windows issue, but still people should be aware of it.

**Comment by cfehse** [comment]
Okay - and a bunch of conhost.exe processes are left over as well.

**Comment by PEZ** [comment]
@kstehn: Do you think using Task provider properly would have a chance to fix this?

**Comment by kstehn** [comment]
Not sure it might.
Dont know how difficult it would be to do it right.

The two java processes are normal. 
One is the leiningen-repl itself and the other is the project that gets started by leiningen.

**Comment by PEZ** [comment]
Thing is that on Linux and Mac VS Code brings down the processes on reload and exit. But we know that we are using the Task a bit too loose for the VS Code devs' taste. And just maybe if we did it through a Task provider vscode would do the right thing on Windows as well. But, we should do it though a task provider anyway, of course.

**Comment by cfehse** [comment]
The nREPL protocol itself seems not to support a termination of the server initiated by a client. A  workaround for this is to simply call "(System/exit 0)" from the repl window (mentioned here https://github.com/clojure-emacs/cider/issues/390).
Perhaps something similar can be included into the termination code of the extension to terminate the repl processes in case the extension started the repl by itself and was not connected to a running instance.

**Comment by cfehse** [comment]
@PEZ: My changes for this didn't make to version 2.0.37 right? So I use my local build based on your merged dev branch until it's coming up from the marketplace. Thanks for merging!

**Comment by PEZ** [comment]
That's right. I have messed up my branches because of low git fu, so cut the release just before your fix. Will try to fix today, but might be tomorrow.

**Comment by cfehse** [comment]
@PEZ No worries! Take your time - it's weekend. *gg,

**Comment by PEZ** [comment]
Should be fixed now. Close issue if you agree. :smile:
