### ISSUE TITLE
Documentation of important keyboard shortcuts is partially wrong

### ISSUE THREAD

**Issue by cfehse** [BetterThanTomorrow/calva#306]
While trying to figure out the best workflow with the extension I could not get some of the important keyboard shortcuts to work. I was following the documentation (mainly project README,md section "More in depth (and some usage info)" and the wiki page "Commands the Top 10"). The information in both places is consistent but unfortunately outdated or wrong. Especially for the bindings sending commands to the repl windows the second cord is not alt+<key> but ctrl+alt+<key>

Examples:
- "Send the current top level form to the REPL terminal" ctrl+alt+c ctrl+alt+space
- "Load current namespace in the REPL window" ctrl+alt+c ctrl+alt+n 
- "Evaluate code from the editor to the REPL window" ctrl+alt+c ctrl+alt+e

**Comment by PEZ** [comment]
Good catch! Please feel invited to fix. :smile:

**Comment by cfehse** [comment]
How can I do it? I'll do it. *gg*

**Comment by PEZ** [comment]
Nice! The wiki is editable.

And the `README.md` should be possible to edit with the Github UI as well. But of course, more for to do it this way: https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute

**Comment by cfehse** [comment]
I changed the affected wiki pages and created pull request for the affected files in the source tree. 
In the wiki page "Keybinding conflicts" (https://github.com/BetterThanTomorrow/calva/wiki/Keybinding-conflicts) the example shown seems no longer relevant because the key binding for "Send the current form (or selection) to REPL and evaluate it" is already `ctrl+alt+c ctrl+alt+e`. I didn't changes the page though.

**Comment by PEZ** [comment]
Thanks for sportting all this and helping to fix! I deleted that Keybindings-conflict page now, since I have solved it by changing the default keybindings (and then been sloppy with updating the docs... :smile:)
