### ISSUE TITLE
Feature Request: Output window should scroll to the bottom on new output 

### ISSUE THREAD

**Issue by cfehse** [BetterThanTomorrow/calva#309]
I think it would be nice if the output window would scroll to the bottom on new output like the repl window is doing. The windows version does not behave that way.

**Comment by PEZ** [comment]
It's the vscode output lock that is a bit too eager. Unlock it:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/30010/64609458-4885de80-d3cd-11e9-9554-9287f7cbd559.png">

**Comment by cfehse** [comment]
Cool - did it. Did You notice that I am an absolute beginner with vscode?
Thanks!
