### ISSUE TITLE
Feature request: shortcut for calling zero-arg functions

### ISSUE THREAD

**Issue by AlexVPopov** [BetterThanTomorrow/calva#310]
It would be nice, if there is a shortcut, which could automatically "call" a form by surrounding it with braces and evaluating it. Example - given the following function:

```
(defn foo [] "bar")
```

instead of having to write `(foo)` on a new line and evaluating it, the shortcut would produce the result, as if I had written this:

```
((defn foo [] "bar"))
```

The main usecase for this is calling tests, defined with `deftest` via a shortcut.

**Comment by PEZ** [comment]
> The main usecase for this is calling tests, defined with deftest via a shortcut.

There is **Run current test**, <kbd>ctrl</kbd><kbd>alt</kbd><kbd>c</kbd>, <kbd>ctrl</kbd><kbd>alt</kbd><kbd>t</kbd>, for that, right?

**Comment by AlexVPopov** [comment]
Agree 👍
