### ISSUE TITLE
CLJS Tests show in console when configured, but Calva reports 0 tests found.

### ISSUE THREAD

**Issue by gerred** [BetterThanTomorrow/calva#311]
Given the following test:

```clojure
(ns demo.other-test
  (:require [cljs.test :refer [deftest is run-tests]]))

(enable-console-print!)
(deftest a-failing-test
  (is (= 1 2)))
```

Located at `src/tests/app_test.cljs`

Running the individual test reports this output:

```
Evaluating file: /Users/gerred/dev/learn-re-frame-course-files/cheffy/src/tests/app_test.cljs
=> nil
Running test: a-failing-test…

No tests found. 😱, ns: 0, vars: 0
```

However, it does show up in my browser's console, which is what I'd expect (since `(enable-console-print!)` sets the reader to js/console.log)

**Comment by PEZ** [comment]
This is due to that `cider-nrepl` doesn't yet support running cljs tests. Something that might not be fixed all that soon. https://github.com/clojure-emacs/cider-nrepl/issues/555

I've added information about this limitation to the README. Don't know if we should keep this issue open. Maybe close and open it again when there is something happening in the tooling to support this?

**Comment by PEZ** [comment]
Here's a possible route we can take: https://github.com/clojure-emacs/cider-nrepl/issues/555#issuecomment-532113098

@gerred , @kstehn

**Comment by gerred** [comment]
That makes sense. I'll have to try out that runner to get this working in CI anyway. Thanks!

**Comment by PEZ** [comment]
Is cheffy a shadow-cljs project? If so, just switching `:autorun` on for the `test` build might suffice? That's what I do with Calva, where I have this:

```clojure
                :test
                {:target    :node-test
                 :output-to "cljs-out/test/cljs-lib-tests.js"
                 :ns-regexp "-test$"
                 :autorun   true}```

**Comment by PEZ** [comment]
Doesn't help with the *Run current test* case, of course, but running all tests on save is similar if all other tests are passing, anyway :smile:.

**Comment by gerred** [comment]
For sure. :) Yeah, Cheffy's a shadow-cljs project while I was messing around with the learn re-frame materials.

**Comment by kstehn** [comment]
But for this route i see it more like a new extension.
It can be in calva, but i dont know how much work it is to implement the usage of it.

Despite my not knowing, i think this would be a good route to take. 
A full test-runner might be a good choice :)

**Comment by PEZ** [comment]
I might be wrong about cider-nrepl not supporting this... Just tried it in a lein-figwheel project of mine, and there the tests run just fine.

**Comment by filipesilva** [comment]
I did some testing of various ways of running tests with a Calva and Shadow CLJS setup here: https://github.com/filipesilva/calva-testing

**Comment by bpringe** [comment]
Going to close this since we've documented that cider-nrepl (and therefore our test runner), only work with Clojure, and anyone interested in cljs testing with Calva can find this issue for alternate methods.
