### ISSUE TITLE
With shadow-cljs, output from code evaluations don't show up in Calva

### ISSUE THREAD

**Issue by aeberts** [BetterThanTomorrow/calva#320]
**Summary:**

In a `lein + shadow-cljs` project (and probably a "pure" `shadow-cljs` project as well) the output from the `Send Current Form to REPL` does not appear in the REPL window (but it does appear in the browser's dev tools console widow).

**Config:**
- MacOS 10.13.6
- VSCode: 1.3.81
- Calva: v2.0.38
- `lein --version`: `Leiningen 2.9.1 on Java 1.8.0_212 OpenJDK 64-Bit Server VM`
- shadow-cljs: `shadow-cljs@2.8.52`

**Reproduction Steps:**

- Download and install Calva v2.0.38
- Verify new version installed correctly with Extensions -> Calva "gear" icon -> "Copy Extension Information"
- Open lein + shadow-cljs project in VSCode (e.g. `lein new re-frame projectname`)
- Issue command `Calva: Start a Project REPL and Connect` and choose `Leiningen + shadow-cljs` as the project type.
- Verify that lein task is running in VSC Terminal -> success; code compiles
- Open browser and visit development server url -> success; application loads sucessfully.
- Open browser dev tools to check shadow-cljs status -> WebSocket connected and Repl started.
- Return to VSC and verify that Calva REPL window opens -> success
- Open CLJS file in project and issue `Load current namespace in REPL Window` -> success; REPL window shows current namespace.
- Evaluate `Send current form to REPL` -> command is executed but output does not appear in the Calva REPL window. REPL window output: `nil`. Output does appear in browser's dev tools window.

**Expected Result:**
- Output from the form called by `Send current form to REPL` appears in the Calva REPL window.

**Actual Result:**
- The output does not appear in the REPL window. `nil` appears instead. The output is displayed in the browser's REPL window.

**Notes:**
- As @PEZ noted on the slack channel (https://clojurians.slack.com/archives/CBE668G4R/p1568393311347700)

"The output issue is because shadow-cljs sends output out of band, and Calva expects it to come along with the evaluation results"

**Comment by PEZ** [comment]
This is fixed in shadow-cljs `2.8.53`.

**Comment by aeberts** [comment]
@PEZ 👏 I will have some time to test this evening and will get back to you with comments (if any).
