### ISSUE TITLE
Content `print`ed to REPL is interpreted as HTML

### ISSUE THREAD

**Issue by rigdern** [BetterThanTomorrow/calva#321]
For example, evaluate `(print "hello <b>world</b>")` in the REPL.

**Expected output**: hello &lt;b&gt;world&lt;/b&gt;

**Actual output**: hello **world**

![image](https://user-images.githubusercontent.com/199935/64926196-9a54ad00-d7af-11e9-8893-78b0985d853c.png)

## Environment

- VS Code Version: 1.38.0
- Calva Version: 2.0.38

**Comment by PEZ** [comment]
Wow. That should be fixed!
