### ISSUE TITLE
Warning: "cider-nrep requires Leiningen 2.8.3 or greater" when starting Lein + shadow-cljs project

### ISSUE THREAD

**Issue by aeberts** [BetterThanTomorrow/calva#324]
**Summary:**
When starting a hybrid `Leiningen + shadow-cljs` project (e.g. via `lein new re-frame projectname`), the warning `cider-nrepl requires Leiningen 2.8.3 or greater` appears in the terminal even though Leiningen 2.9.1 is installed. The project appears to compile correctly despite this warning. 

**Config:**
- MacOS 10.13.6
- VSCode: 1.3.81
- Calva: v2.0.38
- `lein --version` : `Leiningen 2.9.1 on Java 1.8.0_212 OpenJDK 64-Bit Server VM`
- `shadow-cljs` : `shadow-cljs@2.8.52`

**Reproduction Steps:**
- Download and install Calva v2.0.38
- Verify new version installed correctly with Extensions -> Calva "gear" icon -> "Copy Extension Information"
- Open lein + shadow-cljs project in VSCode (e.g. `lein new re-frame projectname`)
- Issue command Calva: Start a Project REPL and Connect and choose Leiningen + shadow-cljs as the project type.
- Result -> project compiles but spurious warning appears in terminal during compilation:

```
 Executing task: lein update-in :dependencies conj '[nrepl"0.6.0"]' -- update-in :dependencies conj '[cider/piggieback"0.4.1"]' -- update-in :dependencies conj '[cider/cider-nrepl"0.22.1"]' -- update-in :plugins conj '[cider/cider-nrepl"0.22.1"]' -- update-in '[:repl-options :nrepl-middleware]' conj '["cider.nrepl/cider-middleware"]' -- update-in '[:repl-options :nrepl-middleware]' conj '["cider.piggieback/wrap-cljs-repl"]' -- dev <

Warning: cider-nrepl requires Leiningen 2.8.3 or greater.
Warning: cider-nrepl will not be included in your project.
Warning: cider-nrepl requires Leiningen 2.8.3 or greater.
Warning: cider-nrepl will not be included in your project.
Warning: cider-nrepl requires Leiningen 2.8.3 or greater.
Warning: cider-nrepl will not be included in your project.
Warning: cider-nrepl requires Leiningen 2.8.3 or greater.
Warning: cider-nrepl will not be included in your project.
shadow-cljs - HTTP server available at http://localhost:8280
shadow-cljs - server version: 2.8.52 running at http://localhost:9630
shadow-cljs - nREPL server started on port 8777
shadow-cljs - watching build :app
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (595 files, 1 compiled, 0 warnings, 7.30s)
```
**Expected Result:**
- Project compiles without warnings

**Actual Result:** 
- Warnings appear in VSC terminal 

**Notes:**
- This may be a configuration issue on my machine. Submitting this issue as a placeholder to record notes and findings as I investigate this issue further.
- Relevant discussion on Slack: https://clojurians.slack.com/archives/CBE668G4R/p1568393311347700
- The source of the warning appears to be `cider-nrepl` : https://github.com/clojure-emacs/cider-nrepl/blob/64694d98e15a48ffd294b0902d90bba5966b21c1/src/cider_nrepl/plugin.clj#L47
- Launching the project with `lein dev` from the mac command line does not cause the warning to appear.
- I have verified that there is no `~/.lein/profile.clj` file injecting deps into the project.
- `cider-nrepl` uses `leiningen.core.mail/version-satisfies?` for the Leiningen version check which I believe is the source of the error. It's unclear why `version-satisfies?` is reporting a different version than the Leiningen binary that is installed via brew.

**Comment by PEZ** [comment]
Can this be closed?

**Comment by aeberts** [comment]
I have installed Calva 2.0.40 and I'm still getting the issue on my Mac. If no one else is reporting it then it's quite possibly some local config issue. I haven't figured out the cause yet but please feel free to close it if you feel it's not a bug.

**Comment by PEZ** [comment]
Let's leave it open a while. Maybe someone else finds it easier then and can help or provide more information or something.

**Comment by bpringe** [comment]
Closing since it's been quite some time with no new reports.
