### ISSUE TITLE
Make pretty print a mode, removing the need for doubling the evaluation commands

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#327]
I believe pretty printing should happen by default when things are evaluated in the REPL window, including when forms are sent from the editor (send top-level, send current).

This should probably be included as a setting that is turned on by default, so users can turn off pretty printing if they would like to.

**Comment by PEZ** [comment]
From offline talk about this: Let's make it an easy to use toggle. Probably even a status bar button.

**Comment by bpringe** [comment]
Had this on my todo list 😉 - should have mentioned before.

**Comment by PEZ** [comment]
Not sure why this did not autoclose? Maybe you didn't include the ”fixes” message in a commit message?

Anyway. Now released!

**Comment by bpringe** [comment]
Weird! The docs say "resolves" works as well, and the PR shows it should have closed it.
![image](https://user-images.githubusercontent.com/12722744/65819386-b1909300-e1d0-11e9-9706-567502fca2cd.png) 
Anyway, thanks for the release!
