### ISSUE TITLE
Connect to nrepl by URL 

### ISSUE THREAD

**Issue by RomanTsopin** [BetterThanTomorrow/calva#328]
There was a handy option in the previous version of Calva to connect to any nrepl by url without creating a project folder first. It was especially cool for lein try plugin to pull any dependency and start messing with it. Seems like it’s not working now.

**Comment by PEZ** [comment]
Hello. This was a casualty in the work with bringing Jack-in and Connect into projects to a better position. I didn't think about this use case at all when we did that work...

I think it would be great if we make Calva support this again. I'll have a look at how difficult it would be to bring it back. (I don't think it should be that much trouble.)

**Comment by PEZ** [comment]
@RomanTsopin , we have now added a separate command to connect to a non-project REPL, can you try this VSIX package out, and see that ut fixes the problem? 

https://343-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.40-wip-connect-non-project-repl-49d232f0.vsix

**Comment by RomanTsopin** [comment]
Thanks, works perfect!
Would be nice to have this option on the bottom nREPL icon. And if you ask me – disconnect (sometimes connection hangs) and restart (after deps are changed) commands too :) At least in command palette.

**Comment by PEZ** [comment]
This command should be added to the nREPL icon... As for what more should be there, chip in on this PR: https://github.com/BetterThanTomorrow/calva/pull/333

**Comment by PEZ** [comment]
This is now released.
