### ISSUE TITLE
[Feature] Enhancement REPL window handling / nREPL menu button 

### ISSUE THREAD

**Issue by cfehse** [BetterThanTomorrow/calva#337]
**Motivation**
Inspired from the conversation about the usage of the REPL window for experienced users in issue #326, #325  the intention is to enhance the REPL window handling and the "nREPL" menu. There are commands to open the different REPL windows but for inexperienced users like me it may be difficult to find - in fact at the beginning I closed the REPl accidentally and did not find a quick way do get it back. There are in fact 2 commands and you have to now the right type of REPL window to open. Choosing the wrong type leads to a strange error message telling of some undefined object.

**Implementation Proposal**
Bundling all nREPL related commands into the nREPL command selection (pressing the "nREPL" button in the status bar). Depending on the state of the extension different commands will be included in the selection. A new disconnect command was added to provide a quick way to terminate the current REPL session. Meaningful error messages were added in case a command could not be executed.

**Comment by PEZ** [comment]
This has been fixed with v2.0.40, right?
