### ISSUE TITLE
[Feature] Command for switching back and forth between the REPL window and editor

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#339]
Slightly related to #337 

I'd like a command that allows for switching back and forth between the editor and the REPL window. Like so:
* If I am editing a file, the command will
  1. Open the REPL Window.
  2. Switch it to the namespace of the file.
  3. Give it focus.
* If the REPL window has focus, the command will:
  1. Open the file corresponding to the current namespace of the REPL window.
  2. Give it focus.

Clojure files should open the CLJ REPL Window. ClojureScript files should open the CLJS REPL Window. CLJC files should open whatever REPL window corresponds to the current mode backing the file.

It might need to be implemented using several commands with the same keyboard shortcut and intelligent `enablement` and `when` clauses.

**Comment by cfehse** [comment]
@PEZ Now I understand what you mean. *gg*

**Comment by slipset** [comment]
`C-c C-z` in Cider, FFIW

**Comment by nima-flipp** [comment]
Can't believe this hasn't been implemented... Do you guys click back and forth between REPL and Editor with a mouse?

**Comment by bpringe** [comment]
@CasualGitEnjoyer Speaking for myself, I very rarely type in the repl/output window. Most of my repl workflow happens from the editor.

However, this can actually be achieved at least somewhat by using the command for opening the repl window (which focuses it), and using the Go Back command to go back to the last editor.

**Comment by PEZ** [comment]
This is actually mostly implemented since long. Bound to `ctrl+alt+o o` by default. But VS Code's API makes it impossible to implement the reverse (from REPL window to the file) in a very nice way (very often we just open a new editor with the file instead).
