### ISSUE TITLE
[REPL Window] Add content security policy to webview and remove image load error

### ISSUE THREAD

**Issue by cfehse** [BetterThanTomorrow/calva#341]
- Add a content security policy to the HTML of the REPL windows  webview as advised by vscode (https://github.com/microsoft/vscode/issues/79248)
![calva-webview-content-policy-warning](https://user-images.githubusercontent.com/55053134/65481188-bd105100-de94-11e9-8144-f3744d871eaa.png)

- Remove image load error at runtime.
![calva-webview-image-load-error](https://user-images.githubusercontent.com/55053134/65481206-cc8f9a00-de94-11e9-9732-70840e40e1c5.png)

**Comment by PEZ** [comment]
This was fixed, right?
