### ISSUE TITLE
IntelliSense for requiring macros not showing

### ISSUE THREAD

**Issue by WhoNeedszZz** [BetterThanTomorrow/calva#35]
Macros are not shown in the IntelliSense list when attempting to `require` a macro. Behavior is working as expected for functions.

Example:
`(require [compojure.core :refer [defrou...]])` should show `defroutes` as an option, but doesn't.

**Comment by PEZ** [comment]
While I agree that it should, this is a rather tricky thing to solve. Closing it for now, and will reconsider if demand for it piles up.
