### ISSUE TITLE
Evaluate current top level form inline and print to output behaves differently depending on how it's invoked

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#355]
Let me first say my setting for "Send async output to" is set to "REPL Window."

1. If I run the command with the hotkeys (ctrl+alt+c, space) the output goes to the REPL window and I get no inline annotation.
2. If I run the command from the command selection menu, the output goes to "Calva says" and not the REPL window, and I also get an inline annotation.

Situation 2 is the same behavior I get when I run "Evaluate current form/selection inline and print to output." In any case, should the output go to the REPL window since I have that set for the "Send async output to" setting? Or is that _just_ for async output?

Besides my last question, it seems as though somehow the two commands are crossed.

**Comment by PEZ** [comment]
> Or is that just for async output?

Yes.

As for 1. You seem to have rebound the default shortcut. Maybe you have that bound to the command for sending the form to the REPL window? Calva does not show the results inline when this command is used. (Which, thinking about it, I might like to change, but anyway.)

**Comment by bpringe** [comment]
I may not have been clear, and I had a typo in my first post with the hotkeys, sorry. Let me try to restate the issue.

All of my keyboard shortcuts for Calva are set to default, I haven't changed any. Let's ignore keyboard shortcuts. When selected from the command menu, both of these commands do the *exact same thing*.

![image](https://user-images.githubusercontent.com/12722744/65820431-ad1ea700-e1dd-11e9-8705-7f69206a1f7b.png)

**Comment by PEZ** [comment]
I can't reproduce this. Does it matter where the cursor is when you issue the commands?

**Comment by bpringe** [comment]
I made to to uninstall and reinstall this time, and verified that no previous Calva folder was left in ~/.vscode/extensions. Here is what I'm seeing.

![calva-commands-2](https://user-images.githubusercontent.com/12722744/65891957-4a064f00-e35a-11e9-933c-dca363644278.gif)

**Comment by PEZ** [comment]
This would be correct behaviour if the containing form is a `comment`. Is it?

**Comment by bpringe** [comment]
Hmm I don't understand why the two different commands should do the same thing if the containing form is a comment (it is here).

Here's another perspective. If I run the command from the menu for `ctrl+alt+c, space` it behaves differently than if I use the shortcut keys. See below.

![calva-commands-3](https://user-images.githubusercontent.com/12722744/65924368-3f22dd00-e3a1-11e9-9769-7bb77405361f.gif)

**Comment by PEZ** [comment]
Two things are in play here:

1. The current form happens to be a top level form. Move the cursor inside the form and you should see the difference between the two commands.
1. In order to promote in-file REPL experiments, Calva treats the comment form as creating a new top level context. So all forms at the first level inside a comment form are considered top level.

That last issue I don't know what to make of. It certainly does not behave like that for me. `ctrl+alt+c space` evaluates top level form inline, and `ctrl+alt+c ctrl+alt+space` evaluates the same form in the REPL window.

**Comment by bpringe** [comment]
I think I must have been confusing multiple commands. I do get that the two commands should do the same thing with the cursor at that position because current and top level are the same there. I think I was hitting `ctrl+alt+c ctrl+alt+space` and thinking I was hitting `ctrl+alt+c space` - that was the confusion! Sorry for using up your time for this >_<. Closing

**Comment by PEZ** [comment]
No problem. You are highlighting areas where we need to be much clearer in how we communicate.
