### ISSUE TITLE
Warnings/Errors should be made more "prominent" in the "Calva says" channel

### ISSUE THREAD

**Issue by cfehse** [BetterThanTomorrow/calva#356]
When for example a connection problem occurs (let's say "port already in use" or some that like) a normal warning is made to the "Calva says" channel mention to look to the "Calva Connection Log" for more information. This warning can easily be overseen. I happened to me more than once that I did not pay attention to the warning and could not find the cause of the problem quickly. 

Perhaps warning and error message to the "Calva says" channel can be mode in a different color or otherwise be emphasized.

**Comment by PEZ** [comment]
I don't think the output supports color or styling, yet?

I think we should `showErrorMessage` for these situations. Maybe add a button for opening the log.

**Comment by cfehse** [comment]
@PEZ 

>I think we should showErrorMessage for these situations. Maybe add a button for opening the log.

Good idea!

**Comment by cfehse** [comment]
This is fixed in version 2.0.47.
