### ISSUE TITLE
PPrint status bar button does not immediately update when config value changed in settings

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#358]
I'm addressing this now with a small change.

**Comment by PEZ** [comment]
Not sure why it is not closing automatically. But this is now released.

**Comment by bpringe** [comment]
I wonder if it's because I'm only putting the "fixes" term in the PR description, and not in any commit message. The docs look like it should work just in the PR description though.

**Comment by PEZ** [comment]
It reached `master` without the issue being closed. I think it needs to be in a commit message.
