### ISSUE TITLE
No PPrint in cljs REPL

### ISSUE THREAD

**Issue by fnumatic** [BetterThanTomorrow/calva#363]
When i evaluate 
```
(repeatedly 6 #(-> {:foo {:bar :buzz}}))
```
it should pretty print in the REPL window.
As of calva v2.0.42 one can use alt+enter in pprint mode.

It works in clojure REPL and looks like that:
![image](https://user-images.githubusercontent.com/1319530/65874065-23114280-e385-11e9-9ab6-441b0cdfb6b2.png)

But in cljs REPL it does not:
![image](https://user-images.githubusercontent.com/1319530/65874099-3e7c4d80-e385-11e9-96f4-678150c45b0b.png)

Same problem exists in calva v2.0.40 (before PR  #344 )

**Comment by PEZ** [comment]
Thanks!

I think this got an issue when we started to use nrepl middleware for the pretty printing. If you have some time to investigate it, you could check if nrepl pprint is even supposed to work in ClojureScript. That would give us some hint on how tricky this is to fix.

**Comment by SevereOverfl0w** [comment]
https://github.com/nrepl/piggieback/pull/108

**Comment by fnumatic** [comment]
It seems like @bbatsov is working on it.
Thanks, @SevereOverfl0w for the hint.

**Comment by ak-coram** [comment]
If you're looking for a workaround while this is being resolved, run
the following in your **Clojure repl** (and not your ClojureScript
repl) after jacking in. It basically wraps `cljs.pprint/pprint` around
everything you evaluate, while also making sure that `*1`, `*e`,
etc. keep working. I've only tested this with the figwheel-main repl.

```clojure
(alter-var-root
 #'cljs.repl/wrap-fn
 (constantly
  (fn [form]
    (let [wrap-pprint (fn [f]
                        `(let [sb# (goog.string.StringBuffer.)
                               sbw# (cljs.core/StringBufferWriter. sb#)
                               form# ~f]
                           (cljs.pprint/pprint form# sbw#)
                           (cljs.core/str sb#)))]
      (cond
        (and (seq? form)
             (#{'ns 'require 'require-macros
                'use 'use-macros 'import 'refer-clojure} (first form)))
        identity

        ('#{*1 *2 *3 *e} form) (fn [x]
                                 (wrap-pprint x))
        :else
        (fn [x]
          `(try
             ~(wrap-pprint
               `(let [ret# ~x]
                  (set! *3 *2)
                  (set! *2 *1)
                  (set! *1 ret#)
                  ret#))
             (catch :default e#
               (set! *e e#)
               (throw e#)))))))))
```

**Comment by fnumatic** [comment]
Thanks!

It works. Use figwheel-main in my projects. 
I eval this in user.clj at jack in.

Seems there is some movement over there at nrepl lately. Quite a lengthy chat with you and @bbatsov. even @thheller is on board.

**Comment by cfehse** [comment]
@PEZ @fnumatic 

I checked this issue and it seems to work for the clj and cljs REPL Windows as well for inline evaluation. I will for now close this issue.
