### ISSUE TITLE
Trailing whitespace not stripped in the middle of forms

### ISSUE THREAD

**Issue by glenjamin** [BetterThanTomorrow/calva#364]
I'm fairly certain this is down to calva settings, as it seems to work ok in other languages.

Give some code like this

```clj
(defn x [y]
  (let [foo "bar"]
  
    (prn foo y)))
```

Trailing whitespace on the "blank" line 3 doesn't seem to be being stripped.

**Comment by PEZ** [comment]
Does it matter if you have the cursor on the blank line when you format the form?

**Comment by glenjamin** [comment]
I played around with this a little bit more, and concluded that the actual problem was PEBKAC - I didn't actually have format-on-save enabled but i thought i did!

**Comment by dijonkitchen** [comment]
What forcing format on save does work, it formats the whole file. 

I think this is still an issue and just for Calva/Clojure since I can add whitespace, save, and it instantly clears it in other filetypes.

**Comment by PEZ** [comment]
Calva does it on purpose. The line with the cursor is indented placing the cursor ready to enter correctly indented text. Pressing tab with the cursor on some other line (while still in the same form, will clear the whitespace on that line.

**Comment by dijonkitchen** [comment]
Ah, I see the tabbing on a different line does format it and remove whitespace, which is nice, but surprising. 

Maybe just clear whitespace at end of line that's not a newline (for proper indentation)?
