### ISSUE TITLE
Calva breaks Vim keybinds

### ISSUE THREAD

**Issue by mattbruv** [BetterThanTomorrow/calva#365]
If you install [Vim emulation](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) and work on a `.clj` file while Calva is installed, you are prevented from using the <kbd>Esc</kbd> key to return to `NORMAL` mode from `INSERT` mode. Strangely, the only time it will actually work is when the IntelliSense dialog box is open.

**Comment by PEZ** [comment]
You'll need to either bind VIM's normal mode key to something else, or Calva's key for clearing decorations to something else than ESC. Read more here: https://github.com/BetterThanTomorrow/calva/wiki/Using-with-VIM-extension

(Generally, I think Calva is not very compatible with the VIM extension.)

**Comment by mattbruv** [comment]
Whoops, guess I should read the docs 😳

**Comment by dijonkitchen** [comment]
The latest docs on Vim are here: https://calva.readthedocs.io/en/latest/vim.html

Regarding 
> In general Calva’s default key bindings are not very VI-ish. This is a call for someone to share their VIM re-mappings.

Maybe Spacemacs's bindings can be a good reference: 
https://www.spacemacs.org/doc/DOCUMENTATION.html#evil-leader
https://develop.spacemacs.org/layers/+lang/clojure/README.html#key-bindings

**Comment by dijonkitchen** [comment]
Related to https://github.com/BetterThanTomorrow/calva/issues/167
