### ISSUE TITLE
Paredit occasionally stops working in repl window

### ISSUE THREAD

**Issue by agoldhammer** [BetterThanTomorrow/calva#373]
Occasionally, paredit stops working in the repl window. I can restore paredit functionality by using "Paredit Toggle" in the command palette. Thus far I have not been able to reproduce the steps that lead to this condition, but it has happened often enough that I wonder if you have any idea what might cause this. It may be relevant that I am using Calva on WSL.

**Comment by PEZ** [comment]
I doubt it is a WSL thing. Even if I don't have many other ideas about what is going on. I'll try to be alert to this, but I do not use the REPL window myself, so maybe I am not the best observer. :smile:

**Comment by cfehse** [comment]
< I can restore paredit functionality by using "Paredit Toggle" in the command palette.

I doubt this can restore any functionality because the command is broken and does not do anything except toggle the statusbar item. This will be fixed in an upcoming release.

**Comment by PEZ** [comment]
The glitch seems to be such that if you move focus from the editor and then back to it, then Paredit wakes up.

**Comment by cfehse** [comment]
@agoldhammer 

This should be fixed in version 2.0.56. I fixed a bug in the line model, which under some circumstances caused the paredit to stop. I will close this issue for now, but if the problem still persist please feel free to reopen it.
