### ISSUE TITLE
clojure.core/read-line doesn't work in Calva REPL

### ISSUE THREAD

**Issue by ozimos** [BetterThanTomorrow/calva#377]
Repro
1.  `lein new app shopping-list`

2.  Add the following code to "src/shopping_list/core.clj"

         (defn prompt
          "get information from the user"
          [msg]
          (println msg)
          (read-line))

  3.  Jack-in to the project and load the file above `ctrl+alt+c enter`
  4.  Evaluate `(prompt "What is my name")` in the Calva REPL

  Calva REPL becomes unresponsive

  5.  In a new terminal window connect to running nREPL server. `lein repl :connect`
  6.   Evaluate `(prompt "What is my name")` in the terminal. 

All is well. Input is entered at the REPL successfully

**Comment by PEZ** [comment]
Thanks. This should be fixed, even if I right now have no clue how to do it. If anyone else has a clue, I'd welcome help here!

**Comment by PEZ** [comment]
Got this from @bbatsov : 

> There’s a stdin message that gets sent when the REPL is waiting for input.
> See https://nrepl.org/nrepl/0.6.0/ops.html#_stdin

**Comment by cfehse** [comment]
This is fixes in Version 2.0.55.
