### ISSUE TITLE
pretty printing in repl doesn't emit reader literals

### ISSUE THREAD

**Issue by Gnurdle** [BetterThanTomorrow/calva#378]
follows is the difference between pretty and non-pretty repl output
clj.user=> 
(ct/now)
#<org.joda.time.DateTime@71436076 2019-10-06T14:13:50.287Z>
clj.user=> 
(ct/now)
#clj-time/date-time "2019-10-06T14:14:22.977Z"
clj.user=>

This is not a huge(tm) deal, but it is a difference.

The particular case that annoys is trying to paste output back into a 'def' etc.

**Comment by PEZ** [comment]
Might be something to also post on the nrepl repo. (If ny hunch that this is also the case in, say, Emacs CIDER, is correct.)

**Comment by cfehse** [comment]
@Gnurdle 

With the new [pretty print options](https://calva.readthedocs.io/en/latest/pprint.html) this should be fixed. I close this issue for now.
