### ISSUE TITLE
paredit `backspace` in strict mode

### ISSUE THREAD

**Issue by slipset** [BetterThanTomorrow/calva#379]
In emacs, backspace in what would be strict-mode in Calva-paredit, moves the cursor leftwards when trying to delete a `)`, ie it works as left-arrow when cursor is right of a `)`
I'd love for this to be in Calva as well.
Also when the cursor is inside an otherwise empty set of parens, eg (), backspace will delete both of them.

**Comment by PEZ** [comment]
We really should get the old paredit.js out in favour of our own. (Our own is used in the REPL window, where you'll notice things work like you want them to.)

> Also when the cursor is inside an otherwise empty set of parens, eg (), backspace will delete both of them.

That works, right?

**Comment by cfehse** [comment]
This is related to #170.
