### ISSUE TITLE
paredit `paredit-kill`

### ISSUE THREAD

**Issue by slipset** [BetterThanTomorrow/calva#380]
In emacs, there is a function `paredit-kill` which (according to docs):
>Kill a line as if with ‘kill-line’, but respecting delimiters.
In a string, act exactly as ‘kill-line’ but do not kill past the
  closing string delimiter.
On a line with no S-expressions on it starting after the point or
  within a comment, act exactly as ‘kill-line’.
Otherwise, kill all S-expressions that start after the point.

This means that if you're inside an S-expression, you kill to the end of that S-epression.
ie if `|` is the cursor, `(foo | bar baz qix)`, then invoking `paredit-kill` would give you `(foo |)`

**Comment by PEZ** [comment]
Yes, I often see my Emacs wielding colleagues do that. Really cool.

For now in Calva, there is **Kill Sexp Forward**.

**Comment by slipset** [comment]
`killListForward` solves this problem :)

**Comment by clyfe** [comment]
In all examples that follow, killListForward outcome would be `(a|)`.  
Whereas paredit-kill has different behavior in each (it's more granular in its effects).

### Example 1 - s-expresions

```clojure
(a| b (c
       d) e)
```
\+ paredit-kill = (expressions starting on the current line past the cursor are killed)

```clojure
(a| e)
````

### Example 2 - comments

```clojure
(a| ;; comment
  e)
```

\+ paredit-kill = (comment killed)

```clojure
(a|
   e)
````

### Example 3 - newline

```clojure
(a|
  e)
```

\+ paredit-kill = (newline killed)

```clojure
(a| e)
````

**Comment by PEZ** [comment]
Nice examples!

Not sure why you want to dig up this old and fixed issue. Please file this as a new issue. And add this one example:

### Example 4 - don't kill past end of list

```clojure
(a| e)
```

\+ paredit-kill = (rest of list killed)

```clojure
(a|)
```
