### ISSUE TITLE
Pprint not working

### ISSUE THREAD

**Issue by anan44** [BetterThanTomorrow/calva#384]
I cannot get the pretty print to work. Regardless what how much it is toggled, the pretty print does not work. Data structures are printed as one blob with no indentations.

**Comment by PEZ** [comment]
Is this with Clojure or ClojureScript?

**Comment by anan44** [comment]
Clojure

**Comment by PEZ** [comment]
Thanks. Now I need to know more about your setup. OS, project type, how you start the REPL, etcetera.

**Comment by anan44** [comment]
Ubuntu 18.04. Close to no pluggins. I start repl from lein on terminal and connect to it from VSC on what ever port it happens to be in.

**Comment by PEZ** [comment]
It could be that your REPL doesn't have the dependencies needed. Have you tried following this guide? https://github.com/BetterThanTomorrow/calva/wiki/Connect-Calva-to-Your-Project
