### ISSUE TITLE
Evaluate Top Level Form Does Not Show Syntax Errors

### ISSUE THREAD

**Issue by marcomorain** [BetterThanTomorrow/calva#390]
My workflow is to write some code, and then eval in Cavla by pressing `F12`:

```JSON
    {
        "key": "f12",
        "command": "calva.evaluateCurrentTopLevelForm",
        "when": "calva:connected"
    },
```

After recently working on Clojure 1.10.1 projects, I get the following output:

![image](https://user-images.githubusercontent.com/448001/66646310-b8ca8e80-ec1d-11e9-8930-ffa11375136a.png)

This doesn't show the error any more. It used to when Clojure would print it all on one line.

![image](https://user-images.githubusercontent.com/448001/66646327-c97b0480-ec1d-11e9-9673-52b136e808a3.png)

I have to open the output pane to see the error ^

**Comment by PEZ** [comment]
You can see the message in the hover as well. If you're on a mac, the default key binding is `cmd+k cmd+i`. So `F12 cmd+k cmd+i` in your case (if on mac and all that). Does that work? (The inline display can only be a single line.)

**Comment by marcomorain** [comment]
![image](https://user-images.githubusercontent.com/448001/66655471-04883280-ec34-11e9-8231-fd94f4ebf551.png)

That does indeed add a hover with the message, that helps a lot, thanks 🙏 .

**Comment by PEZ** [comment]
Can I close this? :smile: ❤️

**Comment by marcomorain** [comment]
Sure, go for it.
