### ISSUE TITLE
Better communicate issues with Vim mode

### ISSUE THREAD

**Issue by martinklepsch** [BetterThanTomorrow/calva#396]
There are a variety of issues with using Calva with Vim mode as documented on this [wiki page](https://github.com/BetterThanTomorrow/calva/wiki/Using-with-VIM-extension). Since most users won't see this wiki page when using Calva first it might make sense to actively warn people when Vim mode is installed.

**Comment by PEZ** [comment]
Can you test this build for us, @martinklepsch ?

https://1360-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.52-dev-c8fa07b8.vsix

What should happen is:

* If you have the VIM Extension installed:
  * _Calva says_ has a message about the VIM Extension detected and a ling to the documentation.
  * An information box opens with a message that you should see the documentation.
  * The box has a button reading: "Open the docs".
  * Closing the info box w/o clicking the button will show the info box next time Calva is activated and finds the VIM Extension installed. (You might want to test this before clicking the button).
  * Clicking the button opens the user documentation page about [using Calva with the Vim Extension](https://calva.readthedocs.io/en/latest/vim.html)
     * The info box should never be seen again.
     * The _Calva says_ message keeps appearing every time Calva activates and finds the VIM Extension.

See https://github.com/BetterThanTomorrow/calva/wiki/Testing-VSIX-Packages if you don't know what to do with the build file. :smile:
