### ISSUE TITLE
Shortcut for jumping to tests

### ISSUE THREAD

**Issue by AlexVPopov** [BetterThanTomorrow/calva#406]
It'd be nice if there was a shortcut, allowing one to jump to a the corresponding file unser `test`, while having open a given file in `src`. Let me illustrate that with an example: if one has open `src/my_ns/foo.clj`, after pressing the shortcut VS Code should opena and focus the file `test/my_ns/foo_test.clj`. An extra would be, if VS Code would offer the user to create the file automatically for them in case the file doesn't exist.

**Comment by PEZ** [comment]
Thanks. I'd like to implement this so that it works both ways. The same command opens the tests from the SUT as opens the SUT from the tests. Much like is suggested for going back and forth between REPL window and the editor in #339 .

**Comment by AlexVPopov** [comment]
@PEZ yep, this makes total sense. Most of such functionalities (for example for Ruby/RSpec) are indeed implemented both ways.

**Comment by PEZ** [comment]
This is implemented since a while.
