### ISSUE TITLE
html->hiccup conversion

### ISSUE THREAD

**Issue by filipesilva** [BetterThanTomorrow/calva#407]
Heya,

This is a feature request.

Cursive, another popular editor for Clojure, has a handy feature where it will ask to convert HTML strings to Hiccup when pasting them into Clojure/Script files. This functionality is similar to what's provided in https://htmltohiccup.herokuapp.com/. It would be handy to have it in Calva as well.

**Comment by filipesilva** [comment]
That site seems to mostly run [hiccup-bridge](https://github.com/hozumi/hiccup-bridge) in https://github.com/seabre/htmltohiccup/blob/master/src/htmltohiccup/conversion.clj
```
(ns htmltohiccup.conversion
  (:require [hiccup-bridge.core :as hicv]
            [clojure.pprint :as pp]))

(defn to-hiccup [hcp]
  (-> (hicv/html->hiccup hcp)
      (pp/pprint)
      (with-out-str)))
```

**Comment by n2o** [comment]
I'd love to see this feature. It is so handy to have it directly backed into the editor when pasting an html snippet :-)

**Comment by filipesilva** [comment]
Wow wasn't expecting this to be added :D thanks!
