### ISSUE TITLE
shadow-cljs Jack-in converts CLJ Session to CLJS

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#408]
This is a pretty horrible bug. When jacking in to a shadow-cljs project (have only tested this with `calva-lib` so far) the CLJ session gets converted to a CLJS session.

To reproduce:

1. Jack in to a shadow-cljs session, and wait for the CLJ and CLJS REPL windows to open.
2. In the CLJ REPL window, evaluate `*ns*`

**Expected**
The result `#namespace[<INIT-NS>]` is printed.

**Actual**
`nil` is printed, or a complaint about no app connected is printed (depending on things).

This is because it is actually a ClojureScript REPL backing that window.

**Comment by cfehse** [comment]
@PEZ 

> This is because it is actually a ClojureScript REPL backing that window.

No the REPL windows behave correctly. The error happens after the init code `(shadow.cljs.devtools.api/nrepl-select <build>)` is evaluated in the CLJS session. After this code is executed in the cloned CLJS session the CLJ session behaves like the CLJS session when evaluating code. If your call the `complete` opcode in the CLJ Session the correct information are retrieved. The completion in the CLJS session does not work - it should not work because no application is connected. 

Seems a bug in shadow-cljs to me.

**Comment by cfehse** [comment]
Here to illustrate the current behavior (version 2.0.52) tested with calva-lib as well:

![calva-issue-408](https://user-images.githubusercontent.com/55053134/67149877-05166e00-f2b1-11e9-812f-2530b3c00786.gif)

**Comment by PEZ** [comment]
> > This is because it is actually a ClojureScript REPL backing that window.

> No the REPL windows behave correctly. 

I don't see a contradiction here. 😄 I do agree it looks like a shadow-cljs bug. But just maybe we do something funny with our sessions in the shadow case. I'll try find a way to isolate the behaviour.

**Comment by cfehse** [comment]
Perhaps no bug in shadow - perhaps it is the intended behavior. If you take a look at the API function there is only one worker, one middleware and one build target. Our code does nothing with the clj session expect of cloning it. But take a look at it. I virtually know nothing about shadow and cljs. *gg*

**Comment by PEZ** [comment]
At least I have now confirmed that this is new behaviour in shadow-cljs. I picked an older version at ”random”, 2.8.2, and there this does not happen.

**Comment by PEZ** [comment]
Now bisected it down so that we know that the change happens between shadow-cljs 2.8.52 and 2.8.53. Thomas Heller is informed about this now and says he thinks he knows what is going on. There's hope!

**Comment by cfehse** [comment]
Very cool!

**Comment by PEZ** [comment]
There is a new shadow-cljs in town, 2.8.65. It fixes the problem reported here, but also introduces a new one: Now the CLJS REPL window gets a Clojure REPL. 😄 The first ClojureScript session we create (backing the editor), does work, however. So the good news is that we can deal with it in Calva, simply by giving the REPL Window the same session as the one backing the editor. This would be safe, because in ClojureScript, the clone and the cloned are the same anyway. (Different from Clojure sessions which maintain separate dynamic variables and such. So we would have to do this only for ClojureScript sessions.)

Thomas Heller is looking at it and will probably fix so that we don't have to. We'll see.

In the meantime. Anyone that needs the ClojureScript REPLs working in Calva, should use shadow-cljs 2.8.64, and if they need both Clojure and ClojureScript REPLs, they should use 2.8.52.

**Comment by PEZ** [comment]
This has been fixed in shadow-cljs `2.8.66`. YAY!
