### ISSUE TITLE
Incorrect red highlights around brackets/paren in specific case

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#410]
Sorry if the title was oddly worded. I didn't know the best way to state the issue.

In the REPL window, if I create a vector of vars I get red highlights in the following manner, which seem to be indicating mismatches, but there are no mismatches. The following code evaluates just fine, but it looks like it would not.

![image](https://user-images.githubusercontent.com/12722744/67024939-0fbae280-f0ba-11e9-9b71-e9abd66e0db3.png)

**Comment by PEZ** [comment]
The wording is fine. No worries. 😍

**Comment by cfehse** [comment]
@bpringe 

If the first character in a pair of `() [] {}` is  `#` the matching will be wrong matching. If the `#` is second or further down in the sequence the matching is correct: like `(def example [map #'+ #'-])`.
