### ISSUE TITLE
TS-linting warnings about floating promises

### ISSUE THREAD

**Issue by sauvala** [BetterThanTomorrow/calva#411]
While I'm hacking Calva my ts-lister is showing warnings about floating promises on function calls of `evaluateSelection` in `src/evaluate.ts`.

Here is one of them
https://github.com/BetterThanTomorrow/calva/blob/9193fd9a09222174e3848ed4e2584cabba5856c3/src/evaluate.ts#L120

**Comment by bpringe** [comment]
Closing since it appears the fix has been merged. Thanks @sauvala!
