### ISSUE TITLE
Indentation on save not working

### ISSUE THREAD

**Issue by jefffriesen** [BetterThanTomorrow/calva#42]
Saving the file with these examples doesn't fix the indentation:
<img width="381" alt="screen shot 2018-06-04 at 6 13 32 pm" src="https://user-images.githubusercontent.com/445733/40948015-13371b34-6823-11e8-9f30-19e8682cabf5.png">

* Parinfer is not installed
* I've tried it with `editor.formatOnSave` both as true and false
* REPL is working
* Calva Paredit: 0.1.7
* Calva: 1.3.23
* VS Code: 1.23.1

My settings are here:
```
{
    "atomKeymap.promptV3Features": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.formatOnPaste": true,
    "editor.minimap.enabled": false,
    "calva.lintOnSave": true,
    "calva.autoAdjustIndent": true
}
```

Thanks

**Comment by PEZ** [comment]
Hello,

I think this might related to #41. Something in the nREPL setup is not working. Currently format on save uses `cljfmt` via Cider/nREPL.

Let's see if we can figure out what causes #41, and if I am right about this being rooted in the same issue.

**Comment by jefffriesen** [comment]
Ok, so it seems I'm connected to nRepl properly. Peek and hovering over a function shows their definitions. I've got: 
* `AAI: on` in the bottom bar of of VS Code. 
* `"calva.autoAdjustIndent": true,`
* Parinfer disabled

But I can't get auto formatting to work. I copy and paste this into a file, save and it doesn't get reformatted:

![screen shot 2018-06-05 at 10 36 33 pm](https://user-images.githubusercontent.com/445733/41017651-142abcb2-6913-11e8-8a8e-7ecac68b5269.png)

Any suggestions?

**Comment by pedrorgirardi** [comment]
There is something on the way for formatting Clojure, ClojureScript and EDN code without a REPL connection for Calva. Peter and I are deciding how to 'deliver the update', but we're very close to ship it.

Would you like to try it before we actually release it to the VS Code Marketplace?

**Comment by jefffriesen** [comment]
Sure - I'll give it a shot. Thanks

**Comment by jefffriesen** [comment]
@pedrorgirardi I tried to install it with these instructions:
https://vscode-docs.readthedocs.io/en/stable/extensions/install-extension/

1. Tried just dragging it into the extensions folder.
2. Tried actually installing using `--install-extension`

Here is my extension folder:
<img width="705" alt="screen shot 2018-06-06 at 7 42 27 am" src="https://user-images.githubusercontent.com/445733/41041755-3334006a-695d-11e8-8e66-f1112c636570.png">

Here is the message I get when trying "Format Selection"
<img width="574" alt="screen shot 2018-06-06 at 7 40 45 am" src="https://user-images.githubusercontent.com/445733/41041772-3ecb7728-695d-11e8-8f4d-52da6c0e25f4.png">

I'm happy to try to get this working to help you debug. But if it's easier for you for me to wait that's fine too. Thanks!

**Comment by PEZ** [comment]
Glad you want to help with getting this stuff working, @jefffriesen!

VSIX packages are installed in their own funny way. In the Extensions view there is a small menu under the three dots (I call them meatballs) in the title bar or the extensions list. In that meatballs-menu you  should find an option to **Install from VSIX…**.

Keep in mind, though, that the current Calva is not prepared for cooperating with this extension so you will need to disable Calva to try it out. Looking at your screenshot there, with the extensions installed, it actually seems like this might be the problem you are facing,

**Comment by jefffriesen** [comment]
Yep - that formatted the selection after disabling the other Calva extensions. I'm going to go back to using the Calva language and paredit until you officially publish the formatter and they work together. Thanks again.

**Comment by PEZ** [comment]
Yes, we did. :smile:

Partly because of your reports, even. Please let us know if something does not work (and if it seems to work we'd like to know as well).
