### ISSUE TITLE
support string interpolation syntax highlighting (and maybe even linting)

### ISSUE THREAD

**Issue by alidlorenzo** [BetterThanTomorrow/calva#443]
for example, in the snippet below, it'd be great if `name` could have the same syntax highlighting as other variables:

```clojure
(ns example) (:require [clojure.core.strint :refer [<<]]))

(defn print-my-editor [name] (println (<< "My go to editor is ~{name}")))

(print-my-editor "Calva")
```

taking this a step further, it'd be great if there was a config that allowed us to extend the string interpolation syntax highlighting for custom formats, based on the symbol that is calling it.

i.e. for graphql 
```clojure
(gql "query Users { users: [User]! }")
```

or for sql

```clojure
(sql "select * from users")
```

currently apollo supports this for `gql` string literals in [apollo-vscode](https://github.com/apollographql/apollo-tooling/tree/master/packages/vscode-apollo)

another example is styled-components which supports this for `css` string literals in their [vscode-styled-components](https://github.com/styled-components/vscode-styled-components)

this would go a long way in integrating Clojure with other languages, since one of the main reason for converting everything into maps and `edn` formats seems to be lack of editor support

**Comment by PEZ** [comment]
I've totally missed `<<`. That's a good find!

I think this could prove a bit tricky. But there are ways to allow for subsyntaxes in the tmLanguage definitions... So for instance I think it might be possible to include the clojure syntax inside those `~{}`. And `gql` syntax inside that string, maybe. I wonder if there are any tmLanguage experts out there that could help take a look at it.

**Comment by alidcastano** [comment]
yeah I'm a JS dev primarily so I used string interpolation a lot, it was one of the first things I looked for in Clojure 😅  I much prefer to write out `gql` and `sql` queries in their native string format, so would be great to have editor support!

why do you think it would not be possible if there's already working solutions with js string interpolation? for example, here's how gql queries look like for me using apollo-vscode: 

<img width="300" alt="Screen Shot 2019-10-30 at 5 37 36 PM" src="https://user-images.githubusercontent.com/11031952/67904324-014ddb80-fb3c-11e9-8898-8bb140466466.png">

**Comment by alidcastano** [comment]
i think it'd be great if Calva could provide a basic interface for interpolation highlighting/lighting that could be extended for custom formats (i.e. i'd be cool if the `sql` string could have autocompletion!) - but haven't created a vscode extension so not even sure if that's possible

**Comment by PEZ** [comment]
> why do you think it would not be possible if there's already working solutions with js string interpolation?

I didn't say not possible. 😄 I just don't think it is easy. But might be not so hard for someone who's experienced with tmLanguage grammar.

To make it user extendible is probably in the *very* tricky realm, however.

**Comment by jwhitlark** [comment]
It's from a library, though, right?  Considering it's age, I don't think it's seriously proposed for inclusion in Clojure.
That makes me think that this specific syntax highlighting should be added in a separate extension.

**Comment by bpringe** [comment]
What is `<<`? I can't find it anywhere.

**Comment by alidlorenzo** [comment]
feel free to close this issue - opened it when I was learning Clojure since I used string interpolation a lot coming from JS, but just had to relearn some habits :) 

@bpringe looks like it's in clojure core.incubator: https://clojure.github.io/core.incubator/clojure.core.strint-api.html

**Comment by bpringe** [comment]
Thanks for the info! Learned something new :smile:
