### ISSUE TITLE
calva repl versus command line repl 

### ISSUE THREAD

**Issue by alidlo** [BetterThanTomorrow/calva#447]
what benefit does calva repl provide over a repl started via the command line? 

as someone new to clojure, I'm not aware of what the optimal experience should be, nor are there any recent videos that I could find online showing it. so I'd be great if you could clarify what the benefits are over the other.

I also ran into an issue where calva repl is just hanging on start, likely because of my use of workspaces. and now I can't get the start option to work even without it 😅 which is partly why I'm opening the issue to ask the question

**Comment by alidcastano** [comment]
as a side question, would it be possible for calva to integrate [rebel-readline](https://github.com/bhauman/rebel-readline) for a better readline experience?

**Comment by PEZ** [comment]
Hello! Sorry for late response.

Calva brings the REPL to your code, inside the files where you are crafting it. Command line REPLs are good for small experiments, but isn't at all optimal for helping you create your functions and your program. Check this demo gif to get a glimpse at how you can stay in the editor while making sure your functions behave as they should:

![top-level-comment-eval](https://user-images.githubusercontent.com/30010/68155308-bec83c80-ff49-11e9-8ee2-c178a195827a.gif)

There is a REPL prompt in Calva, not all unlike the command line REPL prompt. This is a step closer to your project code, but I certainly prefer to only use the REPL from the editor.

As for rebel-readline, it is not really in reach powering Calva's REPL prompt. Is it something in particular you are lacking?

**Comment by bpringe** [comment]
Closing due to staleness. Reopen if desired.
