### ISSUE TITLE
Cannot connect to repl created by lein in vs code 1.24.0

### ISSUE THREAD

**Issue by dtaivpp** [BetterThanTomorrow/calva#45]
Hello, here is my system and what I am running into.
OS: Windows 10 64 bit
Shell: 1.7.12
VS Code Version: 1.24.0
Clojure 1.8.0
REPL-y 0.3.7, nRPL 0.2.12
Java HotSpot(TM) Client VM 1.8.0_144-b01

I took the steps that were previously working, that is navigate to the root directory of my project. Create a rpl with lein repl. Use CTRL + Shift + P and then use Calva: Connect, enter in localhost:(port number shown in repl), and nothing happens. I cannot execute code with CTRL + Shift + V and E. It does not give any errors but is also not seemingly connecting to the repl. 

So far I have tried restarting the computer, starting repl's in different sub directories but to no avail. Any ideas or suggestions?

**Comment by dtaivpp** [comment]
Configuration for Calva was lost in an uncommitted change. Solved by re configuring Calva.

**Comment by PEZ** [comment]
Happy you managed to get it working again.

But, really, Calva should help a bit more with diagnosing the situation.

@pedrorgirardi @jefffriesen
