### ISSUE TITLE
"Require REPL Utilities" command is broken

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#451]
I was looking into #433 and I realized this command doesn't work, at least for me. I run the jack-in command, the repl window opens, and then I run the Require REPL Utilities command. I see `REPL utilities (like apropos, dir, doc, find-doc, pst, and source) are now available.` in the Calva says window, but I get an error when I try to use `doc`:

![image](https://user-images.githubusercontent.com/12722744/68178038-43618d80-ff3f-11e9-9a7a-6f3cacf19bf4.png)

**Comment by bpringe** [comment]
Update: It works if I have the cursor in the repl window when I run this command, but shouldn't it work also if I have the cursor in the editor?

**Comment by PEZ** [comment]
From the screenshot it looks like you are trying to evaluate `(doc map)` in the `user` namespace. Maybe you required in the REPL utils in another namespace in the editor?

**Comment by cfehse** [comment]
@bpringe @PEZ 

The problem is that the REPL window and the editor do not share the same session. If you execute the command the tools will immediately work in the editor that was active while executing the command (only in this namespace the tools are aquired). In the current implementation the REPL window is only used to determine the session type (strange enough) but the session of the REPL window is not used to aquire the tools there as well.

**Comment by cfehse** [comment]
@bpringe 

> Update: It works if I have the cursor in the repl window when I run this command, but shouldn't it work also if I have the cursor in the editor?

Yes you are absolutely wright. One way to make it work as well is to close the REPL window. Execute the command and then open the REPL window (which will clone the editor session with the aquired tools for the new REPL window) then change the namespace of the REPL window to that of the editor and then the tools will work. *gg*

**Comment by PEZ** [comment]
Actually I think this works as intended. No need to close and reclone any sessions. Sessions share definitions. If the utilities are required to namespace `foo` from the editor then they will be available in namespace `foo` in the REPL window. And also vice versa.

**Comment by cfehse** [comment]
@PEZ 

If a REPL Window exists shouldn't  the command not be executed in both sessions? REPL Window and editor?

**Comment by bpringe** [comment]
Ok... so this was not working as you say it should above when I tried it in an existing leiningen clj project. However, I just created a `lein new test-project` and it worked fine. 🤔

**Comment by bpringe** [comment]
Here is an example of it not working. Notice the `(doc map)` does not resolve on save (evaluate, shown in the Calva says window) or in the REPL window after requiring the utilities into that namespace.

![calva-require-repl-utilities](https://user-images.githubusercontent.com/12722744/68226165-6d01cf80-ffa6-11e9-917a-cbf888f5194a.gif)

**Comment by PEZ** [comment]
That's odd. But at least it is consistent. Make a copy of that non-working project, so that you can use it for debugging the issue. 😄

**Comment by bpringe** [comment]
Okay ~ ... At the risk of seeming crazy... I have some repro steps and a test repo. I don't really know how to make sense of the effects as of yet.

The repo:
https://github.com/bpringe/test-project

The steps (with eval on save turned on, but can probably do the same with eval commands)
1. Open the project and open core.clj
2. Jack-in
3. Evaluate the file
4. Add `(doc map)` to the bottom of the file, save, notice doc is not found
5. Run "Require REPL utilities" command, save, notice `(doc map)` evaluated successfully

Now... the above always works with the core.clj file, _however_, in each of the `new(x).clj` files, if you repeat steps 3 through 5 you will notice that the doc expression does not evaluate successfully.

Furthermore, if you avoid step 3 and add `(doc map)` before the first time you evaluate the file, you'll notice that steps 4 and 5 result in the successful evaluation of the doc expression.

**Comment by cfehse** [comment]
@bpringe 

I created a PR which fixes the issue in my tests. One critical point was to ensure that the namespace of the file exists in the REPL. If the namespace exists (even in case of the "empty" files `new(x).clj`) than the command successfully requires the tools and they are available. Perhaps you can take a look at my code. 

Thanks!

**Comment by bpringe** [comment]
Ah that makes sense! Thanks!
