### ISSUE TITLE
Paredit not activated until focused moved from and back to the editor again

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#454]
When having Calva set to not open the REPL window on connect, I notice that Paredit is not active until I click outside the file editor window and back again.

Steps to reproduce:

1. Open a new VS Code window.
1. Open a folder with at least one Clojure file in it.
1. Open a Clojure file.
   1. Make sure you have an active cursor in the file.
1. Close the VS Code window.
1. Open it again.
   * The cursor should be blinking in the file. If VS Code or some extension opens some other panes, close them and repeat from **4**
1. Try to use a Paredit command (expand selection, slurp, barf, anything)

**Expected:**

* The Paredit command should be performed.

**Actual result:**

* The Paredit command isn't being performed.

**Workaround, until this is fixed:**

1. Click outside the edited file window/pane.
1. Click inside the edited file window again.
1. Confirm that Paredit now works.

**Comment by cfehse** [comment]
@PEZ 

It works for me - also checked that the paredit extension gets activated.
