### ISSUE TITLE
[Paredit/Editor] paredit.deleteBackward sets cursor position wrong when deleting a line.

### ISSUE THREAD

**Issue by cfehse** [BetterThanTomorrow/calva#458]
This behavior is a bit hard to describe: if the paredit in the editor is set to strict mode - `[λ]` - the backspace key executes the `paredit.deleteBackward` command. If the delete operation deletes a new line (deletes the line in the editor) the cursor position is set 1 character left from what it was before.  The leads to a behavior like this if the user does not pay attention:

![calva-paredit-delete-linebreak-nex-index](https://user-images.githubusercontent.com/55053134/68487967-5ed0df00-0244-11ea-8012-57a82981e9e0.gif)

**Comment by PEZ** [comment]
Wow!

This should be fixed by us swapping out `paredit.js` for our own Paredit implementation. I have tried filing issues on `paredit.js` and there is no response.

**Comment by cfehse** [comment]
@PEZ 

I just quickly fixed it because this issue is very ugly I think. Changing the paredit implementation is a bit of a bigger task, isn't it? But it should definitely be done soon.

**Comment by PEZ** [comment]
Could be big. Could be small. 😄 I am starting to think it will not be very hard, now that we are starting to understand the token cursor and our own paredit module a bit. We will find out.
