### ISSUE TITLE
Can't go neither to clojure nor java definition

### ISSUE THREAD

**Issue by arthurborisow** [BetterThanTomorrow/calva#460]
**Steps to reproduce**

1. create new project `lein new app test-calva`
2. open it in vs code
3. start repl
4. Open core.clj file
5. Place cursor at `println` and `Go to definition` (either with shortcut or from mouse contextual menu). **It successfully goes to appropriate function**.
6. Move cursor a couple of lines forward and place it on `binding` and `Go to definition` (either with shortcut or from mouse contextual menu). **It issues error `No defintion found for 'binding'`**
7. Go back to file core.clj
8. Add line `(.toUpperCase "asd")`
9. Place cursor on `toUpperCase`  and `Go to definition` (either with shortcut or from mouse contextual menu). **It issues error `No defintion found for 'toUpperCase'`**

My env:

macOs X 10.15 Mojave
VSCode October 2019 (version 1.40)
Calva 2.0.58

openjdk version "13" 2019-09-17
OpenJDK Runtime Environment Zulu13.27+9-CA (build 13+33)
OpenJDK 64-Bit Server VM Zulu13.27+9-CA (build 13+33, mixed mode, sharing)

Java is installed with asdf

**Comment by cfehse** [comment]
@arthurborisow @PEZ The ability to get hover/definition in jar files was merged yesterday to the dev branch. Unfortunately I could not yet figure out how to get those information generally for Java methods other the static methods because the repl does not return any information in this cases.

**Comment by arthurborisow** [comment]
@cfehse oh, that's nice, thank you very much - will be waiting for the next release

**Comment by bpringe** [comment]
Closing due to staleness. Go to definition works for Clojure. Implementing for Java would be another issue / feature request.
