### ISSUE TITLE
In the REPL window, redo works in mysterioius ways

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#462]
Issue Type: <b>Bug</b>

There is something funny with the undo/redo stack, such that if you undo things a few steps and then redo, resiprocity is lost: the things that are _redone_, are not those that were _undone_.

Steps to reproduce:

1. Close the REPL window.
1. Open the REPL window.
1. Type in some nice clojure code, and edit it some.
1. Undo
1. Redo

* **Expected:** The code should be restored to what it was before **Undo**.
* **Actual:** Depending on what you have typed and how you have edited it, different shapes of code materialises, but seldom the code that was there before **Undo**. 

Further. If you press undo a few steps and then undo many steps, really crazy things can happen. Check this gif:

![redo-issue](https://user-images.githubusercontent.com/30010/68613698-a1522000-04bf-11ea-91f2-9972bd9986b9.gif)

The last stuff that gets entered there is not me typing. I am just redoing several times.

Extension version: 2.0.60
VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|-psn_0_458864|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cfehse** [comment]
@PEZ @bpringe 

This is what your sequence looks like on my systems (showing Windows but on Linux as well):

![calva-repl-undo-sequence](https://user-images.githubusercontent.com/55053134/68660232-0bf37200-0539-11ea-9964-05a91ebb9092.gif)

I cannot reproduce it. Peter if you have the time perhaps you can fire your Windows VM up and give it a try there? Brandon are you on  macOS as well? Perhaps you can confirm the issue.

**Comment by PEZ** [comment]
I'll try it on Windows. Maybe it is my fix for lineendings that introduced this... That is easy enough to test.

**Comment by bpringe** [comment]
I'm on Windows. `ctrl+z` works for undo but `ctrl+y` does not work for redo, which I'm used to using for redo. Am I hitting the wrong key? If not, redo does not work at all for me.

**Comment by bpringe** [comment]
I'm on Windows. `ctrl+z` works for undo, but `ctrl+y` does not work for redo. Am I hitting the wrong keys? If not, redo does not work at all for me.

**Comment by bpringe** [comment]
Nevermind, I see that it's `ctrl+shift+z` to redo. But it's `ctrl+y` in the editor. Is there a reason not to make it the same in the repl window?

**Comment by bpringe** [comment]
Btw redo works fine for me on windows. I can't replicate what @PEZ showed.

**Comment by PEZ** [comment]
You are the second member of the Calva Team who ask about the `ctrl+y` mystery, @bpringe . Might be time we fix that. (In some good way.)

About the issue. I can't repro it on Windows. undo/redo works like a charm there.

It's interesting that it works on Linux. That might indicate that it is not an `eol` thing. Can someone of you debug what the `eol` setting the LineInputModel gets for the REPL prompt? I'd do it if it wasn't that it is painful, not only to use Windows, but also that it is so extremely slow in the virtual environment.

**Comment by PEZ** [comment]
On my Windows machine both `ctrl+y` and `ctrl+shift+z` are mapped to `undo`, btw.

**Comment by PEZ** [comment]
OK. I know tried this with Calva v2.0.50 (just to pick something older than my `eol` fix. It is the same. This could be some weird MacOS Catalina issue, because I think I should have noticed this before otherwise. (I newly upgraded to Cataline). Will check with my colleague tomorrow, who is still on El Capitain.
