### ISSUE TITLE
Regex literals tokenizes incorrectly

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#463]
Regular expression literals should tokenise as one form/s-expression, but they don't. E.g. `#"foo"` tokenizes as the the `punc` token `#` and a string `"foo"`.

A way to see that this is happening is to type a regex literal as an argument to a function and watch how the signature help mini-hover, match the wrong active parameter:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/30010/68615544-939e9980-04c3-11ea-9358-ab9485470c11.png">

**Comment by cfehse** [comment]
@PEZ 

Something similar is happening with the `@` character. The form:
`(print @fehse)` 
will be parsed to this:
```
0: {type: "open", offset: 0, raw: "(", state: {…}}
1: {type: "id", offset: 1, raw: "print", state: {…}}
2: {type: "ws", offset: 6, raw: " ", state: {…}}
3: {type: "junk", offset: 7, raw: "@", state: {…}}
4: {type: "id", offset: 8, raw: "fehse", state: {…}}
5: {type: "close", offset: 14, raw: ")", state: {…}}
````
