### ISSUE TITLE
How to suppress or resolve "unused binding" error

### ISSUE THREAD

**Issue by switch201** [BetterThanTomorrow/calva#466]
Hello I am following a clojrue tutorial found here: https://www.braveclojure.com/getting-started/

When creating the default clojure project using `lein new app clojure-noob`

This file is created
```
(ns clojure-noob.core
  (:gen-class))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello World!"))
```

When using the Calva plug in I get the error in VS `unused binding args` but I presume that what is present is need to run the code.

I also have another clojure project I have imported, and I am getting the same compiler error on this project as well.

Its possible these symbols are indeed not needed/ are not used, but I trust that they are needed in some way.

Is there any way to suppress or resolve this error because its making all my files show up red.

**Comment by switch201** [comment]
I confirmed that deleting args breaks the hello world script. so it is indeed needed but Calva is reporting it as unused with the only resolution being to delete the symbol, but that causes the code to not work.

**Comment by PEZ** [comment]
`args` are unused so it should be reported as such, IMO. But you can prefix it with an underscore to tell the linter to not report it (so `[& _args]`.

BTW, it's not Calva reporting it. It is the `clj-kondo` extension. But, yeah, Calva installs it for you. :smile:

**Comment by switch201** [comment]
Thanks for the help I will try that
