### ISSUE TITLE
[Feature request] Ability to restart current connection from bottom nREPL icon in one step

### ISSUE THREAD

**Issue by RomanTsopin** [BetterThanTomorrow/calva#474]
Now it's multiple step process (disconnect, connect with steps). I think it will be convenient to add one simple reconnect/restart option.
Use cases:
- New dependencies 
- Multimethods problems
- State errors

**Comment by PEZ** [comment]
Hello. What I do is that I jack in again, `ctrl+alt+c ctrl+alt+j`. And I get rid of the steps using custom connect sequences, like here: https://calva.readthedocs.io/en/latest/connect-sequences.html

Does that work for you, or is there something else to the restart, that I am missing here?

**Comment by RomanTsopin** [comment]
Thanks @PEZ, that's exactly what I was looking for! 

But still thinking that nREPL icon is a good place for this command :)
