### ISSUE TITLE
 Namespace reported as unused when actually used in a symbol

### ISSUE THREAD

**Issue by carlosblanco** [BetterThanTomorrow/calva#481]
Namespaces that are used in symbols are reported as unused in the required section.

![image](https://user-images.githubusercontent.com/925650/69436745-bda45700-0d20-11ea-8374-99cfa2d896d8.png)

**Comment by PEZ** [comment]
Hello, and thanks for the feedback. I'll let @borkdude have look and the say here.

**Comment by borkdude** [comment]
Quoted symbols do not require any namespaces to be loaded or aliased. 

```
$ clj
Clojure 1.10.1
user=> (def hash-code 's/join)
#'user/hash-code
user=> hash-code
s/join
user=> (require '[clojure.string :as s]) ;; completely unrelated
nil
```

**Comment by borkdude** [comment]
However does require the alias:

```
(require '[clojure.string :as s])

`s/join
```
and is correctly linted.
