### ISSUE TITLE
Cannot type closing token inside string in REPL window

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#482]
![closing-token-inside-string](https://user-images.githubusercontent.com/12722744/69464319-db7ab780-0d32-11ea-939a-2f113b00d57b.gif)

When typing a string in the REPL window, I cannot type the following characters in the string: `} ] )`.

I can type the opening version of those tokens and it will auto-add the closing version, but I cannot type just the closing version. When I do, the cursor jumps to the end of the expression.

**Comment by PEZ** [comment]
Haha, that's funny. Wanna try fix it?

**Comment by bpringe** [comment]
Yes I plan to.
