### ISSUE TITLE
Prevent multiple concurrent evaluations for the same file

### ISSUE THREAD

**Issue by stefan-toubia** [BetterThanTomorrow/calva#484]
Something I've noticed recently is sometimes if the REPL hangs or a file takes some time to evaluate that I can accidentally trigger multiple evaluations.  TBH I'm not sure what type of negative impact this might have, but I'm thinking it's probably a good idea to prevent this from happening.

Maybe there is an edge case where you trigger an evaluation, and during a long evaluation you make some additional changes, so you want to make sure the most recent changes are evaluated as well.  If concurrent evaluations should be prevented, maybe in this case the second evaluation should be queued, and there is at most 1 evaluation queued up at a time.

**Comment by PEZ** [comment]
Interesting. I wonder how this is dealt with in CIDER. Any input you can provide, @bbatsov ?

**Comment by bpringe** [comment]
I don't think there is an issue here with concurrent evaluations, and I think it should be allowed / a feature. I could see perhaps the desire to interrupt running evaluations, but there is a command for that.

**Comment by bbatsov** [comment]
> Interesting. I wonder how this is dealt with in CIDER. Any input you can provide, @bbatsov ?

nREPL serializes the evaluation per one session, so only one would be in progress at any given time and the rest will simply be enqueued. If you want parallel evaluations you have to enqueue them in different sessions, so in your case the outlined potential issue simply doesn't exist. :-)

**Comment by bbatsov** [comment]
More details - https://metaredux.com/posts/2019/12/20/userstanding-nrepl-sessions.html

**Comment by bpringe** [comment]
Thanks for the info @bbatsov. So it seems @stefan-toubia's statement is actually how nrepl works already:
> If concurrent evaluations should be prevented, maybe in this case the second evaluation should be queued, and there is at most 1 evaluation queued up at a time.

i.e. 
>so only one would be in progress at any given time and the rest will simply be enqueued

**Comment by stefan-toubia** [comment]
Oh wow, great to know! Guess that closes out this issue then. Thanks for the extra details, @bbatsov! That was a good read.
