### ISSUE TITLE
How to hide or disable parameter hint (function signature) tooltip?

### ISSUE THREAD

**Issue by pvaibhav** [BetterThanTomorrow/calva#492]
Recently a great new feature was added: tooltip that shows parameters of a function.

However this tooltip appears *above* the cursor, hiding whatever was written above. It's very likely that a programmer needs to refer to the few lines above to continue writing code. For example base cases of a recursive function are hidden:

![image](https://user-images.githubusercontent.com/234072/69913229-6b0c1e80-1435-11ea-8f52-bdc6c2fdecb3.png)

Pressing ESC or anything doesn't hide the tooltip.

Can we have either a key combination, or a settings option to disable this?

Or at least show the tooltip *below* the current line?

As great as this feature is, over time this has seriously impeded my productivity rather than helping... :( 

Thanks.

**Comment by pvaibhav** [comment]
Well this was a short-lived issue.

For anyone wondering how to disable it, VS Code has built-in option "Editor › Parameter Hints: Enabled" (`editor.parameterHints.enabled`) that you can disable.

**Comment by PEZ** [comment]
Good that you found the solution. You can still pop it up at will with `cmd+shift+space` (Mac), or `ctrl+shift+space` (Linux/Windows).

`ESC` should hide it though. I wonder why it didn't...

You can actually be more precise with `editor.parameterHints.enabled` setting by scoping it inside `[clojure]`. Please note that you probably want to use the Calva defaults there then so it would be a settings object looking like so:

```json
    "[clojure]": {
        "editor.wordSeparators": "\t ()\"':,;~@#$%^&{}[]`",
        "editor.autoClosingBrackets": "always",
        "editor.autoClosingQuotes": "always",
        "editor.formatOnType": true,
        "editor.autoIndent": true,
        "editor.formatOnPaste": true,
        "files.trimTrailingWhitespace": false,
        "editor.matchBrackets": false,
        "editor.parameterHints.enabled": false,
    },
```
