### ISSUE TITLE
Select Backward * commands won't grow selection in REPL window

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#498]
A summary:

![image](https://user-images.githubusercontent.com/12722744/69924408-17fb9100-1460-11ea-9588-39168fe95525.png)

**Comment by bpringe** [comment]
@PEZ I'd like to attempt to fix this, just letting you know.

**Comment by PEZ** [comment]
Nice! I now noticed that after a **Grow Selection** the next backward selection works. Maybe that is a clue.

**Comment by bpringe** [comment]
Just an update here. I believe I have the fix for this and will submit a PR probably later today.

**Comment by PEZ** [comment]
Right, so with your input it seems this got fixed in #507, we'll see when we have tested it some.

**Comment by bpringe** [comment]
This has been fixed. I just verified.
