### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by ribelo** [BetterThanTomorrow/calva#50]
I am getting a `"command not found"` message for each calva function. vscode reinstallation and deleting `~ / .vscode` folder does not help.

```
Linux 4.16.14-2-MANJARO

Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:47:35.732Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by ribelo** [comment]
#49

**Comment by PEZ** [comment]
This is hopefully fixed in Calva 1.3.28. Please let me know if that is the case. And thanks for headsup!

**Comment by ribelo** [comment]
Thanks! Now it works.

**Comment by PEZ** [comment]
Fixed now. I am very sorry for my slip-up and the inconvenience it brought.
