### ISSUE TITLE
Implement paredit drag up/down

### ISSUE THREAD

**Issue by bdevel** [BetterThanTomorrow/calva#500]
@PEZ Thanks for the paredit push left/right. 

I also recommend adding `drag-down` which will move an item that has a list to the left, into the list as the first item. You could then `push-right` to desired position. 

* drag-down: `(let *x* [a 1])` to  `(let  [*x* a 1])`

The `drag-up` would move an item out of a list and placed to the right of it. 

*  drag-up: `(let  [a  1 *x*])` to  `(let *x* [a 1])`.

With those two added, anything can be created with structural edits. The only other drag I can think is `drag-next` and `drag-prev` which is indifferent to boundaries. 

*  drag-prev: `(let  [a  1 ] *x*)` to  `(let [a 1 *x* ])` 
* drag-next: `(let  [a  1 *x* ] )` to  `(let [a 1 ] *x* )`

BTW, this are comparable to `clojure.zip` zipper up/down, left/right, next/previous.

**Comment by PEZ** [comment]
Thanks for these suggestions. I'll implement them all. 😄 

About drag-prev/next. They look a bit like the movement commands `Forward Down/Up` , so I think I'll name it something like that.
