### ISSUE TITLE
Better handling of closing delimiters in strict-mode

### ISSUE THREAD

**Issue by yuhan0** [BetterThanTomorrow/calva#501]
### Current behavior:

- Type a closing delimiter `)`, `]` or `}` anywhere except before itself. Alternatively, try inserting the character literal `\(` which incorrectly triggers an auto-closing `)`
- Hitting Backspace to correct the unbalanced delimiter doesn't work as expected, moving cursor across it instead. Requires a force-delete or selection+delete to restore balance.

### Expected behavior:

- Backspace / delete of a delimiter should always be allowed when it is known to be unbalanced (highlighted red)

- Do not insert unbalanced delimiters so easily in the first place - typing `]` etc. should be a no-op or jump the cursor to the nearest closing delimiter. 
An exception could be when there is an unbalanced opening (eg. from partially commented form or pasted text) and the user is trying to manually close it.

**Comment by liftM** [comment]
This is also frustrating with `"`, where my instinct with `"foo"` is to type the closing `"` expecting it to be skipped over (like in most language modes), but instead creating a new unbalanced string.

**Comment by PEZ** [comment]
This build addresses the deletion of unbalanced brackets: https://3366-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.72-fix-delete-unbalanced-501-d089928b.vsix

I like the other suggestion, but would rather have it as a separate issue, in order to not block the bug fix.

**Comment by wevrem** [comment]
I've also found it unintuitive that typing the second double quote does not break out of the string, but instead adds an extra, unbalanced `"`.
