### ISSUE TITLE
Paredit hotkeys not working on macOS VSCode

### ISSUE THREAD

**Issue by dijonkitchen** [BetterThanTomorrow/calva#502]
I have the latest VSCode and Calva, but I can't Slurp/Barf Sexp Forward via `Ctrl + directions`, but it does work when I use the Command Palette (`Cmd + Shift + P`) and search for slurp/barf, etc.

**Comment by dijonkitchen** [comment]
Interestingly Slurp/Barf Sexp Backward (`Ctrl + Shift + arrows`) works though.

**Comment by PEZ** [comment]
Yeah, MacOS hogs those for Mission Control: Fortunately there is a fix. https://calva.readthedocs.io/en/latest/quirks.html#macos-and-the-slurp-and-barf-keyboard-shortcuts

**Comment by dijonkitchen** [comment]
Thanks! That was helpful to unblock me, but this seems at odds with the _Tao of Calva_.

**Comment by PEZ** [comment]
Interesting. How so?

**Comment by dijonkitchen** [comment]
Based on https://github.com/BetterThanTomorrow/calva/wiki#why-calva , Calva should basically work out of the box without external configuration or it'll be a higher hurdle for beginners. 

Maybe at least it would help to have a link to the quirks on the Paredit page? https://calva.readthedocs.io/en/latest/paredit.html

**Comment by PEZ** [comment]
Agree. I added a link to the Quirks page to the README yesterday, because I realised it had become hard to find since I restructured the documentation. That particular quirk certainly should be adressed on the Paredit page. Will do!

The story with Calva keyboard shortcuts is long and with many bumps in the road. It's a bit of a conflict between me wanting to provide defaults and the risk of defaults not working on this or that platform. I've changed central shortcuts many times because it has turned out there are problems for users of some particular keyboard layout. Seems a bit like whichever way I go with it, I run into issues.

**Comment by dijonkitchen** [comment]
Cool, thanks for all the hard work @PEZ !

**Comment by PEZ** [comment]
I added the info right where the keybinding is mentioned. https://github.com/BetterThanTomorrow/calva/blob/dev/docs/readthedocs/source/paredit.md#editing

**Comment by fgerard** [comment]
Hello I tried to follow this links and I get 404 any help please?

**Comment by PEZ** [comment]
@fgerard I’m afk. But see if you can find the info at calva.io

**Comment by bpringe** [comment]
To @fgerard and anyone else reading this in the future, here is the updated link: https://calva.io/quirks/#macos-and-the-slurp-and-barf-keyboard-shortcuts

**Comment by avidrucker** [comment]
I believe the links above do not aid in resolving the issue/question, "How can I use Paredit on MacOS VSCode"... I could be mistaken though.

Update: I found the key-bindings link for structural editing, it is here: https://calva.io/paredit/

PS: For first time users of Paredit "structural editing" I recommend the following explanation:
**Slurp** (to expand current S-expression to envelop the next/following S-expression): <kbd>Control</kbd><kbd>Option</kbd><kbd>Right Arrow</kbd>
**Barf** (to shrink current S-expression to exclude the last S-expression inside of it): <kbd>Control</kbd><kbd>Option</kbd><kbd>Left Arrow</kbd>

**Comment by bpringe** [comment]
@avidrucker I think that make sense too. @PEZ What do you think?
