### ISSUE TITLE
State of Clojure in VS Code

### ISSUE THREAD

**Issue by julienvincent** [BetterThanTomorrow/calva#51]
This is a very exciting project! I have been waiting for Clojure to get better support in VS Code and this looks to be a very strong start in the right direction! Inline code evaluation is huge and its really nice to see an editor other than emacs finally adopt this :)

After reading #44 and some of the other discussions, I am wanting to open this issue as a more general discussion about the current state of Clojure tooling in VS Code and how this project fits in to all of that.

Personally I use VS Code for all my development work _except_ Clojure for which I use Cursive on Intellij. Cursive is fantastic, but intellij is slow and resource hungry and ideally I would like to do all my development on the same editor. Here are the major areas I feel need to be addressed before the productivity loss from moving to VS Code would be small enough that the benefits of VS Code would out-weight. This is coming from the perspective of a 'mediumly' experience Clojurian and I don't know if these points will match the goal of this project or the pain points of the majority of Clojurians :) It will be nice to hear your thoughts on this.

##### Parinfer

This is huge - it is perhaps the biggest reason why I am unwilling to move to VS Code as it directly affects my productivity while writing Clojure. There is currently a project (https://github.com/shaunlebron/vscode-parinfer) to try add support for this in VS Code but it's integration right now really isn't great.

Perhaps a possible route is for this repo to also replace the existing parinfer extension and make it work (well). I'm not sure about the viability of this?

##### Custom User Commands

This is already a point on your readme about planned future work which is nice to see. This would make usage of the [reloaded](http://thinkrelevance.com/blog/2013/06/04/clojure-workflow-reloaded) workflow much more viable in VS Code.

---

I will be trying out Calva more and will add to this if I find anything else I feel is key. I am very keen to see this project make Clojure great in VS Code and I'll try to dedicate some time to contributing! Custom user commands seems like a good place to start, perhaps we can chat on slack about what that will entail.

Keep up the good work!

**Comment by PEZ** [comment]
Hello, many thanks for this feedback!

*Parinfer*: There are two issues here:

1. The one you point out: the VS Code implementation is a bit flaky.
1. It currently conflicts with Calva's formatting.

Shaun Lebron says that while he is not actively maintaining the VS Code integration he will review and pull PR:s. I think that is the first option we should consider for both issues. For issue two I have considered adding an extension API to Parinfer that Calva and other extensions can use to coexist well with it.

*Custom User Commands*: I did some experimenting with this a while ago. Quite a long while now, and the branch will probably be a bit hard to resurrect. I would be happy to talk a bit about this and see if I was on the right track with my experiment. If you are curious checkout that branch and try it. :smile:

I created a channel `#calva-dev` at the Clojurians slack now and invited you. Hope to catch you there!

**Comment by julienvincent** [comment]
Also worth noting that Parinfer doesn't work at all along side [Vim for VS Code](https://github.com/VSCodeVim/Vim) which will also need to be addressed. If we can get it to a state thats similar to the Cursive experience then we will be in a very good place.

So long as Shaun Lebron has time to manage PR's then I agree that will be the best way to go. Once Parinfer works well it can be made a dependency or something.

---

I will check out the existing user commands branch this evening, even if it needs a re-write it will be useful to have some reference for building on.

**Comment by PEZ** [comment]
I'm closing this for now.
