### ISSUE TITLE
[Feature Request] Add option to deselect text after surrounding with parens/braces/etc

### ISSUE THREAD

**Issue by lacarmen** [BetterThanTomorrow/calva#511]
VSCode will wrap an expression if you select it and type your wrapper. However, it maintains the selection after wrapping. So if I were to select the text `foo` and enter `(` then it would look like this (using square brackets to denote selected text): `[foo] -> ([foo])`

I'd like this option added so I can select something, wrap it, and keep typing without having to hit `left` afterwards. I use this workflow a lot to wrap forms with additional functions. (I know there's "proper" paredit commands to do this, but this is what I'm used to doing 😅)

So using the pipe to show where my cursor would be, this is how I'd like the behaviour to look: `[foo] -> (|foo)`

**Comment by PEZ** [comment]
I am not a big fan of sprinkling out options, so I opted for changing the behaviour to the one you want. VS Code already implements the old behaviour anyway, so users will still have the option.

@lacarmen Can you try this VSIX for me and see that it behaves like you want it to? https://3366-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.72-fix-delete-unbalanced-501-d089928b.vsix

**Comment by lacarmen** [comment]
@PEZ This is perfect, thank you!

**Comment by PEZ** [comment]
Great. Thanks for testing that so quickly.
