### ISSUE TITLE
Multiple Project REPLs

### ISSUE THREAD

**Issue by dijonkitchen** [BetterThanTomorrow/calva#513]
Any way we can open multiple REPLs from multiple projects like we can in other editors? 

Use case would be running both a CLJ REPL for server and CLJS REPL for clients or even multiple CLJ ones for different services at once.

**Comment by PEZ** [comment]
This is related to #76 , I think.

Today when you choose a CLJS Project type when jacking in/connecting to a project, you get both a CLJ and a CLJS REPL connect, as well as one REPL window each. So, as long as your client REPL can be spawned off of the server REPL, this use case works.

For projects where client and server are not using the same ”root” REPL, the way you can have one REPL each is to do something like the **One Folder - Two Windows?** trick mentioned here: https://calva.readthedocs.io/en/latest/workspace-layouts.html

To have one REPL per project, open the projects in separate windows.

All that said, I think we will try to support arbitrarily many REPLs In one window eventually. It will need some thinking and some nice time slot, though.

**Comment by dijonkitchen** [comment]
Thanks! That workaround isn't bad at all. Keeps me from opening VSCode for root project directory and I just have one dedicate project per VSCode/REPL.

**Comment by bpringe** [comment]
Closing this in lieu of #76
