### ISSUE TITLE
Deleting up a line removes next opening character

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#514]
![delete-up-line](https://user-images.githubusercontent.com/12722744/70683080-c8824580-1c55-11ea-96de-f6cacf87e6a9.gif)

I've been experiencing this for some time but was usually busy at the time so I'm just now reporting it 😛 . I don't know exactly what's happening here but when I delete "up" a line, or put another way, delete from the beginning of a line that causes the cursor to go up a line, for some reason the first character is deleted. It seems to happen only if the next character is a form opener. Like `{`, `(`, and `[`.

**Comment by PEZ** [comment]
I fail to reproduce this. Is it like this always or some special circumstances? With or without Paredit strict mode?

**Comment by bpringe** [comment]
This is with strict mode enabled. It doesn't do this when strict mode is disabled. Calva version 2.0.71, Windows 10.

![delete-up-line-2](https://user-images.githubusercontent.com/12722744/70821121-30887700-1d8f-11ea-9be5-7d65a6cc1fc8.gif)

**Comment by PEZ** [comment]
Maybe it is a Windows issue. What happens if you set the line endings to `LF`?

**Comment by bpringe** [comment]
That could be true. I'm away from home for the next two weeks and using Linux on my laptop so I can't test it until I get back :sweat_smile:
