### ISSUE TITLE
REPL keyboard shortcuts and autocomplete broken in >= 2.0.67

### ISSUE THREAD

**Issue by liftM** [BetterThanTomorrow/calva#515]
~This bug is report going to be really weird.~

~I had an infinite loop in my REPL which wasn't responding to ctrl+d and was also making VS Code unresponsive, so I killed VSC with `xkill`.~

This looks like it's happening due to an upgrade to Calva >= 2.0.67 that occurred after my editor restarted.

Some symptoms I'm seeing:

- My backspace and delete keys don't work in the REPL window (I'll hit backspace and the character won't delete) nor do enter, alt+enter, or alt+up/down (nothing happens) when I first connect the REPL. Curiously, ctrl+l and shift+arrow (to select) work fine.
- After I focus another window (not the VS Code window) and go back, my REPL works again. My REPL _stops_ working again after I focus an editor tab.
- For some reason, opening "Keyboard shortcuts" _also_ causes my REPL window to start working again the same as if I focused another window (and similarly, focusing another editor tab causes my REPL window to stop working again).
- When my REPL does work, autocomplete is adding characters after my cursor rather than finishing my word (e.g. autocompleting `(fo` with `foobar` will result in `(fofoobar` rather than `(foobar`).

Some other weirdness that I think might be unrelated:

- On latest Calva (2.0.68), my REPL has a sans-serif font rather than the usual monospace one. This might actually have just been unfortunate timing - VSC restarting may have coincided with 2.0.68 being released with https://github.com/BetterThanTomorrow/calva/commit/33abe9b47186c651e1bf9f4637f4e14f13780234 which I'm pretty sure is the cause.
	- All sorts of extra things break with the sans-serif proportional font (e.g. highlighting for selected characters in the REPL is misaligned with the actual rendered characters - the highlights act as if they are selecting invisible monospace characters), but this is honestly the least of my problems right now and I've gotten along by downgrading to 2.0.67.

Some things I have tried:

- Reinstalling Calva
- Downgrading Calva
- `rm -rf $HOME/.vscode/extensions/{calva folders}` before reinstalling
- Disabling and re-enabling Calva
- Rebooting the machine
- `lein clean`

At this point I'm out of ideas. As far as I can tell, I have reset the extension, reset my REPL, reset VSC, and restarted my computer. I have no idea what else could be breaking.

I _think_ what is happening here is that the keyboard input in the REPL window is being disabled because so many of the bindings are active when `calva:replWindowActive`, and something is causing this property to not be true.

**Comment by liftM** [comment]
Uninstalling and reinstalling the editor with a clean `$HOME/.config/Code` and `$HOME/.vscode` also hasn't fixed the problem.

**Comment by liftM** [comment]
Things are working again now I've downgraded to 2.0.66. I'm not sure this is just a coincidence - it may be possible that I've been running on 2.0.66 and didn't load the latest version until the `xkill`. I'll keep this thread posted if I experience bugs running 2.0.66.

**Comment by PEZ** [comment]
I think it sounds like the xkill isn't part of the problem. Can you try with 2.0.67?

**Comment by PEZ** [comment]
Found the problem with the font. Fix is going out in a moment.

The other problem is probably related to a part of 2.0.67, but I have so far not been able to reproduce it.

**Comment by liftM** [comment]
I think you're right. I'm able to reliably reproduce the backspace and autocomplete problems in 2.0.67, and haven't attempted to reproduce the others. If it helps with debugging, the project I'm working on is https://github.com/liftM/advent2019.

**Comment by liftM** [comment]
See also #519, which reports the same autocomplete issue.

**Comment by liftM** [comment]
I think this is due to keyboard shortcuts not activating due to `calva:replWindowActive` not being set properly. https://github.com/BetterThanTomorrow/calva/commit/a603081d8e41f9e77ad24218797b63ca75993684 between 2.0.66 and 2.0.67 looks suspicious to me.

**Comment by PEZ** [comment]
Indeed. .70 fixes some of it. Auto-complete remains.

**Comment by PEZ** [comment]
Autocomplete is being fixed in #520 , see #519 for a link to a VSIX package to test.

**Comment by PEZ** [comment]
I think 2.0.71 should fix the last piece of this mess. Please close this issue if you agree. 😄 

Thanks for reporting. I could have remained oblivious of the problems for quite a while w/o your help!

**Comment by liftM** [comment]
This looks like it's working now. Thanks!
