### ISSUE TITLE
REPL hangs after first eval

### ISSUE THREAD

**Issue by rpompen** [BetterThanTomorrow/calva#516]
Regression:
Since *after* 2.0.66:

When running a CLI-tools based figwheel-main project, the REPL only evals the first form. Then it hangs on eval, but allows some editing of the line, as if [ENTER] is ignored.

To reproduce:
Simply get https://github.com/rpompen/mkproj-demo , or https://github.com/rpompen/mkproj if you want to generate the project yourself.

Then fire up the figwheel-main session.

Thanks in advance.

**Comment by PEZ** [comment]
Hello. I have started to try fix this in PR #517. Can you pick up the VSIX from the CI **build** step and see if it helps any? See [here about Calva VSIX packages](https://github.com/BetterThanTomorrow/calva/wiki/Testing-VSIX-Packages), if you are not familiar.

So far it seems this is a bug that hits Linux users. Is that true for you as well?

Thanks!

**Comment by PEZ** [comment]
It seems it is a bit of a mystery how to find the VSIX. The latest build, as of this writing, is here: https://3288-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.70-fix-repl-win-focus-516-68688bc9.vsix

**Comment by rpompen** [comment]
I'll give your suggestion a try as soon as I have time. I'm on Pop!_OS Linux from http://system76.com/ .
It's an ubuntu based Linux 5.3 system.

**Comment by rpompen** [comment]
That was easy to check. It works now.
Is it known that command history skips items?

**Comment by rpompen** [comment]
The problem is also fixed in mainstream 2.0.70! Thanks a lot! ;)
