### ISSUE TITLE
allow configuring direction calva editor window splits 

### ISSUE THREAD

**Issue by alidcastano** [BetterThanTomorrow/calva#518]
I use vscode centered layout, so it's more fitting to have calva editor below my code one 

(also see the new font changes are in, looks much better thank you!)

**Comment by PEZ** [comment]
Hi! I'm not sure what you are suggesting here. Can you describe it a bit more?

**Comment by alidcastano** [comment]
here's image of calva with editor panel split vertically (in vscode the command is "view: editor split down")
<img width="1133" alt="Screen Shot 2019-12-13 at 11 41 53 AM" src="https://user-images.githubusercontent.com/11031952/70820156-967bfb00-1d9d-11ea-8714-b6008ee9825c.png">

**Comment by alidcastano** [comment]
also, in a related note, it'd be great if the welcome prompt could be toggled or at least an option to hide it, since it takes a lot of screen space

**Comment by PEZ** [comment]
I'm still not clear with what the suggestion is. 😄 What should Calva do differently from what it does today? (Regarding the original suggestion, I'm leaving the side note to the side right now.)

**Comment by alidcastano** [comment]
sorry didn't realize I wasn't being clear.

right now when i connect to Calva repl by default it opens up its editor to the right (well it actually opens up the clj one in same window, and splits the cljs one to the right).

<img width="1171" alt="Screen Shot 2019-12-14 at 11 37 10 AM" src="https://user-images.githubusercontent.com/11031952/70852389-8ed45900-1e66-11ea-800c-f1789c6f829f.png">

so the issue is to allow the direction in which the editor is split on initialization to be configured.

but I guess a simpler fix for me is to stop using a vertically centered layout 😅

**Comment by PEZ** [comment]
Calva should remember where you move the windows to, and open them there next time. See if it behaves like that for you, and let me know If it doesn't.

When I try with centered layout, and move the windows like this:

<img width="1443" alt="image" src="https://user-images.githubusercontent.com/30010/70852739-4f792d00-1ea5-11ea-9742-c57880593508.png">

Then close the project, open it again, and connect the REPL again, the windows open in the same way as when I closed. This is the intended behaviour, but maybe there are cases when it fails to behave like that...

**Comment by alidcastano** [comment]
oh i see, good to know that's the intended behavior. maybe whether it works or not depends on the way we connect to calva?

i've been starting shadow-cljs manually and then running `connect to running repl` command, rather than the `start a project repl and connect` one

**Comment by alidcastano** [comment]
it also might be a workspace issue then, since I have multiple projects opened up in a workspace

**Comment by PEZ** [comment]
I gotta run so short answer.

1. It shouldn't matter how you connect the REPL.
1. Let's investigate if it is a workspace thing. Maybe I store the location in the wrong bucket.

**Comment by alidcastano** [comment]
so testing this out in non-workspace it seems to only work if i have an editor already open where I want calva to go (so I split a window down first, then open calva)

**Comment by PEZ** [comment]
Yeah, it's the same for me, testing that. I think this is an issue for vscode. It only provides an API for selecting view _column_, when opening a window. To me it makes sense that in Centered Layout, columns would stack top to bottom, but vscode seems to forget about the layout being centered if there is only one editor pane. In any case, there is nothing in the API for us to fix this. That I know of, at least. Might be missing something.

**Comment by alidcastano** [comment]
ok, well at least now I know I can make it work by splitting a window down first before opening Calva

thanks for the discussion, will go ahead and close this
