### ISSUE TITLE
autocompletion in REPL window broken in 2.0.70

### ISSUE THREAD

**Issue by agoldhammer** [BetterThanTomorrow/calva#519]
With 2.0.70 there are now problems with autocompletion in the REPL window. Names are autocompleted but appended to the typed letters or placed outside of parentheses or square brackets when they should go inside.

**Comment by PEZ** [comment]
I found the bug. Please try this VSIX package and help confirm that it fixes the issue:

https://3326-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.71-fix-repl-win-completion-519-22fbb520.vsix
