### ISSUE TITLE
Align Map Items Incorrectly Formats Map Destructures

### ISSUE THREAD

**Issue by hindol** [BetterThanTomorrow/calva#523]
Before format:

```clojure
(let [{response-id :id :as response} (<!! source)]
```

After format:

```clojure
(let [{response-id :id
       :as         response} (<!! source)]
```

**Comment by PEZ** [comment]
How do you think it should be formatted?

**Comment by Hindol** [comment]
I would have preferred the former, i.e. the formatter should leave it as it is. As this is a *binding*, I like to keep the binding target in the same line. The binding source can be formatted over multiple lines though. That is just my opinion.

**Comment by PEZ** [comment]
Got it.

This is not easily fixed, though. The aligning happens in `cljfmt`and is experimental even there. The best place to influence the behaviour is probably this PR: https://github.com/weavejester/cljfmt/pull/77

**Comment by bpringe** [comment]
Going to close this since this fixing I think should go in cljfmt as Peter suggested. Please reopen if I'm wrong or misunderstood.
