### ISSUE TITLE
unable to start clojure cli jack-in repl

### ISSUE THREAD

**Issue by alidlo** [BetterThanTomorrow/calva#526]
Issue Type: <b>Bug</b>

as discussed on slack here are steps im taking
```
clj -A:new app pez/fresh-deps
cd fresh-deps
command: "Calva: Start a Project REPL and Connect (aka Jack-in)"
select: Clojure Cli 
```

Extension version: 2.0.72
VS Code version: Code - Insiders 1.40.0-insider (193fead4103363d1a14873bcf38181d97cf611f6, 2019-10-10T05:24:52.897Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|-psn_0_65552|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpringe** [comment]
Hey @alidlo, are you still experiencing this issue? What happens when you attempt jack-in?

**Comment by alidlo** [comment]
I actually don't use Calva's jack-in command anymore (I've been using connect instead) so not sure if this is still an issue, nor if it was just specific to my setup. I'll go ahead and close it, thanks
