### ISSUE TITLE
CLJ REPL Window Incorrectly Detects Parts of Keyboard Shortcut as Input

### ISSUE THREAD

**Issue by Hindol** [BetterThanTomorrow/calva#527]
For example, the shortcut for *Zen Mode* requires me to press `CTRL + K` followed by `Z`. If the *Calva* REPL window is in focus, it accepts `z` as a character input. The file editor, on the other hand, works correctly.

**Comment by PEZ** [comment]
Yes, that is very annoying . Unfortunately a VSCode bug: https://github.com/microsoft/vscode/issues/85879

Also unfortunate that they have closed the issue for comments...

**Comment by Hindol** [comment]
Oops, I did not notice that this is an upstream bug. Please feel free to close this. Or do you want to keep this one to track the upstream bug?

**Comment by PEZ** [comment]
No problem. I should have reported it here as well.

Let's keep it open, so that people can discover it.
