### ISSUE TITLE
[Feature request] Scroll past bottom of REPL window

### ISSUE THREAD

**Issue by liftM** [BetterThanTomorrow/calva#528]
This is a minor quality-of-life ask, but it would be great if I could scroll past the bottom of the REPL window like I can in a normal editor tab. Having this space would make composing multi-line REPL expressions more convenient - I currently need to scroll down a tiny bit every time I add a new line to my expression (since that scrolling doesn't occur automatically).

**Comment by PEZ** [comment]
Maybe we should start by fixing the issue with the window not scrolling when you enter a new line? 😄 

On the first suggestion... I think that should be pretty simple to fix, but saying that w/o having thought about it much.

**Comment by dregre** [comment]
> Maybe we should start by fixing the issue with the window not scrolling when you enter a new line?

@PEZ is there an issue for this?  I'm looking to solve precisely this issue.

**Comment by PEZ** [comment]
@dregre , I don't think there's a separate issue. However, we are about to remove this repls window, since the new output window.

**Comment by dregre** [comment]
Ah, understood — so I should use the output window in lieu of the repl going forward?

**Comment by bpringe** [comment]
>Ah, understood — so I should use the output window in lieu of the repl going forward?

Indeed! :smiley:
