### ISSUE TITLE
Paredit drag left/right commands should drag pairs inside maps and binding boxes

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#529]
Issue Type: <b>Feature Request</b>

In Cursive Paredit, the drag commands has special behaviour inside maps and binding boxes. Example:

```clojure
(let [a 10
      |b 11])
```

Dragging left will do this:

```clojure
(let [|b 11
      a 10])
```

I think Calva should follow the Cursive way here.

Ping: @bdevel

**Comment by PEZ** [comment]
Like so:

![drag-pairs-in-maps](https://user-images.githubusercontent.com/30010/107146960-a82e4380-694b-11eb-853c-64c3572e7a57.gif)

(The map gets a drag-by-pairs treatment.)

Now works continues with other binding lists... 😄

**Comment by PEZ** [comment]
And now in these binding boxes:

* `let`
* `for`
* `loop`
* `binding`
* `with-local-vars`

Demo:

![drag-pairs-in-binding-box](https://user-images.githubusercontent.com/30010/107160271-9a051500-6995-11eb-906e-264ed917ec02.gif)

Questions for anyone stumbling across this:

* What more binding boxes do you know about?
* Similar treatments make sense in more scenarious, right? Thinking about things like `cond` and `case`.

**Comment by bdevel** [comment]
Bravo! That's awesome. Above and beyond expectations. 

I scanned Clojure's `core.clj` for functions that have bindings similar to `let`. Here is what I found (in addition to the ones already mentioned)

```clojure
(doseq [x [-1 0 1]
        y [1  2 3]] 
  (prn (* x y)))
```

```clojure
;; with-redefs
(with-redefs [type (constantly java.lang.String)
              class (constantly 10)]
         (println (type []) " " (class [])))
```

Plenty of other macros have bindings but not in pairs or they use hashmaps.

For macros with "clauses" here's what I came up with:

```clojure
case
cond
condp
cond->
cond->>

```

The oddball is `condp` which takes two arguments  before the pairs:

```clojure
(condp apply [2 3]
  = "eq"
  < "lt"
  > "gt")
;;=> "lt"
```

In general, and specifically for custom binding macros, it is difficult to automatically determine if the items need to be moved in pairs. You might assume that if there are multiple lines with sets of two on each, that they are binding pairs. That may be challenging to implement and in my opinion probably not worth it. It would be worse if you're moving in pairs and the user doesn't want that.

As an alternative, you could treat a selected region as a single s-expression. This would allow manually selecting two items to move them between other expressions. However, if I recall, there may have been an issue with the dragging with an active selection. Ideally the selection would be maintained.

**Comment by PEZ** [comment]
Thanks for helping with collecting these!

It seems that with the clausy forms both `case` and `condp` are oddballs in that they allow a single default form at the end.... My head starts to spin when trying to figure out how to deal with it. I think I might collect my wins with the map and binding boxes for now. 😄

**Comment by muhajirdev** [comment]
how did you guys do the "drag"? what's the shortcut?

**Comment by PEZ** [comment]
@muhajirdev , search for ”Paredit drag” in the command palette. The commands and their shortcuts should appear. They are also listed here: https://calva.io/paredit/

That said, in the animation above, I use the default shortcuts:
* Drag forwards: `ctrl+alt+shift+f`
* Drag backwards: `ctrl+alt+shift+b`

I'm considering if we should change those shortcuts to something simpler. `alt+down/up`, maybe...

**Comment by bpringe** [comment]
> I'm considering if we should change those shortcuts to something simpler. alt+down/up, maybe...

Probably should be careful there since that maps to moving lines up and down by default, but of course in Clojure that action doesn't make a lot of sense. Not saying it shouldn't be overridden :man_shrugging:

**Comment by PEZ** [comment]
That was my reasoning, actually. Moving lines up/down doesn't make much sense at all. And with @crispinb 's PR with `inComment`  when contexts, #1030, we can keep the moving of lines happen there.
