### ISSUE TITLE
setting up emacs-like keybindings for calva

### ISSUE THREAD

**Issue by zcaudate** [BetterThanTomorrow/calva#53]
I really like this project, the fact that `cljc` files have an option to switch between repls is great.

However, I'm finding the combination of `ctrl-alt-v, e` really awkward to use and would like to set up alternate keybindings such as `ctrl-x, ctrl-e` instead of `ctrl-alt-v, e`. Is there a guide on how this can be done?

**Comment by PEZ** [comment]
Hello! Sorry for late reply. You can change to whatever shortcuts you like in VSCode. There is no magic in play for the `ctrl+alt+v` prefix to the Calva commands, it is just me having chosen that consistently. 

Maybe there is a way to share the settings once you have an Emacsy binding that works for you. I would be interested in publishing such a file if so.

**Comment by zcaudate** [comment]
Oh this is great. I'm mainly used to `C-x C-e` for eval current form and `C-c C-k` for eval entire file. I can play around with it some more and look at the equivalent functionality for both environments.

However, there is one thing that bothers me a little bit. I think eval current form should be able to ignore preceeding whitespace:

currently eval current form only works when the cursor is touching the form, ie:

```
(+ 1 2 3)|      => 6
```

but these examples do not work:

```
(+ 1 2 3) 
| 


(+ 1 2 3) | 
```

**Comment by PEZ** [comment]
Yes, I agree that would be convenient. If you file it as a separate issue it will be easier for me to keep tabs on the todo:s.

**Comment by WebWitch** [comment]
It is possible to share your keybindings.json file which will let you overwrite defaults. I'm not familiar with Emacs, however, I have replaced mine with ALT+V instead of CTRL+ALT+V - [shown here](https://gist.github.com/WebWitch/2bfca0eeba1c92d3200076e051eba0fd). Feel free to modify to your needs.

**Comment by PEZ** [comment]
Nice! I'll try to find a place where we can link to the various keybindings.json files people create for Calva.

(It used to be ALT+V, by default actually. But that didn't work for some locales where that also generated a typing in the editor.)

**Comment by PEZ** [comment]
Right, I think the wiki might be a place to index customisation work. How about it? https://github.com/BetterThanTomorrow/calva/wiki/Customising-Calva

**Comment by zcaudate** [comment]
brilliant. thanks for your help!
