### ISSUE TITLE
[Feature request] - Allow controlling the default text in the REPL window.

### ISSUE THREAD

**Issue by tyohDeveloper** [BetterThanTomorrow/calva#530]
When the REPL window opens it fills a big chunk of the window with introduction text. It also does it when the window is cleared (ctrl-l). I'd like to change it to insert nothing. Others may want to change the text, especially in a team development environment. Either having a true/false setting or putting the text in the json file would be great.
![calva](https://user-images.githubusercontent.com/50533494/71325466-03d10f80-24b3-11ea-8b56-4fcec422bccf.jpg)

This may be a duplicate. Please forgive me if I didn't find it.

**Comment by tyohDeveloper** [comment]
[Feature request]

Have the linter work with (load). 

Currently it issues warnings if the symbols/functions/multimethods don't exist in the current file. This is particularly frustrating when trying to break up a large namespace file into smaller files.

**Comment by bpringe** [comment]
Related to #573

**Comment by alefeans** [comment]
I think this issue can be closed due to the amazing effort done on the new REPL window 😄 !

**Comment by PEZ** [comment]
> especially in a team development environment

I think this is worth remembering. Maybe as part of a connect sequence, it makes sense to specify this.
