### ISSUE TITLE
Have the linter work with (load).

### ISSUE THREAD

**Issue by tyohDeveloper** [BetterThanTomorrow/calva#531]
[Feature request]

Have the linter work with (load).

Currently it issues warnings if the symbols/functions/multimethods don't exist in the current file. This is particularly frustrating when trying to break up a large namespace file into smaller files.

**Comment by PEZ** [comment]
Hello. For me the linter seems to find things defined in required namespaces. In any case, the linting is not done by Calva, actually. It is the [clj-kondo extension](https://github.com/borkdude/clj-kondo.lsp) doing that work.
