### ISSUE TITLE
Java Heap Space Out of Memory when trying to Jack In to fresh shadow-cljs project

### ISSUE THREAD

**Issue by Turmolt** [BetterThanTomorrow/calva#532]
I am following [a shadow-cljs workshop](https://github.com/ClojureTO/JS-Workshop/tree/shadow-cljs), and when I try to get the project set up in Calva I immediately run into an error. I can jack in to the project, but the REPL doesnt respond, and after a minute or so it throws the following error constantly until I close VS Code.

> `[:app] Compiling ...
> Syntax error compiling at (cider/nrepl/middleware/ns.clj:1:1).
>         at clojure.lang.Compiler.load(Compiler.java:7648)
>         at clojure.lang.RT.loadResourceScript(RT.java:381)
>         at clojure.lang.RT.loadResourceScript(RT.java:372)
>         at clojure.lang.RT.load(RT.java:459)
>         at clojure.lang.RT.load(RT.java:424)
>         at clojure.core$load$fn__6839.invoke(core.clj:6126)
>         at clojure.core$load.invokeStatic(core.clj:6125)
>         at clojure.core$load.doInvoke(core.clj:6109)
>         at clojure.lang.RestFn.invoke(RestFn.java:408)
>         at clojure.core$load_one.invokeStatic(core.clj:5908)
>         at clojure.core$load_one.invoke(core.clj:5903)
>         at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
>         at clojure.core$load_lib.invokeStatic(core.clj:5947)
>         at clojure.core$load_lib.doInvoke(core.clj:5928)
>         at clojure.lang.RestFn.applyTo(RestFn.java:142)
>         at clojure.core$apply.invokeStatic(core.clj:667)
>         at clojure.core$load_libs.invokeStatic(core.clj:5985)
>         at clojure.core$load_libs.doInvoke(core.clj:5969)
>         at clojure.lang.RestFn.applyTo(RestFn.java:137)
>         at clojure.core$apply.invokeStatic(core.clj:667)
>         at clojure.core$require.invokeStatic(core.clj:6007)
>         at clojure.core$require.doInvoke(core.clj:6007)
>         at clojure.lang.RestFn.invoke(RestFn.java:408)
>         at cider.nrepl$run_deferred_handler$fn__7626.invoke(nrepl.clj:38)
>         at clojure.lang.Delay.deref(Delay.java:42)
>         at clojure.core$deref.invokeStatic(core.clj:2320)
>         at clojure.core$deref.invoke(core.clj:2306)
>         at cider.nrepl$wrap_ns$fn__7744.invoke(nrepl.clj:257)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_resource$fn__7776.invoke(nrepl.clj:363)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_info$fn__7718.invoke(nrepl.clj:181)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_classpath$fn__7676.invoke(nrepl.clj:111)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_xref$fn__7840.invoke(nrepl.clj:467)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_macroexpand$fn__7736.invoke(nrepl.clj:244)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_test$fn__7800.invoke(nrepl.clj:401)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_version$fn__7832.invoke(nrepl.clj:457)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_clojuredocs$fn__7848.invoke(nrepl.clj:482)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at nrepl.middleware.interruptible_eval$interruptible_eval$fn__6702.invoke(interruptible_eval.clj:144)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_debug$fn__7694.invoke(nrepl.clj:137)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_enlighten$fn__7702.invoke(nrepl.clj:163)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at nrepl.middleware.session$add_stdin$fn__6978.invoke(session.clj:326)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at nrepl.middleware.load_file$wrap_load_file$fn__6867.invoke(load_file.clj:81)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at shadow.cljs.devtools.server.nrepl$shadow_init$fn__7461.invoke(nrepl.clj:27)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_complete$fn__7684.invoke(nrepl.clj:117)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_undef$fn__7824.invoke(nrepl.clj:449)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_format$fn__7710.invoke(nrepl.clj:167)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_profile$fn__7760.invoke(nrepl.clj:300)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_content_type$fn__7652.invoke(nrepl.clj:83)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_refresh$fn__7768.invoke(nrepl.clj:337)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_spec$fn__7784.invoke(nrepl.clj:375)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.piggieback$wrap_cljs_repl$fn__6799.invoke(piggieback.clj:310)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_out$fn__7752.invoke(nrepl.clj:291)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_tracker$fn__7816.invoke(nrepl.clj:438)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at shadow.cljs.devtools.server.nrepl_impl$handle.invokeStatic(nrepl_impl.clj:310)
>         at shadow.cljs.devtools.server.nrepl_impl$handle.invoke(nrepl_impl.clj:295)
>         at shadow.cljs.devtools.server.nrepl$middleware$fn__7470.invoke(nrepl.clj:39)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at cider.nrepl$wrap_inspect$fn__7728.invoke(nrepl.clj:200)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at nrepl.middleware.session$session$fn__6963.invoke(session.clj:272)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at nrepl.middleware.caught$wrap_caught$fn__6648.invoke(caught.clj:97)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at nrepl.middleware.print$wrap_print$fn__6615.invoke(print.clj:234)
>         at nrepl.middleware$wrap_conj_descriptor$fn__6391.invoke(middleware.clj:16)
>         at shadow.cljs.devtools.server.nrepl$start$fn__7501.invoke(nrepl.clj:137)
>         at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
>         at nrepl.server$handle_STAR_.invoke(server.clj:15)
>         at nrepl.server$handle$fn__7000.invoke(server.clj:27)
>         at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
>         at clojure.lang.AFn.call(AFn.java:18)
>         at java.util.concurrent.FutureTask.run(Unknown Source)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>         at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.OutOfMemoryError: Java heap space`
> 

When I follow the instructions and just run `npx shadow-cljs watch app` in vscode terminal it starts up as expected, so I am very confused as to why Calva would break.

This is on a fresh `lein new reagent-frontend reddit-viewer +shadow-cljs` project on Windows 10. Any ideas as to what could be wrong?

**Comment by PEZ** [comment]
Really strange. I'll try it myself and see if I can reproduce it.

**Comment by PEZ** [comment]
Hmmm. It works nicely when I try it. I'm on MacOS, using:
```sh
 java -version
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
```

Which Java are you on?

Not that I think it should have to do with that, but anyway.

**Comment by Turmolt** [comment]
I am also finding that doing everything the exact same way on my mac works as expected, but it doesn't seem to want to work on my desktop

`java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) Client VM (build 25.191-b12, mixed mode, sharing)`
