### ISSUE TITLE
Windows documentation for Evaluate corrent form is wrong

### ISSUE THREAD

**Issue by darkdescendant** [BetterThanTomorrow/calva#533]
Just started looking at Calva and was running through the docs when I tripped over this issue. Took me a while to get it out of the Task list what the correct key binding. Figured I should fix the docs for that for the next person.

**Comment by PEZ** [comment]
How did you trip over the issue?

`ctrl+alt+c v` is supposed to work on Windows. It was a way to fix a strange issue where on some Windows machines, combinations with `e` in them produced strange results. See https://github.com/BetterThanTomorrow/calva/issues/323

**Comment by PEZ** [comment]
This is fixed, right?
