### ISSUE TITLE
Support for comment continuation as a convenience?

### ISSUE THREAD

**Issue by Hindol** [BetterThanTomorrow/calva#536]
Do we want to support certain groups of `;` as block comments? Meaning, upon hitting `<enter>` the new line begins as a comment.

Before:
```clojure
;;; A quick brown fox... [cursor] <enter>
```

After:
```clojure
;;; A quick brown fox...
;;; [cursor]
```

Maybe we can follow the [*ELisp* convention](http://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html) to identify which ones are block comments.

**Comment by PEZ** [comment]
Hello. Sorry for the complete radio silence! Good that @filipesilva reminded me about this suggestion.

Anyway, here's a VSIX with the continuation implemented. I think it feels pretty good and would answer yes to your question.

https://4021-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.77-wip-add-comment-continuation-d5898ba7.vsix

Right now I only continue line comments with two semicolons. But it would be easy to do it for any line starting with any number of semicolons.

Please give it a spin and we can talk about what to do about this.

**Comment by PEZ** [comment]
And here's a build where we don't count the semicolons in order for continuation to happen. 😄 

https://4026-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.77-wip-add-comment-continuation-1861c8da.vsix

**Comment by Hindol** [comment]
Cool! Thanks for working on it. How do I use this VSIX thing? Never used one before.

**Comment by PEZ** [comment]
It is how vscode extensions are packaged. See https://github.com/BetterThanTomorrow/calva/wiki/Testing-VSIX-Packages#installing-a-vsix-package

**Comment by Hindol** [comment]
@PEZ I tried the first build, and I like it! Although, it seems you mixed up the builds as this one does not seem to care how many semicolons are there.

Personally, I would like _two or more_ semicolons to continue automatically to the next line. Single semicolons left alone.

**Comment by PEZ** [comment]
I opted for continuation on any line that starts with a semicolon or more. So if a single semi colon is used at the end of a line, it won't be continued.
