### ISSUE TITLE
print output when evaling

### ISSUE THREAD

**Issue by zcaudate** [BetterThanTomorrow/calva#54]
Where does the results of `print` goto? currently, I'm not able to see the printed results of the in-editor eval:

<img width="1006" alt="screen shot 2018-08-04 at 8 55 54 am" src="https://user-images.githubusercontent.com/1455572/43670907-42128e54-97c4-11e8-8bdb-620c2f83ea14.png">

**Comment by PEZ** [comment]
It got devoured by the giant, green, result eating monster. Sorry about that. 😄 

There is a new version of Calva out just now, fixing this bug. Please update and let me know if it works for you or not.

**Comment by zcaudate** [comment]
It's outputting... though do you think it'll be better if there was another buffer that could be outputted to, as the current buffer outputs:

```
Evaluating:
(prn :a)
out: :a
=> nil
```

instead of the usual

```
:a
```

<img width="338" alt="screen shot 2018-08-05 at 8 25 37 pm" src="https://user-images.githubusercontent.com/1455572/43685882-cd9b1f3e-98ed-11e8-8580-76e0f4667df6.png">

**Comment by PEZ** [comment]
I could do that. Not sure which is best. With the ”regular” REPL it looks like::
```clojure
user=> (prn :a)
:a
nil
```

**Comment by zcaudate** [comment]
It looks like this in Emacs:

<img width="307" alt="screen shot 2018-08-06 at 8 11 03 am" src="https://user-images.githubusercontent.com/1455572/43691519-564ee394-9950-11e8-8a6c-573cf25f6efb.png">

**Comment by PEZ** [comment]
I'll close this for now, since the most glaring bug is fixed. Please feel free to open a separate issue for improving this thing.
