### ISSUE TITLE
 eval current form should be able to ignore preceeding whitespace

### ISSUE THREAD

**Issue by zcaudate** [BetterThanTomorrow/calva#55]
currently eval current form only works when the cursor is touching the form, ie:

```
(+ 1 2 3)|      => 6
```

but these examples do not work:

```
(+ 1 2 3) 
| 
```

```
(+ 1 2 3) | 
```

**Comment by PEZ** [comment]
Didn't I reply to this? Anyway, it makes sense. I have it on my todo list now.

**Comment by PEZ** [comment]
(I know realise why I thought I had already answered. :smile:)

**Comment by zcaudate** [comment]
is there a developer's guide for calva? ie. how to get a dev environment up and running.

**Comment by PEZ** [comment]
There is a short page about it on the wiki (link in the README). But thinking about it, I forgot to mention some things, about installing clojure and shadow-cljs.

**Comment by zcaudate** [comment]
I’d like to hack on a little bit. It’ll be great to have a onramping guide, especially how to how the dev workflow works. ie. do you normally develop the plugin within vscode itself?

 An example of how to make a simple change would also be good as well as how to build the plugin artefact for release.

**Comment by PEZ** [comment]
Those are all great ideas on how to improve the instructions and probably get more people trying to hack on Calva. I'll try to get some time to add it. Meanwhile, see if [these instructions](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute) can get you started, and chat me up in the [#calva-dev](
https://clojurians.slack.com/messages/calva-dev/) channel of the Clojurians Slack, and I'll be happy to help.

**Comment by PEZ** [comment]
Forgot, yes, Calva is developed from VSCode. (At least when I do it. I know of a dude who cheats and uses Cursive. :smile:)

**Comment by AlexVPopov** [comment]
As discussed in Slack, adding here another issue with Calva detecting the current form:
 
![Screenshot 2019-09-02 at 17 44 57](https://user-images.githubusercontent.com/3239252/64123091-0b599500-cdac-11e9-89cc-4319088734c1.png)

On line 5 Calva just returns the value of the symbol `+`, instead of taking the syntax quote into account and returning the fully-qualified name of the symbol (as is the case with line 7, where the whole form is selected and passed for evaluation).

**Comment by bpringe** [comment]
Closing, since these cases seem fixed now. Feel free to reopen if something mentioned here is still not right.
