### ISSUE TITLE
No autocompletion when connecting to a running shadow-cljs nRepl in the current project

### ISSUE THREAD

**Issue by alendit** [BetterThanTomorrow/calva#550]
When I connect to an externally started shadow-cljs nREPL Calva doesn't seem to be able to generate autocompletion. It works fine, if I start shadow-cljs from Calva, though.

**Comment by alendit** [comment]
Sorry, disregard that, I start shadow-cljs without piggyback.

**Comment by PEZ** [comment]
For anyone else finding this issue I'll link to these relevant doc pages:

* https://calva.readthedocs.io/en/latest/connect.html
* https://calva.readthedocs.io/en/latest/jack-in-guide.html

TLDR: Look at the command Calva uses for Jack-in to see how to start shadow-cljs yourself in a way that Calva will be able to use.
