### ISSUE TITLE
Calva Repl hangs while running a regular expression on a large test

### ISSUE THREAD

**Issue by schalla76** [BetterThanTomorrow/calva#551]
The function that hangs:

(defn testfunc
  []
  (def sampletext (slurp "http://www.clearwhitelight.org/hitch/hhgttg.txt"))
  (re-seq #"\w+" sampletext))

When we run above function in Calva Repl, it never returns any results. If the same function is run outside the Calva Repl, it returns immediately.

**Comment by PEZ** [comment]
Hi! Thanks for reporting. I've reproduced it now. It was all too easy. 😢 

I think this has to do with that the sequence returned is large enough to be chunked up In a way that Calva doesn't handle correctly.

Ping @bpringe : This goes into fixing those large data structures we've been talking about, right?

**Comment by schalla76** [comment]
Thanks for your response.

**Comment by bpringe** [comment]
@PEZ Yeah, sounds related.

**Comment by PEZ** [comment]
Hello again. I now tried this and it seems it takes a while to `pprint` the results. Without `pprint` on this returns quickly. With `sprint` it is slower, but it does return when I try it. Might depend on how Calva's `pprint` is configured, of course.

**Comment by bpringe** [comment]
With the current default pprint settings, this does not occur, as `maxLength` is set to 50. See [the pretty printing doc] for details. Super long results like this are best not printed in the repl anyway (printing to a file can be handy). Going to close this, but feel free to re-open if you feel it should be.
