### ISSUE TITLE
Support cljs-suitable by adding "enhanced-cljs-completion?" flag to the completion request

### ISSUE THREAD

**Issue by alendit** [BetterThanTomorrow/calva#552]
https://github.com/rksm/clj-suitable allows the user to inspect javascript runtime through nrepl autocompletion interface. For it to be activated the "complete" requests have to have the "enhanced-cljs-completion?": "t" specified. 

You might also want to add an option to calva to activate this flag.

**Comment by PEZ** [comment]
Hello, I think that in current Calva this already happens. The flag is added in later cider-nrepl, iiaci. Anyway, we'll keep this open, because we should confirm it and also we should probably bump the dependencies and add these options, as you suggest.

**Comment by alendit** [comment]
When I type `js/M` in the current calva master while connected to a shadow-cljs nRepl, no completion appears (the completion works in other places). After I added the flag to the "complete" request in repl/index.ts, the javascript completion started working, so I assume the flag wasn't passed before.

**Comment by PEZ** [comment]
Ah, yes, of course! I have forgotten that Shadow brings in some of the dependencies itself. So then the upgrade I thought I had under control has happened anyway. Good catch. I'll add the flag!

**Comment by PEZ** [comment]
Please take #553 for a spin, @alendit . It's a bit unclear to me how to specify `false` with the flag, `"f"` didn't seem to cut it. I looked at [how CIDER does it[(https://github.com/clojure-emacs/cider/blob/4cc4280677e6eeb16cd55d9865c0ea9f9d141af3/cider-client.el#L537), and followed suit.

**Comment by alendit** [comment]
Your change looks good. I'm not sure how to specify false either, but the way you do it (just not send the attribute) is the way CIDER does it, too, so I'd go with that.

I'll close this issue.

**Comment by PEZ** [comment]
Cool. Thanks! FYI, this is released now, so should be working if you upgrade to latest Calva.
