### ISSUE TITLE
Don't change the namespace to `user` for custom REPL commands

### ISSUE THREAD

**Issue by mkarp** [BetterThanTomorrow/calva#558]
I'd like to request a feature: for custom REPL commands, when `ns` setting is empty, it would be great if Calva executed the specified command within the current namespace.

Currently Calva always switches to the `user` namespace. 

Staying in the current namespace would be very handy to send `(cljs.test/run-tests)` to the REPL. 

If users need to run a command within the `user` namespace, they can always specify it in the settings with `"ns": "user"`.

This feature request was briefly discussed in the calva-dev Slack channel https://clojurians.slack.com/archives/CBE668G4R/p1580916516221100

Thank you!

**Comment by PEZ** [comment]
Finally I got around to this. Here's a build with the suggestion (as I understand it) added: https://4041-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.77-dev-d6fba27a.vsix

**Comment by mkarp** [comment]
@PEZ Thank you so much for the fix! I've just tried it out and it works exactly how I expected.

**Comment by PEZ** [comment]
Glad you like it! I think it is a big improvement. Don't know why I didn't design it like that to begin with. 😄
