### ISSUE TITLE
paredit kill commands should copy the deleted part to clipboard

### ISSUE THREAD

**Issue by zcaudate** [BetterThanTomorrow/calva#559]
As part of the editing process on emacs, I use the `killForward` command to move stuff around in a file. I currently find that the `paredit.killForward` command on vscode doesn't `cut` properly so I cannot paste the deleted code back into the editor using `ctrl-v`

It'll be great if that can be added in.

**Comment by PEZ** [comment]
Hello. VS Code doesn't have a kill ring, like Emacs has. What I do is to select forward and then cut.

**Comment by zcaudate** [comment]
Is there a way to combine the two commands into one shortcut?

**Comment by PEZ** [comment]
I don't think so. In a sense it can be regarded as a chord. So to kill and yank forward it gets: `shift+ctrl+alt+right, ctrl+x`.

What we could consider, I now realize, is to make this a setting. So, it could default to not copy on delete, but you emacs types could set it to behave like that. It would not be nearly like a full kill ring, but anyway.

**Comment by zcaudate** [comment]
I've set my shortcuts to commands that are used quite often. 

For the `forward-select::yank::paste` flow  I do this on Emacs:  
 
 ctrl+k, <move to position>, ctrl+v

It'll be great if that could be replicated on vscode.

**Comment by Oddsor** [comment]
@zcaudate : I solved this same issue by adding the multi-command extension (ryuta46.multi-command), and then adding the following in my settings.json file:
```
"multiCommand.commands": [
         {"command": "multiCommand.copySexpAsKill",
        "sequence": [
            "paredit.selectForwardSexp",
            "editor.action.clipboardCutAction"
        ]}
    ],
```
followed by this in the keybindings.json file (I use cmd+k for "copy as kill"):
```
    {
        "key": "cmd+k",
        "command": "multiCommand.copySexpAsKill"
    }
```

**Comment by zcaudate** [comment]
Oh sweet! I just tried it and it worked really well.

Thanks heaps.
