### ISSUE TITLE
Go to / peek at definition not working

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#56]
I'm using Clojure, and I've been using this extension for a few weeks now and have never had the go to / peek definition working. I was thinking it would be nice if this extension had this feature, and then I noticed in the readme that it does, but mine is not working.

I noticed a closed issue related to this problem. I'm not sure if it's back with recent versions of VS Code or something else is going on with my setup. I have a fresh lein project open with no dependencies besides Clojure 1.8. My VS Code version is 1.25.1.

If I right click on a symbol and click peek definition I get "No definition found for..." My file is evaluated before trying this as well, and in the repl if I type the symbol in it shows it exists.

**Comment by PEZ** [comment]
It is most often about not having the nrepl & codependencies set up. Calva is very sensitive to that. (I'm not by the computer right now so can't assist very efficiently.)

**Comment by bpringe** [comment]
My apologies. I just read about the dependencies on the Getting Started page. I must have overlooked them before. I'll set these up and then see if it works.

**Comment by PEZ** [comment]
Did you get it to work @bpringe ?

**Comment by bpringe** [comment]
Yes, I just got it to work. Thanks for checking. It works for clojure.core functions, but is there no way to make it work for functions defined in my namespace? Like if I define a function called `my-fn` and then call it below that, I can't go to definition of my custom function or peek definition?

**Comment by PEZ** [comment]
That should work, yes. I haven't tested it on Windows 10, but see no reason why it should be about that.

Maybe you have something in the project.clj (assuming you are using leinigen).

**Comment by bpringe** [comment]
It seems to be working on my laptop, which is what matters more at the moment. I did notice on the Getting Started wiki that the repl profile is missing a closing `}`. I pasted it into a blank profiles.clj and was getting and invalid content error when running lein repl. Just FYI. Thanks for the help and for the great extension!
