### ISSUE TITLE
[Feature request] Customize comment characters

### ISSUE THREAD

**Issue by filipesilva** [BetterThanTomorrow/calva#564]
When I press the `Toggle line comment` command, the current line is prefixed with `; `.

My colleagues are using another editor (spacemacs I think), that seems to use `;; ` for comments instead. I've also seen `;; ` in a lot of code snippets online.

I thought it might be a good idea to customize the characters that the editor inserts.

But I wasn't aware but this seems to be a ELisp convention:
- https://cljs.github.io/api/syntax/comment
- https://github.com/BetterThanTomorrow/calva/issues/536
- http://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html
- https://stackoverflow.com/questions/5084191/what-is-the-difference-between-and-in-clojure-code-comments

So perhaps this is a more complicated situation.

**Comment by PEZ** [comment]
Thanks for investigating this a bit. I think it is pretty clear that line comments should be `;;` rather than `;`, so opted for just changing that instead of making it a configuration. (Walking the [Calva Tao](https://github.com/BetterThanTomorrow/calva/wiki#the-tao-of-calva) 😄 )

I also added support for **Toggle block comment**, wrapping the block in a `(comment ...)` form.

Test with this VSIX, which also sports the latest Calva Highlight and Paredit parsing: https://4016-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.77-dev-58d85c07.vsix

**Comment by filipesilva** [comment]
Just installed it and can confirm that the `Toggle line comment` keybind now uses `;;` instead of `;`. I Agree that it's better to just "do right thing" instead of adding an option for it.

The new `Toggle block comment` doesn't seem to toggle per se though. It seems to wrap on the first use, and wrap again on the second use. I imagined that it would work as `Toggle line comment` insofar as it added and removed the `(comment ... )` block. But maybe that was not your intention to begin with.

**Comment by filipesilva** [comment]
Here's how it looks after using `Toggle block comment` four time:
```
(comment
 (comment
 (comment
 (comment
 (print "hello block comment") ) ) ) )
```

Looking at https://github.com/BetterThanTomorrow/calva/commit/58d85c078791f9343be4d2f24458c834c97caf29 makes me wonder if there's some weird interaction going on. You're just adding the vscode language settings for comments so it is out of your hands how the toggling proper works. Maybe the auto-indent is adding a couple of spaces and making it so the toggle doesn't work anymore?

**Comment by PEZ** [comment]
I don't think there is any auto-indent going on even. You have to press tab after the wrapping to get it formatted. ¯\_(ツ)_/¯

**Comment by filipesilva** [comment]
If I start with
```
(print "hello block comment")
```

And run `Toggle block comment`, I get
```
(comment
 (print "hello block comment") )
```

So it added `(comment\n  ` and ` )`. Note the two spaces after `\n` and the single space before `)`.

But in https://github.com/BetterThanTomorrow/calva/commit/58d85c078791f9343be4d2f24458c834c97caf29, we don't see those three spaces:
```
blockComment: ['(comment\n', ')']
```

If I start with
```
(do
  (print "hello block comment"))
```

And run `Toggle block comment` with `(print "hello block comment")` selected, I get
```
(do
  (comment
 (print "hello block comment") ))
```

So the same thing, regardless of current indentation: `(comment\n  ` and ` )`, three spaces.

**Comment by PEZ** [comment]
There is a setting for if VS Code should add spaces there or not. Doesn't matter for toggling or not though... I made an experiment with using `#_(` and `)` as the pair instead. Then the toggle happens once, but VS Code loses track of the current selection so toggling again just wrecks havoc. Short of making our own command for this, I don't think we can do much about it.
