### ISSUE TITLE
[Bug] single-quote literal breaks the rainbow and paredit

### ISSUE THREAD

**Issue by kstehn** [BetterThanTomorrow/calva#566]
When somewhere a sinle-quote literale like `\'` is used the paredit and rainbow is broken for this file from this line onwards.

Example function:
```clojure
(defn test [string-to-escape]
  (map #(str "'" (string/escape % {\' "''"}) "'")
       ["ab" "asc"]))
```
In VSCode:
![image](https://user-images.githubusercontent.com/5702321/75248389-61941780-57d4-11ea-94bd-362bcd414c9c.png)

**Comment by 2knu** [comment]
Same Issue for this: (Seems to be the "?" in function name)
![image](https://user-images.githubusercontent.com/5759755/75260605-2866a200-57ea-11ea-9944-0c3277236ffe.png)

**Comment by PEZ** [comment]
I think I have found a workaround that fixes both these. Will post a VSIX here later today. (Or if @kstehn beats me to it 😄 )

**Comment by PEZ** [comment]
I have now found the root of the problem and will try to fix that, rather than employ that workaround.

**Comment by PEZ** [comment]
Please update to v2.0.78. This issue should have been fixed.
