### ISSUE TITLE
[Feature request] Add a setting to hide "Calva says..." window when connecting to nREPL

### ISSUE THREAD

**Issue by mkarp** [BetterThanTomorrow/calva#568]
It would be great to have a setting to hide "Calva says..." window by default after establishing a connection to an nREPL server. I find the status bar items indicative enough about the status of the nREPL connection.

There's always a possibility to open this window in order to debug connectivity problems. When the initial setup is completed, I don't find any useful information in the "Calva says..." window, and it takes a mouse click to dismiss it.

Thanks in advance!

**Comment by PEZ** [comment]
Thanks. We'll consider the implications. The output window has several tasks, amongst them:

1. It's central in guiding new users through the REPL startup and connection process
1. Messaging about changes to Calva
1. Showing the results from evaluations and their printing side effects.

The last one is probably the most important once someone is up and running. It makes me curious that you do not find useful information there. How do you consume the results of evaluations?

**Comment by mkarp** [comment]
@PEZ Regarding evaluations, I usually have them printed out in the REPL window.

**Comment by bpringe** [comment]
@PEZ I think this relates back to our discussion on a new repl experience and a single place for output (aside from the editor annotations). Just noting that here for later.

**Comment by PEZ** [comment]
This setting has been added. So closing.

**Comment by mkarp** [comment]
Thank you so much @PEZ!
