### ISSUE TITLE
Automatically sync namespace in repl terminal to file

### ISSUE THREAD

**Issue by LukeDefeo** [BetterThanTomorrow/calva#58]
Hey guys i have been enjoying watching this project grow and would like to contribute, im just going to dump my ideas for how the ux could be improved and ill try and implement the simplest ones over the coming weeks if you think they make sense. Anyway firstly....

You added a nice switch current repl namespace to the current file command. This is handy but it would be even better if whenever the active window changes and it starts with a valid ns form it automatically does this

**Comment by PEZ** [comment]
This should at least be an setting, and possibly default to your suggested behaviour. I wonder how other tools do this?

**Comment by PEZ** [comment]
Forgot to say that I am happy that you like Calva and even happier that you are considering to contribute to its development. Welcome!

**Comment by PEZ** [comment]
This is implemented since a while ago.
