### ISSUE TITLE
Cant load the current file into Calva

### ISSUE THREAD

**Issue by brentbrinkley** [BetterThanTomorrow/calva#583]
I get this error when trying to load the current file into calva

> Command 'Calva: Load Current File and Dependencies' is not enabled in the current context

The keybindings wont work for me so I'm doing this from the command palette.

**Comment by PEZ** [comment]
Hello!

Sometimes Calva doesn't start it's activation until you open a Clojure file (.clj, .cljs, .edn). Could that apply to your case there?

It could also be that something crashes in the activation process. Bring up the VS Code Developer Tools, from the Help menu and see if the console has any clues.

I'm sorry for the inconvenience!

**Comment by brentbrinkley** [comment]
Hi, 

Thanks for getting back to me. I'm inside of Leiningen project when attempting to load this file. The file in question is a core.clj file. The dev tools console doesn't seem to yield any useful info in this case.

**Comment by PEZ** [comment]
Have you jacked in to the project?

**Comment by brentbrinkley** [comment]
I am so mad that that actually worked. I assumed that loading the file in would automatically jack in to the repl

**Comment by PEZ** [comment]
😄 I'm happy it worked!

You put the finger on an important thing. Even if it might not be feasible to start jack-in automatically, Calva should do something much more helpful than just let the keybindings feel dead and give cryptic error messages. At the very least pop up a message telling you to connect your REPL.
