### ISSUE TITLE
Var quoted symbols are treated as reader tags

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#584]
![image](https://user-images.githubusercontent.com/12722744/76575171-a0d09280-647b-11ea-8147-62a6acfe36e5.png)

In the example above you can see the first two var quoted symbols are colored the same as the next open token - `[`. If I place my cursor just inside the `[` on line 20, then run forward down sexp, the cursor goes inside the `[` on line 22.

**Comment by PEZ** [comment]
Thanks! It should be fixed on `dev` now. Pleas have a look at that commit and let me know if it looks good to you.
