### ISSUE TITLE
Double Parentheses

### ISSUE THREAD

**Issue by gambledrum** [BetterThanTomorrow/calva#587]
I’ve noticed that the Paredit behavior is odd using Calva on VS Code. What I mean is this:
When I type a double quote, then type a word, and then type double quote again, two double quotes appear. For instance, if I type the following at the keyboard:
(println “Hello!”)
it actually comes out
(println “Hello!”"))
It makes it virtually impossible to use Calva. Paredit mode (emacs) doesn’t work like this.

This behavior ONLY happens in the Calva REPL, not in the editor.

**Comment by PEZ** [comment]
Thanks for reporting! I'll have a look at it.
