### ISSUE TITLE
Sort requires alphabetically without removing unused requires

### ISSUE THREAD

**Issue by dani-mp** [BetterThanTomorrow/calva#598]
Calva’s `clj-kondo` helps me detect when a require is not alphabetically sorted, but I’d love if Calva formats this automatically when I save the file, can it be done?

**Comment by dani-mp** [comment]
There's some work done already here: https://github.com/immoh/nsorg/

**Comment by il-tmfv** [comment]
A good thing to have, but, please make it configurable via settings. I mean `Format on save` part.
Autoformat might make things harder if you want to keep your PR cleaner.

**Comment by PEZ** [comment]
I think the first step here would be to make it on demand. So when you see kondo complain about this, you can issue the command to clean it up.

**Comment by dani-mp** [comment]
I guess a nice goal could be that it plays nicely with the linter. This past couple of years I've worked in several JavaScript projects and ESLint and Prettier would respect/help each other so there are no conflicts between their configurations.

**Comment by borkdude** [comment]
Yes please!

**Comment by borkdude** [comment]
For reference, Emacs ` clojure-mode` has this as `clojure-sort-ns`:

https://github.com/clojure-emacs/clojure-mode/blob/da9f1ec717dac1194404b4a4562dba6bd9a4ee3a/clojure-mode.el#L1848

**Comment by bpringe** [comment]
It seems this might be the best path: https://github.com/clojure-emacs/refactor-nrepl#clean-ns

**Comment by bpringe** [comment]
I believe we can soon do this via clojure-lsp :tada:

**Comment by bpringe** [comment]
This has been released. See the `clean-ns` refactoring: https://calva.io/refactoring/#commands

**Comment by borkdude** [comment]
@bpringe With all respect, clean ns is not the same as just ns sorting. I don't want a tool to remove requires automatically for me, to be honest.

**Comment by bpringe** [comment]
Oh, my apologies. Reopening this.

**Comment by dani-mp** [comment]
Remove requires automatically can be super useful, but it's true that if it's happening on save, it can get in the middle of your workflow.

**Comment by bpringe** [comment]
To be clear, `clean-ns` is only run manually via a command, currently.

**Comment by borkdude** [comment]
Coming from emacs, I like that you have just `clojure-sort-ns` which isn't that intrusive as something which rewrites your ns form. So it would be nice if we could also have that option, while `clean-ns` does this and more.

**Comment by PEZ** [comment]
@ericdallo is the [clojure-lsp extra command](https://clojure-lsp.io/features/#clojure-lsp-extra-commands) sort-clauses the way to do this? It seems to work if I with the cursor outside the `(:require ...)` form do **Quick Fix** and select **Sort List**. But maybe it really just “ seems” to work. 😄

**Comment by ericdallo** [comment]
@PEZ I never tested with require form because clean-ns most of the time is enough for most people and me, but seems like it should work as well 😆, and maybe we could improve it if we find anything not working as seems to makes sense to live in that code action.
Said that, I'd say we have already a working command/code-action that does what OP wants

**Comment by PEZ** [comment]
Thanks, @ericdallo. I'll close this for now then, as being implemented via the **Sort List** quick fix. We can reopen or open a new issue if we see that we need something more than this.
