### ISSUE TITLE
Doesn't pick up leiningen on Windows 10 (release, not WSL)

### ISSUE THREAD

**Issue by yatesco** [BetterThanTomorrow/calva#599]
I have leiningen installed and can build the project from cmd or powershell, and leiningen reports as 2.9.3. 

If I connect Calva to a repl running in a normal terminal then it connects and can eval forms, but it can't find any symbol information and neither does it appear to have loaded any namespaces (probably because I _don't_ have the REPL plugins in my `project.clj`).

If I try and jack in from Calva then the following error appears:
```
> Executing task: C:\Windows\system32\cmd.exe /d /c lein update-in :dependencies conj [nrepl"0.6.0"] -- update-in :plugins conj [cider/cider-nrepl"0.23.0"] -- update-in [:repl-options^ :nrepl-middleware] conj '["cider.nrepl/cider-middleware"]' -- with-profile +dev repl :headless <


C:\Users\colin\.lein\self-installs\leiningen-2.9.1-standalone.jar can not be found.
You can try running "lein self-install"
or change LEIN_JAR environment variable
or edit lein.bat to set appropriate LEIN_JAR path.

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Note that it is referring to 2.9.1 instead of 2.9.3, but `LEIN_JAR` and `LEIN_VERSION` aren't being overridden.

Help :-)

**Comment by yatesco** [comment]
never mind - I had an errant `lein.bat` in the project root (blush)

**Comment by PEZ** [comment]
Glad you solved it! I'm surprised that Windows picks up a local `lein.bat` when you run `lein`.
