### ISSUE TITLE
Equivalent of Intellij show parameters (cmd+p)

### ISSUE THREAD

**Issue by LukeDefeo** [BetterThanTomorrow/calva#60]
One feature i notice lacking in the intelli-sense is displaying the expected params to function

I get auto completion and documentation in line like so:

![image](https://user-images.githubusercontent.com/2492575/44093351-3ab80f94-9fcb-11e8-8daa-5d62dd91ddc0.png)

But it would be nice to have the different arity's of the methods show up when the cursor is in the arguments position (ie after you have selected a specific function), something like this:

![image](https://user-images.githubusercontent.com/2492575/44093466-8adf4956-9fcb-11e8-828e-5e8014f6ffa1.png)

**Comment by dabrazhe** [comment]
The new developer release 2.0 show the parameters in hints but only in the Calva's repl pane. It needs to be integrated with the **main** code editor pane.
Below is the repl screenshot, which is what would be good to have.




![image](https://user-images.githubusercontent.com/24795958/56862182-74697000-69a8-11e9-8895-09e9e9f47418.png)

**Comment by PEZ** [comment]
Yes, this should be much easier to fix now that most of the work is done for the repl window.

**Comment by cfehse** [comment]
This is fixed with version 2.0.49.
