### ISSUE TITLE
Weird expand selection behavior near an anonymous function

### ISSUE THREAD

**Issue by hindol** [BetterThanTomorrow/calva#600]
Legend: cursor `|`, selection `<>`

```clojure
(filter even? (map #|(* % %) (range 10)))  ;; Cursor between # and (
(filter even? (<map> #(* % %) (range 10))) ;; Ctrl+w selects the previous form instead
```

I expect it to select the anonymous function instead.

**Comment by PEZ** [comment]
Thanks. Not good. But recently I covered the `currentForm` handling with tests, and it should be reasonably straightforward to add the test for this and fix it. I could be wrong, but my gut feeling is the it is these tests that lack a case or two:

https://github.com/BetterThanTomorrow/calva/blob/dev/src/extension-test/unit/cursor-doc/token-cursor-test.ts#L82
