### ISSUE TITLE
Does not format on save

### ISSUE THREAD

**Issue by MetaMmodern** [BetterThanTomorrow/calva#603]
Here is my problem. When REPL is running and i change my .clj file and save it, a little window pops up saying it tries to format the file before saving. And this process is not finishing. If i press "Отмена" (Cancel in English) it only saves the file without formatting. That's okay for me, but the REPL freezes and doesn't do anything, no response feom the command line.
![image](https://user-images.githubusercontent.com/42899786/79040952-cbd21180-7bf4-11ea-8485-155a7c877c7f.png)
What can I do with it?

**Comment by bpringe** [comment]
@MetaMmodern Is this still an issue for you? Can you provide a repro case, such as a code file that would cause this issue? It may have something to do with the code in the file.

**Comment by MetaMmodern** [comment]
> @MetaMmodern Is this still an issue for you? Can you provide a repro case, such as a code file that would cause this issue? It may have something to do with the code in the file.

No, no
I've understood the problem. I think you should add the info below to the documentation.
If you have a mistake with bracket( (), {}, []), then when saving, calva won't be able to propperly format your file. That's why it is formatting it forever. If this happens, just cancel the formatting, find the mistake, reduce it and save again.
