### ISSUE TITLE
FR: Add option to retry repl connection when its disconnected, (not intentionally closed)

### ISSUE THREAD

**Issue by jwhitlark** [BetterThanTomorrow/calva#609]
Frequently when developing with containers, I'll have a repl that is port-forwarded from vscode to a container (in Kubernetes or elsewhere).  When the container is killed for things that can't be reloaded, I'll be disconnected and have to go through the "connect to repl already running, specify host & port" dance.  This happens often enough during development that I frequently don't have a repl when I need it.

I think a nice feature would be a calva config value, something like retryOnDisconnectedRepl, that when the disconnect isn't triggered by the user, calva would attempt to reconnect to the repl, using the settings from the original connection.  This should work with both jack-in and connect to already running repl, and should have both a backoff and maximum number of retries.  (every 5 seconds, three times, perhaps?  configurable?)

**Comment by PEZ** [comment]
If we can find a way where we can avoid this adding a configuration, we should, I think. Just keep retrying every second until the user attempts a manual connect/jack-in, maybe?

**Comment by jwhitlark** [comment]
I'd want to give up at some point.  Maybe exponential backoff for 10 minutes?  A manual reconnect should kill the timer.  I'd be weirded out if a repl connected 30 minutes after I thought it was dead.

I don't suppose there's some way in the UI to add and auto-reconnect option?  Then we wouldn't have to guess.

**Comment by PEZ** [comment]
I think this will be a bit complicated to make work right. The latest Calva release made it possible to configure away a lot of the ceremony involved with reconnecting a REPL, so there should be less leverage from this feature now.
