### ISSUE TITLE
Implement `Go to symbol in file`

### ISSUE THREAD

**Issue by slipset** [BetterThanTomorrow/calva#612]
There is a `Go to symbol in file` which one can invoke in VSCode.
Unfortunately it shows nothing in Calva. It would be nice if this showed all the symbols in the current file

**Comment by max-reify** [comment]
It'd be nice to get the "Go to symbol in workspace" feature as well. I'm adding this here rather in a new issue since the solution to both issues is likely identical.

**Comment by bpringe** [comment]
These now work in version 2.0.137, thanks to clojure-lsp.
