### ISSUE TITLE
Hide Calva commands in editor context menu when editorLangId is not Clojure

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#615]
![image](https://user-images.githubusercontent.com/12722744/79621697-27a30b80-80c9-11ea-9c66-72f14fa24e04.png)

The above context menu was opened from a non-clojure file (.txt). We should use `when` clauses in the package.json menu contributions to not show these commands when the editor lang is not Clojure.

https://code.visualstudio.com/api/references/contribution-points#contributes.menus

See the docs for the difference in `when` and `enablement`.

**Comment by adairdavid** [comment]
Hi! I was wondering if I could help out by taking this on as my first issue in Calva?

**Comment by bpringe** [comment]
That would be great! Please see the wiki guide for [how to hack on Calva](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva).

**Comment by PEZ** [comment]
I think this should stay open until it is merged onto master (released, that is).

**Comment by bpringe** [comment]
Got it! My bad.
