### ISSUE TITLE
Leiningen profile parsing at Jack-in croaks on `#=()`

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#617]
Inline evaluations in `project.clj` causes Calva to give up on parsing the file and Jack-in fails.

The problem here is that in `parser.cljs` we use `cljs.tools.reader/read` which throws on the inline evaluation reader macro (`#=`). I know [this is not a supported feature of the reader and should not be used](https://www.reddit.com/r/Clojure/comments/g1zhk0/how_do_people_feel_about_using_in_production_code/fniklce/), but we should make Calva resilient to this.

I think that one way might be to consider the `(defproject ...)` form be EDN and use our EDN parsing for this instead, which does not croak on the inline eval reader macro. But I am not sure that is safe either...

**Comment by bpringe** [comment]
It looks like this was fixed by #778. Please reopen if I misunderstood.
