### ISSUE TITLE
Problems Editing a Bare file (instead of directory)

### ISSUE THREAD

**Issue by Gnurdle** [BetterThanTomorrow/calva#622]
@pez: I think Calva is deeply assuming there is a project folder. It might be some work to get rid of that.

It appears that the calva plugin isn't initialized when editing a file rather than a folder.  The problem does not occur when a folder is opened, just a plain file.

Steps to reproduce:
cd /tmp && mkdir fun && cd fun
calva -n fun.clj

type: '(', ')', '<backspace>'

you will receive a complaint about missing paredit bits.

calva -n . 
open fun.clj in the file browser.
all is good

**Comment by Gnurdle** [comment]
the 2.0.98-fix-open-bare-file build is much better.  Happy to close this.

**Comment by PEZ** [comment]
Cool. Thanks for testing! Leaving this open until the fix is released.
