### ISSUE TITLE
Unreadable active item in suggestion popup (REPL window)

### ISSUE THREAD

**Issue by zelark** [BetterThanTomorrow/calva#623]
If one uses a light theme, an active item in suggestion menu is completely unreadable.
![calva-repl-before](https://user-images.githubusercontent.com/2854582/80233057-8f73cc00-865e-11ea-9d75-d5650ab7229d.png)

A local hack to fix it is to put it in `settings.json`
```
  "workbench.colorCustomizations": {    
    "list.activeSelectionBackground": "#d6ebff"
  }
```

![calva-repl-after](https://user-images.githubusercontent.com/2854582/80233694-951de180-865f-11ea-8f4b-5436f75e358b.png)

To fix it globally I'd suggest to use `editorSuggestWidget.selectedBackground` and `editorSuggestWidget.highlightForeground` instead of `list.activeSelectionBackground` and `list.highlightForeground` respectively ([webview.scss](https://github.com/BetterThanTomorrow/calva/blob/master/assets/styles/webview.scss)). Then it will work for both dark and light default themes

**Comment by PEZ** [comment]
Great suggestion! PR?

**Comment by zelark** [comment]
@PEZ Ok, I will do this weekend.
