### ISSUE TITLE
Keep inline evaluation results until dismissed or the evaluated code is deleted

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#63]
Currently when evaluating code and showing the results inline the results disappear when the selection changes/cursor is moved.

Other editors/plugins let the evaluation results stay and you can evaluate some other piece of code and have those results displayed inline too.

This would call for another way for the user to be able to dismiss the results.

**Comment by mikeball** [comment]
I would love this feature!

**Comment by PEZ** [comment]
This will have to do this time around. (Releasing within the hour.)

![sticky-inline-evals](https://user-images.githubusercontent.com/30010/47824720-78f0fb00-dd6e-11e8-853c-4412895901e3.gif)

1. Inline results remain displayed until you dismiss them all by pressing `ctrl+escape`.
1. If an evaluation overlaps with a currently displayed one the new one will replace the older one.(It got really messy without this constraint.)

**CAVEAT**: Only the last result is evaluated each time. Meaning that previously evaluated forms might display something that is no longer true. (Re-evaluating old evaluations is non-trivial because reasons.)
