### ISSUE TITLE
clj-kondo was not found in the classpath

### ISSUE THREAD

**Issue by jorda0mega** [BetterThanTomorrow/calva#639]
getting the following error when starting a REPL connection to the project. any ideas on how to fix?

![image](https://user-images.githubusercontent.com/484084/81320627-7eb05680-905f-11ea-9a92-86b6c1a712e4.png)

**Comment by PEZ** [comment]
What kind of project is it? shadow-cljs?

**Comment by jorda0mega** [comment]
@PEZ yup. shadow-cljs

**Comment by winterscar** [comment]
Chipping is just to say I'm having the same issue. About my runtime environment:
OS: `Windows 10`
VS Code: `Latest`
Calva: `Latest`
Remote development: `docker container`
devcontainer.json: 
```json
{
	"name": "Clojurescript Development",
	"image": "clojure:openjdk-14-tools-deps-alpine",
	"forwardPorts": [8700, 8777, 9630],
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/ash"
  },
	"postCreateCommand": "apk update && apk add git openssh npm && npm i",
	"extensions": ["betterthantomorrow.calva"]
}
```

**Comment by bpringe** [comment]
This is likely caused by the recent addition of debugger decorations. If you're not using Calva's jack-in, and you're connecting to a REPL without clj-kondo loaded as a dependency, you will get that warning.

@PEZ I think we need to document that dependency in the debug docs and maybe elsewhere, so that if someone wants the feature but is not using jack-in, they know how to load the dep. But also, do you think we should remove the warning message? I initially added it so that users would know why a feature they may try to use does not work, but it seems it may cause unnecessary concern.

**Comment by jorda0mega** [comment]
@bpringe I've been connecting using jack-in though but I guess I can check if clj-kondo is in the dependencies

**Comment by bpringe** [comment]
@jorda0mega That's interesting, there could be an issue there. The calva jack-in command adds clj-kondo as a dependency, so it should be there. When I run jack-in I see 
```
> Executing task: clojure -Sdeps '{:deps {nrepl {:mvn/version "0.6.0"} cider/cider-nrepl {:mvn/version "0.23.0"} clj-kondo {:mvn/version "2020.04.05"}}}'  -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]" <
```
in my terminal. Do you see clj-kondo in your terminal when you jack-in too? If you do and then you still get that warning, something weird is going on. If you can provide a repro project that might help.

**Comment by winterscar** [comment]
I am seeing [this issue](https://github.com/BetterThanTomorrow/calva/issues/635) as well, perhaps they are related?

**Comment by jorda0mega** [comment]
@bpringe the project is https://github.com/athensresearch/athens. I realize the project is actually lein + shadow-cljs. However, if I try to jack-in with lein + shadow-cljs it just hangs.

![image](https://user-images.githubusercontent.com/484084/81611735-92cebd80-93a9-11ea-8be5-8600da86ba16.png)

I am able to start up the local server by jack-in with just shadow-cljs but then I get the clj-kondo warning

**Comment by bpringe** [comment]
@jorda0mega When I try to jack-in to that project with lein + shadoiw-cljs I do see it hanging like you say, and I also see the error from the issue @winterscar linked to in the Tasks output, so I think that is related to that issue. We'll need to follow up on that separately. I have a fix coming that will remove this warning as a window message and also fixes a sort of related issue.

**Comment by bpringe** [comment]
v2.0.100 is out now and should remove this window warning. Thanks for the feedback!

**Comment by jorda0mega** [comment]
that did it. thanks so much for looking into this!

**Comment by bpringe** [comment]
No problem! Thanks for assisting with making Calva better!
