### ISSUE TITLE
Stopping auto comments

### ISSUE THREAD

**Issue by sirmspencer** [BetterThanTomorrow/calva#644]
How do I stop the newish feature that continues the comment level on return?

For example if I return after this line, it add more comments automatically.
```
;; Add title comment
```
After return
```
;; Add title comment
;;
```

**Comment by bpringe** [comment]
@PEZ Is there a way to disable? I'm guessing we need to add a setting for this. It has annoyed me too recently :smile:

**Comment by sirmspencer** [comment]
It certainly can be a neat feature but I dont want it way more often than I do.  Maybe change it to a paredit key stroke?

**Comment by PEZ** [comment]
What I do is use **Undo** when I don't want the continuation. There's a flaw with that stil where we don't put an undo-step before we add the semi-colons, making any auto-indentation undone as well, but that can be easily fixed.

I'm always default against settings. 😄 But, yeah, if the auto-continuation annoys you, I would merge a PR which adds a setting for if the behaviour is wanted or not.
