### ISSUE TITLE
Backspace and enter keys stop working

### ISSUE THREAD

**Issue by mishari** [BetterThanTomorrow/calva#648]
Using Clava 2.0.101 on OSX

sometimes I would type (println "hello world") and discover that I cannot press enter, at the same time I cannot press backspace, alt-up either. I find if I switch applications, come back, it starts working again.

This seems to happen straight after I load current namespace in REPL window.

**Comment by PEZ** [comment]
Is it in the REPL Window this happens?

**Comment by mishari** [comment]
> Is it in the REPL Window this happens?

That's right

**Comment by borh** [comment]
To add another datapoint, I have just have this happen editing deps.edn (no REPL, but using VSCode via remote ssh editing) on latest Calva on Linux (VSCode 1.45.1, Calva 2.0.101). Actually, both backspace and delete were not working, though enter was. Restarting fixed the problem, so I'm not sure I can further debug.

**Comment by PEZ** [comment]
Closing this, since the old repl window is no more.
