### ISSUE TITLE
Prevent extra closing brackets in strict mode

### ISSUE THREAD

**Issue by gerred** [BetterThanTomorrow/calva#650]
Currently, if you open a form, the editor gives you the closing bracket as expected:

`()`

However, in either mode, you currently can add more closing brackets to this. These brackets are then not deleted (despite there being no form to balance) unless you perform a force delete:

`()))))]])} ; backspacing or deleting over these will not remove the unbalanced trailing brackets!`

Should this automatically work in strict mode? I go back and forth on this, as force delete gives me a mechanism to still do what I want.

**Comment by PEZ** [comment]
My gut thinks it makes sense that strict mode prevents this unbalance to enter. Force delete is easy to use and all, but it should be a last resort and not against something Calva has almost helped happen.

Is there a case where someone would want to add extra closing brackets? If it is not a common case that someone could use Cave Man mode to enter them and then switch back to Strict, right?

**Comment by PEZ** [comment]
I added the `fun-task` label, because I think this would be pretty entertaining to implement. I'm available to help get you started via Zoom or something if you want to take it on.
