### ISSUE TITLE
Formatting a specific file causes some shortcuts to stop working

### ISSUE THREAD

**Issue by metehan** [BetterThanTomorrow/calva#651]
[ledger.zip](https://github.com/BetterThanTomorrow/calva/files/4641501/ledger.zip)

Issue Type: <b>Bug</b>

I can format any file without a problem but attached file can't be formatted with "Fortmat File" shortcut.  After pressing ALT+SHIFT+F on this file shortcuts stops working on same workspace including CTRL-C, CTRL-V (Copy paste is still possible with command palette.)

Extension version: 2.0.101
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.96GB free)|
|Process Argv|D:\Dev\Spill\spill_cljs|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by PEZ** [comment]
I can reproduce it. Very interesting. Thanks for reporting! This must be fixed.

**Comment by PEZ** [comment]
Something with that file makes a regex match spin away. It might prove really tricky to fix properly, but I'll keep looking a bit at it.

One thing I've noticed is that it doesn't happen if I first format the `new-record` function. Which makes it all extra strange to me, but maybe it can make the file a bit ”safer” for you to work with.

**Comment by metehan** [comment]
Thank you. I am surprised that you could reproduce it I thought it's some edge case only happens on my pc. Thanks for the tip about `new-record` function, It's really strange
