### ISSUE TITLE
Feature request: navigation for re-frame projects

### ISSUE THREAD

**Issue by dbunin** [BetterThanTomorrow/calva#655]
## Problem

It would be great if navigation in `re-frame` between events would be as easy as navigation between functions. Eg point click on keywords/qualified keywords navigates you to the definition of the event/sub. 

## Possible Solutions
This functionality already somewhat exists in emacs with the help of [re-jump](https://github.com/oliyh/re-jump.el), or to a lesser extend using the [dumb-jump](https://github.com/jacktasia/dumb-jump).

### Re-jump approach
Re-jump leverages the cider to resolve the namespace, go to the file and find the snippet with 
```clojure
(reg-...
  ::search-term...
```

We can probably also extend this implementation to search for, for example, spec definitions.

### Dump-jump approach
Dump jump uses grep to search the project file for the occurrences of `::search-term` and `::foo/term` and just shows you all the results.

With this way, calva doesn't limit itself to the implementation detail of the re-frame or spec, so it can find all the possible definitions. Disadvantage being that there are a lot of false-positive, and this can be achieved with a simple project-wide regex-search. I think this still improves the navigation in the project imo, as calva can write the regex for the user.

Maybe we can extend this with limiting the files to include to the file that matches the imported namespace with alias `foo`.

**Comment by PEZ** [comment]
I love this suggestion. And I like the re-jump approach the best. VS Code already has super awesome multi-file search, so dumb-jump wouldn't add much (if I understand things correctly).

**Comment by bpringe** [comment]
Cloure-lsp has this functionality now and it's available by default with Calva. CC @ericdallo

I think it covers what is requested here. @dbunin, maybe you can confirm this?

**Comment by dbunin** [comment]
yeah it does, sorry missed your @
