### ISSUE TITLE
Can’t disable format on paste

### ISSUE THREAD

**Issue by roryokane** [BetterThanTomorrow/calva#656]
Issue Type: <b>Bug</b>

Open your VS Code `settings.json` using the “Preferences: Open Settings (JSON)” action and add these settings:

~~~json
  "editor.formatOnPaste": false,
  "editor.formatOnSave": false,
  "editor.formatOnType": false,
  "clojure.format.enable": false,
  "calva.fmt.formatAsYouType": false,
  "calva.fmt.newIndentEngine": false,
~~~

Then open a new file, enable the Clojure language mode, and try pasting this code:

~~~clj
(deftest combine-adjacent-strings-tests
  (are [x y] (= x (combine-adjacent-strings y))
    []
    , []
    ["some text"]
    , ["some" " " "text"]
    ["some text" [:link] "around a link"]
    , ["some" " " "text" [:link] "around " "a link"]
    [{:something nil} "more text" [:link] "between elements" 39]
    , [{:something nil} "more" " " "text" [:link] "between" " " "elements" 39]
    [{:a 1 :b 2} 3 ["leave" "intact"]]
    , [{:a 1 :b 2} 3 ["leave" "intact"]]))
~~~

I want the code to be pasted as-is. But instead, the commas are automatically removed:

~~~clj
(deftest combine-adjacent-strings-tests
  (are [x y] (= x (combine-adjacent-strings y))
    []
    []
    ["some text"]
    ["some" " " "text"]
    ["some text" [:link] "around a link"]
    ["some" " " "text" [:link] "around " "a link"]
    [{:something nil} "more text" [:link] "between elements" 39]
    [{:something nil} "more" " " "text" [:link] "between" " " "elements" 39]
    [{:a 1 :b 2} 3 ["leave" "intact"]]
    [{:a 1 :b 2} 3 ["leave" "intact"]]))
~~~

I tried specifying only a subset of the preferences `clojure.format.enable`, `calva.fmt.formatAsYouType`, and `calva.fmt.newIndentEngine`, but got the same results.

The code is properly left unformatted after paste if I disable the Calva extension.

Extension version: 2.0.101
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 18.7.0

**Comment by PEZ** [comment]
Try with:

```json
    "[clojure]": {
        "editor.formatOnPaste": true
    }
```

**Comment by PEZ** [comment]
Not sure if that disables other `[clojure]` defaults that Calva sets. See https://calva.io/customizing/#clojure-defaults

**Comment by roryokane** [comment]
Thanks. I think you accidentally wrote `true`, but after I changed it to `false` it fixed my problem:

~~~json
  "[clojure]": {
    "editor.formatOnPaste": false,
  },
~~~

With this, Clojure code is not formatted on paste even with Calva enabled.

**Comment by PEZ** [comment]
Haha, yeah. True that it should be false. 😎
