### ISSUE TITLE
cannot change prompt

### ISSUE THREAD

**Issue by gabrielash** [BetterThanTomorrow/calva#657]
With Calva 2.0.101

I tried adding 
`:repl-options { :init ....  :prompt .... } `
in my lein user profile, in project.clj and in dev profile. 
:init works but :prompt has no effect.

**Comment by PEZ** [comment]
Is this about the REPL Window prompt?

**Comment by gabrielash** [comment]
I'm using vs code on windows, but developing remotely on a debian box. the REPL is inside vs-code. I have no clojure installed locally.

**Comment by bpringe** [comment]
Are you referring to the prompt inside the repl window? If so, this is not the same as `lein repl` and does

**Comment by gabrielash** [comment]
Yes.  So I understand that you mean it is the expected behavior for calva repl windows to ignore the 
:prompt :repl-option in defproject or in a profile ? 

The reason I want to change the prompt is because my window is sometimes narrow and I would like to insert a LF to have the full line available when I start writing. It would be nice if calva noticed that the user has customized the prompt and passed it through.

**Comment by bpringe** [comment]
Yes, that's what I mean, basically. I'm not sure if Calva has access to that from the nrepl session started by lein, but seems like it would. 

There may be a new repl experience coming down the line that gets rid of the repl window (the experience will be improved). I'll label this issue so we remember to address when we get to that feature, if not before. Thanks for the suggestion/feedback. Also feel free to add a PR if you're so inclined :smiley:.

**Comment by PEZ** [comment]
I don't see us trying to interpret prompt settings from different build
tools/project settings.

I would, however, totally consider always adding a newline after the
prompt. It can get really long and the repl window doesn't handle
horizontal scrolling very well.

**Comment by gabrielash** [comment]
Noted. Thanks all for your replies.

**Comment by PEZ** [comment]
The new output/repl window always adds a newline after its prompt.

**Comment by alexamy** [comment]
Why to add non-breaking space (U+00A0) after prompt before newline?

**Comment by PEZ** [comment]
It's because we want a space between the cursor and the prompt. Someone was using an extension that highlighted trailing spaces (#808) so we changed to a non-breaking space.

**Comment by alexamy** [comment]
I have [extension](https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins) that highlights unprintable characters, like NBSP.  :grin: 

It's not a problem, though. Thanks for explaining.

![image](https://user-images.githubusercontent.com/596195/108050796-2630cf80-705b-11eb-8388-86a2f2ad8108.png)

**Comment by PEZ** [comment]
Omgwtflol. I'll keep this highlight issue in mind when I put some prompt work in next time.

We're discussing some  other prompt things here #1033 . Feel invited to chip in there!
