### ISSUE TITLE
Requires not taking effect in Calva Repl when running Shadow-CLJS for the :node-script target

### ISSUE THREAD

**Issue by alpox** [BetterThanTomorrow/calva#661]
Calva Version: **2.0.102**
Shadow-CLJS Version(s): **2.10.0** / **2.10.1** / **2.10.2**

When running the Shadow-CLJS REPL in the Terminal `(require '["crypto" :as crypto])` works and `crypto` can be referred to. However, this does not work for the Calva REPL whether by evaluation through the editor nor directly in the REPL.

Current workaround: Downgrade Shadow-CLJS to 2.9.10 for now.

**Comment by alpox** [comment]
This is fixed with shadow-cljs **2.10.3**

**Comment by PEZ** [comment]
Awesome!
