### ISSUE TITLE
Reader tag highlighting/coloring incorrectly triggered by var quote

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#663]
![image](https://user-images.githubusercontent.com/12722744/83909332-6e9e9c00-a71d-11ea-97b4-dd46fecf79c4.png)

Here the var quote `#'print-and-wait` is highlighted/colored to match the opening character of the next form - as if the var quote were a reader tag describing that form.

@PEZ I think this is your area of expertise :smile:.

**Comment by PEZ** [comment]
Ah. that's not good at all. Wanna tackle it?
