### ISSUE TITLE
Janky behaviour while typing

### ISSUE THREAD

**Issue by orestis** [BetterThanTomorrow/calva#673]
I posted this in Slack and want to preserve here so that it doesn't get lost:

![ezgif-com-crop](https://user-images.githubusercontent.com/9217/84750675-e68d8180-afbb-11ea-9791-1d09a003bfce.gif)

There's two issues here:

1. The flickering (showing, then hiding) of the bracket highlights as you type
2. Typing a character in `require` starts off as blue then quickly turns red.

I have confirmed that native VSCode (with Calva disabled) doesn't exhibit any of the behaviours, but of course you get VSCode's bracket matching which is weird.

The machine this runs on is from 2014 so VSCode is a bit sluggish anyway, but I think at least the bracket highlighting could be after a short delay to make sure typing stabilises.

**Comment by bpringe** [comment]
Thanks for reporting here. I think at least with the bracket highlighting we may need to play with the debounce timing. Currently it's set pretty low (not human noticeable), but there is a short delay. See here: https://github.com/BetterThanTomorrow/calva/blob/133ad6c62f2d360d6bb54c66dfec1d3e58187615/src/highlight/src/extension.ts#L214

I'm not sure about the require coloring without digging in though. But hopefully we can find some way to smooth all of this out like you say.

**Comment by PEZ** [comment]
Debounce might help, but I think the bracket matching highlight going on looks wrong. Calva only highlights brackets when the cursor is outside. In the OP gif it seems that some highlighting is going on from the inside...

**Comment by PEZ** [comment]
So... this would happen if the highlighting was applied on the old text, with the new cursor position, right?

**Comment by PEZ** [comment]
I took @bpringe's clue about how we defer the rainbows a bit and applied to my hunch about the problem being a that we matched on the wrong version of the document. Seems to have been the right diagnosis.

Can you take this VSIX for a spin, @orestis and see what remains of the problem, if any?

https://6443-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.107-fix-flicker-matching-brackkets-a5af01c1.vsix
