### ISSUE TITLE
[Feature Request]: Add support for Figwheel configuration {:target :bundle}

### ISSUE THREAD

**Issue by Mocha--** [BetterThanTomorrow/calva#676]
Hi,

Cljs and Figwheel recently released a new feature with configuration ```{:target :bundle}```, which can generate intermediate code by Clojure Compiler that can be further processed by other frontend tools such as Webpack and Parcel.

However, when I tried to Jack-in a project with the new ```{:target :bundle}``` configuration, Calva reports a Spec Failed error. I guess at the moment Calva does not recognize this new configuration.

Please incorporate this new configuration.

Thanks,
![Screen Shot 2020-06-26 at 12 19 38 pm](https://user-images.githubusercontent.com/8860999/85813894-d3429900-b7a7-11ea-8f27-bce157ae453a.png)

**Comment by bpringe** [comment]
Thanks for reporting. I'm not sure this error is caused by Calva. It looks like this feature is only available in ClojureScript version 1.10.741 and higher. Are you using this version or higher? 

Also make sure your figwheel is at a high enough version, though I don't see anything in fighwheel's docs related to this feature. I see [this](https://figwheel.org/config-options.html#npm) but it looks unrelated.

**Comment by Mocha--** [comment]
My Clojurescript version is 1.10.773, which supports ```:target :bundle``` feature.

Please check out this link [https://figwheel.org/docs/npm.html](url).

Furthermore, please add support for :auto-bundle [https://figwheel.org/config-options#auto-bundle](url)

**Comment by bpringe** [comment]
I see. I don't think Calva itself is using spec to verify that, so it does seem that either Figwheel or, more likely ClojureScript, is throwing that error. I know you said you're using a high enough version of ClojureScript, but I'm wondering if maybe Calva is injecting a different version by chance, or doing something else which could cause this.

Going to ping @PEZ here, as he may have more insight.

**Comment by Mocha--** [comment]
I think the reason is found out. The figwheel version is hardcoded in Calva. [https://github.com/BetterThanTomorrow/calva/blob/v2.0.106/src/nrepl/project-types.ts#L156](url)

If this version could be updated to the latest, which is 0.2.9 at the moment, the problem should be solved.

**Comment by PEZ** [comment]
Gah. We shouldn't be injecting Figwheel Main at all. I thought I had removed that.

 I'm sorry for the inconvenience. Thanks for reporting and investigating it some for us!

To unblock yourself you can either:

- copy the command line used at jack in, kill the jack-in, and start the repo yourself with a fixed version of it, and then use connect instead
- fork the Calva repo, remove that injection, and run Calva in dev mode as described here: [How to Hack on Calva](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva)

The latter has the advantage that you can then send us a PR. 😄

**Comment by bpringe** [comment]
@PEZ Is this fixed? I wasn't familiar with this code before, and the link above seems to not work any more, but I don't see anywhere that we're hard-coding figwheel main in the current code base.

**Comment by PEZ** [comment]
Yes, this is fixed. Calva does not inject Figwheel and won't interfere with which version the user has configured in the project.
