### ISSUE TITLE
Jack in does not work

### ISSUE THREAD

**Issue by Nuube** [BetterThanTomorrow/calva#678]
I just installed Calva in VSCode and tried the Jack-In

"No supported Jack-in project types detected. Maybe try starting your project manually and use the Connect command?"

 (I am new to JSCode, so might be my problem)

**Comment by Nuube** [comment]
deps.edn was missing.

Would be nice when this can be added to the "getting started" information.

**Comment by bpringe** [comment]
Thanks for the suggestion! As mentioned in the calva slack channel, I created this issue for improving the docs for complete beginners. Please add any other suggestions you have to it https://github.com/BetterThanTomorrow/calva/issues/679
