### ISSUE TITLE
Cannot use default connect sequences when custom connect sequences added

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#685]
Two problems here really:

1. For my project I wanted to add some code to be run after the clojure cli repl is started. So I added a custom replConnectSequence for this with `afterCLJReplJackInCode`. This works fine, except that when I start my shadow-cljs repl in a separate terminal and try to connect, I only get the option "Clojure CLI." I see that if any custom replConnectSequences are provided, only those are presented, but it would be nice if I could select/use the default shadow-cljs connect sequence, along with my custom Clojure CLI connect sequence.

2. So this lead me to try to create a custom sequence for shadow-cljs, but alas, I cannot make it work correctly because the default shadow sequence has an object for `cljsType.connectCode` and the JSON schema for the `replConnectSequences` says it must be a string.

![image](https://user-images.githubusercontent.com/12722744/88119394-2b857480-cb75-11ea-8f4e-75c35be18494.png)

Maybe it's not meant for the end-user to add an object themselves, and is only meant to be used as an object in Calva's default connect sequences?

In any case, so long as I have custom repl connect sequences, It seems I am prevented from connecting to a shadow-cljs repl in a way that allows me to evaluate code in it.

**Comment by PEZ** [comment]
We should try make it possible to add the object. And we should make it
possible to use the default ones even in the presence of a custom sequence.
