### ISSUE TITLE
REPL window captures 2nd character of a keyboard chord shortcut

### ISSUE THREAD

**Issue by crispinb** [BetterThanTomorrow/calva#688]
If I execute a non-calva keyboard shortcut chord while in the REPL window (eg. the built-in `ctrl-k s`, or my custom `alt-k n`), the 2nd char of the chord (`s` or `n` in my examples) is unexpectedly printed in the REPL. It also triggers intellisense.

**Comment by bpringe** [comment]
I don't think keyboard shortcuts (chords especially) work as normal in the current repl window for reasons. @PEZ would know more about this.

**Comment by crispinb** [comment]
I didn't realise until reading [@PEZ's post on Clojureverse](https://clojureverse.org/t/calva-summer-of-bugs-2020/6303) that the new output window (which doesn't suffer this problem) is intended to replace the current REPL window. Given that fact, I might as well close this.

**Comment by PEZ** [comment]
For the record, this is an upstream issue: https://github.com/microsoft/vscode/issues/85879

I'm looking forward to dropping the old REPL window!
