### ISSUE TITLE
Calva will fail if no active file on startup

### ISSUE THREAD

**Issue by grav** [BetterThanTomorrow/calva#69]
If I open up VSCode like this:
```
$ cd my-cljs-proj
$ code .
```
VS Code will have the Welcome page active. If I then try to connect with Calva, I'll get the error `command 'calva.connect' not found`

It seems to be this line:
https://github.com/BetterThanTomorrow/calva/blob/562887c9ae03f263fc5ccb4a1ea7cb6efc6d0ad0/calva/utilities.ts#L60
that is the issue. Having run the debugger on Calva, I think the reason is that `vscode.window.activeTextEditor` is `undefined` when only the welcome page is showing.

Edit:
```
 $ code --version
1.26.1
493869ee8e8a846b0855873886fc79d480d342de
x64
```

**Comment by PEZ** [comment]
I think I might have solved this issue now. Please let me know if you see it anyway.
