### ISSUE TITLE
vscode command for to eval code given as args

### ISSUE THREAD

**Issue by daaku** [BetterThanTomorrow/calva#690]
It would be nice if there was a command that took code as args and essentially ran `session.eval` or something along those lines. I know there is `calva.runCustomREPLCommand`, and various existing commands operate on the selection or current top level form. But it would be nice to have a command to eval some code because then other extensions could script code execution (since many like [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros) allow for invoking commands).

**Comment by bpringe** [comment]
Interesting. Would this code be executed in the currently connected REPL?

**Comment by daaku** [comment]
Could do by default, while accepting an arg to choose between `clj` or `cljs`.
