### ISSUE TITLE
Add hover to display results for eval as window into output file

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#693]
Instead of adding the results to the hover like we have done in the past, now that we print them to an output file, I believe we can add a hover for evaluations in files, that shows a window into the section of the output file where the results were printed.

This allows the user to see results without opening the results window.

If possible it would be nice to include links to open the results window (as happens currently), as well as copy all of the text of the result (as we had with the previous implementation of hover results).

**Comment by PEZ** [comment]
What could be within somewhat easy reach is if we can make a definition provider that is aware of the active evaluation annotations. Then holding down the command-key within the evaluation range, or pressing `alt+f12` will display the relevant portion of the output file. And we could probably make a `Copy` button there as well that would pluck the result output range...


Relevant for this is also this upstream issue: https://github.com/microsoft/vscode/issues/3220
