### ISSUE TITLE
jack-in failing in 2.0.109

### ISSUE THREAD

**Issue by iljaf** [BetterThanTomorrow/calva#694]
On Windows, after upgrading to 2.0.109 clj jack-in is failing, such that the REPL window doesn't come up:
Hooking up nREPL sessions...
Connected session: clj
Failed connecting.
Jack-in done.

downgrading to 2.0.108 fixes the issue.

**Comment by PEZ** [comment]
Thanks!

I failed at testing this on Window. I'm sorry! 😢

Working on it now and have a fix ready. Stay tuned!

**Comment by PEZ** [comment]
This is now fixed in 2.0.110, @iljaf . Please take the new output window for a spin.

Again, I'm sorry about the fuck-up. I've added a checklist item to our integration process now, hopefully that should help even a tired brain from forgetting about testing on Windows...

**Comment by pedro-w** [comment]
I'm not sure if this is the same issue, please let me know and I will open a new one.
For me, doing a jack-in to a clojure project seems to connect, but it opens up a window on `output.repl-file` and not the normal interactive Calva terminal. There's no way to interact with the REPL.

The 'Calva says' output tab is
```
Calva activated.
Happy Clojure(Script) coding! ❤️
If you like Calva, please consider how you can contribute: https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute
Please check these resources out:
* Calva Documentation: https://calva.io/
* #calva at the Clojurians Slack: https://clojurians.slack.com/messages/calva/
* Bug reports: https://github.com/BetterThanTomorrow/calva/issues
--
Start the REPL with the command *Start Project REPL and connect (aka Jack-in)*.
Default keybinding for Jack-in: ctrl+alt+c ctrl+alt+j
Jacking in...
Hooking up nREPL sessions...
Connected session: clj
Debugger initialized
cljc files will use the clj REPL.
Jack-in done.
```
I'm sure it was working this morning, prior to the Calva update and possibly the VSCode update. My versions are:

* Calva 2.0.110
* VSCode 1.47.3
* Windows 10

**Comment by PEZ** [comment]
That looks like something else. Can you file it as a separate issue? If you do it using the vscode help menu, it will attach some info about your setup that could be relevant. Also if you could attach a screenshot, that could help understanding what is going on.

**Comment by PEZ** [comment]
One more thing, you should be able to open the old REPL window using the command palette.

**Comment by pedro-w** [comment]
Done (#698) - thanks for your help.
