### ISSUE TITLE
REPL tab doesn't open

### ISSUE THREAD

**Issue by pedro-w** [BetterThanTomorrow/calva#698]
Issue Type: <b>Bug</b>

I am attempting to jack-in to a minimal Clojure  (deps.edn) project. Connection is successful but the interactive Calva tab doesn't appear. Instead, a tab showing the file `output.repl-file` is shown
Previously (v2.0.108), the Calva tab did appear and the `output.repl-file` did not.
It is possible to show the Calva tab subsequently from the command palette 'Calva Open the Clojure REPL Window`

Extension version: 2.0.110
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (0.64GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

Version 2.0.110 (not correct):
![Version 2.0.110](https://user-images.githubusercontent.com/22172519/88683856-2cc21e80-d0ec-11ea-9a1f-afd79d0fffd5.jpg)
Version 2.0.108 (correct):
![Version 2.0.108](https://user-images.githubusercontent.com/22172519/88683895-377cb380-d0ec-11ea-937c-bbb6bc36a1b7.jpg)

**Comment by pedro-w** [comment]
Actually is this just the new default behaviour according to https://github.com/BetterThanTomorrow/calva/commit/d28f8b0b19fb8fcc14ba1abbcf85ea52164c8f34 ?

**Comment by bpringe** [comment]
By "the Calva tab," if you're referring to the "REPL Window" as the commands refer to it, then yes, this is the default behavior. Calva now opens the `output.repl-file` instead of the REPL Window upon jack-in. This new repl-file will eventually (maybe sooner than later) replace the REPL Window.

**Comment by pedro-w** [comment]
I am indeed referring to the REPL window. Thanks for getting back to me so quickly.
