### ISSUE TITLE
Output window sometimes getting out of synch, needing overwrite

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#699]
The output window sometimes gets out of synch with what's saved on disk. This causes it to behave strangely at times, and also annoys the user with a message about wether to revert it from disk or overwriting.

**Comment by PEZ** [comment]
I know why this is happening, and I also think I know how to fix it.

Then again, I have thought I have fixed it several times now. ¯\\_(ツ)_/¯

**Comment by bpringe** [comment]
Do we have a solid repro case? I can't repro. =/

**Comment by bpringe** [comment]
https://github.com/Microsoft/vscode/issues/7025 Related I think

**Comment by bpringe** [comment]
https://github.com/Microsoft/vscode/issues/66035#issuecomment-563156223
There is a setting to always overwrite for a given folder. I'm not sure if it can be set by Calva though, for the `.calva` folder.

**Comment by PEZ** [comment]
No solid repro. It happens now and then. But now I have fixed it by writing the greetings text using the workspace `edit` API, same as we are updating the window with, so we should get no more conflicts like this once the PR is released.
