### ISSUE TITLE
Backspace is not working properly in the output window

### ISSUE THREAD

**Issue by glebovmaksim** [BetterThanTomorrow/calva#700]
Sometimes it deletes the prompt itself. Here is the gif.

![Peek 2020-07-29 15-59](https://user-images.githubusercontent.com/22004226/88810105-95c59700-d1bd-11ea-9ae8-a53bcb5ec161.gif)

Was surprised that it actually worked on the first expression, but after trying to remove an empty brackets it started to fail every time.

**Comment by bpringe** [comment]
I'm unable to reproduce. What's your OS? And what version of Calva are you on? In version 2.0.110 backspacing through the prompt is not allowed. I also see a space being added after your evaluation result, which doesn't happen for me.

**Comment by bpringe** [comment]
I see now that you're saying the disabling of backspace is not being respected after deleting the empty list. But again, I cannot repro. =(

**Comment by glebovmaksim** [comment]
OS: Ubuntu 18.04.1. 
Calva: 2.0.110. Reinstallation did not help =(

Some additional information:
- It happens after deleting *any* empty datastruct affected by Paredit.
- Since deleting the empty datastruct is the last step of deleting every form in Paredit, the problem becomes worse.
- In Cave Man Paredit mode backspacing always work, no restrictions at all.

Sometimes it does work, but mostly not. Could it be some concurrency problem?

**Comment by PEZ** [comment]
It's interesting that the whole buffer seems to break the syntax highlighting... What other extensions are you using? I've seen **Clover** conflicting.

**Comment by PEZ** [comment]
I can reproduce this. Very interesting!

**Comment by PEZ** [comment]
When deleting the empty list, all trailing spaces in the window are deleted. My mind is blown.

**Comment by bpringe** [comment]
I can reproduce now too. Weird.

**Comment by PEZ** [comment]
And now I can't reproduce it any longer. So strange!

**Comment by glebovmaksim** [comment]
Let me show you something crazy. It's even reproducible!

![Peek 2020-07-30 19-03](https://user-images.githubusercontent.com/22004226/88946262-aea27b00-d297-11ea-8a52-be17821e0336.gif)

**Comment by glebovmaksim** [comment]
Another random weird thing. Disappeared after cleaning the file.

![Peek 2020-07-30 23-00](https://user-images.githubusercontent.com/22004226/88969613-c985e700-d2b9-11ea-9301-a042ba6f7476.gif)

**Comment by gustavobertolino** [comment]
Same behavior here : (

[](https://ibb.co/V3SdgjK)

It doesn't affect any part of my code, neither the IDE, but it something bad from the user experience point of view.

**Comment by glebovmaksim** [comment]
@PEZ, @bpringe, I've found the source of the problem. This behavior occurs because Calva formats the entire file, which happens in two cases:

- After removing any pair paranthesis (because of [this](https://github.com/BetterThanTomorrow/calva/blob/master/src/doc-mirror/index.ts#L40) and [this](https://github.com/BetterThanTomorrow/calva/blob/master/src/calva-fmt/src/format.ts#L92)). I doubt it's intentional, maybe it should be fixed. Please correct me if I'm wrong.
- By pressing tab on an empty line. This is fine in a regular file, but in the output file it deletes all trailing spaces next to prompt and breaks it. I think we should not allow to format the entire output file at all, because on a longer session it may grow to a large size, resulting in (possible) slow formatting. And it doesn't seem like a useful feature here.

I can send a pull request if you point me in the right direction to fix this :smile:

**Comment by PEZ** [comment]
Ah, yes, that makes sense! I was looking at the wrong place...

So, many paredit commands finish with formatting and probably we (implicitly or explicitly) tell the formatter to trim trailing whitespace.

Iirc there is a special case for when formatting is performed on the top level. Or, rather, for selecting what is to be formatted. A check there for if it is the output file could maybe stop this madness. Also trimming trailing whitespace is generally a bad idea in this window.

PR is super welcome. Please don't hesitate to ask us for help.

**Comment by bpringe** [comment]
@glebovmaksim Great find! Looks like you're looking in the right places already, though I haven't messed with the formatting much myself.

@PEZ Maybe when formatting, if it's the repl file, we should only format up to the previous prompt?
