### ISSUE TITLE
`figwheel-main` is added as dependency during `Clojure CLI + Figwheel Main` jack-in

### ISSUE THREAD

**Issue by il-tmfv** [BetterThanTomorrow/calva#701]
Calva injects `figwheel-main` as a dependency during jack-in process for `Clojure CLI + Figwheel Main` project type.
I think it is not necessary b/c `figwheel-main` will be present in dependencies list anyway (otherwise, how can one build a project for production?)

**Comment by PEZ** [comment]
Should be fixed now.
