### ISSUE TITLE
Use Eastwood linter instead of Joker

### ISSUE THREAD

**Issue by dijonkitchen** [BetterThanTomorrow/calva#71]
Any reasons why Eastwood can't be used instead of the Joker linter? 

https://github.com/jonase/eastwood

**Comment by jefffriesen** [comment]
Related:  https://github.com/BetterThanTomorrow/calva/issues/43

@dijonkitchen What would be your goal of switching? Can you talk about why it would be better?

**Comment by dijonkitchen** [comment]
Eastwood has a bit more interopability with Clojure and seems to be more of a standard for build processes. 

See Joker's limitations/differences here: 
https://github.com/candid82/joker#project-non-goals

**Comment by zcaudate** [comment]
@dijonkitchen: have you tried https://github.com/clojure-emacs/squiggly-clojure?

**Comment by zcaudate** [comment]
I like the joker linter, though I get quite a bit of false positives, especially for macros that it doesn't recognise. The page says it's configurable but I couldn't figure out how to do it.

**Comment by dijonkitchen** [comment]
I haven't since I've been trying out Calva in VSCode, but I've seen it before and looks cool for Emacs users!

**Comment by zcaudate** [comment]
@PEZ: sweet, I'll try it out.
