### ISSUE TITLE
A recent update now causes the output window to open and display "Calva activated."

### ISSUE THREAD

**Issue by sirmspencer** [BetterThanTomorrow/calva#710]
Version 2.0.112

Current behavior.  If I close vs code and reopen or change from a JS project back to a CLJ project, the output panel is open and it displays a message "Calva activated." with some other information. 

The expected behavior is the default behavior for VSCode.  When I re open vs code, my last configuration should be shown.  For example if I close vscode with the side bar and the panel (holds output, terminal etc) closed, and then reopen vscode, they should remain closed.

Its odd that this behavior just started and I see in the change log that it should already be fixed in 2.0.112

**Comment by PEZ** [comment]
Could the message be a left over from a session of .111?

**Comment by sirmspencer** [comment]
> Could the message be a left over from a session of .111?

The message looks like its loading each time. ie I see "Calva activated", then a half second later the rest of the message loads.

I did "clear output" and relaunched with the same message.  The output is on the channel "Calva Says", is it possible that this channel is still being output to when "Calva Connection Log" is not?

**Comment by sirmspencer** [comment]
FYI, im not on 115. I have double checked that my system and vscode are all up to date.

**Comment by bpringe** [comment]
When I close/reopen vscode with the output window previously closed, it does not open. I just see `Calva activated` in the Calva says window, and I believe this is expected. Is this not what you're experiencing?

**Comment by sirmspencer** [comment]
I had the entire panel closed, output, debug console, terminal, then closed vscode.  This is what it looked like when closing
![image](https://user-images.githubusercontent.com/33734037/89335297-115b9400-d655-11ea-8c20-8e08fd074783.png)



This is what I see when I reopen it.
![image](https://user-images.githubusercontent.com/33734037/89335141-dbb6ab00-d654-11ea-8511-c8f82106a547.png)

Maybe you have your calva says window open somewhere else so it does not open a new panel.

**Comment by PEZ** [comment]
There is a setting for if it should open or not. Very recently added.

**Comment by bpringe** [comment]
Yeah, just to clarify, this Calva says window is not the output window we are normally referring to, and the one we changed back to opening only when connecting to a repl.

So I believe what you're experiencing is expected behavior, as the setting mentioned above is defaulted to open the Calva says window on startup.

**Comment by sirmspencer** [comment]
> There is a setting for if it should open or not. Very recently added.

I see the setting for it, thanks.
