### ISSUE TITLE
Time to remove the old REPL window

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#711]
The new output/repl window is over all better than the old repl window. As fa as I know, the only three things the old repl window does better are:

* Filtered, and more readable, stack traces
* Evaluation history
* Ansi color printing

I don't think this is enough to compensate for the confusion with to different REPL window solutions and all these REPL window commands.

**Comment by madisoncfallin** [comment]
As someone with dyslexia, I preferred the old REPL for exactly these three reasons! Please add it as a legacy option.

**Comment by PEZ** [comment]
Sorry, the maintenance keeping a legacy option alive is more than we can carry. The only such option available will be to keep using version `2.0.108`.

**Comment by bpringe** [comment]
@madisoncfallin I think we can improve on this new one to get close to having or having all those features as before.,

**Comment by gustavobertolino** [comment]
Why would you do such thing like removing REPL window, guys? There are lots of developers like me who are used to it and the evaluation history is from the very beginning a reason to keep REPL window.

New output/REPL window doesn't have evaluation command history and this is very bad for us.

Please guys, give us back old REPL window

**Comment by bpringe** [comment]
For anyone who sees this later, please follow the discussion at #733.

Also, we are just a couple of guys doing much of this maintenance. Please be patient with us. :smile:

**Comment by Yunfeng-Song** [comment]
I really appreciate what you guys been doing. I hope the new REPL will get better in the future.😄
