### ISSUE TITLE
Continuously evaluating in infinite loop

### ISSUE THREAD

**Issue by danielytics** [BetterThanTomorrow/calva#712]
When I evaluate code from a source file, it evaluates it over and over in an infinite loop, printing the same results to the `output.repl-file` window. Its completely unusable.

For example, I just tried this file:
```clojure
(ns dusk.core)
(println "hi")
```

when I run `evaluate toplevel form in REPL window` on the `println` line, I see output like tis in the output window:

```
; Evaluating file: core.clj
hi
nil
clj::dusk.core=> 
; Evaluating file: core.clj
hi
nil
clj::dusk.core=> 
; Evaluating file: core.clj
hi
nil
clj::dusk.core=> 
; Evaluating file: core.clj
hi
nil
clj::dusk.core=> 
; Evaluating file: core.clj
; Evaluating file: core.clj
hi
hi
nil
nil
clj::dusk.core=> 
clj::dusk.core=> 
; Evaluating file: core.clj
hi
nil
clj::dusk.core=> 
; Evaluating file: core.clj
; Evaluating file: core.clj
hi
nil
clj::dusk.core=> 
hi
nil
clj::dusk.core=> 
```
and it just keeps looping re-evaluating it forever, eating CPU and making VSCode completely unusable until I kill the nrepl connection.

I noticed this in the latest version, but I tried older versions and found that this problem started with version `2.0.109` (108 works perfectly).

**Comment by PEZ** [comment]
Oh, oh. Does not look good at all. Do you have `evalOnSave` active? Thinking it could be something with that, that we have butchered...

**Comment by chrisfarber** [comment]
I'm experiencing this issue as well. Turning off both `evalOnSave` and `testOnSave` and restarting VSCode did work around the issue.

**Comment by PEZ** [comment]
Thanks. I'll check what's going wrong.

**Comment by danielytics** [comment]
I've tested both `evalOnSave` and `testOnSave` and have narrowed it down to `testOnSave`. It works fine with `evalOnSave` enabled, but breaks when I enable `testOnSave`. Hope that helps.

In any case, I can work around it for now by simply disabling `testOnSave` :+1:

**Comment by PEZ** [comment]
Fix is coming in a moment.

**Comment by danielytics** [comment]
Great, thanks! I can confirm that its fixed.

> TestOnSave: Check that the file saved is not the output window before loading file and running tests

Oh, wow, that's actually a pretty funny bug :smile: Glad you found and fixed it.

**Comment by PEZ** [comment]
Haha, yeah, pretty crazy.
