### ISSUE TITLE
Frustrating behavior with completion in REPL window

### ISSUE THREAD

**Issue by mtnygard** [BetterThanTomorrow/calva#719]
When entering a form in the REPL window, I often type the full function name that I want. When I hit "enter" however, my direct input gets replaced with a completion from the popup window. This is always the first suggested completion, even if I've correctly typed the full name of a function.

For example, in this screenshot, when I hit enter, I expect to evaluate `(clojure.test/run-tests)`. Instead, my input is replaced with `(clojure.test/run-all-tests)`.

![Screenshot 2020-08-01 142755](https://user-images.githubusercontent.com/116714/89109031-3789f580-d403-11ea-865b-d424d5fdddcc.jpg)

(My cursor was after the final "s" in "run-tests"... it just blinked off as I took the screenshot.)

I cannot find a setting to suppress or delay the completions popup.

**Comment by bpringe** [comment]
I've been annoyed by this as well. However, we're about to remove this repl window in favor of the new output.repl-file, which has all the features we have in the editor, and this is not an issue there. :tada:
