### ISSUE TITLE
Accessing recent results (*1, *2, *3) does not work

### ISSUE THREAD

**Issue by glebovmaksim** [BetterThanTomorrow/calva#724]
E.g. [this](https://clojure.org/guides/repl/data_visualization_at_the_repl#_accessing_recent_results_1_2_3) can't be reproduced in new REPL window.

**Comment by PEZ** [comment]
Can you elaborate some on what happens instead?

**Comment by PEZ** [comment]
Like some reproductions steps and examples. 😄

**Comment by glebovmaksim** [comment]
Here is my favourite arithmetic example  :smiley: 
![Screenshot from 2020-08-04 19-59-50](https://user-images.githubusercontent.com/22004226/89322818-7af79480-d68d-11ea-8e85-b2254a9d91e9.png)

**Comment by PEZ** [comment]
So, this now works for cljs, but not for clj. Reopening. And I think I know how to fix it reliably.
