### ISSUE TITLE
Use HoverProvider with promise to show eval results in editor - vs peek definition

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#726]
https://code.visualstudio.com/api/references/vscode-api#ProviderResult%3CT%3E

We may be able to store the location of the eval results in the output window into state (instead of the output itself to conserve memory), then return a promise from `provideHover` that reads the result from the output file and shows it in the hover on-demand. I think this might alleviate the high memory issue from the old implementation, but would need to be tested.

One issue I see with this is what happens when the output window contents at said locations are modified, or if the contents are wiped? How can we, and how can we know to, "clear" the hovers?

**Comment by PEZ** [comment]
I think the case you worry about is pretty rare and that we can disregard it. In any case, the problem is already there with the peek definition widget.

**Comment by bpringe** [comment]
Very true. Should probably let that change ride for a while and see how it goes.

**Comment by glebovmaksim** [comment]
I'll be happy to test this 🙂

**Comment by bpringe** [comment]
Closing this since results were added back to hovers.
