### ISSUE TITLE
Add ignore form command

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#727]
This form would place a `#_` before the form that the cursor is currently at.

**Comment by bpringe** [comment]
Also should include an un-ignore form command, or make one command that toggles ignore.

**Comment by PEZ** [comment]
What would be the benefit over typing the ignore token?

**Comment by bpringe** [comment]
Not having to navigate to the beginning of the form in order to do so. Simply a little less work. I can be working and in the middle of a form and think, no scratch this, and hit one shortcut to ignore.

Sometimes I might have a thread chain like (excuse formatting)
```clojure
(->> (.getUTCDate current-end-date)
                                        inc
                                        (.setUTCDate current-end-date)
                                        js/Date.
                                        util/first-and-last-day-of-month
                                        (map util/date->iso-date-string))
```
and I'll try different things down the chain, comment out the last two forms, etc. Just easier if I didn't have to manually navigate to the beginning each time.

A small thing, but a nicety. :smiley:

**Comment by PEZ** [comment]
I see. That makes sense. It is mainly the use of “current form” that is confusing. I thought it would be what is selected when you **Expand selection**. But this command would operate on the form enclosing the current form, right?

**Comment by bpringe** [comment]
Good point... I think we could actually make it operate like expand selection, now that you mention that. But imagine instead of a selection expanding, a `#_` is placed at the beginning of each outer form the more you "expand."

For example, imagine the shortcut is `ctrl+i` just for this:
1) I hit `ctrl+i` with cursor at `|` and `#_` is placed like so, with -> indicating before on left and after on right
```clojure
(+ 1| 2) -> (+ #_1| 2)
```
2) Then, without letting up the `ctrl` key, I hit `i` again, and now the ignore form moves to the beginning of the next outer form
```clojure
(+ #_1| 2) -> #_(+ 1| 2)
```

So as long as I hold `ctrl`, the more I hit `i` the farther out the `#_` goes. Something like this, though maybe with some different shortcut, is what I'm thinking.

**Comment by PEZ** [comment]
I like it. :smile:

I had significant problems stabilising **expand selection**. It's probably worth trying to use that logic heavily.

**Comment by PEZ** [comment]
Then again. Is there a reason to keep the cursor inside the ignored form? Otherwise it seems like this is almost already implemented by using the `backwardUp` command and then typing an ignore marker.

**Comment by bpringe** [comment]
It's simply command sugar - a few less key strokes, but that's basically what all paredit commands are. :man_shrugging:

**Comment by PEZ** [comment]
Nah, it's more than that. :smile: But as far as  sugar goes, I think this could be pretty neat if we have a really easy shortcut. (Like `ctrl+I` as you mentioned as an example.)

**Comment by bpringe** [comment]
I think this is a bit unnecessary, looking back at it, so want to close for now. Feel free to reopen if you want.
