### ISSUE TITLE
Cannot start Figwheel Main repl

### ISSUE THREAD

**Issue by alzadude** [BetterThanTomorrow/calva#728]
Hi there,

I'm unable to start a cljs repl when I attempt to Jack-In. From the error message it looks like a classpath issue, the Figwheel Main dependency is missing?

I have an `nrepl-server` alias in my project `deps.edn` which starts an nrepl server, and when I use that and connect manually, it connects successfully and works ok (note that I include `figwheel-main`):
```
{:extra-deps {cider/cider-nrepl {:mvn/version "0.23.0"}
              cider/piggieback {:mvn/version "0.4.2"}
              com.bhauman/figwheel-main {:mvn/version "0.2.11"}}
 :main-opts ["-m" "nrepl.cmdline"
             "--middleware" "[cider.nrepl/cider-middleware,cider.piggieback/wrap-cljs-repl]"]}
```

Here's the Calva Jack-In task output, as you can see `com.bhauman/figwheel-main` is missing:
```
> Executing task in folder tag-event-link: clojure -Sdeps '{:deps {nrepl {:mvn/version "0.6.0"} cider/cider-nrepl {:mvn/version "0.23.0"} clj-kondo {:mvn/version "2020.04.05"} cider/piggieback {:mvn/version "0.4.2"}}}' -A:dev -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware cider.piggieback/wrap-cljs-repl]" <
```
Here's the repl output:
```
; Jacking in...
; Hooking up nREPL sessions...
; Connected session: clj
; TIPS: You can edit the contents here. Use it as a REPL if you like.
;   Use `alt+enter` to evaluate the current top level form.
;   (`ctrl+enter` evaluates the current form.)
;   File URLs in stacktrace frames are peekable and clickable.
; Debugger initialized
clj::user=> 
; Creating cljs repl session...
; Connecting cljs repl: Clojure CLI + Figwheel Main...
;   The Calva Connection Log might have more connection progress information.
; Starting cljs repl for: Clojure CLI + Figwheel Main...
; Execution error (FileNotFoundException) at user/eval5795 (REPL:1).
Could not locate figwheel/main/api__init.class, figwheel/main/api.clj or figwheel/main/api.cljc on classpath.
; Failed starting cljs repl
; Jack-in done.
```
My environment:

Windows 10 2004
VSCode 1.47.3
WSL2 (Debian Buster)
Clojure 1.10.1.536
Remote - WSL 0.44.4
Calva 2.0.115

Thanks!

**Comment by bpringe** [comment]
Yikes, that definitely looks like a problem. Maybe some recent change screwed something up :thinking: . We'll look into it, thanks for all the info!

**Comment by bpringe** [comment]
I've been informed this is because of #701 and is intentional. `figwheel-main` should be in your project deps in any case. Going to look at the docs to see if we should add/change something there to make this clear.

**Comment by bpringe** [comment]
Added a note about project dependencies, using figwheel-main as an example, in the note part of this section. https://calva.io/connect/#jack-in-let-calva-start-the-repl-for-you

**Comment by bpringe** [comment]
Going to close this now, but please reopen if you feel the need!

**Comment by alzadude** [comment]
Hi @bpringe

Ah ok, this is a change in how Calva works then, or at least what is required for developers to put in their `deps.edn`; previously with Calva I've not needed to do this and it was working fine without.

Anyway, when I re-launch a Figwheel repl and additionally select my `nrepl-server` alias which includes the `figwheel-main` dependency, the cljs repl does start successfully. Although it seems to take a lot longer than it used to!? To be fair I've not tried this approach for a while, the last time was on an earlier version of Calva and I've also switched from WSL1 to WSL2 on Windows since then. But I thought I'd mention it anyway just in case this slowness in starting up is a known issue?

However, looking at #701, I didn't understand the comment "I think it is not necessary b/c figwheel-main will be present in dependencies list anyway (otherwise, how can one build a project for production?)"

My project is building a CLI with ClojureScript which runs on NodeJS, so I deliberately **don't** have `figwheel-main` in my project dependencies for production, since for me `figwheel-main` is not required in production. I only need it for my development repl, NodeJS backed in my case, and I specify this in a `dev.cljs.edn` file.

Very good idea to put this in the docs though, because it's exactly the kind of thing that will catch developers out; it's not especially obvious that this needs to be done, especially when it used to work without needing to do so.

Thanks! 🙂

**Comment by bpringe** [comment]
Ah I see... Hmm... I will defer to @PEZ on this one, since he made the change and is more familiar with figwheel, I think, than I am. :smiley:

**Comment by PEZ** [comment]
I agree it is unfortunate that people who had relief on this now get burnt when it suddenly stops working. But it should never have been like it was. It caused problems for people upgrading/using a particular version of Figwheel Main when Calva did its hard override.
