### ISSUE TITLE
Many paredit commands break with multiple selections

### ISSUE THREAD

**Issue by StarScape** [BetterThanTomorrow/calva#732]
For example, trying to do a slurp here: 

![image](https://user-images.githubusercontent.com/4681820/89475947-5d8efd00-d757-11ea-9b5b-2891654c296a.png)

Will only slurp on the top line.

**Comment by PEZ** [comment]
Thanks for reporting! However I am going to close this as it is a duplicate of #610 .

**Comment by StarScape** [comment]
Ah, I should have looked first :)

**Comment by PEZ** [comment]
No worries. Please upvote/chime in on that other issue. This should be within reach to fix, but I haven't experimented with it so there are probably dragons.

**Comment by StarScape** [comment]
Odd to me it does not work out of the box for all cursors...but I know nothing about the VSCode API. I might take a look myself if I can ever find the time, but you know how that goes.
