### ISSUE TITLE
Can't jack-in when no project file is open

### ISSUE THREAD

**Issue by diegovdc** [BetterThanTomorrow/calva#734]
I created a new project with https://github.com/seancorfield/clj-new and when trying to jack in I got this: 
`
Command 'Calva: Start a Project REPL and Connect (aka Jack-In)' resulted in an error (Error: EACCES: permission denied, mkdir '/.calva')
`

Seems like it's trying to create the `.calva` dir on the root  dir, instead of on the project dir.

**Comment by diegovdc** [comment]
I was opening the project dir with `code .` and then  immediately calling the `jack-in` command, but now I realize I first had to select a file within the project.

Closing this.

**Comment by PEZ** [comment]
Actually you shouldn't have to open a file in the project. I'm reopening, so that we keep this on our radar, and so that people find your workaround. Thanks for reporting!

**Comment by bpringe** [comment]
I cannot reproduce this =(. When I open a project and jack-in with no file open, it works as usual. I tried creating a new clj-new project as well.

**Comment by brdloush** [comment]
I have the same issue. Not a big problem though, there's a simple work-around around this.

Steps to reproduce:
```
lein new foo
cd foo
code .
press ctrl+alt+j, ctrl+alt+c => doesn't work, throws `Error: EACCES: permission denied, mkdir '/.calva'`
(click on TERMINAL tab, terminal opens)
press ctrl+alt+j, ctrl+alt+c => works now
```

VS Code version: 1.48.2
Calva 2.0.122

**Comment by PEZ** [comment]
Thanks for the workaround, @brdloush ! Very interesting. Which OS are you on?

**Comment by zonky-brejla** [comment]
I'm using Ubuntu budgie 20.04.

Originally I thought I have to run at least lein deps in the terminal. Later I found out that opening the terminal is all that is needed.

The error message shown is strange: as if it was trying to actually create the '/.calva'` folder in filesystem root. I may check later using strace or something.

**Comment by bpringe** [comment]
Yikes, @diegovdc and I thought we fixed this on his machine, but I think the original fix may have been reverted.

https://github.com/BetterThanTomorrow/calva/blob/4c003fc624bd5f2964d5487524cd22c15ba10c75/src/results-output/results-doc.ts#L112

It has to do with this line, but really the code above that gets the output directory. Maybe @diegovdc can look at it again, if he can still reproduce on his machine.

**Comment by bpringe** [comment]
@brdloush Can you try this vsix and see if the issue is fixed for you? @diegovdc changed something that may work, and seems to work for him. https://7915-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.124-pull-770-21d6640a.vsix

You can hit `ctrl+shift+p` and search `vsix` to find and run the command for installing it.

**Comment by diegovdc** [comment]
@bpringe The vsix is working for me.

**Comment by brdloush** [comment]
I can confirm. That vsix version fixes mentioned isssue. I can jack-in to freshly created project without having to open terminal. :+1: :clap:

**Comment by bpringe** [comment]
Awesome! Great job @diegovdc :tada:
