### ISSUE TITLE
Bring back results in hovers

### ISSUE THREAD

**Issue by Yunfeng-Song** [BetterThanTomorrow/calva#736]
I think it used to display a copy button and your inline evaluation result in a good format.  I really really like this feature.

but I think this feature doesn't work now after the update. Now if I hove over, it just displays a button says Open results window. Now I have to switch to output-repl file every time I want to check a big result. So is it a bug or this hover over feature is gone forever? 
<img width="165" alt="image" src="https://user-images.githubusercontent.com/48872815/89703618-a204dd80-d98f-11ea-9875-99f37747202c.png">

PS: I know we can use peek to achieve the same thing, but I still think this hover over feature is better.

**Comment by PEZ** [comment]
I didn't like the implementation and hurried to remove it once we had the output window displaying and making it easy to copy the results.

It was also my impression that this was not a very used feature. Which seems to have been a faulty assumption. You are not the first one to ask for it, if I put out that way.

We are considering if there is a more proper way to implement it, and even if we can live with the previous implementation.

Let's see if this issue attracts the fans of the feature. That would certainly help in helping us prioritize and decide which way to go.  Thanks for posting it!

**Comment by PEZ** [comment]
@Yunfeng-Song Please give this VSIX a spin: https://12955-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.189-736-result-hovers-cb6f42f1.vsix

**Comment by Yunfeng-Song** [comment]
Looks ### ### good!****
