### ISSUE TITLE
Conciser error/stacktrace reporting in the output.repl-file log

### ISSUE THREAD

**Issue by dabrazhe** [BetterThanTomorrow/calva#737]
Currently the new output window `(.calva/output-window/)` dumps the complete error /exception stack trace to the log. See the last code quote below. Ideally I'd like to display or toggle only the first part of the error, preferably without the comment symbol prepended.

Eg evaluate `(rand-int)`
`
Execution error (ArityException) at aws-http-core.fidlle/eval15719 (form-init4379729622409352072.clj:19).
Wrong number of args (0) passed to: clojure.core/rand-int`

### Filtering
The old repl window had this filtering feature, by the way. Filtering on the level of error would be cool as well. 

### Sample error log
The current error log spans several screen in the output.repl window and it is not really useful: 

`; Execution error (ArityException) at aws-http-core.fidlle/eval15719 (form-init4379729622409352072.clj:19).
; Wrong number of args (0) passed to: clojure.core/rand-int
[{:file "AFn.java" :line 429 :method "throwArity" :flags [:java]}
 {:file "AFn.java" :line 28 :method "invoke" :flags [:java]}
 {:file "form-init4379729622409352072.clj" :line 19 :fn "eval15719"  :method "invokeStatic" :flags [:project :repl :clj]}
 {:file "form-init4379729622409352072.clj" :line 19 :fn "eval15719"  :method "invoke" :flags [:dup :project :repl :clj]}
 {:file "Compiler.java" :line 7176 :method "eval" :flags [:tooling :java]}
 {:file "Compiler.java" :line 7166 :method "eval" :flags [:dup :tooling :java]}
 {:file "Compiler.java" :line 7131 :method "eval" :flags [:dup :tooling :java]}
 {:file "jar:file:/Users/denis/.m2/repository/org/clojure/clojure/1.10.0/clojure-1.10.0.jar!/clojure/core.clj:3214" :fn "eval"  :method "invokeStatic" :flags [:clj]}
 {:file "jar:file:/Users/denis/.m2/repository/org/clojure/clojure/1.10.0/clojure-1.10.0.jar!/clojure/core.clj:3210" :fn "eval"  :method "invoke" :flags [:clj]}
.. etc`

**Comment by bpringe** [comment]
Yes, this is something we need to improve as a priority, imo, and was known when we removed the old one, but this was deemed a reasonable temporary substitute in order to move forward. It will have to be done differently than the old repl window, which was rendered with html, but I think we can get something close or the same with the new editor output window.

In the meantime, if you have pprint enabled, that log is much more readable and still displays basically the same info, it's just not filterable yet. We'll see how we can improve this!

**Comment by bpringe** [comment]
Peter and I came up with a plan for this, which is open to changes if needed, and which can be iterated on for future improvements.

1. Print errors messages with no stack trace in the output window.
2. Provide a command to print the last error's stack trace using `clojure.repl/pst` in the output window, making the elements clickable to allow jumping to the file:line-number. This would look something like the below, but with clickable elements.
   ![image](https://user-images.githubusercontent.com/12722744/94073465-5e81f980-fdac-11ea-8eba-4de7660b270a.png)
3. Provide a command that will show the last error's stack trace in a virtual document with ways to filter elements; also with clickable elements. (Need to experiment to this to make sure it can do what we want.)
   * https://code.visualstudio.com/api/extension-guides/virtual-documents
   * See the gif here for demo of virtual doc. https://github.com/microsoft/vscode-extension-samples/blob/master/virtual-document-sample/README.md
4. Provide a way to get the current vector representation of the stack trace, if desired.

These are listed in order of priority, with 1 and 2 being grouped together. Maybe we would also provide a setting for enabling default printing of stack traces for errors in the output window, which would default to not print stack traces.

@pez Feel free to add to anything I may have missed.

**Comment by bpringe** [comment]
I'm also thinking if we can do 3, then 2 may be an unnecessary command since the user can just call `(clojure.repl/pst)` in the output window if they want to see it there. Or they can enable printing stack traces with the new setting mentioned.
