### ISSUE TITLE
Interrupting evaluations produces extra output and no prompt

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#738]
When interrupting a running evaluation there is no prompt printed in the output window. This indicates that something goes wrong before the prompt is printed.

Also, when interruption something like this:

```clojure
  (loop [i 100]
    (println i)
    (Thread/sleep 75)
    (if (zero? i)
      i
      (recur (dec i))))
```

The output is printed once again, only as single line comments.

**Comment by bpringe** [comment]
The previous fix broke stacktrace output. That was fixed but I forgot to make sure this worked.
