### ISSUE TITLE
Calva's ESC keybinding overrides VS Code's (useful) default

### ISSUE THREAD

**Issue by crispinb** [BetterThanTomorrow/calva#740]
The default keybinding for ESC (editor.action.cancelSelectionAnchor) is useful for quickly dismissing a text selection without having to reach for the arrow keys.

Calva's use of ESC (to clear evaluation results) overrides this, and it doesn't seem to be possible to distinguish the 2 bindings with a 'when' clause. So the  user must choose between the default and Calva's ESC binding.

Ideally, it would be possible to dismiss both text selections, and evaluation results, with the same key.

**Comment by PEZ** [comment]
This should be changed in Calva (PR welcome).

Meanwhile you can fix it for your own setup by changing the when clause for Calva's ESC key binding to:

```
editorTextFocus && !editorHasMultipleSelections && !editorHasSelection && !editorReadOnly && !hasOtherSuggestions && !parameterHintsVisible && !selectionAnchorSet && !suggestWidgetVisible && editorLangId == 'clojure'
```
