### ISSUE TITLE
Post 2.0.109 Repl: entering text and evaluating

### ISSUE THREAD

**Issue by thelazydogsback** [BetterThanTomorrow/calva#744]
Sorry if I'm misunderstanding how things are supposed to be working now. (Just starting w/Calva+Clojure w/o coming from JVM dev. first.)

With the post-x109 REPLT in place every character I type gets placed on a new line.
(With Vim installed I have to enter "i"nsert mode manually at the tail of the REPL with is a bit weird - but I guess I can get used to that -- but w/ or w/o vim I still only get one-char-per line. So the only thing I can do is type and then Join all the lines together and then eval.)  Evaluating from a code window seems to work as expected - so the problem is direct interaction w/the REPL only.

Am I doing something wrong??
thanks

**Comment by PEZ** [comment]
That sounds super weird. Can you type normally in regular `.clj` files, but not in the REPL window? (Which is just a regular file, so that would be super mysterious.)

It does certainly not sound like you are doing something wrong. But maybe some extension you have is doing something wrong. What can you tell us about your setup? Windows/Mac/Linux, what version of VS Code? What more extensions could be in play?

**Comment by thelazydogsback** [comment]
Thanks for the reply, PEZ.
Yes, I can edit (and eval/peek) in CLJ files just fine.
Info pasted below.
I've tried disabling Vim and a bunch of other extension w/no effect.

====VSCode: =========================================

Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

=== Extensions: =========================================
2gua.rainbow-brackets
arthurwang.vsc-prolog
asvetliakov.vscode-neovim
betterthantomorrow.calva
borkdude.clj-kondo
chiptus.refactor-jsx
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
cmstead.jsrefactor
cobaltblu27.rainbow-highlighter
CoenraadS.bracket-pair-colorizer
dbaeumer.vscode-eslint
EFanZh.graphviz-preview
eg2.vscode-npm-script
esbenp.prettier-vscode
evzen-wybitul.magic-racket
fernandoescolar.vscode-solution-explorer
firefox-devtools.vscode-firefox-debug
formulahendry.code-runner
futagozaryuu.pegjs-syntax
imjacobclark.vscode-lisp-formatter
infeng.vscode-react-typescript
intellsmi.comment-translate
Ionide.Ionide-fsharp
JakeBecker.elixir-ls
janisdd.vscode-edit-csv
jasonnutter.search-node-modules
jchannon.csharpextensions
jebbs.plantuml
joeandaverde.vscode-pegjs-live
jsayol.firebase-explorer
kisstkondoros.vscode-codemetrics
leizongmin.node-module-intellisense
lukapetrovic.image-resizer
mattn.Lisp
mhutchie.git-graph
miramac.vscode-exec-node
mohsen1.prettify-json
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-python.python
ms-vscode.azure-account
ms-vscode.cpptools
ms-vscode.vscode-typescript-next
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-audio
msjsdiag.debugger-for-chrome
nickdemayo.vscode-json-editor
nodesource.vscode-for-node-js-development-pack
NuclleaR.vscode-extension-auto-import
oderwat.indent-rainbow
Orta.vscode-jest
paolodellepiane.fantomas-fmt
pgourlain.erlang
rust-lang.rust
Shan.code-settings-sync
shaunlebron.vscode-parinfer
Sir2B.lispbeautifier
steoates.autoimport
toba.vsfire
tonsky.clojure-warrior
usernamehw.run-commands-view
VisualStudioExptTeam.vscodeintellicode
vscodevim.vim
waderyan.nodejs-extension-pack
WallabyJs.quokka-vscode
WallabyJs.wallaby-vscode
wix.vscode-import-cost
xabikos.JavaScriptSnippets
xuqinghan.vscode-hy

**Comment by bpringe** [comment]
Have you tried disabling all extensions (there's a command for that), and then enabling only Calva, and seeing if you have the issue?

**Comment by thelazydogsback** [comment]
Jinx!  I just happened to do that, and now things seem to work as expected!
I'm not exactly sure which extension was the issue.
Unfortunately many extensions can do the same thing (let's say provide rainbow parens or do semantic coloring) and it's never clear what extension is doing what in the UI, so there's no easy way to pair down extensions to get the minimal set for a certain feature-set or to ensure that they don't clash in some way -- unless there's some meta-feature in VsCode I'm not aware of.)
thanks!
