### ISSUE TITLE
Address intermittent failing tests with generated input

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#746]
The "tokenizes list/vector/map/string" test fails every now and then. One input it's failed with is `"($#^#)"`.

We need to fix the test, input generation, or the lexer (have not investigated yet).

I'm labeling this as "bug" just so we prioritize and because it's something that needs to be fixed, even if it's not indicative of a bug in the extension.

**Comment by bpringe** [comment]
This could be a good way to get familiar with a central part of Calva, if anyone is interested. Tip: the Mocha Test Explorer extension makes seeing and running the tests easy.

**Comment by bpringe** [comment]
Going to append another test to this issue.

The `Scanner -> simple -> tokenizes symbol` test fails with input `"\\###"`:
```
expected 'lit' to equal 'id'
```

**Comment by bpringe** [comment]
Another:

```
Counterexample: ["$#^#"]
  Shrunk 31 time(s)
  Got error: AssertionError: expected '$#' to equal '$#^#'
```

**Comment by bpringe** [comment]
```
Counterexample: [":$#^#"]
  Shrunk 26 time(s)
  Got error: AssertionError: expected ':$#' to equal ':$#^#'
```

**Comment by bpringe** [comment]
```
Counterexample: [":$^##"]
  Shrunk 44 time(s)
  Got error: AssertionError: expected ':$' to equal ':$^##'
```

**Comment by PEZ** [comment]
The parsing PR (#838) fixes all cases mentioned in this issue thread, so I made it close this. We can create a new issue should we see that we keep generating data that shouldn't break the tests, but do.
