### ISSUE TITLE
Stack traces not being shown in the REPL output

### ISSUE THREAD

**Issue by StarScape** [BetterThanTomorrow/calva#758]
Stack traces are not showing up at all for me in the REPL output, just the error message itself.

**Comment by PEZ** [comment]
Thanks for reporting! Yes, tried this and see that it worked in `.119` and stopped working in `.120`. So checked the contents of `.120` and now suspect this PR a lot: https://github.com/BetterThanTomorrow/calva/pull/739

Ir sure fixed its issue, but seems to do it in a very crude way. 🤦 

I have a busy work day in front of me, so won't be able to tackle this until tomorrow I think. If someone else can, be my guest!
