### ISSUE TITLE
Parsing project.clj eval error

### ISSUE THREAD

**Issue by brandonstubbs** [BetterThanTomorrow/calva#763]
Hi

I am working on some OSS projects that are a mono-repo and the version is shared into the microservices. Below is an example project.clj

```
(defn ver [] "1.10.1") ; originally (defn ver [] (-> "../ver/project.version" slurp .trim)))
(defproject error "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure #=(ver)]]
  :repl-options {:init-ns error.core})
```

You won't be able to jack-in as the `cljs.tools.reader` library does not support [read-eval](https://github.com/clojure/tools.reader/blob/tools.reader-1.2.2/src/main/cljs/cljs/tools/reader.cljs#L815)
So you will get `Error: read-eval not supported` while trying to `parse-forms`

I propose to change the following [parse.cljs#L36](https://github.com/BetterThanTomorrow/calva/blob/9a296/src/cljs-lib/src/calva/parse.cljs#L36) to `(let [pbr (rt/string-push-back-reader (str/replace s #"#=\(" "#_("))]` ultimately ignoring the eval.

Please let me know if you are happy with this approach and I will open a PR for this change.

**Comment by PEZ** [comment]
Yes, sorry for late response. This is pragmatic. It will work and will not break anything. 

We should parse these files using the token cursor, but for now, this change is super.
