### ISSUE TITLE
Convert html to hiccup when pasted into clj(s) document

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#766]
I saw that this is a feature in Cursive from this Reddit post: https://www.reddit.com/r/Clojure/comments/idw4hc/til_cursive_will_convert_html_into_hiccup_when/

Looks like something neat to add to Calva.

**Comment by gerdint** [comment]
Is this not a dupe of #407? (and can be closed)

**Comment by bpringe** [comment]
Looks like it. Thanks!
