### ISSUE TITLE
cant jack-in in an new leiningen project

### ISSUE THREAD

**Issue by aaring** [BetterThanTomorrow/calva#768]
I created a project with `lein new app calva.test.2` 
Then `cd calva.test.2` and `code .`

project.clj and 2.clj are open.

Trying to jack-in issues the command

```
> Executing task: C:\WINDOWS\system32\cmd.exe /d /c lein update-in :dependencies conj [nrepl"0.6.0"] -- update-in :dependencies conj [clj-kondo"2020.04.05"] -- update-in :plugins conj [cider/cider-nrepl"0.23.0"] -- update-in [:repl-options^ :nrepl-middleware] conj '["cider.nrepl/cider-middleware"]' -- repl :headless <
```

and the following error

```
java.lang.IllegalArgumentException: Provided artifact is missing a version: [cider/cider-nrepl0.23.0]   
 at cemerick.pomegranate.aether$add_version_from_managed_coord.invokeStatic (aether.clj:658)
 ...
```

```
lein -version
Leiningen 2.9.4 on Java 11.0.8 Java HotSpot(TM) 64-Bit Server VM
```
Windows 10 pro 1909 german language
vs code 1.48.1
calva v2.0.122

**Comment by bpringe** [comment]
Very peculiar... I don't see anything wrong with the command itself. I'm not running windows so it's not easy for me to test. @PEZ Any idea here?

>1909 german language

I wonder if this could play any part, though I doubt it. It's weird because the error looks like the system didn't like the string quoting, but it doesn't complain about earlier instances of the same quoting in the command.

**Comment by porkostomus** [comment]
Hi, I am trying to reproduce but am unable to. I'm running Windows 10 Pro Insider but everything else is the same. Are you able to start a Leiningen REPL from the command line?

**Comment by aaring** [comment]
No it's same Problem on cmd.exe and powershell.

**Comment by grangerb16** [comment]
I have the same issue:

Executing task: C:\WINDOWS\system32\cmd.exe /d /c lein update-in :dependencies conj [nrepl"0.6.0"] -- update-in :dependencies conj [clj-kondo"2020.04.05"] -- update-in :plugins conj [cider/cider-nrepl"0.23.0"] -- update-in [:repl-options^ :nrepl-middleware] conj '["cider.nrepl/cider-middleware"]' -- repl :headless <

java.lang.IllegalArgumentException: Provided artifact is missing a version: [cider/cider-nrepl0.23.0]   
 at cemerick.pomegranate.aether$add_version_from_managed_coord.invokeStatic (aether.clj:658)
    cemerick.pomegranate.aether$add_version_from_managed_coord.invoke (aether.clj:650)
    cemerick.pomegranate.aether$add_version_from_managed_coords_if_missing.invokeStatic (aether.clj:686)
    cemerick.pomegranate.aether$add_version_from_managed_coords_if_missing.invoke (aether.clj:680)      
    clojure.core$partial$fn__5839.invoke (core.clj:2624)
    clojure.core$map$fn__5866.invoke (core.clj:2753)
    clojure.lang.LazySeq.sval (LazySeq.java:42)
    clojure.lang.LazySeq.seq (LazySeq.java:51)
    clojure.lang.RT.seq (RT.java:535)
    clojure.lang.LazilyPersistentVector.create (LazilyPersistentVector.java:44)
    clojure.core$vec.invokeStatic (core.clj:377)
    clojure.core$vec.invoke (core.clj:367)
    cemerick.pomegranate.aether$merge_versions_from_managed_coords.invokeStatic (aether.clj:695)
    cemerick.pomegranate.aether$merge_versions_from_managed_coords.invoke (aether.clj:689)
    cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic (aether.clj:797)
    cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke (aether.clj:711)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    cemerick.pomegranate.aether$resolve_dependencies.invokeStatic (aether.clj:819)
    cemerick.pomegranate.aether$resolve_dependencies.doInvoke (aether.clj:813)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    cemerick.pomegranate$add_dependencies.invokeStatic (pomegranate.clj:83)
    cemerick.pomegranate$add_dependencies.doInvoke (pomegranate.clj:57)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.classpath$get_dependencies_STAR_.invokeStatic (classpath.clj:288)
    leiningen.core.classpath$get_dependencies_STAR_.invoke (classpath.clj:281)
    clojure.lang.AFn.applyToHelper (AFn.java:165)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.core$memoize$fn__6877.doInvoke (core.clj:6353)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    leiningen.core.classpath$get_dependencies$fn__6838.invoke (classpath.clj:337)
    leiningen.core.classpath$get_dependencies.invokeStatic (classpath.clj:335)
    leiningen.core.classpath$get_dependencies.doInvoke (classpath.clj:329)
    clojure.lang.RestFn.applyTo (RestFn.java:146)
    clojure.core$apply.invokeStatic (core.clj:671)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.classpath$resolve_managed_dependencies.invokeStatic (classpath.clj:448)
    leiningen.core.classpath$resolve_managed_dependencies.doInvoke (classpath.clj:435)
    clojure.lang.RestFn.invoke (RestFn.java:494)
    leiningen.core.project$load_plugins.invokeStatic (project.clj:763)
    leiningen.core.project$load_plugins.invoke (project.clj:758)
    leiningen.core.project$load_plugins.invokeStatic (project.clj:774)
    leiningen.core.project$load_plugins.invoke (project.clj:758)
    leiningen.core.project$load_plugins.invokeStatic (project.clj:775)
    leiningen.core.project$load_plugins.invoke (project.clj:758)
    leiningen.update_in$update_project.invokeStatic (update_in.clj:21)
    leiningen.update_in$update_project.invoke (update_in.clj:16)
    leiningen.update_in$update_in.invokeStatic (update_in.clj:37)
    leiningen.update_in$update_in.doInvoke (update_in.clj:24)
    clojure.lang.RestFn.applyTo (RestFn.java:146)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$partial_task$fn__7330.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:343)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.update_in$update_in.invokeStatic (update_in.clj:37)
    leiningen.update_in$update_in.doInvoke (update_in.clj:24)
    clojure.lang.RestFn.applyTo (RestFn.java:146)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$partial_task$fn__7330.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:343)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.update_in$update_in.invokeStatic (update_in.clj:37)
    leiningen.update_in$update_in.doInvoke (update_in.clj:24)
    clojure.lang.RestFn.applyTo (RestFn.java:146)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$partial_task$fn__7330.doInvoke (main.clj:284)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:31)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:667)
    clojure.core$apply.invoke (core.clj:660)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:343)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.core.main$_main$fn__7419.invoke (main.clj:453)
    leiningen.core.main$_main.invokeStatic (main.clj:442)
    leiningen.core.main$_main.doInvoke (main.clj:439)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.core$apply.invokeStatic (core.clj:665)
    clojure.main$main_opt.invokeStatic (main.clj:514)
    clojure.main$main_opt.invoke (main.clj:510)
    clojure.main$main.invokeStatic (main.clj:664)
    clojure.main$main.doInvoke (main.clj:616)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.lang.Var.applyTo (Var.java:705)
    clojure.main.main (main.java:40)
The terminal process "C:\WINDOWS\system32\cmd.exe '/d', '/c', 'lein', 'update-in', ':dependencies', 'conj', '[nrepl"0.6.0"]', '--', 'update-in', ':dependencies', 'conj', '[clj-kondo"2020.04.05"]', '--', 'update-in', ':plugins', 'conj', '[cider/cider-nrepl"0.23.0"]', '--', 'update-in', '[:repl-options^ :nrepl-middleware]', 'conj', ''["cider.nrepl/cider-middleware"]'', '--', 'repl', ':headless'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by bpringe** [comment]
@grangerb16 Is your OS Windows 10? This is strange that it only happens for a few Windows users. I'm guessing it must be some difference in shell settings.

Try to run the jack-in command in cmd.exe outside of VS Code and also in Powershell outside of VS Code and let us know what happens.

```
C:\WINDOWS\system32\cmd.exe /d /c lein update-in :dependencies conj [nrepl"0.6.0"] -- update-in :dependencies conj [clj-kondo"2020.04.05"] -- update-in :plugins conj [cider/cider-nrepl"0.23.0"] -- update-in [:repl-options^ :nrepl-middleware] conj '["cider.nrepl/cider-middleware"]' -- repl :headless
```

**Comment by grangerb16** [comment]
I get the same error when running from the cmd prompt or PowerShell.  Windows 10 version 1909.

cmd prompt:
Microsoft Windows [Version 10.0.18363.1082]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\BGranger>lein update-in :dependencies conj [nrepl"0.6.0"] -- update-in :dependencies conj [clj-kondo"2020.04.05"] -- update-in :plugins conj [cider/cider-nrepl"0.23.0"] -- update-in [:repl-options^ :nrepl-middleware] conj '["cider.nrepl/cider-middleware"]' -- repl :headless
java.lang.IllegalArgumentException: Provided artifact is missing a version: [cider/cider-nrepl0.23.0]
 at cemerick.pomegranate.aether$add_version_from_managed_coord.invokeStatic (aether.clj:658)
    cemerick.pomegranate.aether$add_version_from_managed_coord.invoke (aether.clj:650)
    cemerick.pomegranate.aether$add_version_from_managed_coords_if_missing.invokeStatic (aether.clj:686)


PowerShell:
PS C:\Users\BGranger> lein update-in :dependencies conj [nrepl"0.6.0"] -- update-in :dependencies conj [clj-kondo"2020.04.05"] -- update-in :plugins conj [cider/cider-nrepl"0.23.0"] -- update-in [:repl-options^ :nrepl-middleware] conj '["cider.nrepl/cider-middleware"]' -- repl :headless
java.lang.IllegalArgumentException: Provided artifact is missing a version: [cider/cider-nrepl0.23.0]
 at cemerick.pomegranate.aether$add_version_from_managed_coord.invokeStatic (aether.clj:658)
    cemerick.pomegranate.aether$add_version_from_managed_coord.invoke (aether.clj:650)

**Comment by bpringe** [comment]
Thanks for the added info. @PEZ , do you think there's a way we can fix this quoting issue for all Windows users?

**Comment by aaring** [comment]
I have Windows Terminal Version 1.2.2381 installed. 
Maybe this changes some settings.

**Comment by PEZ** [comment]
Shell quoting on Windows is about the trickiest thing to get right. Especially strange that it can behave so differently on different machines. 

Looking at this part of the error message:

```
java.lang.IllegalArgumentException: Provided artifact is missing a version: [cider/cider-nrepl0.23.0]
```

The version is supposed to be a string, but somewhere the quotes are lost...

This is a long shot. But I may have fixed this problem (or made it worse, and/or caused new jack-in problems) in my branch for moving jack-in from the Task subsystem to a pseudo terminal. In the hopes that someone who experiences the problems in this issue can try those changes out, here is the VSIX: https://9157-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.136-wip-terminal-jack-in-a6586e74.vsix

Install that from the Extensions panel's meatball menu: *Install from VSIX...* and let us now how your fare, please.

**Comment by bpringe** [comment]
This is now in version 2.0.139. Can someone who had this issue please test jack-in again with this version and let us know if it works?

**Comment by aaring** [comment]
I tried it with 2.0.139 and 2.0.140. The problem persists.

**Comment by bpringe** [comment]
@aaring Did you mean to close this? If the problem persists, we should keep this open, right?
