### ISSUE TITLE
Can't start the repl(jack-in)-Windows

### ISSUE THREAD

**Issue by fabricioc8** [BetterThanTomorrow/calva#773]
I can't start the repl, it worked fine until yesterday. I do it with ctrl + shift + p (jack-in).

VisualStudio version:
Version: 1.48.1 (system setup)
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:12:39.269Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT ia32 6.1.7601
Windows 7 32 bits

Calva version: 2.0.123
Kondo version: 2020.7.291

I get the following messages:

Terminal:
Full report at:
Syntax error compiling at (C:\Users\usuario\AppData\Local\Temp\form-init7003487012602780590.clj:4353:33).
Unable to resolve symbol: create in this context
C:\Users\usuario\AppData\Local\Temp\clojure-4535704420695670495.edn
Subprocess failed (exit code: 1)
The terminal process "C:\Windows\SYSTEM32\cmd.exe '/d', '/c', 'lein', 'update-in', ':dependencies', 'conj', '[nrepl"0.6.0"]', '--', 'update-in', ':dependencies', 'conj', '[clj-kondo"2020.04.05"]', '--', 'update-in', ':plugins', 'conj', '[cider/cider-nrepl"0.23.0"]', '--', 'update-in', '[:repl-options^ :nrepl-middleware]', 'conj', ''["cider.nrepl/cider-middleware"]'', '--', 'repl', ':headless'" terminated with exit code: 1.

Notification:
No supported Jack-in project types detected. Maybe try starting your project manually and use the Connect command?
Output.calva-repl:
; This is the Calva evaluation results output window.
; Leave it open, please. Because quirks.
; TIPS: The keyboard shortcut `ctrl+alt+c o` shows and focuses this window
;   when connected to a REPL session.
; Please see https://calva.io/output/ for more info.
; Happy coding! ♥️
; No Jack-in possible.

**Comment by fabricioc8** [comment]
form-init7003487012602780590.clj:4353:33

{:clojure.main/message
 "Syntax error compiling at (C:\\Users\\usuario\\AppData\\Local\\Temp\\form-init7003487012602780590.clj:4353:33).\r\nUnable to resolve symbol: create in this context\r\n",
 :clojure.main/triage
 {:clojure.error/phase :compile-syntax-check,
  :clojure.error/line 4353,
  :clojure.error/column 33,
  :clojure.error/source "form-init7003487012602780590.clj",
  :clojure.error/path
  "C:\\Users\\usuario\\AppData\\Local\\Temp\\form-init7003487012602780590.clj",
  :clojure.error/class java.lang.RuntimeException,
  :clojure.error/cause
  "Unable to resolve symbol: create in this context"},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message
    "Syntax error compiling at (C:\\Users\\usuario\\AppData\\Local\\Temp\\form-init7003487012602780590.clj:4353:33).",
    :data
    {:clojure.error/phase :compile-syntax-check,
     :clojure.error/line 4353,
     :clojure.error/column 33,
     :clojure.error/source
     "C:\\Users\\usuario\\AppData\\Local\\Temp\\form-init7003487012602780590.clj"},
    :at [clojure.lang.Compiler analyze "Compiler.java" 6808]}
   {:type java.lang.RuntimeException,
    :message "Unable to resolve symbol: create in this context",
    :at [clojure.lang.Util runtimeException "Util.java" 221]}],
  :trace
  [[clojure.lang.Util runtimeException "Util.java" 221]
   [clojure.lang.Compiler resolveIn "Compiler.java" 7414]
   [clojure.lang.Compiler resolve "Compiler.java" 7358]
   [clojure.lang.Compiler analyzeSymbol "Compiler.java" 7319]
   [clojure.lang.Compiler analyze "Compiler.java" 6768]
   [clojure.lang.Compiler analyze "Compiler.java" 6745]
   [clojure.lang.Compiler$HostExpr$Parser parse "Compiler.java" 1020]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7107]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7095]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler access$300 "Compiler.java" 38]
   [clojure.lang.Compiler$LetExpr$Parser parse "Compiler.java" 6384]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7107]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7095]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7095]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyze "Compiler.java" 6745]
   [clojure.lang.Compiler$InvokeExpr parse "Compiler.java" 3888]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7109]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyze "Compiler.java" 6745]
   [clojure.lang.Compiler$InvokeExpr parse "Compiler.java" 3888]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7109]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler access$300 "Compiler.java" 38]
   [clojure.lang.Compiler$LetExpr$Parser parse "Compiler.java" 6384]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7107]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyze "Compiler.java" 6745]
   [clojure.lang.Compiler$BodyExpr$Parser parse "Compiler.java" 6120]
   [clojure.lang.Compiler$FnMethod parse "Compiler.java" 5467]
   [clojure.lang.Compiler$FnExpr parse "Compiler.java" 4029]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7105]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler eval "Compiler.java" 7174]
   [clojure.lang.Compiler eval "Compiler.java" 7167]
   [clojure.lang.Compiler eval "Compiler.java" 7167]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.Compiler loadFile "Compiler.java" 7574]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$init_opt invokeStatic "main.clj" 477]
   [clojure.main$init_opt invoke "main.clj" 477]
   [clojure.main$initialize invokeStatic "main.clj" 508]
   [clojure.main$null_opt invokeStatic "main.clj" 542]
   [clojure.main$null_opt invoke "main.clj" 539]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "Unable to resolve symbol: create in this context",
  :phase :compile-syntax-check}}

**Comment by bpringe** [comment]
Looks like you may have tried to jack-in without a project directory open in vs code. Can you provide more details about how you opened the project and what type of project it was?

>No supported Jack-in project types detected.

This message is shown when there's no deps.edn, shadow-cljs.edn, project.clj, etc. (project files) found in the open directory in vs code.

**Comment by fabricioc8** [comment]
It's the same project that i've been working in :(.  I didn't change anything. It has the following project.clj:

(defproject flexserach "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]]
  :repl-options {:init-ns flexserach.core})

I updated visualstudio to Version: 1.48.2 (system setup) and it didn't work either.

**Comment by bpringe** [comment]
Hmm, I notice the error mentions `form-init` and that you have `:init-ns` set to `flexserach.core` - is this a typo? Should it be `flexsearch.core`?

**Comment by fabricioc8** [comment]
It was that! I had corrected the files but not the project evidently... I had been several days with the repl on and I realized when I reseted vs. Thanks very much for your time! :)

**Comment by bpringe** [comment]
No problem! Glad it's figured out.
