### ISSUE TITLE
Calva REPL evaluates to last read atomic expr only -- expr ingored

### ISSUE THREAD

**Issue by thelazydogsback** [BetterThanTomorrow/calva#776]
When typing directly into the REPL, only the last atomiac form read by the reader becomes is returned as the result of the evaluation. 
For example, (+ 1 2) will evaluate as 2.
However, evaluating a form from a source file (inline or as comment) works fine. (See below.)
thanks

![image](https://user-images.githubusercontent.com/4603468/91779226-bd879080-eba9-11ea-9593-50136fc3e18c.png)

![image](https://user-images.githubusercontent.com/4603468/91779303-017a9580-ebaa-11ea-9522-0d6feb943db1.png)

**Comment by PEZ** [comment]
Hello. Which commands are you using?

**Comment by bpringe** [comment]
Closing this. It appears you were likely running the command "Evaluate Current Form" with your cursor at the `4`, like `(+ 1 2 (+ 3 4|))` which will evaluate the `4`, resulting in `4`. The command you want to use is "Evaluate Top Level Form."
