### ISSUE TITLE
Linter issue within `defspec` macro of `clojure.test.check.clojure-test`

### ISSUE THREAD

**Issue by amarjeet000** [BetterThanTomorrow/calva#781]
Please see the symbols `property` and `v` within the context of `defspec` macro. It appears to be the linter issue. This is not a compile/runtime bug.

<img width="756" alt="Screenshot 2020-09-12 at 2 43 15 PM" src="https://user-images.githubusercontent.com/7702064/92992139-4c7b9d80-f506-11ea-9ca1-b783e971d8a4.png">

I can move this issue to `clj-kondo` if thats the appropriate place for this.

**Comment by bpringe** [comment]
Hello. This is related to clj-kondo for sure, but not really an issue. You must configure it recognize some macros, essentially.

You can, for example, put this in your `.clj-kondo/config.edn` to make the above lint errors go away:

```
{:lint-as {clojure.test.check.clojure-test clojure.core/def}}
```

There may be other ways to do this too, and that config.edn can be placed in other places as well depending on if you want it to be applied just for that project or all projects on your machine. Please see the clj-kondo docs for more info.

**Comment by amarjeet000** [comment]
Great, thanks :)

**Comment by bpringe** [comment]
Just noticed I had a typo in my example above, but fixed it. :smile:
