### ISSUE TITLE
Format commands fails with this specific scenario

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#782]
I'm not sure why it's failing but just creating this issue for later. With the cursor at `|` below, next to the form that calls `sse/start-event-stream`, if I hit `tab` I get a warning message that says `Running the contributed command: 'calva-fmt.formatCurrentForm' failed.` Before the form was formatted correctly, I had to move the cursor down to `updates-stream-ready` to make formatting work.

```clojure
(def routes
  [[["/commands"
     {:post [::post-command ^:interceptors [(body-params)] `post-command]}]
    ["/events"
     ["/updates" 
      {:get [::get-updates 
            |(sse/start-event-stream
              updates-stream-ready
              10
              10
              {:on-client-disconnect
               (fn [context]
                 (println "on-client-disconnect called")
                 (clojure.pprint/pprint context)
                 (let [client-id (-> :request :query-params :client-id)]
                   (println "removing channel for client" client-id)
                   (swap! sse-event-channels dissoc client-id)))})]}]]]])
```

**Comment by PEZ** [comment]
It's the namespaced keyword. https://github.com/weavejester/cljfmt/issues/106

Might be about to be solved upstream, or maybe even solved, if we piece together the PRs and such.
