### ISSUE TITLE
Not able to escape read-line in the output window

### ISSUE THREAD

**Issue by pedro-w** [BetterThanTomorrow/calva#783]
I had some code with interactive input using `read-line`. 
```clojure
(ns cc.core)
(defn me []
  (loop [l (read-line)]
    (when l
      (prn l)
      (recur (read-line)))))
```
(this is a minimal example)
If run from a normal terminal it's possible to exit the loop by entering EOF (^Z in my case), as `read-line` will then return `nil`.

If run from the Calva output window, the editor pops up a little box, titled REPL Input, to enter the input. From there
* it's not possible to enter ^Z
* pressing ESC just prints "No input provided"
* attempting to disconnect the session is not possible, either from the nREPL icon at the bottom or from the Command palette, because the REPL Input box takes priority.
As far as I can see the only way out is to quit the editor.

Is there another way to indicate EOF to the running code, or otherwise break out of the loop?

Using Clojure 1.10.1, Windows 10, VSCode 1.49.1, Calva 2.0.124

**Comment by bpringe** [comment]
Tested this myself, never seen this before but I do see what you mean. It made me chuckle :smile:. I have a couple of notes:

* You can get out of this loop without closing the editor by terminating the repl session in the terminal.
* You can also run the Calva command "Interrupt running Evaluations" via the shortcut keys (in my case: `ctrl+alt+c ctrl+alt+d`)

@PEZ Is there anything else we should do about this particular situation? I see that this is occurring here: https://github.com/BetterThanTomorrow/calva/blob/5ff07b1584991689156ff103e7e9bc50b0e47480/src/nrepl/index.ts#L799

Perhaps we should interrupt the evaluation at this point, when there's no input (user hit Esc in the prompt)?

**Comment by PEZ** [comment]
We should make dismissal of the input picker send cttl+z, probably.
