### ISSUE TITLE
Test runner can't find tests under cursor when using a custom test macro

### ISSUE THREAD

**Issue by stefan-toubia** [BetterThanTomorrow/calva#786]
It appears that changes made in [this commit](https://github.com/BetterThanTomorrow/calva/commit/059ec2eab85afd389ff0b345047a8b9c924317d9#diff-3e9059b76e61283e94de7e913038d1e7) have broken the ability to run the test runner for custom macros. We use many macros like `defdbtest` which provide some fixturing, now I'm unable to run these tests individually. I only looked very briefly so I'm not 100% confident this is the source of the problem, but I do know this used to work for me :)

**Comment by PEZ** [comment]
Thanks, we'll need to revisit this, it seems.

**Comment by bpringe** [comment]
I see it's this line here: `if (['def', 'defn', 'deftest'].includes(tokenCursor.getToken().raw))` - I was unsure about this at the time and should have been more thorough in assessing the situation. My apologies.

I'll work on getting a fix out soon.

**Comment by bpringe** [comment]
@stefan-toubia Please try this vsix and let me know if it works for your cases.

**Comment by stefan-toubia** [comment]
@bpringe you're awesome :) that worked!

**Comment by bpringe** [comment]
Sweet! Thanks for testing.
