### ISSUE TITLE
Test runner output only partially commented

### ISSUE THREAD

**Issue by stefan-toubia** [BetterThanTomorrow/calva#787]
When a test run fails and shows the expected/actual diffs, only the first line is commented

```clojure
 ; expected: #{{:id 1002197,
   :display-name "Campaign 1002198",
   :state "enabled"}}
; actual:  (#{{:id 1002197,
    :display-name "Campaign 1002198",
    :state "enabled"}})
```

It seems preferable that the diff output would not be commented, maybe there should always be a new line after expected and actual so that the text is commented but the output is not?

```clojure
 ; expected:
#{{:id 1002197,
   :display-name "Campaign 1002198",
   :state "enabled"}}
; actual:
(#{{:id 1002197,
    :display-name "Campaign 1002198",
    :state "enabled"}})
```

While we're at it, I was wondering if there's a reason the `actual` output is always in a list `()` whereas expected is not formatted this way?

Last thing, I'm liking the new output method with the file, much more reliable doing paredit in an actual file, I'm imagining it's less complex than having a whole repl window module too! Do you know if it's possible to customize the color of the comments in this file alone? Green seems pretty appropriate in normal cases, but is a bit hard to read large blocks of for the test runner output.

**Comment by PEZ** [comment]
While I think that this last thing should go in an issue of its own, I can't resist commenting on it. 😄 Yes, it is possible. But it would need to be done via the highlight module, I can talk you through it some on slack or something, if you want to take it on.

**Comment by bpringe** [comment]
So Calva's is calling [`test-var-query`](https://docs.cider.mx/cider-nrepl/nrepl-api/ops.html#test-var-query) from cider-nrepl to run tests and get results. Those results are coming back with `actual` being a list, and I'm not sure why.

Another thing that confuses me is when I run a test to simulate your output, it all comes back on one line in the results (no newline characters). With this test:

```clojure
(with-test
  (defn foo []
    #{{:id 1010101
       :display-name "Campaign 1010101"
       :state "enabled"}})
  (is (= #{{:id 1010102
            :display-name "Campaign 1010101"
            :state "enabled"}} 
         (foo))))
```
I get these results (as seen in the debug pane):
![image](https://user-images.githubusercontent.com/12722744/93689551-7d1e8280-fa84-11ea-9978-8844556c84bc.png)

And hence it prints in the output window like:

```
; Running test: foo…
; FAIL in core/foo (core.clj:24):
;   expected: #{{:id 1010102, :display-name "Campaign 1010101", :state "enabled"}}
;   actual: (#{{:id 1010101, :display-name "Campaign 1010101", :state "enabled"}})
; 1 tests finished, problems found. 😭 errors: 0, failures: 1, ns: 1, vars: 1
```

**Comment by bpringe** [comment]
I guess the newline thing could be my pprint settings... I'll look into that.

**Comment by bpringe** [comment]
@stefan-toubia Please try this vsix and let me know if it looks good to you. https://8033-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.125-fix-test-runner-output-51ad1b13.vsix

**Comment by stefan-toubia** [comment]
@bpringe Another great fix, thanks!

**Comment by PEZ** [comment]
I'm lazy, so haven't checked before suggesting: Make an issue for the extra parens things. They have bit me many times, but lately I have finally learnt to ignore them, which is totally the wrong solution.

**Comment by bpringe** [comment]
I've made a new issue, #794. Knowing what I know, I'm assuming it's an upstream issue and tagged Bozhidar Batsov in that thread.
