### ISSUE TITLE
Actual output in failing test is always in a list

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#794]
Running the test below:

```clojure
(with-test
  (defn bar []
    2)
  (is (= 1 (bar))))
```

The results are:

```clojure
;   expected: 1
;   actual: (2)
```

The `actual` result comes back from nrepl this way, so this seems like an upstream issue in cider-nrepl's `test-var-query` op. Though there may be something I'm not understanding. Maybe @bbatsov can shed more light here.

**Comment by bpringe** [comment]
From Bug on Slack:

> I don't quite remember (this code hasn't been touched in a long time), but it's probably something to do with the fact that actual seems to be the string we get directly from clojure.test:

```emacs-lisp
(defun cider-test--extract-from-actual (actual n)
  "Extract form N from ACTUAL, ignoring outermost not.
ACTUAL is a string like \"(not (= 3 4))\", of the sort returned by
clojure.test.
N = 1 => 3, N = 2 => 4, etc."
  (with-temp-buffer
    (insert actual)
    (clojure-mode)
    (goto-char (point-min))
    (re-search-forward "(" nil t 2)
    (clojure-forward-logical-sexp n)
    (forward-whitespace 1)
    (let ((beg (point)))
      (clojure-forward-logical-sexp)
      (buffer-substring beg (point)))))
```

> I've also noticed that CIDER doesn't use test-var-query directly (for historical reasons), but all the legacy ops are implemented in terms of it, so this probably doesn't change the behavior.

**Comment by marcomorain** [comment]
This is fixed by https://github.com/clojure-emacs/cider-nrepl/issues/735 and https://github.com/BetterThanTomorrow/calva/pull/1450
