### ISSUE TITLE
Add clojure-thread-last-all, clojure-thread-first-all and clojure-unwind-all functionality

### ISSUE THREAD

**Issue by armincerf** [BetterThanTomorrow/calva#798]
Elisp implementations of these functions can be found in [clojure-mode.el](https://github.com/clojure-emacs/clojure-mode/blob/f21e544c157040a0e5ea6fa8eb41641596028b8d/clojure-mode.el#L2329)

**Comment by bpringe** [comment]
I just want to add for reference later, here are visual demos of what these commands should do: https://awesomeopensource.com/project/clojure-emacs/clojure-mode
