### ISSUE TITLE
cljfmt - type hinting not ignored

### ISSUE THREAD

**Issue by brandonstubbs** [BetterThanTomorrow/calva#807]
The `cljfmt` library being used currently has a bug that type hinting isn't ignored during formatting.

Test with the following snippet:
```clojure
(require '[cljfmt.core :as cljfmt])
(cljfmt/reformat-string "(let [^String x       \"foo\"
      some-longer-var \"bar\"])")
```

`[pez/cljfmt "0.0.4-SNAPSHOT"]` output:
```clojure
"(let [^String x               \"foo\"\n      some-longer-var \"bar\"])"

(let [^String x               "foo"
      some-longer-var "bar"])
```

`[cljfmt "0.7.0"]` output:
```clojure
"(let [^String x       \"foo\"\n      some-longer-var \"bar\"])"

(let [^String x       "foo"
      some-longer-var "bar"])
```

These are the personal commits by @PEZ to his cljfmt fork
![image](https://user-images.githubusercontent.com/3731434/95620014-6bb70d80-0a67-11eb-99c5-6a28e4abddd1.png)
The main change adding the [Calva](https://github.com/PEZ/cljfmt/commit/8f6c7520b0e8c5497e88bb325e4045b32d7ce55b) name.

I would be happy to open a PR to update the library to `[cljfmt "0.7.0"]`

**Comment by PEZ** [comment]
Thanks. Actually the main addition is the commit where I merge the align functionality. If that has been added to `0.7.0` we should definitely switch. If not, this would involve merging `0.7.0` and our fork together. I'd welcome that!

**Comment by brandonstubbs** [comment]
@PEZ Thank you for mentioning that merge. The functionality has not been added to `0.7.0` I have opened a PR as WIP to your PEZ branch which contains the alignment as there are some discussion points I would like to have with you 😸

**Comment by PEZ** [comment]
I see the PR. Super awesome stuff! I've commented there.
