### ISSUE TITLE
repl - prompt space ending

### ISSUE THREAD

**Issue by brandonstubbs** [BetterThanTomorrow/calva#808]
The repl prompt currently has a space at the end. Added in this [commit](https://github.com/BetterThanTomorrow/calva/commit/50f517950ade8df62cf77a04d3df364f0e3da292)

If using an extension such as [Trailing Spaces](https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces) this will colour all repl prompt lines.

![image](https://user-images.githubusercontent.com/3731434/95624372-abcdbe80-0a6e-11eb-82b2-3e7d8c244983.png)

Was there a particular reason the above commit was added? Happy to do a PR to remove this space but obviously this was added for a reason maybe.

**Comment by PEZ** [comment]
It's so that backspace shouldn't move the cursor past that space.

**Comment by bpringe** [comment]
Closing as this seems to be intended/desired. @PEZ reopen if I'm mistaken.

**Comment by bpringe** [comment]
Reopening as I feel maybe I closed too eagerly :smile:. I do think @PEZ wants to keep that space there? @brandonstubbs, is there a way to configure that extension to not operate on the .calva-repl file? That may be a reasonable solution if so.

**Comment by PEZ** [comment]
I might have a solution for this. Reopening for realz. 😄
