### ISSUE TITLE
Repl type status bar item showing no repl connection when cljc file open and connected to just clj repl

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#810]
![image](https://user-images.githubusercontent.com/12722744/95640101-00ae0c80-0a50-11eb-9b0e-b405b125c136.png)

Fix for this is coming in a PR soon.

**Comment by PEZ** [comment]
This might be the same bug that causes the button to not toggle from `cljs` to `clj` the first time it is clicked.

**Comment by bpringe** [comment]
Do we have an issue for that? If not, I think we should create a separate one.
