### ISSUE TITLE
Connect to REPL does not work without a project

### ISSUE THREAD

**Issue by alper** [BetterThanTomorrow/calva#811]
I'm editing a CLJ file in a random folder and if I try to Jack-in or Connect to a running REPL the Calva command fails silently.

Two improvements would be nice:

- Give feedback that something didn't work and maybe even why it didn't work (most likely in this case, the fact that this is not a Clojure project, i.e. the presence of a `project.clj` file)
- Make it possible to open a CLJ file anywhere also outside of a project context and just send stuff to a REPL.

**Comment by bpringe** [comment]
So with this, just a note, I think Calva needs to know whether to start a repl via `lein` or `clojure`. The user may have one but not the other on their machine.

**Comment by PEZ** [comment]
We can start with just allowing to connect to a repl.

**Comment by bpringe** [comment]
Let's consolidate and move this discussion to #855.
