### ISSUE TITLE
Add support for "Go to declaration"

### ISSUE THREAD

**Issue by maxrothman** [BetterThanTomorrow/calva#820]
"Go to declaration" and "Peek declaration" are fairly common features for VSCode language extensions. Typically when used on a symbol that has been imported from another file, they move the cursor (or open the peek view) to the import  that adds the symbol to the current namespace. For Clojure, this would mean moving the cursor to the specific vector in the `:require` list in the `ns` form. For example:

```clojure
(ns
  (:require [foo.bar :as f]))
;             ^-----would move the cursor here

(defn something []
  f/baz)
;   ^-----Using "Go to declaration here...
```

**Comment by Hamido-san** [comment]
AFAIK **Go To Definition** [default `F12`] will start working once you've jacked-in to the REPL:
1. open a project folder
2. open a clojure file
3. jack-in and wait for the **terminal > task - calva jack-in** panel to read "nREPL server started..." and such
3. write `(range 1 5)`
4. put the cursor over `range` then hit `F12` and wait a sec
5. calva will open a "core.clj" tab and show you the `defn range` source code

But it doesn't work all the time:
1. once inside the `defn range` source code, put the cursor over `clojure.lang.Range/create` then hit `F12`
2. and nothing; it just fails with a "no definition found" message

**Comment by maxrothman** [comment]
@Hamido-san you are correct, **Go To _Definition_** works fine once the namespace is loaded into the REPL. This request is to add **Go To _Declaration_**

**Comment by marcomorain** [comment]
This should be fixed by the recent addition of Clojure LSP support.

**Comment by bpringe** [comment]
@maxrothman I don't see a Go To Declaration command in VS Code's command palette. Is it normally something a language extension would add, and not something included with VS Code?

@ericdallo Does clojure-lsp have any support for this?

**Comment by ericdallo** [comment]
No, but it's part of the spec [here](https://microsoft.github.io/language-server-protocol/specification#textDocument_declaration), we don't have support yet for that, not hard to implement though for the case on this issue and probably for others that may appear in the future, please open an issue on clojure-lsp for that

**Comment by maxrothman** [comment]
Yep, it looks like it's included, it's called `editor.action.revealDeclaration` in Keyboard Shortcuts.

**Comment by ericdallo** [comment]
Done, available on next clojure-lsp release, the vscode integration would just work OOTB, LMK if any issues.
For more details check [here](https://clojure-lsp.io/features/#find-a-functionvar-declaration-in-the-ns)

![find-declaration](https://user-images.githubusercontent.com/7820865/150697475-060a2931-5403-4e54-80e0-859072bc1476.gif)

**Comment by maxrothman** [comment]
Amazing! Should I close, or do you prefer to do that after it's been released?

**Comment by bpringe** [comment]
If this were a change in Calva, we'd wait, but since it's upstream and this won't be closed automatically, we can close it now and just reopen if needed.

**Comment by ericdallo** [comment]
clojure-lsp was released some days ago, this should be working on calva already

**Comment by bpringe** [comment]
Seems to be working :tada:.
