### ISSUE TITLE
Some keyboard shortcuts missing the languageID check

### ISSUE THREAD

**Issue by kstehn** [BetterThanTomorrow/calva#823]
For Some keyboard shortcuts is the languagID check missing if the shortcut should be active.
I found this  `Calva: Evaluate Top Level Form (defun)` which is bind to `Alt + Enter`.
The problem was i couldnt use the Alt + Enter Shortcut in a diffrent file Type Context because the Calva Shortcut was then used.
Adding `&& editorLangId == 'clojure'` to the when expression fixed this.

I am not sure if there are anymore and if this is needed every time.

**Comment by bpringe** [comment]
Just at a quick glance, this probably should be added to all that Calva keybindings that don't have it.

**Comment by PEZ** [comment]
But then you would lose the ability to evaluate a piece of Clojure code in a markdown file, or similar.

**Comment by bpringe** [comment]
Interesting... is this something that is used often? I didn't even know this was supported :smile:. The collisions with extensions for other file types is concerning, though.

**Comment by PEZ** [comment]
Not sure how often it is used, but it is intentional:

https://github.com/BetterThanTomorrow/calva/blob/master/CHANGELOG.md#119---2018-03-18

Which doesn't mean we must keep it like this, but on the other hand, it has worked to have it like this for quite a while.

**Comment by PEZ** [comment]
Having given this some pondering, I think that it makes sense to free up the shortcuts in non-closure files, and let people use the command palette.
