### ISSUE TITLE
Unable to resolve filesystem provider with relative file path

### ISSUE THREAD

**Issue by nakiya** [BetterThanTomorrow/calva#825]
I have calva installed in VSCode.

I am Just trying to do a REPL jack-in using `ctrl+alt+c ctrl+alt+j`. (This has worked many times in the past.)

Then I get this error: `Unable to resolve filesystem provider with relative file path 'd:\work\projects\formula/.calva/output-window/.clj-kondo'` (`d:\work\projects\formula` is my project folder, I don't see a .calva folder created there though.)

I tried restarting VSCode/machine, moving project location, creating new fresh project, etc and nothing works.

What is wrong and what can I do? I'm not sure if this is a VSCode issue or something related to Calva.

----

Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by bpringe** [comment]
This is related to #821. I'm going to leave this open though since people may search this error and find this issue.

**Comment by bpringe** [comment]
This should be fixed in 2.0.130
