### ISSUE TITLE
Enhancement: Support change in Clojure CLI tools options: -M flag replacing -A for aliases

### ISSUE THREAD

**Issue by practicalli-john** [BetterThanTomorrow/calva#826]
From Clojure CLI tools version 1010.1.697 ownward, the `-A` flag used to include aliases is being deprecated and replaced by `-M` when calling clojure.main.

Calva currently seems to hard-code the use of `-A` flag with aliases that are selected when calling `jack-in` and typing in `-M:alias-name` still uses `-A` flag in the command (as shown in the terminal window output in Calva).

This shows a warning in the terminal output, although the REPL should continue to work as normal
```
> Executing task in folder four-clojure: clojure -Sdeps '{:deps {nrepl {:mvn/version "0.8.2"} cider/cider-nrepl {:mvn/version "0.23.0"} clj-kondo {:mvn/version "2020.04.05"}}}' -A:env/test -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]" <

WARNING: When invoking clojure.main, use -M
nREPL server started on port 44229 on host localhost - nrepl://localhost:44229
```

With some future release of Clojure CLI tools aliases included with `-A` work differently as they currently do.  The challenge though is that -M will not work correctly in Clojure CLI tools before version 1.10.1.697.

Ideally it would be useful to select the use of either `-A` or `-M` flag to use with selected aliases, either in the user interface or a project or user configuration.

As a side note:  From the Calva jack-in user interface, it did not seem aliases defined in the user level configuration (`~/.clojure/deps.edn`).  If this were possible, then aliases from configurations like https://github.com/practicalli/clojure-deps-edn could be used with Calva during jack-in  (although these aliases can be used by starting the repl externally and using Calva to connect)

**Comment by bpringe** [comment]
Thanks!

**Comment by PEZ** [comment]
Regarding user aliases. Calva doesn't read them, that's correct. They can be added via settings, though: https://calva.io/connect/#customizing-jack-in

**Comment by bpringe** [comment]
I wonder if it would make sense for Calva to get the version of clj on the user's machine using `clj -h` or something similar, and use the appropriate flag according to the version seen.

**Comment by jr0cket** [comment]
`clojure -Sdescribe` returns information including the current Clojure CLI tools version.

However, I assume adding a version check adds complexity to the jack-in process which will be redundant sometime in 2021.

At some release in the next few months I think you should just switch over to the -M flag and drop the -A flag.  This is what happened with the Clojure CLI tools itself.

All the official documentation for Clojure CLI tools has been updated

Anyone wishing to keep an unsupported use of the Clojure CLI tool can still use connect instead of jack-in

**Comment by PEZ** [comment]
I woke up today with an intention to add a setting for this. Now I am glad I never got around to that. It is much more reasonable to do what you just suggested, @jr0cket .

**Comment by bpringe** [comment]
Great idea! I very much agree.

**Comment by jeffp42ker** [comment]
Since 1.10.1.672 introduces a new config attribute `:repl-aliases` (and the -M warning), it's been used as crude version test here:  https://github.com/jacobobryant/biff/pull/84

It's simple to grep for it rather than an explicit version check.

**Comment by PEZ** [comment]
I think we'll just add `-M`, and projects holding on to versions that can't handle that will have to start the REPL some other way and use **Calva Connect** instead.

We are a bit past:

> At some release in the next few months

after all. 😄
