### ISSUE TITLE
Connect to a running REPL in your project broken in windows

### ISSUE THREAD

**Issue by FongHou** [BetterThanTomorrow/calva#827]
Hi,

2.0.127 - 129 does not work for connecting lein + shadow-cljs project.
2.0.127 sort of works for lein project, only with "Connection to a running REPL, not in your project" (but still discover nrepl port automatically, a bit strange).

In both cases, ctrl-alt-c ctrl-alt-c does not trigger command menu. ctrl-p command and button in status bar do.

2.0.126 works fine for both type of projects. downgrading seems the only workaround.

Thanks!

**Comment by PEZ** [comment]
This is related to/same as #825.

**Comment by bpringe** [comment]
@FongHou Are you using Windows?

**Comment by FongHou** [comment]
Yes, it's on windows.

Thanks!

**Comment by PEZ** [comment]
Here's a VSIX with this issue fixed. Please give it a try: https://8470-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.130-827-fix-windows-jack-in-193b17e5.vsix

**Comment by FongHou** [comment]
works for me. though I don't use jack-in at all, always connect to nrepl. 

thanks!
