### ISSUE TITLE
Alt+Enter does not work in the repl buffer

### ISSUE THREAD

**Issue by emelens** [BetterThanTomorrow/calva#829]
I am able to use Alt+Enter in file buffer to evaluate a form. But it does not work in Repl Buffer. I had to use Contrl+Enter.

I am using VSCode on Windows Home + Ubuntu on WSL 2

**Comment by bpringe** [comment]
Does this never work for you, or does it only not work under certain circumstances? I've not experienced this before.

**Comment by emelens** [comment]
It is not working when I launch code from ubuntu in WSL2 environment only.

I just created a project under regular windows folder.  Both Alt enter and ctrl enter are working fine in windows file system

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by emelens** [comment]
Unable to reproduce the issue now in WSL. Not sure if it has anything to do with midje repl

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bpringe** [comment]
Thanks for the info.

**Comment by bpringe** [comment]
Closing this since I just realized it's probably the same issue as #767. If I'm mistaken, please reopen.
