### ISSUE TITLE
After connecting to repl I cannot launch any new terminal windows

### ISSUE THREAD

**Issue by gchiaramonte** [BetterThanTomorrow/calva#83]
I just installed Calva and am getting the following error message in VS Code when I connect to the lein repl (cmd + v c). I'm running this on Windows 7 and starting the repl in a cmd.exe window. Then after this any attempt to open a terminal in VS Code gives the same error. nRepl is connected and works, but I cannot open any new terminals. 

"The terminal process command 'C:\WINDOWS\System32\bash.exe' failed to launch (exit code: 2)"

**Comment by PEZ** [comment]
I wonder if Calva has a `bash` dependency by accident. I will check!

**Comment by marcomorain** [comment]
I think this is related to https://github.com/BetterThanTomorrow/calva/issues/64

**Comment by PEZ** [comment]
I would think this is not an issue anymore? Please reopen if I am wrong.
