### ISSUE TITLE
Fix open vsx publish workflow in circle ci

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#830]
It started failing with the following, which is odd because I don't think we've changed anything with this lately:

```
Need to install the following packages:
  ovsx
Ok to proceed? (y) 

Too long with no output (exceeded 10m0s): context deadline exceeded
```

**Comment by PEZ** [comment]
Let's see if I managed to fix this. We'll see next time we publish a new Calva version. 😀

**Comment by bpringe** [comment]
Weird, I knew it was missing that, but didn't even think to check the package.json because I thought surely it worked before so must be there :sweat_smile:

**Comment by PEZ** [comment]
Releasing 2.0.131 proved that this is fixed. 🎉
