### ISSUE TITLE
Better error reporting in editor

### ISSUE THREAD

**Issue by slipset** [BetterThanTomorrow/calva#84]
If you evaluate a fn that doesn’t fit in the current editor window, you get no visual feedback if the evaluation of said function fails. 

I believe the compiler provides file/line/col so it should be possible to add a red squiggly at the pint of failure and maybe even scroll there?

**Comment by slipset** [comment]
<img width="577" alt="screenshot 2018-10-26 at 08 06 16" src="https://user-images.githubusercontent.com/5894926/47547562-42daf380-d8f6-11e8-9e2f-faaab16423f3.png">

As you see from the image above, when the end of the form is above the fold, you see the error, but as you see from the image below, the error is invisible when the end of the form is below the fold
<img width="573" alt="screenshot 2018-10-26 at 08 07 15" src="https://user-images.githubusercontent.com/5894926/47547572-50907900-d8f6-11e8-8f39-9c593c0bee0c.png">

**Comment by PEZ** [comment]
Yeah, for some errors it should be possible to create a problem marker/squiggly.

But otherwise, maybe we can use a different tint on the evaluated region when it has failed?

**Comment by slipset** [comment]
I'd say this is fixed by c15df1981ecac6aea918a465d2b75a77dc740a70
