### ISSUE TITLE
Adding ns form to a newly created clojure file

### ISSUE THREAD

**Issue by zelark** [BetterThanTomorrow/calva#844]
Cursive and Emacs have this feature. It would be nice to have it in Calva too.

When I create a new clojure file, I'd like its ns form is created automatically. For example if a new file is `src/my_app/core.clj`, I'd expect to see `(ns my-app.core)` in it.

To do it we need to add a handler for `workspace.onDidCreateFiles`.
https://code.visualstudio.com/api/references/vscode-api#workspace

Also the [vscode-java](https://github.com/redhat-developer/vscode-java) extension already supports [similar feature](https://github.com/redhat-developer/vscode-java/blob/a7854a12cb948b207968e32cfeeac0eec5c788d1/src/fileEventHandler.ts#L44) for java files.

**Comment by zelark** [comment]
We need a way to collect all current source paths.

**Comment by bpringe** [comment]
Why are all source paths needed?

**Comment by zelark** [comment]
Because to get ns form we need to build a relative path first.
```javascript
function resolvePackageName(sourcePaths: string[], filePath: string): string {
    if (!sourcePaths || !sourcePaths.length) {
        return "";
    }
    for (const sourcePath of sourcePaths) {
        if (isPrefix(sourcePath, filePath)) {
            const relative = path.relative(sourcePath, path.dirname(filePath));
            return relative.replace(/[\/\\]/g, ".")
                           .replace("_", "-");
        }
    }
    return "";
}
```

In general, any directory under a clojure project could be a source path.

There are at least two common ways to get source paths.
1) Read `deps.edn` or `project.clj` (Cursive)
2) Ask nREPL for a classpath and extract source paths from it (CIDER, but also it has a fallback way).

**Comment by zelark** [comment]
Today I made a prototype with a hardcoded source path. Works fine.

**Comment by zelark** [comment]
![ns-form-autocreation](https://user-images.githubusercontent.com/2854582/99277567-ffd27c80-283e-11eb-880f-e2ec6267625d.gif)

**Comment by bpringe** [comment]
Ah, so wherever the file is created you need to find the first parent folder that is a source directory?

**Comment by zelark** [comment]
Right.
