### ISSUE TITLE
Better error reporting in terminal

### ISSUE THREAD

**Issue by slipset** [BetterThanTomorrow/calva#85]
It seems to me that the terminal in calva doesn't report stuff that's happening on stderr
Given
```(.println System/err "foo")```
And `Calva: evaluate current top-level form`, nothing is printed in the Calva terminal.
Expected behaviour would be to see "foo" printed, as I do in the terminal running `lein repl`

A super bonus point wold be a button in the terminal to toggle display of stderr

**Comment by PEZ** [comment]
Hello. I am not sure how to fix this. The terminal REPLs are created using `lein repl :connect`. And it seems that printing via `System/err` (or even `System/out`) only works in the original `lein repl` session. It is the same outside or inside Calva/VSCode. Actually, when you print like that from a connected repl the output ends up in the original session.

**Comment by slipset** [comment]
I seem to remember that I've had this issue before with Cider. Maybe there is a nrepl-setting for this?
maybe @bbatsov knows something about this?

**Comment by bbatsov** [comment]
There's a middleware in `cider-nrepl` to address this - it allows you to re-route the console output of nREPL to the client sessions connected to it. I'm assuming you're referring to this https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/out.clj

Probably at some point we'll have to address this in nREPL itself, as the current "default" situation is quite annoying for connected clients. In the terminal people simply don't notice the problem.

**Comment by PEZ** [comment]
I think this should have been fixed now?
