### ISSUE TITLE
Upgrade cider-nrepl version used by Calva

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#852]
https://github.com/BetterThanTomorrow/calva/issues/427#issuecomment-734099774

https://github.com/clojure-emacs/cider-nrepl/blob/master/CHANGELOG.md

At the time of this writing Calva is using 0.23.0.

**Comment by bbatsov** [comment]
That should be pretty straightforward as most of the changes have been bug-fixes.

**Comment by bbatsov** [comment]
Btw, does Calva have some functionality related to ClojureDocs? I'm asking as I've noticed that the data usage for https://clojuredocs-edn.netlify.app/ has been growing this month and I'm wondering why. An unfortunate design decision in older version of `cider-nrepl` resulted in constant downloads of fresh exports on start, so I'm assuming Calva's growing usage might be related to this.

**Comment by PEZ** [comment]
Those features are lacking in Calva still. We should add it. But first bump `cider-nrepl`, I take it?

**Comment by bbatsov** [comment]
Ideally - yes.

**Comment by PEZ** [comment]
I keep forgetting to add the proper issues to my *fixes* notes. Anyway, this is now done.
