### ISSUE TITLE
Connect to REPL not in project fails: toString of undefined

### ISSUE THREAD

**Issue by holyjak** [BetterThanTomorrow/calva#853]
Issue Type: <b>Bug</b>

1. Install Calva ...133
2. Open a new VS Code window
3. Trigger Connect to running server REPL not in Project 
4. Nothing happens but this error poping up: "Command 'Calva: Connect to a Running REPL Server, not in Project' resulted in an error (Cannot read property 'toString' of undefined)"

Expected: To be asked for host, port.

The dev tools do not contain anything relevant but this

> notificationsAlerts.ts:40 Command 'Calva: Connect to a Running REPL Server, not in Project' resulted in an error (Cannot read property 'toString' of undefined)
> onDidChangeNotification @ breadcrumbsModel.ts:39

Extension version: 2.0.133
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|15, 19, 13|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv|--crash-reporter-id 5c7a26a1-f871-4cd9-b2b3-974197ccffbc|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by holyjak** [comment]
FYI At one point I got this at least partially working with v130 (got stuck at trying to connect to the REPL) but I am not able to replicate it anymore (even after restarting VS Code after the downgrade and opening a real Clojure project instead of an empty window).

**Comment by holyjak** [comment]
The error is somewhat random. After this I downgraded to 130, restarted, still broken. Then I run jack-in, which worked as expected. After disconnecting from it, I could suddenly connect to the server repl.

**Comment by holyjak** [comment]
I am back on 133 and now am getting

```
mainThreadExtensionService.ts:66 TypeError: Cannot read property '0' of undefined
	at /Users/me/.vscode/extensions/betterthantomorrow.calva-2.0.133/out/extension.js:135
	at Generator.next (<anonymous>)
	at /Users/me/.vscode/extensions/betterthantomorrow.calva-2.0.133/out/extension.js:135
	at new Promise (<anonymous>)
	at r (/Users/me/.vscode/extensions/betterthantomorrow.calva-2.0.133/out/extension.js:135)
	at e.calvaJackInOrConnect (/Users/me/.vscode/extensions/betterthantomorrow.calva-2.0.133/out/extension.js:135)
```

**Comment by bpringe** [comment]
Yes, I'd say it's related. Currently Calva requires a directory open in VS Code, partly because the repl/output window is an actual file that's created in the current directory, and also because some other things are stored there (the `.calva` directory). Calva is probably throwing an error while trying to create the folder that this file gets created in.

![image](https://user-images.githubusercontent.com/12722744/100525685-8b210b80-3177-11eb-9f87-37bfc30dfff6.png)


@PEZ What are your thoughts here? Is there another reasonable place on the user's machine we can create the necessary folders/files when they connect to a repl with no directory open in VS Code?

**Comment by bpringe** [comment]
Let's consolidate and move this discussion to #855.
