### ISSUE TITLE
Please make it possible to “jack in” to the REPL without a project

### ISSUE THREAD

**Issue by Hamido-san** [BetterThanTomorrow/calva#855]
I'm pretty sure this is a duplicate of #853 and #811 but after posting [this thread on ClojureVerse](https://clojureverse.org/t/is-there-a-way-to-jack-in-to-the-repl-without-a-project/6809) and being encouraged by @PEZ here we are
Please make this scenario possible:

1. open VSCode
2. click `file` then `new file`
3. click the `plain text` button in the status bar and choose `clojure`
4. click the `nREPL ⚡` button

...and instead of being told **cannot read property '0' of undefined** have Calva jack-in to a sandbox/playground REPL without first having to make a project folder

**Comment by puredanger** [comment]
I would love to see this working. New users often don’t have or understand what a project is and they don’t need one to open a file, jackin and start evaluating Clojure code.

Projects are important as a next step but should not be required.

**Comment by PEZ** [comment]
Indeed. That is a great reason to fix this.
