### ISSUE TITLE
Stop bundling clj-kondo in favor of using it through clojure-lsp

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#868]
This task is for later, after clojure-lsp integration with Calva is released.

Currently there are a couple small issues with clojure-lsp's diagnostics, and until those are fixed, we'll just keep using the clj-kondo extension.

* https://github.com/snoe/clojure-lsp/issues/199
* False 'unused' diagnostics in rich comments: https://github.com/snoe/clojure-lsp/issues/67#issuecomment-533566148
* Make clojure-lsp diagnostics (not ones from clj-kondo) show clojure-lsp as source: https://github.com/snoe/clojure-lsp/issues/116#issuecomment-738495510

Clojure-lsp, at this time, does offer at least one thing clj-kondo does not (that I can tell), and that is showing unused public variables.

![image](https://user-images.githubusercontent.com/12722744/101965029-25e20700-3bc8-11eb-8bcb-c7f71acb0388.png)

`simple` in the above is unused in the code base - clojure-lsp tells me this, but clj-kondo does not (only thing providing diagnostics in the above).

**Comment by ericdallo** [comment]
@bpringe all those issues were fixed :)

**Comment by bpringe** [comment]
Awesome! Thank you, sir.
