### ISSUE TITLE
Calva is slow to delete characters after VS Code 1.52 update

### ISSUE THREAD

**Issue by filipesilva** [BetterThanTomorrow/calva#869]
Between yesterday and today I noticed that VS Code got very slow on cljs and clj files when deleting characters.

I think the only thing that happened between the two times I used VS Code was that it updated to version 1.52. If I turn the Calva extension off, deleting becomes fast again. I'm using Windows 10, connecting to VSCode inside WSL Ubuntu via the VS Code remote functionality.

Here's a video of what I see: https://www.loom.com/share/cd600fe39b864efbb04360a36f9f06e6

I pressed backspace repeatedly, without stopping and with the same frequency, from the start of the video to the point where the deletion stopped. Instead of deleting characters one by one, they were deleted in chunks, and with a delay from the time when I pressed backspace.

**Comment by filipesilva** [comment]
I can confirm that going back to VS Code 1.51 (October version) as instructed in https://stackoverflow.com/questions/49346733/how-to-downgrade-vscode makes editing fast again.

**Comment by filipesilva** [comment]
If you're also running into this, follow the steps in https://stackoverflow.com/a/49347158/2116927 to downgrade. You'll need to manually turn updates on after the issue is fixed.

**Comment by bpringe** [comment]
Thanks for reporting and pointing to info on downgrading. I labeled as upstream, but as Peter said, maybe there is something we can do on our end. Maybe if we give it a little time a fix will come from VS Code, if not, we can start digging into the issue.

**Comment by bpringe** [comment]
I'm not experiencing this on VS Code version 1.52 on l Manjaro Linux. I wonder if the issue it has something to do with the remote functionality.

**Comment by filipesilva** [comment]
That's interesting... I just tried with 1.52.1 again and reproduced again. Is there anything I can do to help narrow down the problem?

**Comment by PEZ** [comment]
Is the problem still there if you disable all other extensions? Thinking it could be some kind of conflict...

**Comment by eliasousa** [comment]
Same here, using WSL2 with Ubuntu 20.04 and VSCode 1.52.1

**Comment by eliasousa** [comment]
> 
> 
> I can confirm that going back to VS Code 1.51 (October version) as instructed in https://stackoverflow.com/questions/49346733/how-to-downgrade-vscode makes editing fast again.

same here, I just downgrade to 1.5.1 and everything back to normal again, thanks @filipesilva

**Comment by bpringe** [comment]
So it seems this issue is only happening with WSL? That's what I see so far.

**Comment by filipesilva** [comment]
I tried disabling all other extensions one by one back on the new version, but then noticed that I couldn't reproduce it anymore. That makes me think it was some kind of problem on the official VSCode Remote WSL extension, because that's the only one that I couldn't really turn off and managed the connection between WSL and Windows.

**Comment by bpringe** [comment]
Thanks for investigating.

**Comment by filipesilva** [comment]
Heya, I think I spoke too soon. I can see the slowness happen again, but I don't think this is inherently related to Calva - it's just that calvafmt might be a bit demanding on the CPU when editing.

Let me explain a bit better. My setup is Calva while running a Shadow CLJS build, and I am not using a repl connection to Calva.

When using VSCode 1.51.1, task manager shows WSL as using 0-2% CPU. But when using VSCode 15.2.1, there's a constant 12-19% CPU usage. If I turn off the Shadow CLJS server or close VSCode, this drops to 0-2%.

https://github.com/microsoft/vscode-remote-release/issues/4205 details similar slowness with the Remote WSL extention on the same version change.

If I follow the steps in https://github.com/microsoft/vscode-remote-release/issues/4205#issuecomment-748974231, I get a 0-2% CPU usage at rest. But if I remove that var, I see a 15%-20% CPU usage.

So I think what's happening here is that the VSCode remote extension is not playing well with Shadow CLJS.
