### ISSUE TITLE
Make REPL prompt submit if the cursor is after the top level form

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#875]
In this Youtube video about how to use VS Code with Calva the demo breaks down because the author does not understand how to evaluate code at the REPL prompt. Its quite painful to watch:

https://www.youtube.com/watch?v=4BA1Od_d9Qw

So. I've prepared some changes that should help users figure this out easier:

1. The REPL prompt will submit on `enter` if the cursor is behind the top level form entered at the prompt.
2. The first prompt printed has a message instructing to use `alt+enter` for evaluating forms.

**Comment by bpringe** [comment]
Awesome! I was just thinking about this again recently.
