### ISSUE TITLE
Red squigglies under compile errors

### ISSUE THREAD

**Issue by slipset** [BetterThanTomorrow/calva#89]
In cider, when evaluating a form with an error, a red squiggly is drawn under the offending form:
![screenshot 2018-11-28 at 08 55 30](https://user-images.githubusercontent.com/5894926/49137203-0b43da80-f2ec-11e8-844c-02f553c80630.png)

I'd think you'd get all the info you need wrt `file` `line` and `col` from the compiler exception
This would make a great addition to Calva!

Also, note that the CompilerException has `ex-data` from version 1.10 which makes this quite a lot easier

**Comment by PEZ** [comment]
Thanks! Of course it would be nice to implement this in a way that it works with older Clojure too, but solving it for only 1.10 would be worth it too.

**Comment by mseddon** [comment]
The way `cider` and `figwheel` handle this sort of behaviour is to catch `clojure.lang/Compiler$CompilerException`  [see here](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/Compiler.java#L6814), which contains the source/column information needed.

**Comment by sauvala** [comment]
Letting others also know in here (in additional to Slack) that I'm working on this.

**Comment by cfehse** [comment]
This is implemented in version 2.0.49.
