### ISSUE TITLE
Bring in refactorings we get access to via clojure-lsp

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#890]
Now that [clojure-lsp is giving Calva more power](https://clojureverse.org/t/calva-gets-static-analysis-features-via-clojure-lsp/), we can also reach in and get access to the `clj-refactor` things it [exposes](https://github.com/snoe/clojure-lsp#refactorings).

Related to #137 #861 #798 (and possibly more feature requests).

**Comment by bpringe** [comment]
Also I think #598 is related

**Comment by bpringe** [comment]
This was released in version 2.0.138 :tada:. Thanks @pez. :smiley:
