### ISSUE TITLE
Step into (F11) does not go inside dependency source code

### ISSUE THREAD

**Issue by seralbdev** [BetterThanTomorrow/calva#893]
Hi team
I would like to report an issue about the debugger. I have a project using a dependency from a project in my local disk (Clojure source code). When I debug the code in Emacs (function instrumented) and I go IN (i) the function I can step by step debug in the source code of the dependency. Emacs "jumps" automatically to the dependency source code

When I do the same in calva (F11) it doesn't behave in the same way. I lose control and system seems to be frozen?
The dependency is installed by lein install in the local .m2 maven cache and the original source code is accessible. The behaviour is different but both are installed in the same laptop...

I am a Clojure beginner...maybe it is lack of knowledge?
I am attaching videos and source code to reproduce

Many thanks in advance and keep to good work! Calva is getting really strong

https://user-images.githubusercontent.com/46577538/103149768-e80ae400-476c-11eb-8c49-8b93f0faf3cb.mp4

https://user-images.githubusercontent.com/46577538/103149771-eb9e6b00-476c-11eb-9efe-c9a2ef8596ed.mp4

[test.zip](https://github.com/BetterThanTomorrow/calva/files/5742945/test.zip)

**Comment by bpringe** [comment]
Thanks for the repro case. I see this error in Output -> Log (Window) after it hangs on that step into:

```sh
Error: cannot open file:///jar%3Afile%3A/home/brandon/.m2/repository/testlib/testlib/0.1.0/testlib-0.1.0.jar%21/testlib/core.clj. Detail: Unable to read file '/jar:file:/home/brandon/.m2/repository/testlib/testlib/0.1.0/testlib-0.1.0.jar!/testlib/core.clj' (Error: Unable to resolve non-existing file '/jar:file:/home/brandon/.m2/repository/testlib/testlib/0.1.0/testlib-0.1.0.jar!/testlib/core.clj')
```

The path we get from cider-nrepl saying where the next breakpoint is looks like this: `jar:file:/home/brandon/.m2/repository/testlib/testlib/0.1.0/testlib-0.1.0.jar!/testlib/core.clj`.

I suspect we need to handle this in some way that `vscode.workspace.openTextDocument` likes. It's this line that the execution is not getting past: https://github.com/BetterThanTomorrow/calva/blob/e01831329339cd411bc0d6d8c4994f09ffe81acf/src/debugger/calva-debug.ts#L181

I suspect the function called in the line above doesn't handle this case correctly. I'll play around with it more and see if I can figure out what needs to be done. @pez might have some insight here about opening files inside of jar's.

**Comment by bpringe** [comment]
I get it a little further by passing a vscode.Uri to `openTextDocument` instead of a string path. This causes our text document content provider to be called which handles jar files: https://github.com/BetterThanTomorrow/calva/blob/e01831329339cd411bc0d6d8c4994f09ffe81acf/src/providers/content.ts#L14

What seems to be failing now is VS Code using the `StackFrame` returned from `stackTraceRequest` to navigate to the code. I think something different needs to be passed when constructing the `Source` there.

**Comment by bpringe** [comment]
This should be fixed in the next Calva release :tada:

**Comment by seralbdev** [comment]
That was fast ;)
Excellent news & great job
Thanks so much 🙏

**Comment by bpringe** [comment]
You're welcome, and thank you for the detailed report.
