### ISSUE TITLE
Goto definition not working for dependent libs since 2.0.137

### ISSUE THREAD

**Issue by FongHou** [BetterThanTomorrow/calva#897]
Like clojure-lsp integration. Two things I noticed:

1. auto completion (goto/peek definition) does not work for namespaces from dependent libs. I remember standalone clojure-lsp supports these. Are they disabled in calva version?

2. After connecting to nrepl, goto/peek definition still does not work for external dependent libs. They used to work in 2.0.136.

Thanks!

**Comment by PEZ** [comment]
Hello. Are you on Windows perhaps?

**Comment by FongHou** [comment]
Hi, yes i am on windows.

**Comment by PEZ** [comment]
It might be a problem upstream. https://github.com/clojure-lsp/clojure-lsp/issues/223

We are going to release a workaround so that we use nrepl definitions when they are available. Later today.

**Comment by bpringe** [comment]
> auto completion

Also, completions, as in when you're typing, are disabled from lsp. They should still work from Calva with a repl connection though. We plan to add completions from lsp soon though. It's a bit quirky, and might suffer from this Windows issue too, but we'll see.

**Comment by PEZ** [comment]
This should be working now, right?

**Comment by bpringe** [comment]
Yes, should be. If anyone sees otherwise, please let us know.
