### ISSUE TITLE
Jack-in prompting for nrepl port since terminal jack-in change

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#901]
Since the recent jack-in change, I'm getting a prompt for the nrepl port at jack-in. This doesn't happen every time though. Maybe it's a race condition related to the .nrepl-port file that's created.

![image](https://user-images.githubusercontent.com/12722744/103251806-4c75a100-492f-11eb-9e33-5f9f558230db.png)

**Comment by bpringe** [comment]
This appears to be working fine too now. :roll_eyes: See comments of #903.

**Comment by bpringe** [comment]
This is actually still happening intermittently, at least with leiningen, on linux.

**Comment by PEZ** [comment]
I wonder what is going on here. #952 just in. 

It smells race condition to me. Something in the promise-spagetti. 😄

**Comment by clyfe** [comment]
[This](https://github.com/BetterThanTomorrow/calva/blob/published/src/nrepl/jack-in.ts#L60) is a todo, yes? We can fix like [this](https://github.com/clyfe/calva/commit/267a76b4de1e697cab012d666b57f6c0ca930245)?

**Comment by bpringe** [comment]
Thanks for looking into this @clyf. That's a neat solution. I think using `fs.watch` or `fs.exists` would be more idiomatic here. Watch for it to exist with a timeout, then when it does, read it. Here's an example of using `fs.watch`: https://stackoverflow.com/questions/26165725/nodejs-check-file-exists-if-not-wait-till-it-exist

**Comment by PEZ** [comment]
This is very much like the code we have replaced. 😄

So, we used to base this on a file watcher, but now we are picking up the port from the stdout of the nrepl server when it starts. The fix will be about figuring out why the port number sometimes fails to be relayed/picked up by the connector.

Since I have never seen this happen it is a bit extra tricky for me to do the bug hunt. But for you who have seen it, if you can run Calva in dev mode and place a breakpoint right where the prompt is shown, the call stack should give us some hints.

**Comment by bpringe** [comment]
What was the reason for moving away from the file watcher? Just wondering.

**Comment by PEZ** [comment]
It's just unnecessary complexity to involve the file system when we are speaking to the process directly. The reason we did it via the watcher before was that we didn't have this access then.

**Comment by clyfe** [comment]
Race is: the "get port from file" code overwrites the "port from regex" with nothing when the ".nrepl-port" file is not yet present at the time is read. Fix: remove "get port from file" code.

**Comment by clyfe** [comment]
In hindsight, does "get port from regex" cover all lein/deps/fig/shadow cases?  
Do we want to have the file as fallback?

**Comment by PEZ** [comment]
Not even with the 20/20 hindsight. 😄 This goes back a long while. The watcher has caused me so much grief.

But you're right to be wanting to cover all bases here. The regex covers the bases you mention. Even babashka (which doesn't even write an nrepl-port file). We have yet to add support for babashka jack-in, but that is what got me to finally finish up the changes. Anyway, what we need is to make the regex configurable. We do that for some other regexes in the jack-in/connect sequences, so this should be quite easy to add.
