### ISSUE TITLE
Make injected libs qualified

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#905]
Using clojure cli version 1.10.1.763 at jack-in the following deprecation messages are shown:

![image](https://user-images.githubusercontent.com/12722744/103304262-06ffb500-49bd-11eb-8564-4f11c21141a1.png)

We should make these libs qualified to get rid of these messages.

**Comment by PEZ** [comment]
Isn't that fixed with 140?

**Comment by bpringe** [comment]
Ah yes, sorry! Had a past vsix installed in my VM.
