### ISSUE TITLE
Copy pretty-printed eval result

### ISSUE THREAD

**Issue by frantic** [BetterThanTomorrow/calva#91]
Would be nice to have a command that copies the result of the evaled expression to the clipboard. Currently VSCode doesn't allow selecting the inline output Calva adds.

For example, executing "Calva: Evaluate and copy" would result in this output and `4` being in your system clipboard.
![image](https://user-images.githubusercontent.com/192222/49682535-ad8d5c00-fa6a-11e8-9071-e5672e751e08.png)

**Comment by marcomorain** [comment]
A command to copy the last result (`*1`) would be awesome. It would also prevent having to doulble up on all commands (Eval, eval and copy, eval file, eval file and copy, ...).

**Comment by PEZ** [comment]
Even better! Maybe how we should do with some of the other commands as
well? Pretty print (which doesn't even work today) and replace inline, for
instance.

**Comment by PEZ** [comment]
So, now there's a command for copying the last results to the clipboard. It doesn't pretty print it yet, but that is because I need to do something about pretty printing as such. Let me know how this works and wether pretty printing is very missed. (Default keybindings are `ctrl+alt+v ctrl+c`).
