### ISSUE TITLE
Improve clojure-lsp jar integration

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#913]
This is a bit of a brainstorm issue, for now at least. Currently, we don't know what version of clojure-lsp Calva is using since we just package a `clojure-lsp.jar` file in the vsix.

It would be nice if we could use a release tag from the clojure-lsp repo to know what version Calva is using. This tag could either be committed with Calva, but also we could have a default that gets bumped sometimes, but allow the user to change the tag via config.

This starts to get into possibly making Calva download clojure-lsp instead of packaging it with the vsix. Is it possible and reasonable to download and save a file to someone's machine from an extension?

1. User installs the Calva extension
2. Calva checks some location for clojure-lsp (wherever we'd download it to)
3. If it's there and it's the latest version (we can include the release tag in the jar file name), then don't download it, just start clojure-lsp using the existing jar
4. If it isn't there, download it, then start it

Thoughts, @pez?

**Comment by bpringe** [comment]
We'd possible need to consider sometimes needing to use a custom version of clojure-lsp that doesn't line up with the upstream repo, but so far it seems we can avoid that, which I think would be best.

**Comment by PEZ** [comment]
I agree it would be good to make this configurable by the user. Like we now do with the nREPL dependencies. Even if that has its downsides too.

No idea how possible it is. But I would be a bit surprised if we would find it very hard to do.

As for an lsp that isn't lined up with upstream. It doesn't seem we would need that so far, let's hope it stays like that. 😄
