### ISSUE TITLE
Option to not show repl window on startup

### ISSUE THREAD

**Issue by jr0cket** [BetterThanTomorrow/calva#922]
It would be very useful to not show the REPL output in a widow, to save space for the actual source code and test code windows.

Could there be a Calva configuration setting to define if the REPL output window should be displayed when starting the REPL?

This is the approach taken in Spacemacs and the majority of people I know who use Spacemacs.  The REPL buffer is not show by default, although it can be opened if required.  Personally I almost never have a separate REPL output window / buffer shown 

This follows the advice of Stuart Halloway who encourages the Clojure community to not type into the REPL directly.  Using the REPL directly is less efficient than using the source code buffers and evaluating inline or using data inspectors.

Sometimes the REPL is used to log output, which is also very inefficient especially as logs get longer.  There are well established ways to view logs more efficiently than in the REPL (using mulog and elasticsearch) 

When using data inspector tools (portal, reveal, rebel) also provide a more effective way to view, navigate and visualize results of evaluation, minimizing the need for an actually REPL output display.

Thank you.

**Comment by PEZ** [comment]
Makes sense. I thought we had such an option already. What you can do as a workaround is to have the output/repl window in the same window group as your other files.Then it won't take up space.

**Comment by bpringe** [comment]
> The REPL buffer is not show by default, although it can be opened if required. Personally I almost never have a separate REPL output window / buffer shown

I know this comes down to personal preference a bit, but for the sake of making the repl window less of a required thing to view output, I just want to link this enhancement that may improve this experience, which Calva used to have: https://github.com/BetterThanTomorrow/calva/issues/736

**Comment by PEZ** [comment]
Indeed. We should consider reinstating that hover!
