### ISSUE TITLE
Calva does not show stack trace when loading a file fails

### ISSUE THREAD

**Issue by pikeview** [BetterThanTomorrow/calva#93]
I have core.clj file
I imported another another ui.clj namespace in core.clj via (:require)

when I changed the ui and saved and loaded the file (ctrl, enter or ctrl+alt+v enter), calva did not show any errors in compilation..

I realized that there were errors only after restarting the repl

**Comment by bpringe** [comment]
I've noticed this as well. I only know there must be errors in a file by looking at the Calva Says window. If I evaluate the file and see `nil` or `no results` in this window, something is probably wrong. It would be nice to see the error to know what went wrong.
