### ISSUE TITLE
So many caches 😀

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#930]
Starting Calva and jacking in currently means creating three **clj-kondo** caches and then some `.lsp.` cache files as well. The `.clj-kondo` caches are:

1. clojure-lsp creates one in `.clj-kondo/cache`
1. the clj-kondo extension then creates one in `.clj-kondo/.cache` (because the `.clj-kondo` directory exists because of 1.)
1. The clj-kondo we inject at Jack-in, for the same reasons, creates yet another on in `.clj-kondo/.cache` (different version subfolder)

There's a picture here that tells this story: https://github.com/BetterThanTomorrow/calva/issues/917

Although this is to some extent going to be dealt with upstream, (hopefully as upstream as well https://github.com/clj-kondo/clj-kondo/issues/1113, but we'll see about that), we should probably consolidate our use of `clj-kondo` some. I know we are heading towards using the linting via `clojure-lsp`. Is there also a way we can use the `clj-kondo` analysis via the lsp, maybe? That would make it easier to use the debugger too.

**Comment by PEZ** [comment]
Thanks. Updated the issue with the correct path.

**Comment by bpringe** [comment]
> Is there also a way we can use the clj-kondo analysis via the lsp, maybe?

I've been thinking about this for some time. Created an issue.

**Comment by bpringe** [comment]
After updates to both Calva and Clojure-lsp, only one cache directory is created now at `.clj-kondo/.cache`.
