### ISSUE TITLE
Use clojure-lsp for usages for debug instrumentation decorations, and stop injecting clj-kondo at jack-in

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#931]
This way we can remove a jack-in dependency, as well as stop an unnecessary cache directory from being created (I think - see #930).

This would, of course, increase our dependency on clojure-lsp for existing features, making it harder to disable. However, I think in a short time we won't be concerned with allowing it to be disabled and can make Calva lean into it as a requirement, as it already tentatively does :smile:.

**Comment by ericdallo** [comment]
Also adds the feature that users wouldn't need to jack in to have linter feature :)

**Comment by bpringe** [comment]
To be clear, they don't currently need to jack-in for linting, as this is provided from the clj-kondo VS Code extension. This is related specifically to the debugger and how it "highlights" what functions are instrumented for debugging, as seen in the gif at the top here: https://calva.io/debugger/

**Comment by ericdallo** [comment]
Oh, got it 😅
