### ISSUE TITLE
calva.jackInEnv set env not work when use Environment variables

### ISSUE THREAD

**Issue by paomian** [BetterThanTomorrow/calva#933]
I start a repl and get an error.

```
lein update-in :dependencies conj '[nrepl,"0.8.3"]' -- update-in :dependencies conj '[clj-kondo,"2020.04.05"]' -- update-in :plugins conj '[cider/cider-nrepl,"0.25.6"]' -- update-in '[:repl-options,:nrepl-middleware]' conj '["cider.nrepl/cider-middleware"]' -- repl :headless
Error: Could not find or load main class ${env:JVM_OPTS}
```
my setting.json
```json
"calva.jackInEnv": {
        "JVM_OPTS": "${env:JVM_OPTS} -Darchaius.configurationSource.defaultFileName=paomianl_config.properties -Dorg.quartz.properties=quartz.properties"
    }
```
I don't know this situation is clava or vscode or my setting is wrong?but my setting work on outdated version。

**Comment by paomian** [comment]
rollback to 2.0.138 can resolve this error.

**Comment by paomian** [comment]
and the latest version go to definition is too slow on my project.but 2.0.138 is fast.

**Comment by PEZ** [comment]
We changed the jack-in process control mechanism in [v2.0.139](https://github.com/BetterThanTomorrow/calva/releases/tag/v2.0.139), which must have caused this problem. The problem with the environment variable that is. Not sure right now how to fix it, since I think it is that the Task system has special support for that syntax, that we don't get when we use childprocess directly. I'll have a look.

That slowness probably is due to our clojure-lsp introduction. Please file a separate issue about it.

**Comment by PEZ** [comment]
It looks like we have lost this functionality, unfortunately. I wasn't aware we had it, but see from your use that it was useful....

I am now thinking how you can work around this, @paomian. And if there is something for your use case that we can make Calva assist with in some other way. If I understand it correctly you need to pass compiler options to Leiningen, while you also have  some options in your current environment?

**Comment by paomian** [comment]
> If I understand it correctly you need to pass compiler options to Leiningen, while you also have some options in your current environment?

yes and this project is development by multi person.I do't want add some env to project.clj because it is tracked by git.Other person can get this env config too.
Can you add some other config to set env can support `Environment variables`.

**Comment by PEZ** [comment]
I see. It seems to be a really useful feature being able to use existing environment variables. So I have prepared a PR adding that specific resolve to the `jackInEnv` entries. Which should mean that your current configuration will work.

Please help me test it by installing this VSIX in your vscode: https://9860-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.147-933-jack-in-resolve-env-vars-e5b20ba1.vsix

**Comment by paomian** [comment]
It work for me!
