### ISSUE TITLE
Error looking up classpath info in ClojureScript projects

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#939]
I think between 146 and 148 it has started to pop up a message about _ Error looking up classpath info_ when clojure-lsp starts in ClojureScript projects.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/30010/104092293-4fec1f00-5283-11eb-9e40-e83cce0cae9e.png">

I can't see that it affects how Calva works.

**Comment by bpringe** [comment]
This was added by @ericdallo to clojure-lsp after we discussed it. Basically, if the classpath lookup fails, clojure-lsp will not work properly. We've had a user or two already wonder what was going on and we had to debug with them to find this info in the logs. This way it's immediately apparent that something is wrong, and they aren't confused why things aren't working.

**Comment by ericdallo** [comment]
Exactly ☝🏻 , @PEZ check your `/tmp/clojure-lsp.out` log for more info on why this lookup failed

**Comment by bpringe** [comment]
I was typing what Eric said above, basically :smile:. There could be something that needs to be better defaulted in clojure-lsp for certain typical clojurescript setups, or you may have a non-typical setup and need to add something to your `.lsp/config.edn` :project-specs -> :classpath-cmd.

**Comment by ericdallo** [comment]
Yes I suspect, since I'm not a clojurescript developer I don't know the common setup for it, if you know or have any suggestion let me know

**Comment by PEZ** [comment]
i think the message, the way it is delivered, makes it feel like something is broken. Before i realized things were actually working I restarted, then reinstalled vs code.

**Comment by bpringe** [comment]
@ericdallo Maybe it should be a warning instead of an error, worded like "Classpath lookup failed in clojure-lsp. Some features may not work correctly." Just a thought.

It is true though, in a way, that something is broken. Some things won't work.

**Comment by ericdallo** [comment]
Actually, without a successful classpath lookup, things like find definition on jars may not work

**Comment by ericdallo** [comment]
Yes, I can change that

**Comment by ericdallo** [comment]
https://github.com/clojure-lsp/clojure-lsp/pull/246
