### ISSUE TITLE
Support remote repl connection?

### ISSUE THREAD

**Issue by FongHou** [BetterThanTomorrow/calva#94]
One typical use case is starting a remote nrepl session on server in aws cloud, then have vscode connect through ssh tunnel to that remote nrepl (+ ssh-fs sync project files). Some features still work, e.g. completion, hover docs, evaluation. however, goto and peek definition do not work anymore because source paths are different on the local machine (typically Windows) and remote server (Linux). It'll be a great enhancement if some kind of file path translation can happen automatically. My guess is that source files under project root should be a simple case to handle, might need to add config settings to handle maven repo and java sdk source jars.

Thanks

**Comment by PEZ** [comment]
That should be perfectly doable. I'll investigate it.

**Comment by mtnygard** [comment]
This would be a good feature to implement via VSCode's new "remote" packages. Remote-SSH or Remote-WSL would both enable this and would not require as much Calva-specific code.

**Comment by PEZ** [comment]
@mtnygard , according to reports, the Remote-WSL case should work: https://github.com/BetterThanTomorrow/calva/wiki/VS-Code-Remote-Development

(If I understand your suggestion, and the wiki page, correctly.)

**Comment by mtnygard** [comment]
@PEZ That works fine with WSL 1. Microsoft is moving to a new approach for WSL 2, which is based on a full VM. WSL 2 is only available via the fast ring of MS Insiders right now, so it's still in beta. I'm giving it a test now.

There's something funny about the IP address assigned to the VM though. Remote-WSL works, but Calva cannot connect to the REPL running in that VM. 

Microsoft states in the release notes that the IP address situation is temporary, though, so it may not be worth doing anything special in Calva.

**Comment by PEZ** [comment]
@mtnygard , thanks! I didn't know about WSL 2. Please keep this thread updated with any developments on that. And let me know if there is something I can do in a Calva build for testing something out. I don't have Windows and can't afford a Mac that lets me run Windows, so can't participate in the testing out of WSL 2 or anything WSL, really, in other ways than shooting you others test builds.

**Comment by cfehse** [comment]
his should all be possible with new vscode remode-ssh or remote-wsl extensions. I tested this setup today with calva version 2.0.49 and it worked correctly. I close this issue for now.
