### ISSUE TITLE
Cannot connect to nrepl server when there is no Internet connection

### ISSUE THREAD

**Issue by alzadude** [BetterThanTomorrow/calva#95]
Hi there,

It seems that Calva is unable to connect to a running nrepl server when my laptop is "offline", i.e. there is no active Internet connection (for example because the wifi is disconnected or is in flight mode).

As a test, I tried to connect using ``lein repl :connect localhost:xxxxx`` in a different terminal, and that works fine (whether there is an active Internet connection or not). So it seems the issue is specifically with Calva itself?

When I issue the command to connect, I am looking out for the ``Hooking up nREPL sessions..`` message in the `Calva says` output, but it doesn't appear.

It would be really useful to be able to use Calva when I am offline for some reason (e.g. there is no Internet connection available).

Any clues? I'm on Windows 10.. Can anyone reproduce this on other platforms?

Thanks!

**Comment by mseddon** [comment]
Hi there!

Just tried this myself, but didn't have an issue under Windows 10. I am using a wired ethernet, and tested by disabling the adaptor. `Calva: Connect` did the right thing and I had no issue for me. Do you have any other devices in your network adapters? Perhaps something is up there.

I will continue testing on various other devices in case I can trigger it my end in the meantime. Thanks!

**Comment by alzadude** [comment]
> Just tried this myself, but didn't have an issue under Windows 10. I am using a wired ethernet, and tested by disabling the adaptor. 

Hi @mseddon is this a desktop? Could you try on a laptop without being connected to any wifi hotspot?

> Do you have any other devices in your network adapters?

I have an L2TP vpn connection.

> Also, (perhaps) - is vscode and the java runtime allowed through the firewall (public + private)?

I didn't make any changes here, but I'm assuming you didn't either so I'm doubtful the problem is with the firewall..

The bit I'm struggling to understand is why manually running `lein repl :connect localhost:xxxxx` in a terminal works fine, even without an Internet connection, but Calva itself is not able to connect (even though it's issuing the same command). The only other thing worth mentioning is that in VS Code, I'm using WSL (Linux) as the integrated shell rather than cmd.

Thanks!

Alex.

**Comment by PEZ** [comment]
> but Calva itself is not able to connect (even though it's issuing the same command)

Calva does not really connect using that command, but instead has an nREPL client that opens a socket connecting to the nREPL server. Only when that connection is established, Calva *then* opens up a session in the vscode built in terminal using that command.

Internally Leiningen has an nREPL client for its connection. So the difference is probably that Calva's client is sensitive to that condition on your laptop, but Leiningen's isn't.

I'm wondering if, while we are in this state of ignorance about the actual condition, can find a workaround. Maybe try connecting to `0.0.0.0` instead (you might need to instruct the nrepl server to listen there, but I don't think so). Or maybe there is a way to set up a fake connection…

**Comment by PEZ** [comment]
@alzadude , can you check if this is still an issue for you? We have made some radical changes in the nrepl connection that just might have effects on this issue.

**Comment by alzadude** [comment]
Hi @PEZ,

I just tried again with version 1.3.61, here are my results:

1.  Using `lein repl`

    Binds to `127.0.0.1:port` according to `netstat -an`

    Connecting to `localhost:port` in Calva: **fail**
    Connecting to `127.0.0.1:port` in Calva: **pass**

2. Using `clj` with a `nrepl-server` alias in `deps.edn` 

        {:extra-deps {cider/cider-nrepl {:mvn/version "0.18.0"}
              cider/piggieback {:mvn/version "0.3.9"}}
         :main-opts ["-m" "nrepl.cmdline"
             "--middleware" "[cider.nrepl/cider-middleware,cider.piggieback/wrap-cljs-repl]"]}

    Binds to `0.0.0.0:port` according to `netstat -an`

    Then using `calva.connectREPLCommand` defined as `clj -Sdeps '{:deps {reply {:mvn/version \"0.4.1\"}}}' -m reply.main --color --attach`

    Connecting to `localhost:port` in Calva: **fail**
    Connecting to `127.0.0.1:port` in Calva: **pass**

    So it seems that overriding the default `localhost:` prompt to specify `127.0.0.1` works around the issue. I say "works around" rather than "fixes" since it's a bit fiddly to type `127.0.0.1` every time I connect. I can't say if this is a different result compared with the version of Calva for which I originally reported the issue, since I don't recall trying to connect using `127.0.0.1` on that version.

    Also, with approach 2. I get the following warnings from the nrepl server when connecting, I don't know if they're significant but it seems to work "ok" regardless:

        WARNING: An illegal reflective access operation has occurred
        WARNING: Illegal reflective access by cider.inlined_deps.orchard.v0v3v0.dynapath.v0v2v5.dynapath.defaults$eval3889$fn__3890 to method java.net.URLClassLoader.addURL(java.net.URL)
        WARNING: Please consider reporting this to the maintainers of cider.inlined_deps.orchard.v0v3v0.dynapath.v0v2v5.dynapath.defaults$eval3889$fn__3890
        WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
        WARNING: All illegal access operations will be denied in a future release

**Comment by cfehse** [comment]
The problem should not exist with version 2.0.49.
