### ISSUE TITLE
Paredit sexp select should unselect in reverse

### ISSUE THREAD

**Issue by clyfe** [BetterThanTomorrow/calva#954]
`paredit.selectBackwardSexp` & `paredit.selectForwardSexp` are bound to modifier keys + left/right arrows.
If I Mod+Right twice and select two sexps, then I Mod+Left: it selects a third sexp one on the left.
I'd like that Mod+Left **to deselect** the last selected sexp insted. On text this is the standard words selection behavior.

If we'd have `paredit.unselectBackwardSexp` & `paredit.unselectForwardSexp` we could toggle chords behavior via `when` & `editorHasSelection`.

**Comment by PEZ** [comment]
Should work with shrink selection, right?

**Comment by clyfe** [comment]
Ideed, it does. Although in this case I'd need flags `paredit.selectionGrownAtLeft` & `paredit.selectionGrownAtRight` to conditionally make the other arrow shrink.
