### ISSUE TITLE
"Extract function" refactoring doesn't work as expected with selections

### ISSUE THREAD

**Issue by svdo** [BetterThanTomorrow/calva#958]
Unless I'm misunderstanding the intended behaviour, I feel "extract function" extracts too much. For example, with this code:

```clojure
(= 3 (+ 1 2))
```

I then select the part `(+ 1 2)` and apply the "extract function" refactoring.

Expected: I get a new function that does `(+ 1 2)`.

Actual: I get a new function that does `(= 3 (+ 1 2))`.

Calva 2.0.151

**Comment by bpringe** [comment]
@Ericdallo What's your input here? (This would be a clojure-lsp issue since we just defer to it for this.)

**Comment by ericdallo** [comment]
I can't reproduce the issue with Emacs using clojure-lsp, @bpringe is Calva sending the correct `line` and `col` arguments to the `extract-function` refactoring?

**Comment by ericdallo** [comment]
![extract](https://user-images.githubusercontent.com/7820865/104951996-66d8f280-59a2-11eb-90f9-c3b6cdb77a8b.gif)

**Comment by bpringe** [comment]
I'll look into it. Thanks!

**Comment by bpringe** [comment]
@svdo It works for me if my cursor is where Eric's is above. So you are _selecting_ the whole form of `(+ 1 2)`? I do see the problem if I select it. The refactorings go off of the current cursor position.

We use `editor.selection.active` for the line and character values, but maybe we should be using `editor.selection.start`... 

@ericdallo What happens in Emacs if you select `(+ 1 2)` and then run the refactor?

**Comment by ericdallo** [comment]
It works too selecting the region on Emacs @bpringe

**Comment by bpringe** [comment]
Ok, I think my above solution will work. This is in lsp.ts in the registerLspCommands function, @svdo, if you feel like making a PR :smile:. If not I'll get to it some time later after finishing other things.

**Comment by svdo** [comment]
For context, for me personally being able to do it with a selection is what happens most. Without having a selection, I sometimes get unexpected results; for example in the attached video I want to extract only the map (because in reality it is a huge nested thing). Without having a selection, the whole (outer) form is extracted. Maybe because it takes the contents of the enclosing `( )`? So instead I select the dictionary and try to extract that, which then doesn't work. 


https://user-images.githubusercontent.com/4028554/104954732-17f28380-59c9-11eb-849b-6a3d99b2605a.mov

**Comment by svdo** [comment]
> Ok, I think my above solution will work. This is in lsp.ts in the registerLspCommands function, @svdo, if you feel like making a PR 😄. If not I'll get to it some time later after finishing other things.

I would absolutely _love_ to do that, but just to manage expectations, I'm not going to be able to do it this week...

**Comment by bpringe** [comment]
No problem, was just throwing it out there. Regarding your above example, if your cursor is at the beginning or the end of the map it should work (it does for me, extracts just the map), but maybe you are saying it's convenient to have your cursor anywhere in the middle of the map and expand selection to select the whole map, then run the command. The above-mentioned solution should fix that.

**Comment by bpringe** [comment]
I've fixed it in the linked PR, but a recent change in clojure-lsp that broke the extract-function command, so once [that issue](https://github.com/clojure-lsp/clojure-lsp/issues/263) is fixed, we can update clojure-lsp in that PR and merge.
