### ISSUE TITLE
Jack-In doesn't start the repl when there are non-strings in `jackInEnv`

### ISSUE THREAD

**Issue by kstehn** [BetterThanTomorrow/calva#959]
So on the latest version of calva (2.0.151) the jack-in doesn't work on windows.
There seems nothing to happen only the output file gets opened and thats it.

I tested by installing older calva version to see what changes might be the problem.
The version 2.0.148 works fine. 
My guess would be that something is wrong with the jack-in env.
I jack-in env-variables but nothing like referencing other env-variables.
Mostly simple strings, number and booleans.
Only two variables are a bit more complex because they are edn-string maps.

Tested on Windows with latest VS-Code version.

**Comment by PEZ** [comment]
I suspect our env-variable interpolation regex gets tripped up on those more complex edn-string maps then. Can you try to isolate it a bit?

**Comment by kstehn** [comment]
Mhm dont know.
We have three kinds of map:
Simple: `"{:big 150000 :small 400000}"`
Nested: `"{:default {:url \"https://domain:port\" :label-key \"label\"}"`
A bit more complex: `"{:classification [{:match {\"identifier\" \"suche\"} :regex {\"label\" \"FOOO.*\"}:=> :big}]}"`

**Comment by bpringe** [comment]
Have you verified that jack-in works if you're not using env variables? Just wondering if it's isolated to that.

**Comment by kstehn** [comment]
Sorry forgot this to do.
I just checked the funny thing is those examples arent the problem but more like
`"calva.jackInEnv": {
 "test_bool": true,
 "test_integer": 100,
 "test_string": "foo"`

when i remove test_bool and test_integer the jack-in works

**Comment by bpringe** [comment]
It seems maybe it has problems with any env values besides strings, but I haven't looked into it. We'll see what @pez says since he was working on this.

**Comment by PEZ** [comment]
Thanks for the clarification. It was very mysterious until then. 😄 Now there's a PR for you to review.

**Comment by kstehn** [comment]
I tested the vsix and looked at the changes. 
It works fine now with the non-string envs.
