### ISSUE TITLE
Better colors for light themes

### ISSUE THREAD

**Issue by ghost** [BetterThanTomorrow/calva#96]
<img width="106" alt="janusdeployment yml charli-account-provisioning-service 2019-01-07 14-52-25" src="https://user-images.githubusercontent.com/33130874/50798075-da13de00-128b-11e9-82af-adf44853dfbd.png">

This is pretty hard on the eyes. Quite frankly, I'd prefer to have a default of the main statusbar foreground color for the enabled repl and a slightly transparent version of that for the disconnected repl. Barring that, we should probably let the user override the colors somehow.

The "bracket-pair-colorizer" extension lets you specify colors as so:

``` json
    "bracket-pair-colorizer-2.colors": [
        "#AC362D",
        "#3BA3F8",
        "#E826AE",
    ]
```

while VSCode lets you override syntax/workbench colors on a per-theme basis like so:

``` json
"workbench.colorCustomizations": {
        "[Alabaster]": {
            "statusBar.background": "#F0F0F0",
            "statusBar.foreground": "#000028",
            "statusBar.noFolderBackground": "#F7F7F7",
            "statusBar.noFolderForeground": "#000028",
        },
        "[Night Owl]": {
            "activityBar.background": "#000C1D",
            "activityBar.border": "#102a44",
            "sideBar.background": "#001122",
            "sideBar.border": "#102a44",
            "sideBar.foreground": "#8BADC1"
        },
        "[Quiet Light]": {
            "statusBar.background": "#AC3543"
        }
    },
```

for customization purposes, I'd prefer the latter, but understand if we can't do this in a plugin.

**Comment by cfehse** [comment]
This is fixed with version 2.0.49.
