### ISSUE TITLE
Clj-kondo config doesn't seem to be picked up anymore

### ISSUE THREAD

**Issue by svdo** [BetterThanTomorrow/calva#961]
We have a custom clj-kondo config in our project, it lives in `.clj-kondo/config.edn`. After one of the recent Calva updates, where the clj-kondo plugin was replaced with the lsp version, the config file doesn't seem to be picked up anymore. I conclude this from the linter errors on the things we configured have re-appeared. Please let me know if there is any information that you need to nail this down.

Calva version: 2.0.151

**Comment by bpringe** [comment]
This is an upstream issue. I created an issue there and it's linked above. Hopefully a solution comes soon. In the meantime you can roll back to Calva version v2.0.149, which uses the clj-kondo extension.

**Comment by svdo** [comment]
It's not _that_ annoying 😉

**Comment by bpringe** [comment]
Oh, actually, I think you may be able to configure clj-kondo still through `.lsp/config.edn`. https://clojure-lsp.github.io/clojure-lsp/settings/#project

Please try this and let me know.

**Comment by bpringe** [comment]
I'm actually seeing that the config in `.clj-kondo/config.edn` _is_ being read and respected by clojure-lsp. For example, if I put the following in that file:

```edn
{:linters {:missing-docstring {:level :warning}}}
```

Then the missing doc string warnings show up, when they weren't there before.

What's your OS?

**Comment by svdo** [comment]
I'm on macOS. Could it be that the auto-generated `.calva/.clj-kondo/config.edn` is interfering? I'll try tomorrow.

**Comment by bpringe** [comment]
Doesn't seem like it interferes on my machine (Linux). We shall see. But strange that at least the above config seems to work. I don't see why only certain config settings would work.

**Comment by svdo** [comment]
Ok I think I found why it stopped working in my case. We have a monorepo with the following structure:

```
|
+–– projects
    |
    +–– common
    |
    +–– project1
    |
    +–– project2
```

Each of these `project[12]` folders had their own `.clj-kondo/config.edn`. We open the root of the repo (i.e. including all projects) in Calva. When I create a `.clj-kondo/config.edn` at top level, it does work. But the project-level config does not work. When I open just one of the projects in VSCode, then it does work again.

Conclusion: apparently only the config in the root of the workspace is used, not the one where the project actually resides.

Now for how this _should_ behave. For me it's not necessarily a bad thing to have the config on top level. It even removes some duplication. I do think however that project-level overrides are also a good thing to support. And with the top-level config, the config does not work when I only open one of the projects in VSCode, because there is no config anymore in there.

In general, in situations like this, I tend to think it is nice to have a config at the project level, _and_ one at top, one overriding the other in case of conflicts. For clj-kondo, this should not be tied to Calva/VSCode in any way (think CI), so "top" should maybe be defined as the folder where the `.git` folder is or something like that? I wonder how @borkdude feels about this? This could be a clj-kondo feature instead of a calva/clojure-lsp feature.

**Comment by PEZ** [comment]
Totally agree about the wanted behaviour of top level config + overrides downstream. It gets tricky when you open a sub project standalone, but that's fine, I think.

**Comment by borkdude** [comment]
The clj-kondo VSCode extension has specific logic to find a .clj-kondo parent directory relative to the currently linted file:

https://github.com/clj-kondo/clj-kondo.lsp/blob/e9a7b8c14be92dba27398fc667ed36845b3f6efb/server/src/clj_kondo/lsp_server/impl/server.clj#L106-L123

This was added after getting repeatedly the feedback that the config wasn't picked up if someone edited a file outside the workspace or in mono-repos (we use exactly the same mono-repo setup as @svdo btw).

Normally clj-kondo starts looking for the .clj-kondo parent dir from the current working directory upwards. In other editors the current working directory is set to the parent dir of the currently linted file, except in VSCode. That is why this patch was only needed for VSCode. I suggest taking this over in Calva, or LSP and not change the behavior to "you need a .clj-kondo in the same dir as .git" since the repo organization like Stefan and mine should be supported.

**Comment by svdo** [comment]
> Normally clj-kondo starts looking for the .clj-kondo parent dir from the current working directory upwards. In other editors the current working directory is set to the parent dir of the currently linted file, except in VSCode. That is why this patch was only needed for VSCode. I suggest taking this over in Calva, or LSP and not change the behavior to "you need a .clj-kondo in the same dir as .git" since the repo organization like Stefan and mine should be supported.

That makes a lot of sense to me.

**Comment by borkdude** [comment]
On the other hand, I guess it couldn't hurt if this code was moved to clj-kondo itself and applied to the case when only linting a single file. Maybe the problem also manifests itself when using LSP with emacs or other editors... 

I guess I'll move it to clj-kondo so it's solved forever and always.

**Comment by borkdude** [comment]
Fixed in version `2020.12.13-20210119.103318-40` deployed on clojars. cc @PEZ @bpringe @snoe @ericdallo

**Comment by borkdude** [comment]
Sorry, I think there is a bug. Hold on.

**Comment by borkdude** [comment]
Use version `2020.12.13-20210119.110530-42` rather than the above one. 

It's important to set `:filename` to the absolute path of the file being linted. This allows you to lint from stdin while still picking up the config dir relative to the file. Clj-kondo will only try to resolve the relative config when `:filename` is being passed explicitly.  Else it will fall back on the current working dir.

See the clj-kondo extension:

https://github.com/clj-kondo/clj-kondo.lsp/blob/e9a7b8c14be92dba27398fc667ed36845b3f6efb/server/src/clj_kondo/lsp_server/impl/server.clj#L132-L136

**Comment by bpringe** [comment]
@svdo Please check if this works in 2.0.154.

**Comment by svdo** [comment]
I just tried with 2.0.155; it doesn't work yet. The top-level monorepo config works (like before), but the per-project config in the monorepo does not work.

**Comment by borkdude** [comment]
@svdo Can you test by executing `clj-kondo`, the binary, from the top-level monorepo directory and then lint a file in the sub-project?

```
clj-kondo --lint sub-project/src/foo/bar.clj --filename sub-project/src/foo/bar.clj
```

If `sub-project/.clj-kondo` exists, the config should be picked up from there, even though the current working dir is the top-level project. If not, then it's a bug in clj-kondo.

EDIT: use clj-kondo version 2021.01.20.

**Comment by svdo** [comment]
I'm afraid that doesn't work either. The attached screenshot should tell the whole story I think.

<img width="1497" alt="Screenshot 2021-01-28 at 13 24 16" src="https://user-images.githubusercontent.com/4028554/106138890-ffbef900-616c-11eb-9582-184ae651c4ac.png">

**Comment by borkdude** [comment]
@svdo `--filename`, not `--file`

**Comment by svdo** [comment]
Oops sorry about that. Yes like that it also finds the config in the subfolder.

**Comment by bpringe** [comment]
So maybe it's not a clj-kondo issue? I wonder then if it's something to be fixed in clojure-lsp. CC @ericdallo

**Comment by ericdallo** [comment]
Not sure if makes sense but probably clojure-lsp is always linting from the project root so configs in subfolders are not being picked up? is this make sense?

**Comment by borkdude** [comment]
@ericdallo It depends. I made a commit in clj-kondo to explicitly support the above desired behavior:

https://github.com/clj-kondo/clj-kondo/issues/1135

Once again, you should set `:filename` explicitly to indicate you are linting from an editor and then clj-kondo will use that path to search for the config dir upwards, regardless of working dir. 

**Unless you set config-dir explicitly**.

https://github.com/clj-kondo/clj-kondo/blob/92ea01f32e9d7f735de463f2672cb57c1aee6a41/src/clj_kondo/core.clj#L95-L98

**Comment by borkdude** [comment]
@ericdallo It seems you are overriding the config-dir here:

https://github.com/clojure-lsp/clojure-lsp/blob/fe50704d5e14009d4eeeb5a88a451d0ef4474838/src/clojure_lsp/crawler.clj#L75

**Comment by borkdude** [comment]
When crawling / initializing the entire cache, I think you should also take the mono-repo scenario into account by detecting existing .clj-kondo directories and crawling projects separately.

**Comment by borkdude** [comment]
@svdo What can also be the case: maybe LSP is getting confused now that you have both a top-level .clj-kondo dir and sublevel .clj-kondo dirs. Maybe try removing the top level one.

**Comment by svdo** [comment]
> @svdo What can also be the case: maybe LSP is getting confused now that you have both a top-level .clj-kondo dir and sublevel .clj-kondo dirs. Maybe try removing the top level one.

Nope that doesn't help :)

**Comment by ericdallo** [comment]
@borkdude so should we remove the `config-dir` and add the `:filename` of the current linted file

**Comment by borkdude** [comment]
@ericdallo 

I think that should work for linting a single file from the editor.

But what about when initializing the cache? What .clj-kondo will be used in monorepo projects?
E.g.:
```
$project/.git
$project/subproject1/.clj-kondo
$project/subproject2/.clj-kondo
```

**Comment by ericdallo** [comment]
@borkdude ATM clojure-lsp will try to find the .clj-kondo from the project-root (which is sent by the LSP client), so if the user configured to set the project root as the `subproject1`, it'll search from there up to `/`

**Comment by ericdallo** [comment]
Emacs for example, with `lsp-mode` asks what is the project root on the first project run.

**Comment by borkdude** [comment]
@ericdallo OK, in that case,  not overriding `:config-dir` and passing `:filename` for linting a single file should be a sufficient fix.

**Comment by ericdallo** [comment]
Got it, I'll make that fix so for linting the current file only, thank you!

**Comment by bpringe** [comment]
@ericdallo Any update on this?

**Comment by ericdallo** [comment]
@bpringe, sorry I forgot about this one, would you mind create an issue on clojure-lsp for that with a basic repro?

**Comment by bpringe** [comment]
> would you mind create an issue on clojure-lsp for that with a basic repro?

@svdo Would you mind doing this since you created this issue and have more experience with the issue?

**Comment by ericdallo** [comment]
Fixed on latest clojure-lsp release, could you confirm the fix @svdo or @bpringe ?

**Comment by svdo** [comment]
Thanks @ericdallo!

I assume this requires an update of Calva before I can test it, right @bpringe?

**Comment by bpringe** [comment]
New Calva version is out with the latest clojure-lsp. Please test @svdo.

**Comment by bpringe** [comment]
Oops, I think I forgot to commit the upgraded lsp before releasing. :facepalm: Releasing a new version now.

**Comment by bpringe** [comment]
@svdo, new version is out now.

**Comment by svdo** [comment]
I'm getting a bit confused about what is supposed to work and what is not, but this is how it now works for me:

1. If I have NO top-level config in the mono-repo, and I DO have a config file in one of the project folders, then it is picked up correctly
2. If I DO have a top-level config in the mono-repo, and I have NO config file in the project folder, then the top-level config IS NOT picked up

So it seems that (1) is fixed, but (2) is now broken. Even running clj-kondo from CLI with both `--lint` and `--filename` doesn't pick up the config in that scenario.

By the way if I have both config files, one overwrites the other apparently; one might imagine them being merged, but I imagine that's not supported atm.

**Comment by ericdallo** [comment]
Sorry for the confusion @svdo, we found another bug related to that [here](https://github.com/BetterThanTomorrow/calva/issues/1026), it was already fixed on `clojure-lsp`, but Calva needs to release a new version using that version

**Comment by ericdallo** [comment]
But probably it won't fix your issue with (2) since it's not working even with raw clj-kondo, WDYT @borkdude ?

**Comment by borkdude** [comment]
@svdo 

1. nice, that is how it's supposed to work
2. this is not how it's supposed to work. can you make a repro for this that I can invoke with a CLI? then I'll have a look.
3. if you have both, only the first one closest to the linted file is used. you cannot have two .clj-kondo directories since this is the central location in which the cache is stored. You can however include the config from the top-level project with `:config-paths [".."]`

**Comment by svdo** [comment]
@borkdude I setup a repo for this. I took the opportunity to explore Sourcehut for this occasion: https://git.sr.ht/~svdo/cljkondoconfigtest. Running the `demo.sh` script should explain the issue. I put the output that I'm getting in the README. HTH!

Good to know about `:config-paths` by the way, that is going to be useful!

**Comment by borkdude** [comment]
@svdo To make the top-level config effective, you have to remove the entire `.clj-kondo` dir in the subproject. Adding `rm -rf projects/app/.clj-kondo` to the script makes that work.

**Comment by svdo** [comment]
@borkdude Ah I see, that explains it! Would you consider making that more 'robust' by specifically checking for `config.edn`? The reason is that I sometimes open the project at subfolder level in Calva, which will automatically create that folder. But I guess I can also make it work by referring to the top-level config from the project folder, like you mentioned the other day.

**Comment by borkdude** [comment]
> Would you consider making that more 'robust' by specifically checking for config.edn?

That would be a breaking change since the only requirement for a cache to be used it to create a .clj-kondo config, as documented here:

https://github.com/clj-kondo/clj-kondo#project-setup

So no.

**Comment by svdo** [comment]
That makes sense. The `:config-paths` probably is the nicer solution anyway. Once I figure it out. ;)

**Comment by PEZ** [comment]
I'm closing this issue. If there are any remaining issues that should be fixed in Calva, please open new, targeted, issues for those things.
