### ISSUE TITLE
Outline feature not working under certain situations on Windows

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#962]
Eric Uitbeijerse mentioned this issue on slack and provided this repro project: https://github.com/eu400000/Calva-VSC-Outline-Issue

**Comment by bpringe** [comment]
When the server starts up and the outline is not working, I'm seeing this in `/tmp/clojure-lsp.out`

```
INFO  clojure-lsp.main: Starting server...
INFO  clojure-lsp.main: ====== LSP nrepl server started on port 50132
INFO  clojure-lsp.main: Initializing...
INFO  clojure-lsp.crawler: Crawling dir c:\Users\brand\development\Calva-VSC-Outline-Issue\src
WARN  clojure-lsp.parser: Cannot read file:///c:/Users/brand/development/Calva-VSC-Outline-Issue/src/calva_vsc_outline_issue/core.clj Assert failed: (string-of? s r/linebreak?)
INFO  clojure-lsp.crawler: Crawling dir c:\Users\brand\development\Calva-VSC-Outline-Issue\test
INFO  clojure-lsp.crawler: Crawling dir C:\Users\brand\development\Calva-VSC-Outline-Issue\src
WARN  clojure-lsp.parser: Cannot read file:///C:/Users/brand/development/Calva-VSC-Outline-Issue/src/calva_vsc_outline_issue/core.clj Assert failed: (string-of? s r/linebreak?)
INFO  clojure-lsp.crawler: Crawling dir C:\Users\brand\development\Calva-VSC-Outline-Issue\test
INFO  clojure-lsp.crawler: skipping classpath scan due to project hash match
DEBUG clojure-lsp.main: :initialize 7426 ()
INFO  clojure-lsp.main: Initialized #object[org.eclipse.lsp4j.InitializedParams 0x1293fd59 InitializedParams [
]]
WARN  clojure-lsp.main: #object[org.eclipse.lsp4j.DidChangeConfigurationParams 0x4a78e127 DidChangeConfigurationParams [
  settings = {"clojure-lsp":{}}
]]
WARN  clojure-lsp.parser: Cannot read file:///c:/Users/brand/development/Calva-VSC-Outline-Issue/src/calva_vsc_outline_issue/core.clj Assert failed: (string-of? s r/linebreak?)
DEBUG clojure-lsp.main: :didOpen 176 ()
DEBUG clojure-lsp.main: :documentSymbol 3 ([:codeAction #{1460476772100}])
```

I think this issue is the problem: `WARN  clojure-lsp.parser: Cannot read file:///c:/Users/brand/development/Calva-VSC-Outline-Issue/src/calva_vsc_outline_issue/core.clj Assert failed: (string-of? s r/linebreak?)`

This is related to this issue in clojure-lsp: https://github.com/clojure-lsp/clojure-lsp/issues/194. Seems it may have trouble with CRLF line endings.

CC @ericdallo

**Comment by bpringe** [comment]
Confirmed on Linux that it worked at first, but if I change the line endings in VS Code from LF to CRLF, save the file, then open the project again, the Outline says "No symbols found...."

![image](https://user-images.githubusercontent.com/12722744/104973854-f7b3cc00-59aa-11eb-841d-4493a948252e.png)

![image](https://user-images.githubusercontent.com/12722744/104973861-fbdfe980-59aa-11eb-8d09-630963bde4b3.png)

**Comment by ericdallo** [comment]
Again, probably this issue will be solved with https://github.com/clojure-lsp/clojure-lsp/pull/261 since we will remove the `parser` ns replaced by clj-kondo analsys, let's check after the merge if it fixes the issue

**Comment by ericdallo** [comment]
@bpringe not sure https://github.com/clojure-lsp/clojure-lsp/pull/261 fixed that, could you test it again?

**Comment by bpringe** [comment]
Outline seems broken on my linux machine now :smile:. Issue here: https://github.com/clojure-lsp/clojure-lsp/issues/276

**Comment by bpringe** [comment]
This works in clojure-lsp 2021.01.26-22.35.27

**Comment by bpringe** [comment]
This is still not working for the project linked in this post, on Windows.

**Comment by bpringe** [comment]
Update: It does actually work. I may have tested with an older version of clojure-lsp by accident.
