### ISSUE TITLE
Feature: Expose formatting functions in extension api

### ISSUE THREAD

**Issue by clyfe** [BetterThanTomorrow/calva#964]
Basically [this](https://github.com/clyfe/calva/commit/e4a6b7ce828f0860293318d818e50bc6423823fd). Allows [this](https://github.com/clyfe/vscode-calva-setup/blob/master/powertools/killSpaceBackward.js). Yay/nay?

**Comment by bpringe** [comment]
Deferring to @PEZ. Looks okay to me at first sight.

**Comment by PEZ** [comment]
It allows much more than that. The formatter API is not currently intended for public consumption. Today we can change our mind about all of it at a whim, since we are the only consumers. If we expose it like this, that would change the situation quite dramatically.

**Comment by clyfe** [comment]
Closing as I can do without (for now) by using commands and inspecting the document.
