### ISSUE TITLE
[DEP0005] DeprecationWarning: Buffer() is deprecated

### ISSUE THREAD

**Issue by clyfe** [BetterThanTomorrow/calva#970]
This pops up in the console when Calva installed:

> (node:35955) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

This must come from a dependency that calls `Buffer()`, upgrading deps should fix.

**Comment by PEZ** [comment]
We upgrade.dependancies all the time. We have had this message for very long. This is a matter of finding out which dependency.

**Comment by PEZ** [comment]
Closing this as it mainly concerns us in the Calva team and we are constantly reminded by the message itself anyway. Risks confusing users into thinking that something is wrong.
