### ISSUE TITLE
Load file command not loading changes since last file save on Windows

### ISSUE THREAD

**Issue by eu400000** [BetterThanTomorrow/calva#975]
-> Running a changed test (also for the other test commands) requires the .clj file with the tests to be saved before the updated test is recognized

Repro steps:
> lein new app calva-test
Goto VSC and start the repl
"Run tests in current namespace" to run the default test
Changes the default test in core_test.clj (like change the 1 in a 2)
"Run tests in current namespace" to run the default test
-> test is still the old test

PS: The other command to run the test produce the same results.

As bringe indicated, a save should not be required.

----
dangercoder Yesterday at 3:38 PM
Does anyone else have issues with running tests through "Run tests in current namespace"? When I redefine my tests, calva doesn't understand that they have been updated.

8 replies

dangercoder  1 day ago
I also tried to reload the whole shebangs into the repl.
If I run the tests through the repl without Calva, things works fine though :slightly_smiling_face:

bringe  1 day ago
Please create an issue with repro steps. I've not experienced this myself, but maybe it's a particular case, or something has broken.
:+1:
1

Eric Uitbeijerse  24 hours ago
@dangercoder It still works fine for me, but I do have to save all the files after I update the tests (Ctrl-K S)

bringe  19 hours ago
It shouldn't require a file save, if it does there is a bug. For me, I can run a failing test, make it pass, not save the file, "run tests in current namespace" and it passes. (edited) 

Eric Uitbeijerse  12 hours ago
Would be nice if it does not require a file save, that would save some time. I'll have another look at it later on and report back.
:+1:
1

dangercoder  2 hours ago
Tests understands the updates when I save the file manually

dangercoder  2 hours ago
Thanks for the tip @Eric Uitbeijerse

bringe  1 hour ago
A save is not supposed to be necessary since the test command reloads the file, and is not necessary for me. An issue would be appreciated.

**Comment by Dangercoder** [comment]
Having the same issue, I haven't tried it on OSX yet.

**Additional Context**
Calva: Version 2.0.152
OS: Windows - Version 10.0.18363 Build 18363
The tests are written using clojure.test .
Works fine if I manually save the file or run the tests from the REPL.

**Comment by bpringe** [comment]
@eu400000 You experienced this issue on Windows as well, correct?

**Comment by eu400000** [comment]
@bpringe , correct (and sorry the late reply, I'm new to github and just noticed that these messages go to the wronf e-mail address).

**Comment by bpringe** [comment]
Interesting thing I found: This actually seems to be an issue with the load-file command, at least on Windows. Before tests are run, the test ns is loaded in order to get the latest version of the tests. This seems to work on Linux. On Windows, I noticed that if you change any code in any ns, then load the file without saving it, then evaluate the changed code, you won't see the new changes.

With the below code in the core.clj file in a new lein app on Windows:

```clojure
(def x "pass")

(comment
  x)
 ```
 
 If `x` is defined as `"pass"` then I change it to `"fail"`, run the load file command without saving the file, then evaluate `x` again, it still says `"pass"`.
 
@PEZ, I'm going to look more into this, just pinging you in case you know off hand why this happens. I'm guessing this is a regression, but no telling how long it's been doing this.

**Comment by bpringe** [comment]
Found the issue - it's a uri matching problem here: https://github.com/BetterThanTomorrow/calva/blob/9185f160b242569f87ad2e527c83848cf5093e9a/src/utilities.ts#L333

I'll fix it soon 😃.

**Comment by eu400000** [comment]
Aha, so I guess this also removes the need to save any changes in a .clj file before using 'Evaluate Current Form' Ctrl+Enter on Windows (I thought that was just a 'feature'). That will save some more clicks :-)

**Comment by bpringe** [comment]
I was not aware that command was affected in this was as well, but hopefully this fixes it if so. :smile: FYI - there's also the setting "Eval on Save" which will evaluate the file on save. I used to use it but don't any more. You may find it useful though.
