### ISSUE TITLE
Stop printing to the output window when all evaluations are interrupted

### ISSUE THREAD

**Issue by livtanong** [BetterThanTomorrow/calva#978]
# How it happened

Accidentally evaluated a function that ended up outputting about 5k lines worth (And each line was of substantial length as well) of material onto the REPL. Interrupting evaluation didn't work because it was already evaluated, so it's a bottleneck of printing.

# Thoughts
The following is a summary of what @bpringe has said to me about the matter:

The output window queues up prints and uses the `applyEdit` function of the VSCode API. Because `applyEdit` is async, it happens after evaluation, and it's slow in general, which is why printing seems to happen in chunks with what appears to be a pause in between each chunk.

The solution will likely lie in clearing this queue, which should be pretty easy because it's just an array.

**Comment by bpringe** [comment]
Just to verify, you are talking about stdout material being printed, not the eval result, right?

**Comment by livtanong** [comment]
Yes, that is correct!
