### ISSUE TITLE
`Go to definition` doesn't work when value has a comma in the end

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva#98]
If I `f12` (go to definition) on the `foo` inside the map it works
```
(def foo :bar)
{:baz foo :aaa :bbb}
```

However if I do the same now it returns `No definition found for 'foo,'`
```
(def foo :bar)
{:baz foo, :aaa :bbb}
```

Clojure prety much ignore commas, but some people use them for readability following https://github.com/bbatsov/clojure-style-guide#opt-commas-in-map-literals

**Comment by mseddon** [comment]
This definitely looks like a lexer issue in calva, thanks!

**Comment by claynon** [comment]
It's working :)
thanks for the very quick fix
