### ISSUE TITLE
Custom commands for selected forms

### ISSUE THREAD

**Issue by sauvala** [BetterThanTomorrow/calva#986]
Hi,

I already asked about his in the Slack channel and now I posted this issue here for tracking. 🙂 

I would like to be able to define custom REPL-commands with keyboard shortcuts that could, for example, wrap the current form or top level form inside `tap>` function. This would make interacting with other tools easier, like tapping evaluation results to Reveal.

Clover-plugin has support for this:
https://github.com/mauricioszabo/clover#custom-commands

**Comment by PEZ** [comment]
It's happening. Here's a snapshot VSIX of the feature in development. https://10533-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.157-986-custom-snippets-variables-6783ff1a.vsix

I'm tapping lke crazy to Reveal now. 😄 

See the PR for some more details: #993
