### ISSUE TITLE
Doesn't print to Output when evaluating the whole file

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva#99]
in a file that contains only
```
(prn :foo)
```
if I evaluate only the top level form (`ctrl+alt+v SPC`) in the `Output` tab (`Calva says`) it's printed as expected:
```
Evaluating:
(prn :bar)
out: :bar
=> nil
```
however if we evaluate the whole file  (`ctrl+alt+v Enter`) the `out:` is not printed, this is what is printed there:
```
Evaluating file: <path-to-the-clj-file-evalutated>
=> nil
```

**Comment by PEZ** [comment]
Thanks! This is probably just something we have missed with the file evaluation command. I'll have a check.

**Comment by claynon** [comment]
I don't know if it has anything to do with this issue but when using cider the loading buffer would run my [midje](https://github.com/marick/Midje) tests. However on calva with `ctrl+alt+v Enter` they don't get run, while with `ctrl+alt+v SPC` they do get run, which is bit annoying since there can be several tests in a namespace

**Comment by PEZ** [comment]
We might be using the wrong op when evaluating the file. Ping @mseddon who is looking at these things a bit as we talk.

**Comment by PEZ** [comment]
I believe this is fixed now?
