### ISSUE TITLE
Add command for copying jack-in command to clipboard

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#992]
I've done this process several times, especially when I'm working on a Calva feature that requires the repl and I want to leave the repl running in a terminal external to VS Code.

1. Start jack-in
2. Copy the command
3. Kill the jack-in terminal process

It would be nice if I could just run a command that copies the jack-in command that would be run to my clipboard, instead of having to do the steps above. I don't think the command needs a default keybinding. I'd be fine just running it from the command palette.

**Comment by PEZ** [comment]
I've been wanting this for very long!

**Comment by bpringe** [comment]
Marked as dev too because for me it would improve my Calva dev experience.
