### ISSUE TITLE
Jack-in on windows, "RemoteException"

### ISSUE THREAD

**Issue by plexus** [BetterThanTomorrow/calva#997]
Jack-in fails with this output:

```
powershell.exe clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version ""0.8.3""} cider/cider-nrepl {:mvn/version ""0.25.7""}}}'  -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
java.exe : Downloading: cider/cider-nrepl/0.25.7/cider-nrepl-0.25.7.pom from clojars
At C:\Users\IEUser\scoop\modules\ClojureTools\ClojureTools.psm1:338 char:5
+     & $JavaCmd -classpath $ToolsCp clojure.main -m clojure.tools.deps ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Downloading: ci...om from clojars:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Jack-in process exited. Status: 1
```

I'm a complete noob when it comes to PowerShell, but some googling seems to suggest that this is powershell seeing any output on stderr and treating it as an error. This [stackoverflow post](https://stackoverflow.com/questions/2095088/error-when-calling-3rd-party-executable-from-powershell-when-using-an-ide) has several proposed solutions (if that is the problem).

Environment: 
- Windows 10 VM as [supplied by Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) (MSEdge on Win10 (x64))
- Java and Clojure installed through scoop

The context here is that with @lambdaisland we're trying to come up with beginner-friendly setup instructions for Clojure on various platforms. Here's a video recording where you can see the exact steps from a blank VM to this error https://www.youtube.com/watch?v=lZojdfY_Cx4 .

This might not be strictly a Calva issue, but I'm posting it here since other Calva users may be affected, and maybe folks here have an idea where to start looking.

**Comment by plexus** [comment]
Some more data points, when running the command inside Powershell it works fine when leaving off the powershell.exe. With the powershell.exe it seems there's some quoting issue going on.

```
PS C:\Users\IEUser> clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version ""0.8.3""} cider/cider-nrepl {:mvn/version ""0.25.7""}}}'  -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
Downloading: nrepl/nrepl/0.8.3/nrepl-0.8.3.jar from clojars
Downloading: cider/cider-nrepl/0.25.7/cider-nrepl-0.25.7.jar from clojars
WARNING: When invoking clojure.main, use -M
nREPL server started on port 52899 on host 127.0.0.1 - nrepl://127.0.0.1:52899
```

```
PS C:\Users\IEUser> powershell.exe clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version ""0.8.3""} cider/cider-nrepl {:mvn/version ""0.25.7""}}}'  -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

PS C:\Users\IEUser>
```

**Comment by bpringe** [comment]
I've seen that last thing I believe in my Windows VM too. At least, if I start a repl myself I need to exclude the `powershell.exe` in the front.

Not sure if this is related but it might shed more light on the issue: https://github.com/BetterThanTomorrow/calva/issues/387#issuecomment-768338988

> I eventually realised Calva is using legacy Windows Powershell (powershell.exe) rather than the newer multi-platform Powershell (pwsh.exe). Once I had installed Clojure CLI tools using the clj on Windows instructions in Windows Powershell (previously they were installed in multi-platform Powershell only) then Calva jack-in worked as expected.

**Comment by PEZ** [comment]
Please try the VSIX from #1004 and see if that works better. For your convenience I'll paste the first version of the VSIX here: https://10624-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.157-1000-deps-launcher-setting-d01ecb63.vsix

**Comment by plexus** [comment]
```
c:\Users\IEUser\.vscode\extensions\betterthantomorrow.calva-2.0.157-1000-deps-launcher-setting-d01ecb63\bb.exe --clojure -Sdeps "{:deps {nrepl/nrepl {:mvn/version,""0.8.3""},cider/cider-nrepl {:mvn/version,""0.25.8""}}}"  -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
Could not find C:\Users\IEUser\.deps.clj\1.10.1.763\ClojureTools\clojure-tools-1.10.1.763.jar
Attempting download from https://download.clojure.org/install/clojure-tools-1.10.1.763.zip
Downloading: cider/cider-nrepl/0.25.8/cider-nrepl-0.25.8.pom from clojars
Downloading: cider/cider-nrepl/0.25.8/cider-nrepl-0.25.8.jar from clojars
nREPL server started on port 49863 on host 127.0.0.1 - nrepl://127.0.0.1:49863
```

Looks great :star_struck: :heart_eyes:
