### ISSUE TITLE
Unexpected newline character in the output

### ISSUE THREAD

**Issue by zelark** [BetterThanTomorrow/calva#998]
If a string you want to print is more than 1024 characters, Calva adds the newline character at the end of a chunk.

```
(->> (repeat 25 (apply str (repeat 50 \.)))
     (clojure.string/join \newline)
     (println))
```

```
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
....
..............................................
..................................................
..................................................
..................................................
..................................................
nil
```

https://github.com/BetterThanTomorrow/calva/blob/9185f160b242569f87ad2e527c83848cf5093e9a/src/evaluate.ts#L67-L69

Any idea how it can be fixed?

UPD. Tеsted it in Clover and lein repl, works as expected.

**Comment by bpringe** [comment]
So expected behavior is to have no newline printed at any point, right? I have no idea off-hand without looking into it why it would print a newline. @PEZ Is this intentional for any reason? If not, a PR would be welcome if you want to look into it @zelark.

**Comment by PEZ** [comment]
I have tried to fix this before. Not really figured it out. Something with nrepl buffer size...

**Comment by zelark** [comment]
I also tried to fix it on Calva side but failed. Probably we need to look how it is arranged in other nrepl clients.

Maybe @bbatsov can suggest something.

**Comment by bbatsov** [comment]
I'm assuming that Calva is printing a new line on each chunk of the output or something like this. Generally it's a good idea to have check whether a chunk is just a chunk or the final chunk. Generally if a chunk is smaller than the max chunk size it's fairly certain that this is the final chunk.

**Comment by PEZ** [comment]
Thanks, @bbatsov . That's probably it.

I previously tried to tackle this by changing the chunk size, but failed at getting it to be anything else but 1024. But of course, that is not the right way to go about it anyway.

**Comment by bbatsov** [comment]
There's one more implication of streaming - how to syntax highlight results, while they are being streamed (you can't just apply font-locking to each chunk individually, as those are going to be partial Clojure forms). I'm guessing VS code is more flexible here and can re-highlight everything from the begining on each chunk delivered or something like this, but with Emacs it's very tricky and I've cheated a bit - I syntax-highlight in CIDER's REPL only single-chunk results and apply no syntax highligting otherwise.

**Comment by PEZ** [comment]
There are two parsers in play in Calva. But both will generally just render broken syntax highlighting while the structure is broken, and it will fix itself when the structure is ok again. 😄 None of them is particularly fond of long lines, so they will throw in the towel when a line exceeds 20K characters (configurable by the user).
